### ISSUE TITLE
Resources undefined in GetProducts

### ISSUE THREAD

**Issue by CJohannimloh93** [dsiekiera/foe-helfer-extension#1]
Hi,

bei einem Spieler bekomme ich beim Plündern einen 'undefined' Type Error zurück.
Dadurch wird mir die Plünderung nicht angezeigt.

Ich versuche mal die Tage heraus zu finden um welches Gebäude es sich dabei handelt.
Evtl bist du dabei schneller.

![image](https://user-images.githubusercontent.com/42354108/57654686-18702f80-75d5-11e9-82ff-43329a2b3242.png)

Grüße
Vain

**Comment by dsiekiera** [comment]
Moni Vain,

bazaar_2 müsste die Ruhmeshalle sein. In deinem Fall mit 15 Kronen.

Den "Erntehelfer" mache ich die Tage eh frisch, dort muss alles was als asset_name bazaar_x heißt gefiltert werden.

**Comment by CJohannimloh93** [comment]
Hab ich mir schon gedacht. 
War nur verwundert da viele andere auch eine Ruhmeshalle stehen hatten.

Evtl waren die ja noch nicht fertig.

**Comment by dsiekiera** [comment]
Da man die sowieso nicht plündern kann, filter ich die weg, dann isses erledigt. Noch Fragen?

**Comment by CJohannimloh93** [comment]
Nein alles tutti!

**Comment by dsiekiera** [comment]
Der Fehler ist in der aktuellen Version 2.2.8 noch enthalten.
