### ISSUE TITLE
WISH: Guild Donations tracking

### ISSUE THREAD

**Issue by masterquinn** [dsiekiera/foe-helfer-extension#1000]
If you go to your guild profile, in the upper left corner the 3 lines button, there is a guild contributions button. it would be nice to just see stats on total contributions by guild members. Many members would appreciate being thanked or recognized for their contributions to GBG or GE lvl 4 and so on.. 

thanks

**Comment by andrgin** [comment]
The guild donations log is very interesting, but unfortunately we only get the data one page at a time, wo you would need to scroll through all 500 pages to get useful data.

**Comment by masterquinn** [comment]
thank you :)
