### ISSUE TITLE
negotiation mistake

### ISSUE THREAD

**Issue by ronintje** [dsiekiera/foe-helfer-extension#1010]
![image](https://user-images.githubusercontent.com/65129679/81506683-758de680-92f8-11ea-884f-6ebd0aee3b3e.png)

Round 3 i'm supposed to try whine, despite there being 3 free spots and already 3 confirmed options for those spots.
I've seen this happen before, but not always.

**Comment by scibuff** [comment]
What wine? The tool is suggesting Dye, Jewelry and Iron, all of which are correct

**Comment by andrgin** [comment]
After round 2 the chance of solving is already 100% so the helper tries to use the cheaper good so jewels and iron are only used once.

**Comment by ronintje** [comment]
Then why not use 3x dye instead ?
At least that would have given a chance of being a required good, in hindsight it even was :D

**Comment by scibuff** [comment]
Because you probably have more of the other goods so the tool determined this was the "cheapest" option leading to 100% solution
