### ISSUE TITLE
PvP Activity need to be changed

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1014]
Hi.

PvP Activity window need to be reworked.
First of all we want to find current opponent in history - this option not implemented.
I have very little battles with neighbours - but even me have 2 pages of VERY big pieces of unneeded info about all battles.
I think that 1-st list of PvP activity must be compact enough - player name, date of battle, win/lost - in single text line. List must be sortable. List must have find option.
When I entered in neighbour city - list must be positioned on string (if it exists) of that neighbour.
When I click on neighbour string - I must receive full info about selected neighbour (as it displayed now).

**Comment by scibuff** [comment]
You can see the next opponent history if you visit the player's city (and open the PvP) but I agree it would be nice to just see that (i.e. without having to visit the city)

**Comment by belikoviv** [comment]
> You can see the next opponent history if you visit the player's city (and open the PvP) but I agree it would be nice to just see that (i.e. without having to visit the city)

You are not right.
I enter neighbour city and open PvP activity. And see total list - not only that neighbour.

**Comment by scibuff** [comment]
I see what you mean. You have the "display all players" filter on. Click on the the name of one of those players and that will switch you to the "single player" mode. Then reload the city ...

**Comment by belikoviv** [comment]
> You have the "display all players" filter on. Click on the the name of one of those players and that will switch you to the "single player" mode. Then reload the city

Thanks a lot!
When I visit city in "single player mode" of PvP activity - history opened with right player.

But anyway list of all players history need to be more compact...

**Comment by andrgin** [comment]
PvP history has been removed: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
