### ISSUE TITLE
Event quest incorrect

### ISSUE THREAD

**Issue by shodbyed** [dsiekiera/foe-helfer-extension#1016]
it seems the event quests are different than what it says are coming up.  i am on the daily quests and it told me the next quest was going to be 15 minute supply runs.  i had these set up to go and when the quest came up it was gain happiness and gather coins.   i also have looked ahead for those supply runs  several times and have yet have it predict those correctly.  if you are going to have the coming quests i hope they are more correct in the future.  as of now i cannot count on what it says is coming. 

i really like your program in its entirety so please keep it going.   thank you

**Comment by andrgin** [comment]
Hat sich denke ich mit dem Ende des Events sowieso erledigt
