### ISSUE TITLE
Bilder für Relikte bei GEX fehlen

### ISSUE THREAD

**Issue by M-Schiller** [dsiekiera/foe-helfer-extension#1020]
Im Deployment der Extension scheinen die Files für Relikte bei der GEX zu fehlen. In meiner Installation gibt es unter `...\js\web\hidden-rewards\images` kein einziges File mit einem `ge_`-Präfix (wie sie laut der Fehlermeldung unten gesucht werden). Das führt zu einem Bild wie im Screenshot unten.

```
chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/js/web/hidden-rewards/images/ge_relic_rare.png:1
GET chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/js/web/hidden-rewards/images/ge_relic_rare.png
net::ERR_FILE_NOT_FOUND
```
![image](https://user-images.githubusercontent.com/11773136/81731947-ffbc8300-948f-11ea-9aa6-4fcfbbf2378c.png)

Metadaten:
```
Windows 10 64-bit (Build 18363)
Google Chrome  64-bit 81.0.4044.138
de8 (Houndsmoor)
2.4.5 - English
```

**Comment by outoftheline** [comment]
hier hat sich über die zeit einiges getan, relikte werden ja nicht mehr angezeigt :D
