### ISSUE TITLE
Plunder FP modification

### ISSUE THREAD

**Issue by TorgardT** [dsiekiera/foe-helfer-extension#1023]
Can you make the FP plunder yellow or gold (and bold). 

Just an easy indication that FP can be plundered - I like the green for Goods.

**Comment by scibuff** [comment]
Or actually sort the list by the amount of FPs (so that the most FPs buildings are on top of the list)?

**Comment by osv** [comment]
I think better to sort by FP amount. Bold font weight are ok for me

**Comment by Vloxxity** [comment]
It also would be a idea to play the notification-soundeffect when there are FP to plunder like that one that appears when there is a GreatBuilding that may be possible to make profit in!

**Comment by andrgin** [comment]
Plundering features have been removed: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
