### ISSUE TITLE
FP-Stock does not diminish

### ISSUE THREAD

**Issue by valimaties** [dsiekiera/foe-helfer-extension#1025]
If you spend some points on research, FP stock does not diminish. You must exit game and enter again to refresh.

Windows 10 x64
Chrome 81.0.4044.138 (Official Build) (64-bit)
Extension version: 2.4.5

**Comment by andrgin** [comment]
Do you mean in the technologies helper or the FP stock in the menu bar?

**Comment by valimaties** [comment]
Also, if one of the Legendary where you put points are closed, the FPStock is increased only if you change world, and came back.
FP Stock in the menu bar @andrgin  .

**Comment by andrgin** [comment]
Oh now I see the problem.

This was caused by the new technology tree and the ability to automatically open forge point packets there. This method is different from auto opening forge point packets when contributing to great buildings.

About getting reward from great buildings: Yes FP stock is not updated when receiving rewards because the notification of rewards is broken in the game with notifications arriving much later than they should.

**Comment by capshort** [comment]
@valimaties There is a shorter workaround for your second problem with incoming rewards from GBs not being counted in FPStock. I've also stumbled upon that problem and noticed that FPStock is recalculated whenever you open someone else's GB while the cost calculator is also opened. I suspect that this works as well with points spent on research but I can't say for sure, haven't researched for quite some time.

**Comment by valimaties** [comment]
> @valimaties There is a shorter workaround for your second problem with incoming rewards from GBs not being counted in FPStock. I've also stumbled upon that problem and noticed that FPStock is recalculated whenever you open someone else's GB while the cost calculator is also opened. I suspect that this works as well with points spent on research but I can't say for sure, haven't researched for quite some time.

Thank you, I will try this one. 👍

**Comment by xLasa** [comment]
@andrgin your right that the GB rewards notification is broken, but the medals are always added directly after it levels, so maybe you can use that.

**Comment by andrgin** [comment]
With the latest change from Inno opening GBs does not send the FP stock any more, same as in research.
We are working on another solution tracking the inventory (similar to the notification when leveling), but it still needs some testing.
