### ISSUE TITLE
Produktionsübersicht Ergänzung

### ISSUE THREAD

**Issue by xLasa** [dsiekiera/foe-helfer-extension#1026]
Hi,
ich hoffe es ist nicht all zu viel Arbeit, aber wäre es möglich die Güterübersicht im Produktionsübersicht-Fenster mit der Gesamtgüterzahl pro Zeitalter zu ergänzen?

Hab da folgend mal ein paar Möglichkeiten wie ich das meine dargestellt:
http://prntscr.com/sg6pfk

Liebe Grüße und danke für eure Arbeit.

**Comment by capshort** [comment]
Ich glaube das ist schon in Planung: #998

**Comment by xLasa** [comment]
Ah stimmt danke!
