### ISSUE TITLE
Calculator Improvement

### ISSUE THREAD

**Issue by fescti** [dsiekiera/foe-helfer-extension#1028]
Hi!
The tool is amazing, but i think it could be better if in Co-paymenta calculator i can choose the % of the calc! In one chat is 90% and its  ok, but in another is 80% and i can't use foehelper to calc point.

For me the best solution is a textbox where i can wrote any kind of number.

**Comment by andrgin** [comment]
You can already change the values in the text fields. The 85 and 90 buttons are just shortcuts for most commonly used values.

**Comment by fescti** [comment]
Yes, i'll attach what i'm asking for
![2020-05-14 09_43_28](https://user-images.githubusercontent.com/65332851/81907165-a0fa2500-95c7-11ea-8dee-c2f7281affd6.png)

**Comment by scibuff** [comment]
Why would you offer slots at your GBs for anything below 90% ?

**Comment by fescti** [comment]
I just start play in a new world, in this one the guild has a chat 80% because a lot of player do not have arc 80.. but it's ok to change the value next to the position.

**Comment by scibuff** [comment]
Well, you should move to a guild with 90% threads. Why pay (a lot) more FPs if you can get them free in another guild

**Comment by andrgin** [comment]
Or at least get 2 guys doing P1+P2 for 1.85. Seriously every player with lvl80 is happy if he can get that easy FP as long as you dont wait forever to get your GBs leveled.

**Comment by outoftheline** [comment]
the calculator % are now customizable
