### ISSUE TITLE
Berechnung für fehlende Diplomatie stimmt nicht

### ISSUE THREAD

**Issue by Blaubaer125** [dsiekiera/foe-helfer-extension#103]
Die Berechnung der fehlenden Diplomatie im Wikingerdorf ist falsch.
Ein Schrein bringt 24 Diplomatie. Es fehlen 354. 354/24= gerundet 15 und nicht 7.

![Neue Bitmap](https://user-images.githubusercontent.com/52349024/65369562-15561180-dc4f-11e9-8e49-ae68cb0c0ca1.jpg)

**Comment by dsiekiera** [comment]
Geprüft und gefixt:

![Bildschirmfoto_2019-09-23_10-10-27](https://user-images.githubusercontent.com/834814/65410355-69e1c400-ddea-11e9-9a64-e868cb56e3df.png)

Gefixt in Version 2.3.9.1
