### ISSUE TITLE
Wish: Notepad/Notes per world

### ISSUE THREAD

**Issue by masterquinn** [dsiekiera/foe-helfer-extension#1035]
I think it would be handy to have a notes area into some sort of a notepad in FOE Helper , and specific to worlds if thats not a bother, otherwise tabs for notes that we can label? trying to track in my world for ARC BP's purchasing the goods for FP and so on and so forth. as it stands now i have 20+ text documents on my desktop, lol.

thanks for looking into it

**Comment by kwhelan1** [comment]
I second this one.

**Comment by whocares1111** [comment]
am on 7 worlds myself and trying to keep track of each world's "todo" list is cumbersome....something in-game would be great.

**Comment by dsiekiera** [comment]
Is still in progress

**Comment by andrgin** [comment]
Released with 2.5.0
