### ISSUE TITLE
Nichtplünderbare Gebäude werden als plünderbar angezeigt.

### ISSUE THREAD

**Issue by private-paula** [dsiekiera/foe-helfer-extension#1036]
Das Belohnungsgbäude "Königliches Badehaus" der Ägypter wird bei Nachbarn als pründerbar angezeigt.
<img width="502" alt="Bildschirmfoto 2020-05-16 um 09 09 13" src="https://user-images.githubusercontent.com/65441099/82113655-f1a08800-9757-11ea-95b0-97a4d6abece2.png">

**Comment by andrgin** [comment]
Ist das Badehaus gerade motiviert?

**Comment by private-paula** [comment]
Da es sich nicht plündern ließ, vermute ich mal, dass es motiviert war.

**Comment by andrgin** [comment]
I think it cannot be plundered at lvl2 or higher.
