### ISSUE TITLE
SQL Fehler bei Tavernenbesuch

### ISSUE THREAD

**Issue by andrgin** [dsiekiera/foe-helfer-extension#1039]
Beitrag aus dem Forum von hhpc1957:

Wenn ich auf Tavernen besuch gehe bekomme ich diese Meldung:
Fataler Fehler: Nicht erfasste ADODB_Exception: mysqli-Fehler: [-9999: Das Eingabearray hat 3 Parameter und stimmt nicht mit der Abfrage überein: ’SELECT DISTINCT YEAR (opse.date_visit) AS Jahr, WEEK (opse.date_visit, 1) AS Spalte FROM other_players_service_de5 as ops LEFT JOIN other_players_service_entries_de5 als opse ON ops.ops_id = opse.ops_id WHERE ops.player_id =? AND ops.is_friend = 1 AND opse.visitor_action = ‘friend_tavern_sat_down’ ORDER BY opse.date_visit DESC LIMIT? '] in Execute (,) in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stapelverfolgung: # 0 / usr / www / Benutzer / foecre / foe-rechner.de / core / Drittanbieter / adodb / adodb.inc.php (786): adodb_throw (‘mysqli’, ‘Execute’, -9999, ‘Eingabearray hat …’, ‘ ’, false, Object (ADODB_mysqli)) # 1 / usr / www / users / foecre / foe-rechner./usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php in Zeile 79

**Comment by andrgin** [comment]
LEFT JOIN other_players_service_entries_de5 als opse

Hier ist doch ein l im "als" zuviel.

**Comment by dsiekiera** [comment]
@andrgin das ist eine Translater-Version einer SQL. Hier das Original:

![Bildschirmfoto 2020-05-18 um 14-07-52](https://user-images.githubusercontent.com/834814/82211363-070ce200-9911-11ea-8073-aa2921ef34ab.png)

Das war der Fehler: "Das Eingabearray hat 3 Parameter und stimmt nicht mit der Abfrage überein"

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2020-05-18 um 14-35-33](https://user-images.githubusercontent.com/834814/82213669-da5ac980-9914-11ea-90d7-3c78f861d2ea.png)

Gefixt
