### ISSUE TITLE
Eigenanteilrechner gibt falsche Werte aus

### ISSUE THREAD

**Issue by 8Merlinako** [dsiekiera/foe-helfer-extension#104]
Habe die Werte für das Cf Stufe 8 kopiert, ausgegeben hat der Rechner die Werte für das Alcatraz in dem ich kurz vorher die Wert kopiert hatte. Allerdings mit dem Lg Name des Cf.

**Comment by dsiekiera** [comment]
Gefixt in der 2.3.9.1
