### ISSUE TITLE
Statistik taucht nicht auf

### ISSUE THREAD

**Issue by moskbnea** [dsiekiera/foe-helfer-extension#1040]
Beim Click auf Statistiksymbol taucht kein Fenster mit Informationen auf. Der Helfer lässt hier keine Aktion zu. Andere Symbole  arbeiten wie erwartet. Die Welt ist egal, es klappt in keiner Welt.

Arch Linux 5.6.13-arch1-1
Google Chrom 56.0.2924.76 (64-bit)
Extension Version 2.4.5 (Deutsch)

Fehlerkopie aus der Console (ob es zu dem Fehler passt oder nicht, kann ich nicht beurteilen):
Uncaught ReferenceError: globalThis is not defined
    at outposts.js?v=2.4.5:629
chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/js/web/plunderer/js/plunderer.js?v=2.4.5:274 Uncaught SyntaxError: Unexpected token ...
chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/js/web/stats/js/stats.js?v=2.4.5:828 Uncaught SyntaxError: Unexpected token ...

**Comment by andrgin** [comment]
Chrome 56 ist über 3 Jahre alte. Den solltest du schleunigst updaten. Dann sollte auch die Extension wieder laufen.

**Comment by moskbnea** [comment]
Danke für den Wink mit dem Zaunpfahl. Ich habe vergessen, dass die Pakete aus AUR nicht automatisch upgedatet werden.

Jetzt funktioniert.
