### ISSUE TITLE
Guild Treasury Contributions

### ISSUE THREAD

**Issue by PompDaddy** [dsiekiera/foe-helfer-extension#1042]
Hello all...
First time I have created a "ticket" here, so I apologize if I am not doing it correctly.  I noticed there were other older tickets that are similar, but they seem to have fallen out of view (#926, #733).

I cannot speak for other guilds, but we have been in desperate need for some sort of "automation" of gathering the guild treasury contribution logs.  On a weekly basis, we are opening all 400-500 pages, and manually typing the donation/cost information into our personal spreadsheets.  This data includes donations from all guild members, their buildings that donate (GBs and special event buildings), GE costs, and GbG costs, etc.,).  I am not familiar with JSON, but I do see the data in the JSON responses (using developer tools>network), as each page is opened.  Obviously, it would help immensely, if there was a way to automatically open all 400-500 pages, capturing all of the data, and then also allowing to export via CSV.  But even if the automated opening of the multiple pages is not an option, it would still be a huge time saver, if as we manually click through all of the pages, your tool could collect all of the data, then allowing for CSV export.

There was a response that said it was not possible to gather other player's information.  But this is not accurate.  The data we are wanting, is already present.  I just do not know how to do the necessary coding to grab the data from the JSON responses, clean it up, and then format it for CSV export.  Any help would be greatly appreciated.

**Comment by scibuff** [comment]
Unfortunately, there's no way to automatically open all pages. The best the cool could do is to gather the data it receives and export that into a CSV (for example). You would still have to go through all the pages however. There's no way around that. 

It is *just* a matter of someone taking the time to write the code.

**Comment by PompDaddy** [comment]
Honestly, even that would be wonderful.  We are already manually opening all the pages.  But the time that it takes to manually type in all of the players names, goods etc., (which usually requires screenshots too - since pages can change without notice), is the real killer.  So if something can be included (maybe with Statistics tab), that once started, will continue to collect as we manually click/open each page, then once finished, we can export a CSV into our personal spreadsheet....  that would save u, seriously, countless hours per week.  Thank you for the response.

**Comment by AlfonZ42** [comment]
I think it should be pointed out, that, apart from the items shifting due to new donations happening at the same time of viewing them, the items themselves are displayed sorted by the datetime but in an unstable way and the following can happen when two GBs are collected at the same time:

page 1:
Arc good 1
Observatory good 1
Arc good 2
Observatory good 2
Arc good 3
--- page break ---
page 2:
Arc good 3
Observatory good 4
Arc good 4
Observatory good 5
Arc good 5

Note the Arc good 3 is listed twice, at the expense of Observatory good 3 missing, due to the order of GBs on second page is reversed.

**Comment by PompDaddy** [comment]
@AlfonZ42 
This is a very point.  But I am confident, that even if this cannot be corrected by code, that we (my guild treasurer and myself) can manually "clean up" duplicates, reconciling by time/date (if included) after CSV is exported to spreadsheet.  We are just looking for any help possible to "replace" manual data entry and save us a huge amount of effort and time each week.

**Comment by PompDaddy** [comment]
Hello all.
Is there any progress on this, or is this ticket currently "shelved"?  If possible, maybe you can provide me with basic coding to parse needed info (while manually changing pages of log).  Something that grabs the user, goods, amount, date-time, type of donation, (and type/amount of cost) etc.... If I can grab needed info and merge/append into a CSV, so that after going through all of the pages manually,  I can export into a spreadsheet....  after which i can easily locate and manually remove any possible duplicates (created by page "shift" due to donation/spending ongoing activities).....  Please, any status update or code help would be greatly appreciated.

**Comment by PompDaddy** [comment]
Hello all.
Unsure why there has been no response since May 26th.  I see plenty of activity on newer tickets.  Can someone please give status update?

**Comment by outoftheline** [comment]
There are currently over 200 open issues labeled as wish for the extension.
As this is a hobby project the devs can basically do whatever they feel like doing, so please be patient. There are ideas floating around on how to tackle this wish, but nothing specific yet.

Also, your request is not easy to fulfill as AlfonZ stated above.

**Comment by andrgin** [comment]
Planned for next update

**Comment by PompDaddy** [comment]
To any and all that worked on this...

Just wanted to spend a minute to tell you all thank you so very much.....  This is perfect.  Exactly what we needed.  I will be modifying our guild treasury spreadsheet (formulas etc), to accommodate this new CSV import.  Again.  Thank you so very much.  Once I get back to working in IT (pandemic job loss), I will donate money to you guys.
