### ISSUE TITLE
Guild Battlegrounds- conquering player name

### ISSUE THREAD

**Issue by MikeonhisBike** [dsiekiera/foe-helfer-extension#1043]
can you show the players name from Guild that conquers a sector? We have members who attack and take sectors even with stop sign up- we would like to see who it is and try and educate them. it might already exist- the info tool didn't show players, just sector and time... really need to know who is hitting, or even just last person who conquered the sector.
Thanks

**Comment by scibuff** [comment]
No. The data is not available. Please see https://github.com/dsiekiera/foe-helfer-extension/issues/860

**Comment by osv** [comment]
The only one way for now I'm using is checking grow of scores of players twise in short period time.
![grow](https://user-images.githubusercontent.com/213405/82207569-b5655700-9912-11ea-8c66-fe4a0c388c33.jpg)
This is not perfect way, but still allow you to know who is attacking right now
