### ISSUE TITLE
Problem bei der Städteansicht

### ISSUE THREAD

**Issue by b-tomasz** [dsiekiera/foe-helfer-extension#1045]
1) Wenn ich in der Stadtansicht die Ansicht oder den Zoom ändere, verändert dies bei mir überhaupt nichts.
2) Die Städteansicht aktualisiert sich nur wenn die Seite neu geladen wird. Es wäre schön wenn sich dieses automatisch updated, sobald ein gebäude gebaut/vesetzt wird. (Weiss nicht ob dies technisch überhaupt möglich ist)

Mein System:
Windows 10 64 Bit
Firefox 76.0.1
de19 (Tuulech)
2.4.5 - Deutsch

**Comment by andrgin** [comment]
Punkt 1 istbereits bekannt und wird mit dem nächsten Update gefixed.

Punkt2: Technisch möglich wäre es scho, nur etwas aufwändiger. Es gibt aber mit demnächsten Update zumindest einRefresh wenn man zwischen Außenposten bzw. Mars und der eigenen Stadt wechselt.

**Comment by b-tomasz** [comment]
Perfekt!
