### ISSUE TITLE
language parameter not working (firefox)

### ISSUE THREAD

**Issue by boeffie** [dsiekiera/foe-helfer-extension#1053]
I installed foehelper for firefox a few months ago, had no problems changing the language (it is in french atm) or the length of the helper-bar.

Then on one world the language or length could not be adapted.

Today I uninstalled foehelper, and re-downloaded it, now I can't adjust the language or length anywhere at all.
It comes with a pop-up saying I don't use the html5 version, which is not true either.

Please can you help?

**Comment by andrgin** [comment]
This is a known problem. Will be fixed in the next update
