### ISSUE TITLE
Plünderbare Produktionen beim Nachbarn werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by CaptainAra** [dsiekiera/foe-helfer-extension#1058]
Hallo :-)

Erstmal vorweg: ich liebe den FOE-Helper! Wirklich ganz toll :-) Herzlichen Dank dafür!

Leider funktioniert seit einiger Zeit die Anzeige der plünderbaren Produktionen meiner Nachbarn nicht mehr. Wenn ich in einer Spielesession erstmals auf einen Nachbarn klicke, wird mir in seiner Stadt sehr, sehr kurz die Liste angezeigt, verschwindet dann aber unwiderruflich. Bei allen weiteren Nachbarn taucht die Liste dann gar nicht mehr auf. Ich habe gesehen, dass auch andere Spieler dieses Problem haben, allerdings gab es keine Antwort im Forum, weshalb ich es hier noch einmal selbst probiere.

Das Problem taucht sowohl bei Chrome als auch bei Firefox auf. Vor zwei Wochen oder so ging das noch problemlos.

Ich würde mich freuen, wenn du da mal einen Blick drauf werfen könntest :-)

Vielen Dank und viele Grüße!
Captain Ara

Windows 7 64 Bit
Chrome 83.0.4103.61 (64-Bit) und Firefox 72.0.2 (64-Bit)
en13 (Noarsil)
Aktuelle deutsche Version

**Comment by andrgin** [comment]
Das Problem scheintzu sein, dass sich die Fenster irgendwo hin verschieben aber wir konnten bisher noch nicht herausfinden wieso.
Das kurze Aufblinken beim ersten Mal liegt daran, dass er beim 1. Öffnen beim Laden etwas länger braucht bis er die Formatierungen verarbeitet.

Hast du zufällig in letzter Zeit deinen Monitor oder die Auflösung gewechselt?
In welcher Auflösung spielst du aktuell das Spiel?

**Comment by andrgin** [comment]
Achja kannst du unter Chrome die Entwicklerkonsole öffnen (F12) und in den Tab Application gehen? Danach links im Baum auf Storage -> Local Storage -> die UrL der Seite auswählen

Danach in der Suche nach "ResultBoxCords" suchen.

Was steht da beim Wert drin?

**Comment by CaptainAra** [comment]
Vielen Dank für deine schnelle Antwort :-)

 

Ich habe in der Tat vor Kurzem den Monitor gewechselt (von normalem Laptopbildschirm auf externen Widescreen mit entsprechender Auflösung). Da hatte ich aber zunächst keinerlei Probleme mit. Das Problem tauchte dann urplötzlich zwischendrin auf.

Der Wert, nach dem du gefragt hast, ist Folgender: 116.22222900390625|498

 

Aber weißt du was? Seitdem ich deine Schritte befolgt habe, um an den Wert zu kommen, wird mir das Fenster wieder korrekt angezeigt! Beim ersten Nachbarn noch etwas nach unten verrutscht, beim Nächsten dann ganz normal. Auch ein Neustart des Browsers hat daran nichts geändert. Weiß der Teufel, warum... Hoffentlich bleibt das so :-)

 

In Firefox bleibt das Problem aber bestehen.

Seltsame Geschichte.

 

Ich hoffe, dass du mit meinen Infos etwas anfangen kannst! 
Vielen Dank, dass du dich darum kümmerst :-) Ich lass gleich mal eine Paypalspende da :-)

 

LG Heiko

 

 

 
 

Gesendet: Freitag, 22. Mai 2020 um 21:16 Uhr
Von: "Gindi4711" <notifications@github.com>
An: "dsiekiera/foe-helfer-extension" <foe-helfer-extension@noreply.github.com>
Cc: "CaptainAra" <heiko.behrens@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Plünderbare Produktionen beim Nachbarn werden nicht mehr angezeigt (#1058)


 

Achja kannst du unter Chrome die Entwicklerkonsole öffnen (F12) und in den Tab Application gehen? Danach links im Baum auf Storage -> Local Storage -> die UrL der Seite auswählen

Danach in der Suche nach "ResultBoxCords" suchen.

Was steht da beim Wert drin?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.





 

Gesendet: Freitag, 22. Mai 2020 um 21:16 Uhr
Von: "Gindi4711" <notifications@github.com>
An: "dsiekiera/foe-helfer-extension" <foe-helfer-extension@noreply.github.com>
Cc: "CaptainAra" <heiko.behrens@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Plünderbare Produktionen beim Nachbarn werden nicht mehr angezeigt (#1058)


 

Achja kannst du unter Chrome die Entwicklerkonsole öffnen (F12) und in den Tab Application gehen? Danach links im Baum auf Storage -> Local Storage -> die UrL der Seite auswählen

Danach in der Suche nach "ResultBoxCords" suchen.

Was steht da beim Wert drin?

**Comment by CaptainAra** [comment]
Hallo, ich noch mal :-)

 

Ich habe jetzt herausgefunden, was genau passiert. Es liegt definitiv an der Auflösung. Wenn ich das Spiel im Vollbildmodus mit meinem Widescreen-Bildschirm spiele, verschwindet die Box leider wieder. Es war keine dauerhafte Besserung. Wenn ich das Browserfenster dann aber schmaler mache, kommt die Box zurück, und zwar von unten. Je breiter ich es ziehe, desto weiter nach unten wandert die Box wieder.

 

Vielleicht ist das für dich ja noch eine hilfreiche Information: Die Box verschwindet also nach unten.

 

LG Heiko

 

Gesendet: Freitag, 22. Mai 2020 um 21:16 Uhr
Von: "Gindi4711" <notifications@github.com>
An: "dsiekiera/foe-helfer-extension" <foe-helfer-extension@noreply.github.com>
Cc: "CaptainAra" <heiko.behrens@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Plünderbare Produktionen beim Nachbarn werden nicht mehr angezeigt (#1058)


 

Achja kannst du unter Chrome die Entwicklerkonsole öffnen (F12) und in den Tab Application gehen? Danach links im Baum auf Storage -> Local Storage -> die UrL der Seite auswählen

Danach in der Suche nach "ResultBoxCords" suchen.

Was steht da beim Wert drin?

**Comment by andrgin** [comment]
Danke genau das war die Lösung. Die Default Position der Box war sowohl in X als auch in Y Richtung von der Breite des Fensters abhängig, was dazu führt, dass sie bei Monitoren, die breiter als 18:9 sind raus geschoben wird.

Wird mit dem nächsten Update gefixed
