### ISSUE TITLE
[BUG UI] Platzbelegung Kopierfenster in der Sprache Englisch zu klein

### ISSUE THREAD

**Issue by yyoshii** [dsiekiera/foe-helfer-extension#106]
In Englischer Sprache ist das Fenster zum kopieren zu klein und der Button zum kopieren ist nicht sichtbar. Mann muss dafür nach unten scrollen:

![2019-09-26_15h25_51](https://user-images.githubusercontent.com/11097888/65692096-4c269000-e072-11e9-9f52-3abcf1b9a970.png)

![2019-09-26_15h30_00](https://user-images.githubusercontent.com/11097888/65692325-a32c6500-e072-11e9-8350-c6af5be58381.png)

**Comment by yyoshii** [comment]
In Deutscher Sprache ist es richtig
![2019-09-26_16h03_22](https://user-images.githubusercontent.com/11097888/65695142-41222e80-e077-11e9-857e-cac70bb55225.png)

**Comment by dsiekiera** [comment]
Ist in der Version 2.3.10 gefixt.
