### ISSUE TITLE
Addon Sprache immer in Englisch

### ISSUE THREAD

**Issue by yyoshii** [dsiekiera/foe-helfer-extension#107]
Hallo,

ich habe Googlechrome in Englischersprache installiert und darauf ein Sprachpaket in Deutsch.
Deutsch ist als Standard gewählt.
FOE ist in Deutschersprache eingestellt.

Das Addon wird mir jedoch nur in Englisch angezeigt. Ich habe bereits den Cache geleert, jedoch habe ich das Addon weiterhin nicht in Deutschersprache.

Wodran kann dies liegen?
Gibt es eine Möglichkeit das Addon manuell auf eine spezifische Sprache um zu stellen?

Mit freundlichen Grüßen
Yyoshii

**Comment by dsiekiera** [comment]
Hey yyoshii,

Die Extension zieht sich die Sprache die in den Einstellungen ganz oben
steht. Das ist dann nämlich die Standardsprache.
Deshalb gibt es auch den Punkt "ganz nach oben" o.ä. zum einstellen.

Aber du hast prinzipiell recht. Ich werde noch einen extra Button verbauen
der das dann extra noch mal überschreibt.

PS: Es gibt den Chrome nicht in Englisch oder anderen Sprachen. Sondern
immer in der Sprache die Standard ist und in der Sprache Übersicht ganz
oben steht.

yyoshii <notifications@github.com> schrieb am Do., 26. Sep. 2019, 15:37:

**Comment by yyoshii** [comment]
Okay, danke es klappt nun.
Ich bin davon ausgegangen, dass die Standard Sprache des Chrome-UI genutzt wird ;-)

![2019-09-26_15h58_39](https://user-images.githubusercontent.com/11097888/65694942-ee487700-e076-11e9-9e08-14e8f458e164.png)

Deutsch in der Reihenfolge als erstes geändert:
![2019-09-26_15h58_53](https://user-images.githubusercontent.com/11097888/65694941-ee487700-e076-11e9-9f09-ef6be0da385f.png)

**Comment by dsiekiera** [comment]
Ich werd des noch mal überprüfen ob die Chrome API das hergibt und ggf ergänzen.

Den Schalter mach ich dennoch rein.

**Comment by dsiekiera** [comment]
Abfrage auf Chrome GUI ersetzt.
