### ISSUE TITLE
Suggestion: Allow sorting on the Production Overview tabs

### ISSUE THREAD

**Issue by FoEHats** [dsiekiera/foe-helfer-extension#1074]
It would be very useful to be able to sort the data in the Production Overview (all tabs) by time left (low to high) to be able to determine when I need to log on to collect next. 
It would also be able to sort back alphabetically but if that it a problem it can be accomplished bey closing and reopening the window.

**Comment by dsiekiera** [comment]
U mean the last Tab?

**Comment by FoEHats** [comment]
That would work.  Everything is there.  Thanks.
