### ISSUE TITLE
Known issue: FP Stock shows 0

### ISSUE THREAD

**Issue by DouglasMilnes** [dsiekiera/foe-helfer-extension#1075]
On three worlds I play, the FP Stock at the top of the screen is displaying zero. It was working until the last update.

Betriebssystem / Operating System
Linux Debian

Verwendeter Browser inkl. Versionsnummer / Used Browser including version
Google Chrome | 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
JavaScript | V8 8.1.307.32
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

Forge of Empires Server
EN1, EN3, EN13

Extension Version und Sprache der Extension
2.4.6 - English

Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole" wechseln) / Errors in the console (press F12 and switch to console tab)
None

**Comment by scibuff** [comment]
Thank you. We are aware of the bug. It's been already reported #1044 and #1059

**Comment by MalcolmLK** [comment]
The FP count appears when you open the city, but when you open a GB it goes away and doesn't come back until you reopen (reload) the city.

**Comment by scibuff** [comment]
This is now fixed in Beta and will be in the next release
