### ISSUE TITLE
Integration of CityPlanner does not work in Firefox

### ISSUE THREAD

**Issue by WeisserStein** [dsiekiera/foe-helfer-extension#1076]
The Button for uploading the data does not appear in the window of the city map

**Comment by dsiekiera** [comment]
Du hast die aktuelle Version? 2.4.6?

**Comment by WeisserStein** [comment]
Wo kann ich die nachsehen?

**Comment by dsiekiera** [comment]
Da:

![Bildschirmfoto 2020-05-25 um 22-40-28](https://user-images.githubusercontent.com/834814/82842156-c72d9800-9ed8-11ea-8424-2299cea907a6.png)

**Comment by WeisserStein** [comment]
Das habe ich zwar auch nicht gefunden, aber bei den Einstellung der add-ons die Einstellungen. Update und Restart, jetzt funktioniert es. Danke! Habe schon viel gutes darüber gehört und es sind alle ganz begeistert, dass man die Daten jetzt wieder hochladen kann! Bin schon sehr gespannt!

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2020-05-25 um 22-49-57](https://user-images.githubusercontent.com/834814/82842502-158f6680-9eda-11ea-8a1a-ddfcd1e384c9.png)

Das wäre aber der entgültige Weg ;-)

**Comment by WeisserStein** [comment]
so, jetzt habe ich auch das Login geschafft.
Bei mir und bei anderen Spielern werden in der Darstellung die obersten Felder abgeschnitten leider.

**Comment by WeisserStein** [comment]
![grafik](https://user-images.githubusercontent.com/65923065/82843438-6785bb80-9edd-11ea-9311-2241b60bada5.png)

**Comment by dsiekiera** [comment]
Das bekomme ich Morgen noch hin.

**Comment by WeisserStein** [comment]
.png ist immerhin komplett, aber auch nach oben verschoben:
![grafik](https://user-images.githubusercontent.com/65923065/82843572-d19e6080-9edd-11ea-9225-4a8a2d17dd81.png)

**Comment by WeisserStein** [comment]
und pdf sieht genauso aus.

**Comment by WeisserStein** [comment]
Ganz vielen herzlichen Dank, ist ein phantastisches Teil, und dass du hier sofort antwortest und hilfst finde ich einfach großartig!!!

**Comment by dsiekiera** [comment]
Dafür sind wir da ;-) Oben links das Suchfeld is Kacke. Das muss noch weg.

**Comment by WeisserStein** [comment]
Das ging ja flott, ist schon weg. Kacke ist gar nix, höchstens unfertig 😉

**Comment by WeisserStein** [comment]
Integration vom Luftschiff klappt übrigens auch problemlos, da gab es heut nachmittag noch Probleme. Ihr seid ja unglaublich schnell!

**Comment by dsiekiera** [comment]
So. Ansicht behoben. Oben ist nun auch etwas mehr Platz und die FIlterbox wird beim rendern ausgeblendet.

**Comment by WeisserStein** [comment]
Perfekt, danke!

**Comment by WeisserStein** [comment]
Seid Ihr auch die Ansprechpartner für den foe-Rechner, oder "nur" für den for-Helper?

**Comment by dsiekiera** [comment]
Die gehören beide zusammen. Wenn dort aber etwas nicht geht, bitte ein neues Ticket öffnen.

**Comment by WeisserStein** [comment]
Die Übertragung der Daten, die gestern funktioniert hat, bleibt heute leider hängen:
![grafik](https://user-images.githubusercontent.com/65923065/82924435-9e5ede80-9f7c-11ea-9688-7bb68a517976.png)

**Comment by WeisserStein** [comment]
Und im City Planer sind alle Gebäude, die ich verändert habe, nach dem Abspeichern um zwei Kästchen nach unten verrutscht. 
![grafik](https://user-images.githubusercontent.com/65923065/82924651-ec73e200-9f7c-11ea-94b2-f40a4642dba9.png)
Das war mir beim Bauen schon aufgefallen: wenn ich Gebäude aus dem Zwischenlager links wieder in die Karte einbauen wollte, erschienen sie zwei Kästchen unterhalb des Mauszeigers.
