### ISSUE TITLE
Same unit appears more than once in the GE reward stats pie chart

### ISSUE THREAD

**Issue by Minotorious** [dsiekiera/foe-helfer-extension#1077]
As the title says, see screenshot below: 
![GE_Stats_Bug](https://user-images.githubusercontent.com/40427380/82846227-15966300-9ee8-11ea-8cb6-47af0859c423.PNG)

**Comment by osv** [comment]
Can you give me  your rewards list? 
- Open dev console,
- type `copy(await IndexDB.db.statsRewards.toArray())` 
- paste to txt file and attach here or upload somewhere

**Comment by Minotorious** [comment]
Here you go :)
[GBRewardsList.txt](https://github.com/dsiekiera/foe-helfer-extension/files/4679071/GBRewardsList.txt)

**Comment by osv** [comment]
cannot find smtg wrong.. can you also give me reward info list 
`await IndexDB.db.statsRewardTypes.toArray()`

**Comment by Minotorious** [comment]
[RewardTypes.log](https://github.com/dsiekiera/foe-helfer-extension/files/4681436/RewardTypes.log)

**Comment by osv** [comment]
ok, it seems inno games uses 2 different types for unit in guild expedition rewards.
e.g `unit_short_ranged5`, `unit_short_ranged_special5`. 
can you run one more time for me :)
`copy(await IndexDB.db.statsRewardTypes.toArray())`

I will add your data to my db for testing fix

**Comment by Minotorious** [comment]
[statsRewardTypes.log](https://github.com/dsiekiera/foe-helfer-extension/files/4681820/statsRewardTypes.log)

here you go :)

**Comment by osv** [comment]
thanks
