### ISSUE TITLE
FoE-Rechner Statistiken > Mitglieder > Button: "aus Gilde entfernen"

### ISSUE THREAD

**Issue by WeisserStein** [dsiekiera/foe-helfer-extension#1078]
in der Statistik Mitglieder taucht neben den Gildenmitgliedern der Button "aus Gilde entfernen" auf. Ich gehe mal davon aus, dass wir die Rechte dazu nicht haben, ausprobieren wollte ich es aber lieber nicht... Dann sollte der Button aber aus dieser Ansicht rausgenommen werden.

**Comment by andrgin** [comment]
Der Button ist dazu da, dass man alte Spieler, die nicht mehr in der Gilde sind aus der Statistik entfernen kann.
Und nein man kann natürlich niemanden so aus der Gilde im Spiel werfen.
