### ISSUE TITLE
Info Box - Level-Up zeigt falsche FP Anzahl

### ISSUE THREAD

**Issue by dorsig** [dsiekiera/foe-helfer-extension#1080]
![2020-05-26 17_18_51-Forge of Empires - Firefox Developer Edition](https://user-images.githubusercontent.com/40668027/82918926-a7987d00-9f75-11ea-8cde-3f4e16d93047.png)

P1 auf Lvl 1 bringt nur 19 FP

Windows 10 64 Bit
Firefox Developer Edition 77.0b9 (64-Bit)
de9 (Jaims)
2.4.6 - Deutsch

**Comment by AlfonZ42** [comment]
Yes, I encountered it as well.
I think it displays the sum of all FP packages you got since either the startup or previous GB level-up message (even from recurring quests and such) and not only from that specific GB level-up reward.

**Comment by scibuff** [comment]
It is more complicated than that ... it is somewhat related to #1044 and #1059 which should be fixed shortly

**Comment by scibuff** [comment]
This is now fixed in Beta and will be in the next release
