### ISSUE TITLE
Upload der Stadt-Daten für den City Planner bleibt hängen

### ISSUE THREAD

**Issue by WeisserStein** [dsiekiera/foe-helfer-extension#1082]
Nachdem ich gestern die Daten erfolgreich hochgeladen habe, bleibe ich heute an dieser Box hängen: 
![grafik](https://user-images.githubusercontent.com/65923065/82925601-37422980-9f7e-11ea-8109-a6f986415736.png)

**Comment by WeisserStein** [comment]
Ein Gildenkollege berichtet dasselbe Problem.

**Comment by dsiekiera** [comment]
Schau ich mir gleich an.

**Comment by SaitaXFoE** [comment]
Habe auch das Problem

**Comment by dsiekiera** [comment]
Is fixed
