### ISSUE TITLE
Stadtplaner

### ISSUE THREAD

**Issue by Silke67** [dsiekiera/foe-helfer-extension#1084]
Hallo,
vielen Dank für dieses Tool.
Ich habe allerdings das Problem in einer Version, dass nach Speicherung die Gebäude um 2 Felder nach unten verschoben werden.
In der 2. Version die ich angefangen habe, finde ich das Rathaus nicht mehr, auch nicht über die Gebäudesuche?
Über einen Tipp wäre ich dankbar.
LG Silke

**Comment by WeisserStein** [comment]
doppelt  #1081

**Comment by dsiekiera** [comment]
Ist seit vorhin behoben.
