### ISSUE TITLE
Stadtplaner - Abschicken Butten funktioniert nicht

### ISSUE THREAD

**Issue by Der-Viking-1983** [dsiekiera/foe-helfer-extension#1085]
Hallo,

 ich habe nach der Anleitung mir einen Account bei FOE-Rechner eingerichtet und das Plug-In auf Chrome geupdatet. Wenn ich nun also die Stadtübersicht öffne und die Übermittlungsbox anzeigen lasse funktioniert der Abschicken Button nicht und übermittelt nicht. Danke

**Comment by WeisserStein** [comment]
doppelt #1082

**Comment by dsiekiera** [comment]
Is fixed
