### ISSUE TITLE
Forge points

### ISSUE THREAD

**Issue by SillyDevil** [dsiekiera/foe-helfer-extension#1089]
after the latest uptdate, my forge points total in the stack is shown zero, after I refresh, I can see the amount on the top bar for sometime, then it again becomes zero
![Screenshot_1](https://user-images.githubusercontent.com/65982368/82953799-b863e580-9fab-11ea-8e20-63f688ba1ed8.png)

**Comment by andrgin** [comment]
Yes already working on it

**Comment by Etwass** [comment]
It becomes zero after opening GB window. After refresh page or use your FP, right FP returns.
