### ISSUE TITLE
Münzboost für LGs

### ISSUE THREAD

**Issue by Kijaho** [dsiekiera/foe-helfer-extension#109]
![LGboost](https://user-images.githubusercontent.com/55881128/65767741-0ed40800-e12f-11e9-928e-2e42869a4560.PNG)

Aktuell wird in der Produktionsübersicht der Boost vom Markusdom auch auf die Münzproduktion der LGs aufgerechnet, obwohl das im Spiel nicht der Fall ist.

**Comment by dsiekiera** [comment]
OK. Macht Sinn. Ändere ich.

Wieso hast du ein englisches Datum?

Sind das Nachkommastellen bei CF?

Kijaho <notifications@github.com> schrieb am Fr., 27. Sep. 2019, 14:01:

**Comment by Julian2424** [comment]
Habe ich auch.
Datum ist bei mir auch englisch, da sind auch Nachkommastellen und scheinbar wird der Bonus auch nicht richtig berrechnet. Es wird dort weniger angezeigt, als ich wirklich habe.
![Screenshot_94](https://user-images.githubusercontent.com/50926918/65777753-ebb45300-e144-11e9-9200-252984b5a84a.png)

**Comment by dsiekiera** [comment]
Der Bonus wurde immer in allen Tests korrekt berechnet. Ich schau mir das noch mal an.

Sind eure Spracheinstellungen auch so wie meine?
![Bildschirmfoto 2019-09-27 um 16-49-51](https://user-images.githubusercontent.com/834814/65779026-43ec5480-e147-11e9-9408-5a2bdbaf5f9d.png)

**Comment by Julian2424** [comment]
So sieht es bei mir aus.
![Screenshot_95](https://user-images.githubusercontent.com/50926918/65779252-bcebac00-e147-11e9-8dbb-5a49bcd612c8.png)

**Comment by Julian2424** [comment]
Mir fehlen genau 20%. Das sind meine aktuellen Boni:
![Screenshot_96](https://user-images.githubusercontent.com/50926918/65779953-07b9f380-e149-11e9-9611-ba0d2f34137b.png)
![Screenshot_97](https://user-images.githubusercontent.com/50926918/65779954-07b9f380-e149-11e9-9423-bc89f09812ed.png)

**Comment by dsiekiera** [comment]
Vorräte fallen da nicht rein. Der Bonus gilt immer erst dann, wenn das Gebäude gerntet wird. Deshalb kann man nicht pauschal alles hochrechnen.

**Comment by dsiekiera** [comment]
@Julian2424 verschieb mal das Deutsch mit der grünen Schrift ganz nach oben.

**Comment by Julian2424** [comment]
> Vorräte fallen da nicht rein. Der Bonus gilt immer erst dann, wenn das Gebäude gerntet wird. Deshalb kann man nicht pauschal alles hochrechnen.
Kannst du da nicht den eigenen Bonus rauslesen und in der Erweiterung selbst berechnen lassen?


> @Julian2424 verschieb mal das Deutsch mit der grünen Schrift ganz nach oben.

Habe ich gemacht und neugestartet. Ist immer noch englisch.

**Comment by dsiekiera** [comment]
> Kannst du da nicht den eigenen Bonus rauslesen und in der Erweiterung selbst berechnen lassen?
Das mach ich ja. Keine Ahnung wo du die fehlenden 20% her zauberst.
Hab gerade mal geschaut. Bei mir stimmt es immer noch

**Comment by dsiekiera** [comment]
Guckst Du:
![Bildschirmfoto_2019-09-27_19-30-03](https://user-images.githubusercontent.com/834814/65789352-87ea5400-e15d-11e9-86f7-8c432d5a35f5.png)

**Comment by dsiekiera** [comment]
PS: An der Sprache hab ich noch mal gefeilt. Müsste in der nächsten Version dann stimmen.
