### ISSUE TITLE
Incident overview

### ISSUE THREAD

**Issue by Columbus69fu** [dsiekiera/foe-helfer-extension#1093]
If you look at the attachment for the incident overview it is showing that there a three incidents on 2 lane roads; look at my city and there are no two lane roads. Your program has a problem.
![helper](https://user-images.githubusercontent.com/66002280/82993843-5a8bd800-a055-11ea-9d58-a7071536c6c5.PNG)

**Comment by dsiekiera** [comment]
No. It hasn't.

Inno sends this data. A player in the Ironage also can pick up the two lane incidents, if there where this street.

This is a Inno Bug. They ever sends this Informations.

Build a part of this street for the chance two pick up or let it be.

**Comment by andrgin** [comment]
Build a 2 lane road an reload the game. You should now be able to collect the incident.

**Comment by Th3C0D3R** [comment]
Also, you are using an old Version. Please update to get continuous support 😉

**Comment by andrgin** [comment]
This ticcket is 2 months old ;-)

**Comment by Th3C0D3R** [comment]
Oh 😅
