### ISSUE TITLE
Foe Helper for Opera

### ISSUE THREAD

**Issue by Dlonrab** [dsiekiera/foe-helfer-extension#1096]
I noticed that Opera is nearly identical to Chrome. Is worth a try to look if Foe Helper can be easily adapted to Opera also?

**Comment by dsiekiera** [comment]
[https://foe-rechner.de/docs/2/introduction/#opera](https://foe-rechner.de/docs/2/introduction/#opera)

**Comment by outoftheline** [comment]
Opera ist supported as stated above :) 
Closing this.
