### ISSUE TITLE
Fehler bei der Berechnung der FP im Lager

### ISSUE THREAD

**Issue by dirk-der-ripper** [dsiekiera/foe-helfer-extension#1098]
Hallo,
es hat sich ein Fehler eingeschlichen in der Anzeige "FP im Lager".
Er tritt dann auf, sobald ich den Kostenrechner aktiviere und ein LG von einem Nachbarn öffne.
In dem Moment springt die Anzeige auf "0" und auch im Kostenrechner wird die mögliche Anzahl an einzahlbaren FP in roter Schrift angezeigt. Was ja bedeutet das zu wenig FP im Lager sind.

**Comment by dsiekiera** [comment]
Duplicate of #1089
