### ISSUE TITLE
Waren in Japanersiedlung werden nicht erkannt

### ISSUE THREAD

**Issue by Blackfir5** [dsiekiera/foe-helfer-extension#110]
Die vorhandenen Waren werden in der Güterübersicht, seit dem letzten update, nicht mehr angezeigt.

![Japanerwarenbug](https://user-images.githubusercontent.com/55910235/65813299-cd496880-e1d3-11e9-9bdc-fdf5b269fdd3.JPG)

**Comment by courseofra** [comment]
Kann ich bestätigen.

**Comment by Blackfir5** [comment]
Also bei mir ist es jetzt schon ca. 5 Tage so. Oft neu geladen, cache gelöscht, im Rathaus war ich auch...
Auf einer Welt bekomm ich nur das leere Fenster (1 Zeile) und nicht mal die Aufstellung wie oben.

**Comment by Blackfir5** [comment]
Ahoi.
So, vor 2 Tagen eine neue Siedlung angefangen, heute früh den Händler frei geschalten (Unterwegs via App), jetzt zeigt die Güterübersicht wieder richtig an...
Hab aber täglich rein geschaut, hat bis heute nicht funktioniert, update-Nachricht kam auch nicht. Komisch....
