### ISSUE TITLE
Die "länge" geht nicht

### ISSUE THREAD

**Issue by Chris1887x** [dsiekiera/foe-helfer-extension#1104]
Moin, wenn ich beim FOE Helper die Menü länge ändern will, nimmt er es nicht an.. habe den FOE Rechner schon neu installiert aber es bleibt bei der Standard Größe.. 

Wie kann ich das beheben?

Hoffe es war kurz, knapp und verständlich aufgeführt. ^^

VG
Chris

**Comment by andrgin** [comment]
Kannst du bitte die Bug Report Vorlage verwenden: https://github.com/dsiekiera/foe-helfer-extension/issues/620

**Comment by Chris1887x** [comment]
Windows 10 64 Bit
Chrome Version 83.0.4103.61 (Offizieller Build) (64-Bit)
de18 (Sinerania)
2.4.6 – Deutsch 

Konsole Fehler?!
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.


DevTools failed to load SourceMap: Could not load content for chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/vendor/dexie/dexie.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by andrgin** [comment]
Ich kann das leider bei mir nicht reproduzieren. Mit der 2.4.5er Version gab es einen Bug aber ab der 2.4.6er sollte es eigentlich wieder gehen.
