### ISSUE TITLE
Kostenrechner - safe, oder nicht?

### ISSUE THREAD

**Issue by Blackfir5** [dsiekiera/foe-helfer-extension#111]
Hat man schon was eingezahlt, zeigt der Kostenrechner nicht mehr an, wieviel man braucht, bis man safe ist. Mit 1FP zeigt er 75FP Gewinn an, da werde ich aber sicher überboten...

![nichtsafe](https://user-images.githubusercontent.com/55910235/65813419-4b5a3f00-e1d5-11e9-9dc6-97a9275d2aee.JPG)

**Comment by SkateScout** [comment]
Ein weiterer Fehler:
180 Besitzer
P1 Belegt mit 1FP
Rechner sagt Safe mit 11FP
Richtig wäre aber 10FP da dann noch 10 offen sind und 1+9 würde bereits Leveln.

**Comment by dsiekiera** [comment]
> Hat man schon was eingezahlt, zeigt der Kostenrechner nicht mehr an, wieviel man braucht, bis man safe ist. Mit 1FP zeigt er 75FP Gewinn an, da werde ich aber sicher überboten...

Das kann man auch nicht wirklich ändern außer man würde seinen eigenen Browser mit Diesen Daten voll müllen. Es müsste für dieses 1FP Vormerken, was ich z.B. nie mache da ich nur einzahle wenn es auch was bringt, immer ein Datensatz irgend wo angelegt werden. Und das ist nicht vorgesehen.

Ich will mal irgend wann eine eigene Funktion dafür schreiben, hat aber derzeit überhaupt keine Prio.

**Comment by Blackfir5** [comment]
Das mit dem 1FP war nur als Beispiel.
In der Regel läuft es ja so, dass ich bis zur 200FP schleife einzahle, die Quest abschließe und dann wieder 200FP rein gebe, bis ich eben die fertigen 1,9 drinn hab. Dann weiß ich aber nicht, ab wann ich wirklich safe bin. Bei LB's die in der "heißen Phase" sind, würd ich ja bis zu safe schnell machen, dann ev. mit ernte füllen...
Ich erinnere mich, dass die Zahl ganz am Anfang immer stehen blieb und sich das verhalten mit irgend einem update geändert hat (hab dir damals direkt ne e-Mail geschickt gehabt), wo dann nur noch das bereits eingezahlte angezeigt wurde.
Meiner Meinung nach muß in der Erweiterung der eingezahlte Betrag nicht angezeigt werden, den seh ich ja auch direkt im Spiel. Es wäre besser, so wie es am Anfang war, wenn hier wirklich die für Safe benötigten FP immer stehen bleiben würden.

**Comment by SkateScout** [comment]
Wenn das gebäude geladen wird kommt doch eine Liste mit dem Investoren an. Darin ist auch Vermerkt was man eingezahlt hat. Darüber könnte doch ohne Zwischenspeicher die Restsumme bis Safe bestimmt werden.

**Comment by SkateScout** [comment]
Da der eigene Beitrag ja auch Blau Markiert ist und der Betrag angezeigt wird sollten die Daten doch Bereits vorhanden sein.

**Comment by dsiekiera** [comment]
So Männers.

Hab das mal was zusammen gefummelt:

![Bildschirmfoto 2019-10-09 um 21-47-15](https://user-images.githubusercontent.com/834814/66514964-764e6800-eade-11e9-9fae-d97fee24b348.png)
![Bildschirmfoto 2019-10-09 um 21-47-43](https://user-images.githubusercontent.com/834814/66514965-76e6fe80-eade-11e9-9444-3f5a9330eb14.png)

Die beiden Hintergrundfarben sollten selbsterklären sein

**Comment by dsiekiera** [comment]
Hier noch mal ein Beispiel bei dem Gewinn dabei ist. Nicht viel aber es zählt 😄 

![Bildschirmfoto 2019-10-09 um 22-38-50](https://user-images.githubusercontent.com/834814/66518534-bf55ea80-eae5-11e9-8889-0801a5418c4e.png)

**Comment by dsiekiera** [comment]
Erscheint in der Version 2.3.11
