### ISSUE TITLE
Forschungskosten Hochmittelalter / Reserach requirements High Middle Age

### ISSUE THREAD

**Issue by megaaffe** [dsiekiera/foe-helfer-extension#1112]
Backsteine (40) fehlen.

Bricks (40) missing.

**Comment by andrgin** [comment]
Geht es ein bisschen genauer?

**Comment by megaaffe** [comment]
Mir ist aufgefallen, dass bei den Forschungskosten des Hochmittelalters die
40 Backsteine (für Stadthaus) fehlen.
Am 28.05.2020 12:39 schrieb "Gindi4711" <notifications@github.com>:

**Comment by andrgin** [comment]
Der Grund dafür ist, dass dies eine optionale Technologie ist d.h. du musst sie nicht erforschen um das Ende des ZA zu erreichen.

**Comment by megaaffe** [comment]
Aber im HMA brauche ich theoretisch alle Gütertechnologien und die dahinter
hängenden Erweiterungen auch nicht. Und die sind auch mit aufgeführt in den
Kosten.
Aber danke für die Erklärung.

Am Fr., 29. Mai 2020 um 15:03 Uhr schrieb Gindi4711 <
notifications@github.com>:

**Comment by andrgin** [comment]
Du hast Recht. Es werden derzeit nur einzelne optionale Technologien (Technologie ohne Nachfolger) ausgeschlossen. Auf ganze Technologiestränge wird nicht geprüft aber da dies einiges an Arbeit wäre und sowieso nur ein paar niedrige ZA betrifft habe ich es bisher nicht integriert.

**Comment by megaaffe** [comment]
Kein Problem.
Am 30.05.2020 10:18 schrieb "Gindi4711" <notifications@github.com>:

**Comment by outoftheline** [comment]
mittlerweile kann man durch häkchen die gesamtkosten sehen
