### ISSUE TITLE
Diamonds missing in statistics

### ISSUE THREAD

**Issue by relax81** [dsiekiera/foe-helfer-extension#1115]
Hello, 
Is it possible that there is a bug with the diamonds in the reward statistics (GEX and GG) or is there a technical limitation with counting / recognizing them?  In my GEX statistics of the last 30 days I see no diamonds at all (which can't be true because I always to all 4 stages) and in the GG I see only 2x 20diamons which also seems to be way too low.

**Comment by osv** [comment]
Not a bug.
In "GE" stats you can see rewards from Temple of relic.

But maybe you are right, good to collect rewards from expedion's chests too..

**Comment by Jay1181** [comment]
My 'Stats' pie chart is resetting every few days. Am I doing something to cause that, or is it something you are working on?
BTW, FANTASTIC tool!!!!
Play hard, play smart, have fun  -   Jay

**Comment by andrgin** [comment]
Loosing data of the stats module is caused by deleting cookies.
