### ISSUE TITLE
Mein LG `` Dynamischer Turm`` ist nur noch ein Gerüst 

### ISSUE THREAD

**Issue by Bocky11** [dsiekiera/foe-helfer-extension#1116]
Hallo,
mein LG `Dynamischer Turm` jetzt ``Turm der Waffenruhe`` ist nur noch ein Gerüst. es ist ca seit zwei Tagen so. 
Seitdem die Forgepunkte im Lager in der Leiste ständig auf null gehen....Danke für eine Antwort

MfG

**Comment by scibuff** [comment]
This is now fixed on beta (#1107) and will be in the next release

**Comment by scibuff** [comment]
p.s. regarding the Dynamic Tower, please see the release notes [de](https://forum.de.forgeofempires.com/index.php?threads/update-auf-version-1-179.45723/) [en](https://forum.en.forgeofempires.com/index.php?threads/update-to-1-179.42123/#post-419271)

> Der Dynamische Turm wurde in Friedensturm umbenannt. Sein Design wird demnächst überarbeit werden. In der Zwischenzeit wird das Gebäude durch eine Baustelle ersetzt werden. Die Fähigkeiten und Werte bleiben jedoch unberührt.

**Comment by dsiekiera** [comment]
@Bocky11 
Bitte immer nur 1 Frage oder Problem pro Ticket. Wir können das sonst nur sehr schlecht händeln.

**Comment by Bocky11** [comment]
Super, ich bedanke für die schnelle Antwort....

MfG
