### ISSUE TITLE
FOE helper does not "see" Fp in stock

### ISSUE THREAD

**Issue by Dlonrab** [dsiekiera/foe-helfer-extension#1117]
See FP Storage upper screen row shows zero FP in stock, 

Cost in the calculator windows are red (not achievable although there are enough FP in Stock for this position.

![image](https://user-images.githubusercontent.com/64436664/83177259-08af8480-a11f-11ea-85d4-ddf338c95c18.png)

**Comment by mhuff249** [comment]
Yeah I noticed this too. Upon launching the game the FP is reported accurately but once you open a GB the stock gets reset to zero.

**Comment by dsiekiera** [comment]
Duplicate of #1089

**Comment by Dlonrab** [comment]
Problem appears in multiple browsers (Firefox,Operaie and Chrome) and did not appear the be present until this afternoon.

(just extra info to help you guys to solve this bug)
