### ISSUE TITLE
Eigenanteilsrechner - 2 überzahlungen

### ISSUE THREAD

**Issue by Blackfir5** [dsiekiera/foe-helfer-extension#112]
Wird mehr als einmal überzahlt und man gibt beide in den Eigenanteilsrechner ein, werden die Anteile nicht mehr berechnet:

![eigenanteil1](https://user-images.githubusercontent.com/55910235/65813490-6ed1b980-e1d6-11e9-9093-a3f17479a844.JPG)
![eigenanteil2](https://user-images.githubusercontent.com/55910235/65813492-72654080-e1d6-11e9-9e48-bf7116838c17.JPG)

Kann man die tatsächlichen Werte (bereits enthaltene FP) auslesen und im Rechner automatisch eintragen?

**Comment by dsiekiera** [comment]
#113
