### ISSUE TITLE
Missing FP on status belt.

### ISSUE THREAD

**Issue by csrsc** [dsiekiera/foe-helfer-extension#1123]
Hi, after last update, sometimes FP on status belt are missing.
It shows 0 FP.

![Zrzut ekranu 2020-05-29 11 37 23](https://user-images.githubusercontent.com/26833140/83246779-e8290e00-a1a2-11ea-95a5-b760f77e6a59.png)
![Zrzut ekranu 2020-05-29 11 37 58](https://user-images.githubusercontent.com/26833140/83246800-ed865880-a1a2-11ea-86d7-13ed10a0d70e.png)

**Comment by dsiekiera** [comment]
In this minutes the new update is rolled out.

**Comment by csrsc** [comment]
Great,
Thank you very much =)

pt., 29 maj 2020 o 11:54 Daniel Siekiera <notifications@github.com>
napisał(a):
