### ISSUE TITLE
Eigenanteilsrechner - weniger FP auf falschen Platz

### ISSUE THREAD

**Issue by Blackfir5** [dsiekiera/foe-helfer-extension#113]
Werden bei einem Platz weniger FP ausgemacht und man gibt es im Eigenanteilsrechner am richtigen Platz ein, wird der Wert automatisch am nächsten Platz eingetragen und die Berechnungen passen nicht mehr:

![eigenanteil3](https://user-images.githubusercontent.com/55910235/65813523-ca9c4280-e1d6-11e9-86ac-8621bf002361.JPG)

Kann man die tatsächlichen Werte (bereits enthaltene FP) auslesen und im Rechner automatisch eintragen?

**Comment by dsiekiera** [comment]
Hab ich auch schon angedacht. Ist aber recht komplex. Das kleine Fenster sieht harmlos aus, hat aber den größten Code um die paar Zahlen zu berechnen...
Warum der in deinem Beispiel so schief rechnet muss ich mal untersuchen.

Das "einsortieren" ist gewünscht. So sieht man wohin man den externen verdrängen kann. Kannst mit einem frischen LG testen und nur mal 5FP eintragen. Das sollte dann recht weit unten ankommen.

Das auslesen hab ich auch mal vor zu schreiben. Überlegung war das er Gildenmitglieder erkennt und "echte" externe bleiben blau.

**Comment by Blackfir5** [comment]
Versteh ich grundsätzlich, aber was ist z.B. wenn P1 (oder P2) abgestaubt wird, der Platz also mit z.B. 100FP unterbesetzt wurde, aber eben nicht mehr überboten werden kann. dann muß ich zum berechnen des Eigenanteils ja mit den weniger FP rechnen und nicht mit voll belegten P1 und 2, weil der Fremde ja nicht mehr verdrängt werden kann.
nehme ich die FP wie angezeigt, ohne die FP des unterbelegten Platzes zu korrigieren, sind die weiteren Plätze nicht safe, wenn ich das angezeigte einzahle...

**Comment by Blackfir5** [comment]
Hallo.
Ich möchte nochmal auf das "Einsortieren" zurück kommen.
Dieses nach unten verdrängen habe ich bis jetzt noch immer nicht benötigt. Allerdings bräuchte ich immer wieder die "weniger FP" auf dem Platz, auf dem ich sie eintrage.
Wie wäre es mit einer Einstellmöglichkeit, bzw. einem haken, um auszusuchen, ob man jemanden verdrängen will (ganz versteh ich das doch noch nicht, weil wenn ich 1,9 safe mache, braucht ein fremder 1,9 um safe zu sein, zahlt er weniger, kann er mit den 1,9 verdrängt werden. war der platz noch nicht safe und er zahlt 1,9, warum soll ich ihn dann verdrängen wollen?...), oder ob die weniger FP gewollt auf dem platz bleiben sollen. wie gesagt, ich hab eigentlich NUR den Fall, dass ich die FP dort haben möchte, wo ich sie eintrage und nicht automatisch einen platz runter rutschen sollen. da weiß ich ja nicht, wieviel ich für den nächsten platz an eigenanteil brauche, bzw. muß ich erst wieder extra rechnen...
