### ISSUE TITLE
FP Stock 

### ISSUE THREAD

**Issue by Soinnet** [dsiekiera/foe-helfer-extension#1131]
resets to zero when FPs are available

**Comment by andrgin** [comment]
This should be fixed with update 2.4.6.1

If you already have this update please give me step by step details on how to reproduce this issue and use the bug report template.

**Comment by Nucleareng-DBA** [comment]
I get this issue as well.
will try and fill the bug report template

**Comment by scibuff** [comment]
You get this in the new 2.4.6.2 version? I cannot replicate this at all after 2.4.6. Could you please provide "steps to reproduce"?

**Comment by Nucleareng-DBA** [comment]
sorry, seem like i was wrong.
thanks guys keep up the great work!!!
