### ISSUE TITLE
Saved city design is messed up on reload

### ISSUE THREAD

**Issue by archonsengine** [dsiekiera/foe-helfer-extension#1134]
OS: Windows 10 64 bit
Browser: Chrome 81.0.4044.138
FoE Server: en6 (Fel Dranghyr)
Extension Version: 2.4.6.2 - English

When I reload a saved design in the city planner, a number of buildings (but not all) get shifted down two rows.
![SAAB planning (3)](https://user-images.githubusercontent.com/38736984/83344905-0d209c80-a2db-11ea-8452-3df9ba0ca7eb.png)

**Comment by dsiekiera** [comment]
I updated this tool a few minutes ago.

**Comment by outoftheline** [comment]
this issue should be resolved by now :)
