### ISSUE TITLE
Request for Statistics: Quest rewards

### ISSUE THREAD

**Issue by reblandi** [dsiekiera/foe-helfer-extension#1135]
In Statistics, it would be a great feature to be able to determine the random rewards earned from recurring quests everyday.  For Chateau Frontenac owners, it would be helpful to see the breakdown of resources gained (or lost ) each day and other time frames from looping through these quests. A tally to keep track of the number of recurring quests performed would be nice to see as well.

**Comment by outoftheline** [comment]
See #985
