### ISSUE TITLE
Someone is talking bad about FOEhelper.

### ISSUE THREAD

**Issue by syjytg** [dsiekiera/foe-helfer-extension#1137]
Hi, someone is talking bad about FOEhelper in https://forum.en.forgeofempires.com/index.php?threads/so-in-the-official-facebook-group.42193/#post-420548

**Comment by osv** [comment]
It is not possible to satisfy all :)

**Comment by scibuff** [comment]
Noobs unhappy about getting plundered I guess ...

**Comment by outoftheline** [comment]
That discussion has been closed a while ago :D -> closing this.
