### ISSUE TITLE
GBG stats Copy and Pasteable into spreadsheet

### ISSUE THREAD

**Issue by vqt123** [dsiekiera/foe-helfer-extension#1139]
Would LOVE LOVE LOVE to be able to copy and paste the GBG stats window into a spreadsheet so that I could sort it to run various contests in my guild!!

**Comment by osv** [comment]
Hi, but it is possible to export to CSV file:
![export](https://user-images.githubusercontent.com/213405/83386567-edc96280-a3f3-11ea-85c0-64533bf43a6a.jpg)

**Comment by osv** [comment]
or vlick view data table to preview as table (not possible to select due some inno game magic with click event as far I know)

**Comment by scibuff** [comment]
Maybe a more thorough solution would be to add the export feature to every `HTML` box, something like this:

![image](https://user-images.githubusercontent.com/722049/83419701-c55a5c00-a425-11ea-9418-cdb87122afa2.png)

and then just do

```
HTML.Box({
	'id': 'export-demo',
	'title': 'Export Demo',
	'auto_close': true,
	'dragdrop': true,
	'export': ExportDemo.export
});

let ExportDemo = {
   
   data: {},
   
   export: ()=> {
	copyToClipboard( ObjectToCSV( ExportDemo.data) );
   }

};
```

and the "copy" icon will appear whenever the `export` callback is defined

**Comment by osv** [comment]
yes, but need to write data adaptor to each window

**Comment by scibuff** [comment]
True, but most just show tabular data so it's only a matter of converting js object/array to csv

**Comment by vqt123** [comment]
That's cool you can in fact download all the GBG data, but it would be a really great user experience to be able to just export the single snapshot of data right from the GBG window itself.
