### ISSUE TITLE
Fehler in Eigenanteilsrechner

### ISSUE THREAD

**Issue by padrone68** [dsiekiera/foe-helfer-extension#114]
gefunden am Beispiel Kraken

Kraken 35 -> 36
erforderlich: 2205
P1 mit 85% = 1054,5 -> aufgerundet auf 1055 (Inno + FOE Rechner)
p2 mit 85% = 527,25 -> abgerundet auf 527 (Inno + FOE Rechner)
Angabe FOE Rechner bei Eigenanteil: 95

das ist aber falsch - der Rest beträgt so 528!

richtig: der Eigenanteil muss auf 96 erhöht werden

**Comment by Morgenmuffel22** [comment]
http://prntscr.com/pdzz6d
Der LG-Eigenanteil wird falsch gerechnet

**Comment by dsiekiera** [comment]
War das die Stufe davor auch schon falsch? Oder nur bei der?

**Comment by Morgenmuffel22** [comment]
Hi, ist mir erst bei der Stufe aufgefallen… seit heute geht’s aber wieder

Gesendet von Mail für Windows 10

Von: Daniel Siekiera
Gesendet: Donnerstag, 3. Oktober 2019 18:18
An: dsiekiera/foe-helfer-extension
Cc: Morgenmuffel22; Comment
Betreff: Re: [dsiekiera/foe-helfer-extension] Fehler in Eigenanteilsrechner(#114)

War das die Stufe davor auch schon falsch? Oder nur bei der?
