### ISSUE TITLE
Anzeige des Spielers, der auf Sektor xy im GG gekämpft / eingenommen hat

### ISSUE THREAD

**Issue by ArtemisEphesia** [dsiekiera/foe-helfer-extension#1142]
In der Infobox kann man sich ja schon den Verlauf /  die Ereignisse im GG anzeigen lassen. Dort wird mit Datum und Uhrzeit vermerkt, welche Gilde auf welchem Sektor wann Punkte macht. In der Aktivitätenübersicht der Gildenmembers sieht man auch, welcher Mitspieler innerhalb der Gilde wieviele Kämpfe/Verhandlungen gemacht hat. Kann man beide Infos  so miteinander verknüpfen, dass die Gildeninternen Spieler in der Infobox angezeigt werden? So könnte der GG Leiter gezielt herausfinden, welcher Mitspieler aus Versehen oder mit Absicht einen Sektor eingenommen hat. Dies dienst ausdrücklich nicht dazu, zu denunzieren sondern vermeidet ewige Diskussionen darüber, wer jetzt versehentlich einen Sektor eingenommen hat und wer auf einem anderen Sektor gekämpft hat. Über den genauen Zeitpunkt könnte man die Daten ja generieren.

**Comment by andrgin** [comment]
Nein siehe abgelehnte Ideen
