### ISSUE TITLE
error when loading statistics

### ISSUE THREAD

**Issue by double816** [dsiekiera/foe-helfer-extension#1144]
when i try to view any of the motivate / polish stats the following error comes up.....

Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_us7' doesn't exist] in EXECUTE("SELECT ops.ops_id, ops.other_id, ops.other_name, ops.is_neighbor, ops.is_friend, ops.is_guild_member, (SELECT UNIX_TIMESTAMP(opse.date_visit) FROM other_players_service_entries_us7 opse WHERE opse.ops_id = ops.ops_id ORDER BY opse.date_visit DESC LIMIT 1) AS last_visit FROM other_players_service_us7 ops WHERE ops.player_id = 17584879 AND ops.other_id = '646517' AND ops.world = 'us7' ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT \n\t\t\t\tops...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1216): ADOConnection->_Exec in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79

**Comment by lrbedal** [comment]
I'm having the same problem:

Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_us3' doesn't exist] in EXECUTE("SELECT ops.ops_id, ops.other_id, ops.other_name, ops.is_neighbor, ops.is_friend, ops.is_guild_member, (SELECT UNIX_TIMESTAMP(opse.date_visit) FROM other_players_service_entries_us3 opse WHERE opse.ops_id = ops.ops_id ORDER BY opse.date_visit DESC LIMIT 1) AS last_visit FROM other_players_service_us3 ops WHERE ops.player_id = 5759733 AND ops.other_id = '171553' AND ops.world = 'us3' ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT \n\t\t\t\tops...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1216): ADOConnection->_Execu in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79

**Comment by Cinimind** [comment]
I'm having the same problem on 2 different servers : FR3 and FR9

Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_entries_fr3' doesn't exist] in EXECUTE("SELECT ops.ops_id, ops.other_id, ops.other_name, ops.is_neighbor, ops.is_friend, ops.is_guild_member, (SELECT UNIX_TIMESTAMP(opse.date_visit) FROM other_players_service_entries_fr3 opse WHERE opse.ops_id = ops.ops_id ORDER BY opse.date_visit DESC LIMIT 1) AS last_visit FROM other_players_service_fr3 ops WHERE ops.player_id = 10671473 AND ops.other_id = '121023' AND ops.world = 'fr3' ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT \n\t\t\t\tops...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1216): ADOConnectio in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79
