### ISSUE TITLE
Stats pie chart is resetting every few days.

### ISSUE THREAD

**Issue by Jay1181** [dsiekiera/foe-helfer-extension#1145]
My 'Stats' pie chart is resetting every few days. Am I doing something to cause that, or is it something you are working on?
BTW, FANTASTIC tool!!!!
Play hard, play smart, have fun - Jay

**Comment by osv** [comment]
I think it is empty because no data for selected period?

**Comment by osv** [comment]
You can also show us screenshot of selected buttons when PIE is empty. And you can check for errors (open dev "console" by pressing F12, if no `red` text than no errors)

**Comment by Jay1181** [comment]
I have not seen it empty. It only shows the most recent rewards. I have pushed the 'Since Tuesday', 'Last 7 Days', 'This Month', 'Last 30 Days', and 'All' buttons, but the same rewards show for each.

**Comment by Jay1181** [comment]
ody {
    position: absolute !important;
    height: 100% !important;
    width: 100% !important;
    overflow: hidden;
}
body {
    margin: 0;
    padding: 0;
    text-align: center;
    color: #ffffff;
    background-size: cover;
    background: #0E1E2D;
}
user agent stylesheet
body {
    display: block;
    margin: 8px;
}
<style>
:root {
    --litepickerBgColor: #fff;
    --litepickerMonthHeaderTextColor: #333;
    --litepickerMonthButton: #9e9e9e;
    --litepickerMonthButtonHover: #2196f3;
    --litepickerMonthWidth: calc(var(--litepickerDayWidth) * 7);
    --litepickerMonthWeekdayColor: #9e9e9e;
    --litepickerDayColor: #333;
    --litepickerDayColorHover: #2196f3;
    --litepickerDayIsTodayColor: #f44336;
    --litepickerDayIsInRange: #bbdefb;
    --litepickerDayIsLockedColor: #9e9e9e;
    --litepickerDayIsBookedColor: #9e9e9e;
    --litepickerDayIsStartColor: #fff;
    --litepickerDayIsStartBg: #2196f3;
    --litepickerDayIsEndColor: #fff;
    --litepickerDayIsEndBg: #2196f3;
    --litepickerDayWidth: 38px;
    --litepickerButtonCancelColor: #fff;
    --litepickerButtonCancelBg: #9e9e9e;
    --litepickerButtonApplyColor: #fff;
    --litepickerButtonApplyBg: #2196f3;
    --litepickerButtonResetBtn: #909090;
    --litepickerButtonResetBtnHover: #2196f3;
    --litepickerHighlightedDayColor: #333;
    --litepickerHighlightedDayBg: #ffeb3b;
}
::-webkit-scrollbar {
    width: 5px;
    height: 5px;
}
::-webkit-scrollbar-thumb {
    background: #281207;
    border-radius: 10px;

**Comment by Jay1181** [comment]
background-attachment:scroll;
background-clip:border-box;
background-color:rgb(14, 30, 45);
background-image:none;
background-origin:padding-box;
background-position-x:0%;
background-position-y:0%;
background-repeat-x:;
background-repeat-y:;
background-size:auto;
color:rgb(255, 255, 255);
display:block;
height:937px;
margin-bottom:0px;
margin-left:0px;
margin-right:0px;
margin-top:0px;
overflow-x:hidden;
overflow-y:hidden;
padding-bottom:0px;
padding-left:0px;
padding-right:0px;
padding-top:0px;
position:absolute;
text-align:center;
width:1365px;
Rendered Fonts
Segoe UI—Local file(10 glyphs)

**Comment by Jay1181** [comment]
The above was the only red I saw.

**Comment by osv** [comment]
no, need screenshot of selected "console" tab, like this. I think there is some errors.

![console](https://user-images.githubusercontent.com/213405/83624149-f0b28780-a59a-11ea-9c06-1a8518c6bd92.jpg)

**Comment by andrgin** [comment]
How much free space is there on your system drive? If free space is running low IndexedDB could delete the database.

**Comment by Jay1181** [comment]
![image](https://user-images.githubusercontent.com/64944311/83634002-d1eacb80-a56f-11ea-935f-73a88458bae3.png)

I have 245gb free space on my drive

**Comment by Jay1181** [comment]
I have 245 gigs of free space on my hard drive. I check the chart almost
every day, and it only seems to show those days' rewards. It doesn't matter
whether I push the 'Today' button, or the 'Last 30 Days' button, the chart
does not change.
 Honestly, besides this issue, this is a fantastic tool!!!
I wish there was a button to automatically collect for the Chateau.

**Comment by osv** [comment]
are you playing in incognito? If yes, than data will be not saved. Also maybe your browser does not allow "storage" usage by some reason. 

I'm pretty sure about it because in screenshot I see `mergeDatabase` log. This message should be visible only once...

**Comment by Jay1181** [comment]
I will check out the 'incognito' thing.
 My browser is Chrome. I can change it if necessary.

**Comment by Jay1181** [comment]
I am using Chrome as my browser. I do not know what 'incognito' is. If I
can find it, is it OK to turn it off?

**Comment by scibuff** [comment]
You can see if you are in incognito mode for example [here](https://jsfiddle.net/806ymka5/), though I don't see how you'd be in that mode unless you specifically want to

**Comment by Jay1181** [comment]
It says, "it does not seem like you are in incognito mode".
It's not that big a deal. The advantage of the other tools far outweigh the issue with this.
 Thanks to everyone for taking time to help.
