### ISSUE TITLE
Moppelauswertung

### ISSUE THREAD

**Issue by Muckinator735** [dsiekiera/foe-helfer-extension#1147]
Entfernt Freunde werden in der "Moppelauswertung" angezeigt, obwohl sie seit Monaten nicht mehr in der FL sind. (https://foe-rechner.de/stats/events/motivations)

**Comment by Muckinator735** [comment]
?????
Keine Antwort wert?

**Comment by andrgin** [comment]
Ja ist ein bekanntes Problem. Der Spielerabgleich funktioniert noch nicht richtig.

**Comment by outoftheline** [comment]
Gibt's nicht mehr
