### ISSUE TITLE
https://foe-rechner.de/stats/events KO

### ISSUE THREAD

**Issue by lnplnp** [dsiekiera/foe-helfer-extension#1148]
Hi,

https://foe-rechner.de/stats/events/motivations
When I visit this page, I get this error message :

> Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_entries_fr7' doesn't exist] in EXECUTE("SELECT ops.ops_id, ops.other_id, ops.other_name, ops.is_neighbor, ops.is_friend, ops.is_guild_member, (SELECT UNIX_TIMESTAMP(opse.date_visit) FROM other_players_service_entries_fr7 opse WHERE opse.ops_id = ops.ops_id ORDER BY opse.date_visit DESC LIMIT 1) AS last_visit FROM other_players_service_fr7 ops WHERE ops.player_id = 7356536 AND ops.other_id = '1587823' AND ops.world = 'fr7' ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT \n\t\t\t\tops...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1216): ADOConnectio in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79

Similar error on all pages under https://foe-rechner.de/stats/events

**Comment by Fooo9** [comment]
Any progress? Seems to be the same as issues #1571 #1144 and  #1102. 

Every time I visit the event history, I see a javascript error in chrome's DevTools console:
```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)		
(anonymous)	@	_main.js?v=2.5.2.0:1262
Promise.then (async)		
send2Server	@	_main.js?v=2.5.2.0:1258
OtherPlayersMotivation	@	_main.js?v=2.5.2.0:1726
....
```
