### ISSUE TITLE
Kostenrechner "Letzte Einzahlung"

### ISSUE THREAD

**Issue by Blutziege** [dsiekiera/foe-helfer-extension#115]
Hallöchen,

ich hoffe das ist kein Doppelpost, habe aber keinen anderen gefunden...

Mir ist gerade zufällig aufgefallen, dass bei der Beschreibung des "Kostenrechners" unter Punkt "6" von der Zeit die Rede ist, zu der zuletzt in das LG eingezahlt wurde. Ist dieses Feature bereits Implementiert? Wenn ja muss ich leider sagen, dass es bei mir nicht angezeigt wird.

Zweiter Punkt, ist es vielleicht Möglich, dass im Kostenrechner zusätzlich einfach oben angezeigt wird, wie viele FP das LG noch bis LvlUp braucht? Ich weiß einfach Subtraktion :D aber hey Fragen kostet ja nichts.

Ansonsten SUPER Tool. Bin echt begeistert.
Weiter so

xoxo B

**Comment by dsiekiera** [comment]
Hey Ziege ;-)

Das ist eine "veraltete" Grafik. Inno hat die Zeit aus den Responses entfernt. Damit haben wohl zu viele Schabernack betrieben.

Daher ist das von mir wieder entfernt worden.

Der zweite Wunsch macht Sinn, daher werd ich das mit aufnehmen. Bin ja auch so ein rechenfauler...

**Comment by Blutziege** [comment]
Danke dir :)
Ich schließe den thread dann.

xoxo B
