### ISSUE TITLE
 Investment-Chart

### ISSUE THREAD

**Issue by kidoudu01** [dsiekiera/foe-helfer-extension#1150]
Hallo, ich habe ein Problem mit der Investitionstabelle des externen GM. Ich habe nicht mehr den zweiten Tisch, um zu sehen, ob wir einen Platz schnappen können. Danke (Entschuldigung, ich verwende Google Übersetzung) x) 
![foe problème](https://user-images.githubusercontent.com/66332025/83562528-02077f80-a51a-11ea-9d1a-74bd5063677d.png)

**Comment by scibuff** [comment]
Try to open the browser console (F12) and copy/paste the following (and hit enter):

`$('#costCalculator').prop('style','top: 0px; left: 0px;');`

Alternatively, you can try to reset all box coordinates in the tool settings

**Comment by andrgin** [comment]
Moving boxes out of the window should not be possible any more. Did you try clicking on the Calculator button in the menu a second time after opening a great building?

**Comment by kidoudu01** [comment]
> Essayez d'ouvrir la console du navigateur (F12) et copiez / collez ce qui suit (et appuyez sur Entrée):
> 
> `$('#costCalculator').prop('style','top: 0px; left: 0px;');`
> 
> Alternativement, vous pouvez essayer de réinitialiser toutes les coordonnées de la boîte dans les paramètres de l'outil


Das Problem war, dass ich hatte "prop('style','top: -897; left: 897px'); 

also setze ich auf 0 zurück 

grosses Dankeschön !! 
gute Partie
