### ISSUE TITLE
Idea : little improved internal GM calculator

### ISSUE THREAD

**Issue by Trankill411** [dsiekiera/foe-helfer-extension#1151]
Hi,

Your FOEhelper is very nice, i would suggest a little improvement to the internal GM calculator.
It's about to look a little like https://foe.tools/fr/gb-investment where you can copy/paste the seats free once you invest in your own GM, like The Blue Galaxy 31 → 32 P1(941) P2(475) for example.
So just to add a copy advert button in the internal GM calculator window, and somewhere to set up the advert message, if possible.

It would be a great thing :)

Thanks

**Comment by andrgin** [comment]
You can open the copy box with the arrow to the right side

![Screen2](https://user-images.githubusercontent.com/55417498/83576571-59194e80-a532-11ea-9674-9daf9e2ba548.png)
![Screen](https://user-images.githubusercontent.com/55417498/83576580-5a4a7b80-a532-11ea-8484-01bba74afb0e.png)

**Comment by dsiekiera** [comment]
Please take a look on this side into the "Copying" Sektion
[https://foe-rechner.de/docs/2/gb-calculator/](https://foe-rechner.de/docs/2/gb-calculator/)

**Comment by Trankill411** [comment]
Daaaaaaaaaaaaaaaaaaamn i didn't see that ^^
