### ISSUE TITLE
GB Cost Calculator - Calculation doesn't consider FPs already invested

### ISSUE THREAD

**Issue by Wyrmblight** [dsiekiera/foe-helfer-extension#1153]
![Capture](https://user-images.githubusercontent.com/66377678/83658547-5a796400-a590-11ea-9183-d707472d32e4.PNG)

As you can see, I have 600FP already invested in this GB. The calculator tells me I haven't enough FPs to reach spot 2, which requires 1058 more FPs, even though I have more than this number. If I roll over the total required, it tells me I have 462FPs too few.

**Comment by Wyrmblight** [comment]
I can confirm I was able to lock the spot for 1058, in spite of the
calculator telling me I needed 1658.

**Comment by scibuff** [comment]
How many FPs did you put in total? Could you add a screenshot of the level 95->96 with invements from everyone?

**Comment by scibuff** [comment]
Thanks for the clarification I did not look at all "reds" in the code I guess
