### ISSUE TITLE
More advanced profit options

### ISSUE THREAD

**Issue by ramijaschek** [dsiekiera/foe-helfer-extension#1154]
I noticed that the helper doesn't analyze slightly more complicated options for making profit:

Let's say there are 55 FP left to pay and the two top spots pay 25 and 20. You can still put in 18 - knowing there is no way 2 people can out invest you (once one of them puts in 19 - the other can not put more than 18). So putting 18 is giving profit although no specific place can be locked.

**Comment by scibuff** [comment]
You can never have spots pay 25 and 20.  The ratio of rewards between slots is always at least 1:2 (actually it is roughly 1:N for the n-th slot up to rounding). Also, if there's 55 FPs left, you can just lock yourself for the slot the pays 25 with 28 FPs and get 20 FPs profit with 1.9 arc bonus.

**Comment by andrgin** [comment]
The only situation where this logic applies (except for team sniping with 2 players) is if P1 is 5FP because then P2 is also 5FP. This is building a new GB (lvl0 -> 1) of colonial age or lower so it is really not worth the effort.

**Comment by ramijaschek** [comment]
The idea in making profit is obviously 'maximum percent increase'. So, if I can make more with a smaller investment - I think that's better. Also - I have no idea when things will come back to me so spreading my investments is better than possibly having a lot of FP locked with a user that isn't moving things around.

So, let's assume there 30FP left and two spots: 20 and 10. If I put in 10 - I am already locking a place currently (can't have two passing me) and keeping the option for myself to get more (say somebody puts 15 - I can put 5 extra and pass again or if just more people put below me - something else can happen).

In general all I am suggesting is looking for options to secure lower spots - simply because you commit fewer FP and keep the option of making more in the future (as you put FP that induces a race in which people tend to make mistakes).

**Comment by andrgin** [comment]
If there are 30 FP left and P1 gives 20, P2 gives 10.
This means you could get P1 for 15 so you are making 5FP more profit without needing to rely on people making mistakes.

**Comment by andrgin** [comment]
Sniping features have been removed: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
