### ISSUE TITLE
Incidents

### ISSUE THREAD

**Issue by Untenshu** [dsiekiera/foe-helfer-extension#1157]
Les incidents n' apparaissent pas dans le FOE power tools ou il y a des différences entre le power tools et l' asssistant, les cquantités ne correspondent pas.

**Comment by dsiekiera** [comment]
FoE Powertools n'est pas une référence car il est absolument interdit.
Des mesures sont en cours pour bannir définitivement les joueurs du jeu avec cet addon "Powertools".
