### ISSUE TITLE
research: victorian houses not recognized as optional tech

### ISSUE THREAD

**Issue by phyden** [dsiekiera/foe-helfer-extension#1158]
Hi,

as stated in the title, I detected a minor issue in the data you use for your tech tree cost calculator.
Here's the screenshot. (current version used: 2.4.6.2)
![image](https://user-images.githubusercontent.com/16943411/83847058-e368da80-a70b-11ea-8adb-0c57d0aec09e.png)

many thanks for your great tool by the way.
br,
Patrick

**Comment by andrgin** [comment]
Yes because I am currently using only a very simple algorithm do determine optional technologies. Currently I only exclude technologies having no successor.
