### ISSUE TITLE
Idee: GG Gebäudeübersicht/Karte mit Zermürbungschance

### ISSUE THREAD

**Issue by KageHikaro** [dsiekiera/foe-helfer-extension#1159]
Wäre es möglich eine Übersicht für die Gildengefechte zu erstellen, in denen die Gebäude der Gebiete angezeigt werden?
Dies würde es erleichtern zu sehen, welche Gebiete Fallen/Köder haben, sodass diese vermieden werden können ohne vorher jedes mal das Gebiet genauer zu betrachten zu müssen.
Weiterhin wäre es ebenfalls möglich zu sehen, wo welche Gebäude gebaut werden um bspw. eventuelle Fallen/Köder-Gebiete vor deren Komplettierung einzunehmen.

Optimal wäre hierfür meiner Meinung nach ein Overlay, dass die Gebäudebilder über das jeweilige Gebiet legt. Alternativ (und vermutlich schneller zu realisieren) wäre eine Liste mit den Namen der jeweiligen Gebiete und den sich dort befindenden Gebäuden oder ein extra Fenster mit einer schematischen GG Karte.
Weiterhin könnte in einer schematische Karte die Zermürbungschance der angrenzenden Gebiete aufgezeigt werden, eventuell farbig ergänzt mit "neutral - gelb, verringert - grün, erhöht - rot".

Vielen Dank für eure bisherige Arbeit!
Kage

**Comment by scibuff** [comment]
Unfortunately, the data regarding sector buildings (and the % of attrition) is loaded only when you open the sector's buildings window. So, you'd have to visit each sector and open the buildings window to collect all the data. Furthermore, there is no way to detect any changes until you reopen the sector building's window again.

**Comment by KageHikaro** [comment]
Thanks for the information :)
