### ISSUE TITLE
FoE Helfer Leiste verschwindet

### ISSUE THREAD

**Issue by Kaye68** [dsiekiera/foe-helfer-extension#116]
Die FoE Helfer Leiste auf der rechten Seite ist nur beim ersten Anmelden nach dem (erneuten) Download sichtbar. Beim Wechsel in eine andere Stadt oder beim Neustart ist sie nicht mehr vorhanden. 
Es hilft dann nur, Chrome-Erweiterung löschen, Helfer neu installieren und wieder bei FoE einloggen.
Das ist ziemlich nervig!!!

**Comment by dsiekiera** [comment]
Davon höre ich zum ersten mal. Sobald sich noch jmd der 5000 Nutzer meldet schau ich mir das an.

Und bitte wirf nicht mit Ausrufezeichen um Dich. Hier ist alles freiwillig. Du musst die Extension ja nicht benutzen wenn sie nervt.

**Comment by Kaye68** [comment]
Verzeih mir bitte meine Ausdrucksweise. Das ist sonst nicht meine Art.
Ich liebe das Tool und bin schon völlig abhängig davon.
Seitdem FoE heute ein Update gefahren hat ist der Helfer "verschwunden", zumindest die Helfer-Leiste. Dass er noch da ist sehe ich nur an der Darstellung der FP im Lager.
Leider bin ich nicht in der Lage, irgendwelche programmierspezifischen Angaben zu machen. Wenn ich aber sonst helfen kann, lass es mich bitte wissen.

**Comment by Kaye68** [comment]
Ich habe für mich eine vorrübergehende "Lösung" gefunden:
Ich wechsel die Stadt nicht, sondern logge mich komplett aus, wieder ein und wähle dann eine andere Stadt. So erspare ich mir das De- und Neu-installieren des Helfers.

**Comment by dsiekiera** [comment]
Brauchst Du nicht. Hab schon die Ursache dafür gefunden und gebe nachher ein Update raus.

Inno hat die Ladezeit verringert, wodurch es zwischen den Welten passiert ist, dass die Extension zu "langsam" war. Habe das bereits behoben.

**Comment by Euse71** [comment]
Hi,
wir haben ein ähnliches Problem in der Gilde. Die Infofenster auf der rechten Seite sind verschwunden. Weltraumfrachter Verhandlungen, Burg Kampfgewinn Chance...
Was ist da los? Im Googelversum finde ich nix. Habe aber auch keine Ahnung wonach ich suchen sollte...
