### ISSUE TITLE
Wunsch: Power-Leveln

### ISSUE THREAD

**Issue by Tsching-Foe** [dsiekiera/foe-helfer-extension#1168]
Wenn mal schnell 10 Stufen eines LG in einer Gruppe gemacht werden, dann ist es aufwendig, jedes Mal erst zu schauen, was eine Stufe an FP braucht und die dann zu posten.
Der Eigenanteilsrechner kann sich die Einstellung nicht merken und bei jedem Level ist wieder Auto angehakt. Das kann ich aber nicht nutzen, da die Plätze ja nicht sicher sind. Ich hake also immer P1 bis P5 an und das jede Stufe wieder etc. Gibt es da vielleicht eine Chance?

**Comment by andrgin** [comment]
Also beim Powerleveln machen wir es normalerweise so dass jeder selbst rechnet. Ich kontrolliere mit dem EA Rechner dann nur ob jeder das gezahlt hat was er soll.

**Comment by Tsching-Foe** [comment]
Manchmal sind die "Helfer" am Handy und bitten um die Zahlen :) Oder ich will auf Nummer sicher gehen.

**Comment by andrgin** [comment]
Hhm vielleicht macht es Sinn die Häkchen zu speichern solange dasselbe LG offen ist.

**Comment by Tsching-Foe** [comment]
Ich dachte das macht vielleicht der Button "merken". Aber dem ist nicht so. Zwischendurch ist das Fenster ja auch wieder zu, da geerntet wird. Aber generell würde eine Schaltfläche genügen, die einfach die Werte für P1-P5 in der Form P5 P4 P3 P2 P1 kopiert reichen, oder?

**Comment by andrgin** [comment]
Ab dem nächsten Update gibt es ein Häkchen "Alle"

**Comment by Tsching-Foe** [comment]
Herzlichen Dank!
