### ISSUE TITLE
foe sniping guide error

### ISSUE THREAD

**Issue by Rontonalon** [dsiekiera/foe-helfer-extension#117]
It has not worked when the amount to go equals an amount already put by someone else.
![image](https://user-images.githubusercontent.com/56032087/65965732-7200ca00-e4a2-11e9-88b5-910796df0c59.png)

**Comment by dsiekiera** [comment]
Hey Rontonalon,

thx for u feedback. I'll take a look. It probably lacks a -1 in the formula.

Regards, mainline

**Comment by Rontonalon** [comment]
HiI was very happy to help.The program is looking good.Also on the sniping tool, sometimes the Building's owner does not change.
Would you like me to advise where English isn't translated properly?
RegardsClive
    On Tuesday, 1 October 2019, 11:36:28 pm AEST, Daniel Siekiera <notifications@github.com> wrote:  
 
 
Hey Rontonalon,

thx for u feedback. I'll take a look. It probably lacks a -1 in the formula.

Regards, mainline

**Comment by dsiekiera** [comment]
Hey Clive,
that would be great and would help me a lot. You can simply check out the en.js in the folder i18n and then make a pull request.

Thank you for your help!

**Comment by andrgin** [comment]
This is already solved in the current version
