### ISSUE TITLE
Не работает регистрация на форуме https://forum.foe-rechner.de/

### ISSUE THREAD

**Issue by vsuh** [dsiekiera/foe-helfer-extension#1170]
При выборе любого способа регистрации (через `e-mail` или `github`) выводится ошибка __К сожалению, что-то пошло не так__
![image](https://user-images.githubusercontent.com/12156293/83969658-e4e7fd80-a8d9-11ea-9993-f08cc739d332.png)

**Comment by outoftheline** [comment]
I saw you posting in the forums later on, so I think this has been resolved :-)
