### ISSUE TITLE
Get total of battles and negotiations after finishing Guild Battlegrounds

### ISSUE THREAD

**Issue by Siguana** [dsiekiera/foe-helfer-extension#1174]
After finishing last Guild Battlegrounds, today I was going to check the total of battles and negotiations.  But when I checked it, the window doesn't pop up.  It seems it pops up only when the Guild Battlegrouns are on air.

Is it possible to implement it?

**Comment by scibuff** [comment]
Yes, there are `GuildBattlegroundService.getPlayerLeaderboard` (during the season) and `GuildBattlegroundStateService.getState` (after the season is over) but you can just check the leaderboard in game

![image](https://user-images.githubusercontent.com/722049/84021372-c0952b00-a984-11ea-9616-b4025788e393.png)

![image](https://user-images.githubusercontent.com/722049/84021407-cf7bdd80-a984-11ea-8fcf-88e6aac79f75.png)

**Comment by outoftheline** [comment]
this has been implemented quite some time ago.
