### ISSUE TITLE
[FeatureRequest] Remember last fight(s)

### ISSUE THREAD

**Issue by weltraumvogel** [dsiekiera/foe-helfer-extension#1176]
Servus zusammen,

Zwar werden da noch mehr Leute jammern, daß das gemein ist, aber dennoch - folgende Idee:

Zeigt (optional) beim Besuch eines Nachbarn an, wie der/die letzten 1-3 Kamp/Kämpfe verlaufen ist.
Mit welcher (eigenen) Aufstellung habe ich gegen die letzte (gegnerische) Aufstellung wie gewonnen/verloren.

Das könnte ich mir natürlich auch selbst aufschreiben, aber dafür wäre der Helfer ja da ;-) 

Danke & Gruß

**Comment by dsiekiera** [comment]
Diese Funktion gibt es bereits seit längerem:

![Bildschirmfoto 2020-06-08 um 15-51-18](https://user-images.githubusercontent.com/834814/84038195-ea0f8000-a99f-11ea-9cb9-a076739dabff.png)

**Comment by scibuff** [comment]
This is already implemented

**Comment by dsiekiera** [comment]
And Atlantis dedection:

![Bildschirmfoto 2020-06-08 um 15-53-22](https://user-images.githubusercontent.com/834814/84038451-407cbe80-a9a0-11ea-9a40-80751d139839.png)

**Comment by weltraumvogel** [comment]
Ja, die Gesamtübersicht. 

Die Idee/Nachfrage hier ist, die Statistiken speziell für diesen einen Nachbarn einzublenden, wenn ich seine Stadt besuche (um nicht durch dröflzig Seiten in der Übersicht scrollen zu müssen)

**Comment by weltraumvogel** [comment]
Oh.... I never opened the PVP-Window when in a City =) Nevermind
