### ISSUE TITLE
Double message's in info box

### ISSUE THREAD

**Issue by SillyDevil** [dsiekiera/foe-helfer-extension#1177]
Message's are displayed twice in Info box, 
![Screenshot_1](https://user-images.githubusercontent.com/65982368/84042320-33ae9980-a9a5-11ea-8b0a-cf12a9a13edd.png)

**Comment by SillyDevil** [comment]
Hi, now its three messages 
![Screenshot_1](https://user-images.githubusercontent.com/65982368/84139885-fbfd2b80-aa50-11ea-9bcd-c4b09333eb4d.png)

**Comment by SillyDevil** [comment]
Hi, still no revert :(

**Comment by scibuff** [comment]
Hi, I've look at this and the other Infobox problem you reported but I haven't been able to replicate either the message duplication nor the delays.

**Comment by troyrock** [comment]
I also see the bug (the number of copies seems to be growing - I'm up to 4 copies now.).

Windows 10 Enterprise 64 Bit
Version 83.0.4103.116 (Official Build) (64-bit)
us5
2.5.0.1 - English

**Comment by GeniusTimo** [comment]
Should be fixed in the next release (see #1376)

**Comment by andrgin** [comment]
The bug in this issue has nothing to do with the current one.
The current one was introduced by a faulty bugfix in 2.5.0.1 (shame on me) so I suggest keeping this issue in "investigating" until it is clear if it still happens or not after 2.5.0.2

**Comment by outoftheline** [comment]
seems to fixed ^^
