### ISSUE TITLE
Guild Battleground Final Statistics - XLS / CSV

### ISSUE THREAD

**Issue by jrq201** [dsiekiera/foe-helfer-extension#1181]
It would be highly useful to have a final line of data for battled from when battleground ended.  The last line of data on the current xls and csv download from the Statistics page shows status as of 2020-06-06 6:28:40 which is I believe 49 hours before the end of GBG.

**Comment by outoftheline** [comment]
your wish has been granted. there is a csv download option now or you can just copy/paste the table.
