### ISSUE TITLE
Wunsch: Produktionsübersicht soll Gebäude mit ZA anzeigen

### ISSUE THREAD

**Issue by Tsching-Foe** [dsiekiera/foe-helfer-extension#1185]
In der Produktionsübersicht sehe ich ja, für welches ZA ich welche Güter produziere. Toll wäre es, wenn ich jetzt auch sehen würde, welche Gebäude für das entsprechende ZA produzieren.
Ist mir nur gerade beim ZA Wechsel aufgefallen, als ich entscheiden "musste" welche Gebäude ich aufs aktuelle ZA und welche ich aufs ZA vorher hebe und welche ich lasse.

**Comment by dsiekiera** [comment]
Ist in der nächsten Version enthalten.

**Comment by Tsching-Foe** [comment]
Verrückt, ist ja top!!!
