### ISSUE TITLE
Treasure hourly - Can't see the graph for the goods.

### ISSUE THREAD

**Issue by wassonv** [dsiekiera/foe-helfer-extension#1190]
The statistics window opens but I can no longer see the graph for the goods lines/stream/delta.
I've cleared browser cache, restarted the computer, no change.
![FOE Helper statistics](https://user-images.githubusercontent.com/66807308/84451185-4a145980-ac20-11ea-8721-21274e08dfab.jpg)

**Comment by scibuff** [comment]
Could you please check if there are any errors in the console (e.g. press F12 and then console) and reload the game -- look for messages in read (or just post a screenshot here)

thanks

**Comment by wassonv** [comment]
onModulesLoaded foe_powertools.js:384:11
Can't parse postData:  [{"__class__":"ServerRequest","requestData":[],"requestClass":"GuildBattlegroundService","requestMethod":"getPlayerLeaderboard","requestId":286}] _main.js:515:13
failed to receive response ID:2

**Comment by wassonv** [comment]
It now shows the goods....but only this hour....no history.

**Comment by wassonv** [comment]
That was city #1. City #2 is not showing the graph now.

This all worked fine this morning.....
Would removing the extension and reinstalling it have dumped the history?

**Comment by wassonv** [comment]
Clearing cash shouldn't have caused this as it clears whenever I close the browser.

**Comment by wassonv** [comment]
It's also not getting the data for rewards GE/GbG.

**Comment by wassonv** [comment]
Have no clue what was wrong.....
NOW it works in both cities but still no history....like it reset. But the history adding up as of 1900 in one city and 2000 in the other city.

**Comment by wassonv** [comment]
The statistics window is doing it again......no display of the data.

**Comment by wassonv** [comment]
Some cookies are misusing the recommended “sameSite“ attribute 4
Cookie “ig_conv_last_site” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite merged-game-8fe8ec25.js:6:400
Cookie “canvas” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite merged-3rd-party-a32c16de.js:54:201
Cookie “instanceId” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite merged-3rd-party-a32c16de.js:54:201
Cookie “startup_microtime” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite merged-3rd-party-a32c16de.js:54:201
unreachable code after return statement
alerts.js:1516:8
Use of mozImageSmoothingEnabled is deprecated. Please use the unprefixed imageSmoothingEnabled property instead. ForgeHX-364b9292.js:1411:83
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ _main.js:457:14
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. ForgeHX-364b9292.js:27418:251
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 16 ForgeHX-364b9292.js:27529:237
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 6 ForgeHX-364b9292.js:27524:350
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 5 ForgeHX-364b9292.js:1369:492
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 4 ForgeHX-364b9292.js:27524:350
WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings) ForgeHX-364b9292.js:27524:350
Storage access automatically granted for tracker “https://github.com” on “https://us20.forgeofempires.com”.

**Comment by osv** [comment]
When you clear browser cache old data will be not available for sure.

**Comment by wassonv** [comment]
However my browser has always and continues to be configured to clear cache when I close it. This has been the case before I started using the FOE Helper extension and since. So why am I now losing all that data? It was very useful to see at a glance the goods levels trend vs having to look at the numbers specifically.

**Comment by wassonv** [comment]
I have corrected the browser setting......
It appears to be working as designed now.
Thank you..
