### ISSUE TITLE
Wiederkehrende Quests

### ISSUE THREAD

**Issue by Bubbabu123** [dsiekiera/foe-helfer-extension#1197]
Gibt es eine Möglichkeit, sich für die wiederkehrenden Quests anzeigen zu lassen, ob man die Dias als Belohnung bereits erhalten hat? Also quasi eine Ausgabe der Wahrscheinlichkeiten für die Belohnungen, wenn Dias da nicht auftauchen, weiß man ja bescheid.

**Comment by andrgin** [comment]
Die Wahrscheinlichlichkeiten werden nicht mitübertragen. Man könnte nur mitloggen, wenn bei dieser Quest schon jemals Diamanten gekommen sind. Für alle Quests, wo du aber die Diamanten jetzt schon einmal bekommen hast oder die du auf einem Gerät ohne Extension bekommst hilft das nicht wirklich.
