### ISSUE TITLE
Moppelaktivität

### ISSUE THREAD

**Issue by Icecold77** [dsiekiera/foe-helfer-extension#12]
Nach dem Update von heute wird bei mir die Moppelaktivität nicht mehr an die Webseite übertragen.

**Comment by dsiekiera** [comment]
Hallo,

Hast du das in den Einstellungen aktiviert?

LG, mainline

Icecold77 <notifications@github.com> schrieb am Mo., 27. Mai 2019, 21:08:

**Comment by Icecold77** [comment]
Hi Mainline,

Da sind alle 3 Haken gesetzt, wie in den letzten Tagen, zu aktualisieren war da nichts...

**Comment by Lashandan** [comment]
Habe das gleiche Problem, nach dem Update werden keine Daten mehr übermittelt.

**Comment by Lashandan** [comment]
> Habe das gleiche Problem, nach dem Update werden keine Daten mehr übermittelt.

Jetzt geht es bei mir mit allen Funktionen: GEX, LGs, Moppeln etc.

**Comment by Icecold77** [comment]
Ja, auf einmal funktioniert es wieder überall

**Comment by dsiekiera** [comment]
Hab ja auch einen kleinen Bug gefunden und diesen gefixt.

Am Di., 28. Mai 2019 um 09:50 Uhr schrieb Icecold77 <
notifications@github.com>:
