### ISSUE TITLE
Fehlermeldungen und leere anzeigen

### ISSUE THREAD

**Issue by MasterInterceptor** [dsiekiera/foe-helfer-extension#120]
Moin Moin, hab mir das Tool heute installiert, und bekommen in folgenden Rubriken keine anzeige: Legendäre Gebäude, Soziale Interaktion (7 Tage), bei Gilde bekomme ich eine Fehlermeldung (siehe Anhang) und Investition ist leer.
Wo liegt da das Problem?
![Fehlermeldung](https://user-images.githubusercontent.com/56156303/66202407-fc654b80-e6a5-11e9-8e2e-81e4df37a632.JPG)
Bei Den FP-Einkommen werden auch nicht alle FP-Bringenden Gebäude angezeigt ( Himmelswacht, Obeliskengarten, Rathaus, Die Täglichen 24 FP(1er Pro Std.), Schreine des wissens nicht in der richtigen anzahl)
Vielen Dank für die Hilfe

**Comment by dsiekiera** [comment]
In der Meldung fehlt ein Wert. Evt war noch nix da. Habe das vorhin gefixt. Die Ereignisse werden wieder korrekt übermittelt.

Die 24h sind selbstredend. Aber die Übersicht soll nur zeigen was gerade produziert wird. Nichts das Maximum.
Daher werden Schreine auch nur angezeigt wenn sie motiviert sind. Ansonsten produzieren sie ja überhaupt keine FPs... Die genauste Übersicht ist daher kurz vor der Ernte nach einem "F5".

Es werden im übrigen nicht Gebäude mit FP Produktion "rausgepickt". Sondern alle deine Gebäude beim Start durchgesteppt und in den entsprechenden "Gruppen" vermerkt. Fehlt also ein Gebäude, produziert es auch nichts ;-)

**Comment by MasterInterceptor** [comment]
In der Statistik fehlen mir immer noch Daten wie die Legendären Gebäude, das die Daten übertragen werden wird mir in einem kleinen fenster als benachrichtigung angezeigt, aber wenn ich mir die anzeigen lassen will, steht unter Legendäre Gebäude nichts.
Wenn ich mir die Moppel Aktivität der Gilde anzeigen lassen will, bekomme ich immer noch die o.g Fehlermeldung

**Comment by Tuetio** [comment]
Hi, das Tool ist der Hammer, vielen Dank dafür. Jedoch muss ich mich meinem Vorredner anschließen. Bei mir bleiben auch viele Anzeigen leer. Habe alle Gildenmitglieder besucht, alle Seiten bei Neuigkeiten durchgeblättert und unter Neuigkeiten auch die mit den LG aufgerufen. 
-Legendäre Bauwerke bleibt leer
-Motivationen anderer Spieler bleibt leer
-Moppelauswertung alle noch nie dagewesen (alle rot)
-Soziale Interaktion DB Fehler
`Fatal error: Uncaught ADODB_Exception: mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY ops.other_name, Spalte ORDER BY ops.other_name ASC, ' at line 16] in EXECUTE("SELECT ops.other_name, WEEK(opse.date_visit,1) AS Spalte, count(opse.visitor_action) AS Anzahl FROM other_players_service as ops LEFT JOIN other_players_service_entries as opse ON ops.ops_id = opse.ops_id WHERE ops.player_id = 3705177 AND ops.world = 'de4' AND ops.is_guild_member = 1 AND opse.visitor_action IN ('motivate','polish','polivate_failed') AND WEEK(opse.date_visit,1) in () GROUP BY ops.other_name, Spalte ORDER BY ops.other_name ASC, Spalte DESC ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXEC in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79`
-Spieler das gleiche:
`Fatal error: Uncaught ADODB_Exception: mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY ops.other_name, spalte ORDER BY ops.other_name AS' at line 13] in EXECUTE(" SELECT ops.other_name, WEEK(opse.date_visit,1) AS Spalte, COUNT(opse.visitor_action) AS Anzahl FROM players LEFT JOIN other_players_service AS ops ON players.player_id = ops.player_id LEFT JOIN other_players_service_entries AS opse ON ops.ops_id = opse.ops_id WHERE players.guild_id = '24205' AND ops.world = 'de4' AND ops.is_guild_member = 1 AND opse.visitor_action IN ( 'motivate', 'polish', 'polivate_failed' ) AND WEEK(opse.date_visit,1) in () GROUP BY ops.other_name, spalte ORDER BY ops.other_name ASC, spalte DESC ") in /usr/www/users/foecre/foe-rechner. in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79`
-Tavernenbesuch auch
`Fatal error: Uncaught ADODB_Exception: mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY ops.other_name, Spalte ORDER BY ops.other_name ASC, ' at line 16] in EXECUTE("SELECT ops.other_name, WEEK(opse.date_visit,1) AS Spalte, count(opse.visitor_action) AS Anzahl FROM other_players_service as ops LEFT JOIN other_players_service_entries as opse ON ops.ops_id = opse.ops_id WHERE ops.player_id = 3705177 AND ops.world = 'de4' AND ops.is_friend = 1 AND opse.visitor_action = 'friend_tavern_sat_down' AND WEEK(opse.date_visit,1) in () GROUP BY ops.other_name, Spalte ORDER BY ops.other_name ASC, Spalte DESC ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1064, 'You have in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79`

Im Tool auf der Seite erhalte ich keine Anzeige in der Infobox, bei Filter sind alle Haken aktiv.
In den Einstellungen habe ich auch alles auf Aktiv gesetzt.
Nutze Crome Version 79.0.3945.117 (Offizieller Build) (64-Bit)
