### ISSUE TITLE
Great building Growth

### ISSUE THREAD

**Issue by Shanon89** [dsiekiera/foe-helfer-extension#1200]
Hello,
I'm always looking for new friends to add to have more Forge points. Actually, to verify if players are very active to up their GB, I make screens and I compare before adding as a friend. It takes looooot of time.

Instead of making screens, I will be verry happy to have something like this :
![souris2](https://user-images.githubusercontent.com/66883991/84576840-f63c7880-adb7-11ea-84fe-806e803b9900.png)

**Comment by andrgin** [comment]
I am not sure if the data will be very helpful if you are checking a player every day (like you do with a neighbor for sniping).
For a rough estimation if a player is active you can use the GB Calculator overview. All yellow lines mean that FP or level has changed since last opening the GB.

**Comment by Shanon89** [comment]
I'm not going in the GB ranking everyday :^). It  can be great before adding someone as a friend... looking if he is slow or fast to up his GB. Time is money, if the player makes just one or two up by week, it is a lost of time & Forge point. It will be nice to activate this just when you want.

**Comment by andrgin** [comment]
Snipe mode for GB calculator has been removed because of a request by Inno.
As this feature assists in sniping it will not be implemented.
