### ISSUE TITLE
Idee/Wunsch: Selektive Anzeige in Info Box

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#121]
Moin,

ich würde gerne als Verbesserung vorschlagen: die Option, die Nachrichten in der Info Box nach Typ zu filtern, damit  man z.B. die Anzeige von Nachrichten des Typs "GEX" oder "Auktion" deaktivieren kann, wenn man mit diesen nichts anfangen kann.
Eventuell steuerbar durch einen Unterpunkt im Plugin Einstellungsmenü.
(Gerade GEX kann montags so scrollen in ner großen aktiven Gilde, dass man die Nachrichten in den RMs glatt übersieht)

**Comment by dsiekiera** [comment]
Wurde mir auch schon angetragen. Werde ich demnächst umsetzen.

**Comment by dsiekiera** [comment]
Kommt mit der 2.3.11
