### ISSUE TITLE
Gildengüter Anzeige in der Produktions Übersicht

### ISSUE THREAD

**Issue by SusiSonne** [dsiekiera/foe-helfer-extension#1216]
Immer mehr Gebäude (Zeppelin , Ehrenstatue...) produzieren Gildengüter. 
Ich wünsche mir, dass mir angezeigt wird wie viele Gildengüter ich in den Gebäuden produzierere und wann sie fertig werden. 
Immer wieder gibt es Questaufgaben in denen Gildengüter gespendet werden müssen.  Diese Güter aus den Gebäuden (nicht aus der Arche) werden dafür angerechnet. Deshalb wäre es sehr hilfreich es auf einen Blick sehen zu können was  noch aussteht.

**Comment by dsiekiera** [comment]
Wenn ich mich nicht irre hab ich das schon vor langer Zeit integriert:

![Bildschirmfoto 2020-06-15 um 11-59-34](https://user-images.githubusercontent.com/834814/84644667-c13b3d80-aeff-11ea-8fba-0390632a4229.png)

**Comment by dsiekiera** [comment]
Aber ich sehe gerade, du hast recht. Die Gildengüter fehlen.

![Bildschirmfoto 2020-06-15 um 12-16-20](https://user-images.githubusercontent.com/834814/84646323-3740a400-af02-11ea-9d6f-374060fea5b9.png)
![Bildschirmfoto 2020-06-15 um 12-15-30](https://user-images.githubusercontent.com/834814/84646326-3871d100-af02-11ea-80c2-01f23fa3f9b8.png)

**Comment by SusiSonne** [comment]
Hallo Daniel , 

 

ja es werden immer nur die normalen Güter angezeigt. 

 

Schön wäre so einen eigenen Reiter oben zu haben wo nur alleine die Gildengüter angezeigt werden. 

 

Ich habe heute wieder eine tägl. Herausforderung die verlangt das ich 130 Gildengüter on die Gildenkasse spende. 

 

Da fände ich es klasse wenn ich auf einen BLick sehen könnte welches Gebäude mir wann welche liefert die ich dafür nutzen kann. 

 

War nur so eine Idee weil halt immer mehr Eventgebäude Gildengüter liefern und das immer unübersichtlicher wird. 

 

LG

Susi 

 
 

Gesendet: Montag, 15. Juni 2020 um 12:18 Uhr
Von: "Daniel Siekiera" <notifications@github.com>
An: "dsiekiera/foe-helfer-extension" <foe-helfer-extension@noreply.github.com>
Cc: "SusiSonne" <SusanneKuhring@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Gildengüter Anzeige in der Produktions Übersicht (#1216)


 

Aber ich sehe gerade, du hast recht. Die Gildengüter fehlen.

**Comment by SusiSonne** [comment]
Super der Reiter ist da . 

Ganz lieben Dank ihr seid einfach spitze :-)

**Comment by andrgin** [comment]
Mittlerweile implementiert
