### ISSUE TITLE
Chrome update 83.0.4103.106 GB cost calculator not working

### ISSUE THREAD

**Issue by jozefboda** [dsiekiera/foe-helfer-extension#1219]
![image](https://user-images.githubusercontent.com/43239530/84751253-a37fde00-afbc-11ea-9223-9dc88efeb4dd.png)

**Comment by Crolla** [comment]
I'm using the same Chrome update, and it is working for me.

Google Chrome Version 83.0.4103.106 (Offizieller Build) (64-Bit)
![foe-keinbug](https://user-images.githubusercontent.com/66923711/84757949-1725e900-afc5-11ea-8521-d2f6200d78d9.png)

**Comment by andrgin** [comment]
Can you please use the bug report template

**Comment by jozefboda** [comment]
Removed, added and works
