### ISSUE TITLE
Infobox: Falscher FP-Gewinn bei LG-Abschluss

### ISSUE THREAD

**Issue by FalkoVPart** [dsiekiera/foe-helfer-extension#1221]
**Voraussetzung:**
- Infobox öffnen - keine Filtereinstellung
- Legendäres Gebäude eines Nachbarn öffnen, wo nur noch 1 FP, sowie P5 frei ist.
- KEIN Forgepunktgewinn für P5

**Durchführung:**
- Letzten Forgepunkt spenden und somit das LG leveln

**Ergebnis:**
- In der Infobox erscheint eine Meldung, dass das Gebäude des Spieler gelevelt wurde
- Spielername, Gebäudename und erreichte Stufe sind  korrekt angegeben
- Als Forgepunktgewinn wird "105 FP" angezeigt, obwohl der Platz KEINEN FP-Gewinn bietete

![FoE Helper Bug](https://user-images.githubusercontent.com/40738463/84766245-c0261100-afd0-11ea-8353-f954fb80a7f9.jpg)

Windows 10 64 Bit
Chrome 83.0.4103.106 (Offizieller Build) (64-Bit)
de11 (Langendorn)
2.4.6.2 - Deutsch

**Comment by scibuff** [comment]
This should be fixed in the next release --- it is already fixed on beta (the issue was with 0 fp rewards)
