### ISSUE TITLE
Kopierfunktion im Eigenanteilsrechner wird nicht angezeigt!

### ISSUE THREAD

**Issue by Hase1805** [dsiekiera/foe-helfer-extension#1222]
Ich habe hier leider keine Möglichkeit irgendetwas zu kopieren.
Vielleicht ist die Funktion aber auch so gut versteckt, dass ich sie nicht finden!

Würde mich über eine Antwort freuen!

Gruß
Hase
![Screenshot 2020-06-16 15 48 22](https://user-images.githubusercontent.com/67008862/84782905-eb1c5f00-afe8-11ea-9282-72a6ba1b4768.png)

**Comment by dsiekiera** [comment]
Versteckt würde ich das nicht nennen... ;-)

![Bildschirmfoto 2020-06-16 um 15-55-34](https://user-images.githubusercontent.com/834814/84783792-e015fe80-afe9-11ea-9543-74fc1958bc9e.png)

**Comment by Hase1805** [comment]
🤦🏼‍♂️ Jetzt wo ich das sehe, muss ich dir auf jeden Fall Recht geben!
Danke und Sorry!

Daniel Siekiera <notifications@github.com> schrieb am Di., 16. Juni 2020,
15:56:
