### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by FouPouDave** [dsiekiera/foe-helfer-extension#1225]
![Sans titre](https://user-images.githubusercontent.com/67053967/84892210-73f4d280-b09d-11ea-9a0c-63b691584598.png)

Il y a un problème dans le calcul : Il dit de poser 19 PF pour sécuriser la première place alors que ce n'est pas le cas.

Translate : There is a problem in the calculation: He says to ask 19 points forge to secure the first place when this is not the case.

**Comment by Th3C0D3R** [comment]
Its not wrong, P2 can overtake P1 because P1 payed 70 FP to few
If you putz 19 FP into the GB, P1 is save
