### ISSUE TITLE
LG mit Gewinn werden nicht immer grün angezeigt.

### ISSUE THREAD

**Issue by mordillo666** [dsiekiera/foe-helfer-extension#1227]
Mir ist heute aufgefallen, dass zwei LG, die seit 2 Tagen Gewinn bringen (ich snipe täglich), heute gelb waren. 
Ich bin mir leider nicht sicher, ob in beide LG seit dem letzten Snipe eingezahlt wurde.
Das werde ich mal beobachten, ob das der Grund ist. 

Meine Frage:
Ist es richtig, dass der Status bei einer zwischenzeitlichen Einzahlung, obwohl das LG weiterhin Gewinn bringt, auf gelb springen soll?

Würde es Sinn machen, die LG "doppelt" zu markieren, bei denen Gewinn möglich ist und in die zwischenzeitlich eingezahlt wurde?

**Comment by andrgin** [comment]
Wenn in ein LG eingezahlt wurde, dann wird es gelb. Selbst wenn es nur 1 FP ist, kann es sein, dass ein Platz inzwischen abgesichert wurde.

**Comment by andrgin** [comment]
Die Übersicht wird mit dem nächsten Update generell entfernt. Deswegen sind weitere Diskussionen hinfällig: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper
