### ISSUE TITLE
Tech Tree Research Costs: Missing SAM Data Crystals Required

### ISSUE THREAD

**Issue by lango6** [dsiekiera/foe-helfer-extension#1228]
![Screen Shot 2020-06-18 at 6 20 39 AM](https://user-images.githubusercontent.com/10041733/85025266-0479f400-b12c-11ea-99ab-e96719fc9e89.png)

As seen in the attached image, the required Data Crystals for Space Age Mars is not shown by the Tech Tree Research Costs tool.

Operating System: MacOS 10.15.5
Used Browser including version: Chrome 83.0.4103.97
Forge of Empires Server: us6
Extension version and language of the extension: 2.4.6.2 - English

**Comment by andrgin** [comment]
These costs do not include optional technologies.
Both technologies are not required to reach the end of the era.

**Comment by lango6** [comment]
It may be true that technically the technologies are optional, but 80% of that era's goods production relies on these two "optional" technologies making them hardly optional at all.  At best, one may be optional in practice.  Weak reasoning.

**Comment by andrgin** [comment]
It is up to you to decide if you need them. There are lots of players who dont build goods buildings on Mars at all.

**Comment by lango6** [comment]
There are "lots" of idiots who aren't wearing masks now too.  I guess that makes the case that we don't really need them.  Doesn't it?  At least now I know your limited perspective and won't rely on this part of your tool.

**Comment by outoftheline** [comment]
Wait, what? This "comparison" - if you can even call it that - leaves me speechless. 
Don't be rude, man.

**Comment by Th3C0D3R** [comment]
Limited perspective?
limited perspective is to build those buildings and don't have GBs or (event) buildings who produces much more in less then those. 

Compare a thing which is optional in a game to a thing which saves lives is out of perspective.
