### ISSUE TITLE
Overview of visitors

### ISSUE THREAD

**Issue by Ruggburg** [dsiekiera/foe-helfer-extension#123]
Hi Team,
It would be great to have an overview of visitors, or did I miss it out?
Thanks for the cool tool :-)
Cheers,
Rugg

**Comment by dsiekiera** [comment]
Hi here is Team, me. 😁

What u mean like visitors? From what?

Regards, Daniel

**Comment by Ruggburg** [comment]
Hi Team Daniel 😊

I mean visiting the taverna and helping/motivating in a way like you can check in the town hall.
Would prefer a better filter there as different activities are shown there, or the possobillity to set filter myself and save them as favorites.

Regards,
Andrea





Gesendet von Mail für Windows 10

Von: Daniel Siekiera
Gesendet: Samstag, 5. Oktober 2019 13:49
An: dsiekiera/foe-helfer-extension
Cc: Ruggburg; Author
Betreff: Re: [dsiekiera/foe-helfer-extension] Overview of visitors (#123)

Hi here is Team, me. 😁

What u mean like visitors? From what?

Regards, Daniel

**Comment by frank42hh** [comment]
Hmmm, perhaps you might want to have a look
at https://foe-rechner.de/stats/events/friends-tavern
and https://foe-rechner.de/stats/events/social-player
which are populated by the data scanned from the town hall when viewing them

**Comment by Ruggburg** [comment]
Hi, 
Was trying to try the links and kept beeing returned to enter the crendtials.
 Thought I has created an account

Ist saying the mailadress ist not known…

Gesendet von Mail für Windows 10

Von: Frank
Gesendet: Sonntag, 6. Oktober 2019 17:33
An: dsiekiera/foe-helfer-extension
Cc: Ruggburg; Author
Betreff: Re: [dsiekiera/foe-helfer-extension] Overview of visitors (#123)

Hmmm, perhaps you might want to have a look
at https://foe-rechner.de/stats/events/friends-tavern
and https://foe-rechner.de/stats/events/social-player
which are populated by the data scanned from the town hall when viewing them

**Comment by dsiekiera** [comment]
@Ruggburg 
Did you register again? Data from other sites or Inno does not work on my site.

**Comment by Ruggburg** [comment]
Not that I am aware of 😉

Gesendet von Mail für Windows 10

Von: Daniel Siekiera
Gesendet: Mittwoch, 9. Oktober 2019 20:05
An: dsiekiera/foe-helfer-extension
Cc: Ruggburg; Mention
Betreff: Re: [dsiekiera/foe-helfer-extension] Overview of visitors (#123)

@Ruggburg
Did you register again? Data from other sites or Inno does not work on my site.
