### ISSUE TITLE
Reorder of the menu

### ISSUE THREAD

**Issue by LordFelix** [dsiekiera/foe-helfer-extension#1232]
Allow reordering of the right-side menu, and save the position. This allows each player to organize the function buttons most used to the most convenient spot.

**Comment by capshort** [comment]
It can already be reordered via drag-and-drop.

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2020-06-19 um 12-29-55](https://user-images.githubusercontent.com/834814/85123492-a67f0680-b228-11ea-9ae6-30ae2116b386.png)

Simply Drag&Drop the icons. By holding the drag on the top/down arrow the menu flip to the next side.
