### ISSUE TITLE
Army list

### ISSUE THREAD

**Issue by LordFelix** [dsiekiera/foe-helfer-extension#1234]
Implement an Army list, similar to FoE Power Tools. Include list of units and expected Alcatraz collection.
Screenshot from Power Tools:
https://media.discordapp.net/attachments/707116842367451157/723472945061691482/unknown.png

**Comment by dsiekiera** [comment]
We have a little overview:

![Bildschirmfoto 2020-06-19 um 12-14-36](https://user-images.githubusercontent.com/834814/85122225-80586700-b226-11ea-8a52-65af14eec806.png)
![Bildschirmfoto 2020-06-19 um 12-14-46](https://user-images.githubusercontent.com/834814/85122226-81899400-b226-11ea-9242-497a77f8f11b.png)
