### ISSUE TITLE
Stadtplaner - Frage

### ISSUE THREAD

**Issue by GidoB** [dsiekiera/foe-helfer-extension#1248]
Zum Stadtplaner habe ich eine Frage.
Ich mich wo denn alle meine Gebäude nach einem Upload sind. Ich sehe immer nur die Gebäude die schon stehen und die Gebäude aus meinem Lager fehlen.
Wenn ich eine leere Stadt anfangen will möchte ich ja Zugriff auf alle Gebäude haben.

**Comment by andrgin** [comment]
Derzeit funktioniert der Stadtplaner nur zum Umordnen bestehender Gebäude (ähnlich dem Umbaumodus im Spiel selbst).

Das Hinzufügen nur Gebäude ist jedoch plant.
