### ISSUE TITLE
Transmit Social Bar to Foe-Rechner.de website and even list the non-polishers in the player statistics 

### ISSUE THREAD

**Issue by Beelzebob6666** [dsiekiera/foe-helfer-extension#1259]
Currently, on the website, players that have not aided at all in the selected time span are not displayed in the player polivation statistic "Auswertung Spieler". So currently I still have to cross check my friends list with the statistics whether they are in the list at all.

You could transmit the friends list/guild member list and neighbors to the website (once per session maybe when the respective list gets opened), and when checking the social interaction in "Auswertung Spieler", the respective players are displayed with a zero even if there has been no aid at all in the selected time span.

This would make it way easier to sort out the "rotten apples".

**Comment by outoftheline** [comment]
Feature has been removed :-)
