### ISSUE TITLE
Münzproduktion von Wunsch- und Jungbrunnen

### ISSUE THREAD

**Issue by MamaLamb** [dsiekiera/foe-helfer-extension#126]
Genau wie bei Rathaus und LGs gibt es keinen Aufschlag. Die derzeitige Berechnung ist demnach falsch. Da die Vorratsproduktion dieser Gebäude richtig dargestellt wird, sollte die Anpassung für Münzen einfach sein.

**Comment by Th3C0D3R** [comment]
ist der Bug noch aktuell? @dsiekiera 
hab leider keines der genannten Gebäude

**Comment by andrgin** [comment]
Ja ist er. Habe jetzt einige Kombinationen durchgetestet.

Anscheinend ist die Definition der Boosts durch einfacher als gedacht und zwar gibt es sowohl Vorratsboosts als auch Münzboost auf:
.) Produktionsgebäude (residental)
.) Wohngebäude (production)

Alles, andere bekommt keinen Boost (LGs, random_production wie Wunschbrunnen usw.)

Was sehr verwirrend ist:
Bei Wohngebäuden, die Vorräte produzieren ist der Tooltip im Spiel selbst falsch. Hier wird der Boost nicht angezeigt, gilt aber trotzdem.
