### ISSUE TITLE
Foe helper grand building question

### ISSUE THREAD

**Issue by ptje63** [dsiekiera/foe-helfer-extension#1261]
![FOE helper ARC](https://user-images.githubusercontent.com/67318902/85393987-30431280-b54e-11ea-9cb9-769597f12785.jpg)
The menu shows I am in position no.2 and how many fp I have spent, but it does not mention how many I still have to spend to secure no.2.
The mention "Nog te storten: 329" at the bottom (Dutch: still to add: 329) is confusing, because it is the total amount the OWNER of the building still needs for leveling.

**Comment by scibuff** [comment]
It tells you you need to added 313 FPs in total to secure the slot - but yes, it could be done in clearer

**Comment by b-tomasz** [comment]
If you put your mouse over the 297/315 on the left side, ther comes a popup, where you can see how much is left.

![grafik](https://user-images.githubusercontent.com/60810950/85450347-f814f180-b598-11ea-9127-37833383297e.png)
