### ISSUE TITLE
zweispurige Straße

### ISSUE THREAD

**Issue by AlmostAtom** [dsiekiera/foe-helfer-extension#1262]
Kaum von Relevanz (vermute ich, außer es führt noch zu anderen Problemen), aber mit dem Tool "Ereignisse" wirds eins der Ereignisse auf einer zweispurigen Straße angezeigt. Allerdings gibt es in meiner Stadt keine derartigen Straßen. Hab mal alles eingesammelt und da ist keine, also ist entweder iwas falsch verknüpft oder es wird einfach eine falsche Nachricht angezeigt, wo sich das Ereignis befinden soll..oder FoE liefert falsche Infos.

Auf dem Bild hab ich mit dem Umbaumodus alles eingesammelt und es sind nur einspurige Straßen vorhanden.
![zweispurigeStr](https://user-images.githubusercontent.com/65259228/85414910-fb928380-b56c-11ea-832c-ab169f0a9846.png)

**Comment by capshort** [comment]
Siehe #502

**Comment by AlmostAtom** [comment]
Ah, danke
