### ISSUE TITLE
Wrong resources calculator

### ISSUE THREAD

**Issue by crios339** [dsiekiera/foe-helfer-extension#1264]
Hi 
I think there are some bugs regardind counting resouces. As you can see from attached picture
Explosives: FoE Helper: Extra/surplus: 93             Game window: missing 180-153
Rubber: FoE Helper: not shown   !                        Game window: missing 160-97

![Capture_9](https://user-images.githubusercontent.com/64492263/85541961-4372e280-b621-11ea-98d3-13acfc1b2880.jpg)

**Comment by capshort** [comment]
Hi,

I think the costs of optional technologies are not taken into account. See also #1228
