### ISSUE TITLE
Event Questliste ist auf dem Stand: Archäologie-Event 2020

### ISSUE THREAD

**Issue by Muckinator735** [dsiekiera/foe-helfer-extension#1265]
Die Questliste für das Fußball - Event liegt mir nicht vor.
Ich dachte, es halte sich um einen Anzeigefehler im Titel, jedoch stimmen die Quests nicht im geringsten überein.

![image](https://user-images.githubusercontent.com/66316515/85590845-0caec380-b645-11ea-8b7e-51ab44887ee9.png)

**Comment by andrgin** [comment]
Da dieses Feature in 2-3 Tagen sowieso nicht mehr existieren wird (siehe https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/22 ) haben wir die Questliste nicht mehr mit Daten versorgt.

**Comment by Muckinator735** [comment]
LOL...
Dumm von mir...
Nicht gelesen oder verdrängt...

**Comment by SkateScout** [comment]
Wie wäre es den wenn die Kommunikation was Innogames genau stört genauso offen gelegt wird wie der Sourcecode?
Vielleicht können sich die Spieler dann ein besseres Bild machen.

**Comment by FalkoVPart** [comment]
Genau das wurde von mainline direkt als erstes gemacht:
https://foe-rechner.de/news/aenderungen-am-foe-helfer

**Comment by SkateScout** [comment]
Event Quests:
Da solche Abweichungen frustrierend sein und Aufwand bei InnoGames erzeugen können, 
beschränken wir uns darauf die Event-Quests auf unserer Website zur Verfügung zu stellen.

-> Wo liegt da der Unterschied? In dem Fall wird ja noch nicht einmal etwas von Inno ausgewertet sondern nur Externer Content als Overlay Angezeigt.

**Comment by FalkoVPart** [comment]
Du schreibst den Unterschied:
Es ist EXTERNER Content, der IM SPIEL dargestellt wird. Der nicht mal von den Live Servern ist, sondern vom BETA Server, also eventuell sogar falsch ist. Das Problem dabei ist, dass einige Spieler insbesondere durch die optische Eingliederung der Komponenten vom Helfer, schnell dazu tendieren die dort aufgeführten Daten als Fakten hinnehmen. Kommt es dort zu offensichtlichen Fehlern führt das zu zusätzlichem Aufwand beim Support und/oder dem Helfer. Deswegen sollen nur sichere Infos dargestellt werden.

**Comment by andrgin** [comment]
Der Punkt mit den Quests war einfach nur ein Wunsch von Inno. Inno hat generell nicht wirklich viel Freude damit, dass die Spieler die Questlisten am Betaserver sammeln. Außerdem sollen damit unnötige Supportanfragen minimiert werden, wenn einmal ein paar Aufgaben getauscht werden. Ich habe nicht den Eindruck, dass diese Änderung bei Inno sehr hohe Priorität hatte. Das wichtigste von den 6 Punkten war ihnen der Erntehelfer.

**Comment by andrgin** [comment]
Was die Ähnlichkeit in der Optik angeht: Ja dem Problem sind wir uns bewusst auch wenn dies überaschenderweise kein Punkt war, den Inno bemängelt hat.
Inno hat nur empfohlen, dass wir keine direkten Link auf unsere Homepage setzen, sondern nur einen Link zum Kopieren, da es sonst mit den Ingame Links zur offiziellen Wiki oder dem Forum verwechselt werden könnte, wobei meine Ansicht ist, dass alle Menü Icons in der Helfer Leiste bzw. alle Fenster, die von dieser direkt geöffnet werden eigentlich eindeutig identifizierbar sein sollten. Der Helfer wird ja bewusst installiert, damit diese zusätzliche Leiste da ist.

**Comment by SkateScout** [comment]
@andrgin Ich denke dein Hinweis das Inno das Wichtigste der Erntehelfer war ist ein Guter Punkt.
1. Kostenrechner => Kann man jederzeit Extern auch durchführen
2. Ereignisse => 
3. Verhandlungen => Exklusive Funktion des Helfers
4. Event Quests => Gibt es als Listen im Netz
5. PvP Aktivitäten => Wenn damit die Kampf History gemeint ist das haben Spieler auch bisher Manuell gemacht
6. Erntehelfer => Exklusive Funktion des Helfers

Ich denke man sollte mir Inno reden. Das man vielleicht nicht alle 6 Punkte wie jetzt geplant umsetzt sondern nur (6) komplett und bei Events vielleicht Deutlich in der Überschrift Markiert das es nur die Erwartete Reihenfolge ist. Und den Kostenrechner vielleicht wie Früher ohne Vorabscan anbietet.

Ich denke wenn alle 6 Punkte umgesetzt werden wird der Helfer zu viel Zustimmung verlieren.

**Comment by andrgin** [comment]
Ob man nun für die Quests auf die Homepage schauen muss oder nicht bzw. ob wir nun die noch nicht erschienenen Ereignisse ausblenden sehe ich nicht also wirklich wichtig an. Wenn Inno es so haben will, dann machen wir es halt so.

Erntehelfer: Diese Funktion war echt grenzwertig und ist eigentlich nur drin geblieben, weil es von Inno damals erlaubt wurde. Rein aus moralischen Gründen ist das schon eine sinnvolle Entscheidung. Vor allem wurde der Helfer auf Grund dieses Features von manchen Spielern immer in das Cheatereck gerückt.

PvP Aktivitäten: War ein ganz nettes Feature auch wenn ich es selbst nicht benutzt habe aber auch nicht wirklich unersetzlich. Muss man sich das Ganze halt wieder manuell aufschreiben.

Verhandlungsassistent: Wo man ihn wirklich braucht nämlich bei der Gex bleibt er ja bestehen. In den GG mit 3 Runden gibt es wenn man die Güterreihenfolge außer Acht lässt nur 17 (bei 5 Gütern) bzw. 19 (bei 6 Gütern) mögliche Tipps. Die kann man auch schnell mal auswendig lernen vor allem da die 5 und 6 Güter auch ziemlich ähnlich zu spielen sind. Eventuell basteln wir mal einen Onlinehelfer dafür wenn Zeit ist.

Kostenrechner: Diese Änderungen schmerzen halt etwas aber es nicht so, dass man damit nun gar nicht mehr snipen kann. Es geht  immer noch viel schneller als mit externen Tools.
