### ISSUE TITLE
Kostenrechner: Plätze auch mit Verlust anzeigen?

### ISSUE THREAD

**Issue by messer78** [dsiekiera/foe-helfer-extension#127]
Hi Daniel,

wenn ich den Kostenrechner aufrufe, dann werden mir ja üblicherweise, wenn vorhanden, der benötigte Einsatz und der erzielbare Gewinn angezeigt. Wenn ich nun mehr einzahle als der Ertrag ist, dann wird mir auch der erzielte Verlust angezeigt – so weit, so gut.

Meine Idee wäre es nun, generell auch den Verlust und den zum Erreichen eines Platzes nötigen Einsatz einzublenden, selbst, wenn ich nichts eingezahlt habe – manchmal sind es ja nur wenige FPs, die man an Verlust verkraften müsste, um dennoch eine stattliche Anzahl an Blaupausen und/oder Medaillen abzustauben. 
Kann ja dann irgendwie rot eingefärbt werden, damit klar ist, dass Verluste drohen :-)

Was hältst du davon?
Gruß
Dennis

**Comment by messer78** [comment]
Alternative Idee als nicht ganz so bequemer Workaround :-)

Derzeit mache ich es so, dass ich aus meinen 85 % Bonus eine 850% mache, dann sehe ich zumindest die nötigen FPs Einsatz zum Absichern, und dann schalte ich auf 85% zurück.
Es ginge daher natürlich auch, einfach einen 1000%-Button zu den 85- und 90%-Buttons hinzuzufügen, zum schnell zwischen echtem Bonus und virtuellem Bonus hin- und her-Schalten :-)

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2019-10-18 um 12-33-02](https://user-images.githubusercontent.com/834814/67087566-75cf6480-f1a3-11e9-9759-c15834479f31.png)

Aktivieren, und dann:

![Bildschirmfoto 2019-10-18 um 12-31-27](https://user-images.githubusercontent.com/834814/67087583-7f58cc80-f1a3-11e9-8dff-578780693f33.png)
Dieser Screenshot zeigt mal alle Optionen:
blau => gesicherter Gewinn
gelb/gelber Hintergrund => würde beim einzahlen das LG leveln
grüne Zahl => Gewinn
grüner Hintergrund => Platz ist save
rote Zahl => Verlust
roter Hintergrund => Platz ist nicht save
