### ISSUE TITLE
Fehler beim Laden der Seite events/social-guild

### ISSUE THREAD

**Issue by rwing1** [dsiekiera/foe-helfer-extension#128]
Hallo,
beim Laden der Seite der Gildenauswertung  events/social-guild bekomme ich immer einen Fehler angezeigt:
Fatal error: Uncaught ADODB_Exception: mysqli error: [-9999: Input array has 3 params, does not match query: ' SELECT ops.other_name,  .....

Woran liegt das (Ist  sowohl beim PC als auch beim Laptop so, beide win 10)
lg rwing

**Comment by dsiekiera** [comment]
Ist gefixt
