### ISSUE TITLE
Troops Loadouts

### ISSUE THREAD

**Issue by kc7uyt** [dsiekiera/foe-helfer-extension#1294]
I would like you to add troop load outs. So like when you are going into battling you can click one button and have that configuration load and go to battle.

Example would be:
load out 1: 4 Trebuchet and 4 Rogue
load out 2: 1 Fast and 7 Rogue
load out 3: 1 Heavy and 7 Rogue
and so on etc...
Maybe nice to have 20 load out I don't know for sure just so you can change and set your own load out thank you.

**Comment by andrgin** [comment]
Notpossible see: https://github.com/dsiekiera/foe-helfer-extension/issues/860

**Comment by kc7uyt** [comment]
So InnoGames really is the problem? If so, I may try to go to them if
that's ok with you? I would like to take some time and tell you thank you
it's a nice tool to have. I did some of the tutorials on the web site
GitHub. It was interesting to me. I may try to do some of it on simple
stuff.

**Comment by andrgin** [comment]
Yes I think the idea section on the Inno forums would be a better point for this idea, but I think this has already been requested several times.
