### ISSUE TITLE
Bug: Number count blocks button press for incidents

### ISSUE THREAD

**Issue by strongstancer** [dsiekiera/foe-helfer-extension#1295]
After the new update the circle with the number count is layered on top of the button thus blocks clicking the button under the circle.

**Comment by GeniusTimo** [comment]
Ich habe diesen Fehler in der Pull-Request #1350 behoben ✔️

**Comment by andrgin** [comment]
Ist im beta Branch gefixed, wird mit dem nächsten Update ausgeliefert
