### ISSUE TITLE
Bug: repeatable "research 2 techs" quest in Iron Age counts as FP quest in cost calculator

### ISSUE THREAD

**Issue by strongstancer** [dsiekiera/foe-helfer-extension#1296]
When the quest to "research two techs" is acitve, the cost calculator shows "2 FP" as if there was the quest for FP investment active with 2 FP left. Pretty annoying if you log in, open GB pay 2 FP and don't have the quest done ;-)

This is not the case in the Late Middle Age, but can't say more for other ages, since I have only cities in IA and LMA.

**Comment by andrgin** [comment]
Behoben in Update 2.5.0.1
