### ISSUE TITLE
Production overview era not correct for goods

### ISSUE THREAD

**Issue by denisebuilder** [dsiekiera/foe-helfer-extension#1297]
The "production overview" shows the era of the player for all Great Buildings, yet from modern era on, the goods produced by FI Atlantis are of a previous age. The goods tab in production overview labels them as the age of the player however. The frame is also a little on the small side, production now take up 2 lines.

**Comment by andrgin** [comment]
Double issue please continue here: https://github.com/dsiekiera/foe-helfer-extension/issues/1298
