### ISSUE TITLE
Production overview goods era not correct

### ISSUE THREAD

**Issue by denisebuilder** [dsiekiera/foe-helfer-extension#1298]
The "production overview" shows the era of the player for all Great Buildings, yet from modern era on, the goods produced by FI Atlantis are of a previous age. The goods tab in production overview labels them as the age of the player however. The frame is also a little on the small side, production now take up 2 lines.

**Comment by andrgin** [comment]
Can you post a screenshot

**Comment by denisebuilder** [comment]
sorry for the delay; a screenshot

hedendaage tijdperk = contemporary era
benzine = gasoline (which is actually progressive era)

![image](https://user-images.githubusercontent.com/64001765/86108876-02b51680-bac4-11ea-9b2a-c0aee6a2ef30.png)

**Comment by andrgin** [comment]
Now I am getting it.

The era column works the same way as in all tabs. It does not show the era of the good, but the era of the building. This was added so you can check for goods buildings stuck in a previous age needing a reno kit.
Great buildings are always of the current era.

**Comment by denisebuilder** [comment]
Ah, it would however be nice if the era shows the era of the produced goods; recognizing a GB should not be that difficult ;-)

**Comment by andrgin** [comment]
Having 2 era columns would be too much and I dont want a different logic for goods and for the other tabs as this will get confusing, but I will look if I can make it a bit clearer.
