### ISSUE TITLE
Bug: New notepad does not save on close 

### ISSUE THREAD

**Issue by strongstancer** [dsiekiera/foe-helfer-extension#1300]
The newly added notepad does not save the text, when you close it while the focus is still in the part where you can edit the text (blinking cursor / vertical line). You have to first click somewhere else outside of the text box (doesn't matter if inside the notepad window itself or completely outside the notepad window on any other part of the game). Guess it's a technical limitation that text is not updated with every character you type in, since its synched with the server. But you could add a force synch when closing the window.

edit: small thing to add here: could you make the notepad open on the group / page where you closed it?

**Comment by outoftheline** [comment]
I could reproduce this:
1. Type some text
2. Close via x
