### ISSUE TITLE
Verhandlungsassistent funktioniert bei der GG nicht mehr

### ISSUE THREAD

**Issue by mitsu2000** [dsiekiera/foe-helfer-extension#1303]
aloha,

Windows 10,64 bit
Chrome/83.0.4103.116, 
de 21 (Vingrid) de 17 (Rugnir) de 13 (Noarsil) de 20 (Uceria)  de 3 (cirgard)
auf allen angegebenen Welten Version 1.181.afe39db02d0 (24.06.2020 10:52

Der Verhandlungsassistent funktioniert nicht mehr bei Verhandlungen in den Gildengefechten

lg mitsu

**Comment by scibuff** [comment]
This is by design to satisfy Inno's requirements
