### ISSUE TITLE
Tech tree research costs.

### ISSUE THREAD

**Issue by Lostchild65** [dsiekiera/foe-helfer-extension#1304]
I purposely left the townhouse portion of my HMA tech tree unfinished because I don't want to advance to LMA yet. Yet when I use the tech tree research costs tool, it states that I have reached the end of the era. Not sure if this qualifies as a bug because you don't need to research townhouses to advance in the tech tree....but I thought it was still worth bringing to your attention.
![image](https://user-images.githubusercontent.com/67509317/85923810-88e81780-b88e-11ea-89ec-b9e9fafecd71.png)

**Comment by andrgin** [comment]
Optionap technologies are not included in the list on purpose. In Mars you have a lot of those and they only unlock stuff you cant use after Mars anyway.
