### ISSUE TITLE
LB Investments-Tool: Entry in the "Cost of goods" field is not accepted 

### ISSUE THREAD

**Issue by Plaatinoo** [dsiekiera/foe-helfer-extension#1305]
With the " LB Investments" tool, an entry in the "Cost of goods" field is not accepted by the calculator. It changes back to the standard values.
Especially in a still young world, the values for the cost of goods still differ considerably.
Otherwise a nice feature!

Chrome Version 83.0.4103.116, Win 10 (Version 1909)

**Comment by andrgin** [comment]
This is a sorting problem. The input is landing in the Box of another GB
