### ISSUE TITLE
Misleading: Sichere / unsichere Plätze nicht korrekt angezeigt

### ISSUE THREAD

**Issue by Nerd2020** [dsiekiera/foe-helfer-extension#1307]
![grafik](https://user-images.githubusercontent.com/67139127/85926032-c0f65700-b89c-11ea-8d9d-5f1106829950.png)

Bei noch offenen 4 fp ist die Einlage von 5 fp sicher, wird aber dennoch rot angezeigt.

**Comment by andrgin** [comment]
Es gibt keinen Snipemodus mehr. Die 5/10 FP beziehen sich auf die eingstellten 90%.
