### ISSUE TITLE
Hide recurring quests that we never do

### ISSUE THREAD

**Issue by billielith** [dsiekiera/foe-helfer-extension#1308]
Hello
I don't know if it's been requested before, but I'd like to make a request for the Forge of Empires Helper.

Could it **hide the recurring quests that we never do**, so we have **less many of them to skip when we do them**?
We could select those we don't want to see anymore, the Helper would hide them, and if we want to reset this, we get back to seeing all the recurring quests.

Thanks.

**Comment by andrgin** [comment]
No see https://github.com/dsiekiera/foe-helfer-extension/issues/860

**Comment by outoftheline** [comment]
No can do.
