### ISSUE TITLE
Kostenrechner: Feld Differenz zeigt immer nur 90% Wert

### ISSUE THREAD

**Issue by Tsching-Foe** [dsiekiera/foe-helfer-extension#1309]
Im Kostenrechner kann ich wählen, mit welchem Bonus ich fördern möchte. Aber das Feld Differenz zeigt immer den Wert für 90% an. Ist es aufwendig, dass sich dieses Feld aktualisiert (in Abhängigkeit dessen, was ich bei den Werten ausgewählt habe)? Merke aber gerade, dass ich natürlich auch irgendwo sehen will, was ich mit meiner Arche > 80 Gewinn mache ...
Wären zwei Spalten vielleicht eine Lösung? Ich würde gerne sehen, wie viele ich noch zum entsprechenden Wert einzahlen muss und ich würde gerne sehen, welchen Gewinn ich mit meiner Arche > 80 mache.

**Comment by andrgin** [comment]
Die Spalte Differenz zeigt den Unterschied zwischen dem einstellten Förderfaktor und deinem Archebonus.

Beispiel:
Fördern ist auf 85% gestellt
Deine Arche ist auf 92%
Der Platz gibt 100FP Netto Mäzen

Dann machst du beim Fördern (92%-85%) * 100 = 7FP Gewinn

Was die Gewinnspalte beim Snipen angeht:
Die war ja schon enthalten, jedoch mussten wir die auf Wunsch von Inno entfernen.
