### ISSUE TITLE
Snipen ...

### ISSUE THREAD

**Issue by Tsching-Foe** [dsiekiera/foe-helfer-extension#1310]
Wie erwartet vermisse ich dieses Funktion am meisten ... Echt bitter ... Ich verstehe auch nicht, warum Inno die weg haben will, aber ist halt so.
Siehst Du irgendeine Möglichkeit, das auf legalem Wege leichter ersichtlich zu machen? Also wie rechne ich es mir denn generell aus?
Es sind noch X FP bis zum leveln notwendig. Ich weiß auch, was der Platz für die 90% kostet. Jetzt muss ich doch nur prüfen, ob die Hälfte vom "bis zum leveln"-Wert weniger ist, als der 90% Platz. Korrekt? Klar, das geht im Kopf. Meinst Du aber, es wäre möglich, wenn Du "bis zum leveln" und die Hälfte anzeigen lässt?

**Comment by dsiekiera** [comment]
Mouseover über die grüne "Differenz" und artig durchlesen. 😁

**Comment by Tsching-Foe** [comment]
Ist es möglich, dass dort die Differenz zwischen Archebonus und "Platz ist sicher" zu sehen wäre? :)

**Comment by GeniusTimo** [comment]
Nach der Einzahlung sieht man die Differenz - außerdem kann man das ja grob abschätzen 😅

**Comment by Tsching-Foe** [comment]
:-)
