### ISSUE TITLE
Fehlerhafte Anzeige in Gildenexpedition

### ISSUE THREAD

**Issue by Schlemmermeyer** [dsiekiera/foe-helfer-extension#1311]
<img width="282" alt="Screenshot 2020-06-27 at 06 59 46 PM" src="https://user-images.githubusercontent.com/59023450/85927760-74b11400-b8a8-11ea-8340-3942460b478a.png">

Leider hilft auch nicht die Boxlänge zu reduzieren von Default auf 7 oder so. Die Oberkante behält dabei die Position. Vielleicht kann man das an der Unterkante ausrichten?

Oder die Darstellung automatisch reduzieren, wenn kein Platz mehr für die FOE-eigene Box darüber bleibt?

**Comment by andrgin** [comment]
Die Position der 3 Icons ist bewusst so gewählt. Diese werden normalerweise rechts oben angezeigt bei GG, Karte oder Nachbarn. In der Gex ist an dieser Stelle leider schon das Relikticon, weshalb wir uns entschieben haben die Box nach unten neben die Menüleiste zu verfrachten.
