### ISSUE TITLE
Latest version no longer runs

### ISSUE THREAD

**Issue by namsur1234** [dsiekiera/foe-helfer-extension#132]
Latest version was installed and the game refreshed. After that the banners or side scroll bars no longer appear as if it were not loading the extension.

This shows up in Chrome Dev Tools error message:
settings.js?v=2.3.11.1:63 Uncaught TypeError: Cannot read property 'Title' of undefined
    at settings.js?v=2.3.11.1:63

**Comment by Mursanian** [comment]
Same issue, Chrome is up to date, using 64bit version.

**Comment by andrgin** [comment]
I think the issue is that the new setting "PreScanLGList" is missing the English and French translation.

**Comment by Mursanian** [comment]
I am on a German server, I can test it if I switch my browser to German, let's see.

**Comment by dsiekiera** [comment]
I fixed it in version 2.3.11.1

Please check for a extension update.

**Comment by Mursanian** [comment]
Lemme switch back, I think I had the update already though, 40 minutes before this post.

**Comment by Mursanian** [comment]
Nope, using version 2.3.11.1 and English Chrome it is not working.

**Comment by andrgin** [comment]
You have added CalculatorShowNegativ, but not PreScanLGList ;-)

> I fixed it in version 2.3.11.1 Please check for a extension update.

You have added CalculatorShowNegativ, but not PreScanLGList

**Comment by dsiekiera** [comment]
Give me 15min...

**Comment by dsiekiera** [comment]
A few seconds ago, I submitted a new update to Google. That should be rolled out in a few minutes.
Sorry for the inconvenience.
