### ISSUE TITLE
GB Calculator

### ISSUE THREAD

**Issue by poodle666** [dsiekiera/foe-helfer-extension#1320]
The new version is broken. The information it displays is wrong. Example it is saying that I need to drop 225 FP in order to secure Zeus L13  when actually 265 is needed

**Comment by asafstr2** [comment]
the only reason i have the helper is to know how much i need to put to secure my location this is the main thing here and it is now removed?

**Comment by andrgin** [comment]
@poodle666 Can you post a screenshot

@asafstr2 This was a request from Inno see our statement here: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/91

**Comment by poodle666** [comment]
Screen shot attached

[image: ]
Bunny's quest for world domination continues

**Comment by andrgin** [comment]
Attachments do not work when responding per mail...

**Comment by andrgin** [comment]
Cant investigate the issue without a screenshot.
