### ISSUE TITLE
Snipe was removed despite being the main attraction   

### ISSUE THREAD

**Issue by asafstr2** [dsiekiera/foe-helfer-extension#1323]
the only reason i have the helper is to know how much i need to put to secure my location this is the main thing here and it is now removed?

**Comment by scibuff** [comment]
Yes, it's being removed as per Inno's requirements

**Comment by andrgin** [comment]
See https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/91
