### ISSUE TITLE
Negotiation Helper not working in GBG

### ISSUE THREAD

**Issue by Eric734** [dsiekiera/foe-helfer-extension#1325]
Negotiation helper seems to work fine in GE but doesn't seem to appear/reset when then moving over to GBG. 
This is using Mozilla Firefox.

**Comment by andrgin** [comment]
This was removed because of a request by Inno see: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/106
