### ISSUE TITLE
negotiations in the fields of glory do not work for the Polish language

### ISSUE THREAD

**Issue by tpaciorek** [dsiekiera/foe-helfer-extension#1326]
negotiations in the fields of glory do not work for the Polish language
chrome version plugin 2.5.0.0.

**Comment by andrgin** [comment]
Negotiation helper has been removed for guild battlegrounds because of a request by Inno: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/111
