### ISSUE TITLE
Verzögerung beim Kampf in den Gildengefechten

### ISSUE THREAD

**Issue by Landauer68** [dsiekiera/foe-helfer-extension#1329]
Seit dem Update kommt es bei mir zwischen dem Klicken auf den Angriffbutton und der Anzeige der Armeen zu einer Verzögerung von rund 2 Sekunden. Wenn ich die Erweiterung deaktiviere passiert das nicht.

**Comment by andrgin** [comment]
Ich denke nicht, dass das etwas mit der Extension zu tun hat.
Ich habe gerade den Profiler in Chrome angeworfen und bei mir dauert es 800ms, wovon ganze 7.3ms auf die Extension entfallen und der Rest auf das Spiel selbst.

**Comment by andrgin** [comment]
Da das Problem nicht reproduzierbar ist, mache ich hier mal dicht.

**Comment by Landauer68** [comment]
Hallo, ich hatte das Problem vorgestern nochmals und zwar ging es kurz vor Mitternacht los und dauerte ca. 5 bis 10 Minuten. Davor und danach lief alles normal. Wenn es nur mich betrifft, lohnt sich der Aufwand eher nicht, da groß auf die Suche zu gehen. Dann schalte ich die Erweiterung in der Zeit einfach aus.

Gruß

Thomas

-----Original Message-----

**Comment by SkateScout** [comment]
Hi,
mache mal nur die Infobox zu. Wen das Hilft wäre eine Gute Information wie viele Einträge darin sind.
Ich habe bei mir gesehen das eine sehr Volle Info Box das System ausbremst. Filter scheint nicht zu helfen.

**Comment by Landauer68** [comment]
Hallo, ich nutze die Infobox nicht.

**Comment by dsiekiera** [comment]
Gestern Abend ca 23:30-23:55 Uhr hatte Inno komplett Probleme. Ich konnte mich zu dieser Zeit gar nicht mehr einloggen. Bei de12 ging es dann ca 10min später wieder.

Hat mit dem Helfer nichts zu tun.
