### ISSUE TITLE
Kostenrechner funktioniert nicht mehr

### ISSUE THREAD

**Issue by Darkproduct** [dsiekiera/foe-helfer-extension#133]
Nach dem neusten Update funktioniert der Kostenrechner nicht mehr. Die FP leiste oben, sowie der Updateplaner funktionieren. Der Kostenrechner lässt sich wie gewohn öffnen, das fenster ist aber nur eine leere leiste mit dem ?- und dem x-Button.

**Comment by andrgin** [comment]
Hast du die neuen Funktionen "Vorab Scan der LG Übersicht" bzw. "Negativer Gewinn im Kostenrechner" aktiviert?

Kannst du mal mit F12 die Entwicklertools öffnen und schauen, ob er an einer gewissen Zeile eine Exception wirft.

**Comment by Darkproduct** [comment]
Nein, die Funktion ist nicht aktiviert. Das werde ich aber noch tun, da ich das Tool sehr nützlich finde.

In der Console sehe ich keine Skript fehler, die auf ein Problem mit dem Addon hindeuten. Da ich allerdings umatrix benutze, wird alles was nicht von forgeofempires, for-rechner oder innogamescdn kommt geblockt. Ich nehme mal nicht an, dass dein Addon von Onlinequellen abhängt.

**Comment by andrgin** [comment]
Das Problem scheint die Splittung des neuen "Mögliche Einzahlungen" Fensters und dem Kostenrechner Fenster zu sein. Ich habe nun 4 fehlerhafte Varianten gefunden (abhängig davon in welcher Reihenfolge man welche Buttons drückt).

Variante1:
1.) Übersicht öffnen
2.) Kostenrechner Button => Mögliche Einzahlungen öffnet sich
3.) LG anklicken => Kostenrechner Fenster öffnet sich nicht => Fehler
4.) Kostenrechner Button => Beide Fenster sind offen => OK

Variante2:
1.) Übersicht öffnen
2.) LG anklicken
3.) Kostenrechner Button => Kostenrechner öffnet sich
4.) anderer Spieler Übersicht öffnen => Mögliche Einzahlungen öffnet sich nicht, auch nicht mit erneutem Drücken des Kostenrechner Buttons => Fehler

Variante3:
1.) Übersicht öffnen
2.) Kostenrechner Button => Mögliche Einzahlungen öffnet sich
3.) LG anklicken => Kostenrechner Fenster öffnet sich nicht => Fehler
4.) Fenster mögliche Einzahlungen schließen
5.) Übersicht eines anderen Spieler öffnen
6.) Kostenrechner Button klicken => Detailansicht des vorherigen LGs wird geöffnet, nur steht dort der Name des aktuellen Spielers => Fehler

Variante4:
Diese hatte die oben beschriebenen Symptome mit einem Kostenrechner Fenster nur mit Titel ohne Inhalt
Leider fällt mir die genaue Reihenfolge nicht mehr ein.  Angefangen hat es mit:
1.) Übersicht öffnen
2.) Kostenrechner Button => Mögliche Einzahlungen öffnet sich
Irgendwann in den Folge habe ich das Mögliche Einzahlungen Fenster geschlossen und auf einen anderen Spieler gewechselt.
Es hatte so ausgesehen als ob das Kostenrechner Fenster geöffnet wurde, jedoch die Daten einer Übersicht geladen wurden.

**Comment by dsiekiera** [comment]
@Darkproduct 
Es wird nix externes heran gezogen. Die Extension ist bis auf *.foe-rechner.de komplett authark.

Sobald man eine Übersicht öffnet, sollte sich das Icon für den Kostenrechner von rot auf grün ändern.  Der erste klick öffnet den Pre-Scann. Geht man dann in ein LG, öffnet sich mit einem zwiten Klick der Kostenrechner.

**Comment by Darkproduct** [comment]
Ok, also hier mal ein paar ausführlichere Tests mit der Option vom pre Scan auf on: (Das Spiel wurde dazwischen immer neu geladen.)
----------
LG Übersich öffnen -> Button wird Grün -> Click -> Fenster erscheint:
Option 1: "Bei xxx ist nichts zu holen."
Option 2: "Übersicht der möglichen LGs" -> Öffnen eines der LGs -> Fenster macht nichts -> Weiterer Click auf den Kostenrechner -> Kostenrechner öffnet sich einwandfrei ohne Probleme.
----------
LG Übersich öffnen -> Öffnen eines LG's -> Kostenrechner öffnen -> Funktioniert wie gewohnt.
----------

Jetzt noch mal mit der Option Pre Scan Off:
----------
LG Übersich öffnen -> Öffnen eines LG's -> Kostenrechner öffnen -> Funktioniert nicht. 
----------

Es scheint also das Problem nur zu geben, wenn die Option vom Pre Scan aus ist.

**Comment by dsiekiera** [comment]
Das klingt echt verwirrend... Ich schaue mir das asap an. Kann nur eine kleine Abfrage sein.
