### ISSUE TITLE
PVP Helper and PVP history.

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1332]
Hi.

I understand why Inno required to remove PVP Helper (because I can see what and when I may plunder).

But I don't understand why Inno required to remove PVP history (when I attaked neighbour, what armies have both of us, lost or win, etc.).
This is OPEN info, I got it after attak and note in my own file.
And Helper just help me not to spent extra time to note this info.

Can you plese talk with Inno to return this info in Helper?

**Comment by outoftheline** [comment]
Convenience (and time, like you said yourself) are the key factors here from my understanding. 

Assumption: As it was so convenient to see what you were up against and change your strategy accordingly, more people attacked their neighbors, as winning became easier.
