### ISSUE TITLE
Foe-Helfer immer wieder bestätigen

### ISSUE THREAD

**Issue by Dude49** [dsiekiera/foe-helfer-extension#1334]
Hallo zusammen,
bei Neustart des Spiel´s und beim Wechsel in eine andere Welt muss jedesmal der Foe-Helfer bestätigt werden,
ich denke nach einem Spieltag mit mehreren wechseln zu den anderen Städten habe ich die Änderungen verstanden
und es wäre schön, wenn ich sie nicht immer wieder auf´s Neue bestätigen müsste ;-)
An dieser Stelle "Danke für eure tolle Arbeit"
Gruß Dude

Win7 64
Firefox 77.0.1  64Bit
de11(Langendorn)
2.5.0.0

**Comment by outoftheline** [comment]
Du musst das Häkchen setzen, dann kommt das Fenster nicht mehr.

**Comment by HAL09001** [comment]
Hi,

ich muss das auf jedem Rechner auf jeder Welt bestätigen, das ist etwas viel. Bei 3 Welten und 5 Rechnern/Browsern sind das 15x bestätigen
Es wäre schön, das entweder 1x pro Rechner oder besser 1x pro Welt zu machen.

**Comment by andrgin** [comment]
Das wäre nur möglich, wenn die Daten mit dem Häkchen auf unseren Server geladen werden, was wir eigentlich nicht machen wollen, schon garnixht wenn der Spieler den Upload auf foe-rechner.de deaktiviert hat.

**Comment by andrgin** [comment]
Hat sich erübrigt, da der Bestätigungsdialog mittlerweile entfernt wurde
