### ISSUE TITLE
Activité JcJ

### ISSUE THREAD

**Issue by S3b08** [dsiekiera/foe-helfer-extension#1335]
Bonjour, 
Depuis la màj assistant du 27.06.2020, je n'ai plus accès à l'assistant JcJ. L'avez-vous retiré?
Mon extension est valide et les termes des modifications acceptées, que faire car c'est un outils que j'utilise beaucoup, svp.
Merci pour votre retour
S3b08

**Comment by Psilemnor** [comment]
Oui il a été retiré suite à revue de l'extension par Inno Games 

https://foe-rechner.de/news/changes-to-the-foe-helper
