### ISSUE TITLE
Suggestion - Add Guild Contributions to Production Overview

### ISSUE THREAD

**Issue by megsterclan** [dsiekiera/foe-helfer-extension#1337]
Two buildings overlooked in the Production Overview - The Arc and Observatory... could these be added so we know how many goods are contributed to the Guild Treasury from these buildings?

**Comment by outoftheline** [comment]
A new tab with guild goods is planned. The statues of honor and airship, as well as atomium will of course show up there, too.

**Comment by megsterclan** [comment]
Excellent news - thanks for the information, outoftheline!

**Comment by andrgin** [comment]
Already implemented
