### ISSUE TITLE
LG Investition Popup

### ISSUE THREAD

**Issue by yyoshii** [dsiekiera/foe-helfer-extension#134]
Hallo,

beim öffnen der Legendären Bauwerkeübersicht
Rathaus -> Neuigkeiten -> Legendäre Bauwerke

erscheint das Popup das die LG Investitionenen übertragen wurden.

Wenn man nun in der Übersicht auf ein LG klickt und dann dort FP einzahlt, dann kommt das Popup für jeden klick von eingezahlten FP, weil die Übersicht im Hintergrund offen ist und anscheinend aktualisiert wird.

In meinem Fall habe ich 2700 FP mit 10er FP Schritten eingezahlt und es kam somit 270 mal das Popup und ich denke es wurde auch jedesmal an den Server übertragen. Irgendwann könnte dies ein Performanceproblem auslösen.

Evtl. könnte man hier eine Funktion einbauen, dass nur jede 1 Minute oder alle 20 Sekunden eine Übertragung durchgeführt wird und das Popup erscheint? 

Gruß,
Yyoshii

**Comment by dsiekiera** [comment]
Macht Sinn. Fragt sich nur warum das so ist.
