### ISSUE TITLE
BUG - production overview for GB

### ISSUE THREAD

**Issue by Psilemnor** [dsiekiera/foe-helfer-extension#1343]
![image](https://user-images.githubusercontent.com/67511740/85948993-5143a300-b954-11ea-83f8-79b063aee500.png)

Please look a the yellow lines on the included screenshot
- Alcatraz is counted twice
- I do not own the Himeji Castle
- Kraken is counted twice

**Comment by andrgin** [comment]
1.) Can you reload the game (F5) and check if it stays the same.

2.) Is the date of your PC correct?

**Comment by Psilemnor** [comment]
![image](https://user-images.githubusercontent.com/67511740/85949735-c618dc00-b958-11ea-8b16-292603c9fca9.png)

F5 solved the issue ! thank you :-)

**Comment by andrgin** [comment]
OK strange. Do you know what you did before opening the production overview?

**Comment by Psilemnor** [comment]
I am new to that (great) tool so I am trying everything ;-)

I had played a lot with all controls and tabs of the production tool, going back and forth

**Comment by Psilemnor** [comment]
Maybe I also opened other windows in the game (GEX, BG, guild mates cities, GB ...)

**Comment by andrgin** [comment]
This happened when visiting another player and opening one of his GBs which added the GB to your Building list
