### ISSUE TITLE
Incidents / Events - Minor Inconvenience

### ISSUE THREAD

**Issue by weltraumvogel** [dsiekiera/foe-helfer-extension#1349]
Was ist das Problem:

Der Counter, wie viele Ereignisse in der Stadt sind, ist großartig. Soweit noch kein Problem.

Allerdings ist er auch "relativ" groß, fast 25% des Buttons werden durch ihn belegt. Wenn man jetzt versehentlich beim Versuch, das Fenster zu öffnen, auf den Counter kommt, geht das Fenster nicht auf. Man muss genau zielen, damit man nicht den Counter trifft.

Verbesserungsvorschlag:
Das Event-Fensters sollte sich auch dann öffnen, wenn man als Grobmotoriker versehentlich den Counter trifft.

----------------

What's the problem:
If you accidentally click the (great!) new counter for incidents, nothing happens.

Improvement:
Make the Counter also clickable, so that even not-so-keen mouse users can open the incident-window at once.

cheers ;-)

**Comment by weltraumvogel** [comment]
Hab gerade gesehen, ist auch in #1295 bereits erwähnt/bemängelt

**Comment by GeniusTimo** [comment]
Ich habe diesen Fehler in der Pull-Request #1350 behoben ✔️

**Comment by andrgin** [comment]
Ist im beta Branch gefixed, wird mit dem nächsten Update ausgeliefert

**Comment by andrgin** [comment]
Ist mit Update 2.5.0.1 gefixed
