### ISSUE TITLE
[Feature Request] Knopf aktualisierung Kostenrechner

### ISSUE THREAD

**Issue by yyoshii** [dsiekiera/foe-helfer-extension#135]
Hallo,

aktuell öffne ich den Kostenrechner, dann investiere ich, schliesse das LG und öffne es wieder damit sich die Anzeige aktualisiert und ich sehe ob alles "OK" ist.

Ich würde gerne einen neuen Knopf vorschlagen -> Aktualisieren, bei dem das Fenster aktualisiert wird. Dieser könnte im Fenster im Header eingebaut werden:

![rechner](https://user-images.githubusercontent.com/11097888/67374049-efd76300-f580-11e9-8d87-7b75cb602e2b.jpg)

Gruß,
Yyoshii

**Comment by yyoshii** [comment]
Vorher:
![2019-10-23_10h44_24](https://user-images.githubusercontent.com/11097888/67375074-632da480-f582-11e9-9508-2d9668ee23e5.png)

Nach dem klicken des Knopfes:
![2019-10-23_10h44_52](https://user-images.githubusercontent.com/11097888/67375093-67f25880-f582-11e9-9af1-4ee44050bb77.png)

**Comment by andrgin** [comment]
Das mit der Aktualisierung hatte ich mir auch schon überlegt.

Das Problem an der Aktualisierung ist, dass die Extension nur die Daten abgreift, die vom Inno Games Server an den Browser gesendet werden.
Würde die Extension selbst eine Abfrage an den Server anstoßen, so greift die Extension aktiv in das Spiel an, was einen Regelverstoß darstellen würde (ähnlich wie ein Skript, das automatisch alle Nachbarn nach LGs durchsucht).

Jetzt bekommt die Extension nicht direkt mit, wenn der Spieler auf den Einzahlen Button drückt, sondern nur indirekt, da das Spiel eine aktualisierte Übersicht aller LGs lädt, wo man nur die Summe aller eingezahlten FPs heraus bekommt ohne die einzelnen Plätze. Das Rückzurechnen dürfte relativ kompliziert werden mit einigen Sonderfällen (Nachbar zahlt gleichzeitig ein, Spieler hat nicht eingezahlt, sondern die Übersicht manuell geöffnet usw.)

Ich mache es immer so, dass ich während dem Einzahlen die bereits eingezahlten FP im Spiel selbst ablese.

**Comment by andrgin** [comment]
Es gibt doch einen Weg, die Ränge raus zu ziehen. Update ist in Arbeit.

**Comment by andrgin** [comment]
Mit dem aktuellen Update wird nun bei Einzahlung automatisch aktualisiert.
