### ISSUE TITLE
Kostenrechner falsch

### ISSUE THREAD

**Issue by FeldiMB** [dsiekiera/foe-helfer-extension#1357]
Hallo

Entweder rechnet der Kostenrechner falsch oder ich schnall die Anzeige nicht.

Bei der Hagia sollte ich 72 ein bezahlen obwohl nur noch 86 offen waren
bei der Arche sollten es 474 sein obwohl 445 reichten.

![Arche](https://user-images.githubusercontent.com/67574301/85977765-83e5ae00-b9dd-11ea-85a3-1714c9fd8686.JPG)
![Hagia](https://user-images.githubusercontent.com/67574301/85977769-847e4480-b9dd-11ea-9de8-081425cef74f.JPG)

In beiden Fällen stimmten die noch offenen FP der Gebäude

**Comment by soulman72** [comment]
Das ist doch die Neuerung: Es werden nur noch Förderungen nach eingetragenen Prozentsatz angezeigt und keine Gewinnberechnungen. Dies wurde als unfairer Vorteil seitens FOE bewertet und muss daher abgeschafft werden, damit das Plugin weiter "legal" bleibt. Mehr Details hier: https://foe-rechner.de/news/aenderungen-am-foe-helfer

**Comment by b-tomasz** [comment]
Bevor du einzahlst, ist die zahl Grün, wenn der Platz safe ist, wenn du ihn mit dem ausgewälten bonus belegst. z.B. bei der 80%
Solange du aber noch nicht 80% eingezahlt hast. Wir dir 445/477 angezeigt. Da du den Platz noch nicht komplett(477) belegt hast. egal ob dieser bereits safe ist oder nicht.
