### ISSUE TITLE
[Feature Request] Güterübersicht Außenstandort - Erweiterungen

### ISSUE THREAD

**Issue by yyoshii** [dsiekiera/foe-helfer-extension#136]
Hallo,

was hälst du davon, bei der Güterübersicht noch eine "Standardspalte" für die Minimalkosten der Erweiterungen hinzuzufügen?

Die niedrigsten Rohstoffkosten erlangt man ja durch 2x2x2x2 zu kaufen. Diese könnte man mit anzeigen und mit in die Berechnung einfließen lassen:
![Gueteruebersicht](https://user-images.githubusercontent.com/11097888/67376557-a557e580-f584-11e9-92b4-82a565a5db6b.png)

Eine weitere Möglichkeit wäre diese Einstellungen durch den Benutzer definieren zu lassen, jenachdem wie er die Erweiterungen bevorzugt zu kaufen.

Einstellungen:
Anzahl Erweiterungen Äxte: 1-X
Anzahl Erweiterungen Met: 1-X
Anzahl Erweiterungen Hörner: 1-X
Anzahl Erweiterungen Wolle: 1-X

Gruß,
Yyoshii

**Comment by dsiekiera** [comment]
Verstehe ich leider nicht so ganz. Was soll dieses 2x2x2x2 bedeuten? Die Anzahl der jeweiligen produzierenden Gebäude?

**Comment by yyoshii** [comment]
Das ist die Anzahl der Erweiterungen die man mit Gütern kauft:

Zuerst 2x mit Äxte, danach 2x mit Met, 2x mit Hörner und zuletzt 2x mit Wolle

Das zumindest ist die niedrigste Anzahl an Gütern die man Investieren kann für Erweiterungen

**Comment by dsiekiera** [comment]
Ahso. Muss ich mal gucken ob das in irgend einem Stream mitgeschickt wird. Dann kann man das easy berechnen und ausgeben lassen.

**Comment by yyoshii** [comment]
https://de.wiki.forgeofempires.com/index.php?title=Kulturelle_Siedlungen:_Wikinger

![image](https://user-images.githubusercontent.com/11097888/67398377-d5b27a80-f5aa-11e9-9f72-cbdf27ea7968.png)

**Comment by andrgin** [comment]
Die noch verfügbaren Erweiterungen werden erst beim Öffnen des Außenpostens übertragen, der Rest ja schon beim Öffnen des Spiels.

Was das 2/2/2/2 angeht, so gibt es hier verschiedene Strategien. Ich spiele normalerweise eher 3/2/2/0, wobei das stark von Durchgang zu Durchgang unterschiedlich ist, je nachdem wie viele Gebäude ich durch das Freischalten mehr unterbringe und wie lange ich sonst auf das jeweils nächste Gut warten müsste.

**Comment by dsiekiera** [comment]
Ich würde das so berechnen lassen, das immer angezeigt würde wie viele Erweiterungen mit dem jeweiligen Gut noch kaufbar wären.
Strategien werden ich keine Vorgeben.

**Comment by yyoshii** [comment]
Vorgeben würde ich das auch nicht. Ich würde die 2er kombi als Standard implementieren, jedoch dann über die Settings eine Möglichkeit schaffen, die der Benutzer definieren kann:

Anzahl Erweiterungen Äxte: 1-X
Anzahl Erweiterungen Met: 1-X
Anzahl Erweiterungen Hörner: 1-X
Anzahl Erweiterungen Wolle: 1-X

Aber das wird evtl. zuviel für eine "einfache" berechnung ;-)

**Comment by krupp58** [comment]
Ich fände es viel besser, wenn über der schwarzen Zeile mit Gebäude und Gütern, also vor der Anzeige der Kupfermünzen , über den Gütern die **Anzahl der jeweils benötigten Güter für die nächste Erweiterung** gezeigt würden.
Das Fenster dient ja dazu eine Entscheidung zu treffen, was als nächstes Produziert wird, da stellt sich halt immer auch die Frage: Erweiterung oder nicht !
Von daher wäre es auch schön in diesem Fenster die **momentane Münzproduktion
** ablesen zu können (für 4/8 Std). So kann man auch sehen ob man nicht doch lieber noch das Einkommen ausbaut.
Wie viele Erweiterungen noch verfügbar sind ist dahingegen ziemlich uninteressant. Entweder es gibt noch welche oder eben nicht (was man ja auch an dieser Art der Anzeige  ablesen kann)
Also etwa so :
![Foe-Helfer-Aussenposten](https://user-images.githubusercontent.com/59014336/71079449-96a83c00-218b-11ea-8c3c-1ebfa992e86e.png)
greetz

**Comment by Darkknightnr1** [comment]
Hallo ich hätte auch noch einen Wunsch den Außenposten betreffend ;-)

Ähm es wäre cool wen da eh was gemacht wird das man eventuell sieht wieviele Ressourcen man in 4 bzw 8 Std. ohne die % Chance bekommt das man sich irgendwie mit der Tagesproduktion die noch verfügbare zeit errechnen kann oder die Oberfläche einem gleich sagt was die Tagesproduktion ist  damit man eventuell doch noch ne Erweiterung kauft um dann mehr Ressourcen zu bekommen.

Liebe Grüße Darki

**Comment by someone97563** [comment]
Aktueller Stand der Entwicklung:

Nächste Erweiterung: (@krupp58)
Ich habe jetzt eine Anzeige der Kosten für die nächste Erweiterung über der Tabelle plaziert.

Münzproduktion: (@krupp58)
Die aktuelle Münz-Produktion wird auch schon für 4 Stunden ausgerechnet.
Hierbei zählt, was JETZT GERADE produziert wird, wenn also jemand 5 min Produktionen macht ist diese Zahl also während dieser 5 Minuten deutlich höher als danach, wenn man wieder eine 4 std Produktion einstellt.
- Ich könnte evtl noch eine Hover-Infobox mit verschiedenen Berechnungen machen, wenn ich an die Werte komme.

Güterbedarf für Erweiterungen: (@yyoshii)
Ich teste eine Möglichkeit, mit der man auswählen kann, welche Erweiterungen man kaufen möchte.
Die Summe dieser Güter wird dann wie vorgeschlagen über der Summe eingefügt.

Freischaltungs Güter summieren: (?)
Ich habe zum Testen einen Haken eingebaut, mit dem man zwischen einzel Preisen und Summen umschalten kann.

Güterproduktion: (@Darkknightnr1)
Ich könnte mir vorstellen mit einer Hover-Infobox Informationen zur Güterproduktion zu machen.
Ob das nun 4 oder 8 Stunden Produktionen sind ist relativ uninteressant. In 40 Stunden schafft man Theoretisch 6 Produktionen von 5 Gütern, aber da man die nicht sofort neustarten kann und evtl. einen festen Tagesablauf hat würde ich von nur 5 Produktionen am Tag ausgehen.

Wenn jemand Vorschläge hat, wie man die Informationen kompakt und verständlich unterbringen kann, würde ich mich über die Rückmeldung freuen.
