### ISSUE TITLE
Kleiner Code Tweak für den Kostenrechner

### ISSUE THREAD

**Issue by sdn-br** [dsiekiera/foe-helfer-extension#1364]
Hab einen kleinen Code Tweak in calculator.js durchgeführt. Diff anbei
[calculator-code-tweak.txt](https://github.com/dsiekiera/foe-helfer-extension/files/4846945/calculator-code-tweak.txt)

**Comment by scibuff** [comment]
Not bad, but I'd use the ES6 template syntax

```
investmentSteps.forEach( bonus => {
    h.push(`<button class="btn btn-default btn-toggle-arc" data-value="${bonus}">${bonus}%</button>`);
});
```

**Comment by sdn-br** [comment]
even better 👍

**Comment by dsiekiera** [comment]
I like it too. Put this combination right in.

**Comment by dsiekiera** [comment]
Kostenrechner
![Bildschirmfoto 2020-06-29 um 19-48-26](https://user-images.githubusercontent.com/834814/86039105-3fd8c480-ba42-11ea-86e6-59d1b708fbda.png)

Eigenanteilsrechner
![Bildschirmfoto 2020-06-29 um 19-53-18](https://user-images.githubusercontent.com/834814/86039107-40715b00-ba42-11ea-98f3-a63045dbc406.png)

Habe es in beide Rechner integriert. Danke für die Zusendung @sdn-br

**Comment by sdn-br** [comment]
Code will lead to duplicated Button if Current Arc Bonus is similar to 80, 85, 90

**Comment by andrgin** [comment]
Thanks, but we already fixed that ;-)
