### ISSUE TITLE
Incidents indicator error.

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1365]
Hi.

Counter on icon shows zero, but Incidents Helper shows 2 incidents (screenshot).

![2006292016](https://user-images.githubusercontent.com/35531243/86035895-b4613280-ba45-11ea-8559-b1b5e19a710e.png)

**Comment by outoftheline** [comment]
Thank you, see also #1321 

We will remove the counter once it's zero to reduce confusion.
