### ISSUE TITLE
Bug: Falsche Anzeige im Eigenanteils-Rechner

### ISSUE THREAD

**Issue by Nerd2020** [dsiekiera/foe-helfer-extension#1367]
Beim wiederkehrenden Quest "research 2 technologies" wird im Fenster des Eigenanteilsrechner jedesmal angezeigt, der aktive Schleifenquest habe noch 2 fp offen, selbst wenn man den (im FMA nur 1 Schleife) offensichtlich nicht aktiv haben kann.
![grafik](https://user-images.githubusercontent.com/67139127/86041127-7f54e000-ba45-11ea-9f82-5f5dd3e838d3.png)

**Comment by GeniusTimo** [comment]
Der Fehler sollte im kommenden Update behoben sein ✔️

**Comment by andrgin** [comment]
Wurde bereits mit 2.5.0.1 gefixed: https://github.com/dsiekiera/foe-helfer-extension/issues/1318
