### ISSUE TITLE
Suggestion - Offline Base editor

### ISSUE THREAD

**Issue by stonekhold** [dsiekiera/foe-helfer-extension#1368]
Why Can't someone create a offline editor to setup your base buildings and roads. The in-game reconstruction is a joke. I should be able to plan and create offline then add to the game.

**Comment by outoftheline** [comment]
We're doing web based stuff. 

So unless you have a suggestion to improve https://foe-rechner.de/docs/2/citymap/ we're not the right ones to approach.

**Comment by dsiekiera** [comment]
This would be never possible. U cant send data into the game. 
With our planner you can create a city, save it as PNG or PDF and then rebuild it in the game. Everything else is technically not possible.

**Comment by TrueLolek** [comment]
since the last update, the weaker players have gone bad..because i don't see the finished production so i attack everyone and when i'm already there i take what i know.i've only gone to the point so far.just for everything. it I do not know who was good?
