### ISSUE TITLE
Bug: Färberei wird nicht in die Stadtansicht übertragen

### ISSUE THREAD

**Issue by Nerd2020** [dsiekiera/foe-helfer-extension#1371]
Siehe Screenshots

![Screenshot_20200629_214019](https://user-images.githubusercontent.com/67139127/86048638-21c69080-ba51-11ea-8758-79b654cdf63a.png)
![Screenshot_20200629_214115](https://user-images.githubusercontent.com/67139127/86048714-43277c80-ba51-11ea-95c1-84d9a7492c01.png)

**Comment by outoftheline** [comment]
gerade getestet, hier funktioniert's
