### ISSUE TITLE
Bug: Wiederkehrende Quest

### ISSUE THREAD

**Issue by Malo1508** [dsiekiera/foe-helfer-extension#1372]
Mir ist auf Mount Kilmore, in der Eisenzeit aufgefallen, das beim öffnen des Zeus im Eigenanteilsrechner 2FP als aktiver Schleifenquest angezeigt werden, obwohl Doppelte Forschung in der wiederkehrenden Quest an der Reihe ist und nicht "Sammel FP".

Scheint allerdings nur in der Eisenzeit zu sein....
Auf 2 anderen Welten, beider in der JHW, ist das nicht der Fall.

**Comment by andrgin** [comment]
Wurde mit dem Update 2.5.0.1 gefixed
