### ISSUE TITLE
[2.5.0.1][infoboard] Bug: Nachrichten in der Info-Box erscheinen doppelt

### ISSUE THREAD

**Issue by weltraumvogel** [dsiekiera/foe-helfer-extension#1375]
Wie der Titel schon sagt: 
* Jede Nachricht aus Nachrichten im Postfach erscheinen in der Infobox doppelt.
* Every message from mails in the mailbox appear twice in the Infobox

**Comment by weltraumvogel** [comment]
![image](https://user-images.githubusercontent.com/10573205/86127216-d3ac9e00-badf-11ea-956f-56459d31f2d6.png)

**Comment by GeniusTimo** [comment]
Ich bin auf der Suche nach der Quelle des Problems, vielen Dank für die Meldung ⏳

**Comment by GeniusTimo** [comment]
Nach einigem Versionschaos habe ich den Bugfix nun als Pull-Request vorgeschlagen 👍

**Comment by SillyDevil** [comment]
problem still exist, but its two messages now
![Screenshot_2](https://user-images.githubusercontent.com/65982368/87538368-63377c80-c69c-11ea-867a-87cc4d8dacd3.png)
