### ISSUE TITLE
Cape Canaveral not in GB investment tool?

### ISSUE THREAD

**Issue by ikkeahja** [dsiekiera/foe-helfer-extension#1377]
I was checking this tool and i noticed it's not in there. Is there a reason why it isn't?

![](https://i.gyazo.com/9712cee7f74e5c8bc38696d2cf010a0a.png)

**Comment by GeniusTimo** [comment]
Can you be more specific? 😅

**Comment by ikkeahja** [comment]
added an image of my tool, is the cape canaveral no showing because there's a maximum amount of lines?

I did just build it and it's still in the mud, not sure if this caused this.

**Comment by GeniusTimo** [comment]
For me the Cape is shown and yes the lines are limited (otherwise this would be quite overcrowded)
![grafik](https://user-images.githubusercontent.com/47282153/86148998-a79f1600-bafb-11ea-9f06-f48f28af78fa.png)

**Comment by ikkeahja** [comment]
thanks for the quick reply, will check when it's out of the mud and put it on owned only.
guess this one can go :)
