### ISSUE TITLE
LG Inventions / greatbuildings.js

### ISSUE THREAD

**Issue by soulman72** [dsiekiera/foe-helfer-extension#1385]
There seems to be a calculation bug for the Castle Himeji (Burg Himeji) when it comes to the average FP values:

From Level 5 it differs to the values from wikipedia. Based on the following formula I've calculated the first 10 levels:

`AvgFP = qty * rate * 18.5`

18.5 comes from the chances of the forge point packages (25% 10, 12% 50 and 5% 200)

So finally my calculation results in the following avg rates:
![image](https://user-images.githubusercontent.com/2987649/86228149-50965100-bb8e-11ea-9aae-366bfd54d1a2.png)

1. 5.18
2. 6.66
3. 8.14
4. 9.62
5. 11.1
6. 12.58
7. 14.06
8. 15.54
9. 17.02
10. 18.5

From the sourcecode in greatbuildings.js I extracted the following list of FPs:
`[5.18, 6.66, 8.14, 9.62, 13.875, 15.725, 17.575, 19.425, 21.275, 23.125, `
 
As you can see it differs from level 5... 

Link:
[https://de.wiki.forgeofempires.com/index.php?title=Burg_Himeji](https://de.wiki.forgeofempires.com/index.php?title=Burg_Himeji)

**Comment by andrgin** [comment]
From lvl5 Quantity increases to 5. Atlvl10: 5*25% = 1.25

**Comment by soulman72** [comment]
Sorry, my bad! There was indeed an error in my excel formula...
