### ISSUE TITLE
Bug: Falsche Zuordnung Gebäude-Kit

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#1387]
Moin, ich glaube hier ist irgendwas falsch:

![Anmerkung 2020-07-01 132620](https://user-images.githubusercontent.com/17932878/86238817-7a577400-bb9e-11ea-938a-2a5ae258d11e.png)

Jedenfalls glaube ich nicht, dass ein Wunschbrunnen ein Diplomatische-Geschenke-Kit ist, was übrigens ein Kit ist, von dem ich bisher noch nie gehört habe :)

**Comment by GeniusTimo** [comment]
Aus dem **Diplomatische Geschenke-Kit** kann man Wunschbrunnen, Wunschbrunnen-Schrumpf-Kit oder ein Renovierungs-Kit wählen
→ [Ein Blick ins Wiki](https://de.wiki.forgeofempires.com/index.php?title=Weltraumfrachter)

**Comment by frank42hh** [comment]
Oh, dann sorry für den überflüssigen bugreport :)

**Comment by dsiekiera** [comment]
@frank42hh das zuordnen dieser Kits ist eh ein Abenteuer für sich. 
Das neue Hippodingsbums hat wieder einen "Kit-Kennung" aber die letzten Kits hatten das gar nicht. Daher kann selbst Inno das nicht mal im eigenen Inventar gruppieren.
