### ISSUE TITLE
Verhandlungsassistent innerhalb der Gildengefechte geht nicht

### ISSUE THREAD

**Issue by Andi-Berlin** [dsiekiera/foe-helfer-extension#1391]
wie der Titel schon sagt, ist seit dem letzten Update kein verhandeln mit dem Assistenten möglich. Das Fenster öffnet sich einfach nicht bei den Gildengefechten. In der Gildenexpedition wird der Assistent allerdings gestartet, wenn man eine Verhandlung eröffnet.

cheers Gawein
________________________________________________

Version 1.181.91412ab38b9 (30.06.2020 09:24), 
Sir Gawein (2050156), de7, de_DE, 
WEB 7,1,1,0, 
Windows 10, 
Chrome/83.0.4103.116, 1920x1009, OpenGL Vendor=WebKit Version=WebGL 2.0 (OpenGL ES 3.0 Chromium) Renderer=WebKit WebGL GLSL=WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium) (512 MB VRAM)

**Comment by dsiekiera** [comment]
Das ist beabsichtigt. Siehe folgende Infos: [https://foe-rechner.de/news/aenderungen-am-foe-helfer](https://foe-rechner.de/news/aenderungen-am-foe-helfer)

**Comment by Andi-Berlin** [comment]
schade, war tatsächlich ein Vorteil ;-)
