### ISSUE TITLE
Have the Calculator for my own GMs

### ISSUE THREAD

**Issue by lnplnp** [dsiekiera/foe-helfer-extension#1392]
Hi,

Could we get the #costCalculator for our own GMs ?

**Comment by dsiekiera** [comment]
Öhm, for what? The self contribution calculator is not enough for you?

**Comment by lnplnp** [comment]
To know how many forge point it need to secure a place for exemple.

**Comment by GeniusTimo** [comment]
Maybe you are searching for this one @lnplnp?

![grafik](https://user-images.githubusercontent.com/47282153/86362806-2455ff80-bc76-11ea-8759-04b4a8167749.png)

![grafik](https://user-images.githubusercontent.com/47282153/86362949-5ff0c980-bc76-11ea-94d3-44dafb612870.png)

**Comment by lnplnp** [comment]
I would like to know how many forge points it need to secure une place.

@GeniusTimo Thanks but I know this tool ;o)

**Comment by andrgin** [comment]
You need to pay "owner to add" to secure the place below. In thus case 298FP so P1 and P2 are safe.

**Comment by lnplnp** [comment]
Thanks
