### ISSUE TITLE
Guild Related Suggestions

### ISSUE THREAD

**Issue by roadkill951381** [dsiekiera/foe-helfer-extension#1393]
Can you add some guild related information to help Guild Masters?

1.) Date each member joined the guild
2.) Who was booted/removed from the guild
3.) Who left the guild and how many times they left
4.) Which Members completed the 1st/2nd/3rd/4th level of Guild Expedition by week
5.) Which Members Aided me and how often over the past month?
6.) Typical Guild Percentage Completion of Guild Expedition
7.) Number of members participating in battlegrounds, guild versus guild and guild expedition
8.) Who read a guild (or group) message, who deleted it without reading.
9.) Language each member uses (thinking browser language or system language?).  Anything to help us communicate better with the members.
10.) List of inactive members and how long they have been inactive
11.) Message a group of inactive members, or members that did not participate in guild expedition or battlegrounds.

I cannot think of anything else.  But if you could add that information, you just save guild masters/leaders a lot of time.  

Thank you.  AWESOME TOOL!  I no longer use 5 of my google sheets because of your tool.  Thank you!!

**Comment by outoftheline** [comment]
1.) Date each member joined the guild
Such information is not available.

2.) Who was booted/removed from the guild
Could only be logged as-you-go, not later on. Why is that info important? I lead a guild and know the people I kick.

3.) Who left the guild and how many times they left
Same as 2.

4.) Which Members completed the 1st/2nd/3rd/4th level of Guild Expedition by week
Available on the website if you transmit the data.

5.) Which Members Aided me and how often over the past month?
Also available on the website, but you cannot filter by guild mates (yet).

6.) Typical Guild Percentage Completion of Guild Expedition
Each week is listed on the website.

7.) Number of members participating in battlegrounds, guild versus guild and guild expedition
Just the number?

8.) Who read a guild (or group) message, who deleted it without reading.
Information not available. 

9.) Language each member uses (thinking browser language or system language?). Anything to help us communicate better with the members.
I don't understand. Each server has a game language. Why would you chose a server where you dont understand the language?

10.) List of inactive members and how long they have been inactive.
As a guild leader you have the ingame fots (blue, yellow, red). Why is that important?

11.) Message a group of inactive members, or members that did not participate in guild expedition or battlegrounds.
That's automation, so not possible.
