### ISSUE TITLE
Nachbarschaftsproduktionen

### ISSUE THREAD

**Issue by dtivil** [dsiekiera/foe-helfer-extension#14]
Die neue Ordnung ist hilfreich, allerdings war die grüne Schrift ein größerer Eyecatcher beim schnellen durchklicken, nach kurzer Rücksprache mit ein paar Freunden, sehen das offenbar auch andere so. Somit könnte man zusätzlich zu der Neuen Fertige/Laufende Kategorisierung noch die grüne Schrift wieder einführen? 👍

**Comment by Selene443Foe** [comment]
Ich möchte mich ebenfalls erfreut zu der neuen Sortierung äußern. Gleichfalls denke ich auch das die grüne Schrift wieder Einzug finden sollte :)

**Comment by dsiekiera** [comment]
Is ja gut 😄
