### ISSUE TITLE
Resourcen Übersicht

### ISSUE THREAD

**Issue by SkateScout** [dsiekiera/foe-helfer-extension#140]
Hi, wie wäre es wenn man bei den Resourcen noch einen Tab mit Zufriedenheit macht?
Außerdem wäre es Klasse wenn man den Plan vom Plündern auch für die Eigene Stadt 
hat um Gebäude zu suchen.

**Comment by andrgin** [comment]
Bei der eigenen Stadt kannst du doch sowieso immer schauen, welche Gebäude ein Symbol zum Einsammeln.

**Comment by SkateScout** [comment]
Es geht darum wenn z.b ein Signalfeuer hinter einem Großen LG verdeckt ist und Man sucht es.
Oder eine Kleine Deko die man für das Event abreisen und neu Aufbauen will.

**Comment by andrgin** [comment]
Achso ich dachte du meinst die Liste mit den fertigen Ressourcen.

**Comment by dsiekiera** [comment]
Wunsch verstanden. Aber derzeit liegt der Fokus auf Bugfixing.
Wenn alle anderen Module laufen, die derzeit überarbeitet werden, gibt es
wieder die grosse Wünschestunde 😅

LG, mainline
