### ISSUE TITLE
Ereignisse auf Strassen

### ISSUE THREAD

**Issue by Thomy1967** [dsiekiera/foe-helfer-extension#1407]
Hallo zusammen

Bei mir werden wieder Ereignisse auf Strassen angezeigt, allerdings sind keine zu finden.
Ich habe alle Gebäude in den Umbau gepackt, und trotzdem nicht gefunden.
Dies betrifft nur die einfachen Strassen, auf den doppelten wird richtig angezeigt und 
der Fehler war in der vorherigen Version nicht vorhanden.

Vielen Dank für eure tolle Arbeit

Grüsse

Thomy

Windows 10 64 Bit
Chrome Version 83.0.4103.116 
de10 (Korch)
2.5.0.1 - Deutsch

**Comment by GeniusTimo** [comment]
Ich war neulich auch einige Minuten auf der Suche nach so einem blöden Hindernis und habe es schlussendlich auch gefunden - bist du dir zu 100% sicher, dass dieser Baum nicht da ist? Ansonsten können wir via Discord gerne gemeinsam suchen 😉

**Comment by Thomy1967** [comment]
Ich habe hier einen Screenshot ohne Gebäude, sofern das was hilft und erlaubt ist 

![03-07-_2020_18-06-48](https://user-images.githubusercontent.com/67797521/86485102-23959a00-bd58-11ea-81a1-03f956a69b02.jpg)

**Comment by GeniusTimo** [comment]
Kannst du das Helfer-Popup daneben öffnen?

**Comment by Thomy1967** [comment]
Kein Problem, 
und dein Tipp war richtig, es handelt sich in der Tat um einen Baum 😉

![Helfer](https://user-images.githubusercontent.com/67797521/86486570-e7643880-bd5b-11ea-973e-b2ec17f5b0a7.jpg)

**Comment by dsiekiera** [comment]
Ähh... ja.

Immer wieder gern 😅

Am Fr., 3. Juli 2020 um 18:36 Uhr schrieb Thomy1967 <
notifications@github.com>:

**Comment by andrgin** [comment]
Meines Wissens nach gibt es im Umbaumodus keine Ereignisse auf den Straßen.

**Comment by Th3C0D3R** [comment]
Richtig, im umbaumodus werden keine Ereignisse  mehr angezeigt, das ging als der Umbaumodus noch neu war

**Comment by Thomy1967** [comment]
Diese Aussage stimmt so nicht 100%!
Die Ereignisse um die Stadt herum bleiben auch im Umbaumodus stehen und sichtbar, gerade überprüft. 
In einem weiteren Schritt habe ich die Browserdaten gelöscht, den Browser neu gestartet, und siehe da das Ereignis war ohne grosse Mühe sichtbar. Nun habe ich wieder auf den Umbaumodus gestellt und das Ereignis war weg. Allerdings kommt es jetzt auch nach 3 maligem Daten löschen nicht wieder zum Vorschein. Das Problem scheint also eher auf dem FoE Server zu liegen als beim Helfer. Wie ich jetzt daran kommen soll, bleibt mir ein Rätsel aber ich denke meine Meldung kann als gelöst bezeichnet werden.

**Comment by Thomy1967** [comment]
Danke für eure Rückmeldungen
