### ISSUE TITLE
Fehlerndes Info Fenster für Spielerauswahl

### ISSUE THREAD

**Issue by SkateScout** [dsiekiera/foe-helfer-extension#1410]
Beim öffnen des Trainingsspiels fehlt das Fenster mit dem Tipp welcher der Günstigste Spieler ist. (V: 2.5.0.1)

**Comment by SkateScout** [comment]
Vermutlich bei dem Löschen des eventquest.js zum verhindern der Eventaufgaben versehentlich mit zum Opfer gefallen.

**Comment by andrgin** [comment]
Hast du die Beta installiert. In der 2.5.0.1 müsste die Spielerauswahl noch drin sein, in der Beta war sie 2 Tage draußen.

**Comment by SkateScout** [comment]
Jepp das war das Problem. Scheine gerade eine Ungünstige Beta Version erwischt zu haben.
Wäre es möglich das man in der Version die SVN/GIT Version automatisch mit Commits einbaut?
Dann ist auch bei Betas immer der stand klar.

**Comment by andrgin** [comment]
Normalerweise sollten die Betaspieler wissen, dass sie eine Extension manuell eingebunden haben :P

Ansonsten sollte Beta oder nicht Beta im Einstellungsmenü bei der Versionsnummer stehen.
