### ISSUE TITLE
Zusammenlegen von "unwichtigen" Buttons

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#1413]
Moin,

da mir nach und nach die Seitenleiste selbst auf einem 27" Monitor zu groß und damit irgendwie unübersichtlich wird, war ich am überlegen, wo man was einsparen könnte, und dabei ist mir sofort dieses aufgefallen:

![Anmerkung 2020-07-04 155401](https://user-images.githubusercontent.com/17932878/86513957-9c572d80-be0e-11ea-8073-a0c0b90035f8.png)

Der unterste Button "Einstellungen" ist super, die drei Buttons oben drüber sind "Fehler / Wünsche", welcher nur ein Link zum github ist, "Frage / Antwort", welches ein Link zur Hilfeseite auf foe-rechner.de ist, und "Forum", welches - ihr ahnt es schon - ein Link zum Forum ist.

Ich möchte gern vorschlagen, diese Module, die nur einen Link darstellen, zu entfernen und diese drei Links im oberen Bereich des Einstellungsmenüs unterzubringen. Zum Beispiel da, wo auch der "Changelog" Link sich ja auch bereits befindet:

![Anmerkung 2020-07-04 155851](https://user-images.githubusercontent.com/17932878/86514050-4d5dc800-be0f-11ea-9cf2-d847a6890779.png)

Macht die Leiste wieder ein klein wenig übersichtlicher :)

**Comment by andrgin** [comment]
Ja würde meiner Meinung nach Sinn machen, die gleich ins Einstellungsmenü zu verfrachten. Das wird von uns gerade überarbeitet.

**Comment by outoftheline** [comment]
Teil des nächsten Updates:
![image](https://user-images.githubusercontent.com/7482863/86538877-0c41e280-bef9-11ea-9302-922ea0100306.png)

**Comment by Morgage** [comment]
Buenas tardes, se puede agregar un nuevo item que muestre cuantos participantes estan leyendo el chat gremial en el momento?, algo que sea parecido al que muestra cuantos han batallado en Campos de Batalla del Gremio.
Es porque tenemos espias en nustro gremio y leen el chat y pasan coordenadas de gvg a gremios enemigos.
Muchas gracias, y ojala se incluya esa opcion entre las nuevas actualizaciones

**Comment by GeniusTimo** [comment]
We can't retrieve if someone reads a chat. Therefore this is not possible for technical reasons @Morgage.

**Comment by Morgage** [comment]
> No podemos recuperar si alguien lee un chat. Por lo tanto, esto no es posible por razones técnicas @Morgage .

Gracias!!
