### ISSUE TITLE
Infobox Limitieren

### ISSUE THREAD

**Issue by SkateScout** [dsiekiera/foe-helfer-extension#1416]
Hallo, wenn bei der GeX oder GG viel los ist und Bekommt die Infobox sehr viele Einträge was den Browser ausbremst.
Gibt es eine Möglichkeit das man in den Einstellungen angeben kann das nur noch die letzten N Einträge behalten werden.
Also das z.b. immer auf die letzten 20 Einträge begrenzt wird.

**Comment by Th3C0D3R** [comment]
Möglich wäre das ja 😊
