### ISSUE TITLE
Ereigniszähler zeigt nicht immer richtig an

### ISSUE THREAD

**Issue by AngelaKraeuterhexe** [dsiekiera/foe-helfer-extension#1421]
Hallo,

ich habe festgestellt, dass er Ereigniszähler nicht immer die richtige Zahl anzeigt, ich hatte 6 Ereignisse in der Liste, er zeigte rechts aber nur eine 3 an.
Aber auch umgekehrt, 0 waren in der Liste und eine 1 wurde angezeigt.

LG

**Comment by GeniusTimo** [comment]
Dieser Bug wird in der nächsten Version behoben sein ✔️

**Comment by GeniusTimo** [comment]
Duplicate of #1321
