### ISSUE TITLE
Stop showing GBG window to users that do not play GBG or make a setting to turn it off

### ISSUE THREAD

**Issue by symbion6** [dsiekiera/foe-helfer-extension#1422]
Scenario: 
* I do NOT play GBG, played it once a couple of weeks a go, but stopped playing. 
* I get a GBG stats window - that's useless to me -  in my face everytime I open FoE, every day, multiple times a day
* I do not have an option to turn off this window, not in the settings, not anywhere else

Please stop showing this window to users that do not play GBG OR make a setting to turn it off, that's the least you could do.
The rest of the extension is great, but this is very annoying and unnecessary.

**Comment by GeniusTimo** [comment]
Can you attach a screenshot? I don't know which popup you mean 🙈

**Comment by outoftheline** [comment]
So by saying you don't play it, you mean you dont participate at all and cannot open the building, correct? 
Which browser are you using?

**Comment by andrgin** [comment]
Can you use the bugreport template please.

I have read reports about this issue, but have never experienced it myself.

**Comment by jbaboval** [comment]
Your bot is causing it to open....

**Comment by outoftheline** [comment]
@jbaboval Bot meaning another tool? 

Would make sense. If a bot does a request and gets a response, the window could open.
If this is the case, we're not to blame. Also, we wouldn't recommend using a bot.

**Comment by Th3C0D3R** [comment]
Can you show us a picture of the window showing while not in GBG? That would be great <-- insert meme

**Comment by andrgin** [comment]
We do not give any support for running tools that are actively sending requests to the Inno server which is a clear violation of game rules.
We suggest that you remove it immediately as such tools may (and most likely will) get your account banned.

**Comment by symbion6** [comment]
Wow that was a quick analysis. Thanks for the effort. You are right, I am using power tools and I had no idea this was in violation of game rules. My apologies for blaming FoE Helper and drawing conclusions too early. All the best and good luck
