### ISSUE TITLE
Eigenanteilsrechner gibt falsche Werte an

### ISSUE THREAD

**Issue by Yusikara** [dsiekiera/foe-helfer-extension#1426]
Ich habe den Eigenanteilsrechner von FoE im Spiel am PC geladen. Wenn ich mein CdM Stufe 3 aufmache, um die Platze anzuzeigen, sehe ich hier auf P3 eine Belohnung von 5 FP ohne Arche-Boni. Der FoE-Helfer sollte mir hier 10 FP zum Einzahlen anzeigen, ziegt mir aber eine Belegung von 2 FP an und einen Eigenanteil von 11 FP bei noch verbleibenden 13 FP bis zum leveln.

**Comment by Th3C0D3R** [comment]
Also ich hab gerade nachgeschaut, bei mir wird für Level 3 auf 4 für P3 eine Belohnung von 10 FP angezeigt.

**Comment by andrgin** [comment]
Kannst du einen Screenshot posten.
