### ISSUE TITLE
Ingame Eigenanteils-Rechner rundet ab statt auf

### ISSUE THREAD

**Issue by derklausi** [dsiekiera/foe-helfer-extension#143]
Hallo,
ich hatte immer eine Abweichung zur Berechnung zwischen der Webseite und ingame. Immer nur paar Punkte.
Der Ingame-Rechner rundet die Anteile für die Plätze ab. In der Praxis, zumindest bei uns, und auch auf der Webseite, wird immer aufgerundet.
Kann das korrigiert werden?
Ist sonst nervig, wenn man die Kopierfunktion nutzen will :)
Grüße

**Comment by dsiekiera** [comment]
Hey derklausi,

Der Eigenanteils-Rechner ist von Grund auf neu geschrieben worden.
Es sind auch einige neue Features drin und clever ist das Teil auch noch.

Lass dich überraschen 😉

**Comment by derklausi** [comment]
Dann bin ich mal gespannt... bekommt man das update automatisch?

**Comment by dsiekiera** [comment]
Ja klar. Da öffnet sich dann ein neuer Tab mit allen Changelog Infos.
