### ISSUE TITLE
Idea: turn off unused icons in Helper Bar

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1431]
Hi.

Helper increases functionality, and it is good.
Each function has own icon - it's right.
But now I have 3 "screens" of icons - some of them I never use...

I think if we have possibility to hide some icons - it will be helpfull.

**Comment by dsiekiera** [comment]
Use Drag&Drop to sort the unneeded icons down and limit the length to your desired height.

**Comment by dsiekiera** [comment]
Duplicate of #1395
