### ISSUE TITLE
Please add an 92% option to the GBG Calculator.

### ISSUE THREAD

**Issue by MaxDrown** [dsiekiera/foe-helfer-extension#1435]
This is for the very popular 100 Arc.

**Comment by outoftheline** [comment]
![image](https://user-images.githubusercontent.com/7482863/86622084-95235180-bfbf-11ea-9d35-0f83ff520fa4.png)

You can always put any value in here and it saves.

**Comment by outoftheline** [comment]
you can now add it yourself :)
