### ISSUE TITLE
Vorschlag: Anzeige Zeitalter der Bauwerke 

### ISSUE THREAD

**Issue by MichaStar72** [dsiekiera/foe-helfer-extension#1438]
Hallo,
eine Idee: Markieren (farblich oder per Text oder Symbol) des Zeitalters der Bauwerke auf der Stadtübersicht.
Dadurch könnte man schnell erkennen, welche Gebäude sich lohnen in ein höheres ZA zu bringen.
Dieses Feature sollte den Regeln entsprechen, da die Informationen sowieso vorhanden sind.
Grüße
Micha

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2020-07-07 um 19-31-05](https://user-images.githubusercontent.com/834814/86819777-6de48700-c088-11ea-8687-3245df18372d.png)

**Comment by MichaStar72** [comment]
Danke... sehr gut.
Wäre es auch möglich, auf der Übersicht für jedes Zeitalter ein Symbol pro Gebäude anzuzeigen?

**Comment by dsiekiera** [comment]
Ich weiß nicht genau wie ich das veranstalten sollte. Zumal es viele
verschiedene sind und es keine Icons für ZAs gibt.

**Comment by MichaStar72** [comment]
Alles klar, war nur eine Idee... mit der Bezeichnung beim Mouse-over ist es ja auch schon super.
Danke dir
