### ISSUE TITLE
"Vorab-Scan"-Fenster verschoben

### ISSUE THREAD

**Issue by Wafsitar** [dsiekiera/foe-helfer-extension#144]
Das Fenster für den "vorab"-scan ist bei mir in die obere rechte Ecke verschoben, wenn ich es öffne. und zwar so weit dass ich es weder verschieben kann, noch schließen kann. das einzige was funktioniert um es "loszuwerden" ist das spiel neu zu laden. de- und reaktivieren des tools sowie komplett entfernen und neu installieren hat nicht funktioniert. Gibt es dafür eine Lösung oder hat jemand eine Idee?

**Comment by dsiekiera** [comment]
Guck mal bitte ins Forum. Dort gibt es einen Beitrag der das behandelt.

In der nächsten Version gibt es einen Button der das beheben kann 😅

LG, mainline

**Comment by andrgin** [comment]
In der aktuellen Version gibt es einen Button "Box Koordinaten löschen" im Einstellungsmenü.
Weiters sollte ab jetzt verhindert werden, dass jemand die Fenster zu weit nach oben schieben kann.
