### ISSUE TITLE
info box

### ISSUE THREAD

**Issue by KingFred5** [dsiekiera/foe-helfer-extension#145]
die infobox hängt an der oberen leiste , anscheinend im unsichtbaren bereich und lässt sich nicht mehr verschieben
![Ashampoo_Snap_Donnerstag, 7  November 2019_20h48m52s_002_Chrome Legacy Window](https://user-images.githubusercontent.com/57503977/68422241-152eb880-01a0-11ea-88af-8874eff6cd2a.png)

**Comment by dsiekiera** [comment]
Ich habe eben gerade ein Update eingereicht mit einer Neuerung.

Wenn Du das Update erhalten hast, wechsel bitte InGame zu den Einstellungen und scroll ganz runter.
Klick auf den Button und lade das Spiel mit F5 neu.

![Bildschirmfoto 2019-11-07 um 21-27-05](https://user-images.githubusercontent.com/834814/68424963-5f666880-01a5-11ea-8a98-3616a5a25f81.png)
