### ISSUE TITLE
Request: Rescale Large Data Values on Charts

### ISSUE THREAD

**Issue by franzalex** [dsiekiera/foe-helfer-extension#1456]
When certain individual values are significantly higher than the rest, it is displayed in such a way that all the other values are too close to the zero line. A demonstration of this can be seen in the screenshot below:  
![image](https://user-images.githubusercontent.com/7560066/86868306-f9c7d480-c0c3-11ea-9947-f30e95caeb02.png)
Note how in this chart for my _No Age_ data, the peak of the coins value effectively flattens the other values.  

By scaling the same data with the cube root function (i.e. in Excel: ```=POWER(cell_reference, 1/3)```), I was able to get results that scale down the very high values. as seen in the chart below:    
![image](https://user-images.githubusercontent.com/7560066/86868405-27148280-c0c4-11ea-9ded-11fdb9ee55f1.png)  
It is observable that after scaling the data, it is now easier to see and track the changes in values of the tavern, medals and diamonds.

Is it possible to perform a similar kind of scaling on the data before plotting them in the statistics chart?  
Thanks

**Comment by SkateScout** [comment]
Maybe an Checkbox that toggle to LOG Scale.
this is more common than than QubicRoot Scale.

**Comment by GeniusTimo** [comment]
If you click on the good with the high rash in the caption, it may scale more appropriately 😉
Would solve this issue for my purposes ✔️

![grafik](https://user-images.githubusercontent.com/47282153/86922303-b48bbd00-c12c-11ea-9103-a42520e3eb50.png)
![grafik](https://user-images.githubusercontent.com/47282153/86922364-c9685080-c12c-11ea-9980-7d7025fa14e4.png)

**Comment by andrgin** [comment]
I dont think rescaling makes much sense because when rescaled you will not be able to see increase/decrease of coins any more.
I see no reason to analyze diamonds and coins on the same graph so I think it is better to just deselect the things you dont need.

**Comment by franzalex** [comment]
> I dont think rescaling makes much sense because when rescaled you will not be able to see increase/decrease of coins any more.
> I see no reason to analyze diamonds and coins on the same graph so I think it is better to just deselect the things you dont need.
> 
> @andrgin 


I am not the one selecting to view diamonds and coins on the same graph; _the extension puts them together when you select **No Age**_.

**Comment by GeniusTimo** [comment]
And as I mentioned you could disable them by clicking on them in the caption 👀
![grafik](https://user-images.githubusercontent.com/47282153/86944940-b5324c80-c148-11ea-8814-3d1dd44c83b1.png)

**Comment by andrgin** [comment]
They extension puts them all together because they all have the era "NoAge".

**Comment by franzalex** [comment]
> If you click on the good with the high rash in the caption, it may scale more appropriately 😉
> Would solve this issue for my purposes ✔️
> 
> ![grafik](https://user-images.githubusercontent.com/47282153/86922303-b48bbd00-c12c-11ea-9103-a42520e3eb50.png)
> ![grafik](https://user-images.githubusercontent.com/47282153/86922364-c9685080-c12c-11ea-9980-7d7025fa14e4.png)
>
> @GeniusTimo 

Thanks for the information. I did not realise that you can _drag_ over a specific area of the graph to zoom in.  
With that, there is no need for this feature request so I will close it.

Thank you very much.
