### ISSUE TITLE
Calculator not calculating right

### ISSUE THREAD

**Issue by SunnyDayCloudyNight** [dsiekiera/foe-helfer-extension#1457]
The calculator before the update used to show snipable spots, highlighted in green. Now it shows those snipable spots at just a flat rate, or at a break even rate, even though it very well is snipable at a lower cost, it doesn't show that. For example, if that spot is a reward spot for 20FPs, it will show that spot for 20FPs, even if that spot is snipable for 10FPs.
The calculator is working fine for the overage part, should you want to contribute more than what the reward spot is worth. But not when it comes to looking for snipable spots. This is a great hindrance when trying to look for snipable spots. Please fix this. You've taken away so much with this last update, the negotiation helper in GBG, incidents that are coming in the future, and what is available to plunder in our neighbourhoods. What is left should be working right.

**Comment by outoftheline** [comment]
It was requested to take away the sniping feature. This is intended behaviour. The "difference" now shows the difference between your chosen percentage and your actual arc bonus.
