### ISSUE TITLE
Eigentanteil bei Investition + Eigenanteilsrechner erschieden

### ISSUE THREAD

**Issue by SkateScout** [dsiekiera/foe-helfer-extension#1459]
![image](https://user-images.githubusercontent.com/919349/86923725-b22a6280-c12e-11ea-8e17-9171174ead37.png)
Ich wundere mich warum die beiden Eigenanteile für die Gleiche Stufe unterschiedlich berechnet werden.

**Comment by andrgin** [comment]
Weil bei den Investitionen die Doppelernte abgezogen wird.

**Comment by SkateScout** [comment]
Verstehe ich dennoch nicht der Frachter wird mit Durschnitt von 2FP am Tag (Ernte) angegeben.
Wie kann dann die Doppelernte die Kosten von 441 auf 425 drücken wo es nur eine Doppelernte
für dieses eine Level gibt.

**Comment by andrgin** [comment]
Der Frachter lvl5 bringt im Schnitt 13,875FP
Der Frachter lvl6 bringt im Schnitt 15,725FP am Tag also 1.85 (gerundet 2FP) mehr als auf lvl5.

Wenn du den Frachter levelst bekommst du die Doppelernte von 15.725FP (gerundet 16FP)

Netto kostet die Aktion also 441-16 = 425FP
425FP / 1.85FP = 229,73 (gerundet 230FP).

**Comment by SkateScout** [comment]
👍Danke für die Erklärung hatte nur die 2FP/Tag gesehen mir war nicht klar das damit nur das Delta gemeint ist,
