### ISSUE TITLE
Idee: Entfernen der Animationen

### ISSUE THREAD

**Issue by Eschi2001** [dsiekiera/foe-helfer-extension#1461]
Mit jedem neuen ZA nimmt die Liste der Schleifenquests weiter zu. Mittlerweile dauert das Durchlaufen von 13 Schleifen Quests so lange, was jedoch fast ausschließlich an der Animation liegt. Könnte diese entfernt werden?

**Comment by GeniusTimo** [comment]
Welche Animation meinst du?
In Bezug auf den Helfer fällt mir keine Animation ein, die das Abbrechen von Quests verlangsamen könnte 🤔

**Comment by outoftheline** [comment]
Genau, da können wir nicht eingreifen.

**Comment by Eschi2001** [comment]
OK, vielen Dank. Hatte die Hoffnung, dass mit einem Schalter o.ä. diese Animation ausgeschaltet werden könnte...

**Comment by SkateScout** [comment]
Vielleicht hilft die in Game Einstellung:
![image](https://user-images.githubusercontent.com/919349/87035503-b8c9e000-c1e9-11ea-8cc2-80a94f01d83a.png)

**Comment by Eschi2001** [comment]
Nein, dadurch werden nur Animation an Gebäude und in der Umgebung gesteuert. Die Leiste mit den Quests ändert sich leider nicht.
