### ISSUE TITLE
Idee: Nach dem Überfall eines Nachbarn in die eigene Stadt zurückkehren

### ISSUE THREAD

**Issue by Eschi2001** [dsiekiera/foe-helfer-extension#1462]
Wenn man Nachbarn angreift, ohne diese Plündern zu wollen, muss man trotzdem immer in die Stadt des Nachbarn. Gerade in den hohen ZA mit großen Städten dauert das Laden hier unnötig lange. Man könnte doch direkt in die eigene Stadt springen, um den nächsten Nachbarn anzugreifen.

**Comment by GeniusTimo** [comment]
Der Helfer greift nicht in das Spielgeschehen ein ⚠️

**Comment by outoftheline** [comment]
Da können wir nix machen. Das Ideenforum von Forge of Empires (DE) befindet sich hier:
https://forum.de.forgeofempires.com/index.php?forums/ideen-und-vorschl%C3%A4ge.39/
