### ISSUE TITLE
LG investition - Inno Tower 

### ISSUE THREAD

**Issue by HAL09001** [dsiekiera/foe-helfer-extension#1466]
Ich sehe dort die Berechnung für den den Inno Tower in den Investitionen als Bug, da die Nebenkosten dazu (Zufriedenheit) nicht mit berücksichtigt werden. 
Bei mir wird gerade vorgeschlagen den auf Level 65 zu bringen
Ich müsste dafür ja z.B. das Alca sowie die Hagia auf ungefähr denselben Level bringen.

**Comment by andrgin** [comment]
Sekundäreffekte werden generell nicht berücksichtigt, da diese nicht objektiv bewertbar sind. Ob man nun die Bevölkerung des Inno braucht oder nicht ist eine individuelle Entscheidung genauso ob du Zufriedenheit haben willst. Mir ist die komplett egal. Ich spiele nicht auf Punkte und mit Markusdom und RAH sind die 50% Malus doch egal.
