### ISSUE TITLE
"Bing, Bing, Bing" im Kostenrechner

### ISSUE THREAD

**Issue by PXWaldy** [dsiekiera/foe-helfer-extension#147]
Das neue Bing ist zwar wirklich nett als Hinweis. Ich bitte nur dringen die Funktion einzuführen das man es ausschalten kann.

Ich höre Musik beim spielen oder unterhalte mich im TeamSpeak mit anderen Spielern. Da ist das Bing mehr als nervig. Einfach neben dem Fragezeichen ein Symbol einfügen was den Ton deaktiviert.

Abgesehen davon, kommt es beim einzahlen dazu das es immer und immer wieder Bing macht..

Ich sage noch einmal Bing, weil´s so schön ist. :)

**Comment by littel66** [comment]
Bitte um Möglichkeit den Ton ausschalten zu können. Extrem nervig!

**Comment by PXWaldy** [comment]
Bis die Funktion eingefügt wurde kann nur empfehlen den Ton für die Seite zu deaktivieren.
Einfach auf das Schloß vor der URL klicken und dann Ton Stummschalten.

![image](https://user-images.githubusercontent.com/3416792/68500899-18d44500-025d-11ea-90ef-caf2bcbc3079.png)

**Comment by dsiekiera** [comment]
Ist in Arbeit. Kommt asap als Update.
