### ISSUE TITLE
Plunder Finder - Statue of Honor is not plunderable

### ISSUE THREAD

**Issue by CaptCanada121** [dsiekiera/foe-helfer-extension#1470]
In the plunder finder, the statue of honor keeps coming up as a building to plunder but it is not a building you can plunder. Not sure if this was a change in the game at some point, or what caused it, but it should be removed from the list of buildings returned in the plunder finder. 

Thanks,
-CaptCanada

**Comment by dsiekiera** [comment]
We removed this modul with version 2.5.0.0..

That is why we **do not answer** any more questions and certainly do **not give any support**.

**Comment by GeniusTimo** [comment]
Please update your helper, we can't provide support for outdated versions.
The Plunder Finder was removed in 2.5.0 after consultation with Innogames ([more information](https://forum.foe-rechner.de/d/355))
