### ISSUE TITLE
Kostenrechner: kleines Infofenster von Mouseover geht nicht mehr weg

### ISSUE THREAD

**Issue by Nerd2020** [dsiekiera/foe-helfer-extension#1471]
Ich benutze den Kostenrechner zum snipen, und lasse mir mit mouseover die nötigen Punkte zum Absichern im Vergleich zum Ertrag anzeigen. Das kleine schwarze Fenster, welches hier erscheint, bleibt gelegentlich aktiv und wird weiterhin angezeigt, selbst wenn man zu einem anderen Gebäude wechselt. (siehe Screenshot) 

![Screenshot_20200709_165555](https://user-images.githubusercontent.com/67139127/87055767-0ef84c80-c205-11ea-9c17-668a1d9c5aea.png)

Wenn man dort mouseover macht, werden die dortigen Werte richtig angezeigt, und ein neues schwarzes Fenster lagert sich über das alte, aber letzteres bleibt stehen, solange bis man den Kostenrechner komplett schließt. (davon kann ich leider keinen screenshot machen).

**Comment by GeniusTimo** [comment]
Ich kann deinen Fehler reproduzieren, aber dazu muss man echt unglücklich timen 😅 Ich schaue mir das mal an

**Comment by Nerd2020** [comment]
Ist mir jetzt schon mehrmals passiert, allerdings bin ich auch sehr fleißig beim Besuchen der Nachbarn...😉
