### ISSUE TITLE
GbG Overview shows at start

### ISSUE THREAD

**Issue by franzalex** [dsiekiera/foe-helfer-extension#1473]
When used in combination with [FoE Power Tools](https://foepowertools.com/), the GBG overview window is shown the moment you log into the game.  
Do you think it is possible to stop this window from being shown at start?

Thank you

**Comment by GeniusTimo** [comment]
By actively sending packets to the server, the server's response triggers events that are processed by the helper.
The helper can't determine whether the event is triggered by another extension or by the game itself.
I encourage you to read [this post](https://github.com/dsiekiera/foe-helfer-extension/issues/1422#issuecomment-654403851) from @andrgin ℹ️

**Comment by franzalex** [comment]
Alright. I thought that was what was happening. Thanks for confirming my theory. 
Also, as Power Tools is in violation of the game's terms, I'll remove it the next time I use my browser.

Thanks
