### ISSUE TITLE
Anzeige LG - FP stand

### ISSUE THREAD

**Issue by HAL09001** [dsiekiera/foe-helfer-extension#1476]
Ich würde mir eine Funktion wünschen, wo ich sehen kann, wie viele FP in welchen eigenen LG eingezahlt ist.
Zum einen ist es mir öfters passiert, das ich ein LG angefangen habe, dann ein oder mehrere neue LG dazugekommen sind, und das andere fast fertige über Tage vergessen habe. 
Zum anderen ist es gut zu sehen, wenn einem nette Leute den Inno Tower Leveln (wollen) und mann dadurch die Zufriedenheit verlieren würde. Dann kann man Gegenmaßnahmen treffen.
Indirekt habe ich sowas ja über Anhang senden bei den Chats, schön wäre es aber, wenn ich es direkt (sortiert) sehen könnte.

**Comment by b-tomasz** [comment]
Wenn du bei der übersicht deiner Freunden, Nachbarn oder Gildenmitglierder, bei dir selber die ansicht der LGs öffnest, siehst du die übersicht von deinen LGs. 
Meinst du sowas?

**Comment by HAL09001** [comment]
Was ich suche ist eine einfache liste, ähnlich wie die im Chat
in etwa so:
```
-  Name     | stufe  | Offene FP  | Eingesetzte FP  |  Gesammt FP
1. Alcatraz |     10 |        130 |            700  |         830
2. Babel    |     13 |        563 |              0  |         563
3. CDM      |     24 |       1014 |              0  |        1014
...
9. Zeuss    |      6 |          3 |            327  |         330

```
So dass, wenn ich die nach Offenen FP sortiere, ich sofort den Quickwin Zeuss sehe, der da seit langem wartet und den ich aus den Augen verloren habe.
Ja ich weiß, den Zeus verliert man nicht aus den Augen. ;) Ist mir aber bei anderen LGs schon passiert. :(

**Comment by b-tomasz** [comment]
Die bereits im spiel enthaltene ansicht hat alles ausser die Spalte Offene FP und die möglichkeit zum sortieren.
Die Offene FP sieht man anhand des grünen Balken und die Sortierung ist so dass das LG in welches als letztes eingezahlt wurde zuoberst ist.

Ich sehe in der von dir beschriebenen Liste keinen wirklichen vorteil.

![grafik](https://user-images.githubusercontent.com/60810950/87202095-29632080-c300-11ea-8478-5ba99d383be8.png)

**Comment by andrgin** [comment]
Im Spiel sind die LGs oben, in die als letztes eingezahlt wurde.
