### ISSUE TITLE
Investitionsübersicht

### ISSUE THREAD

**Issue by Te4k** [dsiekiera/foe-helfer-extension#148]
Ich monitore ganz gerne meinen gesamten FP Bestand.
Manchmal setzt man einfach nur 1 FP in ein LG um via Rathaus beim LvLup benachrichtigt zu werden und dann eben in der nächsten LG Stufe investieren zu können. 
-> Dadurch hat man in der Investübersicht manchmal Mäzen, die man ja nie bekommen wird (1FP 272FP Gewinn) 
-> Aktuell rechne ich manuell diese Mäzen raus.
Wäre es möglich auf der Investpage Haken einzuführen, um solche Investitionen "herausrechnen" zu können? 
-> Alle Mäzen und Gewinn im Rechner sind zu beginn gelistet => entfernt man den Haken, wird die Mäze bzw. das LG nicht in die Summe oben aufgenommen 

Ist klar ein comfort feature, sollte aber vom Aufwand her nicht sonderlich viel Zeit beanspruchen.

Keep up your good work ;)

**Comment by andrgin** [comment]
Funktioniert mittlerweile
