### ISSUE TITLE
Info Box not working and other bugs

### ISSUE THREAD

**Issue by dexonter** [dsiekiera/foe-helfer-extension#1481]
Hello,

I have some issues with the extension that I do not know what to do about:

1. I am using the extension for over a month and the info box is always empty.
2. Also for most things, like productions I have to reload the whole game for the extension to update.
3. Unit overview - the next Traz units are always rogues, no matter if I also have other military buildings
4. Statistics seem to reset and always I start with no statistics

I am using version 2.5.0.1 in English if that helps...

Thank you!

**Comment by GeniusTimo** [comment]
Hi @dexonter,

the info box is filled with time and is always empty when it is opened. Can you give us more information on the second point? On your third point, @andrgin probably knows more about it than I do 🙈 Resetting the statistics sounds to me like an automatic cache cleaning (see [this issue](https://github.com/dsiekiera/foe-helfer-extension/issues/1226#issuecomment-645592690)).

**Comment by outoftheline** [comment]
3) The Traz production does not show what you will collect, but what you have collected when the extension was running. So, if you build new military buildings and collect, the Traz production updates. If you collect your Traz on mobile though, the collection will stay as is as the Helper can only get data from your browser.

4) If you want the stats to run for longer, you shouldn't clear all of website data when closing the browser. We store the data in your browser.
