### ISSUE TITLE
Notification of Known Issues

### ISSUE THREAD

**Issue by SkateScout** [dsiekiera/foe-helfer-extension#1483]
Wie wäre es wenn der FOE-Helfer das PowerTool Plugin erkennt.
Und wenn er es erkennt mit einer Info BOX Informiert das er Inkompatible ist.
Dazu kurz Anleitung zur Deinstallation der Power Tools.
Vielleicht kann man damit den Aufwand wie bei:
https://github.com/dsiekiera/foe-helfer-extension/issues/1473
in den Griff bekommen

**Comment by andrgin** [comment]
Ich denke nicht, dass es unsere Aufgabe ist im Spiel nach verbotenen Extensions zu suchen, vor allem da es ja einige Tools gibt.

Ich habe jedoch die Frage nach anderen Extensions in die Bug report Vorlage aufgenommen. So sollte das ziemlich bald auffallen.

**Comment by SkateScout** [comment]
Es ging mir weniger darum das diese Verboten sind sondern das wegen diesen hier in Letzter Zeit Bug Reports geöffnet werden.
Daher war Idee das man diese als Inkompatible bezeichnet.

**Comment by andrgin** [comment]
Geht ja in erster Linie nur um Powertools wegen deren aktiv Abfragen an den Inno Server und das wird sich hoffentlich bald von selbst lösen.

**Comment by andrgin** [comment]
Powertools ist mittlerweile gebannt  bzw. der Server offline
