### ISSUE TITLE
Few issues with the new Notes menu

### ISSUE THREAD

**Issue by Minotorious** [dsiekiera/foe-helfer-extension#1487]
First of all the menu when you hover over the icon is called "Notices" when it should be called "Notes" (same on the menu title bar as seen in the video below too)

Two small typos in the edit tabs, says "site" and "sites" instead of "side" and "sides"
![1](https://user-images.githubusercontent.com/40427380/87223164-eeea9980-c37a-11ea-9908-70e28dcdf818.PNG)
![2](https://user-images.githubusercontent.com/40427380/87223165-ef833000-c37a-11ea-9b36-e1fa227fb618.PNG)

Last the most important imo, as you can see on the video below, if I go to the start of the line and press "Enter" it adds two instead of one new lines while when I do it from the end of the line it correctly only adds one. I would guess that is due to the EOL characters you have used (possibly the windows default \n\r instead of the more universal \n?) but you would have to take a closer looks as I am not at all familiar with javascript to check myself. (I am playing on Chrome on Win 10 in case it is relevant)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40427380/87223367-ac29c100-c37c-11ea-8c75-1f991b67a893.gif)

Also small note, the typing cursor disappears when it is at the start of a line, you can also see that in the video above.

**Comment by outoftheline** [comment]
The last issue will be fixed with the next update. 
The others are small translation issues I'll fix right away.
