### ISSUE TITLE
Technology tree error in counting required goods

### ISSUE THREAD

**Issue by pavlosgr** [dsiekiera/foe-helfer-extension#1489]
As it seen on the attached screenshot I'm sort of rubber to research ballistics.
Rubber as well gunpowder are not shown on the tech tree research tree costs.

![research](https://user-images.githubusercontent.com/3639193/87225415-7c3ae780-c395-11ea-9f11-4b4a0c744969.JPG)

**Comment by dsiekiera** [comment]
I cant read your current era. What speak is it? 

PS: U can help us to translate the Extension on [http://i18n.foe-helper.com](http://i18n.foe-helper.com)

**Comment by pavlosgr** [comment]
Industrial age. Language is greek.

**Comment by GeniusTimo** [comment]
As @dsiekiera mentioned the calculator only counts the main technologies and ignores optional researches.
If you want to translate the Helper to the Greek language, look at our new translation platform [Weblate](http://i18n.foe-helper.com/projects/foe-helper/extension/el)
