### ISSUE TITLE
Armee Auswahlhilfe?

### ISSUE THREAD

**Issue by Chris1887x** [dsiekiera/foe-helfer-extension#1491]
Hallo zusammen, ist es möglich, zu erkennen, welche Armeen in der Gegnerwelle sind (Beispiel GEX und GG)?
Falls ja: Ist es möglich, dass der FOE-Helfer einen dann die bestmögliche "Konter-Truppe" zusammenstellt und anzeigt?

LG

**Comment by GeniusTimo** [comment]
Aufgedeckte Einheiten auszulesen ist technisch gesehen möglich, aber ein Armeeassistent ist zu komplex 😅
Daher steht er auch bei den abgelehnte Ideen ([angepinntes Issue](https://github.com/dsiekiera/foe-helfer-extension/issues/860)) 🔽
> 4.) Armeeassistent
> Idee: Ein Tool, das die beste Armee für einen bestimmten Gegner vorschlägt ähnlich wie der Verhandlungsassistent beim Verhandeln
> Begründung: Kämpfe sind viel zu komplex (Einheiten mit unterschiedlichen Stats/Fähigkeiten/Terrain etc.) um die beste Armee zu berechnen.
