### ISSUE TITLE
FOE Helper -incidents counter not correct

### ISSUE THREAD

**Issue by ScriptAdel** [dsiekiera/foe-helfer-extension#1494]
**Incidents counter not showing correct number** of incidents until you collect
this is screenshot before Iopen Tab
![image](https://user-images.githubusercontent.com/65903928/87254153-29daf300-c489-11ea-8bf8-d8455d139860.png)

And this picture after i open Tab
![image](https://user-images.githubusercontent.com/65903928/87254186-5f7fdc00-c489-11ea-8647-b056954af03a.png)

**Comment by GeniusTimo** [comment]
Duplicate of #1321
