### ISSUE TITLE
Belohnungen Schleifenquest - Nummern beim Verhandeln im GG - Verhandeln Auswahl bestätigen

### ISSUE THREAD

**Issue by Lore05** [dsiekiera/foe-helfer-extension#1499]
1. Ich würde mir wünschen, dass es bei den Statistiken die Möglichkeit gibt, die Belohnungen zu sehen, welche man durch wiederkehrende Aufgaben bekommen hat. 

2. Das das Verhandeln bei der GG eigene Anstrengungen braucht finde ich ok, hilfreich wäre aber, wenn bei den verfügbaren Güter die Nummernzuweisenung angezeigt wird... 
ich arbeite beim Verhandeln gerne mit dem Nummernblock bekomme aber nicht das richtige Gefühl für die Güterplazierung in der Auswahl.. würden hier die entsprechenden Nummern zu sehen sein. wäre das sehr hilfreich ohne einen unfairen Vorteil beim Verhandeln zu bekommen. 

3. Wenn man Verhandelt und dabei mit dem Nummerblock arbeitet, wäre es auch mega, wenn man noch mit einer Taste die Auswahl bestätigen könnte die dichter beim Nummernblock ist als die Leertaste. Enter oder aber auch das "+" falls das einfacher einzurichten ist... wäre sehr angenehm.

**Comment by andrgin** [comment]
1.) Wäre denke ich möglich

2.) In den GG bleibt dieser komplett deaktiviert. Das haben wir mit Inno so vereinbart und da wollen wir eigentlich nichts daran ändern.

3.)  Die Shortcuts hat Inno so festgelegt. Wir zeigen diese lediglich an. Alles was darüber hinausgeht wäre ein Regelverstoß.

**Comment by Lore05** [comment]
Danke! über 1.) würde ich mich sehr freuen! Danke für die super Arbeit!
