### ISSUE TITLE
Nachbarschaftsproduktionen 

### ISSUE THREAD

**Issue by Datenschutz** [dsiekiera/foe-helfer-extension#15]
Hallo, 
es scheint , als werden nicht mehr alle laufenden plünderbaren Produktionen angezeigt, z.B. Kirschgartenset, Indischer Palastset und Piazzaset. 

LG

**Comment by Selene443Foe** [comment]
Guten Abend,
Spielermeldung: 
in der Plünderanzeige fehlt das Gartenruinenset:
![29](https://user-images.githubusercontent.com/50969949/65377479-c5a63300-dcac-11e9-998c-3639ae9af36d.png)

**Comment by dsiekiera** [comment]
Ein Update ist derzeit in Arbeit und kommt in Kürze.

**Comment by andrgin** [comment]
Mittlerweile korrigiert
