### ISSUE TITLE
Eigenanteilsrechner rundet auch in neuer Version ab statt auf

### ISSUE THREAD

**Issue by derklausi** [dsiekiera/foe-helfer-extension#150]
Hallo,
der Fehler/Bug, dass der Eigenanteilsrechner ingame abrundet statt auf, besteht auch in der aktuellen Version fort.

**Comment by andrgin** [comment]
Kannst du da einmal ein Beispiel bringen?

**Comment by derklausi** [comment]
Gibt man das gleiche auf der Webseite in den Rechner ein, hat man 3 Punkte weniger Eigeneinsatz, da Platz 1, 2 und 4 aufgerundet werden.
![arche](https://user-images.githubusercontent.com/57454394/68527376-5fba4d00-02e6-11ea-8977-4feba5f17256.JPG)

**Comment by andrgin** [comment]
Also ich habe mir das einmal angesehen und meiner Meinung nach:

1.) Was die FP angeht so ist der ingame Rechner richtig und der auf der Homepage falsch, da erst ab .5 aufgerundet wird.
2.) Was die BP und Medaillen angeht, so ist der Rechner auf der Homepage richtig und der ingame Rechner falsch.

Beispiel:
P1: 45FP * 1.85 = 83.25 -> abrunden auf 83FP
P2: 25FP * 1.85 = 46.25 -> abrunden auf 46FP
P3: 10FP * 1.85 = 18.5 -> aufrunden auf 19FP
P4: 5FP * 1.85 = 9.25 -> abrunden auf 9FP

Der Unterschied besteht allerdings nur mit 1.85. Mit 1.9 kommt es zu keinen .25er oder .75er Werten.

**Comment by derklausi** [comment]
Hallo,
ok, da kann ich nur für unsere Gilde sprechen, wir runden immer auf, egal was nach dem Komma steht.
Vielleicht kann man ja eine Option zum Runden "immer aufrunden"; "immer abrunden" und "genau Runden" ergänzen? Somit könnte man es individualisieren und wenn es dann gespeichert bleibt wäre das ideal denke ich.

**Comment by andrgin** [comment]
Da gibt es denke ich unterschiedliche Meinungen, aber ich denke, dass sich sämtliche Rechner an die Rundungslogik des Spiels anpassen sollten d.h. 185% Archenfaktor im Rechner ist das, was ein Spieler mit 185% Archenfaktor (lvl70) bekommt.

Würdest du z.B. in einer 185er Gruppe 5FP aufrunden, so würden alle, die 89.5% Bonus oder weniger (lvl79 oder niedriger) negativ aussteigen.

**Comment by derklausi** [comment]
Ingame Rechner und Webseitenrechner agieren unterschiedlich, ich denke, es sollte einheitlich sein.
Wenn ich bei beiden das gleiche eingebe kommt verschiedenes heraus. Ich halte mich dann an die Webseite, da sie immer aufrundet und ich diese Berechnung für meinen zu kopierenden Text benötige.

**Comment by dsiekiera** [comment]
Ich klink mich mal hier ein.

Tatsächlich denke ich das das Runden beim befüllen immer zur nächsten
vollen Zahl sein sollte. Das ist eine Besonderheit da sonst am Ende ggf FP
fehlen und ein Platz snipebar wird. Ist Mathematisch wie Andreas sagt nicht
korrekt, aber ist für das Spiel entscheidend.

Wir werden das intern noch mal besprechen.

**Comment by dsiekiera** [comment]
WIr haben den Code des Extension-Kosten-Rechners in die Webseite portiert. Beide arbeiten nun komplett identisch.

**Comment by derklausi** [comment]
Super, so ist das zu gebrauchen, vielen Dank. Jetzt rundet der ingame Rechner auf.
