### ISSUE TITLE
For what is option "Levels" in "Copying" window?

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1504]
![2007150901](https://user-images.githubusercontent.com/35531243/87509243-d2e84000-c679-11ea-8222-2dd9627d28b9.png)

I hope that this option is to add "Level 45 -> 46" into text.

But this option inserts text "Bitte Leveln" (I think that it has too little sense) always in German regardless of selected language:

 Зевс Bitte Leveln P4(29)  <- russian
 Зевс Bitte Leveln P4(29)  <- english

Is it possible to replace useless "Bitte Leveln" with "Level X -> Y"?

**Comment by outoftheline** [comment]
The text means "please level up".

**Comment by belikoviv** [comment]
> The text means "please level up".

Yes, I can translate. Google translator is good thing :)
If anybody will add translation - in russian it will be "с закрытием" (with level up)

But level up is rare event. And text near option need to be changed - "level up" instead of "levels".

And new option that inserts text "Level X->Y" will be much more helpfull than "level up".

**Comment by andrgin** [comment]
I thi k I will redo the scheme system in oneof the next updates making it more customizeable and fully translated.

**Comment by andrgin** [comment]
Next update will have a redesigned scheme system where you can include the buulding level.
