### ISSUE TITLE
Infobox (GBG) - Old messages showing up as new?

### ISSUE THREAD

**Issue by Arklur** [dsiekiera/foe-helfer-extension#1506]
Sorry if it's not a "bug" but that's how Inno sends events like this for "no reason". If not, mark it with "request" tag, see my idea below.

C1 is being taken already, but there is a new message for it in the log:

![](https://i.imgur.com/GYE5H4m.png)

If it's not a bug, then could you somewhat filter these out so only new/recent activity shows up? Maybe extend the "GBG functionaility" by providing a new tab in which I can see the upcoming sectors?

**Comment by GeniusTimo** [comment]
We had a similar issue in version 2.5.0.1, do you use the lastest version 2.5.1.0 and could you reproduce it after you checked your version number?

**Comment by Arklur** [comment]
It's 2.5.1.0, but I think I got the update today, after this report...? Anyway, I'll try to reproduce the bug, if it doesn't show up, I'll let you know and you can close this...and well, obviously if it sill persist :).

+1: And next time I'll include my version in the report, I should know better that it's quite important in these reports.

**Comment by Arklur** [comment]
It seems this is still happening:

![](https://i.imgur.com/tmohjJ8.png)

**Comment by GeniusTimo** [comment]
Since I can't reproduce the bug, you have to go through it step by step and also see if there is an output in the console (`F12`). If you join our Discord then we can probably save some time 😅

**Comment by Arklur** [comment]
I can't really reproduce, it's not something "reproducable". I just open up the window and check it every few minutes. I also somewhat thought I'll able to see stuff in the "Network" tab, but it seems empty, at least there are no "events" like those "json?h=" stuff I usually see when interacting with the game:

![](https://i.imgur.com/5SUdH79.png)

This makes me somewhat curious how do you grab the changes :D.

Anyway, I'll try to look the Console then and see if something is off there. If nothing interesting shows up, I'll probably go to Discord, but not sure how will that speed up the process (since I can't provide you a step-by-step repro).

**Comment by andrgin** [comment]
Infobox events arrive via websocket. Those are not visible in the network tab, but you can log them to console by entering:
Infoboard.DebugWebSocket = true

**Comment by Arklur** [comment]
Oh I see, awesome. Wish I had the knowledge to program in JavaScript, it's pretty awesome you guys are doing here!

Anyway, back to the report, it seems that when a **building is finished** on a sector, those messages appear. I tested it 2 times, got the message both times (gemmed 2x1 building).

**Comment by GeniusTimo** [comment]
Thanks for this information, issue is on my list
