### ISSUE TITLE
Bug - Infobox for the own part calculator isn't wide enough

### ISSUE THREAD

**Issue by Benneballe** [dsiekiera/foe-helfer-extension#1507]
I have noticed that since the latest FoEHelper update from today came out the window for the own part calculator isn't wide enough. Some of the text can't fit in to the window.
Did that happen because some of the text in the window (Påkrævet, Investeret, ...) is too long?

Windows 10 64 Bit
Chrome 84.0.4147.89
DK1 (Arvahall)
2.5.1.0 - Danish

![FoEHelper fejl](https://user-images.githubusercontent.com/65241771/87527447-6dea1580-c68c-11ea-8385-c4aa73632656.png)

**Comment by GeniusTimo** [comment]
> Did that happen because some of the text in the window (Påkrævet, Investeret, ...) is too long?

I think so, but we could make this window responsive so that the size also fits for other languages.

**Comment by Benneballe** [comment]
Would be nice if the window would adjust to the space needed for all of the text to show.
