### ISSUE TITLE
Windows too narrow (english version)

### ISSUE THREAD

**Issue by LordFelix** [dsiekiera/foe-helfer-extension#1508]
On some Great Buildings, the GB calculator window is too narrow, causing the "Owner to add" to be 2 lines instead of 1 (Captura 1)
![Captura 1](https://user-images.githubusercontent.com/17072012/87540427-fb833080-c69f-11ea-9d20-02283f5070ba.PNG)

On the Production Overview, "Spage Age Asteroid Belt" doesn't fit in one line either (Captura 2)
![Captura 2](https://user-images.githubusercontent.com/17072012/87540620-4e5ce800-c6a0-11ea-8140-469f57a1e29a.PNG)

On the Production Overview, the names of some buildings also require 2 lines, like "Sphendone Hippodrome - Lv 6" (should the name be translated to server language if we got the extension in a different one?) (Captura 3)
![Captura 3](https://user-images.githubusercontent.com/17072012/87540877-a4ca2680-c6a0-11ea-8294-386289d35d91.PNG)

On the Production Overview (goods), the name of some goods require two lines, like "Material Procesado" (Captura 4) or "Fluido Compuesto" (Captura 5) (again, should the names of stuff be in the server language or the extension language?)
![Captura 4](https://user-images.githubusercontent.com/17072012/87541177-215d0500-c6a1-11ea-8d5b-6687957df495.PNG)
![Captura 5](https://user-images.githubusercontent.com/17072012/87541186-2457f580-c6a1-11ea-8c95-0a826390a540.PNG)

**Comment by outoftheline** [comment]
I fixed the first problem.

The second one is more tricky. If we remove the width of the productions window, the width would change when changing tabs, which I think is more annoying than the height of some columns.

**Comment by LordFelix** [comment]
But if pretty much all the windows have the same problem, cant the window simply be made slightly wider?
