### ISSUE TITLE
Infobox refreshes even though no new messages

### ISSUE THREAD

**Issue by vqt123** [dsiekiera/foe-helfer-extension#1509]
The infobox appears to be refreshing even though there are no new messages. (You can tell this because the background keeps changing)

(I believe what's happening is a refresh is not respecting the filters)

**Comment by GeniusTimo** [comment]
This is due to the implementation of the filters, the entries exist - but are hidden from the user - it would be necessary to modify the filter to solve this problem

**Comment by SkateScout** [comment]
I think in older versions the filter skiped the filtered messages the new version allow that they are displayed if the filter change.
Maybe an good idea would be add the messages to an array and render the table new if filte ris changed.
By the way you can also ad an limit for the tale length so it does not slow down gg with to much messages.

**Comment by vqt123** [comment]
I leave this filter box opened and use it to quickly see if there are new messages on my 2nd monitor using my peripheral vision and oh boy.. I think i may actually prefer the double posting bug =P

**Comment by GeniusTimo** [comment]
For me the background isn't updated, but I could see the new events in the code of this window

**Comment by GeniusTimo** [comment]
I figured out what you meant 👍
