### ISSUE TITLE
Find Incidents

### ISSUE THREAD

**Issue by Kalis-Pathon** [dsiekiera/foe-helfer-extension#1511]
Hey there.  I'd like to suggest a find incident button.  You had something similar back when you had plundering tools to help find the building to plunder.  Well this would be for your own city.  It's just really difficult to find incidents on your roads when they are behind buildings.  This would be an awesome addition to foehelper!  I hope you'll consider implementing it.  =)

**Comment by b-tomasz** [comment]
Yes this wold be nice. But it isn't possible. 
See here: #837

**Comment by b-tomasz** [comment]
Duplicate of #837

**Comment by Kalis-Pathon** [comment]
Well that's disappointing but there's nothing you can do about it. Thanks for the prompt response!! =)
     On Wednesday, July 15, 2020, 11:58:40 AM CDT, b-tomasz <notifications@github.com> wrote:  
 
 


Yes this wold be nice. But it isn't possible.
See here: #837
