### ISSUE TITLE
Idea: QoL Interface improvement

### ISSUE THREAD

**Issue by strongstancer** [dsiekiera/foe-helfer-extension#1514]
Hey guys,

thanks for the great work on the tool! I have some wishes for improvements on the interface, especially regarding window positions. Let me explain my problem first:

I have a multi monitor setup with one 4k Monitor in the middle, two 1920x1200 monitors in portrait-mode (=1200x1920) left and right of the 4k and another 1920x1200 monitor in landscape all the way to the right. Now I play multiple worlds simultaneoulsy and switch the single tabs between the windows very often. Here comes the problem: Window positions are anchored to the top left of the window, leading to unaccessable windows or at least bad positioning when switching monitors and thus resolutions.

Solution: Let me be able to select different anchor points for each window individually. Like the FP investment overview (after opening LG overview in the town hall) to be posinoned relative to the top middle, while some other windows should als be positioned relative to the top right and so on...

Another thing is the problem of positioning of windows in front of each other: Its always the last opened window, that stays on top and is therefor rendered in front of other windows. Clicking into another window does not change this ordering, but closing and reopening the window does. Please make it possible to switch windows to foreground by simply clicking on them.

I hope this is technically realisable ;-)

**Comment by dsiekiera** [comment]
Hello @strongstancer,

you can move all windows except 1 - 2 exceptions. This position is also saved.

I will implement the behaviour with the layers because it seems to make sense to us too.

**Comment by strongstancer** [comment]
Yes I know that I can change all window positions, but it is annoying to do so every thime, i switch to another monitor. It would be much easier, if the window positions would be relative to the anchor point I chose (top, middle, bottom and left, middle, right). And sometimes windows are totally unaccessible because of this, until I reload the window. Let me give you an example:

On the 4K Monitor I position the Infobox right above the friend bar. This is roughly 1800 pixels belo the top corner (which is the anchor point for all windows). Moving to the 1920x1200 Monitor the window is now still positioned 1800 pixels below the top left corner which is out of the total browser size and thus not displayed. Even reopening the Infobox does not solve this. Only reloading the browser tab moves the top bar of the Infobox just high enough, that I can drag and drop it to another position to see the whole box.

**Comment by dsiekiera** [comment]
I understand your wish. But unfortunately it is too specific and we never build in a wish for just one player. Please understand that.

I have just integrated the function "bring forward on click" and it will be available with the next version.

**Comment by strongstancer** [comment]
Yeah, I know it is super special and I undestand the decision. Thanks for the fast solution for the layer problem, you are the best <3
