### ISSUE TITLE
Two small translation errors

### ISSUE THREAD

**Issue by Minotorious** [dsiekiera/foe-helfer-extension#1516]
First of all thank you for implementing the power levelling calculator in game, makes things much easier to plan :)

Just two small corrections:

netto = net
brutto = gross

**Comment by b-tomasz** [comment]
I have updated it. It should be fixed in the next update.

**Comment by dsiekiera** [comment]
Please use our translation platform [http://i18n.foe-helper.com] (http://i18n.foe-helper.com)

Register, login and translate. 

Thx a lot for your help!
