### ISSUE TITLE
FP error

### ISSUE THREAD

**Issue by TeddyBeerNL** [dsiekiera/foe-helfer-extension#1518]
In the Gb investor tool, it says that an option is to build the AO and get it to lvl 61, but it says it will produce 51 daily fp at that level. Is this a visual bug or is there something else wrong?

**Comment by andrgin** [comment]
It produces 51FP more than now.

**Comment by TeddyBeerNL** [comment]
its not yet build, so it doenst produce anything: 
![image](https://user-images.githubusercontent.com/68404171/87730573-77789800-c7c8-11ea-94fc-c92c11bec0e5.png)

**Comment by andrgin** [comment]
Can you post a screenshot of all suggestions

**Comment by andrgin** [comment]
For new great buildings the tool calculates with 0.2 FP/tile for space requirements. So in the case of the AO it assumes you have to get rid of 1 shrines of knowledge to build the AO, but I agree that it is not a good idea to display it that way.

**Comment by TeddyBeerNL** [comment]
![image](https://user-images.githubusercontent.com/68404171/87804773-a3415f80-c854-11ea-84b6-6fc8894d262a.png)

**Comment by andrgin** [comment]
In the next update the costs for space requirements in FP/tile are now visible and can be changed.
