### ISSUE TITLE
Idea: Infobox  > GBG; short names for sectors?

### ISSUE THREAD

**Issue by Arklur** [dsiekiera/foe-helfer-extension#1519]
Instead of writing the full name of the sector, show the abbreviated version of it, such as A4H, B3X, B2T, C1.

![](https://i.imgur.com/6uO4dBF.png)

**Version:** 2.5.1.0

**Comment by GeniusTimo** [comment]
A setting would do it 😅 In the general settings or directly in the infobox? 🤷

**Comment by Arklur** [comment]
Yeah, a setting would be preferred, so for those who, for some weird reason, want to see the full name, they can still see it :D. I think it would be more useful in the Infobox, if that's not much more work for you.

**Comment by dsiekiera** [comment]
This is the same information just a bit shorter.
I don't see the point:

![68747470733a2f2f692e696d6775722e636f6d2f36754f346442462e706e67](https://user-images.githubusercontent.com/834814/87796216-573ced80-c849-11ea-981b-d8c4f6aa3dfe.png)

**Comment by Arklur** [comment]
> This is the same information just a bit shorter.

Well, yes, reason behind abbreviations, in a nutshell. That's exactly the point. I don't need the full name of the sector, it takes too much space. With abbreviating the window can be much smaller to fit each message in a single line, it's visually more appealing. Beside, customer is always right ;).

**Comment by GeniusTimo** [comment]
We have discussed your suggestion internally and concluded that it is not really worth it:
- We get the sector names directly from Innogames, a translator would only complicate the process,
- this would clutter the settings, because this would not affect many players and
- pulling the window a little larger is quite sufficient 😅

**Comment by scibuff** [comment]
Personally, If I may, I'd prefer the short version as well ... a simple `sectorName.substring(0,4)` would do

**Comment by Arklur** [comment]
> We get the sector names directly from Innogames, a translator would only complicate the process,

If you really want, I could send you the mapping of "provinceId" and the codes --> https://hastebin.com/uqizojapad.csv

> this would clutter the settings, because this would **not affect many players** and

That's why I said it shouldn't be there but rather in the Infobox. I'm quite sure for those, who use the Infobox for GBG, would love  to see this change

> pulling the window a little larger is quite sufficient

Yes...

**Comment by Arklur** [comment]
Just dropping this here since it's kinda relevant; whoever changed the design for the GBG events...even though I still think it would be nice to have the short names, the new design is 10/9 (would be 10/10 with the short names :P).

![](https://i.imgur.com/XiA9745.png)

I hope the dev who made this reads this!

**Comment by GeniusTimo** [comment]
He read it 😉 Short Names... We'll see what the future has in store for us 🤷
