### ISSUE TITLE
Błąd Kalkulatora kosztów.

### ISSUE THREAD

**Issue by xbodzio7** [dsiekiera/foe-helfer-extension#1521]
The cost calculator incorrectly counts the number of points needed to close the pearl level of architecture. A preview of the architectural pearl shows 7 and Calculator 8.
Date 16.07.2020
![FoE Helper bug](https://user-images.githubusercontent.com/68440306/87815819-9299e500-c866-11ea-8192-f65b5c4fdce5.png)

Windows 7 64
Google Chrome
FoE Helper 2.5.1.0

**Comment by GeniusTimo** [comment]
You have to use this calculator for your own great buildings 😉
![grafik](https://user-images.githubusercontent.com/47282153/87818390-c2e38280-c86a-11ea-856b-620f2d047d7d.png)

The calculator which is currently open is for a previously opened building of another player. PS: If you'd like to help us with the translation into your language, you can do so on [our new platform](http://i18n.foe-helper.com/projects/foe-helper/extension/pl) 🌍
