### ISSUE TITLE
"Current Production Overview (daily)" : A "Great Monuments" tab as well as a tab grouping together all the harvests (rather than separately).

### ISSUE THREAD

**Issue by MoustyFaia** [dsiekiera/foe-helfer-extension#1523]
Hello, 

Would it be possible to include (during a future update) in the "Current Production Overview (daily)" a "Great Monuments" tab as well as a tab grouping together all the harvests (rather than separately) ?

Thus, it would be more practical to know the next harvests (all resources combined) and at the same time "optimize the double harvests" of our Great Monuments. 🙂 

Do you think this is possible ? 

Thanking you in advance for your interest in my request and for your excellent extension. 👍🙂 

Best regards, 
MoustyFaia

**Comment by andrgin** [comment]
In the last tab you can group productions per building type

![Screen](https://user-images.githubusercontent.com/55417498/87977345-e3137b80-cace-11ea-899f-ab084a4658be.png)
