### ISSUE TITLE
Ratgeber fp-Gebäude Investitionen: Gebäude verschwindet

### ISSUE THREAD

**Issue by Nerd2020** [dsiekiera/foe-helfer-extension#1525]
Da ich in meiner Gilde die Güter für Gebäude geschenkt bekomme, wollte ich die fp für ein bestimmtes LG auf Null setzen. Seitdem wird dieses Gebäude in der Liste gar nicht mehr angezeigt. 
Wäre dankbar für einen Tipp, wie sich das zumindest rückgängig machen ließe, dann würde ich 1 fp eintragen...
Restart Browser hilft nicht.

**Comment by GeniusTimo** [comment]
Welches Gebäude war das denn? Ich kann diesen Bug nicht reproduzieren 😅

![grafik](https://user-images.githubusercontent.com/47282153/87871307-92f1c780-c9af-11ea-9591-ce630b3bed7a.png)

**Comment by Nerd2020** [comment]
Soll ich es mit noch einem anderen Gebäude ebenfalls probieren, um bei der Eingrenzung zu helfen?

**Comment by GeniusTimo** [comment]
Ich denke ich weiß, woran es liegt - müsste dazu aber noch ein paar Details privat abfragen, kannst du bitte auf [unseren Discord](https://discord.gg/z97KZq4) kommen und mich kontaktieren?

**Comment by Nerd2020** [comment]
In den Discord habe ich es geschafft, ebenfalls unter Nerd2020, aber Du bist gerade auf bitte nicht stören geschaltet. Ich probier es später nochmal, bin erstmal weg.
