### ISSUE TITLE
Idea; city layout

### ISSUE THREAD

**Issue by qamar5568** [dsiekiera/foe-helfer-extension#1530]
i know there is city planning in Foe where u can redesign your city but i think there is some changes needed. like u can also view in 3d too not only in 2d. and secondly, if it also suggests where to put which building to adjust it in a better way and look better that tool would be really great

**Comment by andrgin** [comment]
1.) 3D View would be a lot of work because buildings will be overlapping. We would be to design graphics for every building ourselves.
Also one of the problems with the ingame tool is that buildings are blocking the view on others because of the 3D model.

2.) An algorithm for auto arranging buildings is not possible. There are far too many calculations needed to find the best combination.

**Comment by qamar5568** [comment]
isn't there any way for auto arranging? all player are not good at planning well so they need something like that

**Comment by andrgin** [comment]
If you know an algorithm that takes into account single/double streets, set buildings, chain buuldings like the train etc. without trying every possible combination please tell us.

**Comment by qamar5568** [comment]
no

**Comment by SkateScout** [comment]
> if it also suggests where to put which building to adjust it in a better way 
There need to be an definition what "better way" means.
> and look better
There must be an definition what mean "look better" does it mean all streets are visible or the buildings are nice in one line.

Lets define some parameters:
- adjust better mean we have an given city and better means that we have less street used than before.
- look better mean that "lower" buildings are below streets so they keep visible.

This would at least limit the possible options to all with less or equals the same number of streets than the current one.
Also you can cluster the buildings to groups that are equivalent (requiredStreet,length,width).
If only one chain set combination is available that you can define the set as one building.
But even with this definition you i have 23 different building sizes. To place this in an space with over 1000 Fields brute force is not an option.

**Comment by SkateScout** [comment]
Even if there is no algorithm for best placement.Maybe it is possible to build an algorithm. Who creates very good suggestions.
My idea would be defining an building algorithm. Which works with the same rule that you use normally to create an city by hand.
Second from the city's that already exists you can guess what will be an good street ratio.

**Comment by andrgin** [comment]
1.) Even the "use less streets than before" is not a good indicator:
.) Layout1 has 2 streets more, but has a nice 6x4 tiles junk left near a street where you can place the next event building.
.) Layout2 has 2 streets less with 26 free tiles, all of them are 1x1 tiles without a street nearby and all you can do with them is place some victory towers or other decoration.

I cleary prefer layout1

2.) Even when ignoring building types there are far too many combinations. If I want to optimize my layout I often start on one corner and end up switching at least 50 buildings around until I find another useful layout. Often this even includes getting rid of 1 production building or a few SoK when I get space for other useful buildings instead.

**Comment by osv** [comment]
there might be general recommendation for user like 3x2 Buildings should be stacked using small wall connected with road, or building with wall more than 7 cells should be connected with 1 cell, eg:

**bad**:
![bad](https://user-images.githubusercontent.com/213405/87930790-58f8f200-ca91-11ea-9fab-bcaa19f8849a.jpg)

**better**:
![good](https://user-images.githubusercontent.com/213405/87930800-5c8c7900-ca91-11ea-95aa-2493a7ab5ef9.jpg)


But common, autorerange city is really no simple task :)

**Comment by osv** [comment]
short wall road connection are better than long example:
**bad**:
![bad](https://user-images.githubusercontent.com/213405/87930973-abd2a980-ca91-11ea-9752-696d2437f100.jpg)

**better**:
![ok](https://user-images.githubusercontent.com/213405/87930974-ac6b4000-ca91-11ea-904f-c9e792a89ae0.jpg)

**Comment by andrgin** [comment]
There are a lot of useful tipps for beginners, but if the suggestion of the algorithm is not better than what a good player would do by hand, we will get flooded with tickets "this solution is better in this case you should change it".
