### ISSUE TITLE
Kosten/Schritt falsch bei Herbstevent

### ISSUE THREAD

**Issue by Blackfir5** [dsiekiera/foe-helfer-extension#1532]
Windows 10 64 Bit
Chrome 83.0.4103.116
beta
2.5.1.0 - Deutsch

![herbst](https://user-images.githubusercontent.com/55910235/87953772-c6b21780-caab-11ea-918d-b406986424ad.png)

Hallo.
Ich denke, die Kosten pro Schritt werden noch nicht richtig erkannt.
Eine Zutat sollte doch ein Punkt bei den Kosten sein, oder? Demnach bei 2 Zutaten = Kosten 2 und auch 2 Schritte. Kosten und Schritte sind beim Herbstevent immer gleich, also immer 1.
Ich denke, die Kosten sollten Auswirkung auf die % haben.  1 Zutat 8% sind besser, als 2 Zutaten 12% (entspricht 1 Zutat - 6%)

**Comment by GeniusTimo** [comment]
Überraschend genug, dass das funktioniert 😅 Das Event kam heute morgen auf den Betaserver, so schnell sind wir nicht 🙈
Aktuell wird als Kosten eines Preises die Anzahl der Zutat angegeben, von der am meisten benötigt wird - anstatt aufzuaddieren

![grafik](https://user-images.githubusercontent.com/47282153/87955852-8ef89f00-caae-11ea-812b-69ff87ade3fc.png)

**Comment by outoftheline** [comment]
Ich persönlich frage mich in wie fern man diesen Event-Helfer hier nutzen kann. Eigentlich ist es wichtiger die Zutaten im Auge zu behalten.

**Comment by GeniusTimo** [comment]
Kosten/Schritt kann man sich sowieso sparen - das stimmt 😅 Aber der Tagespreis ist eventuell trotzdem spannend?

![grafik](https://user-images.githubusercontent.com/47282153/87957304-61acf080-cab0-11ea-95f9-d436e040adbf.png)

**Comment by Blackfir5** [comment]
Stimmt auch.
Ich glaub es war die letzten Jahre so, dass manche Zutaten häufiger vor kamen als andere. Ich weiß nicht ob bewußt von inno gesteuert, oder ob es durch Zufall passiert...
Kann möglicherweise berücksichtigt werden, so wie beim Verhandlungsassistenten, wo das Gut von dem mehr vorhanden ist bevorzugt gewählt wird...

Und @GeniusTimo: passt schon, der Assistent ging automatisch auf, deshalb hab ich mir das angeschaut. Ist halt auch nicht jedes Event gleich aufgebaut und der Assistent muß jedes Event erst "lernen". Dafür gibt's ja den beta und ich dachte mir, ich schreibs gleich mal :)

und ja, wenn dann sind die % auf den Tagespreis interessant, in Bezug auf die Menge der Zutaten.
und ev. eben vielleicht noch in Abhängigkeit der verfügbaren Zutaten?

**Comment by andrgin** [comment]
Der Assistent ist allgemein programmiert und musste bisher nicht auf die jeweiligen Events angepasst wird. Deshalb wird auch nur allgemein von "Schritten" und "großer Preis" gesprochen.
Das mit den Zutaten scheint das erste Event zu sein, wo Änderungen notwendig sind.
Eigentlich will ich es aber vermeiden Sonderlogik pro Event zu machen, da dies unseren Releaseplan stören würde und kontinuierlich Arbeit macht, die dann bei anderen Projekten fehlt.

**Comment by andrgin** [comment]
Edit: Habe mir das Ganze angesehen

1.) Dass die Anzahl nicht stimmt liegt daran, dass ich immer nur das erste Element in der Ressourcenliste angezeigt habe unter der Annahme, dass es nur eine Ressource gibt. In Zukunft werden alle addiert, was bei Events mit nur 1 Ressource ja auch nicht schadet.

2.) Die Sortierung war etwas verwirrend, da die Auswahlmöglichkeiten nach den Kosten sortiert ausgegeben wurden. Ich ändere das einmal, so dass diese in der korrekten Reihenfolge ausgegeben werden. Beim übernächsten Event, das auf dem Auswahlverfahren basiert werde ich mir das ansehen, ob wir das generell so belassen können oder ob es es wieder zurück ändern muss.

3.) Dass es in erster Linie auf die Zutaten ankommt das stimmt, vor allem wegen dem Hauptpreis. Die Zutaten sind oben aufgelistet. Da kann sich jeder selbst überlegen, welche Strategie er verfolgt. Hier etwas vorzuschlagen wäre erstens nicht sinnvoll, da es von einer Menge Dinge abhängt, ob man auf mehr % oder bessere Zutatenaufteilung geht für ein Event.
