### ISSUE TITLE
Cultural settlements addition: sum up needed goods up to certain technology

### ISSUE THREAD

**Issue by capshort** [dsiekiera/foe-helfer-extension#1535]
Hi,

I find the cultural settlement window quite useful and would like to suggest an addition.
As I've completed a few of the settlements by now I know that it makes sense to have intermediate goals with the technologies and it is most efficient to tune the production such that all needed goods for the next intermediate goal are available at about the same time. Hence, it would be helpful to have the possibility to define such intermediate goals with the helper. The helper then sums up all needed goods _up to but not beyond_ that technology (whereas atm it always sums up to the last technology).

**Comment by andrgin** [comment]
If you check the "show sums" checkbox it will show the accumulated sums. Just look up the values in the correct line.

**Comment by capshort** [comment]
Wow, I never noticed that tiny hook. Thanks!
