### ISSUE TITLE
Vorschau auf Produktionsinhalt auf der eigenen Welt

### ISSUE THREAD

**Issue by Kaye68** [dsiekiera/foe-helfer-extension#154]
Seit dem letzten Sommerevent habe ich drei Leuchttürme stehen. Ich kann in der Vorschau zwar sehen, wieviel FP die Leuchttürme bringen (8 bzw. 20), aber nicht, welcher Leuchtturm das ist.
Für die blaue Galaxie wäre es aber schön zu wissen, wieviel FP welcher Leuchtturm bringt.
Kann man dort nicht auch ein Vorschau "Auge" installieren?

**Comment by dsiekiera** [comment]
Ja das macht natürlich Sinn.

**Comment by dsiekiera** [comment]
Ist in integriert und wird in der nächsten Version verfügbar sein:

![Bildschirmfoto_2019-12-15_14-28-33](https://user-images.githubusercontent.com/834814/70863367-c6ff9880-1f47-11ea-8cc3-a8309941c2a8.png)

**Comment by Kaye68** [comment]
Hallo Daniel!

Vielen Dank für Deine tolle Arbeit!

Ich kann Dir gar nicht sagen, was für ein Spielgewinn dieses Tool für mich bringt.

Großartig! Einfach unschlagbar gut!

Herzliche Grüße,

Lady Kaye

 
 

Gesendet: Sonntag, 15. Dezember 2019 um 14:33 Uhr
Von: "Daniel Siekiera" <notifications@github.com>
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: Kaye68 <bec-ker@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Vorschau auf Produktionsinhalt auf der eigenen Welt (#154)


Ist in integriert und wird in der nächsten Version verfügbar sein:
