### ISSUE TITLE
Infobox Willkommen und Icons

### ISSUE THREAD

**Issue by PXWaldy** [dsiekiera/foe-helfer-extension#1542]
In der Box geht es um die Benachrichtigung der Ereignisse und Nachrichten. Bitte macht die Icons wesentlich kleiner, damit der Text mehr Platz hat. und es wäre super wenn man die  Willkommensnachricht ausblenden könnte, so das man direkt sieht wenn was neues auftaucht und kurze Nachrichten nicht von der Willkommensnachricht "überdeckt" werden.

Danke für die super Arbeit :)

**Comment by GeniusTimo** [comment]
> Bitte macht die Icons wesentlich kleiner, damit der Text mehr Platz hat.

Die Icons sind 30 Pixel groß, das sind etwa 1,5% der Full HD Bildschirmbreite, ich finde die genau richtig groß (auch wenn die Box realtiv klein ist) 😅 Man könnte die Icons theoretisch auch ausblenden, wenn das Fenster kleiner als x Pixel ist, aber ich halte das eigentlich nicht für nötig
![grafik](https://user-images.githubusercontent.com/47282153/88460727-9cdb6500-ce9e-11ea-98e9-0cdc822beb89.png)

> man direkt sieht wenn was neues auftaucht und kurze Nachrichten nicht von der Willkommensnachricht "überdeckt" werden.

Inwiefern überdeckt? Die Willkommensnachricht rutscht einfach nach unten 👀

**Comment by PXWaldy** [comment]
Überdeckt, ist falsch ausgedrückt. Ich meine eher das es zu Dominant ist. 
Wenn das Fenster leer ist, dann wandert der Blick direkt dahin, sobald es was neues gibt. Mit der Willkommensnachricht bekommt man nicht immer jede Nachricht mit, die auftaucht. 

Vielleicht ist es auch nur Gewöhnungssache.

Das ausblenden der Icons wäre Super. Vielleicht kann man in den Einstellungen die Funktion unterbringen.

**Comment by GeniusTimo** [comment]
> Vielleicht ist es auch nur Gewöhnungssache.

👍

> Das ausblenden der Icons wäre Super. Vielleicht kann man in den Einstellungen die Funktion unterbringen.

Wir versuchen bei den Einstellungen immer, dass das nicht zu überfüllt wird - ich schaue mal, ob ich das mit der Breite schnell umsetzen kann

**Comment by strongstancer** [comment]
Man könnte einfach die Willkommensnachricht mit "Box leeren" auch entfernen lassen. Wenn man das Fenster neu aufmacht, kann sie ja meinetwegen wieder auftauchen. Aber mich stört das auch extrem und ich denke, dass es mir nicht alleine so geht :)

**Comment by PXWaldy** [comment]
Auch ne Möglichkeit, Strongstancer

**Comment by GeniusTimo** [comment]
Hatte sie da sogar absichtlich nochmals eingebaut, aber gut - wenn es euch stört, kann ich das beim Leeren auch rausnehmen 😅
Ich dachte mir, dass ist gut, wenn man da sieht, wann die Infobox zuletzt geleert wurde

**Comment by PXWaldy** [comment]
Danke, Timo

Für mich ist die Infobox einer DER features beim Helfer!
Kriegst du es hin, das man die GG Nachrichten auch in der Stadt angezeigt bekommt? Also so wie die GEX Benachrichtigung.

**Comment by strongstancer** [comment]
@PXWaldy 
Denke das wird nicht möglich sein, da die Infos vom Server nur übermittelt werden, wenn diue GEX Ansicht geladen ist.

**Comment by GeniusTimo** [comment]
> Kriegst du es hin, das man die GG Nachrichten auch in der Stadt angezeigt bekommt? Also so wie die GEX Benachrichtigung.

Das hätte vermutlich jeder gerne, aber sobald du die GG verlässt, sendet Innogames keine Daten mehr an den Browser 🙈 Um das zu Erzielen, müsste man ein Paket an den Server senden, dass das Betreten der GG simuliert, aber das wäre natürlich gegen die Regeln und somit werden wir das auch nicht umsetzen.
PS: Es ist auch sinnvoll, dass Innogames deinen Browser nicht permanent mit GG-Ereignissen zuspammt, in der Diamantliga wäre das eine Menge Traffic - wieso das bei den GEX anders gehandhabt wird, weiß ich nicht 😅 Aber diese Daten bekommen wir immer vom Server zugesandt, egal ob man in den GEX ist oder nicht 🤷

**Comment by PXWaldy** [comment]
Ja, aber gerade in der Dia-Liga wäre das deeeeer Hammer. ;)
Aber auch verständlich! 

Danke euch für die Erklärungen. Schönes WE

**Comment by strongstancer** [comment]
Zum them Willkommensnachricht noch: Ich verstehe das mit der Uhrzeit, wann sie zuletzt geleert wurde. Ginge das aber nicht anders? evtl. bei Mouseover über den "Box Leeren" button?

**Comment by PXWaldy** [comment]
Wofür braucht man die Zeit wann die Box geleert wurde?

**Comment by GeniusTimo** [comment]
> Ich schaue mal, ob ich das mit der Breite schnell umsetzen kann

Habe zuerst an CSS Media Queries gedacht, nach kurzer Recherche war klar: Das wird so nix, Media Queries sind nur für die Geräteabmessungen und nicht für Elemente ([Quelle](https://stackoverflow.com/a/12319280/13023030), falls es jemanden interessiert)
Es gibt eine [Library](https://github.com/marcj/css-element-queries), die das aber unterstützen würde - muss ich mit den Anderen abklären, ob es das wert ist 🙈

> Wofür braucht man die Zeit wann die Box geleert wurde?

Als ich die Willkommensnachricht eingebaut hatte, fand ich das eine nützliche Information 🤷

**Comment by PXWaldy** [comment]
> 
> Habe zuerst an CSS Media Queries gedacht, nach kurzer Recherche war klar: Das wird so nix, Media Queries sind nur für die Geräteabmessungen und nicht für Elemente ([Quelle](https://stackoverflow.com/a/12319280/13023030), falls es jemanden interessiert)
> Es gibt eine [Library](https://github.com/marcj/css-element-queries), die das aber unterstützen würde - muss ich mit den Anderen abklären, ob es das wert ist 🙈
> 

Das mit den Icons ist noch nicht mal sooooo wichtig. Die Nachricht ist viel störender.

**Comment by GeniusTimo** [comment]
> Das mit den Icons ist noch nicht mal sooooo wichtig. Die Nachricht ist viel störender.

Nachricht ist in der Beta raus

**Comment by GeniusTimo** [comment]
> Das mit den Icons ist noch nicht mal sooooo wichtig.

Wir halten es nicht für notwendig, dafür extra eine neue Library einzubinden (auch, weil das nicht wirklich störend ist)
Damit sind alle Fragen beantwortet und Wünsche erfüllt 🙈
