### ISSUE TITLE
Änderungswünsche: Marktübersicht

### ISSUE THREAD

**Issue by strongstancer** [dsiekiera/foe-helfer-extension#1543]
Hallo zusammen,

diesmal auf deutsch, da es dann einfacher für mich ist 

Zuerst einmal vielen Dank für das coole neue Feature. Was mich jedoch stört ist folgendes:

Bei "Fair (bei niedrigerem Lagerbestand)" wird nur die ursprünglich Differenz berücksichtigt, nicht aber die Differenz nach dem Tausch. Das ist in vielen Fällen wenig hilfreich. Extrembeispiel:
Gut A: 99
Gut B: 100
Handel: Angebot: 100 Gut A, Bedarf: 100 Gut B
Das Fenster würde den Handel jetzt anzeigen, wenn ich den jedoch annehme, habe ich am Ende 199 von Gut A und 0 von Gut B. Intuitiv wäre, wenn dort nur solche Handelsangebote angezeigt werden, bei denen die Differenz nach dem Tausch geringer als vorher ist. Also bei meine Beispiel: Gut A 49 und Gut B 150, damit würde sich die Differenz von 101 vorher auf 99 (149 zu 50) nachher reduzieren.

Weiterer kleiner Punkt: Bei Angebot und Bedarf würde ich gerne auch Bereiche auswählen, also nicht nur ein Gut, oder ein ZA, sondern z.B. von Eisenzeit bis FMA oder alles über HMA oder so.

**Comment by andrgin** [comment]
1.) Das mit dem "fair bei niedrigem Lagerstand" wurde wurde korrigiert.

2.) Was die ZA angeht:
Ja in manchen Situationen macht das Sinn, Allerdings muss ich mir erst was überlegen, wie ich das im GUI unter bekomme ohne dass es zu überladen wird.

**Comment by strongstancer** [comment]
Danke für die Änderung zu 1)

zu 2) habe ich auch schon überlegt, wie man das machen könnte. Bisher sind mir da zwei sachen eingefallen:
-> Bei den Auswahlfeldern bei Angebot und Bedarf auch mehrfachauswahl zulassen.
-> Hinter den Feldern zwei Checkboxen für "und höhere ZA" bzw. "und niedrigere ZA", die sich gegenseitig ausschließen

vielleicht hilft das ja, bei den Überlegungen ;)
