### ISSUE TITLE
Market do not open automatically

### ISSUE THREAD

**Issue by lnplnp** [dsiekiera/foe-helfer-extension#1545]
Hi,

Could you not open the Market window automatically ?
I do not use it... or put a parameter to know if user want it or not.

Thanks.

**Comment by andrgin** [comment]
If you dont want it to open automatically you should disable it in the settings menu ;-)

**Comment by lnplnp** [comment]
oups ! Sorry I didn't notice it...

I have disable it and it is ok now.

Thanks !
