### ISSUE TITLE
[Player overview - GBG] Table too narrow

### ISSUE THREAD

**Issue by Beta-Wolf** [dsiekiera/foe-helfer-extension#1547]
A friend of mine has the following issue:

The total amount of points isn't visible anymore cause the table is too narrow. What caused it, is unknown.

Image:
![image](https://user-images.githubusercontent.com/31244425/89037663-3e4f3480-d33f-11ea-9fc2-068f0b3f0aa4.png)

It should look like this:
![image](https://user-images.githubusercontent.com/31244425/89037697-4d35e700-d33f-11ea-984f-dc03e9ba6c77.png)

He tried removing the cookies and resetting the box coordinates, but no effect. He doesn't have the issue on every server. On others, it looks fine.

**Comment by GeniusTimo** [comment]
Maybe there is a player with a very long name in his guild?

**Comment by andrgin** [comment]
I think the translation "Onderhandelingen" is a lot longer than the English one and it does not contain spaces so the table cant make a line break.

**Comment by Beta-Wolf** [comment]
We are in the same guild. My table is fine, his isn't.

**Comment by andrgin** [comment]
Oh now I see the screenshots.

Which version are you and your guild mate using?

**Comment by Beta-Wolf** [comment]
![image](https://user-images.githubusercontent.com/31244425/89042719-ac97f500-d347-11ea-8f43-e62929a09b47.png)

**Comment by andrgin** [comment]
Hhm strange.

Can you try if it is the same if you reload the game and open and directly open the GBG window without opening any other tool of the helper.

What I noticed:
The box with the wrong layout has correct 22 minutes. The one with the correct layout has éé

**Comment by Beta-Wolf** [comment]
> The box with the wrong layout has correct 22 minutes. The one with the correct layout has éé

It means 1 minute ago in my language.

**Comment by outoftheline** [comment]
Hmm i guess we should make the width change with the content

**Comment by andrgin** [comment]
I still dont know why it is displayed differently, but even with the correct layout it will be too narrow in the Dutch translation if names are a bit longer or you are doing more than 1000 negotiations to it will be 4 digits.

Making the box wider would be a solution, but I would prefer having the number or the last 3 columns wrapping into the new row as rows are already pretty wide considering there are numbers with 3 or 4 digits in each cell.

**Comment by outoftheline** [comment]
okay, so like this?
![Bildschirmfoto 2020-08-02 um 09 05 32](https://user-images.githubusercontent.com/7482863/89117604-66ee4000-d49f-11ea-981a-a074ee955658.png)
