### ISSUE TITLE
Calculate Guild Treasury Contributions

### ISSUE THREAD

**Issue by nikhilgupta-repos** [dsiekiera/foe-helfer-extension#1549]
Hi,
Looking to fetch some information for the guild where we get to know how many guild goods a city is producing and what era a guild member is .. at the end we want to collect information in this table -

![image](https://user-images.githubusercontent.com/5977607/89248006-3c51d380-d5d4-11ea-91c8-b29e4eeddf5e.png)

Is this possible, not sure if you guys accept pull requests .. but I can try to put in the work for the same.

Also not sure if it will violate any Inno's policy, please let me know that as well.

**Comment by andrgin** [comment]
We already have an export tool for the guild treasure log. If you open the guild treasury log. Unfortunately we do not get the whole log at once, so you have to scroll through all the pages you want.
Then download the .csv file and open it with Excel (or simililar tool like Open Office calc).

An easy way to get information about your guild treasury by creating a pivot table with era, message and amount

The levels of arc/obs etc. are nice in theory, but this does not tell if your guild members are collecting their buildings every day.

**Comment by nikhilgupta-repos** [comment]
Using the method mentioned, able to figure out treasury donations.
