### ISSUE TITLE
Text filter in infobox

### ISSUE THREAD

**Issue by saml1991** [dsiekiera/foe-helfer-extension#1552]
Some sort or text filtering would be great in the info box.

Examples:
You only want to be notified of messages in an arch chat group you type "1.9" in the filter.

You only want to be notified about sector A1: Mati Tudokk in GBG you type "A1: M" in the filter.

You want to see the GBG OR chat thread only you type "1.9", "A1: M" in the filter.

Thanks very much for the great app :)

**Comment by Th3C0D3R** [comment]
Coming with the next Update or already inside the beta branch
