### ISSUE TITLE
Guild Battleground negociation helper not showing

### ISSUE THREAD

**Issue by DanChaltiel** [dsiekiera/foe-helfer-extension#1553]
Hi, thanks for this great extension.

The negotiation helper is showing well in the battle map and in the guild exploration, but not in the GBG.

(Sorry, some terms might be lost in translation)

**Comment by andrgin** [comment]
Negotiation helper has been removed from GBG because of a request of Inno:
https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/112
