### ISSUE TITLE
Old playername displayed in the stats of FoE-helper

### ISSUE THREAD

**Issue by Beta-Wolf** [dsiekiera/foe-helfer-extension#1563]
The site is using my old player name Atókirina instead of Atokirina.

I'm also obligated to enter the username Atókirina to log-in.

Is there any reason why the FoE-helper can't detect the name change?

**Comment by outoftheline** [comment]
Well, the data is probably only transmitted once as name changes are rare.

**Comment by strongstancer** [comment]
Had the same problem, asked in the forum, was told to write an e-mail to the adress in the impressum on the site but never got another answer. Sadly this means I cant use the GB market since ppl cant pm me ingame because of the wrong username
