### ISSUE TITLE
Verbesserungsvorschlag: Einheitliche Position der drei Marker

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#1569]
Moin,

ich hätte einen Vorschlag für die drei Marker, die die noch vorhandenen Ladungen für  Kriegsbeute, Diplomatische Geschenke, und Helfende Hände anzeigen.

Aktuell werden diese in einer fremden Stadt rechts oben angezeigt:

![Anmerkung 2020-08-19 145256](https://user-images.githubusercontent.com/17932878/90637246-0b0c1100-e22c-11ea-8a93-1101d54fb528.png)

und in der GEX Übersicht neben den Modul-Buttons:

![Anmerkung 2020-08-19 145222](https://user-images.githubusercontent.com/17932878/90637293-195a2d00-e22c-11ea-8ea6-199489febf37.png)

Zum einen finde ich persönlich das inkonsistent und verwirrend, wenn solche Marker immer woanders sind, und zweitens hat die Positionierung in der GEX den Nachteil, dass sie zumindest bei mir mit anderen Fenstern kollidiert, da ich diese gerne so am rechten Rand positioniere, dass diese bündig zu den Buttons enden (beispielhaft):

![Anmerkung 2020-08-19 145749](https://user-images.githubusercontent.com/17932878/90637579-781fa680-e22c-11ea-8d5d-744a4cadb7fe.png)

Ich würde vorschlagen, dass man diese Marker an die freie Stelle direkt unterhalb der Relikttempel-Anzeige setzt. Das passt in der GEX, auf der Karte der Kontinente sowie in fremden Städten (ob das auch bei GG passt, kann ich leider erst morgen nachschauen, aber ich denke auch da sollte es passen). Auf diese Weise könnten diese auf allen Screens an der gleichen Stelle sitzen und müsste nicht mehr für die GEX verschoben werden :-)

**Comment by andrgin** [comment]
Grundsätzlich ist die vorgesehene Position rechts oben, dort wo in der Stadt auch die Inno Icons sind.
Bei der Gex ist das leider nicht möglich, da die Reliktanzeige im Weg ist. Mit 3 Symbolen mag sich das noch ausgehen aber wenn man mehr Gebäude wie Friedensturm etc. hat reicht es nicht mehr aus.
