### ISSUE TITLE
Erreur sur des liens de votre site

### ISSUE THREAD

**Issue by FouPouDave** [dsiekiera/foe-helfer-extension#1571]
Bonjour,

En allant à cette adresse : https://foe-rechner.de/stats/events/motivations

j'ai ce message d'erreur :  
Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_entries_fr9' doesn't exist] in EXECUTE("SELECT ops.ops_id, ops.other_id, ops.other_name, ops.is_neighbor, ops.is_friend, ops.is_guild_member, (SELECT UNIX_TIMESTAMP(opse.date_visit) FROM other_players_service_entries_fr9 opse WHERE opse.ops_id = ops.ops_id ORDER BY opse.date_visit DESC LIMIT 1) AS last_visit FROM other_players_service_fr9 ops WHERE ops.player_id = 8697332 AND ops.other_id = '13221' AND ops.world = 'fr9' ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT \n\t\t\t\tops...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1216): ADOConnection- in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79

De même depuis ces adresses : 
https://foe-rechner.de/stats/events/social-player
https://foe-rechner.de/stats/events/friends-tavern
https://foe-rechner.de/stats/events/attacks

Bon courage !

**Comment by b-tomasz** [comment]
Ich erhalte die selbe Fehlermeldung, aber nur wenn ich den Betaserver ausgewählt habe. Bei meiner hauptwelt, de19 funktioniert es ohne Probleme

**Comment by FouPouDave** [comment]
Non moi c'est dans le jeu lui même
