### ISSUE TITLE
Count battle points and add it to statistics

### ISSUE THREAD

**Issue by Julian2424** [dsiekiera/foe-helfer-extension#1583]
Hey, I have an idea, but am not sure, if it is possible.
After a won battle, get the battle points and add a statistic for it (how much points, how many battles in the last week or 2, ...). I know, it is not really necessary at the moment for most of us, but beta and en players already have the PvP-Arena and they can't see how many points the got. It would be nice to get it through the FoE-Helper.

**Comment by outoftheline** [comment]
Weil die PvP Arena vorerst nicht kommt und man noch nicht absehen kann in welcher Form sie zurück kommt, schließe ich hier mal.

Bitte nich haun.
