### ISSUE TITLE
LG-Investitionen Innovation Tower

### ISSUE THREAD

**Issue by SkateScout** [dsiekiera/foe-helfer-extension#1587]
Für den Inno Tower wird Level 3-4 vorgeschlagen mit 1FP Gewinn pro Tag.
Beide Level haben aber jeweils 2FP pro Tag also bringt ein Leveln hier gar nichts.
![image](https://user-images.githubusercontent.com/919349/92413154-0f528c80-f14f-11ea-86a3-2c7399f88b0e.png)

**Comment by andrgin** [comment]
Da ist wohl unter lvl10 etwas verrutscht. Wird mit dem nächsten Update gefixed.

Alle Ergebnisse über lvl10 stimmen aber.
