### ISSUE TITLE
Anzeige was zu plündern ist, unvollständig

### ISSUE THREAD

**Issue by dsiekiera** [dsiekiera/foe-helfer-extension#159]
Es fehlen einige Gebäude:
- Kirchgarten-Set
- Pizza-Set
usw.

**Comment by andrgin** [comment]
Bezieht sich das auf die gesamte Produktion oder nur auf die Boni, die erst durch die Gebäude in der Nähe entstehen?

**Comment by andrgin** [comment]
OK Problem erkannt:

Meiner Meinung nach sollten plünderbare LGs definiert werden durch:
.) Alle Gütergebäude
.) Alle Produktionsgebäude und Wohngebäude, wenn sie nicht motiviert sind (z.B. ein SdW ist plünderbar, allerdings nicht wenn er motiviert ist)

Einzige mir bekannte Ausnahmen:
.) Großer Leuchtturm (dieser ist nicht plünderbar, das wurde erst kurz vor Release geändert)
