### ISSUE TITLE
IgnorePrevEra and IgnoreCurrentEraOptional seems wrong ? !

### ISSUE THREAD

**Issue by lnplnp** [dsiekiera/foe-helfer-extension#1591]
Hi,

When I turn off one or two of these options, it requires less resources than when I turn them on.
But when you ignore a technology, it should cost less resources and not more, right?

![image](https://user-images.githubusercontent.com/934004/92699621-1dbac700-f34e-11ea-9648-bc168870d4f8.png)
![image](https://user-images.githubusercontent.com/934004/92699654-2a3f1f80-f34e-11ea-8cad-2000664b11c2.png)

In addition, what are the technologies that you consider as optional?

Thanks

**Comment by outoftheline** [comment]
> In addition, what are the technologies that you consider as optional?

Dead ends are optional technologies

Regarding the main issue: need to look into it

**Comment by andrgin** [comment]
In the first screenshot spectator sports is ignored because it is an optional technology of a future era (I suppose you are in progressive era). The rest is 1088 FP.

In the second screenshot it is not ignored meaning you have to research it. This means you have to pay 108FP more (total 1196).

**Comment by lnplnp** [comment]
![image](https://user-images.githubusercontent.com/934004/92814828-eb4bb100-f3c3-11ea-9287-df1094b836cf.png)

To be sure, is "Maison de ville" optional tech ?

**Comment by outoftheline** [comment]
And Roues à aubes
