### ISSUE TITLE
Incidents: 2-Lane Road Bug

### ISSUE THREAD

**Issue by MKurn16** [dsiekiera/foe-helfer-extension#1596]
For nearly a month now, my incidents tab says there is an incident on a 2-lane road, but I do not have any 2-lane roads in my city.  I get 2-4 per day on average that show as 2-lane road but I have moved buildings searching for these incidents, but they do not exist.  
![FOE Support](https://user-images.githubusercontent.com/48458354/92982361-cf9be580-f46b-11ea-93a2-e255c00aa812.png)

**Comment by belikoviv** [comment]
It is your problem - not Helper.
The game server take in mind that at your age you **may** have 2-lane roads and it never check are you really have its. And generates incidents counting that you **have** 2-lane roads regardless have you its or not.
You need to place at least one 2-lane road (in any place - not necessary to connect to City Hall) and take incidents from it.

**Comment by dsiekiera** [comment]
Absolutely correct. Thanks for the explanation @belikoviv.

**Comment by MKurn16** [comment]
Thank you, I changed the double alleys to 2-lane motorway and it works fine that way.
