### ISSUE TITLE
Kostenrechner

### ISSUE THREAD

**Issue by Aecyy** [dsiekiera/foe-helfer-extension#16]
Hallo,

erst mal danke für das Plugin. Sowas hab ich mir schon lange gewünscht :)

Ich durchsuche meine Nachbarschaft mit dem Kostenrechner gerne nach Schnäppchen und packe häufiger schon 1FP rein um das LB zu beobachten. Mir ist aufgefallen, dass schon reingestecke FP nicht berücksichtigt werden. So wird ggf. 1FP zu wenig angegeben um sich abzusichern und man bekommt angezeigt, dass Platz 2 ein Plus bringen würde obwohl man z.b. schon auf Platz 1 steht in dem LB.

Ist es möglich die eigenen Punkte zu berücksichtigen oder ist das technisch nicht umsetzbar?

**Comment by Aecyy** [comment]
Guten Morgen,

seit dem letzten Update ist der Kostenrechner leider recht nutzlos geworden. Jetzt wird mir nur noch angezeigt, dass ich mit meinem 1FP aktuell z.b. 55FP Gewinn machen würde. Aber er zeigt nicht mehr an, dass ich mich z.b. mit 30FP absichern könnte und dann 25FP Gewinn sicher hätte.
Die Funktion fand ich vorher sehr praktisch um die Nachbarschaft nach Schnäppchen zu durchforsten :)

Grad was entdeckt. Hab hier ein LB mit 1FP drin. Dann steh ich in dem Kostenrechner PopUp Einsatz 1FP und Gewinn 161FP in blauer Farbe. Wenn ich jetzt den Prozentsatz der Arche erneut eingebe wechselt die Anzeige auf die gewohnten 141FP Einsatz mit 21FP Gewinn möglich. Was ja auch sinnvoll ist :)

**Comment by dsiekiera** [comment]
Ihr mit eurem 1 FP... -.-

Dafür ist das Tool schlicht weg nicht ausgelegt. Es zeigt an ob man was geischert mit Gewinn einzahlen kann oder aber ob man schon eingezahlt hat.
Wie groß soll denn die Box werden wenn ich jede mögliche Option anzeigen lassen würde? 
Das schreibt sich einfacher als es ist.

**Comment by Aecyy** [comment]
Ach so....also wenn ich noch nix eingezahlt hätte sollte direkt die gewohnte Anzeige kommen? 141FP einzahlen und 21FP Gewinn etc.? Hmmm......

So oder so. Liebe das Addon 👍👍👍
