### ISSUE TITLE
[foe-rechner.de] Statistics - Motivate / Polish - Evaluation player: Period: All-time

### ISSUE THREAD

**Issue by Beta-Wolf** [dsiekiera/foe-helfer-extension#1607]
**Link to the site:** [https://foe-rechner.de/stats/events/social-player?rep=m&list=g&limit=12](url)

**Description idea:** I would like to have an **All-time** option as a period. 

**Motivation:** It's always interesting to have an **All-time** option in your stats. 

**Image:**

![chrome_2020-09-22_23-39-15](https://user-images.githubusercontent.com/31244425/93940638-27203800-fd2d-11ea-8c33-c979a709105b.png)

**Comment by outoftheline** [comment]
I'll close this as the feature has been removed
