### ISSUE TITLE
Your FP investment summary numbers off

### ISSUE THREAD

**Issue by dlister70** [dsiekiera/foe-helfer-extension#1608]
I've noticed that the amount of forge point profit that is listed in my FP investment summary is not correct.  I'm wondering how that number is calculated?

Here is an example from today:

https://imgur.com/a/ZnzdotZ

I only had one building on page two, which I have (crudely) pasted to the image at the bottom.  

Most of the buildings were from a 1.9x thread, and my Arc is level 111, so I'm making profit even at 1.9x.  As a result, I have profit on almost every single building except for that one Oracle where I am losing -10fp.  However, the FOE helper says that I am losing a total of -148 forge points.

**Comment by dlister70** [comment]
I somehow missed the low level Arc that I was helping a guild member level by putting in extra points.  I'm stupid.

**Comment by dsiekiera** [comment]
No problem. We all makes mistakes :-)

Have fun with a the extension.
