### ISSUE TITLE
Eigenanteilsrechner/Kostenrechner

### ISSUE THREAD

**Issue by Blackfir5** [dsiekiera/foe-helfer-extension#161]
Als erstes, ich finde den Eigenanteilsrechner seit dem letzten update einfach nur genial!
Die Live-Aktualisierung, das Auto-übernehmen der tatsächlich eingezahlten FP, die ja ein paar Wünsche hier überflüssig gemacht hat... Echt spitze.
Auch die Anzeige beim Kostenrechner, dass man jetzt auch ständig sieht, wieviele FP für safe benötigt werden hast du sehr schön umgesetzt!

Mir ist aufgefallen, dass der Eigenanteilsrechner auch mitzählt, wenn man in ein fremdes LB einzahlt. Ich hab meist beide Fenster offen...
Sieht etwas merkwürdig aus, vor allem weil er ja bei P5 anfängt, Überzahlung rechnet, dann weiter springt auf P4 usw. War so auch sicher nicht geplant, aber mich bringt das irgendwie auf die Idee, den Kostenrechner im Eigenanteilsrechner zu integrieren und einen Rechner daraus zu machen. man könnte sich damit ein Fenster ersparen...
Ich weiß, die Spalten sind nicht ganz die gleichen, aber auch wenn der Eigenanteilsrechner eine spur breiter würde, es entfällt ein Fenster und man hätte insgesamt wieder mehr ausblick auf die Stadt.
Auch der Aktualisierungsbutton von Issue 135 würde, mit der ohnehin live-Aktualisierung, überflüssig werden.

**Comment by dsiekiera** [comment]
Danke für die Blumen. Aber der Großteil des Codes kommt aus der Feder von @andrgin der mir seit ein paar Wochen beim programmieren hilft und mich tatkräftig unterstützt.

Über die Zusammenführung haben wir auch schon gesprochen aber es nicht umgesetzt. Dafür gibt es mehrere Gründe. Auch gibt es technische Hürden die das erkennen der LG Art (LG Eigen, LG fremd) usw. tricky machen.

Mit der umfangreichen Funktion und arbeitsweise haben wie den EA-/Kosten-rechner, glaube ich, auf ein neues Level gehoben was erst mal allen gerecht werden sollte. ;-)

**Comment by Blackfir5** [comment]
Auf alle Fälle^^
