### ISSUE TITLE
Error when trying to consult motivation statistics

### ISSUE THREAD

**Issue by Sebien72** [dsiekiera/foe-helfer-extension#1612]
Hi,
Thank you for this wonderfull tool.
I have this error when trying to consult the motivation statistics page.

> Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_entries_fr15' doesn't exist] in EXECUTE("SELECT ops.ops_id, ops.other_id, ops.other_name, ops.is_neighbor, ops.is_friend, ops.is_guild_member, (SELECT UNIX_TIMESTAMP(opse.date_visit) FROM other_players_service_entries_fr15 opse WHERE opse.ops_id = ops.ops_id ORDER BY opse.date_visit DESC LIMIT 1) AS last_visit FROM other_players_service_fr15 ops WHERE ops.player_id = 9529436 AND ops.other_id = '12172' ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT \n\t\t\t\tops...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1216): ADOConnection->_Execute('SELECT \n\t\t\t\ in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79

When I upload the info, I have this error : 

> Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table ‘foecre_site3.other_players_service_entries_fr15’ doesn’t exist] in EXECUTE(“SELECT item_id FROM other_players_service_entries_fr15 WHERE item_id IN (877230928,877230316,877218965,877215955,877208129,877196841,877191731,877178526,877165269)”) in /usr/www/users/foecre/api.foe-rechner.de/inc/vendor/adodb/adodb-exceptions.inc.php:86 Stack trace: #0 /usr/www/users/foecre/api.foe-rechner.de/inc/vendor/adodb/adodb.inc.php(897): adodb_throw(‘mysqli’, ‘EXECUTE’, 1146, ’Table ‘foecre_s…’, ‘SELECT item_id …’, false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/api.foe-rechner.de/inc/vendor/adodb/adodb.inc.php(877): ADOConnection->Execute(‘SELECT item_id …’, false) #2 /usr/www/users/foecre/api.foe-rechner.de/inc/vendor/adodb/adodb.inc.php(1335): ADOConnection->Execute(‘SELECT item_id …’, false) #3 /usr/www/users/foecre/api.foe-rechner.de/inc/classes/db.php(128): ADOConnection->GetArray(‘SELECT item_id …’, false) #4 /usr/www/users/foecre/api.foe-rech in /usr/www/users/foecre/api.foe-rechner.de/_inc/vendor/adodb/adodb-exceptions.inc.php on line 86

Could you please help me ?

**Comment by dsiekiera** [comment]
This errors may be fixed?

**Comment by Sebien72** [comment]
Yes It works now, many thanks 👍
