### ISSUE TITLE
missing buttons

### ISSUE THREAD

**Issue by decommentator** [dsiekiera/foe-helfer-extension#1614]
On a new installed pc I see a button for example "which fp gb should you upgrade next"
On 2 other pc's, where the extionsion is updated everytime I don't see them

Uninstalled the extension
Reinstalled the extension

**Comment by dsiekiera** [comment]
Have u ever scrolled down the menu via arrow at the bottom?

**Comment by decommentator** [comment]
> Have u ever scrolled down the menu via arrow at the bottom?

sure

**Comment by dsiekiera** [comment]
Very peculiar.

@decommentator all versions are the same?

**Comment by decommentator** [comment]
yes all same version

"solved" this today by exporting foehelper settings from new pc and import them on other pcs
