### ISSUE TITLE
List of GvG sectors with empty defense slots

### ISSUE THREAD

**Issue by CamaradePopoff** [dsiekiera/foe-helfer-extension#1616]
When the Guild vs Guild map is open on a given age, or on the "all ages" battlefield, it would be nice to have a new feature of the FoE Assistant in order to point out which sectors have empty defense slots, and how many slots.

It would save time by avoiding to open all the sectors just to check if they have empty defense slots.

**Comment by outoftheline** [comment]
So you mean for defending your own sectors?

Unfortunately the information about defense slots is only transmitted when opening a sector, so the helper cannot save any clicks for you.

**Comment by CamaradePopoff** [comment]
Alright, understood. In that case, is it possible to proceed as follows?
- When opening the map of a given age, there is a request send by the game that returns the list of owned sectors, with their Ids.
- For each sector Id, trigger the request to get sector information and parse the response to find sectors with empty defense slots.
- Display the found empty slots in a report in the FoE Assistant.

Would such practice be "legal" and allowed by InnoGames?

**Comment by Th3C0D3R** [comment]
Sending own requests to the InnoServer are not allowed (illegal)

**Comment by CamaradePopoff** [comment]
OK, then I guess you can close this issue, for it is not feasible :(
Thanks.
