### ISSUE TITLE
Gildengefechte

### ISSUE THREAD

**Issue by Mursanian** [dsiekiera/foe-helfer-extension#162]
Hast du schonmal reingeguckt in die Gildengefechte?
Kann ausgelesene werden wer wo Angreift, wäre cool wenn es dafür ne Kleine Infobox gibt, damit man seht welche Gildenmitglieder Mist bauen und falsche ziele angreifen. Oder wie viele Gegnerische Spieler gerade wo angreifen und aktiv sind?

**Comment by dsiekiera** [comment]
Das hab ich natürlich bereits untersucht. Inno hat da aber was neues eingebaut.

GEX + Outpost + Main (Hauptansicht) laufen alle über einen Websocket (Hintergrund-Datenkanal). Daher kann man die Infobox dort überall offenlassen und bekommt sämtliche info's dennoch.

Bei den Gildengefechten wechselt mit der Ansicht auch der "Kanal" des Websockets. Hin und zurück. Also würde eine "Infobox" nur dann etwas empfangen wenn man auch dort bei den Gefechten bleiben würde.

Kurz, es geht leider nicht.

**Comment by Mursanian** [comment]
Darf ich fragen ob bei den Gefechten irgendwo gesendet wird wer wo angreift? Also Name des Spielers?

Interessiert mich, weil dann wäre es technisch möglich zu sehen, wer wo falsch angreift und könnte herausfinden wer die Deppen der Gilde sind.

Und wenn ja, hast du vielleicht nen guten Startpunkt wenn ich mich informieren will wie man den Websockets zuhört und da ggf Informationen raus extrahiert?

**Comment by dsiekiera** [comment]
Das steht leider nicht dabei. Auf dem Bild siehst du alles was kommt. Das geht nur nach Gilde. Spieler werden hier nicht unterschieden:

![Bildschirmfoto 2019-11-17 um 19-53-12](https://user-images.githubusercontent.com/834814/69012246-03090300-0974-11ea-93ad-7d765253d1c2.png)

**Comment by Mursanian** [comment]
Schade, aber vielen Dank das du nochmal reingeguckt hast.

Wäre vielleicht auch einfach nen Feature Request für Inno
