### ISSUE TITLE
Güterübersicht Aussenposten funktioniert nicht mehr

### ISSUE THREAD

**Issue by siouxxx83** [dsiekiera/foe-helfer-extension#163]
![qqqq](https://user-images.githubusercontent.com/17090336/68995156-d75e1e00-088a-11ea-927c-efa657fedb3d.PNG)
Es funktioniert nicht ganz bei mir. Unter vorhandenen Güter steht überall 0.

**Comment by andrgin** [comment]
Wir haben ein Update in Bearbeitung, das die Probleme hoffentlich lösen sollte.
