### ISSUE TITLE
Kostenrechner toggelt jetzt immer...

### ISSUE THREAD

**Issue by mordillo666** [dsiekiera/foe-helfer-extension#1631]
Im neuen Update habt ihr ja einen Toggle für den Kostenrechner eingebaut, dass er sich wieder schließt, wenn man das zweite Mal den Menu Punkt klickt.

Bei mir schließt er sich aber auch jedes mal, wenn ich das nächste LG öffne...^^

Bzw starte ich erst den Kostenrechner, gehe dann in eine LG Liste und öffne ein LG, schließt sich der Kostenrechner wieder.

**Comment by dsiekiera** [comment]
Ist bereits gefixt.
