### ISSUE TITLE
GB Cost Calculator vanishes

### ISSUE THREAD

**Issue by clericpreston2** [dsiekiera/foe-helfer-extension#1634]
Since the last update, every time I click on a new GB, the CC disappears and I must click on it each time when I visit a new GB. It is very annoying. Why did you do it?

**Comment by GeniusTimo** [comment]
This issue was addressed in update 2.5.2.8 and already mentioned in #1631 #1632 - please be patient until the Chrome Store retrieves the update. (You could check the installed version in the helper settings)
If there are further problems feel free to reach out to us again!
