### ISSUE TITLE
Filter der Marktübersicht funktioniert nicht richtig

### ISSUE THREAD

**Issue by mordillo666** [dsiekiera/foe-helfer-extension#1637]
Ist mir heute zum ersten Mal aufgefallen:

https://abload.de/image.php?img=marktbersicht4fjhs.png

**Comment by Th3C0D3R** [comment]
wo ist das problem?

**Comment by mordillo666** [comment]
Filter steht auf 50 und zeigt mir trotzdem 10er Angebote an

**Comment by Th3C0D3R** [comment]
Oh xD mal fett übersehen 😅 ja da scheint wirklich was nicht zu funktionieren

**Comment by andrgin** [comment]
Die Filter mit der Mindestmenge gilt nicht für Gildenmitglieder, da es bei denen keine Handelsgebühren gibt.

**Comment by mordillo666** [comment]
Ah, das erklärt einiges. ;-)
Wieder was dazu gelernt.
Danke :-)
