### ISSUE TITLE
Eigenanteilsrechner

### ISSUE THREAD

**Issue by Tsching-Foe** [dsiekiera/foe-helfer-extension#1638]
Hi!
Drei Wünsche:
1. Wenn P5(0), dann sollt er bei "Alle" nicht mit angeben werden. Ich möchte schnell alle Plätze für die 1,9 auswählen können. Oder aber ein extra Button.
2. Vor jeden P eine #, wenn der Platz unsicher ist. Habe jetzt schon Gilden erlebt, die das so machen, um die unsicheren Plätze zu erkennen. #P1(219)
3. Zwei Ausrufezeichen hinter einen Platz, wenn er in "Gefahr" ist. P1(798)!!
Danke :)

**Comment by dsiekiera** [comment]
Hey,

das mit dem P5(0) macht Sinn, aber irgend welche Zeichen solltest Du dir selber reinschreiben. Wir können das leider nicht für einzelne individualisieren.

Weiterhin würde ich dir empfehlen mit "Auto" zu spielen und nicht bewusst unsichere Plätze zu posten. Das mag keiner 😉

**Comment by Tsching-Foe** [comment]
Hey!

 

Da bin ich bei dir. Doch wenn Du Speedleveln machst oder Dein LG gleich levelst, wenn es in der 1.9 genommen wurde, dann geht das ja ratz fatz.

Vielleicht wäre es da eine Idee wie: levelt gleich

 

Viele Grüße

 

Patrick Fischer

 

=========================

Uhlandstraße 4a

97753 Karlstadt

 

Von: Daniel Siekiera <notifications@github.com> 
Gesendet: Freitag, 13. November 2020 07:56
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: Tsching-Foe <patrick@fischer2011.de>; Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Eigenanteilsrechner (#1638)

 

Hey,

das mit dem P5(0) macht Sinn, aber irgend welche Zeichen solltest Du dir selber reinschreiben. Wir können das leider nicht für einzelne individualisieren.

Weiterhin würde ich dir empfehlen mit "Auto" zu spielen und nicht bewusst unsichere Plätze zu posten. Das mag keiner 😉

**Comment by andrgin** [comment]
Das mit den 0FP ist ein etwas komplizierteres Thema.

Einige Spieler vergeben die Plätze gar nicht besonders wenn es sich um die ganz kleinen Level handelt, wo es nicht mal BP gibt.

In den meisten Fällen werden die Plätze aber um 1 FP an kleine Spieler ohne 80er Arche abgegeben, die BP suchen.

Eigentlich sollten vom EARechner solche Plätze um 1 FP vorgeschlagen werden. Das funktioniert allerdings wieder nur dann wenn nicht 2 Plätze ohne FP vorhanden sind.

**Comment by Tsching-Foe** [comment]
Meist gibt es dafür aber eigene Gruppen und diese Plätze „dürfen“ nicht in die 1.9.
Wie wäre es denn mit einem Button P1-4?

**Comment by andrgin** [comment]
Das wird überall anders gehandhabt
Was den 1-4 Button angeht: Das ist ja wieder LG abhängig. Bei manchen fehlen mehr Plätze.

**Comment by dsiekiera** [comment]
Das ist vom Code her nicht so einfach zu händeln. Dann müssten sich ja rückwirkend die komplette Berechnung bezüglich EA ändern.

Ich hab das jetzt mal so gelöst. Was die Spieler dann mit dieser Info machen ist ihnen überlassen.

"Alle" filtert die leeren weg
![Bildschirmfoto 2020-11-15 um 16-07-05](https://user-images.githubusercontent.com/834814/99188537-bf9acd80-275c-11eb-8065-28562f39b063.png)

"Alle + leere" gibt leere Plätze mit aus
![Bildschirmfoto 2020-11-15 um 16-07-21](https://user-images.githubusercontent.com/834814/99188572-e0632300-275c-11eb-9728-3f24dd71b457.png)

Außerdem hab ich eine Formel zum zentrieren des Overlays integriert.

**Comment by Tsching-Foe** [comment]
Mega!!

Wie machen das eigentlich manche Spieler, dass sie ihre Gildenummer mit angeben? Manuell ist ja blöd, da die sich ändern kann.

**Comment by dsiekiera** [comment]
Wozu sollte man in dem String die Gilden Nummer angeben wollen? Das ja noch individueller. 
Ich kenne ja nicht mal meine. Die schreiben das selber rein.

**Comment by Tsching-Foe** [comment]
Gut, dann bin ich beruhigt. Fand das auch Quatsch. Es sei denn, es postet jemand anderes für Dich und der Avatar ist dadurch nicht da. Wo bist Du eigentlich aktiv?

**Comment by andrgin** [comment]
Wenn jemand anderer für dich postet dann gibt er deinen Spielernamen an bzw. schlägt das der EARechner schon automatisch vor.
Allerdings muss man dafür den EA Rechner in den Einstellungen zuerst einmal für andere Spieler aktivieren.
