### ISSUE TITLE
Statistiken: Bug in Güterauflistung

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#1641]
Hi,

mir scheint, ich bin da gerade über einen Bug gestolpert. Auf den Tabs "Deine Güter - stündlich" und "Deine Güter - täglich" werden nur die "Kein Zeitalter" Güter (Münzen, Vorräte, Tavernensilber und Medaillen) angezeigt, wenn man auf "Alles" geht:

![Screenshot 2020-11-20 175436](https://user-images.githubusercontent.com/17932878/99827114-88139300-2b59-11eb-9465-144dee76a369.png)

Zum Vergleich, wenn man "kein Zeitalter" rausnimmt:

![Screenshot 2020-11-20 175557](https://user-images.githubusercontent.com/17932878/99827220-a9747f00-2b59-11eb-905d-430de25ac4fa.png)

In den Tabs der Gildenkasse sieht es korrekt aus:

![Screenshot 2020-11-20 175811](https://user-images.githubusercontent.com/17932878/99827486-f9534600-2b59-11eb-93fd-526143f73f52.png)

**Comment by andrgin** [comment]
Das ist eher ein Skalierungsproblem im Diagramm. Immer wenn Münzen oder Vorräte angezeigt werden und die im Bereich von einer halben Mrd sind sieht man von den Gütern (üblicherweise im 1000er Bereich) nichts mehr.

Gildenkassenist nicht betroffen weil die hat keine Münzen und Vorräte.

**Comment by frank42hh** [comment]
Hmpf. Überredet. Ich wollte gerade widerlegen, indem ich meine Erkenntnis mit Hilfe des Zooms belege, aber:

![Screenshot 2020-11-20 225503](https://user-images.githubusercontent.com/17932878/99853540-72b35e80-2b83-11eb-8435-ec0244205d0e.png)

Vielleicht wäre es eine Idee, wenn man optional eine checkbox für "logarithmische Skala" hätte?
