### ISSUE TITLE
Anzeige für Aktuell einsammelbare FP

### ISSUE THREAD

**Issue by Lore05** [dsiekiera/foe-helfer-extension#1647]
auf den Weg zur 80er Arche versuche ich den Verlust / die Differenz zur Mäzenbelohnung durch  meine FP-Ernte auszugleichen.
Dabei wäre es sinnvoll ich könnte irgendwo sehen, wie viel FP aktuell geerntet werden können, wenn meine Leiste oben schon mit 100+ FP voll ist. Ich kann das zwar in der Produktionsübersicht als Einzelsummen bei den Gebäuden sehen, aber eine direkte Anzeige der Summe wäre echt geil XD

Wenn ich dann im Kostenrechner sehe, dass ich 175 FP Verlust mache, ich aber 105 FP in der Leiste habe und sehe, dass ich noch 150 FP ernten kann wäre ich glücklich.

Dass gleiche ist evtl auch relvant, wenn man eine 80er Arche hat und ein Platz noch nicht abgesichert ist und ich dies auch durch meine Ernte kompensieren möchte um den Platz gleich zu snippen...

Herzlichen Dank für eure Arbeit!

**Comment by andrgin** [comment]
Ist aktuell in Entwicklung. Der aktuelle Plan ist, dass wir die Summe der fertigen Produktionen pro Resource im jeweiligen Tab anzeigen und eine Auswahloption für alle fertigen Gebäude im letzten Tab.
