### ISSUE TITLE
Error in Alkatraz info window (russian text)

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1648]
![2011291306](https://user-images.githubusercontent.com/35531243/100540156-33040b00-3244-11eb-8f52-25fbe1b2410c.png)

I don't know is this error present in english version, but in russian version times stand on wrong places.
Perhaps it'll be clearer from screenshot.

**Comment by outoftheline** [comment]
The translations are managed by this tool http://i18n.foe-helper.com/projects/foe-helper/extension/
Feel free to sign up and correct the error :) 

Thank you!

**Comment by belikoviv** [comment]
> Feel free to sign up and correct the error

Done!

Thanks for link.
I'll try to help in translation.

**Comment by outoftheline** [comment]
Okay, the error will be fixed with the next update, then! 
Thanks again.
