### ISSUE TITLE
Beta - FoE Icons verschwunden

### ISSUE THREAD

**Issue by DaEgo** [dsiekiera/foe-helfer-extension#1649]
Auf dem Beta zz1.forgeofempires.com sind die Icons des FoE Helfers verschwunden,
auf den anderen Welten sind sie alle noch da.

![FoE Fehler](https://user-images.githubusercontent.com/1351055/101154610-3b828a00-3626-11eb-924c-7563b5059c6a.png)

Danke

**Comment by outoftheline** [comment]
Danke für die Info, schauen wir uns an!

**Comment by andrgin** [comment]
Dies tritt am Beta Server auf, wenn keine Ereignisse existieren und auch keine innerhalb der nächsten 24h auftauchen werden (was passieren kann, wenn man sich lange Zeit nicht einlogged).
Wird mit dem nächsten Update gefixed.

**Comment by DaEgo** [comment]
Ich war vorher ca. 8 Std. nicht online, in der Stadt liegen genug Ereignisse herum ?!

**Comment by kleopatra** [comment]
> 
> 
> Dies tritt am Beta Server auf, wenn keine Ereignisse existieren und auch keine innerhalb der nächsten 24h auftauchen werden (was passieren kann, wenn man sich lange Zeit nicht einlogged).
> Wird mit dem nächsten Update gefixed.

deckt sich nicht mit meinen Beobachtungen - es waren genügend (mind. 3 für die aktuelle Event-Quest) vorhanden und ich bin sicher, daß immer noch welche da sind (und sehr wahrscheinlich auch noch auftauchen ..). Gibt wohl noch eine Bug-Path :)

**Comment by andrgin** [comment]
Habe jetzt etwas weiter analysiert:
.) Inno tracked nun vor dem eigentlichen Start des Spiels die verwendete Auflösung und Zoomfaktor (vermutlich wegen dem neuen Menü).
.) Dieses zusätzliche Paket (das vor dem StartUp geschieht) führt dazu, dass dass das Menü zu früh aufgebaut wird (noch bevor das StartUp Paket verarbeitet wurde).
.) Dies führt zu einem Crash im HiddenRewards Modul (Ereignisse) und zwar jedes Mal unabhängig von den Ereignissen. Diesen Crash habe ich im beta Branch abgefangen.
.) Es könnten noch andere Nebeneffekte auftreten. Dies muss noch getestet werden.

**Comment by OttoVanOyen** [comment]
What is the expected time of the release of the next update?

**Comment by dsiekiera** [comment]
Late afternoon today. UTC
