### ISSUE TITLE
Fenster verschoben und nun steckt es fest

### ISSUE THREAD

**Issue by elamatrix** [dsiekiera/foe-helfer-extension#165]
Hallo,
ich habe vor einer Weile das Info-Fenster für die Siedlung zu weit verschoben. Damit ist die Kopfzeile außerhalb des greifbaren Bildschirms gerutscht. Mit dem jetzigen Update ist zwar das Problem behoben (man kann nicht mehr so weit verschieben) - jedoch speichert das Addon die Box-Position und ich bekomme das Fenster einfach nicht mehr weg und auch nicht geschlossen.
Was kann ich tun um die Boxposition zu resetten?
LG
ela

**Comment by andrgin** [comment]
In den Einstellungen gibt es ganz unten einen Button zum Löschen der Box Koordinaten.

**Comment by elamatrix** [comment]
oha cool, das habe ich wohl übersehen. Danke! Hat Geklappt :-)
