### ISSUE TITLE
Werte der Buttons im Kostenrechner selbst einstellen

### ISSUE THREAD

**Issue by ThomasGigerl** [dsiekiera/foe-helfer-extension#1650]
Hallo Foe-HelperTeam
wäre es machbar beim Kostenrechner die fixen Werte auf den Buttons selbst einzustellen?
80,85 nutze ich nie, ich würde da eher 90, 92, 94 und den eigenen Wert benötigen 
![image](https://user-images.githubusercontent.com/54547999/101175239-3123b880-3645-11eb-965f-f0cad4e8a7c5.png)

Danke & LG

**Comment by dsiekiera** [comment]
Das ist ja auch schon das Ticket ;-)

**Comment by outoftheline** [comment]
abgehakt!
