### ISSUE TITLE
Blaue Galaxie Helfer gewichtet nicht korrekt?

### ISSUE THREAD

**Issue by mordillo666** [dsiekiera/foe-helfer-extension#1653]
Erstmal vielen Dank für dieses hilfreiche Tool. :-)

Ich habe heute das erste mal damit geerntet, und es hat mir meinen Immergrün-Express als letzte Option angezeigt. Dieser liefert bei mir 10FP und 10Güter.
Meine Mikawa Brücke liefert allerdings 10FP und 25 Güter. 

Oder habt ihr den Münzboost des Express höher gewertet als Güter?

Gruß Mordillo666

**Comment by andrgin** [comment]
Derzeit werden nur FP gezählt

**Comment by andrgin** [comment]
Aber dem nächsten Update werden auch die Güter angezeigt. Die Gewichtung kann je nach Bedarf geändert werden (Standardwert ist 0.2FP pro Gut (bzw. 5 Güter pro FP)
