### ISSUE TITLE
Blue Galaxy Helper - Diamonds collections

### ISSUE THREAD

**Issue by codegist** [dsiekiera/foe-helfer-extension#1656]
The Blue Galaxy helper seems to order only highest FP producing buildings first.
Double collection also works with diamonds, would be great if it takes that into account and put the diamonds producing building first when they produce diamonds (wishing wells, crow's nest and such) followed by highest FP producing buildings.

**Comment by codegist** [comment]
Out of curiosity, any reason for the not implement? For fairness? :) The city production overview already shows which building will be producing diamonds, so somehow this is already displayed by the helper.

**Comment by andrgin** [comment]
For the production overview: We already had diamonds implemented there when we received the demands from Inno in June. It seems they missed that or did not think about players using it in combination with the galaxy, but as long as we do not receive a request to change it it will stay the way it is.
But we will not add new features around reading of the current diamond production.
