### ISSUE TITLE
FoE Helper new sidebar advice

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1657]
Hi.

As all already know Inno change functionality of own right side sidebar in nearest update - it will have float length, and will overlap with Helper sidebar.

I think that new Helper sidebar may be placed at bottom of screen, in right side, and must have button to hide/show itself (as button on original social panel) to let players find sea incidents at bottom of screen.

Helper sidebar also may have customizable count of rows and columns (to players may adjust it heigth with height of social panel).

**Comment by dsiekiera** [comment]
That's pretty much what we had in mind. It is already in the works.
