### ISSUE TITLE
Problem with new function Motivate/Polish helper

### ISSUE THREAD

**Issue by ecthelioni** [dsiekiera/foe-helfer-extension#1658]
Hello
I have problem with this new function, I dont have any record in the window Motivate/Polish helper. I try disable/enable new function in the settings, I try disable/anable addon and it is same.

https://ctrlv.cz/iKQF

I using Google chrome 87.0.4280.88

I see this error in the addon
https://ctrlv.cz/tuoJ

**Comment by DanChaltiel** [comment]
I have the same problem.
Chrome console says that:
```
Uncaught (in promise) TypeError: Cannot read property 'getTime' of undefined
    at Object.CalcMoppelHelperBody (eventhandler.js?v=2.5.3.0:288)
```

**Comment by andrgin** [comment]
These are language specific problems depending on the language of the game (not the extension). Reason is that we need to have a date parsing function for each language and it seems some languages or not working correctly yet.

Languages we already know that are working:
.) German
.) English

Languages that we know that are not working:
.) French (is already fixed in beta branch)
.) Czech (still need to investigate the reason)

Please give feedback if your language is working or not.

**Comment by andrgin** [comment]
Side note: The date parsing problem occurs when scrolling through the event list and adding the events to the database. In this case no date is written.
If you try to open the "moppel" helper the missing date on one event leads to the exception shown above.

**Comment by ecthelioni** [comment]
My language is Czech and dont working.
Do you need help with this problem?

**Comment by DanChaltiel** [comment]
French here. That was solved with the last update, thanks a lot!

**Comment by ecthelioni** [comment]
Hello
czech language is better in version 2.5.3.1, but not 100% workly.

1. Motivation update windows display this error:
https://ctrlv.cz/85jo

2. Friends correctly working (maybe) but Guild members and nighbors not working
https://ctrlv.cz/yDCC

**Comment by foxycode** [comment]
@ecthelioni You must click on Guild members and neighbors first so extension can load their list.

I believe that `Error parsing date` in Czech language is because of `dnes v` (today on). Second one `včera v` (yesterday on) seems to be working ok when I list backwards.

**Comment by andrgin** [comment]
Last time we checked Inno included a NBSP character (https://en.wikipedia.org/wiki/Non-breaking_space) instead of a blank only in "dnes" on Czech servers, so we included it our format string.

It could be possible that this has already been replaced with a normal space character.

I will try that out. Please give feedback after the next update if it has worked.

**Comment by foxycode** [comment]
@andrgin Is there a way how to check this? Can I check using developer tools in browser?

**Comment by ecthelioni** [comment]
Hello
I have intalled version 2.5.4.0 and error is same.

![image](https://user-images.githubusercontent.com/60727513/102023977-5922c280-3d8f-11eb-9fe0-e201e6fcbd02.png)

**Comment by andrgin** [comment]
If you scroll through the whole event history and do not get errir messages it has worked.

**Comment by ecthelioni** [comment]
It is interesting, I opened history events at 8pm and massages from FoE helper was be "updates corectly" (green), but i open histor events at 9pm and I see same error as last time (The Date value "dnes v ??:?? hod" could not be parsed)

**Comment by andrgin** [comment]
Could you please:
.) Open the event list and scroll through the events until the error message appears
.) Open developer tools with F12 and go to Console tab
.) Enter the following command and press Enter: encodeURI(EventHandler.AllInvalidDates[0]);
.) Please post a screenshot from the result

**Comment by ecthelioni** [comment]
This is result:

![image](https://user-images.githubusercontent.com/60727513/102256628-e5f28b00-3f0b-11eb-9133-1d98ea1720bc.png)

**Comment by foxycode** [comment]
Aaaand we have the winner :) Maybe replace all these characters before parsing would be solution in case Inno will change it again?

**Comment by andrgin** [comment]
I think I have a fix. All NBSP in the datestring will be replaced with blanks.

The update should roll out in the next few days.
