### ISSUE TITLE
LG vormerken/erinnern Funktion

### ISSUE THREAD

**Issue by sdn-br** [dsiekiera/foe-helfer-extension#166]
Es wäre ideal, wenn man sich LGs vormerken könnte, in dem man das LG auf eine Art Favoriten-Liste packen könnte. Ich arbeite regelmäßig meine NB durch und warte teilweise aber noch mit der Einzahlung. Eine Liste ähnlich der "Mögliche Einzahlungen" Funktion würde helfen, damit man da gezielter vorgehen kann und gezielt die Spieler suchen kann. Folgende Informationen wären Interessant:
- Liste (Gilde, FL, NB) (falls er in Mehreren ist, immer die erste mögliche der genannten anzeigen)
- Letzter bekannter Rang in der Liste
- Spielername
- LG Name
- Letzter Stand im LG

Ideal wäre, wenn man ein LG im Kostenrechner und oder den Möglichen Einzahlungen markieren in die Liste hinzufügen kann. Ggfs. dort auch ein Sternsymbol, damit man das LG wieder entfernen kann.

**Comment by andrgin** [comment]
Da die möglichen Einzahlungen entfernt wurden wird auch dieser Wunsch nicht mehr umgesetzt werden: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
