### ISSUE TITLE
Die Sidebar ist verrutscht

### ISSUE THREAD

**Issue by Hagenthal** [dsiekiera/foe-helfer-extension#1664]
Hi, seit dem Update heute ist die Sidebar des FoE-Helfers nach unten gerutscht. Wie bekomme ich die wieder an die (rechte) Seite? 
Ich benutze den Chrome-Browser.
Danke für Eure Hilfe :-)

**Comment by snagglewest** [comment]
+1
I'm using a small laptop and vertical space is in short supply.  The right hand side is much more user friendly!

**Comment by snagglewest** [comment]
To top it off it blocks the item descriptions...
![Screenshot at 2020-12-08 19-46-24](https://user-images.githubusercontent.com/10524656/101559587-6d318300-398f-11eb-9620-10bcbdad469c.png)

**Comment by andrgin** [comment]
The sidebar was moved to the bottom on purpose because tomorrow Inno has increased the size of their sidebar (dynamically extending based on the items) so we had to find another spot.

For the overlapping tooltips:  Which resolution do you have and what is the zoom factor of your browser?

**Comment by ThoWoMa** [comment]
![image](https://user-images.githubusercontent.com/17168489/101585490-215afa00-39e0-11eb-959c-6c35b8c8ea9d.png)

**Comment by Hagenthal** [comment]
On my gamer laptop I am using Chrome for FoE with a zoom factor of 120%

**Comment by ThoWoMa** [comment]
And i am using 75% zoom with MS Edge on a 4k 27" Monitor.

**Comment by snagglewest** [comment]
I am using Chrome f with a zoom factor of 0%

**Comment by snagglewest** [comment]
If Inno is going to adjust their bar, then pin the Foe helper bar to the bottom right corner and limit the number of buttons to 4-5.

**Comment by outoftheline** [comment]
Sifferent styles and positioning options for the menu will be implemented in the near future.

**Comment by Hagenthal** [comment]
Sounds good, outoftheline :-) Thankx ^^

**Comment by Th3C0D3R** [comment]
![grafik](https://user-images.githubusercontent.com/7798500/101772329-851e1980-3aeb-11eb-9a26-168d524b30d9.png)
near future is now. Comming next update

**Comment by Morgage** [comment]
Buenas, se puede hacer como en la barra de tareas de windows, que al pasar el mouse arriba se extienda, y al sacarlo se contraiga y quede una pequeña caja de un solo item a la derecha abajo?
