### ISSUE TITLE
Option to see when friends visited the tavern (Idea)

### ISSUE THREAD

**Issue by quark-z** [dsiekiera/foe-helfer-extension#1667]
I love the new option to see who has motivated  / polished buildings  in my city. 

Keeping track of friends who are active / inactive is tedious so it would be great to see a similar option (if possible) to track which friends are visiting my tavern. Thanks in advance for considering this idea.

BTW thanks for a superb extension - it took me nearly 3 years to discover it but it has transformed the way I play FoE and made the game more fun. Well done.

**Comment by outoftheline** [comment]
![image](https://user-images.githubusercontent.com/7482863/101635293-0dd48100-3a2a-11eb-9606-62b15c81eb14.png)

Already done :)

**Comment by quark-z** [comment]
I don't know how I missed that - (_Do I feel the fool LOL_. )Thanks
