### ISSUE TITLE
Copy settings to all worlds

### ISSUE THREAD

**Issue by JhonnyBn** [dsiekiera/foe-helfer-extension#1669]
Without exporting once and importing to each world, just click a button and replicate settings for all worlds, would this be possible?

![image](https://user-images.githubusercontent.com/29382833/101704723-1a75cb00-3a64-11eb-991e-a2022a6f7a57.png)

**Comment by dsiekiera** [comment]
Sorry, but this is not possible. A page have no access to other pages. This is a security police by browsers.

U only can export ur settings and import it to each other world.

**Comment by andrgin** [comment]
Different worlds have completely different localStorage because the URL ist different so unfortunately there is no way we could access data of other worlds.
Also I would not suggest importing settings from a different world. This could have some unwanted side effects.

**Comment by JhonnyBn** [comment]
> Also I would not suggest importing settings from a different world. This could have some unwanted side effects.

I thought about that for the statistics tool...


> Sorry, but this is not possible. A page have no access to other pages. This is a security police by browsers.
> 
> U only can export ur settings and import it to each other world.

Sad, but understandable. Thanks for the very quick response!
