### ISSUE TITLE
Spielername und Welt nicht auswählbar

### ISSUE THREAD

**Issue by mstc71** [dsiekiera/foe-helfer-extension#167]
Hallo,

ich kann im Profil auf der Homepage meinen Spielernamen und die Welt nicht auswählen. Bei der Gilden-ID und Player-ID wird auch nichts angezeigt.

Ingame-Name: mstc
Welt: Greifental
Player-ID: 378251

Vielleicht könnt Ihr mal schauen woran das liegt.

Vielen Dank.

**Comment by dsiekiera** [comment]
Hey @mstc71 ,
Ich hab die Datenbank geprüft.
Die Extension hat dich in der Datenbank angelegt. Jedoch musst Du über den [registrieren Link](https://foe-rechner.de/register/player) einen Zugang anlegen. um auf dein Profil zugreifen zu können.

**Comment by mstc71** [comment]
Hallo,

ich bin ja schon auf der Homepage registriert. Sonst könnte ich ja nicht mein Profil anschauen.
Trotzdem habe ich es noch einmal mit der Registrierung versucht und dann kommt die Fehlermeldung, dass der Ingame-Name "mstc" schon registriert ist.

Mein Name ist "Michael Sticksel" und meine E-Mail-Adresse "michael.sticksel@gmx.de"

**Comment by dsiekiera** [comment]
Zur Spieler-ID 378251 hab ich kein Konto gefunden. Aber über die Mail-Adresse. Habs gefixt.

**Comment by mstc71** [comment]
Danke
