### ISSUE TITLE
UPD bar covers information from FoE

### ISSUE THREAD

**Issue by MarcAroma** [dsiekiera/foe-helfer-extension#1684]
Your UPD bar covers FoE content and buttons, and is rather annoying, sorry. 

![Screen Shot 2020-12-11](https://user-images.githubusercontent.com/3120697/101902525-16a48e80-3bb3-11eb-8db7-180c754d0aa2.jpg)

Otherwise I love our tool. 

Oh, and also, I preferred the location of your toolbar on the right hand side, not at the bottom, and if you keep it at the bottom, can you please shorten it, since it is far to prominent for a subsidiary tool. Thank you

**Comment by outoftheline** [comment]
Danke, wir werden die Infos per Einstellungen deaktivierbar machen

**Comment by andrgin** [comment]
In which resolution do you play the game? Seems more a translation issue to me with the text being too wide.

We will make it possible to turn the notification off, but you will need them for the Moppel helper so you know which events are already saved and you can stop scrolling.

If you do not use the Moppel helper I suggest turning it off completely. Then the messages will be gone as well.

**Comment by andrgin** [comment]
For the menu bar:
Inno has changed their sidebar so it would overlap with the old menu position if there are more icons active. That is thee reason why we moved it to the bottom.

The next update will contain more customization options.

**Comment by marcSchroder** [comment]
I use an MacBookPro 13,3-inch (2560 x 1600) - Yes, I tried to turn it off, but can't find that tick box :) cause I am not using the Mopple Helper - since I use the Town Hall for that :)
Thank you for our quick response!

**Comment by andrgin** [comment]
1.) I made a test and the only way I could reproduce was with 1024x768 resolution, which we do not support (minimum is 1280x768 at 100% zoom factor because it will leave no room for the menu bar).
My guess is that your MacBook uses some form up zooming/upscaling ignoring aspect ratio. Maybe you can reduce zoom level?

2.) The Moppel helper can be disabled in the menu under Boxes => Motivation activity. It is the last item, so you may need to scroll down the list.

**Comment by MarcAroma** [comment]
Thank you for looking into this.
1.) It's a pretty standard monitor setting at this 2 ear old MacBook Pro.
2.) es, thank you, I found those settings now, the are a bit hidden :)

I don't know why you need to show the user that your tool gets the information in the background, seems to me more a debugging thing, but completely not interesting for any normal user.

**Comment by andrgin** [comment]
No this message is very important. If it tells you that there are no more events for 2-3 pages in a row you know you have collected all events and dont need to scroll through the rest of the pages. Otherwise you would need to look at the date and take notes when you have collected which data.

**Comment by MarcAroma** [comment]
It comes up ever time I go to the next page, which I need in order to press the help buttons for each player who helped me...
