### ISSUE TITLE
Alkatraz production overview give not correct info

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1686]
Hi.

1. After level-up of Alkatraz it gives 1 more unit.
Helper shows previous count of avaiting units.

2. When I buld new military building Alkatraz give units from this building right after I place it, not waiting when building will be finished.
Helper not shows units for new building.

**Comment by Th3C0D3R** [comment]
the helper only shows the last production saved, not the upcoming production! 
as on my laptop it shows units from the The Contemporary Era but I am in Future already since weeks
w

**Comment by belikoviv** [comment]
What means "saved"?

How I can "save" Alkatraz production?

I want to fill table with all gatherings from my Alkatraz for some long period - is it possible?
If you say that your helper shows very stale info - I think that my wish is impossible...

**Comment by andrgin** [comment]
We cannot read which units the Alcatraz will produce like in the production overview.

What we do in the army overview is wait until you collect your Alcatraz and save those units so the units shown in the army overview are probably from yesterday. If you normally collect your Alcatraz on your phone after you wake up or on another PC then those values might be a lot older.

**Comment by belikoviv** [comment]
> the units shown in the army overview are probably from yesterday

To be more clear:
the unitsh shown are from last Alcatraz gather under helper monitor.
If Alcatraz gather made not under Helper control for any reasons - we got stale results in army overview.

OK, thanks a lot, I understand algorithm.
