### ISSUE TITLE
Legendäre Gebäude Liste leer

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#169]
Ich hab keine Ahnung, ob Kommentare an geschlossenen Tickets gesehen werden, daher sicherheitshalber nochmal als neue issue...

Das Problem aus #51 scheint noch zu existieren, zumindest bei mir... egal wie oft ich durch die Gegend clicke, die List bleibt leer:
![Screenshot_2019-11-19_17-03-46](https://user-images.githubusercontent.com/17932878/69165242-8f8d0000-0af1-11ea-9ed6-5ad18e78be61.png)

**Comment by andrgin** [comment]
Ist schon bekannt und in Bearbeitung.

**Comment by Horst-Krawuttke** [comment]
hmmm, nur mal so vorsichtig als Frage:
Gibt es schon Neuigkeiten zum Bearbeitungsstatus?

**Comment by andrgin** [comment]
Ist mittlerweile gefixed.
