### ISSUE TITLE
FP Collector does not count all procs of the Blue Galaxy

### ISSUE THREAD

**Issue by hotochan123** [dsiekiera/foe-helfer-extension#1690]
My BG is at lvl67 (so max. 14 procs at 64% each) and I noticed that the FP Collector only registers only up to 3 procs max at each collection cycle. This is what the past 5 days looked like:
![2020-12-13_09-24-56](https://user-images.githubusercontent.com/75928191/102007033-d1ed3480-3d25-11eb-9eca-5dfbb04164b8.png)
![2020-12-13_09-25-09](https://user-images.githubusercontent.com/75928191/102007034-d285cb00-3d25-11eb-9c6a-1b3964be5c40.png)
![2020-12-13_09-25-20](https://user-images.githubusercontent.com/75928191/102007035-d31e6180-3d25-11eb-806c-f19e81cee2de.png)
![2020-12-13_09-25-30](https://user-images.githubusercontent.com/75928191/102007036-d31e6180-3d25-11eb-9391-06bf6eda2ef0.png)
![2020-12-13_09-25-43](https://user-images.githubusercontent.com/75928191/102007037-d31e6180-3d25-11eb-9779-00119c6ae549.png)

On multiple (if not all of these days) occasion I definitely had more than 2-3 procs. Also notice that only Terrace Farms and/or Crow's Nest are being listed (with the exception of one instance) while I gather a variety of different buildings (for instance Shinto Temple, Mikawa Bridge, Airship, Abendoned Asylum).

Chrome build: Version 87.0.4280.88 (64 bit)

**Comment by outoftheline** [comment]
Will be fixed in the next update!
