### ISSUE TITLE
Sichere Plätze ohne Eingenanteil > Eigenanteilsrechner / Kostenrechner (Idee)

### ISSUE THREAD

**Issue by Lore05** [dsiekiera/foe-helfer-extension#1692]
Es gibt ja Stufen bei denen für die ersten Plätze kein Eigenanteil notwendig ist. Viele dieser Plätze kann man ja auch mit weniger als der evtl gewünschten Förderung belegen, was die Nachbarn ja auch gerne tuen und wir bei Ihnen auch.
Eine Möglichkeit da gegen zu steuern ist, einen Förderer für P1 erstmal nur den notwendigen Anteil einzahlen zu lassen und den Rest erst aufzustocken, wenn auch P2 belegt ist... 

1) Wäre es möglich dies in den Eigenanteilsrechner einzubauen? 
Also, dass der Eigenanteilsrechner als Wert zum Kopieren für P1 zum Beispiel "Arche P1(1403/1507)" ausgibt?

2)Ebenso für den Kostenrechner, dass der bei solchen Plätzen beides Anzeigt? so wie er es tut, wenn man den ersten Teil eingezahlt hat, also "notwendige Einzahlung/Fördereinzahlung" 

Danke für eure super Arbeit

**Comment by andrgin** [comment]
1.) Im EA Rechner gibt es die danger Warnung um zu erkennen, dass P1 bzw. P2 gefährdet sind. Die Sache mit dem nur einen Teil einzahlen und später aufstocken wird fürchte ich etwas zu kompliziert zu rechnen, da es eine Menge Sonderfälle gibt und nicht klar ist wann aufgestockt wird (ein Teil nach P2, Rest nach P3 außer P3 hatte eine kräftige Überzahlung, dann eventuell auch ein Teil nach P4/5). Das wird zu kompliziert.

2.) Im Kostenrechner steht im Tooltip des Gewinns ab wo der Platz safe ist.

3.) Die Methode mit dem nur einen Teil einzahlen löstndas Problem nicht, sondern halbiert nur den Schaden. Meine Empfehlung ist im kritischen Bereich (zumindest dort wo es wirklich weh tut) generell nur Powerlevel wenn man nicht genug Freunde hat, die im 1.9er Thread schnell genug einzahlen.

**Comment by Lore05** [comment]
ok danke für die Rückmeldung
