### ISSUE TITLE
FP Collector: Typo

### ISSUE THREAD

**Issue by icw135** [dsiekiera/foe-helfer-extension#1693]
FP Collector hat einen Typo:
statt "Belohnung" wird "Belohung" ausgegeben.

**Comment by dsiekiera** [comment]
@icw135 an welcher Stelle?

Oder ändere einfach mal selber: [http://i18n.foe-helper.com/translate/foe-helper/extension/de/](http://i18n.foe-helper.com/translate/foe-helper/extension/de/)

**Comment by andrgin** [comment]
Das hab ich vor ein paar Tagen ausgebessert und sollte gerade mit dem neuen Update ausgerollt werden.
