### ISSUE TITLE
Registrierung

### ISSUE THREAD

**Issue by Kekosht** [dsiekiera/foe-helfer-extension#17]
Hallo Zusammen
Ich bin begeistert von dem Tool. Die ganzen Rechner kann ich auch gebrauchen.
Jedoch das Helfertool und die GEX anzeige nicht.... muss man sich registrieren? 
Falls ja hab ich das Problem, dass die Registrierung nicht funktioniert.
Ich hange stundenlang im Ladebildschirm.

Freue mich über eine Antwort 
Greets Keko

**Comment by dsiekiera** [comment]
Verarbeitungfehler gefunden und behoben
