### ISSUE TITLE
Vorschlag: Last update timestamp auf LG Investitionen

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#170]
Moin,

Ich finde die Liste auf
https://foe-rechner.de/invest/list
ziemlich praktisch, hätte allerdings einen Vorschlag, wie man sie noch hilfreicher gestalten kann.
Ich habe manchmal einen ganzen Haufen an LGs auf dieser Liste, und manchmal frage ich mich, warum die nicht kleiner wird. Bei genauer Betrachtung (bzw. händischen notierens) merke ich dann, dass da welche dabei sind, die seit Wochen brach liegen.
Ich fände es praktisch, wenn jedes Mal, wenn die Liste vom Plugin übertragen wird, ein timestamp mitgeführt wird, der sich aber nur dann aktualisiert, wenn sich ein Eintrag verändert hat. Auf diese Weise könnte man sehen, wann sich an den Investitionen eines LG zum letzten Mal was verändert hat und wo man den Owner vielleicht mal fragen sollte, wann er denn zu leveln gedenkt :)
Nicht selten werden durch sowas haufenweise FP blockiert, die anderweitig genutzt werden könnten...

**Comment by andrgin** [comment]
Ist mittlerweile implementiert.
