### ISSUE TITLE
Cant find FoE helper extension in browser

### ISSUE THREAD

**Issue by fareehayasmeen** [dsiekiera/foe-helfer-extension#1701]
Can't see FOE Helper. add-on is on but still cant find the tab on the game. have tried several reinstalls but the issue is not resolved. My game runs as it normally does without FoE helper Extension. It has been six months I am trying to get it back please guide me

**Comment by dsiekiera** [comment]
Which browser and OS ur using?

**Comment by fareehayasmeen** [comment]
> 
> 
> Which browser and OS ur using?

I have tried on both Firefox and Chrome but mainly using Firefox on Windows 10

**Comment by 057Sophie** [comment]
I had the same issue with Version 2.5.4.0 on Firefox. I went back to Version 2.5.3.2 and it works well.

**Comment by 057Sophie** [comment]
and of course I locked the updates

**Comment by andrgin** [comment]
Can you please use the bug report template as this seems to be a system specific problem:
https://github.com/dsiekiera/foe-helfer-extension/issues/620

Also please tell us the resolution and zoom factor younare playing the game in.

**Comment by 057Sophie** [comment]
Bitte bei bug reports folgende Informationen angeben / Please include following information in your bug reports:

Betriebssystem / Operating System => WINDOWS10

Verwendeter Browser inkl. Versionsnummer / Used Browser including version => FIREFOX QUANTUM 60.0.2 (64 bits)

Forge of Empires Server => FR (Tuulech, Fel Dranghyr, Mount Killmore)

Extension Version und Sprache der Extension. Falls ihr Betatester seid unbedingt dazuschreiben!!! / Extension version and language of the extension. If you are beta tester include that as well!!! => Version2.5.4.0 öffnet sich gar nicht. Version 2.5.3.2 ok auf deutsch und französisch.

Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole" wechseln) / Errors in the console (press F12 and switch to console tab)
Sind andere Extensions installiert / Are other extensions installed? => NEIN

Zoom factor: the smaller one available in FOE (no ZOOM changes through FF)
Resolution:1920*976
FOE: v1.193
1.193.78325b73a71 (09.12.2020 11:18), Sophie7810 (4864829), fr19, fr_FR, WEB 7,1,1,0, Windows 10, Firefox/60.0, 1920x976, OpenGL Vendor=Mozilla Version=WebGL 2.0 Renderer=Mozilla GLSL=WebGL GLSL ES 3.00 (512 MB VRAM)

**Comment by Th3C0D3R** [comment]
> Bitte bei bug reports folgende Informationen angeben / Please include following information in your bug reports:
> 
> Betriebssystem / Operating System => WINDOWS10
> 
> Verwendeter Browser inkl. Versionsnummer / Used Browser including version => FIREFOX QUANTUM 60.0.2 (64 bits)
> 
> Forge of Empires Server => FR (Tuulech, Fel Dranghyr, Mount Killmore)
> 
> Extension Version und Sprache der Extension. Falls ihr Betatester seid unbedingt dazuschreiben!!! / Extension version and language of the extension. If you are beta tester include that as well!!! => Version2.5.4.0 öffnet sich gar nicht. Version 2.5.3.2 ok auf deutsch und französisch.
> 
> Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole" wechseln) / Errors in the console (press F12 and switch to console tab)
> Sind andere Extensions installiert / Are other extensions installed? => NEIN
> 
> Zoom factor: the smaller one available in FOE (no ZOOM changes through FF)
> Resolution:1920*976
> FOE: v1.193
> 1.193.78325b73a71 (09.12.2020 11:18), Sophie7810 (4864829), fr19, fr_FR, WEB 7,1,1,0, Windows 10, Firefox/60.0, 1920x976, OpenGL Vendor=Mozilla Version=WebGL 2.0 Renderer=Mozilla GLSL=WebGL GLSL ES 3.00 (512 MB VRAM)

Please update Firefox to the latest version (72)

**Comment by Th3C0D3R** [comment]
> Can't see FOE Helper. add-on is on but still cant find the tab on the game. have tried several reinstalls but the issue is not resolved. My game runs as it normally does without FoE helper Extension. It has been six months I am trying to get it back please guide me

Please update the browsers to the latest version:
Chrome & Edge (80)
Firefox (72)

**Comment by andrgin** [comment]
Side note:
Current versions are 87 for Chrome and 83 for Firefox.
The listed Chrome80 and Firefox72 are the bare minimum that would work, but I strongly suggest not using outdated browsers. This can be a serious security hazard.

**Comment by 057Sophie** [comment]
Thank you for your support, I'm not able to choose my FF VErsion on this machine. SO I won't stay on your previous version and o FF 60 which is the version defined/ rolled out by my company.

**Comment by dsiekiera** [comment]
With the last update, v2.5.4.1, from yesterday it must be possible to play in older version of FF.
Have u installed it?

**Comment by fareehayasmeen** [comment]
Bitte bei bug reports folgende Informationen angeben / Please include following information in your bug reports:
Betriebssystem / Operating System => WINDOWS10
Verwendeter Browser inkl. Versionsnummer / Used Browser including version => FIREFOX 84.0 (64-bit)
Forge of Empires Server => US27
Extension version: 2.5.4.1 
Language of the extension: English
Are other extensions installed? => No
1.193.fa688003aa2 (15.12.2020 15:25), Ptolemy 1064 the Avenger (21422170), us27, en_US, WEB 7,1,1,0, Windows 10, Firefox/84.0, 1525x858 (Fullscreen), OpenGL Vendor=Mozilla Version=WebGL 2.0 Renderer=Mozilla GLSL=WebGL GLSL ES 3.00 (512 MB VRAM)
![FoE](https://user-images.githubusercontent.com/75737271/102273722-9aa89e80-3f44-11eb-8379-e06d75ed9bd3.png)
