### ISSUE TITLE
foe-helfer-extension is don't work

### ISSUE THREAD

**Issue by mrDXmr** [dsiekiera/foe-helfer-extension#1702]
[DE] (auto translate)
   Nach dem letzten Update auf Version 2.5.4.0 und dem Neustart des Spiels verschwanden alle FoE Helper-Panels.
   Die Neuinstallation von "FoE Helper" in Comodo Dragon aus dem Chrome Webstore funktioniert nicht.
   Die Installation von FoE Helper in Opera über den Chrome Webstore funktioniert nicht.

[UA]
   Після останнього оновлення до в.2.5.4.0 і перезавантаження гри, зникли усі панелі FoE Helper. 
   Повторне встановлення "FoE Helper" у Comodo Dragon з Chrome Webstore не працює. 
   Встановлення "FoE Helper" у Opera з Chrome Webstore не працює.

[EN] (auto translate)
   After the last update to v.2.5.4.0 and restarting the game, all FoE Helper panels disappeared.
   Reinstalling "FoE Helper" in Comodo Dragon from the Chrome Webstore doesn't work.
   Installing FoE Helper in Opera from the Chrome Webstore doesn't work.

**Comment by Th3C0D3R** [comment]
Please update to the latest BrowserVersion

**Comment by dsiekiera** [comment]
Duplicate of #1701
