### ISSUE TITLE
Scrolling is missing in production overwiew

### ISSUE THREAD

**Issue by Donna7807** [dsiekiera/foe-helfer-extension#1709]
Not possible to scroll in the production overview window, so we can'see all the productions. It is missing on all tabs - if you have more building what can be shown, the window will be longer than the maximum size and the scrollbar or scrolling option is missing.

Thank you :)

https://prnt.sc/w3rfjl

**Comment by Th3C0D3R** [comment]
fixed in next update

**Comment by Donna7807** [comment]
Thanks!
