### ISSUE TITLE
Rechner (Gewinn/Safe) + Gildengefechte

### ISSUE THREAD

**Issue by marco-wirth** [dsiekiera/foe-helfer-extension#171]
Hallo,

erstmal einen riesen Dank das du das so entwickelt hast, richtig gut!

Rechner
Aktuell werden die dem eingestellten Prozentsatz entsprechenden FP pro Platz in grün angezeigt. Was ich aber nicht sehe ist, ob der Platz denn schon sicher ist. Könnte man die nicht sicheren Plätze nicht in rot anzeigen?
Wenn ich dann den Betrag X eingezahlt habe, dann erscheine ich blau in der Zeile. Ein Gewinn wird mir aber nicht angezeigt (obwohl ich ihn bekomme). Kann man nicht automatisch im Hintergrund die Prozente auslesen die mir meine Arche bringt und danach den Gewinn anzeigen lassen?

Gildengefechte
Wäre schön wenn du dazu auch irgendwas nützliches bauen könntest. Z.b. die Anzeige der Sektoren nach Restlaufzeit mit Filter auf nur angrenzende zu zeigen. Ein erweitertes Log wäre super wo man sieht wer wo eine Fahne gesetzt hat oder wer einen Sektor letztendlich eingenommen hat.

Gruß
Marco

**Comment by andrgin** [comment]
Hallo Marco

Schön, dass dir unsere Extension gefällt

1.) Deinen Archefaktor kannst du im Kostenrechner eingeben. Die Buttons 85% bzw. 90% sind nur zum schnellen Umschalten für bestimmte Ketten gedacht.

2.) Es werden grundsätzlich nur sichere Plätze vorgeschlagen. Die Berechnung funktioniert so:
a) Es wird berechnet wie viele FP man braucht, um den Platz abzusichern (Einsatz)
b) Danach wird anhand des eingestellten Archefaktors der Ertrag (wieviele FP bekommst du zurück) und aus der Differenz (Ertrag - Einsatz) der Gewinn, wobei mit der Standardeinstellung nur positive Gewinne angezeigt werden (wenn man will kann man das in den Einstellungen umstellen).

3.) Wenn du bereits auf einen Platz eingezahlt hast, dann wird die Zeile blau angezeigt. Es werden in der Spalte "Einsatz" nun 2 Werte angezeigt:
Der erste Wert sind die eingezahlten FP, der 2. Wert ist die FP, die du einzahlen musst, damit der Platz safe ist.
Beispiel: 180/190 bedeutet, dass du noch 10 FP einzahlen musst.

4.) Die Extension liest nur im Hintergrund die Daten mit, die Inno Games an den Browser sendet. Ein aktives Abfragen wäre ein Eingriff in die Spielmechanik und nicht erlaubt. Es können also nur die Daten dargestellt werden, die auch übertragen werden. Die Logdatei würde also nur das erfassen können, was passiert, während man das Gex Fenster offen hat.
Timer von angrenzenden Sektoren wäre beim Öffnen des Gex Fensters theoretisch möglich, jedoch frage ich mich, ob man so das wirklich so viel schneller sieht als wenn man gleich auf die relevanten Provinzen klickt.

**Comment by marco-wirth** [comment]
Danke für die Erklärungen!

Beim Kostenrechner kann ich einen bestimmten Arche-Bonus eintragen oder aber mit den Buttons 80 bzw 90% auswählen. Dies stellt dann aber auch nur die Prozentzahl ein, die ich entsprechend der Ketten z.B. zahlen muss. Soweit ist das klar.
Was ich meine ist folgendes: Ich habe sagen wir mal eine 100er Arche und erhalte somit 92% Bonus. Daran ändert sich ja nichts, die bekomme ich immer und nie mehr oder weniger, sondern immer diese 92%. Stelle ich jetzt sagen wir 85% ein, dann berechnet der Kostenrechner den Gewinn aber auf die 85%, die aber nicht stimmen weil ich ja 92% erhalte. Würde ich die 92% einstellen, dann stimmen die Werte nicht die ich einzuzahlen habe wenn ich in einer 85% Kette bin. Verstehst du was ich meine? Wäre halt schön das ich meinen Gewinn auch richtig sehe wenn ich einen anderen Prozentsatz einstellen muss. Das heißt ja nicht das ich nur eine Arche habe die 85% liefert.

Das mit dem Einsatz habe ich jetzt verstanden, das ist cool das ich sehe was ich minimum einzahlen muss um safe zu sein. Hilft halt bei der Nachbarschaft wenn es nicht um Ketten geht.

Das mit den Gildengefechten war auch nur so eine Idee, falls du dich damit mal auseinander setzt. Aktuell ist das Thema Log halt bei allen in der Diskussion weil man nicht weiß wer etwas macht.

**Comment by andrgin** [comment]
1.) Stimmt mit der Überlegung hast du Recht. Da hatten wir einen kleinen Denkfehler. Ich sehe mir einmal an, ob sich das lösen lässt ohne das halbe Tool umzuschreiben.
