### ISSUE TITLE
FP total box blocks results button on PC Google Chrome

### ISSUE THREAD

**Issue by adwsystems** [dsiekiera/foe-helfer-extension#1715]
FP total is no longer displayed at the very top of the screen, in the header bar. It is now under the 10 point fp bar on the city graphic. When in a battle, if you click auto-battle, a red Results button appears at the top fo the screen. The new location for the fp total blocks clicking the button.

**Comment by andrgin** [comment]
Can you post a screenshot?

**Comment by adwsystems** [comment]
Problem has resolved itself.
