### ISSUE TITLE
Suggestion: FoeHelper as Box collapsed notifications

### ISSUE THREAD

**Issue by valimaties** [dsiekiera/foe-helfer-extension#1717]
Hi.
I use FoeHelper as Box, and is docked at the top of screen, near goods. Each square in menu might have some information, like incidents. Can you show this info in "FoeHelper" menu box as well, when it is collapsed?

And a small bug: when it is docked at top of screen, as I have it, tooltips are not shown correctly for top items...

Thanks

**Comment by Th3C0D3R** [comment]
Yes this information can be shown when the box is collapsed.

Yes a small bug
