### ISSUE TITLE
Production Overview window has no scroll bar or is too short

### ISSUE THREAD

**Issue by adwsystems** [dsiekiera/foe-helfer-extension#1721]
When viewing the fp portion of the production overview, I am unable to resize the window or scroll. I can only see what fits in the window. I cannot see the middle portion of buildings. I can see the top is sorted greatest to least or the bottom is sorted least to greatest, but there are some in the middle that never appear. ie., let's say I have 80 buildings, the screen shows 30. I can see the top 30 or the bottom 30, but not the middle 20.

![image](https://user-images.githubusercontent.com/38945034/102692549-15421a00-41e2-11eb-8bda-cec04cf35dd0.png)

**Comment by outoftheline** [comment]
will be fixed by the update.
