### ISSUE TITLE
Market Filter no content

### ISSUE THREAD

**Issue by HAL09001** [dsiekiera/foe-helfer-extension#1723]
Hi, the market filter isn't showing anything anymore:
not an any of my worlds.
Chrome, Version 2.5.4.2
![image](https://user-images.githubusercontent.com/48470058/102715130-7a296d00-42d3-11eb-8dd2-3cf8342d19eb.png)

**Comment by shanagram** [comment]
Same issue with me.

**Comment by donkidd** [comment]
Same on Brave, Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (x86_64)

**Comment by Th3C0D3R** [comment]
Already known and fixed in beta and in next update

**Comment by Pumbaa672** [comment]
Not fixed in Beta.

**Comment by outoftheline** [comment]
You are using beta?

**Comment by Pumbaa672** [comment]
Beta in FOE (ZZ1).

How does one become a beta tester in FOE Helper?

**Comment by andrgin** [comment]
You have to download beta branch and add it to Chrome manually.
