### ISSUE TITLE
Idea - GBG Overview Attrition Factor

### ISSUE THREAD

**Issue by qriz75** [dsiekiera/foe-helfer-extension#1724]
It would be great if the helper can grab the attrition deduction for each fight or negotiation and factors that into the total score. A fight with 92% reduction shouldn't count the same as one without reduction.
This could be used by leaders to motivate everyone to share the attrition and highlights the players that sacrifice for the guild.
I think 1:10 for 0 attrition up to 1:1 for free sectors should be reflective enough.

**Comment by JhonnyBn** [comment]
I think the extension can not get other players' attrition, the same way you can not know your friends attrition without asking him/her

**Comment by outoftheline** [comment]
Yep, you cannot match the attrition to an action, because you don't know the player attrition and also not where the action happened.

**Comment by qriz75** [comment]
I'm not asking for the attrition by player ... I'm asking to evaluate what boost each fight has ... you can tell what sector is hit and with that, you can tell how many camps are on sectors touching the target ... so you can calculate the boost.

**Comment by qriz75** [comment]
thinking about it again ... the list of fights just calculate the last time checked against the current total provided by Inno. So yeah I get it now

**Comment by qriz75** [comment]
impossible
