### ISSUE TITLE
Next GBG Target Time

### ISSUE THREAD

**Issue by JhonnyBn** [dsiekiera/foe-helfer-extension#1725]
It would be nice a window showing when the next GBG target will be open, similar to the incident's box. Would this be possible?

![image](https://user-images.githubusercontent.com/29382833/102732272-03af5e00-4319-11eb-8202-a411e6e9adcc.png)

**Comment by frankmorgner** [comment]
Duplicate of https://github.com/dsiekiera/foe-helfer-extension/issues/1594

**Comment by JhonnyBn** [comment]
It's in the extension now! Thank you very much! 😄 

![image](https://user-images.githubusercontent.com/29382833/107837702-03639a00-6d81-11eb-8473-9df2c6397af5.png)

**Comment by frankmorgner** [comment]
Thank you!
