### ISSUE TITLE
Münzberechnung

### ISSUE THREAD

**Issue by Flobby86** [dsiekiera/foe-helfer-extension#173]
Die Münzberechnung stimmt leider nicht.
Mal sind die Werte höher mal niedriger.
Zur Beruhigung was FoE anzeigt stimmt auch nicht wirklich.

Falls irgendwer weiß wie FoE das rechnet wäre das super.

Beispiel: 
Meine Weltausstellung St. 10 Base : 50.000
Mein Bonus : 290% = 145.000
Laut FoE wenn ich sammel : 390.000
Laut Ext . :370.000  

Münzen sind ja eigentlich total irrelevant aber wäre toll wenn man das iwie Nachvollziehen könnte.

**Comment by andrgin** [comment]
Die Extension berücksichtigt derzeit nicht die Zufriedenheit der Bevölkerung weil wir noch nicht heraus gefunden haben, wo das übertragen wird.

Zur Berechnung:
50.000 ist der Basiswert
Die Weltausstellung ist motiviert, wodurch sich dieser Wert verdoppelt
Die Summe der Boni (Markusdom, Eventgebäude etc.) ist 270%
Deine Bevölkerung ist begeistert. Das bringt nochmal 20%

Die Extension rechnet:
100.000 * (1+270%) = 370.000

Das Spiel rechnet:
100.000 * (1+290%) = 390.000

**Comment by SkateScout** [comment]
Hi die Berechnung ist nicht ganz einfach.
1)  https://foede.innogamescdn.com/start/metadata?id=city_entities-*
Hier bekommt man zu jedem Gebäude Straße etc die Werte
[*].id
[*].asset_id
[*].name
[*].entity_levels[x].provided_population
[*].entity_levels[x].demand_for_happiness
[*].entity_levels[x].provided_happiness
2) Über die Stadt Infos aus dem json Request bekommt man die Gebäude Liste.
responseData.requestClass=StartupService
responseData.requestMethod=getData
responseData.city_map.entities[*].cityentity_id
responseData.city_map.entities[*].connected
responseData.city_map.entities[*].level

Jetzt einfach sum(provided_population) = Minimum Happines
Und sum(demand_for_happiness+provided_happiness) = Happines

Die Verknüpfung erfolgt über "id"="cityentity_id"
Dann gilt:
Happines < Minimum :=  50%
Happines >= 1.4 * Minimum  := 120%
Sonnst 100%

**Comment by SkateScout** [comment]
Leider doch deutlich Komplizierter.
Es spielen noch LG's mit rein.
Und ob die Gebäude Angebunden sind wenn sie es sein müssen.

**Comment by andrgin** [comment]
Ist im aktuellen Beta gefixed und sollte mit dem nächsten Update released werden.

Und ja es war komplizierter, da z.B. polierte Gebäude auch noch berücksichtigt werden müssen.
Die Überprüfung auf "demand for happiness" war nicht notwendig. Diese ist immer gleich mit der Bevölkerung.

**Comment by andrgin** [comment]
Gefixed mit 2.3.15
