### ISSUE TITLE
Market filter doesn't work

### ISSUE THREAD

**Issue by Pumbaa672** [dsiekiera/foe-helfer-extension#1733]
I open my market, than the market filter turns green.  I open market filter to a blank screen.
Sorry for the double screen.  I'm not sure how to only print screen a single monitor on a dual monitor setup.

[Market filter issue.docx](https://github.com/dsiekiera/foe-helfer-extension/files/5745353/Market.filter.issue.docx)

Windows 10
Chrome 87.0.7280.88 (current update)
FOE Helper 2.5.4.2 (auto updates)

**Comment by Pumbaa672** [comment]
Problem has been going on for a few days now.  Not 100% sure when it started.

**Comment by outoftheline** [comment]
the update caused the error, see #1723
