### ISSUE TITLE
GB Cost Calculator Add on? 

### ISSUE THREAD

**Issue by tMFh225** [dsiekiera/foe-helfer-extension#1737]
Is it possible to be able to adjust the % buttons on the cost calculator? They have 80% 85% 90% & your personal Ark %. 
You can add your own custom one under the buttons but it resets if one of the standard buttons are chosen. If we could adjust the first 3 buttons or have the custom input stay the same even if standard buttons are clicked?

**Comment by tMFh225** [comment]
.

**Comment by dsiekiera** [comment]
Duplicate of #1650

**Comment by Jindoss** [comment]
Приветствую! интуитивно неудобна информация о количестве вносимых стратегических очков.
требуется разделить первый столбец на два полноценных, где 
1 - это количество под выставленный процент
2- это недостача до количества процента 
иначе постоянно происходит перелив , потому что смотришь на второй столбец (недостачи, выгоды)
3- выгода

**Comment by outoftheline** [comment]
your wish has been granted!

**Comment by tMFh225** [comment]
Awesome work! Thanks a lot!!
