### ISSUE TITLE
The chat has stopped working since the last update.

### ISSUE THREAD

**Issue by Artriorix** [dsiekiera/foe-helfer-extension#1738]
![2020-12-30 11_47_11-Forge of Empires - Opera](https://user-images.githubusercontent.com/76790670/103376100-04e04800-4adc-11eb-83ba-e29e5fbdff41.png)
This is the screen we see

**Comment by Intellecus** [comment]
Same for me ... and I need it back .. I was giving a guild .class this week using it and now it doesn't... I am scrambling .... trying to get everyone on Teamviewer . #

**Comment by outoftheline** [comment]
should be resolved by now

**Comment by Artriorix** [comment]
Its ok, thanks

 

Van: Yvi <notifications@github.com> 
Verzonden: donderdag 21 januari 2021 14:42
Aan: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
CC: Artriorix <erik.jjm.goris@telenet.be>; Author <author@noreply.github.com>
Onderwerp: Re: [dsiekiera/foe-helfer-extension] The chat has stopped working since the last update. (#1738)

 

should be resolved by now
