### ISSUE TITLE
2-lane Road incidents

### ISSUE THREAD

**Issue by Cady36** [dsiekiera/foe-helfer-extension#1743]
Incident is listed on 2-lane Road. There are no 2-lane Roads in my city. I checked the one lane roads, but didn't find any there, either.

**Comment by outoftheline** [comment]
We just show the data InnoGames sends to the game. If you aren't yet in an era where there are two lane roads available, just ignore these incidents.
If you can however place them, consider doing so during events when currency can be found there.

**Comment by Cady36** [comment]
I'm in Future, but don't use 2LR. I tried adding one, but it didn't appear
on that road.

**Comment by Th3C0D3R** [comment]
Reload the game after placing it or change the screen (gex,gvg,gb) and back to the city, it should appear after a sec
