### ISSUE TITLE
Technology research cost

### ISSUE THREAD

**Issue by ronintje** [dsiekiera/foe-helfer-extension#1749]
There used to be an option to scroll when using the technology research cost option for future era's.
Right now i can go to future eras, but at some point the info will be outside my window and i don't get the option to scroll down.
Is this meant to be like this, is it a bug or is it something on my end and how could i fix it.

**Comment by outoftheline** [comment]
after using the window resize function in the bottom right corner once, the window size stays the same.

**Comment by ronintje** [comment]
That worked, thanks.
