### ISSUE TITLE
Produktionsübersicht - Forge Punkte

### ISSUE THREAD

**Issue by marco-wirth** [dsiekiera/foe-helfer-extension#175]
Hallo,

ich vermisse die FP des Rathauses und dessen Botschafter in der FP Übersicht. Diese Infos stehen ja auch in der json Datei wo die Gebäude gezogen werden, kannst du das nicht noch erweitern?

Gruß
Marco

**Comment by andrgin** [comment]
Die Ursache ist, dass nicht das rh selbst die FP produziert, sondern eigentlich die Gilde und der Bonus nur im rh eingesammelt wird. Mal sehen wie man das raus holen kann.

**Comment by marco-wirth** [comment]
Also da, wo auch die Werte zu den LGs geholt werden können, kannst du nach "daily_strategypoint" suchen. Gibt es nur ein mal und unter Value ist die Anzahl an FP des Rathauses.

Hier der Teil aus der json datei:
{"value":9,"type":"daily_strategypoint","__class__":"DailyStrategyPointBonus"}

Die Botschafter finden sich recht schnell wenn man nach ""type":"emissary"" sucht.

**Comment by dsiekiera** [comment]
Ist integriert und wird im nächsten Update Verfügbar sein:

![Bildschirmfoto 2019-12-15 um 18-39-38](https://user-images.githubusercontent.com/834814/70866519-13100480-1f6b-11ea-9ced-c758c6015228.png)

![Bildschirmfoto_2019-12-15_15-17-15](https://user-images.githubusercontent.com/834814/70866520-17d4b880-1f6b-11ea-9d56-7f8547ae2e59.png)

usw...
