### ISSUE TITLE
Recommendations for GB to level for attack boost

### ISSUE THREAD

**Issue by bbehrens** [dsiekiera/foe-helfer-extension#1760]
The GB tool that indicates which GB is the most "cost effective" is great for deciding where to invest to maximize your FP returns.  However, some players may wish to focus on improving their attack rating with their GB instead.  It would be very nice to me if I could quickly find out which combat GB was most effective to increase my attack boost.  For example, Statue of Zeus will be much more efficient to simply gain 1 attack % for quite a few more levels than Terracota Army.

Long term it might also be beneficial to include the AO as well

**Comment by outoftheline** [comment]
same as #1618
