### ISSUE TITLE
Event Anzeige für bevorstehende Aufgaben für Produktionen

### ISSUE THREAD

**Issue by Lore05** [dsiekiera/foe-helfer-extension#1766]
Hallo,
wäre es möglich, eine Anzeige für die Events einzufügen, die die bevorstehenden Produktionsaufgaben anzeigen??
also sowas wie: 
Aufgabe 4, 5 mal 8 Stunden Produktionen  
Aufgabe 10 2 mal 1 Tag Produktion deines ZA
usw..
und dass sich ein Fenster mit dieser Information öffnet, wenn man ein Produktionsgebäude auswählt/öffnet?

Danke für eure Arbeit!

**Comment by Th3C0D3R** [comment]
Das gab es schon, eine Event-Questliste, wurde aber auf bitten Innos wegen Verwirrung, da es die Beta Aufgaben waren, entfernt.

**Comment by Lore05** [comment]
Bedeutet das, dass das die Anfrage nicht weiter bearbeitet wird? oder gibt es noch Hoffnung dass so etwas noch einmal angegangen wird... 
Ist es also nicht Möglich die echten und ZA entsprechenden Werte für die Produktionsaufgaben auszulesen? dann macht das natürlich keinen Sinn...
! Hilfreich wäre aber auch, dass nur die aktuellen Aufgaben angezeigt werden, also ein Hinweis kommt, wenn man gerade in einem Produktionsgebäude ist und einen Auftrag geben will, dass gerade 10 mal 4 Stunden für eine Aufgabe benötigt werden.
Das würde vor allem helfen, wenn man das aktuelle Event gar nicht so extrem Fokussiert... oder noch gar nicht in die Materie eingestiegen ist...

**Comment by outoftheline** [comment]
Ja, Eventquest-Hilfen bauen wir nicht erneut ein. 
Die Questlisten gibt es z.B. hier https://foe-rechner.de/events/overview oder in einschlägigen Foren :)

Ich spiele schon eine ganze Weile und mMn gibt es heutzutage kaum noch Aufgaben, die richtig lange dauern oder viel Vorbereitung benötigen. Produktionsaufgaben lassen sich ja auch mit Vorratsbeschleunigern, die es häufig beim Händler im Regal gibt, verkürzen.

**Comment by Lore05** [comment]
danke für die Rückmeldung
