### ISSUE TITLE
Spracheinstellungen

### ISSUE THREAD

**Issue by dsiekiera** [dsiekiera/foe-helfer-extension#177]
Zu der erkannten Sprache noch die Möglichkeit geben die Sprache zu wechseln.

**Comment by frank42hh** [comment]
Das unterstütze ich :-)
Ich habe berufsbedingt nen englischen Desktop, würde das Plugin aber trotzdem lieber in deutsch benutzen :)

**Comment by MysticElectron** [comment]
Wie ich schon im Forum schrieb würde ich auch gern implementiert sehen
