### ISSUE TITLE
Notify position not accurate.

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1772]
This is not an error, but code may be slightly improoved.

1. Bottom right.

![2101201436](https://user-images.githubusercontent.com/35531243/105175716-fd391f80-5b2c-11eb-86d7-c9a3b9e90f30.png)

I'm using the Helper menu not at the bottom of the screen.
But notifications are not appear at the very bottom of the screen - as if there is a Helper menu there.
But the Helper code "knows" where the menu is located and can use emty space at the very bottom of the screen.

2. Bottom left.

![2101201426](https://user-images.githubusercontent.com/35531243/105174947-f362ec80-5b2b-11eb-85b8-b07685d2451c.png)

There is a permanent game menu (with fixed height) in the lower left corner of the screen.
Therefore, notifications should appear above this menu (without overlapping it).

**Comment by dsiekiera** [comment]
Die Infoboxen haben von Haus aus eine Limitierung auf 4 Elemente. Käme ein fünftes dazu, wird sofort das älteste entfernt. Das mit der Höhe werde ich versuchen zu beheben.

**Comment by dsiekiera** [comment]
I've done. I maked the toasts notifications intelligent. It checks the menu position:

Menu is set to sidebar, toast to bottom:
![Bildschirmfoto 2021-02-01 um 17-28-05](https://user-images.githubusercontent.com/834814/106490169-d7f5cb00-64b5-11eb-8452-36864bbc16cf.png)

Menu is right-bottom & toast also:
![Bildschirmfoto 2021-02-01 um 17-30-51](https://user-images.githubusercontent.com/834814/106490171-d88e6180-64b5-11eb-96ad-64618103787f.png)

Toast is set to left:
![Bildschirmfoto 2021-02-01 um 17-31-39](https://user-images.githubusercontent.com/834814/106490172-d926f800-64b5-11eb-97c4-cf6af1b5c85d.png)

Menu is box:
![Bildschirmfoto 2021-02-01 um 17-51-26](https://user-images.githubusercontent.com/834814/106490457-230fde00-64b6-11eb-8bf5-f088365a7d2f.png)
