### ISSUE TITLE
v2.5.5.0 removes fight/negotiation delta count

### ISSUE THREAD

**Issue by hire-vladimir** [dsiekiera/foe-helfer-extension#1779]
d93fe4a4e32430813fd78ae60173f6e255acc0b5 removes the delta change indicator of fights since last open. Is it possible to put this back? this was one of the best parts about this functionality.

**Comment by outoftheline** [comment]
sure, don't know why it's gone.

**Comment by therapych** [comment]
We really hope that they will return the previous function.

**Comment by hire-vladimir** [comment]
shameless bump, but would be awesome to see this make it as an enhancement https://github.com/dsiekiera/foe-helfer-extension/issues/1736

**Comment by exstreme** [comment]
https://yadi.sk/i/3UA5W_tYpg51Kw isn't it?

**Comment by outoftheline** [comment]
fixed
