### ISSUE TITLE
Questions about the event helper?

### ISSUE THREAD

**Issue by Pumbaa672** [dsiekiera/foe-helfer-extension#1782]
Can anyone help me figure out what these mean?  Which one is the one I would use to increase my odds of receiving the daily prize?  And wouldn't the main prize be the daily special prize?  Sorry if this noob question for someone who has been playing for a while now.  Or at least point in the post that covers this helper.  But would like to better my odds in the near future.  Thanks

![image](https://user-images.githubusercontent.com/75749807/105557115-6e1d3a80-5cd9-11eb-8f4e-2302930db068.png)

**Comment by outoftheline** [comment]
if you want to play efficiently and get the main prize, look at the last column, the number marked in green is the best option. this means you should choose the player costing 74 footballs (first column).
please not the order of the players in the game is not always the same as in the table.

**Comment by Pumbaa672** [comment]
So what is the point of the cost/step column?

**Comment by Cady36** [comment]
If, instead of wanting the daily special, you wanted more Villa upgrades, choose the one in the cost/step column. That column denotes the cheapest way to move down the field, so you'll complete more touchdowns using fewer footballs.

**Comment by Pumbaa672** [comment]
Ok. Thank you for the help.
