### ISSUE TITLE
gbg Kampfzähler

### ISSUE THREAD

**Issue by GuNZL1NGeR** [dsiekiera/foe-helfer-extension#1783]
Mit dem letzten Update wurde der GBG-Kampfzähler für jedes Gildenmitglied entfernt. Wenn Mitglieder einen Sektorhelfer angreifen, spiegelt dies nicht mehr die Anzahl der Kämpfe wider, die jedes Mitglied hatte, das den Sektor angegriffen hat.

**Comment by outoftheline** [comment]
Du musst das nicht 2x schreiben :)
