### ISSUE TITLE
Kampf Boni

### ISSUE THREAD

**Issue by darylam** [dsiekiera/foe-helfer-extension#1785]
Aktuell mag ich eure "App" LB Investitionen" als Sicht, womit bekommen ich am günstigsten meinen nächsten FP... Könnt ihr so etwas auch für Kampfboni machen? Ist nun meine TA, Zeus, CDM oder AD die nächst beste Möglichkeit?  
 
Danke für eure super Arbeit! viele Grüße
Alex

**Comment by outoftheline** [comment]
danke und der wunsch ist schon bekannt, deshalb schließe ich an dieser stelle wegen doppelt :)
-> #1618
