### ISSUE TITLE
i18n translation loading error: ReferenceError: i18n is not defined

### ISSUE THREAD

**Issue by exstreme** [dsiekiera/foe-helfer-extension#1788]
i18n translation loading error: ReferenceError: i18n is not defined
    at chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/js/web/_main/js/_main.js?v=2.5.5.1:87
(anonymous) @ chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/js/web/_main/js/_main.js?v=2.5.5.1:93
Anyone has thi issue?
![image](https://user-images.githubusercontent.com/18548890/105606476-accef580-5daa-11eb-8410-c3ab46cf2200.png)
Can't find map with languages...

**Comment by outoftheline** [comment]
what language is your helper set to?

**Comment by exstreme** [comment]
Russian, I mean it was on autoupdate, after closing browser variables are returning, but in English. Then I change from Russian to Deutsch, then to Russian - language strings were downloaded with success.
