### ISSUE TITLE
Korrekte Verwendung von "Einzahlung von extern" in Rechner unklar

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#179]
Moin,

keine Ahnung, ob es ein bug ist oder ein feature, das ich nur nicht verstanden habe, aber in dem Rechner kommt mir die Spalte "Ext" komisch vor. Laut Hilfe soll man damit "Eingaben für evt externe Spieler die sich in deinem LG "breit" gemacht haben" getätigt werden. wie man aber an beigefügten Screenshots sehen kann, scheint die Eingabe _zusätzlich_ in die Berechnung genommen zu werden.

![Screenshot_2019-11-27_11-21-50](https://user-images.githubusercontent.com/17932878/69715202-2a946400-1108-11ea-9eed-d9f7c02461d3.png)
![Screenshot_2019-11-27_11-22-06](https://user-images.githubusercontent.com/17932878/69715210-2cf6be00-1108-11ea-9590-82a9e45e4b7f.png)

In dem LG stecken 29 von mir und 100 von einem externen. Wie man auf zweitem screenshot sieht, wird mein Eigenanteil dadurch um 100 reduziert, soweit klar, aber Platz 4 und Platz 5 sehen für mich merkwürdig aus. P4 ist normalerweie 29 FP wert, im zweiten Screenshot weisen aber beide eine Einzahlung von 100 FP auf.

**Comment by dsiekiera** [comment]
Funktioniert tatellos. Was verstehst du nicht?

Der externe (100 FP) wurde erkannt und korrekt unter den 105 von P3
einsortiert. Weil, 100 sind weniger als 105...
Dein EA wurde zurück gerechnet und P4 gibt es nicht mehr da ja der externe
drauf sitzt.
Alle freuen sich über den Rechner und nutzen ihn. Ca 6000 Spieler täglich.
Aber du erkennst das Schema noch nicht 😅?

Guck noch mal genau drauf. Du musst nix klicken wie "Berechnen" oder extra
einen externen einzahlen. Das ist alles schon passiert wenn du das LG
betrittst und den EA-Rechner öffnest.

LG, Daniel

**Comment by andrgin** [comment]
Das funktioniert schon alles so wie geplant

Also das Ganze ist so gedacht:

1.) Beim Öffnen des LG werden alle bereits erfolgten Einzahlungen schon automatisch erkannt. Die sind in der Done Spalte zu finden.
2.) In die Ext Spalte kann man zusätzliche Leute eintragen, die bisher NOCH NICHT eingezahlt haben. Die werden dann auch in die "Done" Spalte geschrieben, weil davon ausgegangen wird, dass die Externen am Anfang einzahlen.
3.) Am Schluss wird dann berechnet wann man wieviel Eigenanteil einzahlen muss, um wieviel man in welcher Reihenfolge die restlichen Plätze vergeben kann und welcher von den Plätzen dann wieviel zuviel oder zu wenig eingezahlt worden ist.

Das was noch nicht aktualisiert wurde ist die Hilfe. Hier sollte erwähnt werden, dass es nicht um Spieler geht, die sich bereits breit gemacht haben sondern um Spieler die noch nicht eingezahlt haben.

**Comment by frank42hh** [comment]
Ich verstand nicht, wieso auf dem zweiten Screenshot -, also wenn ich die 100 "ext" eingetragen habe - zwei Mal die 100 auftauchen, nämlich einmal bei P4 UND einmal bei P5. Ich habe die Hilfe so verstanden, dass der, der 100 eingezahlt HAT, mit Hilfe von der "ext" Spalte als externer markiert werden soll, damit die Berechnung das berücksichtigt, was z.B. Eigenanteil und "safe" Grenzen angeht. In meinem Vertändnis wäre das so eigentlich sinnvoll, damit man einen Einzahler, der z.B. versucht, einen Platz zu kapern, entsprechend markieren kann, damit z.B. P3 (in diesem Beispiel 105 FP) ausreichend abgesichert werden kann, damit er von dem mit den 100 FP nicht überholt wird.

Dem Kommentar von @andrgin entnehme ich nun, dass ich das also ganz richtig falsch verstanden habe, da er sagt, dass "ext" eben nicht für die ist, die sich schon breit gemacht haben, sondern quasi als "was wäre wenn" Berechnung dient.

Damit ist das geklärt und die 6000 Spieler täglich können sich wieder beruhigt zurücklehnen.

**Comment by andrgin** [comment]
Die Doku ist leider auf der Homepage ist leider nicht mehr ganz aktuell. Da ist noch die alte Version beschrieben. In der neuen Version gehen alle Einzahlungen, die bereits passiert sind wie erwähnt automatisch. Ob es sich dabei um eine geplante oder ungeplante Einzahlung handelt ist egal, Das ändert nichts am Rechenweg. Wenn auf einen Platz zu wenig eingezahlt wurde und der Platz nicht safe ist, wird das Tool immer vorschlagen diesen zu überbieten.
