### ISSUE TITLE
Anzahl der getätigten Kämpfe im GG

### ISSUE THREAD

**Issue by Lillyxyz** [dsiekiera/foe-helfer-extension#1791]
In einem der letzten Updates ist die Anzahl der (seit dem letzten Öffnen des Fensters) getätigten Kämpfe im GG rausgenommen worden... Das ist sehr schade, könnt ihr das bitte wieder mit reinnehmen?

Danke!

**Comment by outoftheline** [comment]
Ist schon behoben, schau mal bitte nach einem Update!
