### ISSUE TITLE
Maximising diamonds with Blue Galaxy Helper

### ISSUE THREAD

**Issue by NickRing** [dsiekiera/foe-helfer-extension#1792]
Sometimes, a city (that has a Blue Galaxy) gets converted over to a diamond farm - would it be possible to have an option in the Blue Galaxy Helper to help maximise diamond collection?

**Comment by outoftheline** [comment]
As diamonds are the resources you'd normally have to pay for, we don't want to include such a feature, because it would probably piss Inno off.

**Comment by NickRing** [comment]
Thought that might be the case.
