### ISSUE TITLE
Statistik Modul: "View data table" Markiersperre aufheben

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#1799]
Moin,

Im Statistik Modul kann man sich mittels "View data table" eine Tabelle der der Daten der gerade angezeigten Statistik anzeigen lassen. Es wäre super, wenn man für diese Tabelle die Markiersperre aufheben könnte, damit man diese per copy&paste z.B. in einem ingame Chat verwenden kann. Das wäre deutlich einfacher, als die Daten erst per CSV runterzuladen, in eine Tabelle zu importieren, dann nochmal zu markieren und in den Chat zu pasten.

**Comment by vegaz337** [comment]
added im pull

**Comment by outoftheline** [comment]
@vegaz337 bitte keinen riesigen pull request aufmachen, sondern für so einen einzelnen fix einen einzelnen pull request.

**Comment by vegaz337** [comment]
@outoftheline oder man sagt danke
