### ISSUE TITLE
Eigenanteilsrechner Zusatz "Kicken"

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#18]
Ich drücke mich jetzt bestimmt total unqualifiziert aus, weil ich super schlecht erklären kann...
Will es aber trotzdem versuchen ;D 

Bsp: 
Ich möchte in meinem LB alle Plätze mit z.b. 1,9 belegen lassen.
Die Plätze 1 und 2 sind nun ordnungsgemäß belegt worden. 
Nun hat sich auf Platz 3 jemand eingeschummelt mit etwas mehr als für Platz 3 gefordert wird.
Wenn man nun neu rechnet, kann man mit einer anderen Verteilung für die restlichen Plätze den eingeschummelten überbieten - also kicken, sodass er leer ausgeht oder soweit wie möglich nach unten in der Platzierung rutscht.

Könnte man diese hierfür benötigte Berechnung hinzufügen?
Sodass man quasi die derzeitige Platzbelegung eingibt, dann markiert welchen Platz man überbieten will und jetzt angezeigt wird wie die restliche Punktierung dann hierfür aussehen muss? 
War das halbwegs verständlich?

**Comment by andrgin** [comment]
Mit der aktuellen Version sollte sich das mittlerweile machen lassen. Alle bestehenden Einzahlungen werden bereits mitberücksichtigt und es wird bei jedem Platz angegeben, wie viel dieser zu viel oder zu wenig gezahlt hat.
Falls du jemanden rauskicken willst, dann trägst du in der Spalte "Ext" genau 1 FP mehr ein und das Tool macjt dir einen aktualisierten Vorschlag und du kannst entscheiden, ob dir der gefällt oder nicht.
