### ISSUE TITLE
Aussenpostenanzeige Wikinger will nicht.......

### ISSUE THREAD

**Issue by SamBrePy** [dsiekiera/foe-helfer-extension#181]
Hi,
Habe eine kleine zweite Stadt in einem meiner Accounts erstellt und spiele dort derzeit die Wikinger.
Während in den anderen Städten bei den Japanern alles hervorragend läuft, erkennt die Außenposten-Anzeige meine vorhandenen Güter bei den Wikingern nicht. Es wird dauerhaft angezeigt, ich hätte 0 von jedem Gut.

Versucht habe ich:
Cache leeren,
Relog + Reload
Funktion aus + ein
 
Bisher ohne Erfolg.

Schönen Tag noch!!

**Comment by andrgin** [comment]
Das hört sich nach #163 an. Im nächsten Update sollte das behoben sein.
