### ISSUE TITLE
Military units overview - bug ?

### ISSUE THREAD

**Issue by tatia34** [dsiekiera/foe-helfer-extension#1810]
Hello,
I think the tab that shows upcoming units is incorrect.

Currently I produce 3 types: cannons, heavy Knight and rogue.
![image](https://user-images.githubusercontent.com/78537833/106882290-e2df7400-66de-11eb-8368-15fee4b06279.png)

On the tab, it says that the next production will be : great sword warrior and longbow Archer
![image](https://user-images.githubusercontent.com/78537833/106882195-c2afb500-66de-11eb-8f04-174c8bb59260.png)

**Comment by andrgin** [comment]
The alcatraz overview does not show the next units, but the last units you have collected using this PC

**Comment by tatia34** [comment]
OK ! Thanks for the explanation.
