### ISSUE TITLE
Verhandlungsassist geht nicht auf.

### ISSUE THREAD

**Issue by eddwood** [dsiekiera/foe-helfer-extension#1814]
Hallo Foe Helfer Team,
mein Verhandlungsassist geht seit heute nicht mehr auf. Habe es schon mit Chrom und Firefox probiert. Beides das gleiche Ergebnis. An was kann das liegen? Der Haken ist gesetzt.
Nachtrag: Es geht nur bei GEX nicht bei GG. Ist das normal?

**Comment by vegaz337** [comment]
Das ist normal, da inno das so verlangt hat

**Comment by andrgin** [comment]
Bei den GG musste der Verhandlungsassistent entfernt werden, da sonst die negativen Auswirkungen auf das Balancing laut Inno zu groß wären (bzw. zu Lasten von anderen Spielern gehen) siehe:
https://github.com/dsiekiera/foe-helfer-extension/issues/860
