### ISSUE TITLE
Als Nutzer möchte ich bei Verhandlungen sehen, mit welcher Wahrscheinlichkeit ein Gut auf einen Slot passt.

### ISSUE THREAD

**Issue by korsmed** [dsiekiera/foe-helfer-extension#183]
Mal eine Idee, um ein bisschen mehr Übersicht in die Verhandlungen zu bringen
beim Start der Verhandlung wäre die Wahrscheinlichkeit, mit der ein Gut auf einen Slot passt bei allen Gütern und allen Slots gleich. 

Jedoch könnte man ja berechnen wie sehr die Wahrscheinlichkeit mit fortschreitenden Zügen bei bestimmten Gütern anwächst, und so dumme Fehler vermeiden, nur weil man im Kopf nicht alle möglichen Züge mitgedacht hat

**Comment by dsiekiera** [comment]
Das trifft sich aber gut.
So etwas in der Art ist bei uns intern bereits in Arbeit. Derzeit zu
Entwicklungszwecken noch als Windows Programm. Aber wenn der Algorithmus
sauber läuft wird dieses Feature in dir Extension integriert.

**Comment by SkateScout** [comment]
Hi, die Idee ist gut aber die Wahrscheinlichkeit ist hier nicht von Interesse.
Denn es ist wie bei einem Logical. Es gibt Güter die auf Basis der vorhergehenden
Informationen ausgeschlossen werden können. Also eine Wahrscheinlichkeit von
0 haben und N Güter die Möglich sind. Diese haben eine Wahrscheinlichkeit von 1/N.
Also wäre nur eine Anzeige  gut die Sagt welche Möglichkeit noch Sinn macht.

**Comment by dsiekiera** [comment]
Ja das macht es.
Basierend auf der Runde vorher berechnet es welches Gut passen könnte.

**Comment by andrgin** [comment]
Das Tool liefert nicht nur die Wahrscheinlichkeit, sondern ist als genereller Verhandlungsassistent geplant, bei dem man vorgeschlagen bekommt, was man tippen soll.

**Comment by dsiekiera** [comment]
Kommt in der 2.3.13

**Comment by phillip-pilz** [comment]
Das neue Feature hat einen Bug. Wenn man zum Beispiel für eine Event Quest oder sonstige Quest eine Verhandlung führen muss und vom Spiel 4 Versuche bekommt. Rechnet das neue Tool nur mit 3 Versuchen. Es erkennt nicht automatisch die Versuchsanzahl
