### ISSUE TITLE
Typo in English language string

### ISSUE THREAD

**Issue by HapkidoNinja** [dsiekiera/foe-helfer-extension#1831]
When cycling through news the FOE Helper message displays a typo...

![image](https://user-images.githubusercontent.com/8702190/107707133-3ff69f00-6c76-11eb-8314-2c1aae326277.png)

"Event History page **_previoulsy_** updated"

It should be spelled "previously"

**Comment by dsiekiera** [comment]
Hey @HapkidoNinja 

ich found a request on [http://i18n.foe-helper.com/projects/foe-helper/extension/en/](http://i18n.foe-helper.com/projects/foe-helper/extension/en/) and accepted the new suggestion:

![Bildschirmfoto 2021-02-12 um 11-15-57](https://user-images.githubusercontent.com/834814/107756026-dd5bdc80-6d23-11eb-8730-a7683bb792e1.png)

The change comes with the next BugFix Update. Thanks for this report.
