### ISSUE TITLE
Statistiken zum Chateau 

### ISSUE THREAD

**Issue by PeterPaulMary** [dsiekiera/foe-helfer-extension#1835]
Hallo zusammen,

ich hätte eine Wunsch. Ist es möglich die Statistiken des Chateau zu erfassen? es wäre schön wenn man erkenn könnte wie viele Quest man pro tag gespielt hat und welchen Gewinn man durch das CF erhalten hat. So wäre man in der Lage zu entscheiden in wieweit es sich lohnt das CF zu leveln. Ähnliches gilt auch für die Arche.

Vielen Dank für eure tolle Arbeit.
Gruß
Peter

**Comment by jjgomera** [comment]
+1

**Comment by outoftheline** [comment]
Duplicate of #985
