### ISSUE TITLE
Idea - Show Attrition reduction on GBG map

### ISSUE THREAD

**Issue by qriz75** [dsiekiera/foe-helfer-extension#1836]
It would be awesome to have the combined attrition reduction (from Siege Camps and Watch Towers) displayed on each attackable sector, Additionally a red outline if the sector contains traps.

Thank you, you are awesome !!!

**Comment by outoftheline** [comment]
unfortunately, we cannot grab that information without the user opening all building info on all (adjacent) sectors of your guild. 
and even if you have opened them before the buildings can change.

**Comment by qriz75** [comment]
too bad ... thanks for clarifying.
