### ISSUE TITLE
Datum des letzten Updates im Kostenrechner fehlt

### ISSUE THREAD

**Issue by korsmed** [dsiekiera/foe-helfer-extension#184]
Hallo zusammen :-)

in der Dokumentation zum Kostenrechner befindet sich der Hinweis, dass unten im Kostenrechner ein Datum angezeigt werden soll, wann das letzte mal etwas in dieses LG eingezahlt wurde.
Bei mir ist dieses Datum leider nicht vorhanden, gibt es dafür einen bestimmten Grund? Muss das LG dafür schon einmal besucht worden sein oder wie zieht sich die Extension die Information?

![image](https://user-images.githubusercontent.com/32894871/69912206-3c3a7c00-1426-11ea-9cda-2a756236f881.png)

**Comment by andrgin** [comment]
Die Dokumentation ist leider nicht mehr auf dem aktuellen Stand. Das Datum wird seit einiger Zeit nicht mehr von Inno Games mitgesendet und kann deshalb nicht angezeigt werden.
