### ISSUE TITLE
Typo in Motivate/Polish Helper

### ISSUE THREAD

**Issue by AmethystGlitter** [dsiekiera/foe-helfer-extension#1849]
Good day, there is a spelling error in the Motivate/Polish Helper pop-up in Event History.  Previoulsy should be Previously.

Also please make the "Event History page previously updated" box go away a little faster?  For those of us on older laptops, the box obscures the Aid/Visit buttons and causes quite a delay when aiding from event history.

![image](https://user-images.githubusercontent.com/79022046/107859432-fd140300-6dfe-11eb-84f7-da58de1a3af8.png)

**Comment by dsiekiera** [comment]
Danke für die Meldung, das wurde bereits behoben.
