### ISSUE TITLE
Armeen Anzeigen bleibt leer

### ISSUE THREAD

**Issue by Molchie** [dsiekiera/foe-helfer-extension#185]
Hallo, 
erst einmal Toll das dieses feature eingfügt wurde. Nur leider bleibt das Fenster leer nachdem man es über sein Armeen Fenster aktiviert hat. Oder habe ich was übersehen.

MfG Molchie

weiter so sonst echt klasse

**Comment by dsiekiera** [comment]
Eben bei jmd anderes auch gesehen. Da fehlt ein LG und deshalb kommt es bei der Bonus-Brechnung zu einem Fehler was die Box crached.

**Comment by Molchie** [comment]
danke für die schnelle Info 👍

**Comment by dsiekiera** [comment]
Im nächsten Update gefixt.

**Comment by Th3C0D3R** [comment]
funktioniert bei mir immer noch nicht 😢

**Comment by dsiekiera** [comment]
Ist auch noch nicht bei Google eingereicht...

**Comment by Th3C0D3R** [comment]
Ich nutzt nicht google, ich lad die erweiterung direkt aus der repo 😄 aber alles gut 👍
