### ISSUE TITLE
Falsche Sortierung der Eintragszeit bei Investitionen

### ISSUE THREAD

**Issue by Bozer-der-Barbar** [dsiekiera/foe-helfer-extension#1854]
Im "Investitionen" Helfer gibt es die Möglichkeit, die Eintragszeit einzublenden (Setup > Zeige Eintragsdatum). Wenn man die Spaltenüberschrift anklickt, scheint die Reihenfolge aber wirkürlich zu sein statt nach Datum/Uhrzeit auf- bzw. absteigend.

Chrome 88.0.4324.150 auf Windows 10 Enterprise Build 19041.746
FoE-Helfer 2.5.6.0

**Comment by danielvoigt01** [comment]
Vielen Dank für den Hinweis. Ist im nächsten Update behoben.
