### ISSUE TITLE
Fenster zu klein

### ISSUE THREAD

**Issue by Silke67** [dsiekiera/foe-helfer-extension#186]
Hallo, ich habe ein Problem mit der Größe der Fenster der Kosten-sowie Eigenanteilsrechner, ich sehe den Archebonus nicht. Ebenso den Zeitpunkt der letzten Einzahlung nicht. Muss ich irgendwo irgendetwas einstellen?
Vielen Dank im Voraus für die Hilfe.
Gruß Silke

![Screenshot 2019-12-01 20 25 52](https://user-images.githubusercontent.com/58400885/69919079-6b2e0d80-1479-11ea-910e-a4346f2516cb.png)

**Comment by dsiekiera** [comment]
Hey Silke,

Du hast in deinem Browser die Übersetzung von Google aktiviert.
Mach das aus und schon steht statt Medikamente => Meds drin und alles passt.

**Comment by Silke67** [comment]
> Hey Silke, Du hast in deinem Browser die Übersetzung von Google aktiviert. Mach das aus und schon steht statt Medikamente => Meds drin und alles passt.

Danke, und wo stelle ich das um? Weißt Du auch Rat zu den Größen der Fenster?

**Comment by Silke67** [comment]
> Hey Silke, Du hast in deinem Browser die Übersetzung von Google aktiviert. Mach das aus und schon steht statt Medikamente => Meds drin und alles passt.

schon gefunden, jetzt passt es wieder, Dankeschön
