### ISSUE TITLE
Warning icon not present

### ISSUE THREAD

**Issue by Gertrudek** [dsiekiera/foe-helfer-extension#1861]
hi, in the IT3 world I don't have the icon to put the warning in game, which is correctly present on the IT7 world. Is this a possible bug?

IT3: 
![IT3 (2)](https://user-images.githubusercontent.com/79145674/108060717-90e00c00-7057-11eb-8f2a-0b98750388a9.png)
![IT3 (1)](https://user-images.githubusercontent.com/79145674/108060718-9178a280-7057-11eb-9547-efdc465e296e.png)

IT7: 
![IT7 (2)](https://user-images.githubusercontent.com/79145674/108060809-b3722500-7057-11eb-8655-f2cfcdb67592.png)
![IT7 (1)](https://user-images.githubusercontent.com/79145674/108060812-b40abb80-7057-11eb-8da7-0b7b1aa94f60.png)

**Comment by danielvoigt01** [comment]
Yes, this is a known problem. You can find a workaround here:

https://foe-rechner.de/docs/2/workarounds/#menu-icon-disappeared

**Comment by Gertrudek** [comment]
perfect, it works correctly now. Thanks so much.

Il giorno mar 16 feb 2021 alle ore 14:11 danielvoigt01 <
notifications@github.com> ha scritto:
