### ISSUE TITLE
FP Investment hiding doesn't work as expected

### ISSUE THREAD

**Issue by Cady36** [dsiekiera/foe-helfer-extension#1865]
This is for the box that pops up when you view GBs in your town hall. I had three set for hidden, and I expect them not to be included in the calculation. This should be showing a profit of 58 FPs - instead it shows a loss:
![image](https://user-images.githubusercontent.com/52673062/108236912-449ad780-70fc-11eb-9197-5cce7b976af2.png)

If I unhide them in the calculation, then the calculation works, and shows my 58 FP profit:
![image](https://user-images.githubusercontent.com/52673062/108237471-cab71e00-70fc-11eb-8890-2448c85a5dc2.png)

It's like it's a toggle that stuck in the wrong direction? Refreshing does not fix.

Using Google Chrome/Win 10.

**Comment by danielvoigt01** [comment]
Yes this is a known problem and is solved in the next update.

**Comment by Cady36** [comment]
Awesome, thanks. Couldn't find it. :)
