### ISSUE TITLE
incident incorrectly

### ISSUE THREAD

**Issue by rado7216** [dsiekiera/foe-helfer-extension#1867]
Displays incident incorrectly. I don't have 2-way roads but still the helper shows me I have an incident there.

![2-lane road](https://user-images.githubusercontent.com/10429633/108361774-cff29680-71ea-11eb-9017-2f20d81b0d5e.png)

**Comment by outoftheline** [comment]
this is not a bug. build a 2 lane road and you can collect the incidents.

**Comment by rado7216** [comment]
And why should I build something I don't want?

**Comment by dsiekiera** [comment]
@rado7216 
Ask Inno. Dont us.
