### ISSUE TITLE
It's unclear what the +num is in GB View

### ISSUE THREAD

**Issue by poorpaddy** [dsiekiera/foe-helfer-extension#1869]
I've been trying to figure out what the +number is for on the progress bar. Can you let me know please?

<img width="592" alt="Screen Shot 2021-02-21 at 7 01 19 AM" src="https://user-images.githubusercontent.com/2213076/108629033-e418dc80-7412-11eb-8595-a9fa1a0dc0af.png">

**Comment by danielvoigt01** [comment]
This number is the latest increase of the investment.
![Auswahl_261](https://user-images.githubusercontent.com/46729881/108630201-ea837480-7463-11eb-9376-ab9c98d24b46.png)

**Comment by poorpaddy** [comment]
Thank you
