### ISSUE TITLE
Chrome Web Store

### ISSUE THREAD

**Issue by romather** [dsiekiera/foe-helfer-extension#1872]
https://chrome.google.com/webstore/detail/foe-helper/bkagcmloachflbbkfmfiggipaelfamdf 
Extension give a 404 error when search in chrome web store

**Comment by outoftheline** [comment]
we're looking into it.

**Comment by romather** [comment]
![image](https://user-images.githubusercontent.com/47756883/108761798-0f441e80-752e-11eb-819f-be95ced3f9cb.png)
my chrome is pt-br version!!!

**Comment by outoftheline** [comment]
yeah, we have to contact google. unfortunately, it will take some time to sort this out.

**Comment by outoftheline** [comment]
Update on the matter: we'll probably be back online in two weeks.

As a workaround: you can download the latest version here: https://github.com/dsiekiera/foe-helfer-extension/archive/master.zip
Unzip it.

Then you navigate in chrome to chrome://extensions/
Activate the developer mode in the top right corner. click on "load unpacked" in the top left corner and navigate to the folder of the unzipped extension. 
tada!

**Comment by robinhugy** [comment]
any update?

**Comment by outoftheline** [comment]
unfortunately, nothing new yet :/

**Comment by andrgin** [comment]
It is back online: https://chrome.google.com/webstore/detail/foe-helper/bkagcmloachflbbkfmfiggipaelfamdf
