### ISSUE TITLE
Ereignis-Übersicht - Sammeln der Daten fängt von vorn an wenn der Browser neu gestartet wurde

### ISSUE THREAD

**Issue by andy71** [dsiekiera/foe-helfer-extension#1873]
Hi, eine Freundin hat ein Problem mit ihrem Chrome-Browser und der Erweiterung. Wenn sie die Daten aus der Ereignis-Übersicht sammelt, zeigt die Erweiterung unten rechts wie viele neue Ereignisse gefunden wurden. Wenn sie das nach einer Weile wiederholt, bekommt sie alle neuen Ereignisse ebenfalls angezeigt und sobald eine Seite erreicht wurde die keine neuen Daten beinhaltet, wird auch die Meldung "Alles aktuell" angezeigt. Soweit passt das aus meiner Sicht.

Sobald sie aber den Browser schließt und neu öffnet, bekommt sie alle Daten aus der Ereignis-Übersicht als neue Daten gemeldet, von der ersten bis zur letzten Seite. Ihr Browser läuft nicht im Incognito-Modus. Es sind keine sonstigen Erweiterungen installiert und Cookies sind auch erlaubt, aber auch explizit noch mal für foe-rechner.de im Chrome-Browser eingetragen. Sie nutzt die aktuelle Version 88.0.4324.182.

Woran könnte das liegen?

**Comment by outoftheline** [comment]
Diese Daten werden im LocalStorage und der IndexedDB gespeichert, nicht über Cookies. 
Wenn also Website Daten bei jedem Schließen des Browsers gelöscht werden, geht es immer wieder von vorne los. Das lässt sich leider nicht ändern.

**Comment by andy71** [comment]
@outoftheline, vielen Dank für diese Info. Damit habe ich schon mal einen guten Ansatz wo ich suchen muss.
Ich werde mir dann noch mal die Einstellungen im Browser meiner Freundin ansehen und ggfs. mal alles auf Default zurücksetzen.
