### ISSUE TITLE
transparente Fenster

### ISSUE THREAD

**Issue by gandalfw4** [dsiekiera/foe-helfer-extension#188]
Seit ein paar Tagen erscheinen die Fenster nur noch transparent:
![screenshot-20191202-074240](https://user-images.githubusercontent.com/55873251/69936212-68620580-14d7-11ea-8e26-050f73376d64.png)
Wie kann man das ändern?

**Comment by dsiekiera** [comment]
Das hab ich ja noch nie gesehen...

Da die Struktur stimmt, scheinen lediglich die Grafiken nicht geladen zu
werden.

Ich denke das müsste ich mir mal persönlich anschauen.

Schreib mir bitte mal via Impressum von [foe-rechner.de](
https://foe-rechner.de)

**Comment by brefort** [comment]
Hallo,

ich kann das bestätigen, Habe ich auch. Ich habe mir inzwischen die
Extension über Github gezogen und per Entwicklermodus im Chrome lokal
von der Platte eingebunden. Das fixed das Problem. Vielleicht hängt das
mit dem Packaging zusammen?

Cache leeren und Cookies löschen habe ich selbstredend hinter mir...

Liebe Grüße
poppel77

Am 02.12.19 um 08:10 schrieb Daniel Siekiera:

**Comment by gandalfw4** [comment]
Habe den Cache und die Cookies NICHT gelöscht und funktioniert plötzlich wieder.
Nun allerdings stürzt die Erweiterung bei jedem Einloggen ab (siehe Bild) - kann sie zwar verwenden, doch beim nächsten mal einloggen funktioniert sie nicht mehr.
![screenshot-20191202-112930](https://user-images.githubusercontent.com/55873251/69952239-1204bf00-14f7-11ea-9a5d-98f715ec4ebb.png)

**Comment by gandalfw4** [comment]
Zu früh gefreut - Transparenz ist wieder da...

**Comment by gandalfw4** [comment]
Problem gelöst. Da ich auf meinem Rechner mit Linux arbeite und dies "case-sensitive" ist, unterscheidet es zwischen Groß- und Kleinbuchstaben.
Spitzenleistung Daniel - herzlichen Dank!

**Comment by foepsy** [comment]
Hallo, ich habe das gleiche Problem - transparente Fenster. Die Erweiterung soll auch ständig repariert werden.
Benutze ein Chromebook, und Problem ist neu seit gestern glaube ich.

**Comment by dsiekiera** [comment]
Das liegt an einem falschen Bildnamen.
In der CSS Datei wird ein technologies.png verlinkt, in der Extension ist aber eine Technologies.png.

Linux Systeme sind Case-Sensitiv, daher kommt es dort zu einem Fehler.
