### ISSUE TITLE
LG Investitionen -> falsche Berechnung beim ausblenden von LG

### ISSUE THREAD

**Issue by SmartCologne** [dsiekiera/foe-helfer-extension#1889]
Moinsen,

wenn ich ein LG ausblende in dem nur 1 FP ist und dessen möglicher Gewinn nicht beim aktuellen Gewinn einberechnet ist, wird dieser mögliche Gewinn trotzdem beim aktuellen Gewinn abgezogen nach dem ausblenden. 

Vor dem ausblenden:
![image](https://user-images.githubusercontent.com/16509118/109938777-b2382d80-7cd0-11eb-98dc-f25fe4e8a112.png)

Danach:
![image](https://user-images.githubusercontent.com/16509118/109938920-d4ca4680-7cd0-11eb-9fdd-c46374231a0c.png)

**Comment by danielvoigt01** [comment]
Hallo, in Version 2.5.6.1 gibt es noch nicht die Möglichkeit unsicheren Gewinn aus der Kalkulation auszublenden. Dies ist erst mit Version 2.5.6.2 möglich. Da bei dir hinter "Aktueller Gewinn" und "Lager + Umlauf + Gewinn" kein "(sicher)" steht, wird auch noch der unsichere Gewinn mit in die Kalkulation genommen. Von daher ist es so, wie es deine Screenshots aufzeigen korrekt. 

Du nimmst das gesamte LG aus der Kalkulation, also werden die 100 investierten FP von "Investierte FP" abgezogen und der "Aktuelle Gewinn" um die 128 FP erwarteter Gewinn verringert.  Damit verringert sich dein "Lager + Umlauf + Gewinn" um 228.

Und wie oben erwähnt, ab Version 2.5.6.2 kannst du über das Einstellungsmenü der Box die Einstellung "berechne nur sicheren Gewinn + Verlust" auswählen.

**Comment by SmartCologne** [comment]
ähm naja ok werde das in der nächsten version beobachten.
aber es ist nicht ganz so wie du sagst... denn der aktuelle Gewinn aus den ersten screenshots wird nur aus den sicheren LG berechnet, abzüglich der 10. (=548FP)

wenn man das LG dann ausblendet werden die 128 FP nicht sicherer Gewinn trotzdem von den 548 FP angezogen wo sie gar nicht berücksichtigt worden sind ;)

naja mal sehen in der neuen Version ^^

**Comment by Muckinator735** [comment]
Habe dasselbe Problem, jedoch stimmt die Berechnung weder bei ausgeblendeten LGs, noch bei Berücksichtigung aller...

Ohne Ausblendung:
![image](https://user-images.githubusercontent.com/66316515/110670980-4a04b280-81ce-11eb-8626-208d6d124603.png)

Mit Ausblendung:
![image](https://user-images.githubusercontent.com/66316515/110671081-686aae00-81ce-11eb-89ea-22a57f046534.png)

**Comment by danielvoigt01** [comment]
Ja,die Berechnung ist bis Version 2.5.6.1 fehlerhaft. Diese ist in Version 2.5.6.2 korrigiert.

**Comment by andrgin** [comment]
Ich schließe hier mal, da schon in der aktuellen Release Version behoben. Chrome User müssen sich noch ein paar Tage gedulden, bis die Extension im Store wieder online geht.

**Comment by SmartCologne** [comment]
ich möchte nicht kleinlich sein aber mir wurde grade V2.5.6.3 installiert und das Verhalten ist gleich

**Comment by danielvoigt01** [comment]
Hast du in den Einstellungen der Box "berechne nur sicheren Gewinn/Verlust" ausgewählt?

**Comment by SmartCologne** [comment]
OK, das war es.
Feld ist neu oder der haken beim update rausgeflogen, jetzt ist es korrekt!

**Comment by danielvoigt01** [comment]
Sehr schön! Die Option ist neu hinzugekommen, aber als Standardoption deaktiviert.

**Comment by SmartCologne** [comment]
muss nochmal nachhaken. 
Haken bei "nur sicher" gesetzt.
Dennoch wird meine Investition zum Gesamtvermögen hinzugezählt obwohl das nicht sicher ist und aktuell auf Verlust steht.
Dürfte nicht weder die Investition noch der Gewinn / Verlust gezählt werden?

![image](https://user-images.githubusercontent.com/16509118/115678080-69f0cf80-a351-11eb-8851-b6040591ef5b.png)

![image](https://user-images.githubusercontent.com/16509118/115678103-707f4700-a351-11eb-8078-e393a2bcb7fc.png)

**Comment by danielvoigt01** [comment]
Naja, die Investition wurde ja getätigt und wird somit zum Umlauf mit hinzugerechnet. Es wird bei gesetzter Option halt nur der sichere Gewinn/Verlust mit eingerechnet, um diese riesigen "Ausreißer" bei z.B. 1FP Investitionen herauszurechnen. Zum komplett rausnehmen aus Umlauf und Gewinn ist ja die Ausblenden Funktion gedacht. Von daher stimmt das m.M. nach schon. Was aber irritiert ist vielleicht der Begriff "sicher" hinter dem Wert, da ja nur der sichere Gewinn gemeint ist.

**Comment by SmartCologne** [comment]
Stimmt schon, im umlauf ist es.
Aber sicher ja nicht wie du gesagt hast.
Naja hab drauf aufmerksam gemacht, den Rest macht Ihr schon. oder auch nicht ;)
