### ISSUE TITLE
Erledigter Eigenanteil wird falsch berechnet, wenn gelöschter Spieler etwas eingezahlt hat

### ISSUE THREAD

**Issue by rauschm** [dsiekiera/foe-helfer-extension#1891]
Wenn ein gelöschter Spieler etwas in ein LG eingezahlt hat, dann wird der Teil des Eigenanteils, der bereits erledigt ist, falsch berechnet.
Beispiel: [http://prntscr.com/10d8xtc](url)

**Comment by andrgin** [comment]
Der Screenshot Link funktioniert leider nicht.

**Comment by outoftheline** [comment]
@andrgin https://prnt.sc/10d8xtc
