### ISSUE TITLE
NF: List of own GBs, with sorting options/filtering

### ISSUE THREAD

**Issue by NickRing** [dsiekiera/foe-helfer-extension#1902]
Hi,
I don't know if this exists in FoE-Helper as yet but it would be handy to be able to list _my own_ GBs, to see where they are at (open, primed, closed... ). Running three worlds, I forget which GBs I am working on where, and clicking on each one to find where they are at is slow.  

The data presented may need to be simplified depending on how much data is available to FoE-Helper

Suggestion of what I am thinking of:

GB | amount | state | other
---|--------|-------|-----
Arc|8111|Closed|
Zeus|230|Open|17 left for priming
CoA|348|Primed|
HC|4260|Ready to Flip| 3 remaining

Filtering would be to include/exclude closed GBs (default to exclude?)
Sorting could include the ability to sort based on the number of FPs required for the next stage (`other` column in the example above).

Still a thought in progress - so hopefully you get the idea.

**Comment by andrgin** [comment]
The information to calculate the "state" column is only available after opening each individual GB.
GB name amount paid/amount total with a nice bar is already shown in ingame GB overview.

**Comment by NickRing** [comment]
@andrgin  Sorry, the only GB overview I can find is for GBs that you have invested in (town hall -> news -> Great Buildings), not ones that are owned by me. How to get the feature you mentioned?

**Comment by Bluep** [comment]
> @andrgin ... How to get the feature you mentioned?
You can see (and enter) your GBs when clicking on the castle icon 
![image](https://user-images.githubusercontent.com/8077909/111228679-e5d65a00-85e4-11eb-982d-e8c23b0499ca.png) of your own portrait in the social bar (in the app, tap on your portrait and chose the icon from the popup menu). The same that you can do with other players.

Besides the overview, the great benefit of that list is that you can enter your GBs without collecting in case the production has finished.

**Comment by NickRing** [comment]
Didn't know about that - that is good enough. Thanks @andrgin and @Bluep 

Closing now.
