### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by izerman** [dsiekiera/foe-helfer-extension#1905]
Hi,
can't install or update Chrome Help :-(
You can help me? Thank you

**Comment by valimaties** [comment]
Yes, there is a problem with Chrome extension. It was removed from Chrome store due to a complain from one of developers (This is what I read on reddit.).

May I ask if it is possible to **build chrome extension for offline install**?

**Comment by Arklur** [comment]
@izerman, @valimaties:

CHROME INSTALLATION FROM GITHUB

- Download: https://github.com/dsiekiera/foe-helfer-extension/archive/master.zip
- Unzip
- Open chrome://extensions/
- Activate the Developer Mode in the top right corner
- Click on "load unpacked" in the top left corner 
- Navigate to the directory of the unzipped extension.

**Comment by izerman** [comment]
Thank You ;-)

**Comment by SkateScout** [comment]
https://www.reddit.com/r/forgeofempires/comments/lqo0ma/foehelper_for_chrome/goti37w/
Are there any more details about the issue?
What code was the problem, maybe it can be replaced with another version.

**Comment by outoftheline** [comment]
nothing new yet, please see here #1872
