### ISSUE TITLE
Gebäude / Auswahlkits werden nicht richtig berechnet

### ISSUE THREAD

**Issue by marco-wirth** [dsiekiera/foe-helfer-extension#1910]
Hallo,

die Zahlen zu den Gebäuden der Sets wird nicht richtig angezeigt. Ich hatte mich immer darauf verlassen, musste aber feststellen, das die Zahlen hinten und vorne nicht stimmen. Mir kommt es so vor, als ob nach einem Gebäude geschaut wird und wenn es gefunden wurde, wird diese Zahl angezeigt. Evtl. bleiben weitere gleiche Gebäude aus anderen ZAs dabei auf der Stecke und die sollten ja eigentlich addiert werden oder?

Der Gong des Kirschblütensets z.B. ist ZA los, da stimmt es, aber alle anderen Teile werden nicht addiert.

Vielleicht kann man das beheben?

Gruß
Marco

**Comment by andrgin** [comment]
Ist bereits bekannte und wird mit den nächsten Update behoben.
Im Beta Branch sollte es bereits gefixed sein siehe: https://github.com/dsiekiera/foe-helfer-extension/pull/1895/files

**Comment by andrgin** [comment]
Anmerkung:
Derzeit wird das Inventar noch nicht laufend aktualisiert. Es ist also möglich, dass während dem Spiel hinzugewonnene bzw. verbrauchte Kits noch nicht berücksichtigt sind. Dies lässt sich jedoch umgehen, indem man vor dem Öffnen der Übersicht das Spiel einmal mit F5 neu lädt.

**Comment by Bluep** [comment]
Hallo,
 ich weiß nicht, ob es mit diesem Bug hier zu tun hat (der mit dem letzten Release gefixt sein sollte; ich habe die v2.5.6.3 installiert), ich hänge es mal präventiv hier dran:

![image](https://user-images.githubusercontent.com/8077909/112757649-f6c29a80-8fea-11eb-9182-864fd9e04234.png)

Wie man sieht, wird das Palast-Kit komplett nicht angezeigt (auch nicht weiter oben/unten als "eigenständiges" Set).
