### ISSUE TITLE
Moppelassistent: Sortierung nach Name halb falsch

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#1912]
Moin,

Im Moppelassistenten kann man dien einzelnen Spalten sortieren. Das ist super, allerdings klappt es bei der Spalte "Name" nicht so richtig.

Ich habe absolut keinen Plan, wonach der da zu sortieren versucht, aber es sieht komisch aus:
![Screenshot 2021-03-16 104541](https://user-images.githubusercontent.com/17932878/111288798-cf5feb00-8644-11eb-8714-b03689d4627d.png)

Die markierte Zeile scheint so ca. der Trenner zu sein. Bis dort hin habe ich ein absolutes Durcheinander, was die Sortierung angeht, aber ab der markierten Zeile scheint es alphabetisch weiterzugehen. Dabei fällt mir auf, dass in dem oberen Teil nur Namen mit Leerzeichen und Sonderzeichen auftauchen, und der untere (sortierte) Teil besteht nur aus Namen, die aus Buchstaben und Ziffern (auch keine Leerzeichen) bestehen (der sortierte Teil geht nochmal ein paar Seiten sortiert weiter, habe ich aber aus Übersichtlichkeitsgründen weggelassen).

**Comment by danielvoigt01** [comment]
Vielen Dank für den Hinweis, ist im nächsten Update korrigiert.
