### ISSUE TITLE
FP Investments Totals

### ISSUE THREAD

**Issue by antigonus** [dsiekiera/foe-helfer-extension#1913]
When calculating the current profit GBs with a yellow profit number (presumably profit that is not locked) are not included in the calculation.

However, if you hide GBs that have a yellow profit it incorrectly deducts the yellow profit from your current profit (despite not being in that calculation previously), which negates some of the usefulness of the feature as you can't hide GBs if you want your current profit and stock+invested FP+profit number to be correct.

**Comment by andrgin** [comment]
Whcih version do you have installed?

**Comment by antigonus** [comment]
I just double checked after updating the extension today and it is still
calculating profits in this way if a non-locked spot is hidden

**Comment by danielvoigt01** [comment]
I haven't really figured out the problem yet.

Basically, in the default setting, the non-safe profit/loss is also included in the totals.

You have two setting options in the overview:

- Hide the building from the list: The building is now completely removed from the calculation. So the invested amount and also the profit/loss will be taken out completely. This consequently reduces the total profit and the total invested FP amount.

- Calculate only safe profit/loss: Can be activated in the menu of the box. Here, only the safe/locked profit/loss is taken into the calculation of the total profit. The invested FP remain the same.

**Comment by antigonus** [comment]
Yes, nevermind. I had not seen the setting in the investments tab to only
show safe profit/loss. Works like a charm!
