### ISSUE TITLE
Moppel Auswertung Spielerliste nicht aktuell

### ISSUE THREAD

**Issue by marcomo09** [dsiekiera/foe-helfer-extension#192]
Moin,
in der Moppel Auswertung sind Spieler drin die ich nicht mehr auf der Freundesliste habe. Scheint als würde sich die Liste nicht aktualisieren.
Außerdem gibt es ein Problem bei den Datumstempel, Moppels die mehr als 31 Tage zurück liegen werden wieder von vorne gezählt. 
Hier mal ein Bild was ich meine:
https://photos.app.goo.gl/RDCuiZPifDoGGVeQA

Ansonsten vielen Dank für das Tool, es ist super :)

grüße
marco

**Comment by andrgin** [comment]
Damit die Moppelereignisse übertragen werden musst du die Ereignisanzeige öffnen und alle Seiten durchklicken. Hast du das schon gemacht?

**Comment by marcomo09** [comment]
Ja, das habe ich gemacht. Die Moppelereignisse sind auch aktuell. Nur sind halt auch Spieler drin die ich nicht mehr in der Freundesliste habe. Das war früher nicht so.

**Comment by dsiekiera** [comment]
Also werden keine "Freunde" abgeglichen. Hm...

**Comment by marcomo09** [comment]
Freundesliste wird wieder abgeglichen.
Problem mit dem Zeitstempel besteht weiterhin.

**Comment by Plumsklo123** [comment]
Mahlzeit..

Ich habe aktuell das Problem das dem Moppelhelfer keine Daten übertägt. Normalerweise wenn ich die Ereignisse durchklicke kommt eine Meldung das Daten übertragen werden. Bei den LG´s funktioniert es tadellos. Habe es im Chrome und im Firefox probiert, die letzten übertragenen Moppel Daten sind ca. 1 Monat alt.

Gruß Plums

**Comment by marcomo09** [comment]
Hast du es in den Einstellungen vielleicht deaktiviert?
bei mir geht alles. Bis auf das Timestamp Problem.

**Comment by Plumsklo123** [comment]
Nope.. Es ist alles auf Aktiv gesetzt..

**Comment by marcomo09** [comment]
Alles behoben, hier kann zu
solved. thank u
