### ISSUE TITLE
[Fehler] Armeeübersicht -> Alca fertig

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#193]
Wenn das Alca fertig ist, wird in der Armeeübersicht folgendes angezeigt:
**",Die nächsten 6 Einheiten kommen kommen in  Invalid date um Invalid date Uhr,"**

**Comment by dsiekiera** [comment]
Eigentlich sollte dort so etwas stehe wie: "Bereit zur Ernte"

**Comment by Th3C0D3R** [comment]
Problem ist immer noch da ^^
"Die nächsten 6 Einheiten kommen in Invalid date um Invalid date Uhr"

**Comment by Th3C0D3R** [comment]
So ist behoben + Übersetzung im nächsten Update
