### ISSUE TITLE
FP Übersicht in "Investionen" addiert auch unsichere Plätze

### ISSUE THREAD

**Issue by JamesCook1788** [dsiekiera/foe-helfer-extension#1931]
Im Fenster "Investitionen" werden auch mögliche Gewinne aus nicht abgesicherten Mäzenplätzen zur Summe aus "Lager+Umlauf+Gewinn" hinzuaddiert.

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2021-03-26 um 16-20-25](https://user-images.githubusercontent.com/834814/112653979-3785ac80-8e4f-11eb-8fcd-0bccac0df3bd.png)

**Comment by JamesCook1788** [comment]
Super :-) Vielen Dank für die schnelle Hilfe
