### ISSUE TITLE
[Feature Request] Armeeübersicht -> Alca

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#194]
Wäre es möglich in der Armeeüberischt anzeigen zu lassen, welche möglichen Einheiten das Alca produziert?

**Comment by dsiekiera** [comment]
Das ist nicht möglich. Aber ich hab eine Funktion begonnen die zur Ernte anzeigen kann, welche Einheiten das Alca ausgeworfen hat.

**Comment by dsiekiera** [comment]
Ab und zu wird der letzte Eintrag mit [] überschrieben. Aber das bekomme ich noch raus. Das sieht dann so aus:

![Bildschirmfoto 2019-12-12 um 10-59-21](https://user-images.githubusercontent.com/834814/70702556-9bbe4480-1cce-11ea-94f2-ff47be1391f3.png)

Wirkt bei mir ein bisschen spärlich da ich nur Agenten und Helden produzieren lasse.
