### ISSUE TITLE
[Feature Request] Eigenanteilsrechner: Nachrichten sammeln

### ISSUE THREAD

**Issue by Cycloth** [dsiekiera/foe-helfer-extension#195]
Meistens bereite ich mehrere LBs vor und muss dann die einzelnen Werte / Fördernachrichten erst in ein Editor kopieren und dann kann ich erst alle Nachrichten zusammen in unsere Gilden Fördergruppe posten, z.B.:

    bitte LB1 P1 P2
    bitte LB2 P4
    bitte LB3 P5

Daher wäre eine Funktion zum Sammeln der Nachrichten ein enormer Nutzen (zumindest für mich).
Es muss nichts kompliziertes sein, z.B. zwei weitere Buttons "Sammeln" und "Alles kopieren"

Mittels ersterem wird die Nachricht intern zu einer Liste hinzugefügt, und letzterer kopiert alle zusammen und löscht den internen Speicher.

Übrigens vielen Dank für diese äußerst hilfreiche Extension!

**Comment by Th3C0D3R** [comment]
funktioniert nun und im neuen Update vorhanden (nutzen vom Button "merken" und beim letzten LG den Button "Werte kopieren" nutzen

**Comment by Cycloth** [comment]
Hi danke, hatte es schon damals gesehen.
Leider funktioniert es bei mir irgendwie (noch) nicht ...
Ich bekomme immer nur den letzten Eintrag.

Ich gehe auf das erste LB, klicke "Merken", dann 2tes LB, dann "Werte kopieren".

[Die Stelle](https://github.com/dsiekiera/foe-helfer-extension/blob/master/js/web/part-calc/js/part-calc.js#L664) wird bei mir mehrmals aufgerufen, wodurch nur nach dem ersten Durchlauf alle Zeilen enthalten sind. Aber wieso die Funktion mehrmals augerufen wird, k.A.

**Comment by dsiekiera** [comment]
Das Update kommt ja erst die Tage raus ;-)
