### ISSUE TITLE
4K Unterstützung - Rechte Seitenleisten

### ISSUE THREAD

**Issue by phillip-pilz** [dsiekiera/foe-helfer-extension#196]
Eine 4K Unterstützung in den Einstellungen wäre hilfreich. Auf großen Monitoren / Auflösungen kann man beide Scrollleisten auf der rechten Seitenleiste komplett anzeigen. Dann spart man sich das dauernde gescrolle.

**Comment by SkateScout** [comment]
Eine alternative wäre wenn man im Setup auswählen kann das nicht Alle Optionen angezeigt werden.

**Comment by dsiekiera** [comment]
Nüscht. Gibt alle Icons aufs Auge gedrückt... ;-)

Das mit der "vollen" Höhe ist tricky da die Hud-Grafik, also der Rahmen mit den Buttons eine feste Form haben. Das müsste ich zerhacken und als Sprite zusammen tüteln...

**Comment by frank42hh** [comment]
Fürs Protokoll: DAS Feature ist KLASSE :)

**Comment by dsiekiera** [comment]
So soll es sein. Es kommt noch eine Drag&Drop Sortierung dazu.
