### ISSUE TITLE
[BUG] GildenLive-Chat funktioniert nicht mehr

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#198]
Mit Version 2 des WebSocket.in Server funktioniert nun der LiveChat nicht mehr. 
Wenn man den Chat das erste mal lädt wird folgende Nachricht als Erstes an `Chat.WebsocketChat.onmessage` geschickt: 

``` json
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: WebSocket {url: "wss://connect.websocket.in/foe-guild-xxxx?room_id=1", readyState: 1, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
data: "{"info":"Please switch to websocket.in v2"}"
defaultPrevented: false
eventPhase: 2
isTrusted: true
lastEventId: ""
origin: "wss://connect.websocket.in"
path: []
ports: []
returnValue: true
source: null
srcElement: WebSocket {url: "wss://connect.websocket.in/foe-guild-xxxx?room_id=1", readyState: 1, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
target: WebSocket {url: "wss://connect.websocket.in/foe-guild-xxxx?room_id=1", readyState: 1, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
timeStamp: 1443.8150000023597
type: "message"
userActivation: null
__proto__: MessageEvent
```

Dadruch gibts zum einen eine Fehler:

> Uncaught TypeError: Cannot read property 'player_name' of undefined
    at Object.TextRow (ws-chat.js:316)
    at WebSocket.Init.Chat.WebsocketChat.onmessage (ws-chat.js:119)

zum anderen funktioniert durch V2 der Chat nicht mehr.

###MÖGLCIHER FIX###

Aktuell ist es leider nicht möglich ohne ein Token zu arbeiten. Man soll diesen theoretisch nicht über Client-Side Anwendungen veröffentlichen, doch ist das die einzige Möglichkeit den Chat wieder funktionierend zu machen.
Die GildenID darf dabei nicht größer als 10.000 sein.
Diese Zeile:

```javascript
let wsUri = 'wss://connect.websocket.in/foe-guild-' + Chat.GildID + '?room_id=1';
```
in diese zu ändern:
``` javascript
let wsUri = 'wss://connect.websocket.in/v2/' + Chat.GildID + '?token=YOUR_TOKEN';
```

**Comment by dsiekiera** [comment]
Hab ich bereits Lokal so durchgeführt. Bis dato war das Teil ja noch komplett for free, mal sehen wie lange das so bleibt ;-)

PS: Ob jmd den Token sieht oder nicht ist egal. Kosta nix...
