### ISSUE TITLE
Kopier-Buttons in Eigenanteilsrechner mit falschen FP-Werten

### ISSUE THREAD

**Issue by calli23** [dsiekiera/foe-helfer-extension#2]
Hey,

die Kopier-Buttons beinhalten nicht die korrekten Werte wie in der Rechnung in der Tabelle rechts berechnet. Es scheint sich alles um einen Platz zu verschieben. Platz 4 wird im Beispiel über die Buttons mit10 FP in die Zwischenablage kopiert, statt mit 38.

![grafik](https://user-images.githubusercontent.com/24553863/57676441-cb1bae80-7624-11e9-9030-46c5680a079c.png)

**Comment by dsiekiera** [comment]
Hab ich gestern auch gesehen. Kommt asap.

**Comment by dsiekiera** [comment]
Im Update 2.2.8 behoben.
