### ISSUE TITLE
Kostenrechner Anzeige fehlt

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#20]
Ein dickes Dankeschön für den herrlichen Kostenrechner. 

Leider gibt es Spieler bei denen wird nichts im Kostenrechner angezeigt:
![image](https://user-images.githubusercontent.com/50969949/58498377-3bc2df00-817e-11e9-8555-c0e0b5f85288.png)

**Comment by Lashandan** [comment]
In deinen eigenen LG's wird nichts angezeigt.
Und dann ist es noch wichtig, wie du das LG des Spielers öffnest.
Versuch mal bei dem gleichen Spieler über sein Portrait die Übersicht seiner LG's zu öffnen und klicke dann das gewünschte LG an - jetzt sollte der Kostenrechner auch etwas anzeigen.
