### ISSUE TITLE
Kampfassistenz

### ISSUE THREAD

**Issue by BFlassig** [dsiekiera/foe-helfer-extension#202]
Hallo! Erstmal ein großes lob für den Verhandlungsassistent!

Es wäre echt gut wenn es sowas auch für die Kämpfe gibt, zb. bei GEX, Quest, Kontinente usw..
über dort wo die gegnerische arme schon erkennbar ist.

Es soll Anzeigt werden mit welchen meiner Krieger in meiner Armee, die prozentuale beste Wahrscheinlichkeit gibt, eine den Kampf zu gewinnen.

Danke LG

**Comment by phillip-pilz** [comment]
Oh ja. Das wäre Klasse. Ich hab keine wirkliche Ahnung vom kämpfen und kämpfe nur mit Artillerie.

**Comment by andrgin** [comment]
Da habe ich leider im Moment noch gar keinen Ansatz wienich das ausrechnen sollte. Das Ganze ist ja von der KI der Einheiten, dem Gelände und zum Teil auch vom Zufall abhängig. Der Autokampf macht in gewissen Situationen auch schwere Fehler z.B. wenn er die einzige nicht Agenteneinheit alleine vor ins Gefecht schickt.
Generell sehe ich die "Chance einen Kampf zu gewinnen" nicht unbedingt als die entscheidende Kennzahl an. In der Regel sollte man ja jeden Kampf gewinnen. Die Frage ist ja wieviele Einheiten man dabei verliert.

**Comment by BFlassig** [comment]
Bei einer höheren Alca ist mir persönlich zweitrangig wieviele Einheiten ich verliere, auch wenn die Gewinn Chance nicht gehen würde wäre es eine Riesen Hilfe wenn mir angezeigt wird welche Krieger von meiner Armee die besten Angriffs uns Deff Werte im Verhältnis zu der gegnerischen Armee hat. Es kann jeder entscheiden ob es Auto Kampf wird oder Manuell steuert. Die Agenten würde ich so einstellen das man sie benutzen kann oder nicht, mit einen Aktivierungskästchen (Mit Agenden oder ohne). Agenten waren recht gut und bis zur Jahrhundertwende .. ab der Jahrhundertwende brauche ich keine mehr

**Comment by Selene443Foe** [comment]
...mir persönlich würde ja schon reichen, wenn man sehen würde welcher der richtige Gegenpart ist. Also das Resultat aus "wer hat welchen Bonus gegen wen". So, dass man am Ende nicht totalen Unfug stellt wenn man die Boni gescheit durchdacht hätte.

**Comment by andrgin** [comment]
Verworfen siehe: https://github.com/dsiekiera/foe-helfer-extension/issues/860
