### ISSUE TITLE
Eigenanteilsrechner: Anzeige der noch fehlenden FP insgesamt

### ISSUE THREAD

**Issue by poppel77** [dsiekiera/foe-helfer-extension#205]
MfG

**Comment by dsiekiera** [comment]
Wie genau ist das gemeint?

Also EA (Eigenanteil) + Mäzen addiert?

**Comment by poppel77** [comment]
Du hast oben links die gesamten GEPLANTEN Mäzen, darunter die LG-Gesamt-FP, oben rechts den GEPLANTEN Eigenanteil, darunter der Eigenanteil Verbleibend.

Ich möchte Wissen, wie viele FP ingesamt noch fehlen, bis das LG fertig ist, also Eigenanteil Verbleibend + Mäzen Verbleibend.

Hoffe, ich habe mich klar ausgedrückt.

**Comment by dsiekiera** [comment]
@poppel77 in der nächsten Version ist das bereits integriert. Geduld.
