### ISSUE TITLE
Ziwschenspeicher für GvG der Mitglieder

### ISSUE THREAD

**Issue by dsiekiera** [dsiekiera/foe-helfer-extension#206]
Es sollen Snapshots der einzelnen Gefechte und Verhandlungen getrackted werden um zu sehen wann welche Mitglieder was gemacht haben. 
Die Abstände muss der User selber wählen um ein genaues tracking zu haben.

https://forum.foe-rechner.de/d/18-gildengefechte-tracken

**Comment by R3d-N4x3l4** [comment]
In Kombination zu https://forum.foe-rechner.de/d/32-vorschlag-fur-neues-feature-fur-die-neuen-gildengefechte

Wie ist denn der Stand hierbei? Wird soetwas implementiert?
V.a. die Idee mit der "Vorher/Nacher"-Anzeige InGame finde ich super und würde sehr weiterhelfen!

**Comment by dsiekiera** [comment]
So in etwa?

![Bildschirmfoto_2019-12-29_10-54-25](https://user-images.githubusercontent.com/834814/71555211-d55eb180-2a29-11ea-92b8-044d0ba757c1.png)

Kommt im nächsten Update mit.

**Comment by Horst-Krawuttke** [comment]
hmm, habs in Beta mal getestet.
Da kommt zwar so ein Fenster, aber keine Spielerübersicht.
