### ISSUE TITLE
Erntehelfer

### ISSUE THREAD

**Issue by john-empire** [dsiekiera/foe-helfer-extension#21]
Hallo ZSM,
mein Erntehelfer funktioniert seid dem letzten Update nicht mehr.
Was kann ich tun?
LG, John

**Comment by dsiekiera** [comment]
Hey John,

Wir haben ja erst heute Vormittag geschrieben 😉

Geht es generell nicht oder nur bei einem bestimmten Nachbarn?

Hast du mal die Einstellungen recht beim Schraubenschlüssel gecheckt?

LG, mainline

john-empire <notifications@github.com> schrieb am Mi., 29. Mai 2019, 17:20:

**Comment by john-empire** [comment]
https://prnt.sc/nv2jkb

**Comment by john-empire** [comment]
In den Einstellungen ist alles aktiv  nur es werden manche garnicht (war vorher schon) bzw falsch dargestellt

**Comment by dsiekiera** [comment]
Ich glaube du suchst nur die grüne Farbe.
Hab euch wohl zu sehr verwöhnt 😅
Ließ mal die Überschrift der Tabelle.

LG, mainline

john-empire <notifications@github.com> schrieb am Mi., 29. Mai 2019, 21:07:

**Comment by john-empire** [comment]
Danke :)

**Comment by john-empire** [comment]
alles klar  danke daniel !!!  lg, john

Am Mi., 29. Mai 2019 um 22:10 Uhr schrieb Daniel Siekiera <
notifications@github.com>:
