### ISSUE TITLE
[Idee] Produktionsübersicht: Anzeige der nicht aktuellen Gebäude

### ISSUE THREAD

**Issue by Yashemike** [dsiekiera/foe-helfer-extension#211]
Hi,

ich fände es ziemlich hilfreich, wenn mir die Gebäude angezeigt würden, die noch in einem vorigen Zeitalter festhängen. 
Die Krönung wäre es, wenn ich dann auch noch sähe, wie sich die Einnahmen verbessern, wenn ich das Gebäude mit einem Plus-Eins- oder Renovierungs-Kit pimpe.

Geht sowas?

Yashem

**Comment by Th3C0D3R** [comment]
Ersteres würde gehen, zweiteres ist leider nicht möglich, da man hier eine liste braucht in der die Gebäude im neuen ZA mit deren Produktion stehen. Diese Überliefert Inno nicht und ist schwieriger umzusetzen.

**Comment by Yashemike** [comment]
Ich nähme auch schon Ersteres dankbar an! :-)

**Comment by SkateScout** [comment]
Hi, Inno Liefert diese Liste:
https://foede.innogamescdn.com/start/metadata?id=city_entities-cba5e5c24ff4a1fa658391682a311edecddd05c0
Achtung sehr groß. Zu JEDEM gebäude Kosten Produktion etc.

**Comment by andrgin** [comment]
1.) Ja da mit den ZA wäre möglich.

2.) Müsste auch möglich sein. Die Liste verarbeiten wir bereits und ziehen die additionalResources raus, um zu ermitteln, wieviele FP ein Gebäude durch Motivieren bringen würe.
Es ist aber denke ich eines an Sonderlogik notwendig, da sich die Produktionen in der metadata nicht immer mit der aktuellen Produktion decken z.B. bei "random_good_of_age" oder "all_goods_of_age", wo bei der vom Gebäude selbst ausgelesenen Produktion schon konkret steht, was alles rauskommt.
Gerade die Güter sind ja im Normalfall der der Hauptgrund, warum man ein Renokit benutzt.

**Comment by andrgin** [comment]
Das ZA wird mittlerweile in der Produktionsübersicht angezeigt
