### ISSUE TITLE
Armeeübersicht bleibt leer

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#212]
Die Armeeübersicht bleibt bei manchen Spielern generell, bei manchen Spielern (bei mir) temporär leer.

**Comment by andrgin** [comment]
Ist bereits bekannt. Fix kommt mit der nächsten Version. Grund ist ein Fehler, wenn man Einheiten aus der angreifenden oder verteidigenden Armee heraus nimmt.

**Comment by dsiekiera** [comment]
Nicht ganz. Wenn man kein Alca hat, kann die Zeit nicht abgefragt werden, was auch in eine Exception läuft. Das muss eine if drum.

**Comment by andrgin** [comment]
Ich vermute mal die Spieler ohne Alcatraz sind diejenigen, bei denen es überhaupt nicht funktioniert hat ;-)

**Comment by MrBagoo** [comment]
Stimmt. Ich habe kein Alca und bei mir funktioniert es gar nicht. Ok krass dann lag ich mit meiner Vermutung ins Blaue gar nicht so verkehrt.

**Comment by dsiekiera** [comment]
Ist bereits gefixt und kommt im nächsten Update.
