### ISSUE TITLE
Auswertung Nutzen pro Feld

### ISSUE THREAD

**Issue by bustero** [dsiekiera/foe-helfer-extension#213]
Hallo dsiekiera,
da hast Du ein wirklich tolles Tool gebastelt. Es entlastet das eigene Hirn doch erheblich. :-D Vielen Dank dafür!

Ich hätte gern noch eine Übersicht über den Nutzen (Münzen, Vorräte, FP, Güter) den ein Gebäude pro Feld liefert.  Auch wäre es schön, wenn man einstellen könnte, welche Helfer einem in der Leiste angezeigt werden.

Grüße
bustero

**Comment by Vloxxity** [comment]
Ich kam gerade um das selbe vorzuschlagen!
Lässt sich super in die Produktionsübersicht integrieren je eine Spalte nach der Menge mit Fläche und danach den Nutzen das Ergebnis aus z.B. FP/Fläche!
Um es ganz genau zu nehmen müsste man noch die Straßenanbindung oder ähnliches mit einberechnen aber das ist zu individuell als das man das ins Tool integrieren könnte/sollte!

**Comment by andrgin** [comment]
Mittlerweipe implementiert
