### ISSUE TITLE
Verhandlungsassistent Sammelthread

### ISSUE THREAD

**Issue by phillip-pilz** [dsiekiera/foe-helfer-extension#215]
Das neue Feature hat einen Bug. Wenn man zum Beispiel für eine Event Quest oder sonstige Quest eine Verhandlung führen muss und vom Spiel 4 Versuche bekommt. Rechnet das neue Tool nur mit 3 Versuchen. Es erkennt nicht automatisch die Versuchsanzahl

#183

**Comment by andrgin** [comment]
Die Logik müsste eigentlich schon funktionieren. Wieviele Güter hatte denn deine Verhandlung zur Auswahl bzw. war das eine tägliche Aufgabe oder ein Eventquest?

**Comment by phillip-pilz** [comment]
Die Auswahl der Güter dürfte sich laut Erinnerung so um die 8 gehandelt haben.
Es war eine tägliche Aufgabe mMn.

**Comment by phillip-pilz** [comment]
![event](https://user-images.githubusercontent.com/12075619/70429009-0b86c200-1a78-11ea-8e1c-5d565b533c66.png)

Gerade im Event getestet

**Comment by phillip-pilz** [comment]
Wäre auch sehr nice wenn sich das Verhandlungsassistent Fenster automatisch öffnet bei ner Verhandlung und danach auch wieder schließt.
Ähnlich des Fensters fürs plündern der Nachbarn. Gern auch über die Einstellungen aktivierbar.

PS: Ihr macht nen super Job mit eurem Tool!

**Comment by Selene443Foe** [comment]
Spielermeldungen:
1) der letzte Zug wurde nicht erkannt
2) ein Gut wurde vorgeschlagen, was nicht mehr zur Auswahl stand

![34](https://user-images.githubusercontent.com/50969949/70652904-c0290b00-1c53-11ea-8628-84bdde6dbab3.png)
![36](https://user-images.githubusercontent.com/50969949/70652927-cae3a000-1c53-11ea-9e5f-9189e6b06cc9.png)

**Comment by dsiekiera** [comment]
Genom muss im Angebot gewesen sein, da es in keinem Slot **rot** war. Bei grün wird kein Gut deaktiviert.
Das mit dem 4 Zug ist bekannt und zeitnah umgesetzt.

**Comment by andrgin** [comment]
Beim Genom verstehe ich nicht ganz, wo da das Problem liegt. Nach dem ersten Zug ist klar:
a) Es kommen alle 4 Güter vor
b) Verpackungen sind in der Mitte
c) Entweder Halbleiter, Stahlbeton oder Genomdaten kommen ein 2. Mal vor
d) Es kommt kein Gut 3 Mal vor

Genomdaten sind noch nicht rot, also noch ein möglicher Tipp.

Der Grund, warum dein Tipp vom Assistenten nicht vorgeschlagen wird ist, dass du damit folgende 2 Kombinationen nicht unterscheiden kannst:
Genom-Stahlblech-Verpackungen-Genom-Halbleiter
Halbleiter-Stahlblech-Verpackungen-Genom-Halbleiter

**Comment by Selene443Foe** [comment]
Vielleicht hab ich mich falsch ausgedückt? 
Genom stand zur Auswahl, aber die 3 Güter die gesucht waren, waren ja schon bekannt und da war Genom nicht dabei.
Also setzt man doch nicht das ein, was zum Verhandeln definitiv nicht mehr richtig sein kann.

**Comment by phillip-pilz** [comment]
Du hast da einen kleinen Denkfehler:

Es ist kein Gut ausgeschlossen worden. Es sieht zwar danach aus, als wäre schon klar welche drei Güter noch eingesetzt werden können, jedoch sind dort 2x das selbe Gut dabei. Das heißt es könnte in der Theorie noch ein drittes, unbekanntes Gut geben. Daher macht der Verhandlungsassistent an der Stelle alles richtig.

**Comment by Selene443Foe** [comment]
Ok. 
Denkfehler erkannt.
Sorry

**Comment by phillip-pilz** [comment]
![bug](https://user-images.githubusercontent.com/12075619/70789208-dbe6fb00-1d92-11ea-9bf5-f4bf66143d06.jpg)

Allerdings habe ich nun tatsächlich einen Bug gefunden.

**Comment by Th3C0D3R** [comment]
Ich seh kein Bug :D 
Du hast 3 Züge übrig und 3 Mögliche Güter die passen, er versucht jedes Gut nacheinander in alle freien slots, ist die einfachste und sicherste Möglichkeit

**Comment by phillip-pilz** [comment]
Der Bug ist, dass bei den drei freien Slots die drei passenden Güter bekannt sind. Nur nicht deren Kombination.
Der Assistent versucht aber ein viertes Gut zu verifizieren. Welches aber rein logisch schon ausgeschlossen ist.

**Comment by Th3C0D3R** [comment]
oh achso, ja das ist dann ein Bug :D hatte wohl ein knick in der Optik ^^

**Comment by andrgin** [comment]
Das ist kein Bug, sondern ein Feature
Bis lautet die Logik: Suche die Variante mit der höchsten Chance (was in diesem Fall immer noch 100% ist). Sind mehrere Möglichkeiten vorhanden nimm die Variante, die für diesen Zug die Günstigste ist.
Um das zu beheben muss ein Rekursiver Güterkostenvergleich stattfinden, was der Assistent derzeit noch nicht kann. Die Funktion ist aber geplant.

**Comment by Blackfir5** [comment]
Es werden auch nicht alle Güter erkannt. Mir ist das jetzt schon ein paar mal aufgefallen. Jedenfalls immer wenn 6-8 Güter zur Auswahl stehen. Im Beispiel wurden die Superlegierungen komplett ignoriert:
![verhasssis](https://user-images.githubusercontent.com/55910235/70851385-c659fa00-1e94-11ea-9d22-ea2293de295a.jpg)

Es wird auch meistens im 2. Zug ein Gut ignoriert, was dann zur Folge hat, dass im 3. Zug mehrere Güter auf einem Platz möglich sind und somit eigentlich immer ne 50:50 Wahrscheinlichkeit besteht.
Bei meinem Glück hat das Tool eine Gesamt-Erfolgsquote von 50-60%...

Auch im Beispiel: "Versuche zu Ende" obwohl bei der Komplexen TQ der 4. Versuch ohnehin dabei ist und nicht mal Dias braucht. Ich weiß, ist bekannt, aber:
Das Tool könnte ja immer einen Vorschlag für den nächsten Versuch bringen, egal ob man ihn kauft, oder nicht. Einen Handelsabbruch erkennt das Tool ja ;)

**Comment by Blackfir5** [comment]
noch ein bild, 6 mögliche, superlegierungen wurden wieder ignoriert, aber wie man sieht, gebraucht...
![verhandlungsas](https://user-images.githubusercontent.com/55910235/70855589-a2ff7100-1ecd-11ea-9362-23dfb30a8a13.jpg)

**Comment by andrgin** [comment]
1.) Das mit den 3 Zügen bei den Events ist schon bekannt. Das ist in der Beta schon gefixed und im nächsten Update enthalten.

2.) Da alle Züge aus Performancegrünen vorberechnet sind, ist das mit dem Vorschlagen nicht so einfach. Dabei müsste wahrscheinlich fast der gesamte Programmcode, der aktuell in der Simulation zum Vorberechnen läuft zusätzlich in der Extension implementiert werden.

3.) Bei 3 Zügen ist die Wahrscheinlichkeit nur ca. 80% bei 5 Gütern bzw. ca. 60% bei 6 Gütern. Besser geht es leider nicht.

4.) Derzeit sieht der Algorithmus so aus:
a) Fange immer mit 5 verschiedenen Güter an (der erste Zug ist fest codiert)
b) Suche den Züge mit der höchsten Lösungswahrscheinlichkeit
c) Haben mehrere Züge die höchste Wahrscheinlichkeit, so wähle den billigsten aus. In diesem Fall sind das bevorzugt Güter der VZ. Superlegierungen sind ganz am Schluss dran, da bei denen der Lagerstand am Geringsten ist.

Dass solange die Lösungswahrscheinlichkeit nicht darunter leidet Güter gespart werden ist geplant.

Die Schwachstelle daran ist jedoch, dass derzeit nur die Kosten des aktuellen Zuges bei der Reihung berücksichtigt werden, wodurch in einige Fällen Züge vorgeschlagen werden, die zwar auch die beste Lösungschance haben, jedoch insgesamt teurer sind z.B. wenn eine nicht mögliche Kombination ausgewählt wird, da dieser in diesem Zug billiger ist.

Ich habe mittlerweile eine neue Version entwickelt, die die Güterkosten auch rekursiv prüft. Aktuell werden gerade die neuen Tabellen generiert. Das dauert aber leider etwas (mit dem alten Algorithmus waren es 16 Stunden für die 10 Güter/4 Runden Tabelle).

**Comment by andrgin** [comment]
Zu dem lezten Bild:
Nach den ersten 2 Zügen gab es noch 2 mögliche Kombinationen:
Goldreis/Goldreis/Naniten/Naniten/Naniten
Goldreis/Goldreis/Naniten/Naniten/Superlegierungen

Da es eine 50/50 Chance ist werden Naniten ausgewählt, da diese billiger sind (VZ vs. Mars). Das soll ja so sein.

**Comment by Blackfir5** [comment]
Das System hat ein paar gröbere haken.

1. Wenn in der 2. Runde nicht alle restlichen Güter angetestet werden, ist es sehr unwahrscheinlich in 4 Zügen zum Ziel zu kommen. Grad in der GEX mit 10 möglichen Gütern ist mir aufgefallen, dass das Tool überhaupt keinen Sinn macht.

2. Das "billigste" Gut ist für mich immer das Gut aus dem aktuellen ZA. Alte Güter werden ja nicht mehr produziert. Gibt man für die Versuche nur alte Güter aus, ist man schnell am Ende, bei vollem Güterlager des aktuellen ZA. Das runterhandeln, gerade von Mars in VZ, kann man ja immer mehr vergessen, weil keiner mehr tauscht.
2a. weiters ist auch die Wahrscheinlichkeit höher, dass bei einer 50:50 Chance das aktuelle Gut trifft. Das trifft auch auf Werkzeug und Münzen zu. Stehen ein Gut und Münzen zur Auswahl, treffe ich fast immer mit dem Gut.
2b. Das heißt, in meinen bisherigen Verhandlungen hab ich die beste Trefferquote mit dem Gut des höchsten Lagerstandes, des aktuellen ZA. Kann jetzt natürlich subjektiv sein, aber das ist definitiv meine Beobachtung aus meinen Verhandlungen.
Und es hat den Vorteil, dass das Lager möglichst lange hält.

**Comment by andrgin** [comment]
1.) Das Tool rechnet alle möglichen Kombinationen durch (bis auf die Annahmen mit 5 verschiedenen Gütern zu starten und nicht 2 Mal dasselbe Gut an denselben Platz zu setzen). Wenn man von externen Faktoren wie "Güter sind zu Ende" absieht, dann wirf es immer eine der Lösungsvarianten mit der höchsten Lösungswahrscheinlichkeit aus.

Beispiel anhand der 4/10er Verhandlung:
5rot, 4rot1gelb, 3rot2gelb, 2rot3gelb probieren alle im nächsten Zug die Güter 6/7/8/9/10 durch
Die Variante 1rot4gelb probiert nur 6/7/8 durch und versucht mit den anderen 2 Stellen die Position der anderen 4 Güter heraus zu finden. Dabei entsteht eine Wahrscheinlichkeit von ca. 66%. Ein Verwenden aller 5 anderen Güter scheint hier nicht mehr Erfolgsquote zu liefern, da es wenig bringt nur das 5. Gut zu wissen, wenn am Schluss nichts über die Positionen der anderen 4 Güter bekannt ist.

2.) Über die Marsgüter kann ich noch nichts sagen, aber in jedem Zeitalter davor kann man locker hinunter handeln, zwar meistens nicht mit einem Kurs von 1:2 aber definitiv höher als 1:1. Das schlimmste war bisher glaube ich von Morgen auf Gegenwart, wenn man selbst in OZ sitzt mit 1:1.4
Ich werde mir einmal weiteres Feedback einholen von Spielern aus dem Marszeitalter, ob man das generell bei allen sagen kann. Wenn ja, dann füge ich eine Ausnahmeregelung nur für die Marsgüter ein.

2a/b) Also ich habe das Tool mit der Annahme entwickelt, dass die Güter wirklich zufällig generiert werden. Bisher habe ich noch keine Anzeichen dafür gefunden, dass dem nicht so ist. Ich denke also, dass das eine rein subjektive Wahrnehmung ist. Es hat hier jeder seine eigenen sich teilweise widersprechenden Theorien.

3.) Was das Ausgleichen des Lagerstandes angeht, so versucht das Tool bereits innerhalb des gleichen ZA bevorzugt die Güter mit höherem Lagerstand auszuwählen aber eben zuerst Münzen/Vorräte bzw.  Güter aus vorherigen Zeitaltern.

**Comment by Selene443Foe** [comment]
Zu dem Thema habe ich hier einen Vorschlag eines Gildies. Vielen Dank an dieser Stelle hierfür nochmal.
Vielleicht wäre das ja eine Variante:

"Am besten wäre wenn man selbst die Prioritäten der unteren Liste vergeben könnte, dann wären alle glücklich.
Ich würde z.b. Medis vor Gütern nutzen da ich nicht weiß wohin damit, aber für kleinere Spieler wäre das grausam.
Und ich würde erst Güter höherer ZA und dann die der niedrigeren nehmen.

Zuerst Münzen
Dann Vorräte
Dann Medaillen
Dann Güter höherer Zeitalter
Dann Güter niedriger Zeitalter
Dann Promethium
Dann Orichalcum

So quasi, evtl als Preset für fortgeschrittene Spieler auswählbar (und die alte Liste als Standard für alle Spieler)."

**Comment by andrgin** [comment]
1,) Das mit der Reihung ist an sich eine gute Idee. Die Frage ist nur, wie man das benutzerfreundlich umsetzt.
Mein ursprünglicher Plan war ja, dass der Spieler selbst, die Reihenfolge durch die Auswahl der Güter in der Verhandlung bestimmt. Das Problem daran war, dass man ohne Lesen einer Anleitung es für den Spieler nicht ersichtlich ist, wo er Güter wechseln kann bzw. nicht.

2.) Bist du auch im Marszeitalter? In allen anderen Zeitaltern kann man ja die Güter runter handeln.

**Comment by Selene443Foe** [comment]
1) Benutzerfreundlich:
Ich würde in den Einstellungen hierzu die Auswahl "Standard" und "Insider" wählbar machen.
Unter "Insider" ist der Text (so oder so ähnlich) aus dem Forum zu lesen. Der erscheint mir für die Leute die "Ahnung haben" verständlich:

> A) Wähle die Kombination die (rekursiv mit demselben Algorithmus betrachtet) zur höchsten Wahrscheinlichkeit führt. Mit dem Zusatz dass kein Gut an einer Stelle doppelt geraten wird (ja es gibt wirklich ein paar wenige Sonderfälle wo es Sinn macht an einer Stelle 2 Mal dasselbe Gut zu raten aber in 99.9% der Fälle erhöht es nur sinnlos den Güterverbrauch).<

>B) Wenn es mehrere Möglichkeiten mit derselben Wahrscheinlichkeit gibt (besonders wenn genügend Züge vorhanden sind und man locker 100% Trefferchance hat), dann wird die billigste Kombination genommen wobei die Güter mit 0 bis 9 gereiht werde. Was derzeit noch nicht gemacht wird ist die Güterkosten auch rekursiv zu betrachten. Das ist irgendwann einmal als Optimierung geplant.<

>Die Extension verwendet dann die Tabellen reiht die Güter jedoch schon einmal selbständig um. Derzeit ist der Algorithmus der:
Zuerst Münzen
Dann Vorräte
Dann Güter niedriger Zeitalter
Dann Güter höherer Zeitalter
Dann Medaillen
Dann Promethium
Dann Orichalcum<

>Wenn 2 Güter eines Zeitalters gefordert werden, so wird bevorzugt das verwendet wo der aktuelle Lagerstand höher ist.<

Dann würde ich die Reihung so wie sie hier aufgeführt ist als Auswahlfeld anzeigen.
Vielleicht sogar so gestrickt wie es manchmal bei irgendwelchen Webseiten zu sehen ist, wo man erst den ganzen Text runter scrollen muss und ein Häkchen setzen muss, bevor das eigentliche zum Vorschein kommt.
Hinzu ein dicker roter Hinweis, dass man gefälligst die Standardeinstellungen belassen soll, wenn man nicht zu 100% verstanden hat, was in der Info dazu steht.

2) Nein. Weder ich noch der Spieler von dem der Vorschlag stammt.
Sein Argument hierzu ist, dass er zum Handeln keine Lust / Zeit hat. Er holt alles über LG's, Nachbarn oder Schleifen rein. Da er mit dieser Spielweise nicht der einzige ist und somit die aktuellen Güter jene sind die man "billig" beschaffen kann, passt die derzeitige Vorgehensweise des Tools nicht auf solche Spieler.

**Comment by andrgin** [comment]
Es sind nun folgende Änderungen geplant, die schon in der Beta vorhanden sein sollten:
1.) Die Güterkosten wird nun auch rekursiv berechnet.
Alte Auswahllogik:
a) Wähle einen Zug mit der höchsten Lösungswahrscheinlichkeit
b) Ist die Lösungswahrscheinlichkeit mehrerer möglicher Züge gleich, nimm den Zug mit den geringsten Güterkosten für diese Runde

Neue Auswahllogik:
a) Wähle einen Zug mit der höchsten Lösungswahrscheinlichkeit
b) Ist die Lösungswahrscheinlichkeit mehrerer möglicher Züge gleich, nimm den Zug mit den geringsten Güterkosten für die gesamte Verhandlung

Bei der Bewertung der Kosten kommt wie bisher die Gewichtung der Güter zum Tragen d.h. das erste Gut ist das Billigste, das letzte Gut ist das Teuerste.

2.) Die verwendeten Güter inkl. der durchschnittlichen Kosten werden nun vor jedem Zug oben im Fenster angezeigt. Dabei wird auch bei zu geringem Güterbestand (gelb/Güterbestand knapp => der Gütervorrat wird im Worst case nicht ausreichen, rot/Güterbestand kritisch => der Gütervorrat ist geringer als die Durchschnittlichen Kosten)

3.) Der Spieler hat die Möglichkeit vor dem ersten Zug die Reihung der Güter per Drag and Drop zu ändern (z.B. Medaillen weiter nach vor, Güter der vorherigen Zeitalters weiter nach hinten usw.)

4.) Die Position den Fensters wird nun nicht mehr gespeichert, sonder es wird automatisch so über das Verhandlungsfenster gelegt, dass die Gütervorschläge in einer Linie über dem Verhandlungsfenster sind, wobei der Schließen Button noch erreichbar bleibt.

5.) Das Verhandlungsfenster öffnet sich sofern in den Einstellungen die jeweilige Option aktiviert ist automatisch bei Verhandlungsstart bzw. schließt sich automatisch wieder (in der Beta ist die Einstellung derzeit immer aktiv, das automatische Schließen funktioniert nur teilweise)

**Comment by Selene443Foe** [comment]
In einer meiner zwei Welten (Greifental) wirft der Rechner (Beta) eine falsche Anzeige zum Lagervorrat aus.
Es scheint nur meine Welt betroffen zu sein, bei anderen Gildis besteht das Problem nicht.
F12 / F5 = keine Veränderung.
![40](https://user-images.githubusercontent.com/50969949/71131759-e3c0f800-21f5-11ea-9ead-ce21b6b9327b.png)

**Comment by andrgin** [comment]
Kann es sein, dass du von dem Gut gar nichts mehr auf Lager hast?

**Comment by dsiekiera** [comment]
@andrgin laut dem Foto hat sie 2617 davon. Stellt sich die Frage warum genau das eine nicht erkannt wird...

**Comment by andrgin** [comment]
Achso sorry habe ich übersehen. Funktioniert die Anzeige der Außenpostengüter? Das greift auch dieselben Daten zu.

**Comment by Selene443Foe** [comment]
Ahhhh.... die Frage nach dem Außenposten löst das Rätsel.
Ich habe keine Ausßenposten. In MK habe ich dennoch den Haken aktiviert - hier funktioniert die Anzeige des Verhandlungsassi korrekt.
In Greifental ist der Haken nicht aktiviert = Anzeige des Verhandlungsassi nio.
Nach Aktivierung des Hakens nun auch in Greifental eine korrekte Anzeige im Verhandlungsassi.

**Comment by andrgin** [comment]
Bei weiterer Analyse hat sich herausgestellt, dass die Erkennung der Güter nur mit aktivierten Außenpostenmodul funktioniert bzw. die Erkennung der 4. Gex Runde nur mit aktiviertem Tavernenbadge. Im beta Branch ist das bereit korrigiert und wird mit dem nächsten Update ausgeliefert.

Weiters wurde die default Güterpriorisierung geändert sodass Marsgüter nun unter virtuellen Gütern eingeordnet sind.

**Comment by Blackfir5** [comment]
ahoi.
erst mal, das mit der Reihung ist ja schon nicht schlecht, man muß aber bei jeder Verhandlung die Marsgüter nach vor ziehen. Im Gefecht, speziell im Duell um einen Sektor, ist das aber kostbare Zeit. (ja, meckern auf hohem Niveau ;)  ). Ev. würde hier eine "Merkfunktion" helfen?
Ich bin auch nicht sicher, ob sich da jetzt nicht zu stark auf Mars-Güter versteift wird. Im Hinblick auf die Zukunft und weitere ZA.
Das billigste ist ja nach wie vor das niedrigere ZA. Allerdings wenn man berücksichtigt, dass nur aktuelle Güter produziert werden, ist das aktuelle das Beste (ähnlich Best- und Billigstbieter Prinzip. Der billigste Anbieter ist nicht immer der Beste...
Es ist auch immer das Ende der Forschung was das ganze starkt beeinflußt. Ist man am Ende, sammeln sich die Güter. So kann es sein, dass man aktuell je 20k Güter Mars hat, aber nur 1k VZ. In ein paar Zeitaltern werden zukünftige aufsteiger diese Situation nicht haben.
Für die Zukunft wäre also eine Auswahl zwischen "billigstes Gut bevorzugen", oder "aktuelle Güter bevorzugen" am sinnvollsten. Im nächsten Za wirds dann ja vermutlich so sein, dass Ceres-Güter bevorzugt werden sollen und VZ wieder "normal" vor Mars...   ;)

**Comment by andrgin** [comment]
1.) Ich habe ein paar Marsspieler befragt 7nd die meinten, dass Marsgüter am Markt deutlich wertloser sind als VZ Güter. Sie meinten sogar unter OZ Niveau. Ich muss mich hier leider auf das Feedback der anderen Spieler verlassen, da ich selbst noch nicht im Mars bin.

2.) Bei jedem anderen ZA kann man ja jederzeit eines der aktuellen Gütergebäude abreißen und eines des vorigen ZA hinstellen. Auch kann man jederzeit im Markt die Güter runter handeln oder eben beim nächsten ZA nicht alle Eventgebäude mit Renokit  hochziehen.

3.) Was die verschiedenen Profile angeht würde ich das eher vermeiden, da das schnell ausartet. Der eine will die Güter des vorigen ZA zuerst, der andere will die Güter bei denen er Vorkommen hat, der andere vielleicht die mit den geringsten Produktionskosten, einer mag Medaillen vorne, einer vielleicht Promethium weil er davon zu viel auf Lager hat usw.
Das gibt Unmengen an Einstellungen.

**Comment by Blackfir5** [comment]
Aber das ist ja genau das, was ich sagte. Mars ist im Moment wertloser, weil das in unmengen da ist, deshalb sollte jetzt Mars vor gereiht werden können. Wird das nächste ZA Ceres frei geschalten, wird sich das wieder ändern und Ceres anfangs teuer, weils jeder haben will, später wieder das billigste, weils in unmengen da ist. Mit ZA wechsel levelt man die Gebäude um die neuen Güter zu bekommen, später kann man sie aber nicht mehr downgraden. Es wird sich also immer so weiter drehen. Ohne Einstellmöglichkeit müßtet Ihr das immer umstellen, jenachdem ob es ein neues ZA gibt und wie lange. Wobei das für jeden Spieler auch wieder unterschiedlich ist, je nachdem wie schnell er seine Lager mit den neuen Gütern füllen kann.
Eine Einstellmöglichkeit dafür würde Euch die Entscheidung, wann was umgereiht wird, abnehmen.

Zu 2. welches Gütergebäude soll man abreißen, wenn Gütergebäude doch gar nicht mehr gebaut werden (Chateau, Eventgebäude)?...

**Comment by andrgin** [comment]
1.) Ich richte mich da weniger nach dem einzelnen Spieler, sondern nach der allgemeinen Situation im Markt und dieser dürfte für alle Spieler im Mars ähnlich sein, zumindest nach 1-2 Wochen nach dem ZA Wechsel wenn einer eine Nachbarschaft aus Marsspielern bekommt.

2.) Derzeit ist über Ceres noch nichts bekannt, Wenn das Update kommt, muss die Extension sowieso updatet werden um die Ceres Güter zu erfassen und dann wird Ceres einmal als hochwertigstes Gut eingestuft werden. Ich gehe einmal davon aus, dass Ceres Güter immer mehr wert sein werden als Marsgüter und Ceres und VZ Güter gibt es voraussichtlich nicht gemeinsam in einer Verhandlung. Von daher wird denke ich nur VZ > Mars die einzige Ausnahme sein.

3.) Jeder spielt anders. Ich habe z.B. in der VZ noch 10 reguläre Gütergebäude stehen. Viele Spieler haben zwar keine Gütergebäude mehr, jedoch eine Menge Terrassenfelder aus dem vorigen ZA und können bei Bedarf in denen jederzeit noch alter Güter produzieren. Sobald der Markt wirklich so weit kippt, dass z.B. VZ Güter weniger wert sind als OZ Güter, werden sofort einige Nachbar anfangen OZ Güter zu produzieren. Das regelt der Markt dann von alleine.
Mars ist hier einfach ein Sonderfall, da man hier eine extra Basis hat, wo man eben nur Marsgüter machen kann, ob man diese nun braucht oder nicht.

**Comment by Andi47** [comment]
> c) Haben mehrere Züge die höchste Wahrscheinlichkeit, so wähle den billigsten aus. In diesem Fall sind das bevorzugt Güter der VZ. Superlegierungen sind ganz am Schluss dran, da bei denen der Lagerstand am Geringsten ist.
> 

wäre gut, wenn die Güterkosten bzw. der Lagerstand auch beim ersten Zug berücksichtigt würden:

Ich bin im Marszeitalter und habe aktuell von den Mars-Gütern 10k bis 39k je Sorte, und von den VZ-Gütern ca. 3k je Sorte. Trotzdem werden bei mir regelmäßig die VZ-Güter als erstes eingesetzt, oft wird sogar das knappste Gut als Gut mit dem höchsten durchschnittlichen Verbrauch ausgewählt.

Vorschlag: es wäre besser, wenn die automatische Auswahl für den ersten Zug so liefe, dass das knappste Gut den geringsten durchschnittlichen Verbrauch hat, und das am meisten vorhandene Gut (bzw. Münzen, Vorräte oder Medaillen) als erstes (d.h. mit dem höchsten durchschnittlichen Verbrauch) ausgewählt wird

**Comment by andrgin** [comment]
Ich mache hier einmal dicht. Wenn noch Bugs/Wünsche auftreten bitte ein einzelnes Ticket eröffnen.
