### ISSUE TITLE
Gildengefechte

### ISSUE THREAD

**Issue by phillip-pilz** [dsiekiera/foe-helfer-extension#216]
Ähnlich zu der GEX Auswertung auf der Webseite wäre dies auch klasse für die Gildengefechte.

Für IG wäre es klasse wenn man eine Prognose sehen könnte, dies ist vor allem gegen Ende der GG interessant um zu sehen wie viel die Konkurrenz stündlich einnehmen müsste um einem den Platz streitig zu machen. So kann man gegen Ende etwas die Kräfte sparen und für die nächste Saison schonen.

Eine Gebäudeansicht wäre auch gut, bei der man alle gebauten Gebäude sieht und in welcher Provinz diese stehen.
Da man hierfür vermutlich alle Provinzen anklicken muss, wäre es praktisch wenn in der Übersicht noch nicht gescannte Provinzen markiert werden und die Ergebnisse gecached werden.

**Comment by Horst-Krawuttke** [comment]
Wenn wir schon dabei sind:
Es wäre auch nicht schlecht, wenn man die Spielerliste einlesen könnte und einen Vergleich zur letzten Liste sieht
Also z.B.
1 Willi 3 (+1) 27 (+5)
2 Horst 2 (-) 13 (+2)
3 Walther 1 (-) 12 (-)
Auf diese Art, könnte man, wenn man zwei mal kurz nacheinander aktualisiert,  Leuten auf die Spur kommen, die gerade irgendwo planlos angreifen.

**Comment by orgetorix-retter** [comment]
Wenn wir schon dabei sind part 2 :)
Es wäre echt genial wenn man in der Infobox sehen könnte wer gerade von den Gildies auf Sektoren kloppt :)
Sowie bei der GEX kommt ja auch ständig die Info das ein Spieler gerade bei der GEX  X-Punkte gemacht hat

Aber liefert FOE überhaupt diese Info?

**Comment by dsiekiera** [comment]
Nein leider nicht. Es wird nur übertragen welche Gilde gerade wie viele Punkte gemacht hat. Das wird nicht aufgeschlüsselt.

**Comment by orgetorix-retter** [comment]
hmm ich dachte weil die Mitgliederliste
sich ja auch ständig aktualisieren muss wieviele Verhandlungen/Kämpfe der jeweilige Spieler gemacht hat da muss inno doch auch die Daten an der Karte schicken?

**Comment by dsiekiera** [comment]
Da hast du natürlich recht. Die Daten kommen aber wirklich auch nur dann wenn du diese Liste aufrufst.
Es gibt schon ein Ticket mit dem Wunsch diese Übersicht zu tracken.

**Comment by Th3C0D3R** [comment]
Ist nun vorhanden. Ich schließ hier mal, bei Problemen kann mans wieder öffnen
