### ISSUE TITLE
Event Questliste

### ISSUE THREAD

**Issue by phillip-pilz** [dsiekiera/foe-helfer-extension#217]
Ein weiteres Feature was ich mir sehr gut vorstellen könnte, wäre die Event Questliste zum ingame nachschlagen.

Diese könnte auch als Hilfestellung für die nächsten 5 Quests die Anforderungen mitteilen, sodass man die Quests einfacher planen kann um schneller und effektiver voran zu kommen.

**Comment by Th3C0D3R** [comment]
Leider übermittelt Inno diese Informationen nicht (nur die aktuelle Quest) 
Aber um die Idee nicht gleich fallen zu lassen, gäbe es die Möglichkeit die Questliste "manuell" einzulesen und der User dann die Möglichkeit hat dies Quests einzeln als erledigt zu markieren.
Die Erledigten werden dann ausgeblendet und die nächsten 5 werden angezeigt.

@dsiekiera ich meine damit eine json Datei die alle Quests beinhaltet (eventuell mit Belohnung), Die Quests bekommt man ja von [hier](http://xmedia.xobor.de/f9-EVENTS-Winter-Event.html). Diese Liste könnte man recht einfach in eine JSON packen (muss man dann ja nur einmal pro Event machen)
Die Datei kann zum Start der Erweiterung eingelesen werden, wenn im localStorage nichts hinterlegt ist.

**Comment by Th3C0D3R** [comment]
Ok, schwierig wirds dann eher für andere Sprachen, da ich keine Quellen für die Quests in anderen Sprache finde. Ein Live-Übersetzer kommt aufgrund der Abkürzungen auch nicht in Frage.
Werd die Idee im Hinterkopf behalten aber erstmal fallen lassen @phillip-pilz

**Comment by Th3C0D3R** [comment]
Falls noch nicht mitbekommen, derzeit arbeite ich an diesem Feature, es wird aber erst leider im laufe des Events erscheinen bzw mit dem nächstmöglichsten Update. Aber danach kann es für jedes event genutzt werden 😉

**Comment by Th3C0D3R** [comment]
Ist in der Beta und kommt beim nächsten Update
