### ISSUE TITLE
Danke

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#22]
Darf man hier eigentlich auch einfach nur mal Danke sagen? :)
Die neue Moppelauswertung ist ja super geworden 👍

**Comment by JHCD** [comment]
Vielen Dank für die Blumen :)
Tavernenbesuche folgen...

**Comment by Selene443Foe** [comment]
So... am ersten Tag als das Tool raus kam hab ich gesagt "dieses tolle Ding würde ich ja sogar sofort kaufen wenn ich müsste".
Jetzt geht das ja sogar :D 
Also erstmal ein schönes Bierchen spendiert 👍 Lass es dir schmecken ;)
