### ISSUE TITLE
[BUG] Produktionsübersicht

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#221]
In der Produktionsübersicht wird "St. 1 Gong der Weisheit" unter "Zufalls Produktionen" geführt, obwohl es keine Zufallsproduktionen besitzt:

![image](https://user-images.githubusercontent.com/7798500/70621373-b2ef2a80-1c19-11ea-8855-08d97d12d894.png)

**Comment by Th3C0D3R** [comment]
Ok, kann geschlossen werden, das ist leider etwas was FoE so übermittelt.

**Comment by dsiekiera** [comment]
Jo. Wollt ich gerade so schreiben. Diese "letzte" Liste gibt eigentlich 1:1 zurück was Inno übermittelt, nur gruppiert.
Die sind halt auch nicht perfekt ;-)
