### ISSUE TITLE
Eine mal andere Frage :D

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#223]
Da ich keine andere Kontaktmöglichkeiten gefunden habe mach ich einfach ein Issue auf, was kein Issue ist.

@dsiekiera
Ich hab mich mal bissle schlau gemacht und wollte schauen ob es nicht doch eine Möglichkeit gibt den Helfer für (zumindest Android) als App zu erstellen.
Hab auch ein, zwei gute Ansätze wie das eventuell umsetzbar wäre.

jetzt wollte ich Fragen, falls ich das je hinbekomme, die Logik und Icons übernehmen darf.
Wollte das jetzt nicht einfach so "klauen" und lieber mal nachfragen. Die Statistikübermittlungen würde ich selbstverständlich auch mit implementieren.

Wie weit @andrgin hier Mitspracherecht weiß ich nicht, verlink ich trotzdem ^^

**Comment by dsiekiera** [comment]
Der @andrgin darf immer sagen was er denkt. Wir diskutieren sehr viel über mögliche Funktionen und wägen ab. Ich schätze seine Meinung.
Fals es dir gelingt, kannst du schalten und walten wie du möchtest. Bedenke jedoch das du nie versuchen solltest Daten zu manipulieren, davon distanziere ich mich ausdrücklich.

Ansonsten findest du mein Email-Adresse im Impressum von foe-rechner.de

**Comment by andrgin** [comment]
Was die Android Version angeht, so wäre ich sehr interessiert, was da raus kommt bzw. wie du das überhaupt vor hast und ich werde dich auch so gut es geht unterstützen.

Ansonsten schließe ich mich @dsiekiera an. Alles, was Daten des Spiels verändert, wird von Inno Games als Bot/Cheat eingestuft und damit will ich dann nichts mehr zu tun haben.

**Comment by Th3C0D3R** [comment]
natürlich hab ich nicht die absicht irgendwelche Dinge zu tun, die mir (oder anderen) in irgendeinerweise einen ungerechten Vorteil verschaffen.

Ich bin gerade dabei das Grundgerüst zu bauen, werd mich aber nochmal melden wenn ich genauseres weiß (auch ob es nun geht oder nicht).

**Comment by dsiekiera** [comment]
Vermutlich möchtest Du eine Android App basteln die sich "über" die FoE App legt. So eine "Display over App". 
Stellt sich die Frage ob das auf einem Handy noch bedienbar ist. 
Falls Du Fragen hast oder Hilfe brauchst, ich hab auch schon ein paar Apps geschrieben. Ggf, kann ich da auch helfen.

**Comment by Th3C0D3R** [comment]
richtig, ein Overlay. 
Das würde auch funktionieren, doch steh ich nun vor dem Problem das die Kommuniation zwischen der FoE App und deren Server verschlüsselt ist (also es werden die daten nicht so gesendet wie in der Browserversion) diese zu enschlüsseln und so würde, glaub ich, "illegal" sein.
Da man auf die App nicht anderweitig zugreifen kann und auch keine "Klartext" Daten verschickt, ist der Versuch hier glaub ich zu Ende ^^.

**Comment by SkateScout** [comment]
Um an die Daten zu kommen gibt es evtl die Möglichkeit eines Proxys.
Dieser setzt aber voraus das kein Zertifikat Pinning genutzt wird.
Oder als Root via tcpdump.

**Comment by dsiekiera** [comment]
Das ist schade zu hören. Dennoch danke für den Versuch @Th3C0D3R

**Comment by Th3C0D3R** [comment]
@SkateScout
Selbst dann müsste man noch die Daten entschlüsseln. 
Ich bin schon so weit gewesen das ich eine mögliche encrypt und decrypt Funktion hatte mit eventuell einem passenden Key, aber hab es nicht hinbekommen die Daten zu entschlüsseln. Da es dann aber nicht mehr legal wird, hab ich mich nicht weiter damit beschäftigt 😅

**Comment by SkateScout** [comment]
@Th3C0D3R die decodierung ist seit 3 Jahren samt Schlüssel offen gelegt.
Denke das Haupt Problem wird ein Mögliches Key-Pinning der Zertifikate sein.
Denn dann kannst du mit einer eigenen CA nicht mehr machen. Und wie gesagt
da auf dem Weg die Komplette Netzwerk Sicherheit untergraben wird würde ich
so einnen Proxy nicht Nutzen wollen.
https://github.com/m3talstorm/foe-decryption

**Comment by Th3C0D3R** [comment]
@SkateScout 
Auf die Repo bin ich auch aufmerksam geworden, aber das ist für die Flash/Bzw HTML Version. 
Die App verschlüsselt nochmal anders. Wie gesagt, hab eine Funktion samt Schlüssel gefunden die mir die Daten eventuelle entschlüsseln könnte, aber hat bis jetzt nicht funktioniert. Aber wie du bereits sagst, ist das Problem mit der Entschlüsselung gelöst, muss man immer noch die Hürde überwinden um an die Daten ranzukommen (die Apps haben nicht den Netzwerkzugriff wie Programme am PC) da wäre ein loopback VPN oder sowas nötig ^^

das was in der Repo ist, ist wenn man eigene, valide Anfragen an Inno schicken möchte, aber das würde als Bot/modifizierte Anfrage laufen.
