### ISSUE TITLE
Plünderanzeige - falsches Objekt

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#224]
Spielermeldung:
In der Plünderanzeige wird ein Objekt angezeigt, was nicht plünderbar ist:

![35](https://user-images.githubusercontent.com/50969949/70653229-5d843f00-1c54-11ea-8f6f-552f30aa5bd3.png)

**Comment by dsiekiera** [comment]
Eines der ganz wenigen LGs die nicht plünderbar sind.
Es steht bereits auf der Black-List und ab dem nächsten Fix nicht mehr auftauchen.
