### ISSUE TITLE
Eigenanteilsrechner funktioniert in zwei LG nicht

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#225]
In der AO sowie der Burg funktioniert der Eigenanteilsrechner nicht. Es wird immer das vorhergehende LG dargestellt.
Alle anderen LG werden korrekt angezeigt.
F12 / F5 / Chrome on/off, PC Neustart = keine Änderung

![37](https://user-images.githubusercontent.com/50969949/70653676-3bd78780-1c55-11ea-9dd3-0a5d836ef8f1.png)
![38](https://user-images.githubusercontent.com/50969949/70653677-3bd78780-1c55-11ea-831f-8f6ac19d245c.png)

**Comment by dsiekiera** [comment]
@Selene443Foe Das ist ein Bug in der BETA-Verrsion. Sehen nur wir ;-)
@andrgin hat eine Blätter funktion begonnen die noch nicht ganz fertig ist.

**Comment by SkateScout** [comment]
Kann bestätigen das es mit der Version "Latest commit 597b71a" von Andreas wieder Funktioniert.
