### ISSUE TITLE
[Feature Request] Plünderübersicht Filter

### ISSUE THREAD

**Issue by Nasljiana** [dsiekiera/foe-helfer-extension#226]
Wenn ich ein bestimmtes Gut (z.B. Stahlbeton) plündern möchte, wäre eine **Filtermöglichkeit** in der Plünderübersicht sehr hilfreich.

**Comment by andrgin** [comment]
Der Erntehelfer wurde entfernt: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115

**Comment by GeniusTimo** [comment]
Der Erntehelfer wurde mit dem letzten Update entfernt ([weitere Informationen](https://forum.foe-rechner.de/d/355)) 🔒
