### ISSUE TITLE
Vorschlag: Güter in der Produktionsübersicht nach Zeitaltern gruppieren/hervorheben

### ISSUE THREAD

**Issue by Niorian** [dsiekiera/foe-helfer-extension#228]
Hallo, 
Erstmal möchte ich euch ganz herzlich für eure Erweiterung danken, sie ist einfach nur super! 

Zu meinem Anliegen:
Wenn man viele Eventgebäude bzw. Legendäre Gebäude besitzt, wird die Güter-Produktionsübersicht mit den Gütern aus verschiedenen Zeitaltern etwas unübersichtlich. Siehe auch hier: meine Gebäude produzieren Güter aus den letzten 3 Zeitaltern und dem aktuellen... 

![Snip](https://user-images.githubusercontent.com/58807000/70695665-817e6980-1cc2-11ea-9b13-1a4164be9c7a.PNG)

Mein Vorschlag an dieser Stelle: vielleicht wäre es möglich, die Güter aus den gleichen Zeitaltern zusammen zu gruppieren, sei es mit einer Überschrift oder einem farbigen Rahmen/Hintergrund, so wie hier in dem Beispiel unten z.B:.? Dies würde die Lesbarkeit deutlich verbessern! Die Überschrift wäre wohl die einfachste Option, und dürfte ja wohl nicht zu viel Zeit in Anspruch nehmen... Vielen Dank :) 

![Snip2](https://user-images.githubusercontent.com/58807000/70696374-db336380-1cc3-11ea-9918-c19f08f85f78.png)

**Comment by dsiekiera** [comment]
Ist integriert und kommt in der nächsten Version:

![Bildschirmfoto_2019-12-15_13-51-56](https://user-images.githubusercontent.com/834814/70862864-18a52480-1f42-11ea-8953-207d8102e067.png)
