### ISSUE TITLE
Moppelstatistik

### ISSUE THREAD

**Issue by Silke67** [dsiekiera/foe-helfer-extension#229]
Hallo,

erstmal vielen Dank für die Mühe für dieses Tool.
Ich spiele auf 3 Welten, aber bei einer Welt steht meine Moppelstatistik immer noch auf Anfang November. Muss ich dort irgendetwas noch aktivieren?
Für einen Tipp wäre ich dankbar.
LG Silke

**Comment by andrgin** [comment]
Ich vermute einmal es geht um das Problem hier:
https://forum.foe-rechner.de/d/28-moppelaktivitat/4
