### ISSUE TITLE
Kostenrechner: Ich als Spieler möchte wissen wann ein Platz sicher ist um risikofrei einzahlen zu können

### ISSUE THREAD

**Issue by JHCD** [dsiekiera/foe-helfer-extension#23]
Ich als Spieler möchte wissen wann ein Platz sicher ist um risikofrei einzahlen zu können

1. Bitte in der Anzeige im Kostenrechner anzeigen, ob die Plätze bereits sicher sind. 
Dafür eingezahlte Plätze und Eigenanteil des Eigentümers mit berücksichtigen.

2. Anzeige, wie viel man einen Platz überzahlen müsste, damit er sicher ist. 
Gerade bei den hinteren Plätzen interessant.

**Comment by andrgin** [comment]
1.) Das macht der aktuelle Kostenrechner mittlerweile
2.) Macht der aktuelle Kostenrechner auch, wenn du in den Einstellungen die Anzeige von negativen Gewinnen aktivierst.
