### ISSUE TITLE
Kostenrechner Fenster verschwunden

### ISSUE THREAD

**Issue by Juegi** [dsiekiera/foe-helfer-extension#231]
Hallo,

Ich wollte die 2 Fenster vom Kostenrechner auf einen zweiten Monitor verschieben. Dachte das ist möglich und habe dadurch eine bessere Übersicht.

Leider waren beide Fenster danach weg.

Das Fenster mit den möglichen Einzahlungen, konnte ich wieder finden, in dem ich mit STRG und- das Fenster so weit verkleiner hatte bis bis es unten in der Ecke auftauchte.
Das Frenster Kostenrechner finde ich nicht mehr, habe schon alles mögliche probiert.
Tool neu instaliert, Chrome gelöscht und neu instaliert, das Fenster ist einfach weg.

Kann mir jemand damit helfen?

Gruß Juegi

**Comment by dsiekiera** [comment]
Hey Juegi,

schau mal dort nach:

![Bildschirmfoto 2019-12-15 um 19-41-55](https://user-images.githubusercontent.com/834814/70867927-4c507080-1f7b-11ea-9c2b-869c213e58df.png)
