### ISSUE TITLE
helper removes game scroll bars on small screens

### ISSUE THREAD

**Issue by Beelzebob6666** [dsiekiera/foe-helfer-extension#2364]
no helper - screen has scroll bars:
![image](https://user-images.githubusercontent.com/66054355/157057438-908ba7b8-9d22-4cab-bec5-816124e93dbb.png)

with helper - scroll bars are gone:
![image](https://user-images.githubusercontent.com/66054355/157057374-d0d851a2-9e0a-48a6-8558-17b52e50a88e.png)

**Comment by oesi03** [comment]
> in der boxes.css müsste zeile 18 raus.

führt zu weiteren Problemen beim zoomen/scrolle
![Screenshot (22)](https://user-images.githubusercontent.com/81358053/157564583-8481894c-42c1-4cbb-8f10-f930df023194.png)
n
