### ISSUE TITLE
Eigenanteilsrechner zeigt zweimal denselben Wert

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#237]
...ich weiß, dass ich dieses Bild / diese Diskussion schon mal gesehen hab. Ich finde da aber nicht mehr hin. Somit mache ich ein neues Ticket auf. Bitte löschen wenn das falsch ist.

![39](https://user-images.githubusercontent.com/50969949/71043255-5d8dae80-212e-11ea-88da-307ed7d0991a.png)

**Comment by andrgin** [comment]
Das war dieses Ticket: https://github.com/dsiekiera/foe-helfer-extension/issues/179

Kurzversion: Die Doku ist leider nicht mehr aktuell. Man muss bereits erfolgte externe Einzahlungen nicht mehr manuell erfassen. Das macht das Tool bereits automatisch.

**Comment by Selene443Foe** [comment]
Ja stimmt... das wird ja automatisch übernommen *ankopfklatsch
Wofür ist die Spalte Ext dann noch? Was gebe ich dort ein? 
Ark ist doch wenn der Platz anders belegt werden soll als Standard. Aber Ext, wenn Externe doch automatisch übernommen werden?

**Comment by andrgin** [comment]
Die Ext Spalte ist für alle Externen die noch nicht eingezahlt haben also z.B. wenn ich Güter gegen 200 FP verkaufen will und mir ansehen will was dabei raus kommt. Oder mir jemand FP schuldet die er mir zurückzahlen will.
