### ISSUE TITLE
Kostenrechner zeigt sporadisch nicht richtig an

### ISSUE THREAD

**Issue by mordillo666** [dsiekiera/foe-helfer-extension#239]
Seit dem Update gestern, zeigt der Kostenrechner immer mal wieder anders an.
Einmal war der 5. Platz mit 10 safe und 10 bis zum Leveln, im Kostenrechner wurde er grün (5) angezeigt mit -6 Gewinn.
Dann wurden mir nach einer Neuinstallation des FoE Rechners freie Plätze mit Negativgewinn ausgegraut angezeigt, so als ob sie safe wären.
Auch waren alle LGs im Fenster mögliche Einzahlungen gelb, selbst die, wo Gewinn zu machen war.
Nachdem ich zwischen meinen Welten mal hin und her gewechselt habe, zeigt er anscheinend wieder richtig an. Mal schauen wie lange...

**Comment by andrgin** [comment]
Kannst du da einen Screenshot davon machen?

**Comment by mordillo666** [comment]
![Rechenfehler](https://user-images.githubusercontent.com/59010411/71084323-4afa9000-2195-11ea-82eb-4317f44c7eaf.jpg)

**Comment by mordillo666** [comment]
![Rechenfehler3](https://user-images.githubusercontent.com/59010411/71084903-93ff1400-2196-11ea-9dc5-afd86ff5b48a.jpg)

**Comment by Th3C0D3R** [comment]
Also in Bild 2 sieht alles korrekt aus, man kann kein Platz belegen ohne Verlust zu machen.

Aber Bild 1 zeigt wahrlich ein Fehler.

**Comment by mordillo666** [comment]
In Bild zwei sind die Berechnungen richtig, das stimmt. Allerdings dürften die Plätze, die trotz Verlust belegt werden können, nicht ausgegraut sein, sondern "aktiv" sein, wie hier:
![richtig](https://user-images.githubusercontent.com/59010411/71091806-278c1100-21a6-11ea-9283-500204e91210.jpg)

**Comment by Th3C0D3R** [comment]
ich vermute weil die Plätze noch frei sind und nicht belegt (also die Tatsache das sie belegt sind macht sie, denk ich, grau

**Comment by mordillo666** [comment]
Das war vor dem Update aber nicht so. Und ist der Übersicht auch nicht förderlich. Außerdem wird es im ersten Bild auch anders angezeigt.

**Comment by mordillo666** [comment]
Hier nochmal ein Bild, wo die Einzahlungen anscheinend garnicht mitgerechnet wurden:
![falsch](https://user-images.githubusercontent.com/59010411/71167873-d3406a00-2255-11ea-87dc-ebdb3d8d5f4e.jpg)

**Comment by andrgin** [comment]
Es gibt beim Kostenrechner bei der Hintergrundfarbe generell einige Bugs. In den meisten Fällen betreffen diese nur die Unterscheidung zwischen roten und grauen Zeilen. In einigen Fällen jedoch auch die Unterscheidung grün/rot. Diese werden voraussichtlich im übernächsten Update behoben, da es hier eine größeres Redesign der Rechenlogik notwendig ist und einige Sonderfälle zu testen sind.
