### ISSUE TITLE
Anzeige der Güter für die nächste Erweiterung im Aussenposten

### ISSUE THREAD

**Issue by krupp58** [dsiekiera/foe-helfer-extension#240]
Ich fände es viel besser, wenn über der schwarzen Zeile mit Gebäude und Gütern, also vor der Anzeige der Kupfermünzen , über den Gütern die **Anzahl der jeweils benötigten Güter für die nächste Erweiterung** gezeigt würden.
Das Fenster dient ja dazu eine Entscheidung zu treffen, was als nächstes Produziert wird, da stellt sich halt immer auch die Frage: Erweiterung oder nicht !
Von daher wäre es auch schön in diesem Fenster die **momentane Münzproduktion
** ablesen zu können (für 4/8 Std). So kann man auch sehen ob man nicht doch lieber noch das Einkommen ausbaut.
Wie viele Erweiterungen noch verfügbar sind ist dahingegen ziemlich uninteressant. Entweder es gibt noch welche oder eben nicht (was man ja auch an dieser Art der Anzeige  ablesen kann)
Also etwa so :
![Foe-Helfer-Aussenposten](https://user-images.githubusercontent.com/59014336/71079449-96a83c00-218b-11ea-8c3c-1ebfa992e86e.png)
greetz

_Originally posted by @krupp58 in https://github.com/dsiekiera/foe-helfer-extension/issues/136#issuecomment-566979007_

**Comment by andrgin** [comment]
Den Wunsch hatten wir schon einmal. Aktuell haben wir leider eine Mnenge anderer Baustellen. Daher kann ich derzeit nicht sagen ob und wann das kommt.

**Comment by someone97563** [comment]
Im weiteren siehe #136
