### ISSUE TITLE
Endless loading beim Laden der Gildengefechte bei geöffneter Infobox

### ISSUE THREAD

**Issue by Schlemmermeyer** [dsiekiera/foe-helfer-extension#241]
Bei geöffneter Infobox endet das Starten der Gildengefechte in Endless Loading.
Nach Schließen der Infobox selbes Verhalten.
Heilung: Reload FOE
Reproduzierbar: ja

Version 2.3.14 (deutsch) + Chrome Version 79.0.3945.79 (Offizieller Build) (64-Bit)

**Comment by andrgin** [comment]
Gefixed in Version 2.3.15
