### ISSUE TITLE
Verhandlungsassistent: Fenster merkt sich die Koordinaten nicht

### ISSUE THREAD

**Issue by Andi47** [dsiekiera/foe-helfer-extension#242]
Wenn man z.B. bei den Gildengefechten eine Verhandlung startet, öffnet sich der Verhandlungsassistent automatisch, das Fenster merkt sich allerdings seine letzte Position nicht:
1.) GG öffnen und einen Sektor wählen
2.) Verhandlung starten --> Assistent öffnet sich
3.) Fenster des Verhandlungsassistenten ein Stück nach oben schieben
4.) Verhandlung gemäß Assistenten durchführen
5.) Nach erfolgreichem Ende der Verhandlung schließt sich das Fenster des Assistenten
6.) nächste Verhandlung starten
Beobachtet: Fenster des Assistenten öffnet sich an der Standardposition
Erwartet: Fenster des Assistenten sollte sich dort öffnen, wo ich es bei der vorhergehenden Verhandlung hingeschoben habe.

**Comment by andrgin** [comment]
Das ist so geplant, dass dieses an einer fixen Position sitzt sodass die Vorschläge über den jeweiligen Slots erscheinen, man aber noch an den schließen Button kommt. Dass man es überhaupt verschieben kann ist nur, falls es doch einmal im Weg sein sollte.
