### ISSUE TITLE
Optimale Flächennutzung

### ISSUE THREAD

**Issue by aberlechristian** [dsiekiera/foe-helfer-extension#244]
Ich bin schon seit längerer Zeit auf der Suche nach einem Tool welches die Gebäudeplatzierung optimiert, bin aber leider bisher nicht fündig geworden. Es wäre super wenn der FOE Helfer das integrieren könnte. Sprich wenn er die aktuell verfügbare / freigeschaltete Fläche nimmer und dann berechnet wie die aktuell platzierten Gebäude optimal angeordnet werden sollten um möglichst wenig "Verschnitt" zu haben auch unter Berücksichtigung der Straßenanbindungen, sodass man im Optimalfall danach etwas mehr Platz hat um ein zusätzliches Gebäude setzen zu können.

**Comment by someone97563** [comment]
Wenn uns niemand einen guten Algorithmus dafür liefert, wird das vermutlich erstmal nichts. Eine Optimale Belegung zu finden ist nicht so einfach.
