### ISSUE TITLE
Güterproduktionsübersicht

### ISSUE THREAD

**Issue by Darkknightnr1** [dsiekiera/foe-helfer-extension#246]
Hi
ein Wunsch wäre das auch alle Güter die Produziert werden an einem Tag angezeigt werden , momentan zeigt der nur 4 Güter je Zeitalter an aber die Gebäude bringen definitiv 5 Güter je Zeitalter.

Zb.: Der Winterdom Stufe 12 Moderne bringt 15 Güter also 3 Je Gut 

3 Stahlbeton
3 Aromastoffe
3 Luxusmaterialien
3 Fertiggerichte
3 Verpackungen

und diese 3 Verpackungen zeigt er net an und das macht er irgendwie mit jedem Zeitalter...

Liebe Grüße Darki

**Comment by Th3C0D3R** [comment]
Kannst du ein Screenshot hinzufügen?
Bei mir werden alle 5 Güter angezeigt die zb beim Schlittenbauer produziert werden

**Comment by Darkknightnr1** [comment]
Da sieht man das nicht alles angezeigt wird ... 

http://prntscr.com/qddkjl

auf ner Nebenwelt wird alles gezeigt aber da bin ich auch erst frühes Mittelalter

http://prntscr.com/qddlci

**Comment by Th3C0D3R** [comment]
ich denk das hängt mit der länge der Güternamen zusammen, dadruch wird das eine Gut in die 2. Zeile gesetzt und das 5. Gut "verschwindet", ist aber noch da (nur unter dem 4. Gut) ^^

**Comment by Darkknightnr1** [comment]
ah ok supi das schon komisch nen bissel ich meine die Güter kommen ja aber fehlen in der Übersicht :-)

wäre cool wenn das klappt das die komplett angezeigt werden 
danke auch für die schnelle Bearbeitung ;-)

**Comment by Th3C0D3R** [comment]
@Darkknightnr1 muss paar Fragen stellen
hast du aktuell Verpackungen auf Lager?

**Comment by Th3C0D3R** [comment]
https://github.com/dsiekiera/foe-helfer-extension/blob/719b83e4b18e4f6e8f64177559c11f03c9015034/js/web/productions.js#L75
wenn das Gut in der Schleife übersprungen wird, kann es nicht angezeigt werden

**Comment by Darkknightnr1** [comment]
wie in der schleife übersprungen ?

**Comment by Darkknightnr1** [comment]
mit den schleifenquests ?

**Comment by Th3C0D3R** [comment]
ne ne alles gut 😄 ist ein Fehler von unserer Seite, wird mit dem nächsten Update behoben sein

**Comment by Darkknightnr1** [comment]
Ah Supi coole Sache das ^^

vielen dank

**Comment by Th3C0D3R** [comment]
@andrgin du bist da ja grad dran ^^

**Comment by andrgin** [comment]
1.) packaging ist der interne Name für die Kategorie "Güter". Das hat mit dem Gut Verpackungen nichts zu tun.

2.) Kann jemand aus anderen Zeitaltern das Problem reproduzieren? Bei mir in der virtuellen Zukunft wird alles richtig dargestellt.

**Comment by andrgin** [comment]
Ich muss mich korrigieren. Es hatte doch mit dem Gut "packaging" zu tun bzw. einer Sonderbehandlung, da dieses den gleichen Namen hat wie die Güterkategorie.
Sollte im beta branch gefixed sein.

**Comment by andrgin** [comment]
Gefixed mit 2.3.15
