### ISSUE TITLE
[BUG] Eigenanteilsrechner erhält falscher Spielername

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#248]
Forumsbeitrag: [Eigenanteilsrechner erhhält falscher Spielername](https://forum.foe-rechner.de/d/36-eigenanteilsrechner-falscher-spielername)

Wenn man den Account wechselt und der LocalStorage noch befüllt ist, wird dieser Name anstelle des neuen genommen.
https://github.com/dsiekiera/foe-helfer-extension/blob/719b83e4b18e4f6e8f64177559c11f03c9015034/js/web/part-calc.js#L435-L436

https://github.com/dsiekiera/foe-helfer-extension/blob/719b83e4b18e4f6e8f64177559c11f03c9015034/js/web/part-calc.js#L442

**Lösung: Wenn der `PlayerCopyName` vom `current_player_name` abweicht, soll der `current_player_name` genommen werden**

**Comment by dsiekiera** [comment]
Das ist glaube ich noch nicht die Lösung. Wir in unserer Gilde nutzen verkürzte Namen in den Ketten. Das sicherste ist vor den current_player_name die Spieler ID zu setzen.

So etwas in der Art, dann könnten theor. belibig viele Spieler an einem Gerät spielen:
```
 n = localStorage.getItem(extPlayerID + 'PlayerCopyName'), 
 m = localStorage.getItem(extPlayerID + 'current_player_name'), 
```

**Comment by Th3C0D3R** [comment]
Stimmt, das wäre naturgemäß viel besser 😅👍🏻

**Comment by Th3C0D3R** [comment]
ist mit [Externe Spieler ID hinzugefügt](https://github.com/dsiekiera/foe-helfer-extension/commit/bc0f1458f50cfc986fcdca1531d0841009237c31)
behoben
