### ISSUE TITLE
Plündern: Fenster öffnet sich nicht bzw. zeigt nichts an

### ISSUE THREAD

**Issue by Tsching-Foe** [dsiekiera/foe-helfer-extension#255]
Ich spiele FoE auf mehreren Welten und habe im Chrome verschiedene Tabs geöffnet. Manchmal geht das Plünderfenster auf, manchmal nicht.
Teilweise kann ich scrollen, das sehe ich aber nicht. Ich hätte dafür gerne eine Anzeige.
Toll wäre auch, wenn wenn es nichts zu plündern gibt, dass das einfach im Fenster steht. Dann wüsste ich, dass es gerade kein Fehler ist, dass das Fenster nicht da ist.
Aktuell könnte ich etwas plündern, das Fenster zeigt mir aber nichts an.
Und noch toller wäre es, wenn die wertvollen Gebäude oben stehen. Also die mit FP, dann die Güter und am Ende erst Münzen und Vorräte.

**Comment by andrgin** [comment]
Welches Gebäude war denn plünderbar?

**Comment by Tsching-Foe** [comment]
Nur die Ziegeldachhäuser. Aber es scheint so, als ob es nur im ersten Tab aufgeht, in den weiteren Tabs dann eben nicht mehr.

**Comment by andrgin** [comment]
Also ich kann das Problem leider bei mir nicht reproduzieren. Bei mir gehen bei beiden Tabs die Fenster auf, wenn nichts zu plündern da ist.
Kann es sein, dass du auf der anderen Welt die Nachbarschaftsernte in den Einstellungen deaktiviert hast?

**Comment by Tsching-Foe** [comment]
Ist überall an. Ich habe jetzt alle Einstellungen mal gleich gesetzt und behalte es im Auge. Das Fenster sollte also immer beim Besuch eines anderen Spielers aufgehen, egal ob er etwas zu plündern hat oder nicht?

**Comment by dsiekiera** [comment]
Nein, noch nicht. Es geht nur auf, wenn etwas zu holen ist.
