### ISSUE TITLE
Visual cues for fighting window

### ISSUE THREAD

**Issue by Valutin** [dsiekiera/foe-helfer-extension#2550]
Well. I know that Inno does not allow you to auto click, but would an visual cue authorized? Window pop up in between auto-fight takes a litlle bit of time to load, would it be possible to have a red square indicating where Auto-fight/Ok button will be as an overlay?
How legal would that be and if ok, can it be implemented? 
This way I can move the mouse to the right area before the windows pop up. Sometimes, it's frustrating to have to move the cursor because we are off by 1 or 2 pixels.
Maybe you had that in the past in which case, I am sorry to suggest something that was already suggested.
Thanks

**Comment by outoftheline** [comment]
I understand the request as I (used to) play a ton of GvG, but I think it would be bad for the game, because the servers are quite weak and laggy in GvG already. If more people would do fast fighting, it would only get worse.

**Comment by Valutin** [comment]
Actually.. the worse is on PVP reset... Monday morning for me (GBG night shift player here). It makes everything painful and completely break the pace.

**Comment by Beelzebob6666** [comment]
I was tempted a couple times already to write a script that positions the mouse where it needs to go to hit the button... so no "clicks are automated", but still felt cheaty and I opted against it - also I hope that the siege nerve comes out soon, so that there will be no need anymore for such shenanigans

**Comment by Valutin** [comment]
Well.. Inno probably wants to milk fighters as much as possible to get us buy their choclateries and treasure chest add-on, and then, make fighting moot. 
Going back to the original inquiry, I don't mind moving the mouse.. even clicking on it.. I just find it somewhat bad development to have the UI shift because score are getting reset for 8 hours by deleting the whole ladder.. they could simply just leave the ladder blank and keep the windows at the same position as usual. I am quite used to it.
Anyhow, they'll.. probably fix the game one way or the other.
