### ISSUE TITLE
Verhandlungsassistent

### ISSUE THREAD

**Issue by hhpc1957** [dsiekiera/foe-helfer-extension#256]
Verhandlungsassistent zeigt 4 Versuch nicht an

**Comment by andrgin** [comment]
Hast du den Tavernen Badge deaktiviert? Falls ja, so wird der gekaufte 4. Zug in der Taverne nicht erkannt.

**Comment by hhpc1957** [comment]
Er wird erkannt ist auch da funktioniert auch nur im Verhandlungsassistent werden nur 3 angezeigt
