### ISSUE TITLE
Homepage zeigt Beta-Account nicht an

### ISSUE THREAD

**Issue by Andi47** [dsiekiera/foe-helfer-extension#259]
Ich spiele aktuell in Houndsmoor (de8) und am Betaserver (zz1) jeweils mit dem selben Benutzernamen (Andi47), und habe auch noch eine alte Stadt in Eldenborough (de5), die ich nicht mehr bespiele.

Wenn ich auf der Homepage (foe-rechner/startpage) den Pfeil bei der Weltenauswahl anklicke, werden mir Houndsmoor und Eldenborough angezeigt - der Betaserver fehlt. (und gerade für Beta würde ich die Homepage aktuell zum Bereinigen meiner Freundesliste brauchen, da ich meine Schreine nicht mehr alle gemoppelt bekomme)

Wie füge ich hier Bilder ein? z.B. dieses: https://www.dropbox.com/s/880vgawd0mku7z8/Extension_Weltenauswahl.jpg

**Comment by dsiekiera** [comment]
Ja, das weiß ich. 
Alle Welten, außer der Beta-Server, werden mit deiner PlayerID verknüft. Der Beta-Server benutzt aber eine neu erstellte Player-ID, dort ist wiederrum nur der Name gleich. 

Es gibt dazu schon eine Frage im Forum: https://forum.foe-rechner.de/d/24-moppelaktivitat-der-freunde-gilde-nachbarn-aus-ereignisubersicht/11

**Comment by dsiekiera** [comment]
Ist verbaut. Dazu bitte auf foe-rechner.de neu einloggen
