### ISSUE TITLE
Kostenrechner Rathaus

### ISSUE THREAD

**Issue by Lagewegerin** [dsiekiera/foe-helfer-extension#26]
Wenn ich den Rechner "im" Rathaus benutze, zeigt er nicht den Richtigen Eigner und meistens nicht das Richtige LG und auch falsche Ergebnisse. 
Außerdem rechnet er die schon von mir selbst gedropten FP mit. Es kommt so also zu einem falsch positiven Ergebnis und man kann, wenn man es nicht selbst dazu rechnet natürlich noch überboten werden.

**Comment by dsiekiera** [comment]
Hallo Lagewegerin,

wie muss ich das verstehen "im" Rathaus?

**Comment by Lagewegerin** [comment]
im rathaus über die liste der legendären gebäude, also da wo alle von dir belegten und noch nicht gelevelten lgs aufgeführt sind.
manchmal legt man einfach einen fp ab um z.b. bei ex-nachbarn nochmal helfen zu können. das hat auch zur folge das die liste der invests/gewinne nicht ansatzweise stimmt. man müsste diese lgs vielleicht beim zusammenrechnen "missachten" können.
ausserdem fiel mir gerade auf, daß das erntehelfer fenster nicht bei jedem nachbarn angezeigt wird. woran kann das denn liegen?

...uuuuund, ich hab das helferlein jetzt seit 3 oder 4 tagen und bin total begeistert, dickes fettes danke und zwei enthusiastisch nach oben erhobene daumen! alleine die gesparte zeit is schon der hammer. richtig gute sache und ich werde fleißig melden und kommentieren  :-)

**Comment by andrgin** [comment]
Ist mittlerweile gefixed
