### ISSUE TITLE
Eroberungskostenrechner fehlerhaft

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#260]
Beobachte es seit 2 Tagen.
Gehe auf einen Sektor. Sehe was fehlt.
Erstelle Handel die direkt angenommen werden.
Gehe auf die Karte zurück öffne den Sektor udn den Rechner.
Güter fehlen angeblich immernoch.
Spiel neue laden.
Alles aktuell

**Comment by Th3C0D3R** [comment]
Aktuell werden Handelsangebote die du einstellst und andere annehmen nicht in der Güterliste verrechnet.
Ich werd das ganze anpassen und beim nächsten Update wird es dann up-to-Date sein 👍🏻

**Comment by Th3C0D3R** [comment]
Aus privaten Gründen leider doch erst beim Übernächsten Update

**Comment by Th3C0D3R** [comment]
Ist im nächsten Update behoben 👍
