### ISSUE TITLE
Kostenrechner 2. Stadt fehlerhaft

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#261]
Auf Tuulech ist alles ok
Auf Langendorn habe ich eine 2. (neue) Stadt nun.
Aber hier stimmt etwas nicht.
siehe screenshot...
https://www.bilder-upload.eu/bild-0e0d4c-1577283212.png.html

**Comment by andrgin** [comment]
Der Bug dass die Hintergrundfarbe nicht immer stimmt ist schon bekannt. Wichtig ist die Spalte "Gewinn".

**Comment by andrgin** [comment]
Es gibt beim Kostenrechner bei der Hintergrundfarbe generell einige Bugs. In den meisten Fällen betreffen diese nur die Unterscheidung zwischen roten und grauen Zeilen. In einigen Fällen jedoch auch die Unterscheidung grün/rot. Diese werden voraussichtlich im übernächsten Update behoben, da es hier eine größeres Redesign der Rechenlogik notwendig ist und einige Sonderfälle zu testen sind.
