### ISSUE TITLE
Infobox - Chatüberschrift fehlt

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#262]
In der Infobox fehlt in einem Chat die Überschrift und damit auch der Name des Erstellers.
Eine Änderung des Chatnamens zu einer vergleichbaren Überschrift brachte keine Veränderung.

![42](https://user-images.githubusercontent.com/50969949/71450230-394d5580-275e-11ea-967c-2e54f464ce18.png)
![43](https://user-images.githubusercontent.com/50969949/71450231-3f433680-275e-11ea-80d6-06522750b9fa.png)

**Comment by dsiekiera** [comment]
Ist mit dem nächsten Update behoben
