### ISSUE TITLE
Verhandlungsassistent erkennt Versuch 4 nicht

### ISSUE THREAD

**Issue by SamBrePy** [dsiekiera/foe-helfer-extension#268]
In 3 von 4 Städten erkennt bei mir der Verhandlungsassistent den gekauften 4ten Versuch in der GEX nicht.
Nur in meiner kleinsten Stadt klappt es super.
Was kann ich tun?

Versucht bisher: 
Relog
Reboot
Cache löschen
Ausschalten/Einschalten der Funktion.
Einschalten/Ausschalten Tavernen-Badge.

**Comment by andrgin** [comment]
In der aktuellen Version muss der Tavern Badge aktiviert sein. Achtung: Die Einstellungen gelten pro Welt. Du musst ihn also in allen 4 Welten aktivieren.

Im nächsten Update, das in den nächsten Tagen raus kommt geht es dann auch ohne Tavernen Badge.

**Comment by andrgin** [comment]
Gefixt mit Update 2.3.15
