### ISSUE TITLE
Anzeige der eigenen Stadt funktioniert nicht korrekt

### ISSUE THREAD

**Issue by Kaye68** [dsiekiera/foe-helfer-extension#269]
Ich habe gerade versucht nachzusehen, welcher meiner Leuchttürme 20 FP produziert, um meine blaue Galaxie-Versuche optimal einzusetzen.
Leider poppt aber immer wieder das Fenster der Nachbarstadt auf, die ich zuletzt "besucht" habe. Ich muss erst den Browser schließen und das Spiel danach neu starten, bevor ich meine eigene Stadt in der Vorschau dargestellt bekomme.

**Comment by dsiekiera** [comment]
Im nächsten Update gefixt
