### ISSUE TITLE
Fenster zu hoch geschoben

### ISSUE THREAD

**Issue by Patrick-7** [dsiekiera/foe-helfer-extension#27]
Hi, 
ich habe das Fenster der Nachbarschafts-Ernte versehentlich zu weit nach oben verschoben, wodurch der Teil, auf dem man es wieder verschieben könnte unter Adresszeile und Lesezeichen-Leiste ist. Jetzt kann ich das Teil nicht mehr schließen oder zurück verschieben. Auch Ändern der Auflösung, zoomen oder sonstiges hat leider nichts gebracht. 
Gibt es die Möglichkeit das ganze anders zu verschieben? Und falls das nicht möglich ist, kann dann ein kleines Feld am unteren Rand hinzu gefügt werden, wodurch ich das wieder verschieben kann?
Vielen Dank & mit freundlichen Grüßen,
Patrick

**Comment by dsiekiera** [comment]
Hey Patrick,
das ist recht einfach zu fixen:
- Öffne im Spiel mit der Taste "F12" die Konsole des Browsers.
- Wähle im Reiter "Application", dann links unter "Local Storage" die URL des Spieles
- Gib im Suchfeld auf der rechten Seite "Result" ein und ändere unten die Werte oder löschen den Eintrag (rote Box)

Hier noch mal ein Foto dazu:
![Screenshot Resultbox Coords](https://i.imgur.com/ZsnEaBe.png)

**Comment by kleopatra** [comment]
funktioniert, danke :)
