### ISSUE TITLE
Kostenrechner 2. Fenster fehlt

### ISSUE THREAD

**Issue by dirk-der-ripper** [dsiekiera/foe-helfer-extension#277]
Seit gestern fehlt das 2. Fenster wo immer die LG´s drin stehen die überhaupt in Frage kommen.

**Comment by andrgin** [comment]
Hast du den Vorab Scan der LGs in der Übersicht aktiviert?

**Comment by dirk-der-ripper** [comment]
Ja das hat sich von alleine deaktiviert. Jetzt geht es wieder
