### ISSUE TITLE
Produktionsübersicht sortieren

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#278]
Moin,
die Produktionsübersicht finde ich unglaublich praktisch. Eine kleine Verbesserung möchte ich trotzdem vorschlagen, nämlich eine Sortierung.
Aktuell werden auf der Seite der Güter (vorletzter Tab) die Güter in ihre Zeitalter aufgeteilt angezeigt, soweit so gut. Aber es gibt keine Sortierung.
Bei mir kommt (von oben gesehen) z.B. heute:
Ozeanische Zukunft, Arktische Zukunft, Morgen, Zukunft, Ohne Zeitalter. 
Das ist weder alphabetisch sortiert noch nach Zeitaltern, und auch die Güter innerhalb der Zeitalter folgen keinem Muster :)

Ich möchte daher vorschlagen, die Zeitalter nach Zeitalter zu sortieren und innerhalb der Zeitalter die Güter alphabetisch. Und "Ohne Zeitalter" gerne ganz nach oben, beinhaltet es doch hauptsächlich die heiß begehrten Diamanten :)

P.S. Promethium und Orichalcum tauchen da nicht auf, ich vermute mal, das gehört so?

**Comment by andrgin** [comment]
Ja macht Sinn mit der Sortierung. Hatte ich auch schon überlegt.
Was Promethium und Orichalchum angejt die bekommt man doch nur durch die Häfen. Mal sehen wie man die abfragen kann.
