### ISSUE TITLE
Punkteübersicht bei der GG

### ISSUE THREAD

**Issue by Platthammer** [dsiekiera/foe-helfer-extension#280]
Ich würde mir eine Übersicht wünschen wo man zu jeder Zeit auf dem GG Feld den derzeitigen Punktegewinn der zu sehenden Gilden sieht. Sollte dazu dienen um zu sehen wieviel  Punkte mehr man stündlich haben muß um auf den nächsten Platz zu kommen
Vielen Dank für dieses geniale Tool !

Grüße Platthammer

**Comment by dsiekiera** [comment]
Ist das nicht diese normale Übersicht?

![Bildschirmfoto 2020-01-10 um 16-09-48](https://user-images.githubusercontent.com/834814/72163197-ad753380-33c3-11ea-974f-20889ef0d449.png)

**Comment by Platthammer** [comment]
Ja Entschuldigung, da war ich etwas zu voreilig !
Vielen Dank trotzdem und ein dickes Lob an eure Arbeit ! Sehr schönes Tool !!!
