### ISSUE TITLE
Bug: FoE hängt sich auf

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#281]
Moin,

ein Problem, das ich nun die letzten Tage reproduzieren konnte, ist mir aufgefallen:

Wenn ich die Info Box aufhabe, und mit aktiver Info Box die Gildengefechte öffne, komme ich danach nicht mehr zurück. Wenn ich dann via "Zurück zur Stadt" aus der GG Map raus will, hängt sich FoE vollständig auf und muss neu gestartet werden.

**Comment by mordillo666** [comment]
Habe es gerade mal bei mir getestet, ich komme erst garnicht in die Gefechte rein, der Ladebalken bleibt stehen. Ich muss die Stadt dann neu laden.

**Comment by Schlemmermeyer** [comment]
Dürfte ein Duplikat zu #241 sein.

**Comment by andrgin** [comment]
Gefixed mit Update 2.3.15
