### ISSUE TITLE
Cost Calculator RQ/loop option

### ISSUE THREAD

**Issue by ljettinger** [dsiekiera/foe-helfer-extension#282]
I understand that you would have to open the quests tab to populate the data, and I'm not sure for how long that data can be saved and still trusted, but would it be possible to add an option to the Cost Calculator so that it could include the amount of FP left when looping the FP recurring quest?? To have that show up in the calculator tab would really make it nice and save the time clicking from the GB to the quest and back just to see how many more are needed for that particular quest...

**Comment by Th3C0D3R** [comment]
Its indeed possible, how it's going to be accomplished , we have to look
