### ISSUE TITLE
Cost Calculator Box not wide enough

### ISSUE THREAD

**Issue by ljettinger** [dsiekiera/foe-helfer-extension#283]
The Cost Calculator is showing a partial column on the right side that I'm guessing is "Cost", but it's cut off, at least in the english version, and is only showing "Co" and the first 2 numbers below that...
![chrome_kIBCaKOFk4](https://user-images.githubusercontent.com/18238040/71741473-fdd11c00-2e2c-11ea-9b90-67072c898805.png)

**Comment by dsiekiera** [comment]
Fixed in next Version.
