### ISSUE TITLE
Fehler beim Laden der Module in der Beta

### ISSUE THREAD

**Issue by SkateScout** [dsiekiera/foe-helfer-extension#284]
Mit diesem Fix in injects.js wird zuerst main geladen und danach die Restlichen Scripte.
Ansonsten kann es zu dem Fehler FoeProxy undefined kommen.
``` Javascript
function checkForjQuery(){
	if (typeof jQuery === undefined){
		requestIdleCallback(checkForjQuery);
	} else {
		InjectCode();
	}
}

function checkForDOM() {
	if (document.body && document.head) {
		var ant = document.createElement('script');
		ant.src = chrome.extension.getURL('js/web/_main/js/_main.js?v=' + v);
		ant.id = 'main-script';
		ant.onload = function(){ 
			this.remove(); 
			requestIdleCallback(checkForjQuery);
		}; 
		document.head.prepend(ant);
	} else {
		requestIdleCallback(checkForDOM);
	}
}
requestIdleCallback(checkForDOM);
```

**Comment by SkateScout** [comment]
Damit wird auch der Fehler des fehlenden HTML vermieden.
Die Modul Idee ist gut aber es muss eine Ladereihenfolge beachtet werden.

function loadSerial(todos, next) {
	if(todos.length > 0) {
		var m = todos.shift();
		var ant = document.createElement('script');
		ant.src = chrome.extension.getURL('js/web/'+m+'/js/'+m+'.js?v=' + v);
		ant.onload = function(){ 
			this.remove(); 
			requestIdleCallback(()=>{loadSerial(todos,next)});
			}; 
		document.head.prepend(ant);
	} else {
		requestIdleCallback(next);
	}
}

function checkForDOM() {
	if (document.body && document.head) {
		loadSerial(['_main','helper'],checkForjQuery);
	} else {
		requestIdleCallback(checkForDOM);
	}
}

**Comment by Th3C0D3R** [comment]
Danke, aber wir konnten den Fehler leider nicht feststellen

**Comment by SkateScout** [comment]
Fehler tritt mit Cache sporadisch auf bei Disable Cache fast nie. Das Problem am Orginal Script ist
das es alle Module hintereinander einfügt. Chrome aber diese scheinbar "Out of order" lädt.
Durch den Patch wird sichergestellt das die "Klassen" HTML + FoeProxy verfügbar sind wenn die anderen Module sich dort Registieren bzw die CSS laden. Auf den Fehler bin ich über die Console gekommen das dort wenn das Plugin nicht ging der Fehler stand HTML bzw FoEproxy not found.

p.s. Nutze die Entpacke Version, kann es daran liegen ?

**Comment by Th3C0D3R** [comment]
Ich nutze auch die entpackte Version

**Comment by dsiekiera** [comment]
Wir haben eine neue mechanik verbaut damit auch der Firefox korrekt läd.
