### ISSUE TITLE
Kostenrechner zeigt sicher Plätze rot

### ISSUE THREAD

**Issue by marco-wirth** [dsiekiera/foe-helfer-extension#287]
Hallo,

mir ist jetzt ein paar mal aufgefallen, das mir sichere Plätze rot angezeigt werden. Gerade hatte ich wieder den Fall, das ich bei 90% 48FP einzahlen musste und es waren genau noch 96FP im Gebäude offen. Somit war ich safe.
Warum ist das so? Es wäre wirklich schön, wenn man direkt sehen würde das der Platz safe ist. So bleibt immer ein Zweifel und man rechnet nach.

Ist da was zu machen?

**Comment by andrgin** [comment]
Ist bereits bekannt und in Bearbeitung.
