### ISSUE TITLE
Nachbarschafts Ernte

### ISSUE THREAD

**Issue by Franksnorre** [dsiekiera/foe-helfer-extension#288]
Hallo,
ich habe mein Fenster zur Nachbarschafts Ernte nach unten aus dem Bild geschoben und bekomme es jetzt nicht mehr zurück.
Habe das addon bereits deinstalliert und neu aufgespielt, leider ohne Ergebnis. Hat jemand einen Tip für mich?

**Comment by Franksnorre** [comment]
Hier mal ein Bild:

![Unbenannt](https://user-images.githubusercontent.com/59539967/71785025-1f7ffe00-2ffb-11ea-94ac-3bb3fca43d2b.png)

**Comment by dsiekiera** [comment]
Geh links im Menü in die Einstellungen und such den einzigen Button darin...
