### ISSUE TITLE
Investitionsübersicht - Arche-Bonus in Zehntel-Prozent einstellbar

### ISSUE THREAD

**Issue by thorstenkranz** [dsiekiera/foe-helfer-extension#29]
Ich habe eine 84er Arche - und damit einen Bonus von 90,4 Prozent. In der Investitions-Übersicht kann man aber nur 90,0 oder 90,5 einstellen, die Schrittweise des Controls ist 0,5 Prozent. Gerade oberhalb von Level 80 braucht man aber Schritte von 0,1%.

**Comment by thorstenkranz** [comment]
Kann ich hier irgendwie unterstützen? Soweit ich sehe ist die Website nicht auf github, sonst könnte ich einen Pull Request bauen.

**Comment by dsiekiera** [comment]
Hey Thorsten,

ich hab das schon integriert. Es kommt in Kürze mit einem Update:
```javascript
h.push('<p class="costFactorWrapper">Arche Bonus - <input type="number" id="costFactor" step="'+ (Calculator.ArcBonus > 80 ? '0.1' : '0.5') +'" min="12" max="200" value="'+ Calculator.ArcBonus +'">%</p>');```

**Comment by thorstenkranz** [comment]
Super, danke
