### ISSUE TITLE
Eigenanteilrechner funktioniert nicht mehr

### ISSUE THREAD

**Issue by dirk-der-ripper** [dsiekiera/foe-helfer-extension#293]
Hallo vor 20 min lief noch alles wunderbar, jetzt bleibt das Fenster für den Eigenanteilrechner leer und der ganze FOE Helfer wird nicht mehr in dem kurzen Fenster mit den beiden PFeilen dargestellt sondern in voller Länge mit allen Menüpunkten sichtbar am rechten Rand. Kann es sein das vielleicht gerade ein Update eingespielt worden ist ?

**Comment by Barbar65** [comment]
Bei mir ist es genauso. Eigenanteilsrechner und Kostenrechner funktionieren nicht mehr. Fenster geht auf, bleibt aber leer

**Comment by daenischesbettenlager** [comment]
Selbes Problem, aber nicht nur Eigenanteilsrechner. Viele Tools versagen gerade

**Comment by andrgin** [comment]
Bei Update erstellen ist etwas schief gegangen. Sollte gleich behoben sein

**Comment by dsiekiera** [comment]
Update ist raus. Sollte alles gleich wieder gehen.

**Comment by Barbar65** [comment]
Jo, danke
