### ISSUE TITLE
Sound spielt nicht mehr

### ISSUE THREAD

**Issue by Mursanian** [dsiekiera/foe-helfer-extension#299]
Der Sound der bei LB Nachbarschaftsbelegungen spielt wenn was belegbar ist spielt nicht mehr, der für ~~die Infobox auch nicht~~. Der Button um den Sound einzuschalten scheint auch blasser zu sein als die anderen Buttons.

editiert: Infobox scheint der sound zu spielen aber in den Möglichen einzahlungen und im eigentlichen Kostenrechner nicht.

**Comment by andrgin** [comment]
Hast du den Sound im Fenster auch aktiviert? Kannst du davon einmal einen Screenshot machen?

**Comment by Mursanian** [comment]
https://gyazo.com/7cbb3da66fae7fdd6256d6f917f7b257

**Comment by Mursanian** [comment]
Gerade nochmal getested bei der Infobox geht der Sound aber nicht bei möglichen Einzahlungen

**Comment by Mursanian** [comment]
Ich kann gerne mal wenn es past im Discord oder so streamen oder auch teamviewer

**Comment by Mursanian** [comment]
Intressant, scheint am ausgabemedium zu sein, mein usb wireless headset spielt den sound nicht, mein TV(über hdmi angeschlossen) spielt ihn aber schon, :/

**Comment by Th3C0D3R** [comment]
Kann man das hier dann schließen?

**Comment by andrgin** [comment]
Ja sieht einfach nach in Windows verstelltem Standardaudiogerät aus.
