### ISSUE TITLE
Verbesserungsvorschläge

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#3]
Also ich muss sagen ich liebe das Tool :-D

auch wenn man noch was verbessern könnte:
- Dinge wie Fürstenhaus…sind ja nicht plünderbar. Also müssten sie nicht auftauchen.
- Alle fertigen Gebäude könnten ganz oben stehen und nicht durcheinander.
- Alle Gebäude die FP liefern könnten ganz oben stehen (sind am begehrtesten)
- wenn ich bei einen Nachbarn gehe, öffnet sich das "Aktive Produktionen" Fenster.
Klicke ich dann auf Angreifen, wäre es gut, wenn es weggehen würde.

**Comment by MrMattn** [comment]
die FP Inventar Menge wird nicht immer oben im Balken angezeigt.

**Comment by dsiekiera** [comment]
Die Menge wird von Inno erst beim betreten eines LGs übertragen. Vorher ist schlicht weg nichts bekannt, daher wird dieser Wert immer erst etwas später ergänzt.

**Comment by dsiekiera** [comment]
Ein Fenster das sich selbstständig schliesst geht nicht wirklich. Ansonsten habe ich das Teil noch mal erweitert.
