### ISSUE TITLE
Änderungen

### ISSUE THREAD

**Issue by agnc27** [dsiekiera/foe-helfer-extension#300]
Warum wird ständig was geändert das dann wieder nicht funktioniert und das Tool langsam dazu bringt den Bildschirm auszufüllen. Ich mochte den einfachen Helfer. Gibt es die Möglichkeit der Auswahl? LG A.

**Comment by andrgin** [comment]
Wir sind eben so fleißig, dass wir ständig neue Features entwickeln. Das wird sich auch hoffentlich nicht so bald ändern ;-)
Wenn du uns sagst, was dir konkret nicht gefällt, können wir das eventuell für das nächste Update berücksichtigen.

**Comment by Th3C0D3R** [comment]
Ich mach mal zu, wenn es noch was gibt, kann man ja wieder öffnen
