### ISSUE TITLE
[BUG] Menü geht kaputt

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#301]
Schonmal entschuldigung für die größen Bilder 😄 

Wenn man ein sehr großen Bildschirm hat dann kann man im Menü unendlich weiter runterscrollen:
![image](https://user-images.githubusercontent.com/7798500/71870462-47b04f80-3116-11ea-835d-f9313dbb54d8.png)

wenn man dabei bissle rumspielt kann sowas passieren:
![image](https://user-images.githubusercontent.com/7798500/71870590-c3aa9780-3116-11ea-891f-7884fe3f9288.png)

**Comment by dsiekiera** [comment]
Und was genau muss man dafür machen?

**Comment by Th3C0D3R** [comment]
Fenstergröße ändern -> die Pfeilbuttons drücken -> Weiter die Größe ändern und so weiter

Irgendwann kam das bei mir raus, die Buttons sind dann alle irgendwo im nirgendwo 😅

**Comment by Th3C0D3R** [comment]
Ich schließ das mal, weil es nur ein Bug ist der auftritt wenn man damit rumspielt und wer macht das schon 😄
