### ISSUE TITLE
Außenposten geht nicht

### ISSUE THREAD

**Issue by Kerngfoe** [dsiekiera/foe-helfer-extension#302]
Hallo, gleiches Problem wie beim Eigenanteils- und Kostenrechner  (wurde ja schon behoben) tritt auch beim Ausenposten-Fenster auf. Siehe Bild
![ausenposten](https://user-images.githubusercontent.com/59596743/71874788-11c59800-3123-11ea-8d45-c4de455ad7e4.jpg)

LG
Kerng

**Comment by Th3C0D3R** [comment]
also in der Beta funktioniert das bei mir.

**Comment by Kerngfoe** [comment]
Ich habe es gerade auf einem anderem PC probiert, da geht es auch. Ich werde es am Abend nocheinmal auf dem ersrten Gerät probieren und gebe dann bescheid. LG

**Comment by saki3220** [comment]
Auch bei mir besteht dieses Problem, interessanter weise ausschließlich auf dem Beta Server.
folgende Dinge wurden bereits probiert :
- BrowserCache geleert
- Erweiterung neu installieren
- AppData Cache geleert

Gibt es eine Idee, wir das Problem, z.B. über die Console, eingegrenzt werden kann ?
LG

**Comment by Kerngfoe** [comment]
Ich habe es soeben auf dem PC von heute Früh wieder probiert. Jetzt geht es wieder ohne Probleme.

**Comment by andrgin** [comment]
Problem erkannt. Inno Games sendet nun einen Parameter weniger am Beta Server mit. Wird behoben...

**Comment by Holger1968** [comment]
Seit dem Update auf Version 1.169 hab ich das Problem beim Aussenposten auch
https://forum.de.forgeofempires.com/index.php?threads/update-auf-version-1-169.38134/

**Comment by Th3C0D3R** [comment]
Der Commit [Outpost: Anpassung an neues Datenformat am Betaserver](https://github.com/dsiekiera/foe-helfer-extension/commit/ddb62b735945bc42520fedfda5a162fbfc07a96d) wurde nicht in Version 2.3.15.1 mitgeliefert.
@dsiekiera @andrgin

**Comment by andrgin** [comment]
Ja das 15.1er Update kam gleich nach dem Release. Das behebt den KR/EA Rechner Fehler mit der 15er Version.
Die 15.2er ist noch nicht released. Die Änderungen sind auf den master committed aber @dsiekiera muss noch ein Release machen.

**Comment by ljettinger** [comment]
Mine just updated to the 1.169 this morning and I have the problem with the Outpost window too...

**Comment by dsiekiera** [comment]
We have developed a new multi-browser version that runs in Chrome, Firefox and Opera. This will be published either tomorrow or on Friday. The fix is also included there.
