### ISSUE TITLE
Live Chat

### ISSUE THREAD

**Issue by MasterInterceptor** [dsiekiera/foe-helfer-extension#303]
Der Live-Chat funktioniert nicht, ebenso werden keine Emjoy´s angezeigt

**Comment by MasterInterceptor** [comment]
Zusätzlich habe ich festgestellt, das die Einheiten Übersicht, Investitionen in LG´s, Produktionsübersicht und einiges mehr nicht mehr angezeigt wird, seid dem letzten UP-Date :-(

**Comment by MasterInterceptor** [comment]
Ist noch nicht geschlossen

**Comment by MasterInterceptor** [comment]
Hatte falsch geklickt, Sorry

**Comment by dsiekiera** [comment]
Wir hatten in der 2.3.15 einen kleinen Bug.
Dann haben wir sofort 2.3.15.1 nachgeschoben die alles gefixt hat.

**Comment by Th3C0D3R** [comment]
> Der Live-Chat funktioniert nicht, ebenso werden keine Emjoy´s angezeigt

Der Tocken für den LiveChat ist leider ungültig, wird mit nächsten Update behoben sein

**Comment by MasterInterceptor** [comment]
Die Außenposten, kosten und Eigenanteilsrechner werden erst nachdem ich das spiel mehrmals (so zwischen 5 und 10 mal) neugeladen habe angezeigt.

**Comment by dsiekiera** [comment]
Das ist nicht "normal". Eigentlich sollte seit der 2.3.15 schon alles sauber geladen werden. Wenn du vor dem betreten die Konsole(F12) öffnest und dann das Spiel betrittst, bekommst du dann rote Error Meldungen in der Konsole?

**Comment by dsiekiera** [comment]
Der Chat wird bis auf weiteres erst mal deaktiviert. 
Der kostenlose Service des WS-Echo-Servers ist so in der Form nicht mehr verfügbar und liegt bis zu einer neuen Lösung auf Eis.
