### ISSUE TITLE
Team Snipe Option

### ISSUE THREAD

**Issue by ljettinger** [dsiekiera/foe-helfer-extension#304]
Would it be possible to add a team snipe option to the Cost Calculator?? Maybe a checkbox to turn it on and off and display what's needed for sniper #1, sniper #2, the profit to each and what sniper #1 owes to sniper #2...
I can supply a link to an online calculator if you'd like to see one in action??
thanks

**Comment by andrgin** [comment]
Yes it would be possible, but I am not sure if it is a good idea for the community if everybody can do team sniping with just 2 clicks.

**Comment by ljettinger** [comment]
I considered that before posting a request, but I'm on the second newest US world and we have to protect ourselves from teams constantly... I've been calculating it in a spreadsheet for a while now and now there's an online calculator in beta that will likely get integrated into the other guy's chrome extension, so I thought I'd suggest it and stay in front of the curve... A solid countermeasure to keep everything balanced would be to also include a team counter snipe tool, showing your own vulnerability to teams??

**Comment by SkateScout** [comment]
Can you provide the excel with an example how you calculate it?

**Comment by ljettinger** [comment]
I can... I have it in google sheets now, let me see how it moves over...

**Comment by andrgin** [comment]
If this really gets a big thing I think we could consider it for the own part calculator.

**Comment by ljettinger** [comment]
Here's a spreadsheet that I commented to explain to a guild member that it was real math and not just black magic, it's in a rough form, and since it's a spreadsheet and not code, I'm not covering every possibility, but it gets the job done... 
The basic formula takes the total FP required for the level and subtracts the FP already contributed to find the balance still needed... Then add to that balance the total FP put in by the person you want to place above (making sure there's enough room for both team members to place), or zero if no else or only the owner have contributed, then divide that number by 3 (for both team members and the person you're trying to pass) and that will give you the amount needed by each team member to lock the spots... This spreadsheet doesn't handle the situations where one team member needs to add one more FP than the other or situations where one would need to take first and the other take third... I also only calculates what the first place holder owes second when second takes a loss... In my experience I've found that 99% of the situations are covered with what's included... This spreadsheet also only works for 2-man teams... If you wanted to use a 3-man team, you just divide by 4 (or divide by 5 for a 4-man team)... One for each team member plus one for the person you're trying to beat...
A quick note on the number of team members used, 2-man teams are almost always more profitable than just 1 sniper when there is room for them... And there is a slim window, when the conditions are right, where using 3 people is more profitable than 2, but using a 4-man team is only ever used to bring pain to the owner and it's done by taking a reduced individual profit...
[team snipe heavily commented.xlsx](https://github.com/dsiekiera/foe-helfer-extension/files/4033054/team.snipe.heavily.commented.xlsx)

**Comment by ljettinger** [comment]
Here's a [detailed explanation](https://forum.en.forgeofempires.com/index.php?threads/low-advanced-guide.33723/page-2#post-226671) of what's going on, at least this is what I used to to create the spreadsheet... lol

And here's a link to an [online calculator](http://foetools.net/gbslotlocker.html) that just recently appeared that's capable of doing both 1 and 2-man teams... 

If you need any more info, let me know and I'll help best I can...

**Comment by BDRMega** [comment]
I upvote this enhancement!

**Comment by andrgin** [comment]
Da die Snipefunktion entfernt wurde, wird es auch kein Team snipen geben: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
