### ISSUE TITLE
Gilden-Gefechte Mitglieder-Aktivität

### ISSUE THREAD

**Issue by Mehlmuetze** [dsiekiera/foe-helfer-extension#306]
die neue Snapshot-Funktion funzt nicht, Fenster bleibt leer
![2](https://user-images.githubusercontent.com/59614234/71979097-2be3a100-321d-11ea-9c90-9f9343bb55dc.JPG)

**Comment by Reneg84** [comment]
wie kommt man eigentlich zu dem fenster? muss man da was spezielles drücken? ein button hab ich nicht gefunden

**Comment by Mehlmuetze** [comment]
> @mainline#274 Wenn du zu den Gilden Gefechten wechselst, ein Klick oben auf das grosse Siegel das die Gold-, Platin- oder sonst welche Stufe darstellt.
s.
https://forum.foe-rechner.de/d/63-welcher-button-fur-tracken-der-gg-beteiligung

**Comment by Andi47** [comment]
...und außerdem überdeckt das (leider nutzlose) leere Fenster die von FoE gelieferte Tabelle, selbst wenn man es beim letzten Öffnen zur Seite geschoben hat. (mit anderen Worten: Das Ding merkt sich die Koordinaten nicht)

**Comment by sanity65** [comment]
empty for me too
![Screenshot from 2020-01-09 11-03-00](https://user-images.githubusercontent.com/59678978/72039788-9ace0200-32d0-11ea-8adb-cf761095374c.png)

**Comment by dsiekiera** [comment]
Ein leeres Fenster kann ich leider nicht reproduzieren. IKönnt ihr mal mit offener Konsole spielen um ggf Fehler angezeigt zu bekommen?

**Comment by dsiekiera** [comment]
@sanity65 
You will be happy to hear that the Russian language will be integrated as of the next update.

**Comment by 7777777a8** [comment]
![Problem](https://user-images.githubusercontent.com/59689599/72061070-67da3d00-32d5-11ea-8ba3-cb71f775fcff.png)

**Comment by Mehlmuetze** [comment]
auf Dinegu und Fel funzt es super 👍 
nur auf BETA bleibt das Fenster leer...
![3](https://user-images.githubusercontent.com/59614234/72061395-10889c80-32d6-11ea-867e-eb60b1bd42ce.JPG)

**Comment by 7777777a8** [comment]
Ich spiele auf Fel und bei mir ist das Fenster auch leer (siehe Screenshot oben).

**Comment by dsiekiera** [comment]
Sehr schön, danke Jungs. Ich weiß ich wo es klempt. Werde das direkt prüfen.

**Comment by 7777777a8** [comment]
Super! Danke. :D

**Comment by dsiekiera** [comment]
Schreib mal bitte unter Konsole das rein: MainParser.PlayerPortraits und drücke Enter.
Was kommt da raus?

**Comment by Mehlmuetze** [comment]
bei mir tut sich nix
![4](https://user-images.githubusercontent.com/59614234/72061957-25b1fb00-32d7-11ea-96d4-4ad97be5db61.JPG)

**Comment by 7777777a8** [comment]
![Mainparser](https://user-images.githubusercontent.com/59689599/72061961-26e32800-32d7-11ea-9124-16997222f970.png)

Bei mir tut sich leider auch nichts.

**Comment by dsiekiera** [comment]
null - Aha. 
Bei euch wird das Mapping File nicht geladen. Prüfen wir nachher noch mal.

**Comment by Mehlmuetze** [comment]
thx :)

**Comment by 7777777a8** [comment]
Danke. Ich hoffe das klappt bald - habe mich schon sehr auf dieses neue feature gefreut. :)

**Comment by dsiekiera** [comment]
Ist gefixt.
