### ISSUE TITLE
Event Questliste - Mehrsprachigkeit

### ISSUE THREAD

**Issue by phillip-pilz** [dsiekiera/foe-helfer-extension#309]
Da ich auf das alte Ticket nicht mehr antworten kann, anbei eine Quelle für die englische Questliste.

Somit könnte man Englisch und Deutsch anbieten. Ebenso sind in der Quelle die entsprechenenden Ressourcen-Spannen angegeben für die verschiedenen Zeitalter.

https://forgeofempires.fandom.com/wiki/2020_Forge_Bowl_Event

 @Th3C0D3R #217

**Comment by Th3C0D3R** [comment]
wo ist da die Questliste?

**Comment by Th3C0D3R** [comment]
habse gefunden, danke 😊

**Comment by dsiekiera** [comment]
#217
