### ISSUE TITLE
GuildFights module fails to load

### ISSUE THREAD

**Issue by davemolton** [dsiekiera/foe-helfer-extension#310]
Testing the extension in the US it looks like the startup handler routine for avatars/portraits is not initializing the portraits collection correctly because the handler is checking the url for 
`https://foede.innogamescdn.com/assets/shared/avatars/Portraits.xml`
where in my region the actual sent request url is
`https://foeus.innogamescdn.com/assets/shared/avatars/Portraits.xml`

This leaves the collection null and later when the GuildFights module loads, the empty collection is indexed here:
`t.push('<img src="https://foede.innogamescdn.com/assets/shared/avatars/' + MainParser.PlayerPortraits[ p['player']['avatar'] ] + '.jpg" alt="">');`
and error placed in console.

**Comment by dsiekiera** [comment]
Fixed in next Version.
