### ISSUE TITLE
Nachbarschaftsproduktionen

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#32]
Hi,
ein Spieler hatte mir berichtet, dass bei ihm bei manchen Nachbarn das Fenster mit den Produktionen fehlt. Da ich dieses Phänomen noch nicht hatte, habe ich bisher noch nichts dazu geschrieben.
Heute habe ich so einen Fall.
Das Fenster fehlt... bin mehrfach rein gegangen, hab auch zu anderen Spielern gewechselt (hier kommt das Fenster) - wieder zurück = Fenster weg...

![image](https://user-images.githubusercontent.com/50969949/58940833-d624b300-877a-11e9-8ec3-614160f5d8bc.png)

**Comment by dsiekiera** [comment]
Hab das auch gehört. 
Vermutlich ist dann ein Gebäude in der Stadt vom Nachbarn das die Extension nicht "versteht".

**Comment by Lagewegerin** [comment]
Tagchen!
wir (3 andere spieler und ich) haben das auch hin und wieder.  nu mal meine frage zu deiner antwort, ein gebäude das irgend eine ausdehnung nicht versteht?!? welche ausdehnung, warum soll/muss ein gebäude das können und ist es dann immer das selbe? dann könnten wir bei gelegenheit mal kontrollieren, welches gebäude die spieler haben, die die anderen bei denen der "erntehelfer" funzt nicht haben xD

**Comment by dsiekiera** [comment]
Nicht Ausdehnung...

In meinen ersten Versuchen gab es immer Probleme mit einer Ruhmeshalle. Die Struktur der Daten ist bei diesem Gebäude ganz anders, das erzeugte einen Fehler im Code und das Fenster wurde nicht geladen. 
Evt gibt es noch ein anderes Gebäude das einen ähnlichen Fehler erzeugt.

**Comment by MrMattn** [comment]
hm da mit der Ruhmeshalle kann echt sein.
Habe es bei dieser Nachbarschaft auch einmal...und der jenige hat eine RH stehen

**Comment by Lagewegerin** [comment]
muss noch ein anderes gebäude sein....hab nen nachbarn gefunden ohne rh und der erntehelfer funzt trotzdem nicht :-)

http://prntscr.com/o8pb74

**Comment by MrMattn** [comment]
korrekt bei mir aktuell auch wieder einer...
https://www.bilder-upload.eu/bild-2b4dc9-1561928439.png.html

**Comment by bthau** [comment]
funktioniert bei mir bei einem nb auch nicht - hatte aber gestern mal funktioniert. habe neustart und auch ccleaner drüber laufen gelassen - geht immer noch nicht bei dem nb

**Comment by Metal-Frog** [comment]
Hi.
Das Nachbarschaftsfenster wird seit Installation der aktuelle Version gar nicht mehr angezeigt.

**Comment by MrMattn** [comment]
Man muss den obersten Punkt (Übermittlung an Foe-rechner) aktivieren…dann gehts wieder
warum auch immer

**Comment by dsiekiera** [comment]
Dieser neue Menüpunkt war schon länger angedacht. So kann man die Extension auf autark stellen. Also keine Kommunikation ausserhalb des Spieles. 
Die Kombination mit dem Erntehelfer war ein versehen, das hab ich Lokal schon gefixt.

**Comment by Bunderos** [comment]
Da ich das Feature zum Leid meiner Nachbarn sehr gerne nutze, habe ich noch mal bzgl. fehlendem Fenster recherchiert. Wie einige schon vermutet hatten, liegt es an Produktion von "Ruhm", sei es über Ruhmeshallen oder über Event-Produktionsgebäude. Sobald Ruhm zu ernten wäre, taucht das Produktionsfenster gar nicht auf.
Hoffe, das hilft bei der Fehlerbehebung

**Comment by Selene443Foe** [comment]
Version 2.3.2
Letzte Spielermeldung hierzu:

![10](https://user-images.githubusercontent.com/50969949/62010858-6cb89380-b170-11e9-9b50-70d3b3dc776e.png)

Der "F5 Trick" zeigte keine Wirkung.

**Comment by Selene443Foe** [comment]
Sag mal wie ist das gemacht? 
Aktualisiert sich die Anzeige eigentlich wenn man auf der Stadt des Nachbarn sitzt und wartet?
Ich hab den Eindruck das weder die Sabotageanzeige von FoE noch das Tool sich von selbst aktualisieren.
Nachdem mir das spanisch vorkam hab ich die Stadt verlassen und bin wieder rein = alles grün. 
Soll das Zufall gewesen sein?

**Comment by dsiekiera** [comment]
Inno übermittelt immer nur Daten bei einer bestimmten Aktion.
In diesem Fall wenn man die Stadt des Nachbarn betritt danach kommt einfach nix mehr. 

Die Gesamtanzahl aller deiner FPs kann zum Beispiel kann nur beim betreten des Spieles übermittelt werden. Danach wird nix mehr übermittelt.

**Comment by Selene443Foe** [comment]
Ah. OK. Verstehe. 
Vielen Dank
