### ISSUE TITLE
Seitenleiste

### ISSUE THREAD

**Issue by Durzo-Blint** [dsiekiera/foe-helfer-extension#33]
Hallo,
Ich habe mir die Chrome Erweiterung gerade erst installiert.
Mir fehlt nachdem ich Flash usw. aktiviert habe die neue "Sidebar".
Was muss ich machen, damit mir auch diese Angezeit wird?

Danke für die Hilfe
Auf den ersten Blick ein echt gutes Tool

**Comment by Durzo-Blint** [comment]
![image](https://user-images.githubusercontent.com/51476774/59093817-20da3280-8915-11e9-9ad4-c7739b433aa4.png)

**Comment by dsiekiera** [comment]
Hallo Durzo-Blint,

Flash deaktivieren. Die Extension kann nur in der HTML5 Version laufen.

**Comment by Durzo-Blint** [comment]
OK, Flash ist aus und ich habe die sidebar immernoch nicht
und HTML5 ist an
![image](https://user-images.githubusercontent.com/51476774/59095078-e756f680-8917-11e9-864d-046202103e20.png)

**Comment by dsiekiera** [comment]
Hast Du in der Toolbar des Browsers das Icon der Erweiterung?

**Comment by Durzo-Blint** [comment]
Ja habe ich
auch ein reinstall der erweiterung und neustart des Browsers hilft nicht
![image](https://user-images.githubusercontent.com/51476774/59099419-58e87200-8923-11e9-8987-3ed131f7fdbf.png)

**Comment by MrMattn** [comment]
Hi
mein Balken ist seit heute auch weg!?

**Comment by Durzo-Blint** [comment]
Ich habe immernoch das Problem das ich oben beschrieben habe.
Das was "MrMattn" beschreibt klingt sehr nach dem Problem, das ich auch habe.

**Comment by MrMattn** [comment]
was ich interessant finde...in meiner 2. Stadt habe ich den Balken. (die ist noch ganz klein)
in der Hauptstadt nicht

**Comment by dsiekiera** [comment]
Ich würde gerne mal bei euch beiden via AnyDesk oder Teamviewer auf den Rechner schauen. Diese Fehler kann ich hier einfach nicht darstellen. Würde es mal auf Betriebsblindheit schieben.

Schreibt mich bitte mal direkt an.

**Comment by MrMattn** [comment]
hi klar gerne. habe Zeit aktuell
wie können wir kontakt aufnehmen? per email hatte ich ja schon ;-)

**Comment by Durzo-Blint** [comment]
@MrMattn Denkst du das da etwas mit den Welten zusammenhängt? Ich bin ich Tuulech unterwegs...
@dsiekiera gleiche frage wie MrMattn, Auf welchem weg soll ich Kontakt zu dir aufnehmen?

**Comment by MrMattn** [comment]
bin auch in tuulech.
auf uceria geht es ...tuulech nicht.

**Comment by MrMattn** [comment]
gerade am Windows pc drin mit meiner Frau ihrer Stadt (auch tuulech) alles ok

mit meinem Account auch.
also liegt es an google chrome auf meinem macbook.
nur warum dann bei einer Stadt ja bei der anderen nicht?

**Comment by dsiekiera** [comment]
mainline.pyracantha@gmail.com

**Comment by MrMattn** [comment]
Kannste mich heute gerne anrufen unter 0170 2121173 
öffne dann Teamviewer.

Gruß
Martin

**Comment by Durzo-Blint** [comment]
@dsiekiera Habe dir gerade ne Mail geschrieben

**Comment by dsiekiera** [comment]
So kurze Teamviwer-Session und Problem gelöst.

Bei MrMattn war der Cache vom Browser zu agressiv.

**Lösung Windows:**
1. Stadt betreten
2. F12
3. In der Konsole den Reiter "Network" anwählen und Haken bei "Disable Cache" setzen
3. F5
4. F12

Lösung Mac:
1. Stadt betreten
2. CMD - Umsch + i (Konsole öffnen)
3. In der Konsole den Reiter "Network" anwählen und Haken bei "Disable Cache" setzen
3. CMD + R
4. 2. CMD - Umsch + i (Konsole schliessen)

Das solle in 98% alle Fälle helfen.

**Comment by Durzo-Blint** [comment]
Hallo,
Der hacken war bei mir gesetzt...
Habe ihn raus genommen und reload --> ging noch nicht
hacken wieder gesetzt  und reload --> ES GEHT JETZT !!!

Vielen Dank
