### ISSUE TITLE
Estimating Settlement Coin need

### ISSUE THREAD

**Issue by Norton5150** [dsiekiera/foe-helfer-extension#334]
If you know you need 200 more goods in a settlement, it would be nice to know that will cost you $40,000 Coins  
Calculated as such:(1000 Coin / 5 Goods )Production for Japan... so that  means you need 40 productions, costing 40,000 
Since Overstock flaws that logic, and you need to calculate each one separately.  Here is the Spreadsheet (with formula used to calc)

[Settlement Coin Need.xlsx](https://github.com/dsiekiera/foe-helfer-extension/files/4048951/Settlement.Coin.Need.xlsx)

Then you could expand that to say you have x coins, so you need x more.

Thanks

**Comment by andrgin** [comment]
Already implemented
