### ISSUE TITLE
Produktionsübersicht Münzen für LGs

### ISSUE THREAD

**Issue by kingcap12** [dsiekiera/foe-helfer-extension#338]
alle werte passen bei bein Münzen außer die LGs  Aachener Dom und CF da stehen bedeutend mehr Münzen als mein LG hergibt..woran liegt das ?

**Comment by andrgin** [comment]
Das ist ein Bug: https://github.com/dsiekiera/foe-helfer-extension/issues/126
Es wird derzeit noch der Münzboost des Markusdom und der Zufriedenheitsboost berücksichtigt, obwohl dieser nur für Wohngebäude und Produktionsgebäude gilt.
