### ISSUE TITLE
Neighborhood harvest error

### ISSUE THREAD

**Issue by sanity65** [dsiekiera/foe-helfer-extension#339]
Thanks for all your great job!!)
Sometimes Neighborhood harvest window isn't loaded, it happens when there is 4-hour production.

![Screenshot from 2020-01-13 00-42-41](https://user-images.githubusercontent.com/59678978/72283877-edf5db00-3669-11ea-8172-07338008c208.png)

**Comment by andrgin** [comment]
I could reproduce the problem. It has nothing todo with 4 hour productions, but with buildings that only produce clan power. In this case d['state']['current_product']['product'] is undefined.

Will be fixed in the next update.
