### ISSUE TITLE
kostenrechnerfenster lässt sich nicht mehr verschieben

### ISSUE THREAD

**Issue by Lagewegerin** [dsiekiera/foe-helfer-extension#34]
tagchen!
ich selbst habe das problem nicht, aber 2 spieler die ich kenne haben seit heute das kostenrechnerfenster starr. umstellung auf flash und dann wieder auf html5 brachte ebenso wenig wie das entfernen aus chrome. irgend ne idee dazu? :D

**Comment by Lagewegerin** [comment]
nach längerem austausch hab ich jetzt wohl alle infos^^
die kinners haben das fenster auch zu weit hoch geschoben, also haben sie das mit f12 und storage versucht, aber da findet er keine daten. sind die beim kostenrechner wo anders? 
mit cache löschen ging es aber :-)

**Comment by dsiekiera** [comment]
Löschen geht immer. Vom Kostenrechner heißt der Wert: **FPBoxCords** im Localstorage
