### ISSUE TITLE
Eigenanteilsrechner öffnet bei bestimmter Einzahlung nicht

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#341]
Der Rechner klappt nicht auf wenn diese Einzahlungskonstellation erfolgt ist:

![47](https://user-images.githubusercontent.com/50969949/72244733-302e0680-35ef-11ea-84f2-4b3406d40a96.png)

**Comment by andrgin** [comment]
Problem gefunden. Wird mit dem nächsten Update behoben.

Ursache war, dass bei 5 Einzahlungen in ein LG, wo es nur 4 Plätze mit Belohnungen gibt beim letzten Rank der reward undefined ist.
