### ISSUE TITLE
Investitionsübersicht: Datum und Veränderung

### ISSUE THREAD

**Issue by B3-ta** [dsiekiera/foe-helfer-extension#342]
Hallo zusammen,

ich habe immer einen relativ großen Bestand an FP "draußen" bedingt durch reichlich Push Aktivität.
Nun würde ich gerne den Überblick über diese Investments behalten, denn es gibt immer wieder Spieler die Ihre LGs pushen lassen und dann tagelang nicht leveln. Und dafür wären ein paar mehr Informationen auf der Internetseite wirklich hilfreich. Lässt es sich einrichten das:

- Datum / Uhrzeit wann die Investition getätigt/das erste mal zum FOE Helfer übertragen wurde
- Veränderung der FP Belegung einsehbar

werden?

Danke euch für dieses großartige Tool

**Comment by Th3C0D3R** [comment]
Der Wunsch kam gerade auch von einem Gildenmitglied an mich.

Wir schauen mal wie und wann wir das umsetzen können

**Comment by andrgin** [comment]
Mittlerweile implementiert
