### ISSUE TITLE
Sortierung in der Produktionsübersicht

### ISSUE THREAD

**Issue by Orthanc123** [dsiekiera/foe-helfer-extension#346]
Ich finde euren FoE-Helfer wirklich klasse !!! Vielen Dank dafür ;-)

Bei der Nutzung ist mir eine Sache aufgefallen, die für mich die Planung etwas einfacher gestalten würde. Solch eine Funktion hinzuzufügen dürfte vmtl. auch nicht sonderlich kompliziert sein. Es geht um die Produktionsübersicht.

Ich fände einen weiteren Slot, in dem alle Gebäude nach der Reihenfolge aufgelistet sind,  in der sie als nächstes ihre Produktionen abschließen nicht schlecht. Noch besser wäre ein Slot, wo man sich per Auswahl selbst sortieren kann, ob man nach Ablaufzeit bzw. Erntezeitpunkt (was ja das gleiche ist), Art des Gutes (Geld, Vorräter, FP, ...) und der Art der Gebäude (LG Gebäude, Gütergebäude, Dekorationen, ... (genau wie bereits vorhanden)) sucht. 

Ich weiß nicht was andere davon halten, aber ich glaube, dass das einigen Spielern das Spiel vereinfachen würde, da sie z.B. auf einen Blick nachschauen könnten, wann sie wieder online sein sollten, damit ihre Güter / Vorräte / FP nicht gestohlen werden.

MfG und nochmals vielen Dank für die tolle Unterstützung :-)

Orthanc

**Comment by dsiekiera** [comment]
Dann klick doch einfach auf den jeweiligen Tabellenkopf und sortiere es dir wie du möchtest 😁

**Comment by Orthanc123** [comment]
Welcher Tabellenkopf sortiert denn nach der Zeit?

**Comment by Orthanc123** [comment]
Es geht ja genau darum einen Tabellenkopf mit der Sortiermöglichkeit nach der Zeit zu erstellen

**Comment by dsiekiera** [comment]
Dann klick ich auf Ernte:

![Bildschirmfoto 2020-01-13_23-33-13](https://user-images.githubusercontent.com/834814/72297910-3e1a7080-365d-11ea-92f7-8d43d30e9d75.png)

Das sortiert die beiden Spalten. Eine gibt die grobe Richtung, die andere hat die genaue Zeit.

**Comment by Orthanc123** [comment]
oh ... 
sehr gut, das gibts schon ;-) 
Demnach Frage beantwortet - Vielen Dank

**Comment by dsiekiera** [comment]
Intuitiv. Klick einfach mal durch...
