### ISSUE TITLE
Info box error

### ISSUE THREAD

**Issue by sanity65** [dsiekiera/foe-helfer-extension#348]
I don't see any level-up events in info box, there is an error.
![Screenshot from 2020-01-14 17-54-22](https://user-images.githubusercontent.com/59678978/72344024-78861b00-36fa-11ea-9c1a-7b099b86d2d7.png)

**Comment by Th3C0D3R** [comment]
fixed with next update -> 7247a214624ab574205e1a04ec53b72f4881ac49
