### ISSUE TITLE
Produktionsübersicht --> Güterproduktion nur 4 Güter anstatt 5 in einem ZA

### ISSUE THREAD

**Issue by Durzo-Blint** [dsiekiera/foe-helfer-extension#349]
Hallo,

Bei mir werden im  ZA Moderne nur 4 Güter angezeigt.
Es scheint, dass das 5. Gut (in meinem Fall sind das die Verpackungen) nicht gibt.

![image](https://user-images.githubusercontent.com/51476774/72346868-11a33a80-36d7-11ea-9efe-20157a0e46ab.png)

**Comment by Th3C0D3R** [comment]
Das Problem gab es schonmal, ist das noch nicht gelöst worden?

**Comment by Th3C0D3R** [comment]
@dsiekiera

**Comment by andrgin** [comment]
Sollte eigentlich behoben sein. Ich kann es nur leider schwer testen, da ich keine Stadt habe, die Güter aus der Moderne aproduziert.
