### ISSUE TITLE
Produktionsfenster fehlt

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#35]
Hi
wenn ich meine Nachbarn durchklicke, gibt es ab und zu welche, bei denen kein Produktionsfenster geöffnet wird. Obwohl entsprechende Gebäude vorhanden und sogar plünderbar sind!?
woran liegt das?

**Comment by dsiekiera** [comment]
Hey MrMattn,

den Fehler hab ich bereits gefunden. Ein Scriptfehler war die Ursache. Ich hoffe es war auch nur der eine ;-)
