### ISSUE TITLE
Menü Länge einstellbar

### ISSUE THREAD

**Issue by dsiekiera** [dsiekiera/foe-helfer-extension#351]
Das Menu-Strip soll in der Länge einstellbar sein.

**Comment by JHCD** [comment]
Coole neue Funktion, aber hier gibt es einen Bug:

Automatisch macht das Menü länger als Einträge vorhanden sind:
![image](https://user-images.githubusercontent.com/12496340/72708834-d2a43780-3b63-11ea-87f6-7fffd2a5c556.png)

Wenn ich testweise 16 einstelle, stimmt die Länge.
Es schein also ein Max-Wert zu fehlen.
