### ISSUE TITLE
Kostenrechner: Anzeige wann das LG bereit zur Ernte ist

### ISSUE THREAD

**Issue by B3-ta** [dsiekiera/foe-helfer-extension#352]
Ist es möglich im Kostenrechner ein Feld hinzuzufügen das Anzeigt wann das LG das nächste mal "bereit zur Ernte" ist. 

Somit könnte man im Push direkt sehen ob man aller Wahrscheinlichkeit nach noch einige Stunden auf seine FP warten muss.

(wenn ich mich recht entsinne war sogar schon mal möglich)

**Comment by dsiekiera** [comment]
Inno hat diese Zeit ganz schnell entfernt da ein Erntezeitpunkt nicht erwünscht ist. 
Wir werden so etwas auch nicht einbauen können und wollen.

**Comment by B3-ta** [comment]
Das ist wirklich schade.
Aber gut, was nicht an Informationen übertragen wird, kann auch nicht angezeigt werden......
