### ISSUE TITLE
Menü

### ISSUE THREAD

**Issue by pegazusfw** [dsiekiera/foe-helfer-extension#36]
Hallo,
der Menübalken rechts unten ist nicht im Vollbildmodus sichtbar

**Comment by Hirnqualle** [comment]
hallo, bei mir taucht die Leiste für den Helfer nur noch auf 2 Welten auf und auf zwei weiteren Welten nicht mehr, nur die Anzeige Fp Lager taucht dort auf.
was kann ich dagegen tun
