### ISSUE TITLE
Website erfordert Passwort

### ISSUE THREAD

**Issue by Julian2424** [dsiekiera/foe-helfer-extension#37]
Die Seite [https://foe-rechner.de/](https://foe-rechner.de/) erfordert Benutzernamen und Passwort (Danach Fehler 401). Ist das gewollt?

**Comment by dsiekiera** [comment]
Der Hoster hat heute Mittag die Seite wegen zu hohem Traffic vom Netz genommen.
Sie ist bereits auf einen größeren Webserver umgezogen und wird in Kürze wieder Verfügbar sein.
