### ISSUE TITLE
P2P-Chat

### ISSUE THREAD

**Issue by SkateScout** [dsiekiera/foe-helfer-extension#372]
Wäre es eine Option den Live Chat auf "https://peerjs.com/" umzustellen?
Das ganze basiert dann auf WebRTC und nutzt nur für den Verbindungsaufbau
den Freien Server die Gesamte Kommunikation ist Serverlos und entlastet so
den Serverbetreiber. Vielleicht hält diese Lösung dann auch länger als die letzte
für den Live Chat.

**Comment by Th3C0D3R** [comment]
Aber du weißt schon was P2P bedeutet?
Das können wir leider nicht nutzen, selbst wenn es serverlos ist, müssen die clients sich mit dem Server erst verbinden um dann eine clientverbindung aufzubauen.

**Comment by SkateScout** [comment]
Ja das ist mir klar.
Zu dem Server gibt es mit peerjs.com einen der Frei genutzt werden darf.
Außerdem kann man auch mittels P2P ein Netzwerk aufspannen für einen Gildenchat.
Daher war es ein Vorschlag um die Serverlast zu reduzieren.

**Comment by andrgin** [comment]
Hat sich mittlerweile erübrigt. Haben eine neue Lösung.
