### ISSUE TITLE
Eigenanteilsrechenr läßt sich nicht öffnen

### ISSUE THREAD

**Issue by MasterInterceptor** [dsiekiera/foe-helfer-extension#375]
Der Eigenanteilsrechenr läßt sich nicht öffnen, obwohl ein LG geöffnet ist

**Comment by MasterInterceptor** [comment]
Ich habe keinen Fehler in der Konsole, egal welches LG ich auf habe ob Krake, Arche TA usw.

**Comment by MasterInterceptor** [comment]
Im Forum kann ich eigenartiger weise nicht antworten

**Comment by andrgin** [comment]
Kannst du einmal einen Screenshot von einem LG posten. Das macht die Suche deutlich einfacher.

**Comment by MasterInterceptor** [comment]
Arche LEvel 90 auf 91, TA als beispiel
![arche](https://user-images.githubusercontent.com/56156303/72567370-1114ca80-38b6-11ea-8bbf-3244e680ef49.JPG)
![TA](https://user-images.githubusercontent.com/56156303/72567385-196d0580-38b6-11ea-9d37-315511ecb66c.JPG)

**Comment by MasterInterceptor** [comment]
habe die extension einmal ganz entfernt, den rechner neu gestartet und dann wieder zu chrome zugefügt, jetzt funktioniert er wieder.
vielen dank für die mühe
