### ISSUE TITLE
Gildengefechte in der Infobox + Neues Dropdown

### ISSUE THREAD

**Issue by dsiekiera** [dsiekiera/foe-helfer-extension#379]

**Comment by MrMattn** [comment]
klappt aber nicht immer
https://prnt.sc/qp508t

von back to future (meine Angriffe) fehlen "Erfolge"

**Comment by dsiekiera** [comment]
Ach deine eigenen Anträge

**Comment by MrMattn** [comment]
ja meine Angriffe erschienen auch, aber halt nicht alle wie du an der Kampfstatistik siehst.
Und dank tool weiß ich auch, dass ich der einzigste war der gekämpft hat ;-)
