### ISSUE TITLE
Eigenanteilsrechner hängt sich auf

### ISSUE THREAD

**Issue by mooneh** [dsiekiera/foe-helfer-extension#38]
Wählt man ausversehen ein LG, bei dem kein Eigenanteil berechnet werden kann, kann man zwar weiter die Lgs wechselnt, allerdings kann ich das Fenster nicht mehr schliesse. Ein Klick auf das X bewirkt nichts. Um das Fenster zu entfernen bleibt nur ein Neustart.

**Comment by dsiekiera** [comment]
Alter gefixter Fehler.
