### ISSUE TITLE
Infobox zeigt kein Level-Up bei Beteilung an

### ISSUE THREAD

**Issue by dsiekiera** [dsiekiera/foe-helfer-extension#380]

**Comment by MrMattn** [comment]
hab nun die betaversion wieder
da geht levelup

**Comment by Th3C0D3R** [comment]
Doch anzeigen schon, aber nicht wieviel FP man bekommen hat, da steht dann statt x FP einfach 0 FP

**Comment by Th3C0D3R** [comment]
Behoben im nächsten update
