### ISSUE TITLE
Motivation import error?

### ISSUE THREAD

**Issue by sanity65** [dsiekiera/foe-helfer-extension#388]
![Screenshot from 2020-01-18 21-11-42](https://user-images.githubusercontent.com/59678978/72665919-439a0100-3a37-11ea-9f86-d6616d49c964.png)

**Comment by sanity65** [comment]
I have nothing in the infobox since yesterday... is it related with this error?

**Comment by someone97563** [comment]
This error is known and repaired in beta and has nothing to do with the event-quests.
