### ISSUE TITLE
Cost calculator does not update when a member contributes to GB

### ISSUE THREAD

**Issue by abbygail14** [dsiekiera/foe-helfer-extension#403]
The cost calculator does not update the spot if it is already taken while the cost calculator window is open unless all windows are closed and reopened.

**Comment by andrgin** [comment]
Do you mean your own contributions or from other players?
Did the ingame window update?

**Comment by SkateScout** [comment]
Hi, i also see that there is an glitch in the game. You see in the progress bar that there was an Contribution (MaxProgress and CurrentProgress) but you did not get the information who (rank/person) did the contribution. So the calculator can not proberly be updated.

**Comment by andrgin** [comment]
When the new quick donation feature was introduced there was nothing transmitted when someone else invests in the currently open LG because there is no request to refresh it. I can take a look if there was something changed but atm the cost calculator only supports refreshing on an own investment.

**Comment by abbygail14** [comment]
> Do you mean your own contributions or from other players?
> Did the ingame window update?

From the other players. Yes, the InGame window updates but the cost calculator did not refresh

**Comment by andrgin** [comment]
1.) Which ingame window was updated? The one for the actual GB or the overview listing all GBs of the player.

2.) Was the window updated automatically or only after open/closing.

**Comment by outoftheline** [comment]
As this issue has been open for a while without further response, I'll close it.
