### ISSUE TITLE
Request for new feature in cost calculator

### ISSUE THREAD

**Issue by abbygail14** [dsiekiera/foe-helfer-extension#404]
Currently the cost calculator only shows the first available position in a GB, it would be nice to show which spot gives us profit. For example: In a GB, if there are spots 4 and 5 available, the cost calculator only shows if I can make a profit or not on position 4 but does not indicate if I can make a profit on spot 5 or how much the spot 5 costs.

**Comment by andrgin** [comment]
Snipefunktion wurde entfernt: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
