### ISSUE TITLE
Empty event list

### ISSUE THREAD

**Issue by sanity65** [dsiekiera/foe-helfer-extension#405]
No errors in console
![eventlist](https://user-images.githubusercontent.com/59678978/72701716-7698dd80-3b7a-11ea-8442-365f1b98c593.jpg)

**Comment by Th3C0D3R** [comment]
can you write this in console `EventQuest` and show me the output just like this:
![image](https://user-images.githubusercontent.com/7798500/72702042-9ec01680-3b51-11ea-839e-9cc8ca9539a4.png)

**Comment by Th3C0D3R** [comment]
and also how many quests you finished

**Comment by sanity65** [comment]
I finished 41 quests
![quest](https://user-images.githubusercontent.com/59678978/72702328-7f8aae80-3b7c-11ea-9738-8f665168e06e.jpg)

**Comment by sanity65** [comment]
I just finished 42nd quest and now I have upcoming quests
![eventlist2](https://user-images.githubusercontent.com/59678978/72702557-50c10800-3b7d-11ea-903c-c89c3b447aba.jpg)

**Comment by sanity65** [comment]
After finishing today's quest
![eventlist3](https://user-images.githubusercontent.com/59678978/72702615-8fef5900-3b7d-11ea-9d7d-0dacf9439643.jpg)

**Comment by Th3C0D3R** [comment]
ok, yeah the second thing is a bug which I already fixed in beta. first issue is that I cant get this on my side, what did you do before open the questlist?

**Comment by sanity65** [comment]
all daily things. collect production, put fps....
I try to reload the game and open questlist first, it was the same situation.
I will see tomorrow if it repeat

**Comment by Th3C0D3R** [comment]
right, just repearte it tomorrow again. I will see also what is going on tomorrow.

**Comment by ljettinger** [comment]
My quest list is also empty... I also did all the daily things before attempting to open it... I'm on quest 39 and will finishing it in about 5 minutes... I'll let you know if that changes anything...

**Comment by someone97563** [comment]
The empty quest-list  should be fixed in the next version. There may still be an error with the current quest, if it isn't unlocked.

**Comment by sanity65** [comment]
same today
so waiting for next update)
