### ISSUE TITLE
Infobox: level up error

### ISSUE THREAD

**Issue by sanity65** [dsiekiera/foe-helfer-extension#408]
Whatever place I have it always says that I got 0 FPs.
![level-up](https://user-images.githubusercontent.com/59678978/72708404-d26c6200-3b8c-11ea-93c5-a256fda668a3.jpg)

**Comment by Th3C0D3R** [comment]
Fixed in next update

**Comment by dsiekiera** [comment]
Das gleiche in deutsch #380
