### ISSUE TITLE
Keine Max-Länge für das Menü definiert

### ISSUE THREAD

**Issue by JHCD** [dsiekiera/foe-helfer-extension#409]
Coole neue Funktion (#351) mit der Menü-Länge, aber hier gibt es einen Bug:

Automatisch macht das Menü länger als Einträge vorhanden sind:
![image](https://user-images.githubusercontent.com/12496340/72708834-d2a43780-3b63-11ea-87f6-7fffd2a5c556.png)

Wenn ich testweise 16 einstelle, stimmt die Länge.
Es schein also ein Max-Wert zu fehlen.

**Comment by andrgin** [comment]
Sollte mittlerweile gefixed sein
