### ISSUE TITLE
Eigenanteilrechner mit verschiedenen %en belegen lassen

### ISSUE THREAD

**Issue by PXWaldy** [dsiekiera/foe-helfer-extension#41]
Es wäre super, wenn man den Prozentsatz pro Platz bestimmen kann.
Also so das man jeden platz die Prozente definieren kann.
z.B.
P1 190%
P2 190%
P3 180%
P4 100%
P5 100%

**Comment by dsiekiera** [comment]
Das kann die Online Version auf jeden Fall schon.

Hier ein Beispiel: [https://foe-rechner.de/ownpart/index?lg=thearc&step=90&p1=190&p2=190&p3=180&p4=100&p5=100](https://foe-rechner.de/ownpart/index?lg=thearc&step=90&p1=190&p2=190&p3=180&p4=100&p5=100)

**Comment by messer78** [comment]
Darf ich dies noch einmal in die Gegenwart zurück holen? Habe derzeit einen Mäzen, der gerne mit 1,9 fördert, alle anderen mit 1,85. Gäbe es die Möglichkeit, doch noch mal pro Platz den Föderfaktor getrennt eintragen zu können, so wie in der Website-Variante, oder ist das unverhältnismäßig viel Programmieraufwand?

**Comment by andrgin** [comment]
Kann die aktuelle Version mittlerweile
