### ISSUE TITLE
FoE Helfer startet nicht

### ISSUE THREAD

**Issue by Kaye68** [dsiekiera/foe-helfer-extension#410]
Hallo!
Bis vor 10 Minuten wurde der FoE Helfer noch geladen (Chrome), aber nach dem letzten Neustart ist der Helfer nicht mehr sichtbar. 
Übrigens: Die neue Stadtansicht und Übersicht über die Ereignisse sind großartig.

**Comment by andrgin** [comment]
Ist das Update Extension Einstellungen aktiviert bzw. hast du allen Berechtigungen zugestimmt?

**Comment by Kaye68** [comment]
Peinlich! *schäm*
Danke für die schnelle Hilfe! ♥
