### ISSUE TITLE
Mehrfachlistung der Menü Punkte 

### ISSUE THREAD

**Issue by ZorakYj** [dsiekiera/foe-helfer-extension#411]
Hallo, seit dem Update werden mir die Punkt Ereignisse, Stadtübersicht und Event Questliste doppelt im Menü angezeigt. Ich nutze Chrom

**Comment by sanity65** [comment]
For me too...
![Screenshot from 2020-01-20 18-54-21](https://user-images.githubusercontent.com/59678978/72727950-60a90e00-3bb6-11ea-964d-9da2040a3dfe.png)
![Screenshot from 2020-01-20 18-54-38](https://user-images.githubusercontent.com/59678978/72727954-63a3fe80-3bb6-11ea-9bd3-b83aa55214ae.png)

**Comment by MrMattn** [comment]
Man müsste eh mal drüber nachdenken, ob es Möglich wäre, die Leiste manuell anpassen zu können!? 
Jeder hat so (wie ich es in der Gilde höre) Vorlieben wie die Reihenfolge der Symbole sein müsste.
Ich zb brauche das Ereignisse finden Feld mal überhauptnicht ;-)
Nice to have...aber lieber weiter unten

**Comment by ljettinger** [comment]
same here...

**Comment by MrMattn** [comment]
ihr könnt in die Einstellungen gehen udn die Anzahl verändern der Symbole in der Leiste.
man kann die Symbole auch in der Leiste verschieben.
NAchdem ich das gemacht habe waren die doppelten plötzlich weg

**Comment by ljettinger** [comment]
Did you move the duplicate to the bottom and then hide it?? because I've tried both moving them and changing the number displayed and I still have doubles... I also cannot move a menu item from the first 8 to the second 8, but that's another issue all together... :)

**Comment by ZorakYj** [comment]
Bei mir sind die doppelten nun auch verschwunden seit dem ich mein Pc neu gestartet habe.

**Comment by Br0k3nH0m3** [comment]
Browser >> STRG F5 x 2 >> ok... ;)
