### ISSUE TITLE
Stadtübersicht fehlerhaft

### ISSUE THREAD

**Issue by Nersgatt** [dsiekiera/foe-helfer-extension#412]
In der Stadtübersicht werden einige Ritualflammen und Piraten-Wachposten nicht angezeigt, sondern als freie Fläche ausgewiesen. Es geht um die Ritualflammen am untersten Zipfel bei der Weltausstellung und die Piraten-Wachposten links neben dem Castel del Monte.
Siehe Screenshot 

![image](https://user-images.githubusercontent.com/60100528/72728766-61c64500-3b8e-11ea-8e73-6e8f3013caa4.png)

**Comment by ljettinger** [comment]
I'm getting the same thing with missing buildings... And after some testing, it's not the buildings themselves, but it's anything that is entirely in the last 4 rows along the water... if it sticks out into the 5th row or beyond, it will place it on the diagram, but if it's small enough to fit in that last row of expansions it's not being shown... So everything in the 4 rows from his northernmost outposts to southernmost ritual flames...

**Comment by slayerkenya** [comment]
bei mir ist es auch so das am einten rand diverse gebeude fehlen

**Comment by andrgin** [comment]
Ja liegt am linken Rand. Wird korrigiert.

**Comment by Timee79** [comment]
Bei mir wird die Kampfpanzer und Haubitzen Fabrik als freier Platz angezeigt.
![Stadtübersicht](https://user-images.githubusercontent.com/60137913/72802936-26d71680-3c4d-11ea-80ad-05cfc34e5d3b.JPG)
