### ISSUE TITLE
Show total invested amout!

### ISSUE THREAD

**Issue by MikssLv** [dsiekiera/foe-helfer-extension#413]
It would be nice to make a total invested at the time in gb, showing invested amout + proffit and all togeather

**Comment by lolospeed** [comment]
nous en parlions hier soir avec un amis quand nous étions la calculatrice a la main pour connaitre le nombres de pf a l’extérieur a gauche de la barre de pf ça serait bien

**Comment by Th3C0D3R** [comment]
Ist in der Beta nun drin. Geht aktuell als kleines Fenster auf mit der Anzahl investierter FP und dem aktuellen Gewinn (Investiert + Gewinn sind dann das was man am ende bekommen würde)
11c236e

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2020-02-20 um 17-58-43](https://user-images.githubusercontent.com/834814/74959337-a7cf2c80-540a-11ea-97b2-87d8defaa03b.png)
