### ISSUE TITLE
Kampf + Verteidigungswerte der Nachbarschaft (+Angebot zum Erstellen einer Liste mit Kampfwerten von Gebäuden) 

### ISSUE THREAD

**Issue by Niorian** [dsiekiera/foe-helfer-extension#414]
Vorab: Dies betrifft Vorschlag https://github.com/dsiekiera/foe-helfer-extension/issues/53
-> Anzeigen der vier verschiedenen Werte Angriff+Def bei Verteidigung, Angriff+Def bei Angriffen in der Stadtansicht von Freunden/Nachbarn/Gildenmitgliedern
 
Ich habe auf diesen Vorschlag vor ein paar Tagen geantwortet, da aber hier keine Rückmeldung kam bzw. der Thread deswegen nicht nach oben gepusht wurde, dies nochmal als separater Thread. 

Der Hauptgrund, der gegen diesen Vorschlag von euch geäussert wurde, war, dass es keine existierende Liste mit diesen Werten gibt. Ich könnte euch zumindest bei diesem Punkt gern helfen bzw. bei Interesse diese Liste erstellen, da ich so ein Feature gern in der Erweiterung sehen würde. Hierzu könnte man die Infos auf dem offiziellen FoE-Wiki (nicht das Fandom Wiki) zur Grundlage geben. Kategorie: Gebäude.
https://de.wiki.forgeofempires.com/index.php?title=Gebäude

In den verschiedenen Kategorien werden alle Gebäude angezeigt, die es im Spiel gibt. Eventgebäude, Militärgebäude, alles was das Herz begehrt. Hier könnte man die einzelnen Gebäude durchgehen und bei jedem Gebäude was in irgendeiner Form Kampfbonus gibt, auflisten.

Ich weiss jetzt nicht in welcher Datenform das Spiel die Gebäudenamen intern ausspuckt, aber in den Bilderlinks zu den Gebäuden wird auch immer der technische Name der Gebäude genannt, beim Olympischen Tresor vom Forge Bowl Event ( https://de.wiki.forgeofempires.com/index.php?title=Olympischer_Tresor_-_St._9) z.B. R_SS_MultiAge_SportBonus20i
Wäre dies hilfreich, oder bräuchte man die Gebäudenamen irgendwie in einer anderen Form? 

--> https://foede.innogamescdn.com/assets/city/buildings/R_SS_MultiAge_SportBonus20i.png

Einfach Bescheid geben, falls Interesse besteht.

**Comment by andrgin** [comment]
Ich würde eher eine Lösungbevorzugen, wo die Gebäude selbst ausgelesen werden. Theoretisch sollte man da alles raus bekommen.
Allerdings haben wir gerade einen Schwung neue Features released und sind deshalb noch um Fixen von Bugs, aber wir werden das inter diskutieren.

**Comment by SkateScout** [comment]
Die Informationen bekommt man aus den "city_entities" ist aber durch die Struktur mit Zeitaltern und LG Levels keine leichte Aufgabe.

**Comment by Niorian** [comment]
Wie ihr meint. Das Angebot steht immer noch, wenn es mit dem direkten Auslesen nicht klappt, wisst ihr Bescheid :)

**Comment by andrgin** [comment]
Der Erntehelfer wurde entfernt: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
