### ISSUE TITLE
FP Lager +Mäzen =Gesammt FP 

### ISSUE THREAD

**Issue by kingcap12** [dsiekiera/foe-helfer-extension#415]
schön das es jetzt FP Lager + Kaufbar zu sehen ist ..es wäre aber sehr nützlich wenn man dahinter noch die FP angezeigt bekommt die unterwegs sind +Mäzen damit man weiß wie hoch sein alkueller FP Stand ist ...das Kaufbar aber trotzdem lassen ist wie gesagt eine super idee

**Comment by andrgin** [comment]
Grundsätzlich meiner Meinung nach eine gute Idee allerdings schwierig in der Leiste umzusetzen, da die Investment Liste nur beim Öffnen der Investitionsliste im Rathaus übermittelt wird. Diese würde sich also nur sehr selten aktualisieren. Beim Einzahlen würden dann die FP im Inventar weniger werden und noch nicht in der Investment Anzeige dazu kommen. Wenndann wird es eher auf eine MessageBox im RH hinaus laufen.

**Comment by kingcap12** [comment]
das mit der Message Box im RH ist auch eine gute Idee ...dort ist man ja auch ständig am nachschauen ...auf die FOE Rechner Homepage geht man ja doch seltener

**Comment by Th3C0D3R** [comment]
Ist in der Beta nun drin. Geht aktuell als kleines Fenster auf mit der Anzahl investierter FP und dem aktuellen Gewinn (Investiert + Gewinn sind dann das was man am ende bekommen würde)
11c236e

**Comment by dsiekiera** [comment]
Gleiche Ticket wie #413
