### ISSUE TITLE
Add RQ FP to CoPayment Calculator

### ISSUE THREAD

**Issue by ljettinger** [dsiekiera/foe-helfer-extension#416]
Great job on implementing adding the remaining RQ fp to the cost calculator (#282 )... Is it possible to also add the functionality to the Copayment calculator as well?? thank you...

**Comment by andrgin** [comment]
So far we have not decided yet if we want to implement that feature. My opinion on that is that we will only include a team snipe feature if we can offer a method of protection as well.

**Comment by ljettinger** [comment]
Actually I was referring to the amount of FP left until the "spend x fp" recurring quest looped that was added to the bottom of the Cost calculator window, but I've just discovered that has gone away with this last update?? I found it to be VERY helpful and hope that's just a bug and it's not being scraped??

**Comment by dsiekiera** [comment]
> I found it to be VERY helpful and hope that's just a bug and it's not being scraped??
Yes it's a small bug and will be fixed in the next update.

**Comment by andrgin** [comment]
Oh now I think what you mean. Yes it will be fixed for the cost calculator in the next days.
For the Own part calculator we could do it as well.

**Comment by ljettinger** [comment]
Would it be possible to also add it to the CoPayment Calculator as well as the Cost Calculator?? It would make sense there too...
