### ISSUE TITLE
vorschlag für die GG

### ISSUE THREAD

**Issue by view-matic** [dsiekiera/foe-helfer-extension#418]
hallo, 
wäre es möglich, dass man alle kämpfe auf einem sektor in einer kleinen rangliste zusammenfasst um sie anschliessend im chat zu posten, also alle mitglieder die auf dem sektor gekämpft haben und wieviele kämpfe jeder gemacht hat?

**Comment by DJMMC** [comment]
Würde ich auch sehr hilfreich und gut finden

**Comment by andrgin** [comment]
Nicht möglich siehe: https://github.com/dsiekiera/foe-helfer-extension/issues/860
