### ISSUE TITLE
Menü-Leiste rechts erscheint, aber bleibt leer

### ISSUE THREAD

**Issue by dsiekiera** [dsiekiera/foe-helfer-extension#42]
Dieses Problem führt von einer falschen Browser Einstellung.

Gehe ins Menü des Chrome zu den "`Einstellungen` > `Erweitert `> `Sprachen`" oder über diesen Link => chrome://settings/?search=Sprache

Klappe es auf und prüfe ob `Deutsch` in der Reihung ganz oben steht. Das kannst Du mit den drei Pünktchen einfach ändern.

**Comment by namsur1234** [comment]
English or other language users need to make sure Deutsch is listed as a language preference and is at the top of the list. 
Chrome menu (3 dots in top right) choose Settings then in the search box type "Language". This will reveal the Language setting box. Click the drop down arrow on the right to expand Language settings. Click on "Add Languages" and search for and choose German - Deutsch then click Add. Once added click the 3 dots next to "German - Deutsch" and select "Move to the top". Once that is done you can reload the browser and it will work.

I have not noticed any bad effects from changing the language but reverse these steps if you need to remove it.

**Comment by dsiekiera** [comment]
The English translation will follow as soon as possible.

**Comment by MrMattn** [comment]
ich schreib es mal hier rein.
das tool ist aktuell ja wieder top zu gebrauchen. 
Allerdings verschwindet die Leiste  bei mir im OSX mit Chrome ab und an, zb wenn ich die Seite schließe und neu lade.
bzw bei der Erntehilfe steht "undefiniert..."
Dann hilft nur Cache leeren (aufwendiger) oder ganz einfach google chrome komplett schließen und neu das Spiel starten.
warum? keine Ahnung
