### ISSUE TITLE
Verhandlungsassistent bei abweichenden Gütern nicht abbrechen

### ISSUE THREAD

**Issue by dand751801** [dsiekiera/foe-helfer-extension#420]
Üblicher Weise wähle ich im 1. Durchlauf per Shortcuts die ersten Güter:. 2x 1, 2x 2, 2x 3 etc; das spart eine Menge Zeit. Allerdings bricht dadurch der Verhandlungsassistent ab. Zwar gibt es die Möglichkeit, in diesem die gewünschte Reihenfolge festzulegen, ist aber umständlich und kostet eine Menge Zeit.

Es wäre daher wünschenswert, wenn der Verhandlungsassistent bei allen Durchläufen die eingezahlten Güter ermittelt und mit diesen dann die Berechnungen weiter führt.

**Comment by andrgin** [comment]
DerVerhandlungsassistent kann selbst gar nicht rechnen. Hier wird lediglich auf vorberechnete Tabellen zurückgegriffen, da der Vorgang ziemlich rechenintensiv ist und in den meisten Fällen nicht in Echtzeit stattfinden kann. Nur zum Vergleich: Die 10 Güter 4 Runden Tabelle braucht mit Multi Core Optimierung auf einem i7 9900K immer noch über 13 Stunden.

Ein Weiterrechnen mit falsch ausgewählten Gütern wäre also nur nach dem ersten Zug 
möglich und nur wenn lediglich die Reihenfolge vertauscht wurde. In allen anderen Fällen kann nicht weitergerechnet werden, da es einfach für den Fall keine Werte gibt.

**Comment by dand751801** [comment]
Das Weiterrechnen nur nach dem ersten Zug, wenn nur die Reihenfolge vertauscht worden ist, würde zumindest alles bis 5 Güter erschlagen. Von daher: Wäre definitiv ein Mehrgewinn, denn aktuell verwerde ich ihn gar nicht, da er immer nur "manuell weiterspielen" meldet.

Kann mir echt nicht vorstellen, daß die Berechnung derart kompliziert sein soll...
- Münzen, Vorräte und die billigsten/meist vorhandenen Güter zuerst
- ggf. weitere Güter anvisieren, solange noch welche unbekannt sind
- Puzzeln, wo was hinkommen könnte

Von daher: Gut zu wissen, daß mein Gehirn noch mit einem i7 mithalten kann. :-D

**Comment by Th3C0D3R** [comment]
Ich find deine antwort eine Frechheit..
nur weil du halt die falschen Güter auf die falsche position setzt und dir dadruch den Nutzen des Assistenten zerstörst. Ich komm mit dem sogut klar, das er mir zu 80% immer ein Erfolg verspricht (die restlichen 20% sind Verhandlungen mit entweder 8 oder mehr Gütern oder weil es einfach zufall ist)
"Puzzeln, wo was hinkommen könnte" ist eine Aussage die zeigt, das du keine Ahnung von wahrscheinlichkeitsrechnung hast.

Wenn du einen (besseren) lösungsvorschlag mit fertigen, ressoursensparenden funktionen hast, die das errechnen, kannst dich gerne nochmal melden.

**Comment by andrgin** [comment]
Ein bisschen herumpuzzlen kann man manuell auch. Das Ziel des Verhandlungsassistenten war nicht, dass das Ganze schneller geht sondern um die höchste Lösungswahrscheinlichkeit raus zu bekommen. Zusätzlich wird auch noch versucht den Güterbedarf der teuren Güter zu optimieren. Es soll nicht irgendeine Lösung präsentiert werdensondern die Beste.

**Comment by dand751801** [comment]
@Th3C0D3R 
So wie du meine Antwort als "Frechheit" einstufst, so bin ich mit deiner auch nicht sonderlich glücklich. 

Nur weil ich Gut D (idealer Weise Münzen) nicht wie vorgegeben in Slot 1 sondern in Slot 5 packe - weil das mit 2x Taste 5 einfach viel einfacher geht -, hat das absolut keinen Einfluß auf die Wahrscheinlichkeiten. Auch auf die schonende Verwendung der Güter hat das keinen wesentlichen Einfluß.

Daher resultierte meine Anfrage, ob der Verhandlungsassistent anstelle der Vorgegebenen Güter/Slots auch jene berücksichtigen kann, die dann tatsächlich verwendet wurden.

Wahrscheinlichkeiten haben den gravierenden Nachteil, daß sie nicht beherrschbar sind. Eine hohe Wahrscheinlichkeit kann genauso gut scheitern, wie eine schwindend geringe. Einzig die Anzahl der Möglichkeiten läßt sich einschränken. Bleiben mehr Güter als Slots übrig, ist das Ganze nun mal Puzzle. Aber darum ging es mir gar nicht. Ich wollte auch keinem vor die Nase stoßen.

**Comment by someone97563** [comment]
Ich glaube hier lässt sich das Problem auch teilweise anders lösen, als die Tabellen neu aus zu rechnen, zumindest so, dass er nur in besonderen Fällen nach der ersten Runde "aufgibt". Ich probiere das mal aus.

**Comment by someone97563** [comment]
Ab der nächsten Version kann der Verhandlungs-Assistent vertauschte Plätze/Güter erkennen und sich anpassen, im letzteren Fall kann das heißen, das die vorgeschlagenen Güter teurer sind, als eigentlich vorgeschlagen werden, wenn man sich an die Vorgabe hält.
Momentan werden die Güter noch nicht vorsortiert, so dass das doppelte Drücken der Nummerntasten nicht direkt vorgeschlagen wird. Dafür fehlt noch eine Sortier-Information.
