### ISSUE TITLE
Weitere Filter für Info-Box

### ISSUE THREAD

**Issue by dand751801** [dsiekiera/foe-helfer-extension#422]
Filtert man in der Info-Box nach Nachrichten wird es schnell noch unübersichtlicher, als das FoE-Nachrichtensystem selbst.

Es wäre grandios, wenn man (insbesondere bei Nachrichten) sowohl nach Spielernamen als auch nach Typ des Nachrichtenanhangs, ggf. auch nach Teilen der Nachrichten (bspw. aktuelle Ziele der Gildengefechte, solange hier ein bestimmtes Format eingehalten wird), filtern könnte.

Noch genialer wäre es - sofern möglich -, wenn man dann je nach Nachrichtenanhang auch noch die angehängten LGs filtern könnte. Das würde Beteiligungen in den Förderketten um ein Vielfaches verbessern.
Auch die Handelsnachrichten könnten nach bestimmten Güter (je Angebot, Nachfrage) gefiltert werden.

**Comment by Th3C0D3R** [comment]
klingt gut.
wir besprechen mal wie man das grafisch lösen kann ^^

**Comment by SkateScout** [comment]
Der alte Filter mit den Checkboxen hatte 2 Vorteile:
1) Man konnte sofort sehen welche Filter Aktiv sind und
2) Man musste in nach dem umstellen nicht extra zuklappen.
Wie wäre es wenn man ein Menü Button macht und dann in dem Title
ALL , Handel, Gex, GG Auktion, +1 Grün im Anzeigt.
Damit weis man was Aktiv ist ohne viel Platz zu verschwenden.
Einen Spieler Filter könnte man dann über einen Menü Button Realisieren der es erlaubt in einem Textbox eine Regex für den Nachrichtentext anzugeben. Damit wäre es dann extrem Flexibel.
Im Titel würde ich dann nur "REGEX"/"CUSTOM" anzeigen.

**Comment by Th3C0D3R** [comment]
wie gesagt, man kann die Infobox noch erweitern.
Grafisch muss man das nur besprechen damit das ersichtlich ist welche aktiv sind.
Auch habt bitte geduld wenn es eventuell nicht nächstes Update kommt.
Mir machen das schließlich in unserer Freizeit, oder so 😄

**Comment by SkateScout** [comment]
Denke das alle hier eure Arbeit zu schätzen wissen und keiner Drängeln will. Wollte nur möglichkeiten Aufzeigen wie man es evtl lösen könnte.

**Comment by outoftheline** [comment]
De es mittlerweile einen Textfilter gibt, ist der Wunsch damit hoffentlich erfüllt :)
