### ISSUE TITLE
Nachbarn

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#423]
VON: [Nachbarn](https://forum.foe-rechner.de/d/100-nachbarn)

Hätte da mal eine Frage,
wäre es Technisch machbar, die Armeen der Nachbarn zu Loggen?

so das wenn ich jemanden Angegriffen hab in der Nachbarschaft, das mir dann in einer liste Angezeigt wird, welche Armee er bei meinem Angriff drin hatte und welche Prozente Angriff und Deff derjenige hatte ?

dachte da nicht an eine Live Darstellung, lediglich eine Liste was zu dem Zeitpunkt meines Angriff in der Stadt drin stand.

**Comment by andrgin** [comment]
Das PvP Feature wurde entfernt: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
