### ISSUE TITLE
Kleiner Bug beim Münzen Rechner

### ISSUE THREAD

**Issue by Th3C0D3R** [dsiekiera/foe-helfer-extension#424]
[Kleiner Bug beim Münzen Rechner](https://forum.foe-rechner.de/d/111-kleiner-bug-beim-munzen-rechner)

Es gibt da wohl eine kleine Fehlberechnung wenn man auf der GEX Karte war, dann zeigt der "Münzen in FP"-Rechner falsche Werte an.
http://prntscr.com/qqptfb

**Comment by IchChefDuNixx** [comment]
es werden die kosten der medaillen für versuche genommen, aber wird aktualisiert wenn man in der stadt wieder den richtigen preis einliest. könnte man, nachdem das gefixt wurde, nicht auch die kaufbare menge an versuchen der gex anzeigen?

**Comment by andrgin** [comment]
1.) Ja der bisherige Code ist auch auf das "Versuche kaufen" Fenster angeschlagen. Das wird im nächsten Update behoben.

2.) Ja theoretisch könnte man auch die Versuche berechnen. Allerdings ist es wahrscheinlich blöd, wenn man das in die Leiste zu den FP dazu legt. Kannst du dafür ein eigenes Issue aufmachen.
