### ISSUE TITLE
Army suggestion like negotiation suggestion

### ISSUE THREAD

**Issue by Redline1969** [dsiekiera/foe-helfer-extension#425]
It would be really nice to have an army suggestion when you go battle an army. It would act similarly to the negotiation suggestions and give you an idea as to which military units should used against the current army you are battling.

I think this would be helpful instead of always having to look at which unit is what type and then what it is good against.

Thanks.

**Comment by andrgin** [comment]
Do you know an algorithm how this could be calculated other than for the obvious choices when there are 8 units of one type.
Negotiation needed a lot of computing power (13 hours for the 10 goods 4 turn simulation), but it was still doable. With millions of different unit combinations each having their own AI on different terrain I dont see a solution.
Well yes I could simply compare the stats ignoring all abilities and differences in speed/range, but I dont think this would make much sense.

**Comment by Redline1969** [comment]
I was thinking more about a simple way of looking at the opposing army and
suggesting what would be best for defeating it. So for example, Ranged
units are good against Heavy units, Fast units are good against Ranged
units, Light units are good against Fast units, etc.

I may be oversimplifying it as I am not the best at battles and there may
be way more involved than what I am thinking, but this would be a nice help
as I can never remember what is good against what.

Thanks,

Scott

**Comment by Vloxxity** [comment]
It could initially suggest units based on the attack bonus 1 by 1 / 1 vs 1
so if the enemy has 4 ranged and 4 fast
it would suggest 4 fast and 4 Light Units
And it could save user chosen armys that have a better result than that if you find a solution to consider the Atck bonus The Player has through GBs

**Comment by saml1991** [comment]
Glad I found this, I had a similar idea. Some logic would be of great help for when you are trying to autobattle quickly. Vloxxitys suggestion is good. To add to it there are certain unit combinations that guarentee loss:
if 'enemy has stealth unit' and 'my units are all ranged' raise alarm
if  'enemy has swarm unit' and 'my units are all artillery' raise alarm

**Comment by mrok-gmx-de** [comment]
What about the intelligence of the crowd. I.e. in GEX there are always the same combination of troups. When an user  wins a battle, you can transmit (if the user has opt in) his setup to your server and upvote it. This will increase the chance for other players to win the same battle, too.

**Comment by Vloxxity** [comment]
> What about the intelligence of the crowd. I.e. in GEX there are always the same combination of troups. When an user wins a battle, you can transmit (if the user has opt in) his setup to your server and upvote it. This will increase the chance for other players to win the same battle, too.

Thats what i ment in the last sentence of my last comment!
I maybe didn't make it clear enough to save it globally not only for the user.

**Comment by andrgin** [comment]
https://github.com/dsiekiera/foe-helfer-extension/issues/860
