### ISSUE TITLE
Ereignisse- Foe-Helper

### ISSUE THREAD

**Issue by john-empire** [dsiekiera/foe-helfer-extension#426]
Hallo,
vorab schon mal ein großes Danke für euer klasse Tool.
In dem Ereignisse- Helper erscheint "große Strasse" also wahrscheinlich Doppelstrasse gemeint, aber ich habe keine Doppelstrassen da ich erst im Kolo-ZA bin.
Bitte um Aufklärung, da schon andere Gildies deswegen gefragt haben.

LG, John

![image](https://user-images.githubusercontent.com/51168213/72809790-a3bdbc80-3c5c-11ea-99e8-de55e3719cd1.png)

https://prnt.sc/qqrv0z

**Comment by timmep90** [comment]
Guten Tag,
theoretisch würden diese Objekt auf Doppelstraßen spawnen, sobald diese Straßen gebaut werden.
Dass sie auch in unteren Zeitaltern spawnen geht von InnoGames aus und hier kann von den Entwicklern der Extension nichts gemacht werden (außer diese Ereignisse manuell auszuschließen).

Dieses wird bereits in einem Thread im deutschen Forum diskutiert: https://forum.de.forgeofempires.com/index.php?threads/wie-sammelt-man-unsichtbare-ereignisse.38250/page-2#post-344917
Ob es von InnoGames als Fehler anerkannt und behoben wird steht zum momentanen Zeitpunkt noch aus.

**Comment by john-empire** [comment]
Danke für Deine rasche Antwort.

Am Di., 21. Jan. 2020 um 14:53 Uhr schrieb timmep90 <
notifications@github.com>:

**Comment by dsiekiera** [comment]
@john-empire der @timmep90 hat recht. 

Wir machen aber noch einen Filter rein, damit das gar nicht erst auftaucht und für Verwirrung sorgen kann.

**Comment by andrgin** [comment]
Ich denke nicht, dass es Inno Games als Fehler anerkennt, da sich die Fehler nur auf die übertragenen Daten bezieht und nicht mit freiem Auge sichtbar ist. Theoretisch könnte man ja mit Diamanten jederzeit ins nächste Zeitalter wechseln und eine doppelte Straße bauen, um das Ereignis einzusammeln.

Was den Filter angeht so denke ich dass wir auf < JHWD filtern sollten. Darüber könnte man ja ganz einfach doppelte Straßen bauen, um das Ereignis auszulösen.
