### ISSUE TITLE
stadtuebersicht in chrome

### ISSUE THREAD

**Issue by pluto1245** [dsiekiera/foe-helfer-extension#427]
Hi, 
stadtübersicht ladet bei chrome Version 79.0.3945.130 (Offizieller Build) (64-Bit) Nicht! 
lg

**Comment by Th3C0D3R** [comment]
Beim klick auf das icon?

Beta oder richtiger Server?

**Comment by pluto1245** [comment]
beim kicken auf das icon ... 
und fp rechner ist nicht vorhanden aber wenn man bei gex medis kauft dann steht da ein sehr grosser wert da ... wahrscheinlich kaufbare versuche durch medis oder ähnlich ...

**Comment by pluto1245** [comment]
fp - münz rechner gemeint ..

**Comment by pluto1245** [comment]
richtiger rechner ... 
auch bei nachbarn ladet die übersicht karte nicht ... ( ist leer )

**Comment by outoftheline** [comment]
Hi, hast du das Problem noch?

**Comment by andrgin** [comment]
Sollte mittlerweile gefixed sein
