### ISSUE TITLE
Kostenrechner defekt!?!

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#428]
https://prnt.sc/qqvlk8

ging vor ca 3-4 Std noch...jetzt zeigt er ihn so komisch an.

Chache reset bringt nichts

**Comment by andrgin** [comment]
Kannst du mal die Entwicklerkonsole öffnen (F12) und schauen, ob da ein Fehler in der Konsole angezeigt wird.

**Comment by MrMattn** [comment]
bitte mehr Infos...wenn ich F12 drücke sieht es so aus:
https://prnt.sc/qr2wji

**Comment by Th3C0D3R** [comment]
in der Entwicklerkonsole auch den "Console" Tab anklicken ^^ danach erst die den Kostenrechner öffnen

**Comment by MrMattn** [comment]
https://prnt.sc/qr8m35

da tut sich nichts

**Comment by andrgin** [comment]
Kannst du mal.schauen, ob das Problem mit der aktuellen Version behoben ist?

**Comment by MrMattn** [comment]
hi
mit 2.4.1.1 ist alles wieder ok.
danke!
