### ISSUE TITLE
Gesamter Gewinn der FP von Legendären Bauwerken

### ISSUE THREAD

**Issue by Carlos420DE** [dsiekiera/foe-helfer-extension#429]
Moin Moin,
Ich hätte da einen Wunsch. Und zwar würde ich gerne sehen können wieviele FP ich überhaupt in LGs aktuell investiert habe und am besten noch wieviel Gewinn ich bei aktuellem Archenwert erzielen würde.

**Comment by Th3C0D3R** [comment]
Davon gibts schon genug offene Wünsche hier 😅 wird kommen

**Comment by Th3C0D3R** [comment]
Also im Spiel ist das erst möglich wenn man das Fenster auf macht wo man es sowieso sieht, erst dann werden die Daten von Inno übertragen.
Deswegen die Frage: ist es dann noch erwünscht? weil um das zu updaten man eh in das Rathaus und auf die Beteiligungen gehen muss @Carlos420DE

**Comment by Th3C0D3R** [comment]
Ist in der Beta nun drin. Geht aktuell als kleines Fenster auf mit der Anzahl investierter FP und dem aktuellen Gewinn (Investiert + Gewinn sind dann das was man am ende bekommen würde)
11c236e

**Comment by dsiekiera** [comment]
#413
