### ISSUE TITLE
Extension geht nicht auf allen Welten (Chrome Cache Problem)

### ISSUE THREAD

**Issue by dsiekiera** [dsiekiera/foe-helfer-extension#43]
**Lösung Windows:**

- Stadt betreten
- F12
- In der Konsole den Reiter "Network" anwählen und Haken bei "Disable Cache" setzen
- Bei geöffneter Konsole F5
- F12

**Lösung Mac:**
- Stadt betreten
- CMD + Umsch + i (Konsole öffnen)
- In der Konsole den Reiter "Network" anwählen und Haken bei "Disable Cache" setzen
- Bei geöffneter Konsole CMD + R
- CMD + Umsch + i (Konsole schliessen)

Das solle in 98% alle Fälle helfen.

**Comment by MrMattn** [comment]
wenn ich (osx) auf Network gehe...ist der Haken bereits da!?

**Comment by RosiSol** [comment]
Danke für die Info, bei funktioniert jetzt wieder alles einwandfrei. LG :)

**Comment by ClaesSparre** [comment]
Guten Tag, 
"Network/Disable Cache" ist aktiviert. Es funktionierte auch. Seit ca. 4 Tagen wird die Extension auf einer  Welt nur nach mehren Neustarts des Spiels angezeigt. Seit heute wir sie auf einer Welt nicht mehr angezeigt. Egal, ob man die Browserdaten bereinigt, Spiel neu startet, sich neu auf FoE-Helfer einloggt. Woran liegt es? Was kann man noch unternehmen, damit diese tolle Erweiterung -am besten gleich mit Start des Spiels- wieder einwandfrei funktioniert. (Andere Chrome Extensions funktionieren ja auch ohne "Extra Aufwand" und diese konnte es ja auch mal....)

**Comment by ClaesSparre** [comment]
Ergänzung: Jetzt habe die FoE-Helfer Extension deinstalliert. Browser bereinigt. Neu installiert.
Es wird der verschiebbare "Tavernen Badge" angezeigt. Sonst nichts. Das soll jetzt mal einer verstehen....
