### ISSUE TITLE
Icons/Buttons doppelt

### ISSUE THREAD

**Issue by Elschen** [dsiekiera/foe-helfer-extension#430]
Nur auf der Welt Noarsil habe ich die neuen Buttons doppelt in der Leiste: Ereignisse, Stadtansicht und Eventquestliste. Letztere funktioniert leider nicht - aber auf allen meinen Welten.

**Comment by andrgin** [comment]
Wird gerade dran gearbeitet: https://github.com/dsiekiera/foe-helfer-extension/issues/411
