### ISSUE TITLE
Event Questliste Nur die Aufgaben 8 bis 13

### ISSUE THREAD

**Issue by slayerkenya** [dsiekiera/foe-helfer-extension#432]
Beim Batton Event Quest-liste kommen nur die aufgaben 8 bis 13 die ich schon lange abgearbeitet habe. Ich finde die IDE toll das man schnell nachscheuen könnte aber es müsste halt auch alle aufgaben da sein oder noch besser einem die nächsten aufgaben zeigen die kommen.

**Comment by andrgin** [comment]
Ja ist schon bekannt. Da gibt es noch ein paar Probleme mit dem Auslesen der Events: https://github.com/dsiekiera/foe-helfer-extension/issues/405
