### ISSUE TITLE
Filtereinstellung bei Info Box bitte speichern

### ISSUE THREAD

**Issue by RastoDE** [dsiekiera/foe-helfer-extension#435]
Für mich wäre es eine große Hilfe wenn die zuletzt ausgewählten Filter der Info Box erhalten blieben. Es interessieren mich meist nur 1 oder 2 Themen dort und von daher ist es etwas unkomfortabel wenn ich den Filter bei jedem Aufruf jedesmal wieder neu einstellen muss.

**Comment by Th3C0D3R** [comment]
Kommt im nächsten Update 😉
