### ISSUE TITLE
Seiten Leiste Auto Minimieren 

### ISSUE THREAD

**Issue by sunniboi** [dsiekiera/foe-helfer-extension#436]
Seitenleiste müsste Verschwinden in der Seite oder die Task Anordnung ändern können oben unten links rechts Bildrand . Verkleinern zu sein, sie stört das Spiel. Ich habe etwas nicht gleich einsammeln können . Ereignisse ! War zwar nur ein Boot aber es ist schon im weg gewesen.

**Comment by RastoDE** [comment]
Möglichkeiten:
1. Doppelklick auf oberen Blätterpfeil minimiert die Toolbar bzw. vergrößert wieder falls minimiert
2. Bei Settings einstellbar wieviel "Kacheln" angezeigt werden sollen damit die Leiste nicht so groß ist.

**Comment by dsiekiera** [comment]
> 2. Bei Settings einstellbar wieviel "Kacheln" angezeigt werden sollen damit die Leiste nicht so groß ist.

Ist bereits seit 2 Versionen integriert.

**Comment by RastoDE** [comment]
Danke, bin begeistert von diesem Feature. Hab es leider bisher übersehen.
