### ISSUE TITLE
LG Blaupausen finder.

### ISSUE THREAD

**Issue by sunniboi** [dsiekiera/foe-helfer-extension#437]
Wer hat zum beispiel ein LG kurz vorm Level suche. Dann kann man und sollte denjenigen eine PN schreiben . kann ich bei die BP haben, habe ich gefunden bei dir , brauche ich beispiel P3 . Viel leichter als suchen manuell! Auch bei Nachbarn und Freunde . Alle LG müssten aufgelistet sein , darunter Kategerosiert Freunde Gilde Nachbarn . Dazu dann die möglichen BP . War eben eine idee weil mich das schon lange nervt diese Manuelle Sucherei

**Comment by outoftheline** [comment]
Die Daten liegen erst vor, wenn man ein LG öffnet, an dieser Stelle kann der Helper nichts verbessern.
