### ISSUE TITLE
Spenden in die Gildenkasse /Liste/Filter 

### ISSUE THREAD

**Issue by Kivschranz** [dsiekiera/foe-helfer-extension#438]
Hi ...
Wir beobachten in Unserer Gilde immer die Spenden  in die Gildenkasse nachdem wir wir dazu aufgerufen haben. Es ist sehr mühselig sich durch diese einfache Liste (siehe: Gilden Menü (G - und dann oben das unscheinbare Menü mit dem punkt -Beiträge zur Gildenkasse-) )  zu arbeiten und dann in eine Exeltabelle zu schreiben wer, wie viel, von jedem Gut wirklich gespendet hat ..es wäre eine echte  Erleichterung wenn man eine liste hätte bei der man einfach einen Zeitraum festlegt  .. die Spenden aus LG-Spenden raus nimmt und dann vielleicht noch kopieren könnte .

ich glaub das ist Programmiertechnisch nicht sehr schwer ..wäre aber eine echte Hilfe und würde so manchen tag eine stunde arbeit ersparen 

Grüße Kiv

**Comment by Barbar65** [comment]
Ich fände das auch sehr hilfreich und unterstütze die Idee.

**Comment by andrgin** [comment]
Das Exportfeature ist mittlerweile schon implementiert allerdings muss man sich weiterhin manuell durch die Seiten klicken. Das können (bzw. dürfen) wird nicht automatisieren.
