### ISSUE TITLE
Eigenanteilsrechner - Externe FPs

### ISSUE THREAD

**Issue by JHCD** [dsiekiera/foe-helfer-extension#44]
Hi, 

1. Wenn ich bei mehr als einem Platz externe FPs eintrage, ist es Zufall, ob der Rechner danach korrekt funktioniert.

2. Könnte man das Ext.-Feld so einrichten, dass die 0 überschrieben wird, sobald man etwas in das Feld schreibt? (placeholder anstatt value)

**Comment by JHCD** [comment]
Geht gerade mal wieder nicht, hier ein paar Bilder:

1. Eintrag geht:
![image](https://user-images.githubusercontent.com/12496340/60538073-2b1c0080-9d0a-11e9-805c-27c1cd4e09ff.png)

2. Eintrag liefert nicht das erwartete Ergebnis:
![image](https://user-images.githubusercontent.com/12496340/60538169-4dae1980-9d0a-11e9-9ccc-b06575a1a123.png)

**Comment by andrgin** [comment]
Ist in der aktuellen Version behoben
