### ISSUE TITLE
Ingame - Toasts

### ISSUE THREAD

**Issue by someone97563** [dsiekiera/foe-helfer-extension#446]
Statt der System-Benachrichtigungen wäre es schön, die Benachrichtigungen die man als Reaktion auf Aktionen im Spiel bekommt auch im Spiel erscheinen, was auch nicht ständig die Systemsounds auslöst.

Hierfür könnte man Toasts nutzen, die dann in einer Ecke für eine kurze Zeit auftauchen.

**Comment by andrgin** [comment]
Also ich wäre dafür. Nicht jeder hat die Windows 10 Benachricbtigungen aktiviert. Bei meinen PCs sind die in der Regel alle deaktiviert.

**Comment by ljettinger** [comment]
on a sidenote, all my win10 notifications appear in german, not sure why, but they do... lol

**Comment by andrgin** [comment]
Mittlerweile implementiert
