### ISSUE TITLE
Technologien (Kosten für Forschung berechnen)

### ISSUE THREAD

**Issue by EdwintheFirst** [dsiekiera/foe-helfer-extension#447]
Hallo.

Ist es möglich das man die Güter weglässt die nicht im Forschungsbaum des ZA benötigt werden das man auswählt?
Es zeigt auch die Güter an die man gebraucht hätte um eine Forschung eines unteren ZA zu machen, das man aber ausgelassen hat.
PS: Der Text wird automatisch geändert?!

**Comment by Th3C0D3R** [comment]
warum machst du nicht die Forschung die du ausgelassen hast? 

Welchen Text meinst du?

**Comment by andrgin** [comment]
Hast du da einenScreenshot dazu? Sind das ein paar Gütergebäude in Eisenzeit/FMA?
Technologien, die keinen Nachfolger haben werden bereits gefiltert aber es gibt ein paar einzelne in Eisenzeit/FMA wo das eine optionale 2er Kette. Da greift die Filterlogik nicht ganz.

**Comment by EdwintheFirst** [comment]
In der Postmoderne braucht man keine Seide, Porzellan oder Papier

Mit sportlichen Grüßen
Edwin Gatschnig

Von: Gindi4711<mailto:notifications@github.com>
Gesendet: Donnerstag, 23. Jänner 2020 08:06
An: dsiekiera/foe-helfer-extension<mailto:foe-helfer-extension@noreply.github.com>
Cc: EdwintheFirst<mailto:edwin.gatschnig@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Technologien (Kosten für Forschung berechnen) (#447)


Hast du da einenScreenshot dazu? Sind das ein paar Gütergebäude in Eisenzeit/FMA?
Technologien, die keinen Nachfolger haben werden bereits gefiltert aber es gibt ein paar einzelne in Eisenzeit/FMA wo das eine optionale 2er Kette. Da greift die Filterlogik nicht ganz.

**Comment by Th3C0D3R** [comment]
ähm natürlich braucht man das, du musst diese Güter veredeln. Deswegen werden sie dir angezeigt

**Comment by andrgin** [comment]
Neindas hat mit dem veredeln nichts zu tun. Das stamm noch aus einem ZA davor. aus welchem weiß ich nicht. Deshalb die Frage nach dem Screenshot.

**Comment by andrgin** [comment]
Ich habe noch einmal gesucht. Kann es sein, dass du im Industriezeitalter nicht alle Millitärgebäude freigeschaltet hast?

**Comment by Th3C0D3R** [comment]
Doch, weil ich, wenn ich bei mir anschaue was ich für Güter in den nächsten ZAs brauche auch die von den unteren ZAs angezeigt bekomme.

**Comment by Th3C0D3R** [comment]
Ok vergesst mein letzten Kommentar 😅 ich wieder 🤦🏻🙈

**Comment by andrgin** [comment]
Mittlerweile werden optionale Technologien (keine Nachfolgertechnologie) und Technologien aus vorherigen ZA ausgeblendet
