### ISSUE TITLE
[Feature request] GBG Tracking

### ISSUE THREAD

**Issue by Damianbv** [dsiekiera/foe-helfer-extension#448]
I'd like to see a small thing added in the Player overview tab.

Currently it shows the players, negotiations and fights:
I'd like an extra row that shows the changes between the last update and this update in fights and negotiations. 
So it would show like this:
![ba33ec5f4022afbef327a6f73a263528](https://user-images.githubusercontent.com/815721/72980644-4439eb00-3ddb-11ea-8589-a579823a92d1.png)

This will greatly help with showing who is online and who is fighting what.

**Comment by Th3C0D3R** [comment]
this is already implementet. If you visit it after some fights and negotiations you can see the difference

**Comment by Damianbv** [comment]
Thank you
