### ISSUE TITLE
Als Besitzer eines Dynamischen Turms möchte ich möglichst Gebäude hoher ZA motivieren, um die beste Güterausbeute zu erreichen.

### ISSUE THREAD

**Issue by JHCD** [dsiekiera/foe-helfer-extension#45]
Als Besitzer eines Dynamischen Turms möchte ich möglichst Gebäude hoher ZA motivieren, um die beste Güterausbeute zu erreichen.

Könnte - wie beim Plüdern - ein Fenster aufgehen, welches die motivierbaren Gebäude inkl. ZA anzeigt? 
Liste nach ZA sortiert, 
Nicht motivierbare Gebäude müssen nicht angezeigt werden.

**Comment by Th3C0D3R** [comment]
da gleich wie #46 schließ ich hier mal, doppelt braucht mans ja nicht
