### ISSUE TITLE
Falsche Anzahl der FP beim Level-Up/Info Box

### ISSUE THREAD

**Issue by IchChefDuNixx** [dsiekiera/foe-helfer-extension#451]
![bbcha](https://user-images.githubusercontent.com/47155538/73015795-ff36a880-3e1c-11ea-8cb7-705400543e0f.png)
Zeigt die FP von 2 Stufen an. Immernoch besser als 0 :)

**Comment by MilaPi** [comment]
Got similar bug just now 
![image](https://user-images.githubusercontent.com/22200982/73560453-4ba26980-4457-11ea-92c4-aa34b6828d20.png)

**Comment by Th3C0D3R** [comment]
Ist in beta behoben ;) beim nächsten updaten dann auch in den store versionen
