### ISSUE TITLE
GBG log including player name

### ISSUE THREAD

**Issue by dlowe2k2** [dsiekiera/foe-helfer-extension#453]
that would be very helpful

**Comment by SkateScout** [comment]
This information is not transmited bei the game server. And so also not posible to be displayed.

**Comment by dlowe2k2** [comment]
Thank you

Dustin Lowe Lake Catherine Blueberries LLC 352-536-4324 

    On Thursday, January 23, 2020, 4:16:17 PM EST, SkateScout <notifications@github.com> wrote:  
 
 
This information is not transmited bei the game server. And so also not posible to be displayed.

**Comment by andrgin** [comment]
Not possible see: https://github.com/dsiekiera/foe-helfer-extension/issues/860
