### ISSUE TITLE
Ereignisse in der Auflistung fehlerhaft?

### ISSUE THREAD

**Issue by Kaye68** [dsiekiera/foe-helfer-extension#454]
Ich habe in der Auflistung der Ereignisse vier Stück, die angeblich auf einer "großen Straße" sein sollen. Bei mir gibt es aber keine großen Straßen. Ist das vielleicht ein Fehler?
![image](https://user-images.githubusercontent.com/56027214/73023788-88a1a700-3e2c-11ea-94a5-d97866f3eaaf.png)

**Comment by SkateScout** [comment]
Nein kein Fehler das Spiel Ordnet dir diese Ereignisse zu du kannst sie aber leider nicht bekommen.
Also wenn ein Fehler bei dem Spiel selber.

**Comment by EdwintheFirst** [comment]
Bei mir ist es das Selbe, bin in der Eisenzeit, also gibt es keine große Straße, und bei mir zeigt er auch immer Ereignisse an.
![Unbenannt](https://user-images.githubusercontent.com/60211221/73241178-92673980-41a1-11ea-96fa-c7c1b67c9f38.PNG)

**Comment by Th3C0D3R** [comment]
Nein, Inno überträgt alle möglichen Ereignisse. Egal ob der Spieler zb eine große Straße (2x2) hat oder nicht.
Es wird noch ein Update kommen wo das Zeitalter mit berücksichtigt wird.
