### ISSUE TITLE
Security leak?

### ISSUE THREAD

**Issue by Damianbv** [dsiekiera/foe-helfer-extension#455]
I was wondering if it was the intention that you can swap to any user profile and see all the people they snipe and see the progress on their guilds GE stats? 

I think a lot of personal information is shared with everyone that knows how to swap profiles easily or if someone registers your profile before you do. 

Also I would like to know how I can get my data removed from the database as I don't like people to be able to see who I snipe? 

It says it only shares data for the guild alone but you can still swap to any profile you want or register a profile of someone else. Swapping profiles can be done in the profile part.  

I tried to send this to an e-mail but their is none available.

**Comment by Andi47** [comment]
I just logged in with my email address and a wrong profile name was displayed (NOT my ingame name, so I logged out immediately again). 
What's wrong?

**Comment by Damianbv** [comment]
The issue is that you can even go into any account even without having to register their name.
1. There should be a function within the extension that gives you a random number ingame to proof it's you. 
2. You should NOT be able to swap profiles!!

**Comment by MrMattn** [comment]
vor allem:
HILFE!
habe das eben getestet und im toll (browser) unter Profil andere spieler ausgewählt die dort angezeigt wurden...jetzt kann ich meinen Namen nicht mehr wählen. es stehen warum auch immer nur noch 2 stück zur Verfügung.

**Comment by Damianbv** [comment]
You can change the ID of one of the persons with your own player id and then save and you'll be logged back in. (Inspect element)

**Comment by Th3C0D3R** [comment]
Wait wait wait.. do I understand this right? You can change the Id via Inspect Elements and do some saveroni and are logged in with an other user?

**Comment by Andi47** [comment]
Looks like a CRITICAL issue!!!

**Comment by MrMattn** [comment]
dafür müsste man aber die ID des jenigen kennen!?

**Comment by Damianbv** [comment]
Just go to https://foestats.com/  and then look a person up in the url you'll see the user id, this is the easiest way to find a user id without knowledge of reading json files.

**Comment by MrMattn** [comment]
ich bekomme MEINE Id nicht mehr hin.
ich kann nur noch im profil 2 leute auswählen die ich nicht kenne

**Comment by dsiekiera** [comment]
Vorabfragen verbaut um solche Spielchen zu unterbinden.
