### ISSUE TITLE
Armee-Übersicht lässt sich nicht scrollen

### ISSUE THREAD

**Issue by Waagie** [dsiekiera/foe-helfer-extension#458]
Zuerst möchte ich ein Lob aussprechen, das Tool ist wirklich toll !

Bei der neuen Version kann man in der Armee-Übersicht nicht mehr hoch/herunter scrollen.

Bitte korrigieren, danke für Eure tolle Arbeit ;-) !

**Comment by Waagie** [comment]
Nachtrag: ich benutze das Tool in Firefox

**Comment by andrgin** [comment]
Ich habe es gerade probiert. Bei mir scrollt alles wunderbar mit dem Mausrad. Hat noch jemand das Problem?
