### ISSUE TITLE
Verhandlungsassistent zeigt ausgeschlossene Güter

### ISSUE THREAD

**Issue by dand751801** [dsiekiera/foe-helfer-extension#459]
Der Verhandlungsassistent zeigt auch ausgeschlossene Güter.

![Beispiel 1](https://user-images.githubusercontent.com/60128881/73047924-b829d100-3e77-11ea-84c8-7a162f8fcd1f.png)

Dies könnte evtl. daran liegen, daß nicht die exakt vorgegebene Reihenfolge eingehalten wurde.

FoE-Helper: 2.4.1.1
Chrome: 79.0.3945.117 (Offizieller Build) (64-Bit)

**Comment by andrgin** [comment]
Ja eigentlich sollte schon vorher die Verhandlung mit einemFehler abbrechen wenn es nicht nur ein simples Vertauschen der Spalten ist.

**Comment by someone97563** [comment]
Beim versuch den Verhandlungsassistenten trotz falscher Güter noch zu retten wurden 2 Güter als identisch behandelt, das wurde nun behoben.
