### ISSUE TITLE
Als Spieler möchte ich möglichst Gütergebäude hoher ZA plündern, um die beste Güterausbeute zu erreichen

### ISSUE THREAD

**Issue by JHCD** [dsiekiera/foe-helfer-extension#46]
Als Spieler möchte ich möglichst Gütergebäude hoher ZA plündern, um die beste Güterausbeute zu erreichen.

Bitte die Plünder-Liste um das ZA erweitern. 
Viele Spieler haben Gebäude aus zig Zeitaltern und man ist sich nicht immer sicher, wohin es denn nun gehört. Auch bei den Eventgebäuden ist das eine nützliche Information.

**Comment by DasAtom** [comment]
Dir ist aber schon bewusst, dass man das Zeitalter eines jeden Gebäudes sehen kann wenn man nur mit der Maus darüber hovert? Wenn du also jemanden als plünderbar einstufst und er hat 3 TFs mit Gütern kannst du einfach die Maus darüber halten und herausfinden um welche Art Güter es sich handelt. Das gleiche gilt übrigens auch für dein Issue #45

**Comment by JHCD** [comment]
Ja, aber ich habe keine Lust/Zeit erst die potentiellen Gebäude zu suchen und dann das ZA festzustellen... 
Hier böte die Erweiterung die Change die Zeit, bei täglich 50 Angriffen und Spielern mit durchaus 30 und mehr potentiellen Gebäuden, deutlich zu reduizieren.

**Comment by andrgin** [comment]
Erntehelfer ist entfernt worden: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
