### ISSUE TITLE
Negociation error presenting a previously refused choice

### ISSUE THREAD

**Issue by troll31** [dsiekiera/foe-helfer-extension#460]
Just got a case where negociation gives a bad solution on round 3 (on a 100% luck to complete)
See screenshot with member 5 proposing a wrong choice (already refused on round 2)
[negociation-error](https://user-images.githubusercontent.com/60022095/73054790-976b7680-3e8b-11ea-955d-4346b0f64c5d.png)

**Comment by andrgin** [comment]
Which version did you use? Was this in beta or the release version?

**Comment by troll31** [comment]
Sorry forgot to mention it was from beta

**Comment by andrgin** [comment]
I am closing this because it should already be fixed in beta. Please open a new ticket if you see it again. And please always mention if it happens in beta.
