### ISSUE TITLE
Infobox error?

### ISSUE THREAD

**Issue by sanity65** [dsiekiera/foe-helfer-extension#462]
![infobox](https://user-images.githubusercontent.com/59678978/73063592-52663500-3ec9-11ea-8ab1-0b184d3fd86f.jpg)

**Comment by sanity65** [comment]
I don't see all messages in infobox(

**Comment by Th3C0D3R** [comment]
Its fixed in beta and will be in the next update

**Comment by Th3C0D3R** [comment]
I think so 🙈
