### ISSUE TITLE
Aid list 

### ISSUE THREAD

**Issue by deepthefriedpotato** [dsiekiera/foe-helfer-extension#463]
Would it be possible to assist in aids and maybe even tavern visits in any way? So much time is spent tapping each and every aid every 24 hours.. it would be great if there was a flexible list in which aids could be completed in less clicks.. maybe even just one once the list is made.

**Comment by andrgin** [comment]
Simulation of clicks is a bot. This is against the rules of the game.

**Comment by deepthefriedpotato** [comment]
ah
