### ISSUE TITLE
Login on homepage leads two wrong profile (wrong user)

### ISSUE THREAD

**Issue by Andi47** [dsiekiera/foe-helfer-extension#464]
Hab mich gerade auf der Homepage eingeloggt und:

https://www.dropbox.com/s/y2tapynrtp61h0y/Extension_Homepage_wrong_user.jpg?dl=0 (wie kann ich den Screenshot als Bild einfügen?)

Falscher Name, das bin nicht ich. Mein Ingame-Name ist Andi47

ist mein Account gehackt worden?
Oder haut's mit den Profilnummern auf Beta und Live noch nicht so hin?

Edit: Ach, warum schreibe ich hier auf englisch, hier geht's ja auch auf deutsch ;-)

**Comment by Andi47** [comment]
Scheint mit dem hier zusammenzuhängen: https://github.com/dsiekiera/foe-helfer-extension/issues/455

Und wenn man einfach so in einen anderen Account einloggen kann, ist das als KRITISCHES Security-Leak einzustufen!!

**Comment by dsiekiera** [comment]
Alles ausgebaut. Perma-Loggin adé...
Cookie-Login ausgebaut. Dropdown im Profil entfernt.

**Comment by Andi47** [comment]
bitte wieder öffnen - ich komme beim Login mit meiner Mailadresse immer noch auf den falschen User (immer noch der selbe wie vorher)

da ist also anscheinend immer noch ein DICKER Hund drinnen.

**Comment by dsiekiera** [comment]
Schreib mir bitte mal privat und nenn mir deine Mail-Adresse. Dann schau ich nach der korrekten Vernüpfung.

**Comment by Andi47** [comment]
bin gerade am suchen, aber ich finde nirgends einen Button, um Dir eine PN zu schreiben?

**Comment by dsiekiera** [comment]
Hier hin: mainline.pyracantha@gmail.com

>

**Comment by Andi47** [comment]
Danke - Mail ist unterwegs.
