### ISSUE TITLE
Wunsch: Investitionen - Homepage

### ISSUE THREAD

**Issue by BFlassig** [dsiekiera/foe-helfer-extension#471]
Es währe sehr hilfreich wenn vielleicht auf der Homepage unter Investitionen die Tage des geförderten Bauwerk dabeisteht. 

z.B.: Ich Fördere einen Nachbarn mit 200 FP und habe vielleicht noch einen Gewinn dabei,
verliere ihm aus dem Auge da ich immer 30-40 Leute in meiner Investitionsliste habe.
Dieser Nachbar hört auf zum Spielen und meine FP hängen seit 200 Wochen im Nirvana und ich bemerke es nicht.

**Comment by andrgin** [comment]
Mittlerweile implementiert
