### ISSUE TITLE
Leere Listen

### ISSUE THREAD

**Issue by firefox1970** [dsiekiera/foe-helfer-extension#472]
Hallo zusammen,
bei mir sind in der Statistik die folgenden Listen leer:
---
Events:
Motivationen anderer Spieler
Motivationen aus Deiner Gilde
Gesamt-Motivationen der Gildenmitglieder in Eurer Gilde
Tavernenbesuche von Deinen Freunden

Legendäre Gebäude
---
Habe ich was falsch eingestellt??

Gruß
Firefox

**Comment by ljettinger** [comment]
is this the same issue I'm having here?? Or do I have something else going on?? It's almost like when I log in, it's not connecting to my game character... It was working...
![image_3](https://user-images.githubusercontent.com/18238040/73516236-c6bb3f80-43c5-11ea-88c2-bb1fbed95b6f.png)
