### ISSUE TITLE
'possible deposits' filters, using FP stock and GB type

### ISSUE THREAD

**Issue by saml1991** [dsiekiera/foe-helfer-extension#473]
Add filter similar to 'Info Box' with these options:
Filter 1:  Exclude GB too expensive:
Don't show possible deposits if you don't have enough FP to take it:
filter if ('total'-'payed')/2 > FP-Stock

For example in attached picture, I have 195 FP. To lock a position in Himeji Castle I would need at least (2244-1696)/2=275FP this is more than available 

Filter 2: Only show GB:
List of all great buildings. This is useful when looking for blueprints

![image](https://user-images.githubusercontent.com/54473694/73135465-41890100-403a-11ea-9249-73adbd30345d.png)

**Comment by andrgin** [comment]
Possible deposits have been removed: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
