### ISSUE TITLE
Incidents - a bug?

### ISSUE THREAD

**Issue by Mutor7** [dsiekiera/foe-helfer-extension#474]
Hello, I downloaded the FoeH yesterday. 
It announces that a couple of the BIG ROAD incidents are present in my town, which, in fact, I cannot detect nor collect using "a big building" trick as shown on a video. So, either the info that an incident was present was wrong or the programme causes a conflict unabling me to see/collect those incidents...
The rest of the incidents is announced/found properly.
Thanks for your advice.

**Comment by Th3C0D3R** [comment]
Big road means road 2x2 which you can build from progressive area (one after industrial area) and onward

**Comment by Mutor7** [comment]
Are you telling me that all the incidents are determined of the same kind, time and place for all the players? That's a revelation for me, thank you! Clear now. Cheers

**Comment by someone97563** [comment]
I don't think they are the same for all players, but the server basically sends a list of Incidents to show together with time frame and a location name. Then the game can choose one of those places matching the location name to show the incefent within the given time-frame. As for the big road: the server apparently has no logic to check if the player has a big road or is able to build a big road when createing this list.

**Comment by Mutor7** [comment]
Thank you for your explan,anyway - good to know that everything was o.k. with my eyes, town and programme performace, cheers!

**Comment by 1msummers** [comment]
This is definitely a bug. 

If you invoke FOE's build mode, and then shove all buildings and roads into the save buffer, you can see the undeveloped field for your city. In that field, I can see 3 items (a fallen tree, a bush, and another smaller tree) all of which are made visible (in the normal display) by lifting building from the location of the buggy incident. None of them are actually on roads, although FOE Helper reports them as being "small road" incidents (as mentioned above, they are all actually UNDER other buildings). All 3 of my "small road" incidents persist from one day to the next. I have asked Inno about these "incidents" and they claim that they are just background decorations.

**Comment by Th3C0D3R** [comment]
Its definitely not a bug. 
If the incident data says its on a road than it is on a road. There is no bug. Your perspective is just odd and you think after putting all Buldings into the save slot that the incident is on ground. 

You have to blame Inno for coding it like this so that road incidents are displayed on ground

**Comment by Th3C0D3R** [comment]
Closing this. If there is something new or more, please open a new ticket
