### ISSUE TITLE
Seit dem Update (Chatfunktion) wird fehlt die Plünder-Anzeige

### ISSUE THREAD

**Issue by CybDis** [dsiekiera/foe-helfer-extension#48]
Neuerdings wird nicht mehr angezeigt, was es bei den Nachbarn zu plündern gibt.
Ich habe bereits aus-/einloggen und den Start ohne Cache probiert.

**Comment by DasAtom** [comment]
Siehe https://github.com/dsiekiera/foe-helfer-extension/issues/32#issuecomment-509631099
