### ISSUE TITLE
Produktionsübersicht Reihenfolge der Zeitalter falsch

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#484]
In der Produktionsübersicht ist die Reihenfolge der Zeitalter falsch.

Hier könnte eine kleine Perfektion reinbringen ;-)
lg

https://prnt.sc/qtdua3

**Comment by andrgin** [comment]
Ist geplant: https://github.com/dsiekiera/foe-helfer-extension/issues/278
