### ISSUE TITLE
sidebar not available in full screen in Chrome

### ISSUE THREAD

**Issue by Regaljoe** [dsiekiera/foe-helfer-extension#486]
When playing in full screen mode in Chrome, the side bar disappears.

**Comment by Th3C0D3R** [comment]
just dont use the ingame Fullscreen. use the F11 fullscreen mode then you have it

**Comment by Regaljoe** [comment]
> just dont use the ingame Fullscreen. use the F11 fullscreen mode then you have it

That worked!  Thanks for the quick response!  Love this feature!
