### ISSUE TITLE
Liste der plünderbaren Gebäude sortieren

### ISSUE THREAD

**Issue by 7777777a8** [dsiekiera/foe-helfer-extension#487]
Hallo zusammen,
erst mal vorweg, ich bin ein großer Fan von eurer Extension und das spielen macht mir wieder mehr Spaß, seitdem ich sie verwende. Also danke dafür.
Ich hätte da noch einen Vorschlag, der zwar nicht essentiell ist, aber trotzdem angenehm wäre, wenn ihr einmal Zeit dafür findet. 
Und zwar bin ich zur Zeit im Mars Zeitalter, und plündere daher vorzugsweise Virtuelle Zukunft Güter, falls diese verfügbar sind. Nun priorisiert euer Tool aber forgepunktproduzierende Gebäude in der Liste der verfügbaren Gebäude. Und ich scroll  jetzt halt immer durch die Liste durch und suche nach den passenden Gütern. Das ist alles gut und recht, aber angenehmer wäre es natürlich, wenn man einen Filter setzten könnte, nach welche Gütern oder halt FP man sucht. 
Wie gesagt - nicht essentiell, aber wenn jemand einmal Zeit für solche Kleinigkeiten findet, würde ich mich trotzdem freuen.
Liebe Grüße,
7777777

**Comment by MrMattn** [comment]
oder dass man nach: "wo gibts die meisten FP" sortieren kann

**Comment by andrgin** [comment]
Der Erntehelfer wurde entfernt: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
