### ISSUE TITLE
Negotiation Helper Extra Turns??

### ISSUE THREAD

**Issue by ljettinger** [dsiekiera/foe-helfer-extension#489]
Is it possible to have the negotiation helper continue after diamond purchasing the extra turn(s) instead of erroring out and stopping??

**Comment by andrgin** [comment]
The problem is that the negotiation helper has no logic to solve negotiations on his own. It uses precalculated tables. If the negotiation ends there are no more values in the table.

**Comment by andrgin** [comment]
Already supported. We show all good combinations that are still possible
