### ISSUE TITLE
Negotiation Helper Help [suggestion to functionality]

### ISSUE THREAD

**Issue by ljettinger** [dsiekiera/foe-helfer-extension#490]
Not that the Negotiation Helper logic isn't working, but I've seen the helper not use what I'd call an 'advanced method' that can help in the elimination process... And I've found it very useful while manually negotiating countless times now... Since I've seen the helper not use it at least half a dozen times, I'm guessing it's not included in the logic, but maybe I'm wrong and it's just smarter than I am... 😊😊
Let me see if I can explain this in easy to understand terms, if not, just ask and I'll try again...
Brand new Negotiation with 8 possible choices, so five are selected and come back as 2 aren't used at all and are eliminated (red) and 3 are used but are in the wrong spots (yellow)... So on the next selection, there are 6 choices to pick from, 3 of which haven't been tried at all and 3 which are used, but haven't been found yet... So what I do here is take the 3 selections I have not tried at all just to eliminate the easy ones, and I place them in the yellow spots where the 3 that were in the wrong places were, then place 2 of the 3 that I know are used in the two red spots that were eliminated the first round because I know nothing about those spots... What this does is eliminates the chances of having a spot 2 or 3 rounds in with no other information than 'nothing that's been tried here so far goes here' (red, red, red)... 
By placing completely unknown choices on spots where at least something has been eliminated from going there rather than on a spot where nothing in play has been eliminated, it could possibly remove a guess at the end or use that extra info to help thru process of elimination to find the correct order just because there would be some sort of info on each spot as to what doesn't go there... 
Hopefully that makes sense, if not, just ask... i can probably record a video if needed, just lemme know... thanks...

**Comment by andrgin** [comment]
The negotiation helper does not work with specific strategies. The only rule that is hardcoded is to use 5 different goods in the first round. Everything else is calculated by a simulation that uses a brute force algorithm to check every possibpe guess.

Currently the rules are:
1.) Pick the guess with the highest chance of solving the negotiation.
2.) If there are multiple guesses with the same chance pick the one with the lowest good costs. Good costs are weighted. The first good counts 1 point, the second good costs 2, the third 3 and so on. This weighting table may be fined tuned in the future, but at the moment it seems to be working OK.

In your specific case it seems that selecting 3 of the unused goods in round 2 does not get you a higher chance compared to selecting only 2 new goods, but the third good is the most expensive one, so it is avoided.

**Comment by Timee79** [comment]
Kann man hier vielleicht noch festlegen, dass immer erst Güter des aktuellen ZA verwendet werden, den davon hat man im Normalfall am meisten.

**Comment by syjytg** [comment]
@andrgin Can you please teach me how to generate the tables as other games have similar concept and it will help me a lot?
