### ISSUE TITLE
Fehler beim Verhandlungsassistenten

### ISSUE THREAD

**Issue by PerryHotter** [dsiekiera/foe-helfer-extension#491]
Vorgeschlagene Güter eingesetzt - Bitte manuell weiterspielen
![FG](https://user-images.githubusercontent.com/60373762/73230462-aef17a80-417d-11ea-8d99-1c3a05b2abdb.PNG)

Gütervorrat
![FG2](https://user-images.githubusercontent.com/60373762/73230716-7dc57a00-417e-11ea-823b-cf6789a1f192.PNG)

**Comment by andrgin** [comment]
Tritt anscheinend immer noch auf

**Comment by andrgin** [comment]
Korrektur: Nein doch nicht. Der Bug hier war anders
