### ISSUE TITLE
Investitionsanzeige fehlerhaft bei Liste leg. Gebäude

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#493]
Gehe ich im Rathaus auf die Liste der legendären Gebäude, erscheint ein Investitionsfenster.
Fenster ist zu klein...
und der Gewinn stimmt leider sicher nicht ;-)
Die Investitionen selbst stimmen

https://prnt.sc/qty3kq

**Comment by andrgin** [comment]
Ich nehme einmal an in der Beta?

**Comment by MrMattn** [comment]
ja genau

**Comment by MrMattn** [comment]
besser aber noch nicht gut :-)
https://prnt.sc/quf7fz

Lager plus Umlauf plus Gewinn komme ich auf 37408

**Comment by andrgin** [comment]
Sollte gefixed sein
