### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Vladone2017** [dsiekiera/foe-helfer-extension#494]
New button

How many FP I need to level up all of my Legandary Buldings considering the BP wich I have for each one...:)

**Comment by andrgin** [comment]
So I have blueprints to level my arc up to lvl400. How does this information help me?

**Comment by MrMattn** [comment]
was ein Quatsch.
ich kann meine Arche auf Stufe 3968 bringen...ja und?

**Comment by outoftheline** [comment]
This wouldn't really be useful, sorry.
