### ISSUE TITLE
QUESTION, GB api?

### ISSUE THREAD

**Issue by patrikliska** [dsiekiera/foe-helfer-extension#495]
Hi!
I want to ask if its here any API with all great buildings of my guild members. I need to calculate some gb withdraws (observatory, arc, etc...)

**Comment by andrgin** [comment]
There is no API for the game. What we are doing is reading the data that is transfered from the server to the browser and analyse it. You can check which data is transfered by pressing F12 and opening the Network tab.

**Comment by patrikliska** [comment]
Yes, my question is if you are providing some data after you transfer it all to your app

**Comment by dsiekiera** [comment]
A simple API is planned. So u can send some data to your own server.

**Comment by patrikliska** [comment]
Thats amazing @dsiekiera ! Great job with this extension!! <3 Closing this issue, thanks for response!
