### ISSUE TITLE
Leiste überdeckt rechten Pfeil im Forschungsbaum

### ISSUE THREAD

**Issue by Cycloth** [dsiekiera/foe-helfer-extension#496]
Hallo,

in der neuen Version des Forschungsbaums befindet sich links und rechts ein Pfeil. Der eine wird durch die Helferleiste überdeckt.

Wenn man die Höhe auf 1 festlegt, sieht man ihn:
![image](https://user-images.githubusercontent.com/48488704/73303023-eca1e200-4215-11ea-80b1-b75708d90c12.png)

**Comment by andrgin** [comment]
Ja der Pfeil ist da etwas blöd positioniert. Die Leiste kann ausgeblendet werden, indem man auf den Vollbildmodus im Spiel wechselt. Ist die Frage, ob wir nicht zusätzlich einen Shortcut zum Ausblenden der Leiste machen.

**Comment by timmep90** [comment]
Würde an dieser Stelle etwas gegen ein Einblenden über hover sprechen?
Alternativ dazu kann auch seitlich ein Pfeil zum ein-/aus-klappen des Menüs angebracht werden.

Könnte folgendermaßen (nur in schön) aussehen.
![toggle_menu](https://user-images.githubusercontent.com/17743608/73432514-33412a80-4343-11ea-8d7c-6c3d85c0d202.png)

**Comment by outoftheline** [comment]
Mittlerweile gibt es andere Menü-Einstellungen und das Menü wurde neu positioniert
