### ISSUE TITLE
Große Straße ?

### ISSUE THREAD

**Issue by Encik7** [dsiekiera/foe-helfer-extension#499]
hey hey,

in der ereignis übersicht werden mir sachen auf der großen straße angezeig...

Wo soll die den sein?
Könnte es ein übersetzung Fehler sein oder so ?

Liebe Grüße

**Comment by Th3C0D3R** [comment]
das ist die 2x2 Straße die ab der Jahrhundertwende verfügbar ist

**Comment by ase2-stack** [comment]
Ich bin in meiner Nebenwelt im Hochmittelalter, die Anzeige für Ereignisse, zeigt mir dauernd Ereignisse für 2 spurige Strassen an, die es ab er erst ab der Jahrhundertwende gibt.

**Comment by andrgin** [comment]
Da es öfters zu Verwirrungen kommt wird ab dem nächsten Update das jeweilige Ereignis ausgeblendet wenn man die jeweilige Straße nicht hat.
