### ISSUE TITLE
Eigenanteilsrechner Reihenfolge

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#5]
Hi :) 
Zunächst... Ich lieeebe dieses Plugin. Ganz herzlichen Dank für die Arbeit. Ein Traum!

Die Kopierfunktion ist quasi verkehrt herum. 
Belegt werden (bei größeren LB) im Normalfall die Plätze 1 und 2 zuerst da zusammen safe.
Nun folgen die anderen Plätze einzeln.
Die Button werfen aber die Platzierung genau anders rum aus, so dass man immer die hinteren Plätze raus löschen muss.
Vielleicht wäre die "Hakenvariante" wie hier http://graldron.bplaced.net/ praktikabel?

**Comment by dsiekiera** [comment]
Du meistest bestimmt wie hier um unteren Teil: https://foe-rechner.de/ownpart/index ;-)

Aber ich habe meine Technik von der Webseite übernehmen können und die Hakenvariante verbaut.
