### ISSUE TITLE
Gesamt-Motivationen der Gildenmitglieder in Eurer Gilde

### ISSUE THREAD

**Issue by Horst-Krawuttke** [dsiekiera/foe-helfer-extension#50]
Hier werden mir irgendwelche Leute angezeigt, die aber mit meiner Gilde nichts zu tun haben.
Cache-Leeren hat nichts daran geändert.
Einmal komplett durchs Rathaus klicken hat (im Gegensatz zu gestern) Meldungen von erfassten Spielern erzeugt, so dass jetzt auch moppeln aufgelistet wird.
Die merkwürdigen fremden Spieler sind allerdings immer noch da.
Der gestern gemeldete Fatal Error scheint nicht mehr aufzutauchen.
Allerdings finde ich die Fehlermeldung auch nicht unter erledigt.
Was ist da passiert?

**Comment by JHCD** [comment]
Das liegt daran, dass auch die Personen angezeigt werden, die mal in der selben Gilde wie Du waren... 
An der Lösung arbeiten wir...

**Comment by Horst-Krawuttke** [comment]
Da stehen Leute, die mir so gar nix sagen. MÜsste also mindestens 2 Jahre her sein ....

**Comment by MasterInterceptor** [comment]
Es ist zwar die Funktion vorhanden die Nichtgildis zu löschen, aber die funktioniert leider nicht
