### ISSUE TITLE
Eigenanteilsrechner zeigt keine sicheren Plätze an

### ISSUE THREAD

**Issue by mordillo666** [dsiekiera/foe-helfer-extension#501]
![Eigenanteilsrechner](https://user-images.githubusercontent.com/59010411/73349104-e13cce00-428a-11ea-8bc7-d7149331d99b.jpg)

Wenn ich jetzt 180 EA einzahle, ist P2 mit 65FP nicht sicher, da ja noch einer mit 5FP da ist. 
Es ändert sich an den Farben der Zahlen auch nichts, wenn ich P2 von 85 auf 110 umstelle, womit P2 definitiv sicher wäre.

Soll das so sein, dass mir das nicht angezeigt wird, oder ist das ein Bug?

**Comment by dsiekiera** [comment]
Nein. Du liest das nur flasch.

Du müsstest jetzt nur 9 FP einzahlen, dann wäre P2 schon save. Die kleine (-180) zeigt nur an wie viel due mit den 9 Fp dann insgesamt an Eigenanteil eingezahlt hast. Also nur eine Zwischensumme als Info. 
Du darfst dich nur an den Zahlen vor den Klammern orientieren.

Insgesamt musst du nur noch 59 FP einzahlen, oben rechts.

**Comment by dsiekiera** [comment]
Ach und trag mal beim _Platz 1_ hinten wieder die *90* ein. Dann siehst du auch die BPs + Meds wieder korrekt ;-)

**Comment by mordillo666** [comment]
Dass ich nur noch 9 einzahlen muss, hatte ich verstanden. ;-)

Mein Fehler war, dass ich die 5FP, die schon eingezahlt waren, nicht von den Gesamt FP abgezogen habe. :-(
Somit passt das doch alles. Manchmal klemmt es halt im Kopf...

P1 hatte ich absichtlich nichts eingetragen, das ist mein Tauschpartner. ;-)

**Comment by Th3C0D3R** [comment]
Dann trag da nicht nichts ein sondern 0, das sollte dann glaub besser sein

**Comment by andrgin** [comment]
Im nächsten Update werden ungültige Eingaben beim Archefaktor verhindert
