### ISSUE TITLE
Ereignisse (Firefox) zeigt nicht existierende Ereignisse an

### ISSUE THREAD

**Issue by Smh-S** [dsiekiera/foe-helfer-extension#502]
Z.B 2 Ereignis auf großen Straßen, aber die Stadt (FMA) hat keine große Straße. Oder Ereignis auf kleiner Straße in großer Stadt, aber nichts zu finden (habe sogar im Umbaumodus alles ins Lager getan, da war kein Ereignis übrig, was sonst der Fall ist)

**Comment by Th3C0D3R** [comment]
1) das ist weil Inno alle Ereignisse die potentiellen möglich sind überträgt ohne darauf zu achten ob der Spieler diese einsammeln kann.

2) Im Umbaumodus werden nie Ereignisse angezeigt (war zumindest bei mir nie der Fall)
Wenn mal ein Ereignis wirklich nicht da sein sollte (es laut Erweiterung aber vorhanden sein müsste) dann einmal die Stadt neuladen (irgendeine Karte besuchen (Außenposten, GG/GvG/GEX/ Karte der Kontinente) und nochmal suchen)
