### ISSUE TITLE
Gildenchat und Außenposten

### ISSUE THREAD

**Issue by Shea690901** [dsiekiera/foe-helfer-extension#505]
Zum einen vermisse ich den `Gildenchat`, oder taucht der, abgesehen von der Nutzbarkeit, nur auf wenn auch andere Gildenmitglieder den foe-helper benutzen?
Zum anderen hab ich einen ausgegrauten Punkt `Außenposten` mit dem ich irgendwie nix anfangen kann.
Ich benutze die Version 2.4.1.1 für Firefox des Helpers und egal wie oft ich in die Wikingersiedlung gehe bzw. das ganze neu lade, es ändert sich nix an diesem Zustand, mit den Japanern hab ich es noch nicht versucht.
Für den unwahrscheinlichen Fall das es relavant sein sollte: Ich spiele auf **de4** (_Dinegu_).

**Comment by Th3C0D3R** [comment]
Der Gildenchat wurde deaktiviert. Wird gerade aber überarbeitet und sollte bald wieder vorhanden sein.

zum Außenposten: Bitte prüf einmal ob das mit den Japanern auch so ist.

**Comment by andrgin** [comment]
Kannst du einmal einen Screenshot von dem Button machen. Ausgegraut sollte es nicht geben. Entweder ist der Rahmen rot oder grün und wenn er rot ist, steht normalerweise im Tooltip warum.

**Comment by Shea690901** [comment]
"Ausgegraut" = "deaktiviert" ;)
Und der Tooltip sagt mir, daß ich erst in den Außenpostenwechseln soll und zwar auch dann, wenn ich gerade im Außenposten bin und die entsprechende Botschaft geöffnet habe (Konnt jetzt bei den Japaner mit dem gleichen Ergebnis ausprobieren)

**Comment by andrgin** [comment]
Kannst die Entwicklerkonsole mit F12 öffnen und schauen, ob im Tab Konsole neue Fehlermeldungen auftauchen, wenn du den Außenposten besuchst

**Comment by Shea690901** [comment]
Nope, nix neues...
Hier ein screenshot mit allen Meldungen (reload & eventliste schliessen, der anschliessende Wechsel zum Aussenposten änderte nix mehr):
[FoEhelper2.jpg](https://www.dropbox.com/s/u2pu43dupr44nzj/FoEhelper2.jpg?dl=0)

**Comment by andrgin** [comment]
Welche Firefox Version hast du bzw. kannst du die einmal updaten?

**Comment by Shea690901** [comment]
60.8.0esr (Linux, 64bit)

Ich mach gerade mal 'n sync der package datenbank und schau mal was ich alles runterladen muß dafür (ich benutze [gentoo](https://www.gentoo.org/)), wird sowieso mal wieder Zeit....

**Comment by andrgin** [comment]
Wir haben auch gerade bei der Extension ein Update raus gebracht. Kannst du gleich mit neuer Firefox und Extension (2.4.2) Version testen und uns sagen, ob es noch auftritt

**Comment by Shea690901** [comment]
Jetzt hab ich leider erstmal ein anderes Problem:
Meine Festplatte ist, leider ohne vorherige Warnungen durch SMART, kaputt gegangen.

Ich muss mir erst irgendwie (Danke, Corona...) eine neue besorgen, bevor ich irgendwas testen kann, diesen Update verschicke ich per LiveCD mit 'nem noch älteren Firefox....

Melde mich wieder, sobald ich wieder irgendetwas vernünftiges machen kann....

**Comment by Shea690901** [comment]
Zwar immer noch nix wirklich vernünftiges möglich, aber trotzdem ein update:
Hab jetzt eine LiveCD mit einem 66.0.3 (64bit) Firefox am 'laufen' und dort das Addon ausprobiert...
Zumindest mit den Wikingern läuft's :)

Ich würde sagen, das ganze kann man damit, zumindest erstmal, als "closed" deklarieren....
Sollte sich an dieser Einschätzung etwas ändern, kann man das ganze ja wieder aufmachen (oder neuen Issue)...
