### ISSUE TITLE
Negotiations

### ISSUE THREAD

**Issue by T1uhgs** [dsiekiera/foe-helfer-extension#508]
Negotiation helper doesn't take a count if you have 4 tries.

**Comment by Th3C0D3R** [comment]
Do you have the extra turn from tavern or is it 4 turns from beginning? Or did you bought the new turn with diamonds?

**Comment by T1uhgs** [comment]
I have tavern boost.

**Comment by Th3C0D3R** [comment]
Thats odd, for me the helper recognizes the 4 turns
Can you provide a screenshot?

**Comment by Cyber-Raptor** [comment]
hi 
should helper recongnise the 4  turn when we  buy with dimos in BG ?

**Comment by Th3C0D3R** [comment]
no it only recognise the extra turn from tavern, because currently all possible turns in the helper are preproduced so it can not consider the extra turn bought with diamonds
