### ISSUE TITLE
Legendäre Gebäude

### ISSUE THREAD

**Issue by Horst-Krawuttke** [dsiekiera/foe-helfer-extension#51]
Ich habe die gesamte Gilde durchgeklickt und bekam auch Meldungen, dass diese aktualisiert wurde. Unter Legendäre Gebäude wird allerdings nichts angezeigt.
Die Gildenmitglieder unter Mitglieder werden angezeigt (wobei auch Ex-Mitglieder aufgelistet sind) und wenn ich dort die Mitglieder anklicke, sehe ich auch LG.
Ist die Übersicht einfach noch nicht aktiv? Oder gibt es da einen Trick, der sich mir nicht erschließt?

**Comment by dsiekiera** [comment]
Alter gefixter Fehler.

**Comment by frank42hh** [comment]
Moin,
mir scheint, dieser Fehler tritt bei mir immer noch auf. Wie kann ich den wegmachen?

![Screenshot_2019-11-19_17-03-46](https://user-images.githubusercontent.com/17932878/69163613-d0374a00-0aee-11ea-9960-f4ac1b3fb2cd.png)

**Comment by gandalfw4** [comment]
Der Fehler ist auch bei mir vorhanden.
Verwende Version 2.3.13
