### ISSUE TITLE
Active/Inactive friends

### ISSUE THREAD

**Issue by Rasipikukja** [dsiekiera/foe-helfer-extension#515]
It would be awesome if you guys can make us an easier way to update our friend list. Example if someone has not polished or motivated more than a week, or has not been active for a week, or something like that. It is a bother to check every name individually.
Thanks in advance,
Ras

**Comment by Th3C0D3R** [comment]
Lol you can easily polish and motivate through your Main-Building. Then after you clicked through all pages and did aid the players. Just go through your List and see who could be aided any way. Then you know who does not aided you

**Comment by Rasipikukja** [comment]
That is the point look for the name in the search screen of the main building than look for the name in the friend list, it is too time consuming and tedious. 
i was thinking of a list of some sort that tells who is or is not active and for how long ranging from least active to most active friends.

**Comment by Callisto649** [comment]
FOE Sniffer does this

**Comment by civwizzard** [comment]
Not only friends....
All players from neighbours, guild , friends tab in game.
For parallel loking into , or for click paste into message center to make group message.
Idea...we make often message groups that include some guild members, some friends, some neighbours , or want to add them into existing message groups...

**Comment by civwizzard** [comment]
can you suggest me any tool or trick how to make list of players from friends, guild and current neighbours easy, not to open notepad and select copy select copy , close, open close open..
