### ISSUE TITLE
Plunder

### ISSUE THREAD

**Issue by Pleios89** [dsiekiera/foe-helfer-extension#517]
Hello
day ago when plundering neighbors there was a list of what could be plundered
it disappear today 
all other lists are OK
is ther a way to show it again ?
regards

**Comment by andrgin** [comment]
The list only appears if there is something to be plundered.

**Comment by Pleios89** [comment]
Hello

 

Sorry, It did do it, bit no more, now nether shows up anymore even if there is somtehing to, don’t show……

2 days ago it does

 

I did remove and installthe add on again

I did purge chrome, cookies and so….

I did uses it in firefox, same do not show up, others windows are showing up not this one

I can send Hard copies if you want.

 

regards 

 

De : Gindi4711 <notifications@github.com> 
Envoyé : mardi 4 février 2020 00:05
À : dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc : Pleios89 <cronos61@laposte.net>; Author <author@noreply.github.com>
Objet : Re: [dsiekiera/foe-helfer-extension] Plunder (#517)

 

The list only appears if there is something to be plundered.

**Comment by andrgin** [comment]
Can you check:
1.) In the settings menu there is the option "neighborhood harvest". Ist this option enabled?
2.) If you press F12 an open the Console tab do you see any errors when visiting your neighbors?

**Comment by Pleios89** [comment]
Hello

 

I’m not a dev man but : 

merged-game-8fe8ec25.js:16 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

r @ merged-game-8fe8ec25.js:16

[Violation] 'requestAnimationFrame' handler took 51ms

 

 

 

 

De : Gindi4711 <notifications@github.com> 
Envoyé : mardi 4 février 2020 19:06
À : dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc : Pleios89 <cronos61@laposte.net>; Author <author@noreply.github.com>
Objet : Re: [dsiekiera/foe-helfer-extension] Plunder (#517)

 

Can you check:
1.) In the settings menu there is the option "neighborhood harvest". Ist this option enabled?
2.) If you press F12 an open the Console tab do you see any errors when visiting your neighbors?

**Comment by Th3C0D3R** [comment]
this is from Inno, not us ^^

**Comment by Squazz** [comment]
I'm now seeing this too: https://github.com/dsiekiera/foe-helfer-extension/issues/651

**Comment by andrgin** [comment]
The plunder feature will be removed in the next update: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/26
