### ISSUE TITLE
Keine Daten aus dem Game verfügbar. 

### ISSUE THREAD

**Issue by Kostja963** [dsiekiera/foe-helfer-extension#518]
Moin,
ich hab da ein kleines Problem. 
Ich habe mit gestern auf foe-rechner.de angemeldet. Es wurde auch eine Auswahl meiner Welten angezeigt. Ich habe eine Welt ausgewählt und die Anmeldung schien erfolgreich. 
Das Script zeigt mir im Game, dass es Daten nach hause schickt aber es kommt irgendwie nichts an und ich kann in meinem Account auch keine Daten einsehen. Fehlen Menüs und so. 
Anbei auch ein Screenshot. 
http://prntscr.com/qx9fvm
Ist da irgendwie was schief gelaufen oder hab ich evt. was falsch gemacht?
Gruß
kostja

**Comment by dsiekiera** [comment]
Das sieht halb-eingeloggt aus. Schreib mich bitte mal direkt mit einer Mail an und sende mir deine ID + Spielernamen wie sie in der Extension dargestellt wird.

ICh prüf das mal diekt in der DB.

**Comment by Kostja963** [comment]
Hast meine E-Mail erhalten? Nicht, dass ich sie falsch verschickt habe.
