### ISSUE TITLE
Verhandlungsassistent Nummerntasten Anzeige

### ISSUE THREAD

**Issue by someone97563** [dsiekiera/foe-helfer-extension#519]
Der Verhandlungsassistent zeigt nun auch die Zahlen an, um die Verhandlung mit den Nummerntasten  zu spielen (mit Leertaste die Auswahl bestätigen). In der Anzeige steht nun bei jedem Gut "<Platztaste>-<Guttaste>".
In diesem Zusammenhang werden die Plätze anfangs auch so sortiert, dass die Gütertasten leichteres eingeben ermöglichen.

Außerdem wird die Gewinnwahrscheinlichkeit auch durch einen Farbverlauf im Hintergrund der untersten Zeile angezeigt (Grün 100%, Orange 50%, Rot 0% mit Farbverlauf dazwischen).

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2020-02-20 um 18-23-28](https://user-images.githubusercontent.com/834814/74961289-1bbf0400-540e-11ea-9049-0d738c93e35d.png)
