### ISSUE TITLE
Eigenanteilsrechner; Plätze im eigenen LB verdrängen

### ISSUE THREAD

**Issue by BerserkerRudi** [dsiekiera/foe-helfer-extension#520]
Als Güterhändler wäre es interessant Einzahlungen in z.B. meine Arche ignorieren zu können. Z.B. habe ich 5 Einzahlungen über jeweils x FP in meiner level 90 Arche. Jetzt sollen die Plätze 1-5 durch Gildies besetzt werden, wobei die jeweiligen Einzahlungen dadurch natürlich erheblich vom Faktor 1,9 abweichen würden. 
Gefragt wäre nun ein Zahlplan, der z.B. angibt das P1 mit Y FP zu belegen ist, wobei dann noch die Differenz zum gewählten Archebonus berechnet werden müsste. Das dann für die Plätze 1-5. Als Ergebnis sollte dann herauskommen, wie viel die Plätze einzahlen müssten und was das jeweilige +/- pro Platz wäre um die durch den Güterhandel Einzahlenden auf P6+ zu verdrängen.

**Comment by andrgin** [comment]
Du kannst beliebige Simulationen durchführen indem du die geplanten Einzahlungen in die Ext Spalte einträgst. Hier musst du immer um 1 FP mehr eintragen als die Zahlung, die du verdrängen willst. In Klammer bekommst du dann mit + oder - angezeigt um wieviele FP derjenige zu viel oder zu wenig gezahlt hat.

**Comment by BerserkerRudi** [comment]
Danke für die Antwort!
Das ist mir bewusst. Ich habe aber in meiner Arche…. Ein Bild sagt mehr als tausend Worte:
http://prntscr.com/qxj88j
obigen Stand. Soetwas ist für Händler eigentlich recht üblich, daher die Frage nach der Funktion.
Würde ich die FP wie von dir vorgeschlagen eintragen, würde der Rechner dennoch die Plätze, welche durch die jeweilige Einzahlung gesichert wären, anzeigen. Da es sich dann aber auf P5 um die Summe der bereits offenen FP handeln würde, würde da nur Blödsinn rauskommen.

Kurzum nochmal: Ich will die Plätze 1-5 durch Gildies verdrängen lassen (weil das bei Güterverkäufen so abgemacht wurde), dazu sollte es eine Berechnungsmöglichkeit wie beschrieben geben.
Der jetzige höchste Platz soll keine FP bekommen, was muss wer einzahlen um das zu sichern und wer muss wieviele FP an wen kompensieren bei einer 1,9er Förderung.


Gesendet von Mail für Windows 10

Von: Gindi4711
Gesendet: Dienstag, 4. Februar 2020 18:58
An: dsiekiera/foe-helfer-extension
Cc: BerserkerRudi; Author
Betreff: Re: [dsiekiera/foe-helfer-extension] Eigenanteilsrechner; Plätze im eigenen LB verdrängen (#520)

Du kannst beliebige Simulationen durchführen indem du die geplanten Einzahlungen in die Ext Spalte einträgst. Hier musst du immer um 1 FP mehr eintragen als die Zahlung, die du verdrängen willst. In Klammer bekommst du dann mit + oder - angezeigt um wieviele FP derjenige zu viel oder zu wenig gezahlt hat.

**Comment by andrgin** [comment]
Also im Endeffekt muss es so aussehen:
P1: normal
P2: normal
P3: 601FP
P4: 601FP
P5: 601FP

Du trägst also 3 mal 601 in die ext Spalten ein und lässt die 3 Leute vorher einzahlen. Da die 3 ja über 1.9 einzahlen wird die ja kaum jemand rausdrängen und wenn ja machst du damit ja nur Gewinn.
Die FP die du entschädigen musst sag dir der Calculator.
Falls bei P1 und P2 einen großen danger Wert hast, dann kannst du auch probieren einmal nur 2 Einzahlungen einzugeben.

**Comment by BerserkerRudi** [comment]
Eben nicht, es soll so aussehen:
P1: Gildi
P2: Gildi
P3: Gildi
P4: Gildi
p5: Gildi
P6: 601
.
.
Im Normalfall kann P2 normal mit 1,9 einzahlen. P1 muss weniger als 1,9 einzahlen und die Plätze 4 und 5 müssen 602FP einzahlen.

Das geht dann nicht, da, würde ich das eintragen wie von dir beschrieben, würde der mit 601 immer auf P3 sein, egal an welcher Stelle ich den Externen eintrage.
Ich müsste sozusagen die Summe der Fremdbelegung auf einem fiktiven P6 eintragen können, der dann auch p6 bleibt.

**Comment by BerserkerRudi** [comment]
Ich saß da ein wenig auf der Leitung, geht natürlich schon^^
http://prntscr.com/qxy0gv
