### ISSUE TITLE
Markt 

### ISSUE THREAD

**Issue by PietSahad** [dsiekiera/foe-helfer-extension#521]
Ich habe diesbezüglich noch keine Vorschläge gesehen (bin aber auch erst seit eben registriert und habe alles nur überflogen), daher erwähne ich es mal bzw. frage ich nach, ob sowas möglich wäre. 

Für mich wäre es interessant Markierungen im Markt-Fenster zu haben, die mir zeigen, was faire/unfaire Handel oder sogar Schnäppchen sind. 
Schnäppchen: grün
Fair: gelb
Unfair: rot
Vielleicht in einem neuen Pop-up oder in einem bestehenden (Info-Box, etc). 

Natürlich kann man auch einfach mit der Maus über das jeweilige Gut hovern und sehen, aus welchem Zeitalter das entsprechende Gut stammt, allerdings kommt es zumindest bei mir ab und zu vor, dass ich ein ZA verwechsel und nicht genau weiß, ob es jetzt ein oder mehrere ZA zurückliegt bzw. vor mir liegt. Vor allem aber möchte ich, dass mir Schnäppchen angezeigt werden. 

Ist sowas möglich? Wäre das eurer Meinung nach ein nützliches Feature? Oder bin ich da alleine mit meiner Meinung und es ist eher unnötig? ^^

Ich freue mich auf Antworten!
Grüße
Piet

**Comment by PietSahad** [comment]
Ich habe gerade gesehen, dass es diesen Vorschlag in der Art bereits auf Englisch gibt. ^^

**Comment by outoftheline** [comment]
See #485 
-> Closing duplicate
