### ISSUE TITLE
FoE-Helfer recourcenschonender programmieren

### ISSUE THREAD

**Issue by KusterBee** [dsiekiera/foe-helfer-extension#522]
Hallo .. FoE-Helfer ist wirklich ein gutes Tool ;) .. 
aber nicht jeder hat vielleicht einen HighEnd-PC .. selbst bei meiner 100k Leitung hängt sich das Spiel für eine gefühlte Ewigkeit auf, wenn ich z.B in der GEx oder bei den Gildengefechten ins Gefecht gehe .. mag sein, das meine Grafikkarte mit 2GB Ram schon zu klein ist .. 4 GB Arbeitsspeicher .. Win7 .. 
aber wie gesagt .. so macht das auf Dauer mit der ewigen Warterei keinen Spaß .. 
Ohne die FoE-Helfer Erweiterung läuft das Spiel eigentlich flüssig .. 
bin ich wirklich der einzige mit diesem Problem? .. 
Ansonsten keine Beschwerden ;))

**Comment by andrgin** [comment]
Kannst du genau beschreiben wann es bei dir genau auftritt? An sich sollten keine extrem ressourcenfressenden Dinge passieren außer bei Verhandlungen, wo die Tabellen geladen werden müssen aber das passiert nur einmal pro Verhandlungstyp nach dem Neustart.
Kann es sein, dass dir der RAM ausgeht?

**Comment by Th3C0D3R** [comment]
*hust* Windows 7 *hust* und vielleicht auch Chrome? mit 4GB RAM? das kannste knicken 😂

**Comment by KusterBee** [comment]
Win10 kann ich in die tonne drücken .. habs versucht, aber gleicher effekt .. 
und ... ist ja mein Reden.. wird ein BrowserSpiel jetzt auch nur spielbar, wenn man einen Highend-Rechner hat?? also, minimum einen 7er Razor mit 16GB Arbeitsspeicher und am besten ne Grafikkarte mit 8GB ?? wo sind wir nur gelandet ;)) . 
ich geb zu, mein Rechner ist schon ziemlich alt .. mehr oder weniger .. hatte bis jetzt noch keine probleme .. erst jetzt, seit dem FoE-Rechner ;)
und tritt dann auf, wenn ... Beispiel ;)
ich geh in die GEx .. alles ok .. wähle Kampf aus.. alles ok .. die Truppen stellen sich auf. .nichts mehr ok .. dauert ewig .. 
gleiches bei den Gildengefechten.. sprich . auch da dauerts ewig, bis die Truppen angezeigt werden und ich loskämpfen kann
ganz ehrlich.. mir gefällt im prinzip gut.. aber ich kauf mir keinen neuen Rechner, nur damit ich hier auch reibungslos spielen kann.. was ja vorher "ohne" FoE-Rechner funktioniert hat ;)

**Comment by andrgin** [comment]
Also ich habe mal den Start eines neues Gefechts im Profiler analysiert. Der Anteil der Extension liegt da bei unter 2%. Der Rest wird vom Spiel verbraucht, größtenteils zum Zeichnen der Einheiten.

**Comment by KusterBee** [comment]
> Also ich habe mal den Start eines neues Gefechts im Profiler analysiert. Der Anteil der Extension liegt da bei unter 2%. Der Rest wird vom Spiel verbraucht, größtenteils zum Zeichnen der Einheiten.

Naja .. ich sage ja auch nicht, das ihr "Mist" gebaut habt ;)) .. 
ist mir schon klar, das es **"auch"** an meinem System liegt. Ist nur komisch, das ohne den Helfer alles reibungslos funktioniert . und mit ihm Probleme auftauchen.. 
alles andere funktioniert wunderbar .. sei es die Auslesung der LGs von Nachbarn, oder der Verhandlungs-Helfer ;) ... eigentlich alles .. nur eben der Wechsel zum Kampf nicht ..

**Comment by andrgin** [comment]
Ich meinte damit, dass das Spiel selbst bei mir ca. 50 Mal so viel CPU Leistung verbraucht wie die Extension. Somit verstehe ich nicht, wie es ohne Extension spürbar schneller sein kann.

**Comment by dsiekiera** [comment]
> .. nur eben der Wechsel zum Kampf nicht ..

Und genau da haben wir gar nix mit dem Spiel zu tun. Es gibt zwar eine Menge anfragen diesbezüglich aber nicht 1 Bit Code der an dieser Stelle von unserer Seite.

**Comment by KusterBee** [comment]
tja.. dann versteh ich das auch nicht.. ich kann nur beschreiben, wie es bei mir ist ;) 
Helfer an: Wartezeiten
Helfer aus: alles normal .. 
aber egal .. lässt sich dann anscheinend nicht ändern .. ich muss dann eben damit leben ;) .. 
aber danke für die info`s und "Anteilnahme" ;)

**Comment by SkateScout** [comment]
Es gibt leider doch ein paar Code Stellen die nicht gerade "optimal" sind.
Bsp: strategy-points.js

Orginal Zeile 51-53 : 
        for(let counter = 1; counter <= boughtCount; counter++) { 
               currentlyCosts += factor;
	}

Besser: currentlyCosts += boughtCount * factor;

**Comment by andrgin** [comment]
Wie oft läuft denn die Schleife durch? Im besten Fall sind es um die 10K Mal und immer nur dann wenn man auf den FP kaufen Button klickt. Das ist sinnlos da Zeit zu investieren, wenn die Zeitersparnis irgendwo im Mikrosekundenbereich liegt.

**Comment by sauerbi** [comment]
Also das Spiel ansich braucht schon ewig viel Resourcen, vor allem CPU. Dass Du nur mit 4 GB RAM unterwegs bist ist schon mal ein Punkt. 8 GB sollten mindestens in den Rechner (auch für andere SW) und die GraKa auch nicht zu klein sein.
Und ja, solche Schleifen sollte man wirklich entfernen, denn das läuft dann nicht mehr im Micro- sondern eher im Millisekundenbereich und kann bei mehreren Aufrufen auch mal Sekunden ausmachen. Und da wir bei JavaScript sind, gibt es auch keinen JIT-Compiler.
