### ISSUE TITLE
Nachbarschaft Deff% des Nachbars anzeigen.

### ISSUE THREAD

**Issue by ClaesSparre** [dsiekiera/foe-helfer-extension#53]
Guten Tag Herr Siekiera,

besteht die Möglichkeit in dem Fenster der Nachbarn neben dem Namen die Verteidigungsstärke in % anzuzeigen?

Beste Grüße,
Claes

(PS: Ausgezeichnete Arbeit dieses Tool. Darüber hinaus meine Hochachtung für ihr Engagement und die laufenden Weiterentwicklungen. Ich würde ja gerne mal einen "Kaffee rüberscheiben" Allerdings nicht über paypal. Vielleicht geht es über paysafe?)

**Comment by dsiekiera** [comment]
Hallo ClaesSparre,

diese Option hatten wir bereits überlegt, ist aber extrem aufwendig zu programmieren. Die Werte werden nicht einfach so übermittelt. Inno übermittelt lediglich die Gebäudenamen, keine Werte. Notwendig wäre hier eine Schleife mit einer Liste die alle Gebäude mit den verschiedenen Defs + ZA kennt um diese zu addieren. Leider gibt es so eine Liste aber nicht. Die müsste erst erstellt werden.

Wenn mal etwas mehr Zeit ist, werde ich die Sache noch einmal angehen. Aber derzeit liegen die Schwerpunkte noch wo anders.

**Comment by JHCD** [comment]
Auch dann müsste man eine abgesetzte Anzeige realisieren... 

Das Ändern der NL-Leiste würde ich als kritisch bewerten, das könnte Inno als Änderung werten.

**Comment by ClaesSparre** [comment]
Hallo Daniel Siekiera,
vielen Dank für die Antwort, die gut nachvollziehbar ist.

Seit dem letzten Update des FoE-Helfers wird dieser auf de11 nicht
mehr angezeigt. Auf anderen Welten hingegen schon. Woran könnte es
liegen?

Beste Grüße
Claes Sparre

**Comment by Niorian** [comment]
Ich möchte diesen Vorschlag erneut aufgreifen. 

Falls ihr Hilfe beim erstellen der Liste mit den Kampfboni des Gegners (Also Angriff+Verteidigungsboni bei der **verteidigenden** Armee) braucht, könnte ich euch gerne behilflich sein. 

Hierzu könnte man die Infos auf dem **offiziellen** FoE-Wiki (**nicht** das Fandom Wiki) zur Grundlage geben. Kategorie: Gebäude.
https://de.wiki.forgeofempires.com/index.php?title=Gebäude

In den verschiedenen Kategorien werden alle Gebäude angezeigt, die es im Spiel gibt. Eventgebäude, Militärgebäude, alles was das Herz begehrt. Hier könnte man die einzelnen Gebäude durchgehen und bei jedem Gebäude was in irgendeiner Form Kampfbonus gibt, auflisten. 

Ich weiss jetzt nicht in welcher Datenform das Spiel die Gebäudenamen intern ausspuckt, aber in den Bilderlinks zu den Gebäuden wird auch immer der technische Name der Gebäude genannt, beim Olympischen Tresor vom Forge Bowl Event ( https://de.wiki.forgeofempires.com/index.php?title=Olympischer_Tresor_-_St._9) z.B. R_SS_MultiAge_SportBonus20i

--> https://foede.innogamescdn.com/assets/city/buildings/R_SS_MultiAge_SportBonus20i.png

Einfach Bescheid geben, falls Interesse besteht.

**Comment by andrgin** [comment]
Der Erntehelfer wurde entfernt: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
