### ISSUE TITLE
Gildengefecht: Anzeige der Spieler in der Infobox

### ISSUE THREAD

**Issue by DJMMC** [dsiekiera/foe-helfer-extension#531]
Es wäre gut sehen zu können wer genau im Gildengefecht welche Koordinaten angegriffen hat. Spielerübersicht mit Infobox Gildegefechte verknüpfen.
Wenn nicht 100% möglich, dann zumindest anzeigen wer zeitnah angegriffen hat um Rückschlüsse darauf ziehen zu können wer wann wo angegriffen hat

**Comment by andrgin** [comment]
Man bekommt nicht raus welcher Spieler angegriffen hat. Das überträgt Inno nicht, sonst würden wir es anzeigen.
Die Spielerübersicht wird nur übertragen wenn man darauf klickt.

**Comment by DJMMC** [comment]
Kann man die Daten aus dem Snapshot der Spielerübersicht (also die grünen Markierungen) nicht mit der Infobox rechnerisch vergleichen und damit eine Zusammenführung beider Datensätze hinbekommen? Vielleicht nur als "Richtwert" welcher Punktezuwachs zu welchem Angriff passen könnte? (natürlich nur beim draufklicken, eben dann wenn die Spielerübersicht geladen wurde)

**Comment by masterwebsk** [comment]
+1 well, this will be very useful for comanders, because in higher ligues there are many players atacking in sectors where they should not atacking. And this is not good if you have ally/agreement between guilds for example. So this will be great tool for "cleaning" not team players.

**Comment by Barbar65** [comment]
I agree with masterwebsk and would appreciate such a feature

**Comment by scibuff** [comment]
OK, let's assume you have the following

![image](https://user-images.githubusercontent.com/722049/79634555-5ec9f900-816b-11ea-9764-5b9656d2be19.png)

what exactly would you like to "merge" from these two?
