### ISSUE TITLE
Temple of Relics - Powerleveling

### ISSUE THREAD

**Issue by Damianbv** [dsiekiera/foe-helfer-extension#532]
The website gives an error on powerleveling the Temple of Relics:
<br />
<b>Warning</b>:  array_key_last() expects parameter 1 to be array, null given in <b>/usr/www/users/foecre/foe-rechner.de/core/modul/invest/pages/ajax-parts/get-levels.php</b> on line <b>32</b><br />
{"status":"OK","level":null}

**Comment by andrgin** [comment]
Already fixed
