### ISSUE TITLE
Short Name option for Great Buildings

### ISSUE THREAD

**Issue by Looonybomb** [dsiekiera/foe-helfer-extension#533]
Is there a way to create a short name for a GB from the Cost Calculator screen... instead of Statue of Zeus, just need Zeus

**Comment by andrgin** [comment]
The names of the great buildings shown ingame are those that are transfered by Inno games depending on the language of the server. If we use short names we have to translate every GB to every of our supported languages which is not worth it in my opinion.

**Comment by dsiekiera** [comment]
I think he means the name for copying a name.
That is already integrated. Both input fields in the overlay for copying the values can adopt and save other LG names and / or player names by input.

![Bildschirmfoto 2020-02-19 um 16-19-32](https://user-images.githubusercontent.com/834814/74858785-3037c980-5346-11ea-9911-38802f01c8e8.png)

![Bildschirmfoto 2020-02-19 um 16-19-49](https://user-images.githubusercontent.com/834814/74858796-35951400-5346-11ea-8373-0f2e165e6ca3.png)
