### ISSUE TITLE
CITY PLANNER

### ISSUE THREAD

**Issue by stonekhold** [dsiekiera/foe-helfer-extension#534]
How about a city planning? So you can plan city off line and than use the schema to do city instead of trial and error with Reconstruction and waste hours to find out bad design or need to delete/store buildings and cancel because you cant do in reconstruction.

**Comment by R3d-N4x3l4** [comment]
Maybe contact https://foemanager.com/city-planner/app/
He is/was coding a Multi-Plattform-App, but his "City-Import" was shut down by InnoGames

**Comment by outoftheline** [comment]
There is now one on the website: https://foe-rechner.de/docs/2/citymap/
