### ISSUE TITLE
FP Inventar nur selten vorhanden

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#54]
Wie viele FP in meinem Inventar sind erscheint nur, wenn ich ein lg öffne und dann den Kostenrechner dazu öffne. Vorher nicht.
Ist die Anzeige einmal da...bleibt sie auch bis man das Spiel schließt.

**Comment by dsiekiera** [comment]
Das ist korrekt und lässt sich leider nicht anders lösen. 
Inno übermittelt einfach vorher keinen Bestand. Der kommt immer erst mit dem öffnen des ersten LGs.
