### ISSUE TITLE
[2 Features Request] Friend Summary & Reveal Random Recurring Quest

### ISSUE THREAD

**Issue by tu4h** [dsiekiera/foe-helfer-extension#543]
1. Summary of friend aid, number of times come to tavern & last aid/visit tavern (last interaction), which pull from event history.
2. Reveal Random on Recurring Quest. 

Thank you.

**Comment by Th3C0D3R** [comment]
1.) you can see on the website: https://foe-rechner.de/

2.) this is not possible of no data is send from Inno

**Comment by outoftheline** [comment]
Closing this for reasons stated above :D
