### ISSUE TITLE
[Parameters] Missalignment WorldID/GuildID when GuildID is lower than 1000

### ISSUE THREAD

**Issue by troll31** [dsiekiera/foe-helfer-extension#548]
On actual beta version 2.4.1.1 (last updated), in the parameter windows.
There is a missalignment (i think when when Guild ID is lower than 1000),
The WorldID is not going to a new line and is following the GuildID (see screenshot)

Actual display : 
"World ID"   {000}"Guild ID"
{xx0}

Should be:
"World ID"   {000}
"Guild ID"    {xx0}

![foeassitsant_align](https://user-images.githubusercontent.com/60022095/74376770-041ac680-4de3-11ea-84c6-89c5e5591b67.png)

**Comment by andrgin** [comment]
Yes seems to be a formatting issue when the guild id string is too short.

**Comment by andrgin** [comment]
Should be solved with the new settings menu
