### ISSUE TITLE
Kostenrechner funktioniert nicht

### ISSUE THREAD

**Issue by houndshounds** [dsiekiera/foe-helfer-extension#55]
Bin neu dabei. Soweit funktionier alles was ich getestet habe. Wenn ich allerdings bei nem Nachbarn ein LG öffne und dann den Kostenrechner benutzen möchte, bleibt dieser ohne Inhalt. Das Fenster lässt sich auch nicht über das X schließen. Hab Chrome 64bit neuster Stand und das HTML4 am laufen.

**Comment by MrMattn** [comment]
by the way....das Piazza Set wird nicht aufgelistet. eben komplett geplündert ohne dass es in der Liste war

**Comment by dalmipuh** [comment]
Bei mir zeigt der Kostenrechner manchmal den gleichen Effekt.
Er scheint bei folgender Codestelle zu stoppen:
`		let BuildingInfo = Calculator.EntityOverview.find(obj => {
			return obj['city_entity_id'] === e['cityentity_id'];
		});`
Gerade mehrfach reproduziert als ich auf einer Welt ins Rathaus ging, dort ein LG öffnete und den Kostenrechner starten wollte.
OtherActiveBuildingOverview konnte ich im local storage nicht finden.

**Comment by dsiekiera** [comment]
Alter gefixter Fehler.
