### ISSUE TITLE
Falsche FP Werte beim Leveln eines LGs in der Infobox

### ISSUE THREAD

**Issue by andrgin** [dsiekiera/foe-helfer-extension#555]
Wird ein LG mehrere Male hintereinander gelevelt so werden zu hohe FP Werte ausgeben. Es scheint dabei jedes Mal die Summe aller Level ausgegeben zu werden.

Vermutung: Es werden im d von getPlayerNoticeIndicators mehrere LG Level übergeben.

**Comment by scibuff** [comment]
This is fixed now on Beta (#1107) and will be in the next release
