### ISSUE TITLE
Installationsprobleme in EN Version

### ISSUE THREAD

**Issue by danjelous** [dsiekiera/foe-helfer-extension#56]
Hi, 

erstmals: super Extension! Erleichtert einem echt sehr viel 👍 

Zum Issue: Ich hatte die Extension über den Webstore installiert (aktuelle Version 2.2.14), passiert ist dann leider recht wenig. Die DevTools sagten `i18n is undefined` (siehe Screenshot). Ich schaute dann in meinen Browser-Einstellungen nach und da waren nur englische Sprache hinterlegt.. Mit Hinzufügen von `Deutsch` ging's dann problemlos. 

Also dieser Issue ist mehr eine Art Info ;) Danke nochmals für die super Extension!

![Bildschirmfoto 2019-07-15 um 06 22 11](https://user-images.githubusercontent.com/12988554/61195621-7ac6d880-a6c9-11e9-8e0e-0ae0905e3734.png)

**Comment by dsiekiera** [comment]
Das ist korrekt. Das Thema Übersetzungen ist noch aktuell und ist eine eigene Baustelle.
