### ISSUE TITLE
Fenster schnell wieder ausblenden durch Klick in die Leiste

### ISSUE THREAD

**Issue by rauschm** [dsiekiera/foe-helfer-extension#561]
Vorschlag: Ich fände es gut, wenn man ein Fenster durch erneutes Anklicken der Box in der Leiste auch wieder schließen könnte.
Also:
Fenster nicht sichtbar -> Klick auf Box -> Fenster sichtbar
Fenster sichtbar -> Klick auf Box -> Fenster nicht sichtbar

**Comment by MilaPi** [comment]
That's exactly what I've been wishing lately - to quickly hide the window again after second click! Two windows even when using sniping feature.

**Comment by rauschm** [comment]
Funktioniert leider nicht mit dem Kostenrechner.

**Comment by dsiekiera** [comment]
Ist so gewollt und wird auch so bleiben. Auf dem Button liegen schon 2 Funktionen. Stichpunkt (VirabScan)
