### ISSUE TITLE
Login funktioniert nur mit Email (nicht mit Spielernamen) und Spieler und Gilden ID wird nicht gefunden. Somit kann ich keine Statistiken sehen etc. Liegt der Fehler bei mir oder in der Datenbank?

### ISSUE THREAD

**Issue by silesiano** [dsiekiera/foe-helfer-extension#566]
![login](https://user-images.githubusercontent.com/61193430/74741565-5afa2300-525d-11ea-8c94-3f449e6ce285.jpg)

**Comment by nikhil1611** [comment]
Similar issue - https://github.com/dsiekiera/foe-helfer-extension/issues/554

**Comment by dsiekiera** [comment]
Ist gefixt. Es muss nun beim Login ein Spiel-Server angegeben werden, ansonsten kommt eine Meldung ála => "Keinen verlinkten Spieler gefunden"
