### ISSUE TITLE
Verhandlungsassistent: Sortierung der Güter

### ISSUE THREAD

**Issue by basti2305** [dsiekiera/foe-helfer-extension#572]
Für den Verhandlungsassistenten eine Auswahl in den Einstellungen einfügen, wie die Güter sortiert werden sollen. Bei Mangel an Gütern aus den zwei ZAs muss immer manuell umsortiert werden.
1) Münzen, Vorräte, Güter vorheriges ZA, Güter jetziges ZA
2) Nach verfügbarer Menge

**Comment by andrgin** [comment]
Mit dem nächsten Update gibt es nun 2 permanent gespeicherte Einstellungen:
.) Aktuelle Güter sparen: Legt fest ob wie jetzt bevorzugt Güter früherer ZA verwendet werden sollen oder ob es nur nach aktuellem Lagerstand geht
.) Medaillen sparen: Legt fest, ob die Medaillen wie bisher nach der Gütern verwendet werden sollen oder davor (für Leute die schon genug davon haben)

Münzen und Vorräte werden immer als Erstes benutzt, Spezialgüter wie Promethium und Oricalchum immer am Schluss
