### ISSUE TITLE
Eigenanteilsrechner - Med u. BP nach eigenen Prozenten?

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#58]
Guten Morgen :)

Im wunderschönen <3 Eigenanteilsrechner kann man die Medis und die BP ablesen.
Diese Angaben verwende ich gern um sie als Info für Sponsoren dahinter zu schreiben, was sie denn bekommen wenn sie die Plätze belegen. Gerade bei einem FP-losen P5 interessant...

Seltsamerweise werden unter "Einzahlen" die Werte korrekt angegeben die der Sponsor einzahlen muss. 
Unter "BPs" und "Meds" werden die Angaben aber mit meinen Prozenten berechnet. 
Da ich die Plätze aber nicht belege sondern wer anders, stimmt das doch nicht oder?
Besser wäre doch hier der "echte" Wert ohne jegliche Prozente?!

Bsp: AO zur Stufe 8 - P5 wird bei mir mit 2BP angezeigt. Richtig wäre 1BP

![2 1](https://user-images.githubusercontent.com/50969949/61198940-532d3b80-a6dc-11e9-978d-bbdaebaddb2d.PNG)
![2](https://user-images.githubusercontent.com/50969949/61198941-532d3b80-a6dc-11e9-8b4f-358ff1e9e309.PNG)

**Comment by JHCD** [comment]
Du hast im Eigenanteilsrechner den Arche-Bonus auf 90% eingestellt; daher sind 2 BP technisch korrekt.

**Comment by Selene443Foe** [comment]
Theoretisch gebe ich dir recht. Das Ding heißt ja "Eigenanteil..." 
Jedoch im Grunde interessiert mich doch "mein" Anteil nicht wenn den Platz ein anderer belegt?!
Besser wäre doch wenn ich dem der belegt sagen könnte was er davon hat wenn er ihn belegt?!

Jain... ich weiß ja nicht wer den Platz belegen wird. Also auch nicht wie hoch sein Boni ist.
Ich denke es wäre "richtig" wenn dort einfach keine Boni berechnet werden...

**Comment by Selene443Foe** [comment]
Oder aber so, wenn man #41 verwendet - sprich also dort einen Prozentwert einträgt, dass dann die Prozente entsprechend berechnet werden und wenn man nichts einträgt, dann auch nichts berechnet wird?! 
Wäre das ein Deal? ;)

**Comment by JHCD** [comment]
Du verstehst da eine Kleinigkeit falsch: Das Feld Arche Bonus ist nicht der Wert für Deine Arche, sondern mit welchem Arche Aufschlag zu die Plätze besetzen willst.

Der Eigenanteil ist der Wert, den Du einzahlen musst, damit Du die Plätze mit dem gewählten Bonus sicher anbieten kannst.

**Comment by Selene443Foe** [comment]
Ok... hab ich mir auch gedacht und das Feld auf Null gestellt damit ich den "echten" Wert der BP bekomme.
Nun ändern sich aber auch alle Zahlen... Ich bin ja mathematisch ne absolute Niete... Aber ich glaube da stimmt dann irgendwas nicht?!
Und zwischen der 90 und der Null hin und her schalten scheint mir irgendwie nicht richtig?!

**Comment by dsiekiera** [comment]
Der Wert "90%" im Rechner oben bezieht sich auf alle Werte. Das Tool dient eigentlich alleinig dem Zweck seine eigenen LGS mit dem Wert von 90% füllen zu lassen. Ansonsten wäre es eigentlich sinnlos.

Im das nicht "ausrechnen" zu lassen gibt es keine Funktion. Alles wird mit den "90%" berechnet.

Wie bereits schon einmal erwähnt gibt es das auf der Webseite diese Option. Sobald das passt kann ich es ja mal mit einbauen.

![foe-rechner.de > Eigenanteilsrechner](https://user-images.githubusercontent.com/834814/61206725-92b35200-a6f3-11e9-95cb-ba85e635f533.png)

**Comment by Selene443Foe** [comment]
Ok... ich verstehe die Logik dahinter.
Das Ganze will ich auch nicht aufbauschen. So wichtig ist das nicht!

Nur nochmal zum Verständnis für alle:
Auf der Webseite ist es so gemacht wie du sagst, das stimmt. 
Jedoch ist die Verwendung doch in der Realität etwas anders!

Du sagst das mit 90% belegt werden soll, sonst ist es "eigentlich zwecklos". Gebe ich dir voll und Ganz Recht.
Diese 90% geben dir aber auch die kleinen Spieler. Teils sogar mehr. Gerade für einen P5.
Diese Spieler bekommen aber immernoch nur Ihren eigenen Boni (den ich vorher nicht weiß) heraus. Denen (und mir) ist egal was ich raus bekommen würde wenn ich diesen Platz belegen würde/könnte.

Da in der Regel ein P5 oder P4 auch meist von einem kleinen besetzt wird, machen diese regelmäßig (an Punkten) minus. Die interessiert doch maßgeblich wieviel BP die dafür bekommen. Und das teile ich denen gern mit :)

Heißt also:
würde ich jetzt auf der Webseite auf den entsprechenden Plätzen einen Boni von 0 eingeben um die korrekten Werte für BP und Medis des Einzahler ablesen zu können, dann wird mein Eigenanteil entsprechend hoch gesetzt. 
Aber das stimmt ja dann nicht. 
In der Realität geht der Einzahler genauso wie alle anderen mit 90% rein. Nur das er die nicht raus bekommt da er seine Arche vielleicht auf 50% oder sowas hat...

**Comment by dsiekiera** [comment]
Oder so... 😄
