### ISSUE TITLE
Feature reequest: Plünder-Fenster nicht automatisch einblenden

### ISSUE THREAD

**Issue by gneiss15** [dsiekiera/foe-helfer-extension#588]
Das Tools ist wirklich klasse.
Eine Kleinigkeit die mich etwas stört ist die Tatsache, dass das Plünder-Fenster immer automatisch eingeblendet wird. Da ich nur unter bestimmten Bedingungen plündere, aber meine Nachbarn regelmäßig "durchgehe" muss ich das Fenster jedes mal wegklicken damit es beim Kampf nicht stört.

Ich könnte mir denke, das man das Verhalten über eine Option ändert. Bei Abgeschaltetem "Auto PopUp" könnte man das Fenster immer noch über das Menü einblenden.
Eine Alternative wäre das das Fenster nicht erst "verschwindet" wenn man in die eigene Stadt zurückkehrt, sonder auch wenn man in die Kampf-Ansicht wechselt.

Ich hoffe Ihr findet irgend wann mal die Zeit das zu implementieren, Danke.

**Comment by andrgin** [comment]
Ich denke das Einfachste ist, dass du den Erntehelfer einfach in den Einstellungen deaktivierst, wenn du ihn gerade nicht haben willst.

Was das automatische Ausblenden während des Kampfes angeht so müssen wir uns das ansehen aber ich denke das wäre möglich.

**Comment by gneiss15** [comment]
@andrgin: Das mit dem Ausschalten in den Einstellungen ist leider ja noch umständlicher als das Fenster häufig weg zu klicken.
Nur zum Verständnis: Ich plündere nur Nachbar die (fast) nichts in Ihre Deff stecken. Heißt also der Entehelfer ist schon sehr nützlich.
Aber selbst bei Leuten die jeden Plündern dürfte es sinnvoller sein das Fenster auszublenden wenn ein Kampf-Fenster auf geht, denn auch dort stört das ja.
Ich hoffe mal Ihr findet eine Möglichkeit..

... und danke für die tolle Arbeit/ das tolle Tool ...

**Comment by andrgin** [comment]
Der Erntehelfer wurde entfernt: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
