### ISSUE TITLE
Impossible to reorganize the icons in the tool bar.

### ISSUE THREAD

**Issue by Gregory-F** [dsiekiera/foe-helfer-extension#589]
Hello,

since this morning (21/02/2020) the FoE helper bar has his icons reset every login to some default order. Before the user could reorganize the icons in any convenient way and the expansion would remember it, but not anymore.
foe-helper version 2.4.2
browser: Chormium Version 80.0.3987.106 (Build officiel) Arch Linux (64 bits)

**Comment by sanity65** [comment]
still here in 2.4.2.1
