### ISSUE TITLE
Kostenrechner Ebenen?

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#59]
Guten Morgen :)
würde es viel Arbeit machen den Kostenrechner eine Ebene tiefer zu programmieren?
Also so, dass eine ausgeklappte Seitenleiste sich darüber legen kann?

Erklärung:
Die Liste der Nachbarschaft / Freunde / Gilde ist im Bild links.
Wenn man die durchklickt, dann bewegt man sich mit der Maus und den Augen im linken Bereich des Bildschirms.
Also stelle ich mir den Kostenrechner auch auf die linke Seite - so ist das praktisch und komfortabel abzulesen.
Will ich nun die Quest wieder aufladen, dann muss ich mir Seitenleiste ran holen um den richtigen Questgeber anklicken zu können. 
Jetzt steht mein Kostenrechner im Weg und ich schiebe ihn nach rechts. (oben / unten ist kein Platz. Bildschirm wohl zu klein, oder Auflösung zu hoch, oder Kostenrechner zu groß)
Richtige Quest gefunden, Seitenleiste wieder rein, nächster Nachbar / Freund / Gildie.
Nun steht der Kostenrechner rechts, die Augen wandern also ständig von unten nach oben und links nach rechts.... (gutes Augentraining, aber unkomfortabel beim spielen) 

Einfacher wäre es wenn man den Kostenrechner links stehen haben könnte, das Seitenfenster würde sich über ihn legen, es fährt wieder ein und weiter gehts...

Nichts wichtiges!! 
Nur als Idee und wenn es nicht zu viel Aufwand ist.
<3

**Comment by dsiekiera** [comment]
Ist umgebaut und in der nächsten Version Verfügbar:

![Bildschirmfoto 2019-08-15 um 18-21-08](https://user-images.githubusercontent.com/834814/63109439-85ef7b80-bf89-11e9-8373-1a65e5b25a29.png)
