### ISSUE TITLE
Kostenrechner funktioniert seit dem Update nicht mehr

### ISSUE THREAD

**Issue by bthau** [dsiekiera/foe-helfer-extension#60]
Seit dem Update vorhin funktioniert der Kostenrechner leider  nicht mehr

**Comment by Julian2424** [comment]
Ich habe auch das Problem. Der Kostenrechner und Eigenanteilsrechner werden nicht grün, wenn ich ein LG öffne.

**Comment by dsiekiera** [comment]
Das liegt lediglich an eurem Browser Cache.

So löst ihr das Problem:

> Ganz genau geht es so: Chrome Menü oben rechts (drei Punkte) => "Weitere Tools" => "Browserdaten löschen". Dann im ersten Tab (Grundlegens) nur unten bei "Bilder und Dateien im Cache" den Haken rein, "Daten löschen".

Danach sollte alles wieder gehen.

**Comment by Elschen** [comment]
Leider nur bis zum nächsten Weltenwechsel :-(

**Comment by Elschen** [comment]
Kostenrechner, Eigentanteilsrechner und FP-Lager funktionieren nicht. Eine Welt mag den Rechner gar nicht mehr öffnen. Chrome ist upgedatet, Cache ist geleert, Chrome neu gestartet. Nix.

**Comment by dsiekiera** [comment]
Kann auch nur ein Cache sein, schau bitte mal hier #43

**Comment by Elschen** [comment]
Das hatte ich schon mal probiert. Eben wiederholt. Danach gingen in zwei Welten Kostenrechner und Co. genau einmal - beim nächsten Weltenwechsel alles wieder inaktiv. Ich spiele auf drei Welten und bisher ging es immer. Dieses Problem habe ich erst seit dem heutigen Update.

**Comment by bthau** [comment]
Cache geleert aber funzt trotzdem nicht

**Comment by dsiekiera** [comment]
Ich hab aber an der Technik usw nix geändert. Es kann nur irgend ein Cache sein.

Versucht einfach mal gemäß #43 (Haken in der Konsole auf Disabled) und offener Konsole die Welten zu wechseln. Einfach auflassen. Und auch mal mit Strg + R einen Hard+Reload erzwingen. F5 is Wurst und taugt eh nix :-) 

Wir hatten das Problem in unserer Gilde auch kurz. Aber mit dem löschen aller Daten gemäß meinem ersten Beitrag ging es schon wieder.

Sollte das auch nicht gehen, schau ich mir das auch gern mal persönlich an.

**Comment by MrMattn** [comment]
also bei mir gehts auch nicht Daniel.
hab nur eine Welt.
Nach Anleitung vorgegangen im OSX (Konsole über Leiste oben geöffnet, da cmd+shift+i nur eine email erzeugt)
umschalt ist doch shift oder?

wie auch immer...cache geleert nach Anleitung...nix

**Comment by bthau** [comment]
#43 hat jetzt bei mir funktioniert - vielen dank :)

**Comment by frankholler** [comment]
Habe das selbe Problem. Cache löschen hilt einmal Welt wechseln. Der Workaround von #43 hält auch genau einmal Welt wechseln, danach ist der Kostenrechner und auch der Eigenanteilsrechner immer deaktiviert, obwohl der Haken bei "Disable Cache" noch drin ist. Ich nutze Chrome unter Windows.

**Comment by bthau** [comment]
ich habe gerade herausgefunden dass der rechner dann nicht funktioniert wenn man einmal drauf geklickt hat ohne ein lg geöffnet zu haben. dann den cache leeren, aktualisieren und schon geht es wieder - also war gerade bei mir so

**Comment by Moods01** [comment]
Ich habe ebenfalls das Problem, dass seit dem Update Kosten, Eigenanteilsrechner und FP Lager nicht mehr angezeigt werden. Mit #43 funktioniert es wieder bis zum neustarten oder aktualisieren der Seite, dann muss der ganze Vorgang wiederholt werden. :(

**Comment by gerrybass** [comment]
auch bei mir läufts nicht... trotz löschen des cache

**Comment by Julian2424** [comment]
Cache löschen hat das Problem temporär behoben. Wird der Browser neu gestartet, funktioniert es wieder nicht.

**Comment by Selene443Foe** [comment]
Oh ein Erlösungsschrei ging durch die Gilde nachdem ich den Text von #43 gepostet hab.
Das Teil ist tatsächlich nach dem Update in der kompletten Gilde ausgefallen.
Vielen Dank für den schnellen (temporären) Lösungsweg :) Bis jetzt funktioniert es....

**Comment by dsiekiera** [comment]
Das sind alles Cache Probleme. Chrome ist sehr hartnäckig was das angeht.

**Zur Erläuterung:**
Es gibt zwei Arten von Caches. Einer Cached die _Extensions_ und der andere was man "_sieht_".

Der FoE Helfer ist eine Extensions die sich auch noch in die Webseite injiziert. Sitzt also in beiden Caches.

Der Plugin Cache wird über diesen Weg gelöscht: [weiter oben](https://github.com/dsiekiera/foe-helfer-extension/issues/60#issuecomment-511963091)

Der "Sichtbare Cache" über die #43. 

Ich würde beide purges hinterander durchführen. Da der Pugin-Cache den Sichtbaren wieder überschreiben kann usw... Warum das so ist, weiß ich nicht. Google halt.

Sollte beim Weltenwechsel etwas nicht klappen, meine Empfehlung:
Gemäß #43 die Konsole öffnen, Haken drin bei "Disable Cache" und einen Spalt offen lassen auch wärend des Weltenwechsels. Gerne auch alle eigenen Welten hintereinander durchsteppen. Jede URL hat ihren eigenen Cache. 
Man kann die Konsole mit der Maus kleiner schieben.

Wenn dann alles passt, wird es auch für immer so bleiben und ihr solltet keine Probleme mehr haben.

**Comment by Moods01** [comment]
Was heißt das?  **Haken drin bei "Disable Cache" und einen Spalt offen lassen** Oder wo finde ich das. 
Ich bin schon froh, dass ich das andere hin bekomme, ich kenne mich gar nicht mit sowas aus :)

**Comment by dsiekiera** [comment]
`Der "Sichtbare Cache" über die #43.` Dort steht es drin.

**Comment by Lyssina** [comment]
Klare Sache - bei mir haut's nicht mehr hin, Suuuuuuuper schade, das Tool war vor dem letzten Update eine wucht, jetzt ist es praktisch nicht mehr zu gebrauchen, zumindest für mich nicht.

Mit dem Schritt #43 kann ich mich salopp gesagt "dranhalten", das Tool hängt sich spätestens dann auf, wenn ich die Welt gewechselt habe und auf die Welt zurückkehre, auf der ich morgens begonnen habe. Schritt #43 und es geht wieder - bis zum nächsten Hänger...

Heute morgen gibt es eine neue "Macke", obgleich mein Inventar komplett leergefegt ist und alle FP im Umlauf sind, zeigt das Tool ganz stoisch 100FP an, die definitiv nicht mehr da sind... Schritt #43 ausgeführt und die FP sind weg, bißchen irgendwo rumgeklickt und sie stehen wieder da - wäre ja ein netter FP-Brunnen, aber leider sind die Dinger nur im Tool und nicht in der Realität vorhanden!

Was immer mit dem letzten Update geändert wurde, zumindest mit den Chachesettings auf meinem relaitv modernen und nicht ganz kleinen Rechner kommt das Tool nicht mehr klar - schade!

**Comment by Moods01** [comment]
Ich habe jetzt alles befolgt was Du geschrieben hast. Es ist nach jedem Neustart des Spiels, alles weg und ich muß wieder die Chache in den Einstellungen löschen.

**Comment by Moods01** [comment]
Auch habe ich das Tool entfernt und wieder installiert. Leider bleibt es dabei, ich persönlich brauche auch keinen extra Overlay für den Tavernenboost, Den sehe ich über der Taverne, ich fand es vor dem Update einfach besser. Tut mir Leid! Sonst wirklich eine klasse Arbeit von Dir, muß man auch erwähnen. Leider macht es so keinen Spaß.

**Comment by gerrybass** [comment]
ja, das tool hatte ich erst vor n paar tagen empfohlen bekommen und meine begeisterung fand keine grenzen mehr... aber nun ist es leider überflüssig geworden! echt schade :-((((

**Comment by Julian2424** [comment]
Es ist definitiv nicht nur ein Cache-Problem. Da muss auch was bei der Erweiterung faul sein. Ist der Cache leer, funktioniert es, mach dem 2x geht es nicht, egal, was man löscht.

**Comment by Elschen** [comment]
So, spiele auf drei verschiedenen PCs, ich habe alle Anleitungen befolgt und alles an cache gelöscht, was zu finden war. Es löppt nich! Das Teil für den Aussenposten und die Taverne brauch ich auch nicht. Lieber wieder die Version davor, die war nämlich wirklich klasse!

**Comment by MrMattn** [comment]
als ich spiele mit Betriebssystem OSX und hab jetzt wie Daniel geschrieben hat, erst den normalen Cache (Bilder usw) gelöscht und dann über die Konsole noch den anderen.
DAS hat dann jetzt geholfen und es blieb die letzten 15min dauerhaft alles da

**Comment by dsiekiera** [comment]
So Kinners. Nun hatter das gelöst.

Hab eben das Update eingereicht. Bei mehreren Test, auch auf anderen Systemen, klappt alles wunderbar.

Die neue Version ist dann die 2.3.0.

Eur Feedback ist gerne gesehen ;-)

**Comment by MrMattn** [comment]
so also die ersten 20 min....waren top (nachdem heut morgen nichts mehr ging....)
wäre ja top! hast du also Fehler gefunden? ;-)

**Comment by Moods01** [comment]
Hallo, bei mir läuft es einwandfrei! Das war mir wichtig ist. Es wurde ein extra Thread aufgemacht, das der Außenposten sich nicht aktualisiert. Habe ich auch, ist mir aber nicht wichtig :)
Vielen Dank für Deine Mühe

**Comment by Elschen** [comment]
Nachdem Update und einer erneuten gründlichen Cache-Reinigung läuft es wieder. Klasse!

**Comment by Selene443Foe** [comment]
Daumen hoch! 
Ich sammle aus zwei Gilden die Meldungen zum FoE-Tool ein :D 
Bei Kleinigkeiten kann ich selbst Rat geben, alles andere stelle ich hier ein.
Die Reparatur des Kosten- und Eigenanteilrechners hat offensichtlich gut geklappt. Bisher nur Lobeshymnen :D 
Vielen Dank dafür.

**Comment by Lyssina** [comment]
Irgendwas läuft bei mir noch verkehrt - das Tool haut immer mal wieder ab und läßt sich dann nicht mehr starten. Ich habe diverse Formen des "Cache-Löschens" laufen lassen, gleich danach ist alles fein und die Sidebar wieder da, irgendwann will ich sie dann nutzen und äh??? Weg ist sie wieder!

HAst Du einen Tip für mich, was falsch laufen könnte? Ging doch vorher auch ohne Probleme...
