### ISSUE TITLE
Missing translation variables

### ISSUE THREAD

**Issue by Beta-Wolf** [dsiekiera/foe-helfer-extension#602]
Some words in the extension aren't able to be translated yet.

https://forum.foe-rechner.de/d/192-words-that-arent-able-to-be-translated

Also the notifications bottom right of the screen, when information is transmitted are in German and can't be translated yet.

**Comment by andrgin** [comment]
I have added the translations. You can get a copy of the beta branch and update the nl.json.

**Comment by Beta-Wolf** [comment]
![unknown (3](https://user-images.githubusercontent.com/31244425/76661310-6817e280-657b-11ea-988e-5a86a41d1622.png)
