### ISSUE TITLE
Bug: Menü: Positionen der Icons werden nicht mehr gespeichert

### ISSUE THREAD

**Issue by gneiss15** [dsiekiera/foe-helfer-extension#609]
Version 2.4.2.1
Wie im Titel beschrieben. Werden die Icon via Drag&Drop anders angeordnet, bleibt das "nur kurz" bestehen, jedes reload (oder noch was anderes) stellt die "Standard"-Anordnung wieder her.

**Comment by andrgin** [comment]
Sieht so aus als wäre beim letzten Update was schief gegangen. Das sollte eigentlich schon gefixed sein...
