### ISSUE TITLE
Nach Lösung des Cache-Problems funktioniert der Außenposten nicht mehr....

### ISSUE THREAD

**Issue by SamBrePy** [dsiekiera/foe-helfer-extension#61]
Moin!

Danke für die Lösung des Cache-Problems. Und danke für das Tool!! Ich bin riesiger Fan und nutze es täglich intensiv!!
Der Teil der gestern noch das Cache-Problem hatte läuft nach deinem Update bei mir problemfrei!

Dafür updaten sich die Zahlen des Außenpostens aber leider nicht mehr.  Sie bleiben konstant auf dem Stand von gestern, auch wenn ich ein neues Gebäude frei schalte.
Versucht habe ich bereits:
- Reload
- Relog
- Funktion aus-/einschalten
- Cache löschen
- PC Neustart
Zahlen bleiben die von gestern - auf 3 Welten. 

Geht das noch jemandem so?

**Comment by dsiekiera** [comment]
Haste denn was geerntet damit es sich verändern kann? Bei mir springen im Wikinger Dorf sofort die Münzen oder der Güter nach oben wenn ich etwas ernte.

**Comment by cloudts** [comment]
Hallo, 
bei mir Funktioniert es leider auch nicht.
Ich habe geerntet es verändert sich leider nichts

**Comment by SamBrePy** [comment]
:-))) Ja, ich habe in allen drei Städten entweder geerntet oder neue Gebäude frei geschaltet. Weder der Stand der Münzen ändert sich, noch die Tabellenangaben zu den noch benötigten Gütern.
In der Stadt mit neu frei geschaltetem Gebäude steht die Liste auch immer noch in der Zeile zur Freischaltung des Selbigen.

**Comment by dsiekiera** [comment]
Hab das hier bei mir bereits gefixt. Da fehlte noch eine Funktion aus der 2.2.16 die genau das überwacht hat.
Schicke ich nachher raus.

**Comment by Julian2424** [comment]
So lange das Cache-Problem dann nicht wieder auftritt :P

**Comment by Selene443Foe** [comment]
Wie kann man sehen welche Version man denn in seinem Chrome hat?
Vielleicht kannst du das in die Seitenleiste mit einbauen?

**Comment by kneipenjaeger** [comment]
Welche Version Du hast siehst Du so:
Rechte Maustaste auf Deine Erweiterung von FoE Helfer im Chrome
Erweiterungen Verwalten anklicken und dann siehst Du die Versin, die Du hast

**Comment by SamBrePy** [comment]
Also bei mir funktioniert der Außenposten leider nach wie vor nicht. Habe in 1 Stadt mittlerweile sogar Runde 2 bei den Japanern begonnen - die Anzeige ist und bleibt aber die von vor dem Update das das Cache-Problem auslöste.
Habe auch heute wieder alle möglichen Schritte durch und viel hin und her probiert...... :-( 
Ohne Erfolg, leider.
Da der Rest funktioniert, spiele ich halt ohne die Außenpostenfunktion......was aber SCHADE ist, da ich die Tabelle wirklich klasse finde...
GLG

**Comment by dsiekiera** [comment]
Hab das angepasst. Die Werte, welcher Typ Außenposten, welche Güter, die Übersetzungen usw. sollten nun alle sauber laufen. Zu mindest tuen sie das in der Testumgebung ud bei ein paar Testern.
