### ISSUE TITLE
Falsche FP Errechung Eigenanteilsrechner

### ISSUE THREAD

**Issue by ullin** [dsiekiera/foe-helfer-extension#613]
![image](https://user-images.githubusercontent.com/61455318/75234819-88921f80-57bb-11ea-9667-4f3549d19f72.png)

Anbei ein Snip - schaut mal wenn ich jetzt mit die Werte für die Förderung automatisch kopieren/erstellen lasse sagt er mit das kein Platz sicher ist.

Wenn ich P5 mit 9 belegen lasse dann ist dieser sicher!?

Nicht weltbewegendes aber ich möchte drauf hinweisen.

**Comment by dsiekiera** [comment]
Es fehlen noch 5 FP Eigenanteil. Dann wäre P5 sicher.

**Comment by ullin** [comment]
Sorry komplett daneben...Mathe für Anfänger oh mein Gott :/

Sorry das war quatsch!

**Comment by dsiekiera** [comment]
Kein Problem. Viel Spaß weiterhin.
