### ISSUE TITLE
wrong goods

### ISSUE THREAD

**Issue by yuckup** [dsiekiera/foe-helfer-extension#614]
am i missing something here ?
![image](https://user-images.githubusercontent.com/61456290/75237574-b73be480-5813-11ea-9e7c-e8f958b3f39c.png)

**Comment by andrgin** [comment]
Was this a negotiation with 4 different goods?

**Comment by yuckup** [comment]
possible ? never took much notice

**Comment by andrgin** [comment]
1.) Did the negotiation helper suggest this combination or did you pick it yourself?

2.) Which version of the extension are you using. Do you have 2.3.2.1 installed? (click the settings icon)

**Comment by yuckup** [comment]
foe helper suggested and have version 2.4.2.1 installed

**Comment by yuckup** [comment]
![image](https://user-images.githubusercontent.com/61456290/75618635-515dad00-5bc5-11ea-8c5b-f1cb9fb062ec.png)
happened again was 5 goods negotiation 
foe helper version 2.4.2.2

**Comment by andrgin** [comment]
You picked the wrong good on the 5th place.
Currently the last line shows the goods that you have selected, not the goods that you should have selected. We will change that in the next update to make it more clear what went wrong.
