### ISSUE TITLE
Recommended Army

### ISSUE THREAD

**Issue by MickW69** [dsiekiera/foe-helfer-extension#618]
Would love to see a recommended army, taking the units that your battling against vs the units that have a bonus against them, pick one of each of these units, plus rouges.

**Comment by andrgin** [comment]
Would be nice, but not possible, because battles are far too complex to be calculated considering all the different abilities, AI behaviour, terrain etc.

**Comment by kchwistek** [comment]
I have an idea how to implement this functionality. 
A small neural network decision making might do the work. The neural network can be trained by real examples. i.e. collecting data about fighting armies and fight results. For training purposes the Enemy Army would be Input vector, Your army will be resulting vector. Vectors can contain also information about the attack and defense bonuses. Your army damage will be used for the classification of the selection. This decision will not cover battlefield specifics but this can be ignored I think ... 
A simple training service running on some server can train NN. Trained NN can be part of the extension distribution once NN is trained or can be pulled from the server in the time of extension load.

**Comment by Th3C0D3R** [comment]
thats not a bad Idea. the main problem are:
- I dont think we have one which can do such stuff
- it will be a little more complex as you described it.

**Comment by kchwistek** [comment]
I can do something arround ... I do not think it will be that difficult there are available NN implementation in javascript ... No promisses but I will start to shape it.

**Comment by Th3C0D3R** [comment]
Wow that would be really great 🙈
Sadly I have no time for that (RL and work) else I would have taken a look

**Comment by kchwistek** [comment]
Is there a way how to read a content of the FoE fight dialog? i.e. other than catching ArmyUnitManagementService ?

**Comment by osv** [comment]
No, this is blackbox

**Comment by SkateScout** [comment]
Hi, it is possible with BattlefieldService submitMove you get the Army of the player and oponent as well as the battle result and if it was auto play. But also the relation of attack/defense bonus are relevant.

**Comment by kchwistek** [comment]
Yes I know I am using it to get the battle results. But if speaking about the BattleAdvise then I need to get the opponent army before player submit. I did not find a way how to get this info yet.

**Comment by scibuff** [comment]
There is `BattlefieldService.getArmyPreview` for the Battlegrounds armies, for example.

You can use the following code to see all services & method calls (for both http/json as well as websockets and the actual data), just copy/paste into the console

```
FoEproxy.addRawWsHandler( data => { 
    if ( !data || !data[0] ){ return; } 
    let requestClass = data[0].requestClass;
    let requestMethod = data[0].requestMethod; 
    console.log('WS '+requestClass+'.'+requestMethod); console.log(data);
});

FoEproxy.addHandler( 'all', 'all', data => { 
    if ( !data ){ return; } 
    let requestClass = data.requestClass;
    let requestMethod = data.requestMethod; 
    console.log(requestClass+'.'+requestMethod); console.log(data);
});
```

**Comment by kchwistek** [comment]
Thank you so much for the HINT!

**Comment by kchwistek** [comment]
I gave up with idea of the AI/Neural Network analysis... Instead of that I am thinking about collecting data on server and allowing users to query them . If it would be a part of your code then I think it should be hosted on your server. Is it possible ?
