### ISSUE TITLE
Investitionen: Alte Investitionen werden nicht immer entfernt

### ISSUE THREAD

**Issue by andrgin** [dsiekiera/foe-helfer-extension#619]
Investitionen werden nicht aus der Liste entfernt, wenn man beim nächsten Mal hochladen nach dem Leveln schon wieder neu eingezahlt hat. In diesem Fall bleibt das alte LG erhalten. Das neue LG wird nicht angzeigt.

**Comment by andrgin** [comment]
Problem besteht noch immer

**Comment by dsiekiera** [comment]
OK. Will take a look once more.
