### ISSUE TITLE
Nach Update 2.3.0 Keine Erweiterung auf de4

### ISSUE THREAD

**Issue by skyruner** [dsiekiera/foe-helfer-extension#62]
Huhu,

nach dem letzten Update funktioniert die Erweiterung auf DE4 nicht mehr. Auf 2 anderen Welten funktioniert wieder alles (abgesehen vom Außenposten) normal.

Grüße
Sky

**Comment by DasAtom** [comment]
Hast du auf De4 schon mal nen cache refresh erzwungen? Strg+R. Kann sein dass auf der Welt noch Blödsinn im Cache rumliegt von vor dem Update

**Comment by skyruner** [comment]
Cache schon mehrfach gelöscht, aber ohne Erfolg. Auf der gleichen Welt funktioniert das Update bei anderen Spielern.

**Comment by ClaesSparre** [comment]
Das kann ich bestätigen. Seit dem letzten Update funktioniert die Extension 50/50. Mal ist sie sofort da, mal nicht. Wenn nicht, dann sind Browserbereinigung und  bis zu 5 Neustarts des Spiels FoE nötig, damit sie wieder geht. (Eigenleben?)

**Comment by dsiekiera** [comment]
Alter gefixter Fehler.
