### ISSUE TITLE
Affichage de la barre latérale / Sidebar menu

### ISSUE THREAD

**Issue by SdQY78** [dsiekiera/foe-helfer-extension#622]
La barre latérale regroupant les différentes commande (en bas à droite) est gênante car elle masque une partie de l’écran, en particulier dans les combats du Type EG, CdG, ... .
Il faudrait pouvoir la réduire.
Pour info, je suis sous Chrome.
Merci d’avance et bravo pour cette extension géniale.

The sidebar grouping the different commands (bottom right) is annoying because it hides part of the screen, in particular in combat of Type EG, CdG, ....
We should be able to reduce it.
FYI, I'm on Chrome.
Thanks in advance and well done for this awesome extension.

**Comment by outoftheline** [comment]
There are dofferent menu position options now, hope that resolves this.

**Comment by SdQY78** [comment]
Bravo pour la nouvelle barre d'outils. Elle va au delà de mes espérances.
