### ISSUE TITLE
foemanager

### ISSUE THREAD

**Issue by ZorakYj** [dsiekiera/foe-helfer-extension#626]
Viele kennen Bestimmt die Seit foemanager.com, es ist eine art Baukasten Seite mit der man den Umbau seiner Stadt planen kann. Der größte vorteil war das man die Daten seiner Stadt importieren konnte und so die Stadt nicht erst nachbauen musste. Dies geschah über Bots die die Daten auslasen, leider wurde nun diese Bots von FoE gesperrt. Jetzt kam mir die Überlegung ob es nicht möglich wäre mit foemanager zu kooperieren und die Daten aus der Stadtübersicht zu übermitteln oder halt was eigenes zu programmieren um einen Stadt umbau zu planen.

**Comment by andrgin** [comment]
Ja wäre möglich und wurde dem Emtwickler auch schon angeboten. Wie der Entwicklungsstand bei ihm ist weiß ich jedoch nicht.

**Comment by outoftheline** [comment]
scheint irgendwie im sande verlaufen zu sein, daher schließ ich hier mal
