### ISSUE TITLE
LiveChat funktioniert (bei mir) nicht

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#63]
Guten Abend :)
ich kann nicht Recht nachvollziehen wie das sein kann, vielleicht nur eine Einstellungssache?
Im LiveChat werde ich teilweise gesehen, teilweise kann man lesen was ich schreibe, teilweise nichts von all dem.
Ich selbst sehe garnichts. Es ist so als ob ich allein im Raum bin.
![3 1](https://user-images.githubusercontent.com/50969949/61567381-95110580-aa7f-11e9-92fb-de28528ea925.GIF)
![3](https://user-images.githubusercontent.com/50969949/61567382-95a99c00-aa7f-11e9-95ac-0982328f60a0.GIF)

Was kann ich tun?

**Comment by Selene443Foe** [comment]
Vielleicht könnte man den Chat auch so machen wie alle anderen Fenster?
Einfach als Overlay verschiebbar, oder zumindest als Option für Leute mit zweitem Bildschirm.
Wenn als Overlay wäre aber eine Skalierbarkeit (größer/kleiner machen) sinnvoll.

Wenn man den Button ein weiteres Mal betätigt (um das Chatfenster aufzurufen), dann öffnet sich noch ein Chatfenster. Schließt man das zweite wird im Textfeld angezeigt das man gegangen ist, obwohl man noch drin ist.
Vielleicht könnte man das auch anders machen?

**Comment by dsiekiera** [comment]
Die Option im Fenster hatte ich zu Beginn mal. Aber dann war das Teil ständig im Weg. Daher hab ich das als einzelnes Fenster gebaut.
Ist dieses Fenster im Hintergrund, macht es sogar "Ping!". Bitte teste das noch ein mal. Hier klappt das in allen Tests.

**Comment by dsiekiera** [comment]
Wurde geupdatet und sollte nun überall funktionieren.
