### ISSUE TITLE
FOE Helper Negotiation Suggestions Window Covers Goods Selections on 4th Turn

### ISSUE THREAD

**Issue by ndjv2739** [dsiekiera/foe-helfer-extension#632]
The Suggested Goods window formerly was movable, but was recently changed to be fixed-position. It grows downward as goods are selected for negotiation. This causes a problem since the Suggested Goods window now hides the top row of the goods selection window on the 4th negotiation turn. Please change the goods suggestion window back to "movable" (like it was before) so it can be manually moved up to reveal the hidden goods selection window on the 4th turn.

**Comment by andrgin** [comment]
Can you use the bug report template here as it seems to be a problem only with your system: https://github.com/dsiekiera/foe-helfer-extension/issues/620

Can you provide a screenshot. Which resolution do you play the game at?

**Comment by ndjv2739** [comment]
Mac OS/X Catalina 10.15.3

Hardware Overview:
  Model Name: Mac mini
  Model Identifier: Macmini8,1
  Processor Name: 6-Core Intel Core i7
  Processor Speed: 3.2 GHz
  Number of Processors: 1
  Total Number of Cores: 6
  L2 Cache (per Core): 256 KB
  L3 Cache: 12 MB
  Hyper-Threading Technology: Enabled
  Memory: 16 GB
  Boot ROM Version: 1037.80.53.0.0 (iBridge: 17.16.13050.0.0,0)
  Serial Number (system): C07YL0F5JYW0
  Hardware UUID: 4185D2F2-89E5-5E8D-992E-43D6D13DC19C
  Activation Lock Status: Enabled
Display:
  HP 32 QHD
Browser:
  Waterfox 2020.02.1 (64 bit)
FOE Server:
  US19
FOE Helper 2.4.2.4 (English)
Console:
  No errors shown
FOE Helper.png - attached



Verwendeter Browser inkl. Versionsnummer / Used Browser including version
Forge of Empires Server
Extension Version und Sprache der Extension. Falls ihr Betatester seid
unbedingt dazuschreiben!!! / Extension version and language of the
extension. If you are beta tester include that as well!!!
Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole"
wechseln) / Errors in the console (press F12 and switch to console tab)

Beispiel / Example:
Windows 10 64 Bit
Chrome 80.0.3987.122
de16 (Qunir)
2.4.2.2 - Deutsch

**Comment by Th3C0D3R** [comment]
there is no image attached

**Comment by ndjv2739** [comment]
[image: FOE Helper.png]

**Comment by Th3C0D3R** [comment]
still no image. maybe dont answer from Email?

**Comment by ndjv2739** [comment]
![FOE Helper](https://user-images.githubusercontent.com/61363686/76536933-035d6a80-644b-11ea-9f76-5ae1cb478142.png)

**Comment by ndjv2739** [comment]
Try above image.

**Comment by ndjv2739** [comment]
I did try a higher screen resolution and it didn't help. The window overlap still happened. 

Note: this is a fairly recent issue. The behavior of the windows has changed in the past 2-3 weeks. Before that, the top window was movable and I could adjust its position to make the negotiation window visible. Since the change, I cannot move it: it's fixed in a position that hides the top part of the negotiation suggestions. If the suggestions window were movable again, the problem would be fixed.

**Comment by andrgin** [comment]
Already fixed in current version.

Btw. moving the window is not required as the suggestion show exact the same as the ingame window.
Selection of goods can be done with the shortcuts displayed on the good icons.
