### ISSUE TITLE
Firefox Addon - Falsche Anzeige

### ISSUE THREAD

**Issue by thepab** [dsiekiera/foe-helfer-extension#636]
Mit der neuen Version des Addons ist die Anzeige der Seitenleiste schlecht. Sehe den Printscreen.
window10, mit Firefox 73.0.1 (64 bits)
![Addon_FOE_Rechner](https://user-images.githubusercontent.com/61996796/76267840-53caa180-626c-11ea-8b10-bcdee4e3a7a3.PNG)
![Version_Addon_FOE_Rechner](https://user-images.githubusercontent.com/61996796/76267905-8bd1e480-626c-11ea-8a8b-c38691d00cbb.PNG)

ich habe schon den browser-Cache geleert. und der Addon deinstaliert und wieder installiert ohne Erfolg.

**Comment by Th3C0D3R** [comment]
there is an update to 2.4.2.4 please install it

**Comment by thepab** [comment]
es ist jetzt gut mit dem neuen Version 2.4.2.4. Danke
