### ISSUE TITLE
Forschungskosten werden fehlerhaft berechnet

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#638]
Moin,

da ich gerade kurz vor dem Ende meines aktuellen Zeitalters bin, ist mir das vermutlich jetzt erst aufgefallen.
Ich habe noch zwei offene Forschungen, bevor es von OZ in die VZ geht. Hierbei stimmt aber die Berechnung der Forschungskosten nicht, wie angehängte Screenshots zeigen.
![f2](https://user-images.githubusercontent.com/17932878/76316344-be1a2b00-62da-11ea-873e-91222d6bd7fd.png)
![f1](https://user-images.githubusercontent.com/17932878/76316345-beb2c180-62da-11ea-8298-9ce95d734ab6.png)
![Forschungskosten](https://user-images.githubusercontent.com/17932878/76316346-bf4b5800-62da-11ea-8853-5184f4fb87b5.png)

Beispielsweise:
- Münzen: 13000000 statt 12500000
- Vorräte: 12500000 statt 12000000
- Nanokabel: 500 statt 320
- FP: 148 statt 200

**Comment by frank42hh** [comment]
Edit: Mir ist eine Idee gekommen und habe nachgeschaut. Ich glaube, die Ursache liegt hier:
![f3](https://user-images.githubusercontent.com/17932878/76317838-194d1d00-62dd-11ea-84b7-b884ee055fbd.png)

Hierbei handelt es sich um eine einzelne offene Forschung in der AZ, und wenn ich mir die Werte so ansehe, könnte diese die Differenz erklären, allerdings nicht, warum eine AZ Forschung bei den Forschungskosten OZ -> VZ mitgerechnet wird :-)

**Comment by andrgin** [comment]
Da hast du Recht. Die Filter für abgeschlossene Zeitalter funktioniert noch nicht ganz.
