### ISSUE TITLE
Eigenanteilsrechner (Webseite)

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#64]
Guten Morgen :)

der Eigenanteilsrechner der Webseite hat beim Saatguttresor Stufe 31 einen Berechnungsfehler:

![4](https://user-images.githubusercontent.com/50969949/61568984-92b1aa00-aa85-11e9-829b-c580603e6c42.GIF)

**Comment by dsiekiera** [comment]
@Selene443Foe Verräts Du mir auch welchen, bzw. wo?? Oder muss ich das alles nachrechnen?

**Comment by dsiekiera** [comment]
Mein Fehler. Auf den zweiten Blick habe ich gesehen das gar keine Werte enhalten sind.

Die Daten werden via Crawl regelmäßig von einer englischsprachigen Seite gezogen. Die haben einfach mal Tippfehler in ihrem Quellcode. Hab den Crawler angepasst, die Daten sind nun bis Level 109 Verfügbar.
