### ISSUE TITLE
Gildengüter-Bilanz

### ISSUE THREAD

**Issue by SalvatoreAmarone** [dsiekiera/foe-helfer-extension#645]
Ich wünsche mir eine Übersicht, welche Güter über die Gebäude und Zeitalter in die Gildenkasse fliesst, sowie eine Rechnung darüber, was an Ausgaben wieder weg geht, und damit eine Analyse gemacht werden kann, in welchem Zeitalter welche Güter knapp werden.
Was neu gebraucht wir, ist das Auslesen der Zeitalter der Member. Über Archen, Observatorien, Atomiom, Ruhmeshallen und Ehrenstatuen kann man die Gütereinnahmen errechnen.
Ausgaben der Gildenexpedition kann man vorkalkulieren lassen.
Als weitere Posten müsste man dann die GvG und Gildengefechtsausgaben ausweisen können.

**Comment by dsiekiera** [comment]
Die Idee kam schon öfter auf. Nach ersten Einschätzungen sind das unmengen an Daten die gespeichert und ausgewertet werden müssen.
Wir werden uns was überlegen.

In der Extension selbst ist das nicht lösbar und wird mit Übertragungen an foe-rechner.de gelöst werden müssen.

**Comment by R3d-N4x3l4** [comment]
@SalvatoreAmarone https://www.foe-tools.eu/
