### ISSUE TITLE
GG lassen sich bei aktiviertem Plugin nicht betreten (Firefox)

### ISSUE THREAD

**Issue by news2swen** [dsiekiera/foe-helfer-extension#649]
Win10 64bit
Firefox 73.0.1
de5
Version 2.4.2.4

Bei aktiviertem Plugin ist es nicht möglich, Gildengefechte zu betreten. Meldung "Gefecht nicht erreichbar. Es scheint momentan ein Problem beim Betreten des Gefechts zu geben. Bitte überprüfe deinen Netzwerkverbindung und versuche es später erneut."

Nach Schließen der Meldung kann man in der Stadt nichts mehr machen(Gebäude öffnen, Scrollen, die Karte bewegen...), lediglich die Menufunktionen (Nachrichten, Gildenexpedition, Optionen , ...) sind auswählbar. Nach dem Reload der Seite funktioniert wieder alles, solange die GG nicht wieder betreten werden soll.

Deaktiviert man das Plugin, funktioniert alles.

**Comment by dsiekiera** [comment]
Das klingt nach einem sehr alten Fehler den wir mal hatten. Da du bissher der einzige mit diesem Problem bist, würde ich das erst mal auf deinen Browser eingrenzen. 

Ist es möglich das du mich über die Mail im Impressum von foe-rechner.de kontaktierst und wie schauen mal via AnyDesk zusammen ins Spiel?

**Comment by andrgin** [comment]
Kannst du die Extension noch einmal installieren und neu probieren. Ich denke das liegt an Inno Games. Ich hatte genau dasselbe Problem sporadisch ein paar Tage davor mit der Android App.

**Comment by news2swen** [comment]
Ich habe die Extension noch mal neu installiert und nun funktioniert es. Danke
