### ISSUE TITLE
Berechnung Aussenposten Japaner fehlerhaft

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#65]
http://prntscr.com/ohn6p2

also wenn ich mir das genau anschaue...sagt er ich brauche noch Instrumente für Zen Garten.
Dieser ist aber schon freigeschaltet!? Und Rüstungen passt auch nicht...und auch die Kobanmünzen sind fehlerhaft ;-)
Lass mich raten...Cache Problem? :-D

**Comment by DasAtom** [comment]
Wahrscheinlicher ein Problem mit einer alten Version der extension siehe #61. Der Chrome Store scheint die gefixte 2.3.1 nicht rauspushen zu wollen. Der Changelog auf der Website ist auch angepasst angepasst. Google will aber nicht, dass wir die bekommen

**Comment by dsiekiera** [comment]
Die habe ich vor 2min eingereicht. Gebt Google ruhig mal 10 min Zeit 😁

DasAtom <notifications@github.com> schrieb am Sa., 20. Juli 2019, 15:44:

**Comment by DasAtom** [comment]
Timing kann ich ;D Danke dir für deine Arbeit!

**Comment by MrMattn** [comment]
jep spitze klappt!
update kam nicht. also entfernt und neu hinzugefügt.

**Comment by dsiekiera** [comment]
Siehe #61
