### ISSUE TITLE
Incidents on roads

### ISSUE THREAD

**Issue by PaulH111** [dsiekiera/foe-helfer-extension#650]
Several closed issues,  but I am having same problem.

Incidents on "big Road" - apparently a big road is a 2 x 2 - but although I am in Prog Era I do not ave any.  At all.

I have tried using the builder - but other web posts indicate that incidents disappear when entering build mode so won;t work.  I have also moved all my buildings individually to look behind - no sign of incidents. Also tried to click on every single road section and even though I have (apparently) four current incidents not a single hit.

Tried using the "big Building",both moving existing and building new one. neither works unless the centre where the mouse pointer is when clicked is over the incident (tested using a previous incident I could see).

Since the software identifies the incident, could it be coded to give the location as well?

**Comment by dsiekiera** [comment]
This is not possible. Inno sends only the type and the time. No location. 
Build one 2x2 street and switch to the outpost and back. Then u can collect the event.
Otherwise u can't get the event. This is calculated by inno.

**Comment by PaulH111** [comment]
Wow!  Mega quick response.  

And it works...A but of a pain having to build a pointless 2x 2 road, but did that, switched in and out of outpost and all four big road incidents cleared.

VMT

PH

**Comment by dsiekiera** [comment]
This is the inno logic. 😉

**Comment by Jay1181** [comment]
Wow!! I had to build one section of double-wide road to get those incidents. I collected and refreshed three times to get all of them. Thanks for the tip. INNO makes the most interesting games... and not always on purpose.  lol
