### ISSUE TITLE
Missing popup when visiting neighbors

### ISSUE THREAD

**Issue by Squazz** [dsiekiera/foe-helfer-extension#651]
When visiting neighbors I don't get a pop-up showing me what I'm able to loot

I tried disabling and uninstalling the plugin and then turning it back on again. No change.
Works fine on other computers

The option is enabled under settings

Windows 10 64 Bit
Chrome 80.0.3987.132 (Officiel version) (64-bit)
de16 (Qunir)
2.4.2.2 - English

**Comment by andrgin** [comment]
Did you try resetting the box coordinates in the settings menu?

Was the player a friend of guild member?

**Comment by Squazz** [comment]
Yup, I also tried resetting box coordinates :)

The player was not a friend or a guild member.
I visted the same player(s) on another computer, and there the plugin worked just fine

**Comment by Squazz** [comment]
I just got it working

Resetting box coordinates didn't work.
But resizing the window & reloading the game did.

I don't know if it has anything to do with the fact that I have a 21:9 screen

**Comment by outoftheline** [comment]
As the popup has been removed, I'll be closing the issue.
