### ISSUE TITLE
Ereignisse auf Strassen werden zu früh angezeigt

### ISSUE THREAD

**Issue by mordillo666** [dsiekiera/foe-helfer-extension#653]
Mir ist aufgefallen, dass die Ereignisse auf Strassen immer zu früh im Plugin angezeigt werden. Sie erscheinen dann in der Stadt ca 30min später.

**Comment by Th3C0D3R** [comment]
Der Zeitpunkt der angegeben ist, ist der Zeitpunkt ab dem dieses Ereignis auftauchen kann. Sobald der erreicht ist gibt es ein 2. Zeitpunkt bis zu diesem das Ereignis erscheinen kann. Es kann schon sein das es erst eine halbe stunde später in der Stadt auffindbar ist. Dagegen gönnen wir nichts machen, aber normal sollte es mit erreichen des 1. zeitpunktes einsammelbar sein

**Comment by mordillo666** [comment]
Ah ok, dann ist das also normal. Mir war es nur aufgefallen, da ich noch ein solches Ereignis offen hatte und für eine Quest gebraucht hätte und ich mir dann einen abgesucht hatte. ^^
