### ISSUE TITLE
Missing translation variables

### ISSUE THREAD

**Issue by Beta-Wolf** [dsiekiera/foe-helfer-extension#654]
![unknown (3](https://user-images.githubusercontent.com/31244425/76661389-985f8100-657b-11ea-83a2-6d9236b08b84.png)

**Comment by Beta-Wolf** [comment]
(undefined)

**Comment by andrgin** [comment]
I think this is not a translation issue. It is because your current stock of these goods is 0.

**Comment by Beta-Wolf** [comment]
It should be in Dutch (onbepaald) when your stock of these goods is 0.

**Comment by andrgin** [comment]
The "undefined" is a bug, even in the English version. It should show (0). Will be fixed in the next update.
