### ISSUE TITLE
Im globalen Userverzeichnis von FoE nach spezifischen LGs suchen 

### ISSUE THREAD

**Issue by Otto962** [dsiekiera/foe-helfer-extension#655]
Hallo, 

ich suche gerade möglichst viele FoE-Spieler, die das VIRGO-Projekt (wenn möglich aktiv) bespielen. 
Die ersten 70 Spieler in der globalen Liste hab ich manuell durchgecheckt. Könnte man das im FoE-Rechner vielleicht auch automatisieren? 

Beste Grüße
Otto

**Comment by andrgin** [comment]
Die LG Daten werden erst übertragen, wenn man zumindest die LG Übersicht des Spielers öffnet und dort hast du sowieso schon eine Liste der LGs, wo sich eine Investition lohnt.

**Comment by Otto962** [comment]
Danke Andrgin, ich hatte es vermutet, daß das nur manuell geht. Da sehr wenige Spieler überhaupt ein VIRGO haben, ist das sehr mühsam. Hab nur 7 von den TOP100 Mitspielern gefunden.

**Comment by dsiekiera** [comment]
Auf welcher Welt bist du denn?
