### ISSUE TITLE
Kein Vorschlag zum Snipen bei letztem FP eines LG

### ISSUE THREAD

**Issue by geepy** [dsiekiera/foe-helfer-extension#662]
Die FoE Etikette verbietet es, als Förderer ein LG zu leveln. Das soll der Erbauer tun, wenn er es am sinnvollsten findet (meist direkt nach dem Ernte einsammeln).
Daher sollte das AddOn LGs, die nur noch einen Punkt vom Leveln entfernt sind, auch nicht mehr im Kostenrechner in der Liste "Mögliche Einzahlungen" anbieten.

**Comment by andrgin** [comment]
Es wird beim Öffnen des LGs extra gelb und mit Tooltip angezeigt, dass man das LG damit levelt. Ob man das nun tut oder nicht musser jeder selbst für sich entscheiden. Das wird ganz vom Idealfall abhängen. Wenn es sich z.B. um einen Zeus oder eine Terrakotta handelt sehe ich keinen Grund, warum ich nicht leveln sollte, genauso wenig bei einem Nachbar, der mich täglich plündert.

**Comment by mordillo666** [comment]
Fände ich auch nicht so dolle. Die LGs sind ja entsprechend farblich markiert.
Ich zB frage dann auch schon mal beim Besitzer nach, ob ich leveln darf, um den Platz zu belegen.
