### ISSUE TITLE
Vorschlag / Idee / Wunsch: Automatischer City Planner?

### ISSUE THREAD

**Issue by Chris1887x** [dsiekiera/foe-helfer-extension#663]
Moin,
wäre es möglich, die Daten der Aktuell stehenden Gebäude und Straßen auszulesen, der verfügtbare Platz um dann am ende ein Popup zu bekommen, wie man am effizientesten die Gebäude und Wege legen kann??

**Comment by Th3C0D3R** [comment]
Dazu müsste man eine KI entwickeln, die einige Dinge berücksichtigt, wie zb Gebäude setz zusammen zu bauen, 2x2 Straßen an dazugehörige gebäude zu setzten und alle Straßenabhängige Gebäude auch mit einer Straße zu versehen.
Das erfordert viel Rechenleistung und ist für eine kleine Extension eher sinnfrei.
Als eigenständiges Programm in welches man die Daten der Extension einliest wäre das schon eher was.
Bleibt trotzdem das "Problem" der KI (welches in meinen Augen das größte ist)

**Comment by Chris1887x** [comment]
Alles klar, danke für die Rückmeldung! :))

**Comment by ebuchanan** [comment]
What if a 3rd party server was set up to do the computation? Does the extension's city overview map have the necessary input data (building sizes, road requirements, adjacency requirements, city expansions, etc) to send as input?

If so, do you have a sample to work from?
