### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by SirArchie** [dsiekiera/foe-helfer-extension#664]
Eine Notizfunktion

**Comment by jiim92** [comment]
Ja, bitte unbedingt implementieren. Würde mir gerne notieren, welcher Mitspieler eine zu starke Verteidigung hat!

**Comment by SirSolero** [comment]
fände auch genial, ein ganz simpler text-editor mi speicherfunktion würde imho schon reichen

**Comment by andrgin** [comment]
Mittlerweile vorhanden
