### ISSUE TITLE
Technologies: research costs should accumulate

### ISSUE THREAD

**Issue by wschaal** [dsiekiera/foe-helfer-extension#665]
When using the Technologies tool to calculate research costs for the next age, the remaining costs for the current age should be added to the totals. This would allow the user to more easily estimate how much of any particular goods will be needed overall in the game.

For example, I want to know when can I stop gathering Promethium. I have enough now but want enough for the next two ages (assuming newly released ages won't ask for more). Gathering too much justs wastes AO goods. [Yes, I can do the math but this was just an example.]

**Comment by Th3C0D3R** [comment]
Its already implemented 😉 it add all the costs together

**Comment by wschaal** [comment]
I see now that it was just a delay in the updating. Seems like I need to log out/in.
Thanks.
