### ISSUE TITLE
Fenster lassen sich in Firefox nicht verschieben

### ISSUE THREAD

**Issue by Marinaxs** [dsiekiera/foe-helfer-extension#666]
Plugin Fenster lassen sich in Firefox nicht verschieben

in Chrome schon, aber in chrome läuft foe derzeit nicht so gut

**Comment by andrgin** [comment]
Kannst du bitte die Bug Report Vorlage verwenden. (weches Betriebssystem, welche Firefox Version etc.)

**Comment by outoftheline** [comment]
Da es keine Rückmeldung mehr gab, mach ich hier zu
