### ISSUE TITLE
Idee/Wunsch Emotes

### ISSUE THREAD

**Issue by Tikx** [dsiekiera/foe-helfer-extension#669]
Hey,
ich würd mich über ein kleines Fenster mit einer Liste Emotes freuen, bei der evtl. ein eigener Bereich für favorisierte Emotes ist.

**Comment by dsiekiera** [comment]
Wie genau muss man das verstehen?
Wofür brauchst du die?

**Comment by Tikx** [comment]
Einfach eine Liste mit Emotes ähnlich wie es die Appspieler haben. Hät bloß gern mehr möglichkeiten mich auszudrücken :-) und fänds praktisch wenn das gleich im Helfer integriert wär anstatt, andere Dateien o.ä. offen zu haben in denen Emotes gespeichert sind. 
Würds mir so vorstellen dass man ein zweigeteiltes Fenster hat. In dem man im unteren Bereich  eine große auswahl an emotes evtl. sogar zwischen Android/Apple/Pc Emotes kategorisiert hat und dieses einklappbar ist. Im oberen Bereich wärn die Favoriten die man sich via Drag&Drop o.ä. von den unteren auswählen kann. So hätte man ein Fenster das man neben dem Chat offen hat und könnte sich ein Emote auswählen und dann mit strg+v im chat einfügen.

**Comment by Cycloth** [comment]
Unter Windows lässt sich mit der Tastenkombination Win + .   (Punkt) ein Emojimenü aufrufen 😉

**Comment by dsiekiera** [comment]
Das wusste ich noch gar nicht. Danke für den Tipp 👌

**Comment by Tikx** [comment]
Danke 😍👍
