### ISSUE TITLE
Daten auf Website übertragen

### ISSUE THREAD

**Issue by 1234Pick1234** [dsiekiera/foe-helfer-extension#67]
Hallo,

ich habe die Extension erst seit ein paar Minuten und mich auch schon auf der Website registriert. In-Game habe ich alle Häkchen gesetzt (außer das erste, denn wenn ich das mache, verschwindet meine Leiste und ich muss Chache usw. lösche, damit sie wieder da ist).

Was muss ich noch machen, damit ich die Daten auf der Website sehe?

Liebe Grüße und schönen Abend noch :)

**Comment by DasAtom** [comment]
Den ersten Haken setzen ;) wenn das nicht aktiviert ist wird die Extension niemals Daten übertragen, egal was du tust.

Das verschwinden der Leiste ist seltsam. Bleibt sie denn vorhanden sobald du einmal den Cache gelöscht hast?

**Comment by 1234Pick1234** [comment]
Hey, ich habe nochmal ein bisschen getestet.

Als erstes mal zur Website: wenn ich eingeloggt bin, sehe ich unter Mitglieder mich und bei punkten steht 7xx.xxx was viel zu wenig ist. Ist das eventuell der Stand einer meiner Nebenwelten?

Dann zum Tool: aktiviere ich den ersten Haken, passiert erstmal nichts. Ich gehe durch die Ereignisse und Gebäude usw. aber es wird nichts auf die Website übertragen. Reloade ich die Seite, ist das Tool weg.
Um das tool wiederzubekommen, reicht es NICHT den Cache zu leeren, habe ich getestet. Ich muss cookies mit löschen, dann kommt die Leiste wieder aber die Einstellungen sind weg.

Das ist so mein aktuelles Problem :( Ich erkenne leider nicht, was ich falsch mache.

Ich nutze übrigens ein MacBook Pro mit macOS auf dem neusten Stand.

**Comment by PXWaldy** [comment]
> 
> Als erstes mal zur Website: wenn ich eingeloggt bin, sehe ich unter Mitglieder mich und bei punkten steht 7xx.xxx was viel zu wenig ist. Ist das eventuell der Stand einer meiner Nebenwelten?
> 
Du hast aber schon den richtigen Server (Welt) oben rechts ausgewählt?

**Comment by 1234Pick1234** [comment]
> > Als erstes mal zur Website: wenn ich eingeloggt bin, sehe ich unter Mitglieder mich und bei punkten steht 7xx.xxx was viel zu wenig ist. Ist das eventuell der Stand einer meiner Nebenwelten?
> 
> Du hast aber schon den richtigen Server (Welt) oben rechts ausgewählt?

Ich kann da nichts auswählen, das sieht nämlich so aus:

<img width="72" alt="Bildschirmfoto 2019-07-22 um 19 27 31" src="https://user-images.githubusercontent.com/53126564/61651833-fcfd6100-acb6-11e9-8fbf-a2c6d02f6fd8.png">

**Comment by 1234Pick1234** [comment]
Gibt es keine Problemlösung dafür?

**Comment by Selene443Foe** [comment]
Guten Morgen :)
die Übertragung der Daten an die Webseite funktioniert bei mir in einer Welt korrekt. Das kleine Fensterchen unten geht auf, alles io. Wir schreiben heute KW33 - wird auch auf der Webseite so angezeigt.

In Mount Killmore erscheint das kleine Fensterchen nicht. Letzte Übertragung laut Webseite in KW32.

In beiden Welten stehen die Häkchen in den Einstellungen gleich.
Ich habe in Mount Killmore auch alle Häkchen zum Test mal entfernt - Reload - wieder gesetzt. Cache gelöscht. Keine Veränderung. Daten werden weiterhin nicht übertragen.
Version: 2.3.4

**Comment by dsiekiera** [comment]
Ist gefixt in der 2.3.12.2
