### ISSUE TITLE
More Guild statistic

### ISSUE THREAD

**Issue by tample17** [dsiekiera/foe-helfer-extension#670]
Hi!
It would be nice to see more Guild statistic, such as Treasury changes for a day\week\month

Or Guild members age, for example:
- Bronze Age - 0
- Iron Age - 5
- Early Middle Ages - 15
- High Middle Ages - 5
- Late Middle Ages - 5
- Colonial Age - 5
- Industrial Age - 2
- Progressive Era - 3
- Modern Era - 2
- Postmodern Era - 5
- Contemporary Era - 2
- Tomorrow Era - 7
- The Future - 10
- Arctic Future - 1
- Oceanic Future - 1
- Virtual Future - 5
- Space Age Mars - 3

And maybe some others, if anyone have more ideas.
Thanks!

**Comment by haroldpga** [comment]
I would love to see the ability to export the treasury report into an external, delimited file which I could then import into excel or some other program to produce my own reports.  Just give me the data and let me generate my own reports.

**Comment by scibuff** [comment]
that is fairly simple, I implemented exactly that (in my own chrome devtools plugin) and I'm going try to add it here (already forked just need to have a look at the code structure)

**Comment by dsiekiera** [comment]
I have already started with a function that can send data from the guild fund for statistics to foe-rechner.de.
Since we all have an RL, it doesn't happen that quickly. ;-)

**Comment by andrgin** [comment]
We have an export feature for the logs planned for next update.
