### ISSUE TITLE
Outpost | Egypts | Required loot

### ISSUE THREAD

**Issue by CJohannimloh93** [dsiekiera/foe-helfer-extension#672]
It would be great when the helper would display the required loot for the egypts.

For example:
20 cereal missing --.> 200 loot required

This way you can farm loot until you have enough for all productions

Best regards
Christopher

**Comment by Cory847** [comment]
Agree.  This would be helpful.  Just a total would be necessary.  Also note to remember 21 barley missing would require 250 loot since you have to produce in increments of 5.  This would also adapt to the other settlements as well.
