### ISSUE TITLE
co-payment calculator for Zeus is missing spot 5 for levels 40 and around

### ISSUE THREAD

**Issue by LeoDW8r** [dsiekiera/foe-helfer-extension#673]
Zeus is offering 5fp for 5th spot around level 40, but this spot is not reflected in de co-payment calculator.

**Comment by andrgin** [comment]
Do you have a screenshot?

**Comment by LeoDW8r** [comment]
Unfortunately not anymore, since my Zeus is now already on level 45, on the way to 46, and at rhis level the number 5 spot is correctly displayed.
I'll ask some of my guild-members if they have a Zeus around level 40.
Thanks for your quick reply!

**Comment by LeoDW8r** [comment]
![DvA43](https://user-images.githubusercontent.com/62558306/77843872-98799680-71a1-11ea-8f17-d8154f52b5c7.jpg)
Aachner Dom seems to have the same issue between levels 40 and 45, so I made a screenshot.

**Comment by andrgin** [comment]
The problem is that you have paid 10 FP too much yourself.
There are only 29 FP left. P4 will pay these 29 FP and level the great building, so nobody can get P5 any more.
