### ISSUE TITLE
Moppelaktivitäten werden nicht richtig zugeordnet

### ISSUE THREAD

**Issue by psonline66** [dsiekiera/foe-helfer-extension#675]
Die Erfassung der Moppelaktivitäten ist nicht korrekt. Es werden Freunde als Nachbarn zugeordnet, auch die Zählung der Moppelungen funktioniert wieder nicht richtig. 
Mir ist aufgefallen, dass die Übertragung der Ereignisse manchmal mehrere Minuten dauert.

**Comment by psonline66** [comment]
Die Übertragung flutscht wieder, allerdings wurden wieder Spieler gefunden, an Tagen an denen ich garantiert alles übertragen hatte. Jetzt wollte ich überprüfen, ob die Aktivitäten passen, komme aber auf FOE-Rechner nicht ins Menü

**Comment by marcomo09** [comment]
Bei der Moppelübersicht werden jetzt keine Namen mehr angezeigt sondern nur Plätze.

**Comment by psonline66** [comment]
Es scheint jetzt so, dass alle Spieler übertragen werden. Allerdings nicht richtig, habe z.B. einen Spieler den ich aus der Nachbarschaft in die FL hinzugefügt. Er moppelt 6-7x die Woche. In der FL-Übersicht wird er mit 0 angezeigt.

**Comment by psonline66** [comment]
Kleine Frage: Lohnt es sich derzeit im Rathaus die Aktivitäten durchzuklicken?

**Comment by psonline66** [comment]
Tut sich hier noch etwas oder erst in ferner Zukunft?

**Comment by outoftheline** [comment]
Die Funktion ist nicht mehr auf der Website verfügbar.
