### ISSUE TITLE
Eigenanteilsrechner nio wenn gelöschter Spieler enthalten Nr.2 (Nr.1 = #57)

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#68]
Guten Abend :)
kann ich diesen Bug nocheinmal öffnen?

Der Fehler ist noch nicht ganz behoben.

Enthält das LB einen gelöschten Spieler funktioniert der Rechner nach wie vor nicht.
Was sich verändert hat ist das Wechseln in ein anderes LB. Das ging vorher nicht. Jetzt funktioniert es.
Allerdings geht wiederum das Schließen nicht.

Würdest du hiernach nochmal schauen?
Vielen Dank

![5](https://user-images.githubusercontent.com/50969949/61595511-69655b00-abf8-11e9-8933-a0298cf4163f.GIF)

**Comment by dsiekiera** [comment]
Das ist immer tricky. Ich hab schon längere Zeit kein LG mehr mit einem gelöschten User gesehen. Sobald ich eines finde, kann nich mir das sofort anschauen.
So weiß ich leider nicht was für Werte "reinkommen".

**Comment by Selene443Foe** [comment]
Schade, hätte dir gern das LG genannt. Ist auf Korch. Wurde aber fremd gelevelt... :(

**Comment by Selene443Foe** [comment]
Ich hätte ein LG mit gelöschtem Spieler auf Greifental! Kannst du dort zugreifen? Dann schicke ich dir den Spielernamen per PN!?

Auch hat der Spieler noch ein Problem. Das Tool funktioniert in zwei Welten problemlos. Nur in Greifental funktioniert Kostenrechner und Eigenanteilsrechner nicht. Und das unabhänig von dem LG mit dem gelöschten Spieler.

Cache löschen, Version aktualisieren, Tool löschen und neu installieren = alles durchprobiert.
Der Fehler besteht weiterhin - und das ausschließlich nur in Greifental...

**Comment by Selene443Foe** [comment]
ach fast vergessen... die Button für Eigenanteilsrechner und Kostenrechner sind sogar grün. Bei klick drauf öffnet sich aber beides nicht...
