### ISSUE TITLE
FoE Helper is transmiting data, why and where?

### ISSUE THREAD

**Issue by kronikpillow** [dsiekiera/foe-helfer-extension#681]
I have to say that I have a serious issue with FoE helper transmitting data from my game to a unknown location, where can this data be seen? for example, I noticed that when I open my sniped GB list, data gets transmitted, am I sharing my snipe targets with the entire world by using FoE Helper? and if so why? and where can I see this data?/

I also noticed you started recording attacks and looting, why? so that when Inno decided to start banning players for using a cheat like the Plunder Helper that all of us would get banned? I seriously don't understand ...

Plunder Helper is a heavy cheat, negotiation helper is a bot, and the rest is so and so okay and not bankable, but those 2 functions Inno can easily decide to start banning people over it.. but that's not my topic here .. I have checked your websites, there is no page where we can view the data we are transmitting, so whats the actual purpose of it? also who guarantees me that you do not have my password since your transmitting data and basically spying on us?

**Comment by dsiekiera** [comment]
> I have to say that I have a serious issue with FoE helper transmitting data from my game to a unknown location, 

What do you think where it will be sent to? Google, Facebook or even Inno?
Of course only at foe-rechner.de. You have also granted the authorizations for this and only this.


> ... where can this data be seen? for example, I noticed that when I open my sniped GB list, data gets transmitted, 

This is an activated option in the settings to convert your investments into net. There you can also check whether further payments have been made to this LG. ==> https://foe-rechner.de/invest/gbs (after logging into your account)

> ... am I sharing my snipe targets with the entire world by using FoE Helper? and if so why? and where can I see this data?

Of course not. How do you come up with something like that?

> I also noticed you started recording attacks and looting, why? 

Wtf?! What makes you think that??!

> ... so that when Inno decided to start banning players for using a cheat like the Plunder Helper that all of us would get banned? I seriously don't understand ...

Äh, no .. ?!

> Plunder Helper is a heavy cheat, 

Why? This data is available in your browser all the time. We only represent them.

> ... negotiation helper is a bot, 

You don't know what a bot is. A bot automatically performs actions. He either fills something out for you or clicks something for you. Does the FoE helper do something like this?

> ... and the rest is so and so okay and not bankable, but those 2 functions Inno can easily decide to start banning people over it.. 

No way. No idea how players like you come up with ideas like this? Have you ever spoken to Inno or have you read the Inno rules?

> but that's not my topic here .. I have checked your websites, there is no page where we can view the data we are transmitting, 

But! Naturally. Register on foe-rechner.de and have a look.

> so whats the actual purpose of it? also who guarantees me that you do not have my password since your transmitting data and basically spying on us?

Oh my God. I can't think of anything more ...

Summary: Please uninstall the helper immediately or ask guild friends who will be happy to explain the functions to you.

The helper is a project by players for players. Take off the aluminum hat and be happy that you can use such a great help.

Check out these posts in the Inno forum. There, a community manager commented on this: https://forum.de.forgeofempires.com/index.php?threads/tool-erlaubt.33170/
Use Google Translate to understand the content.

Regards,
Daniel (Founder & Leader)

**Comment by kronikpillow** [comment]
> ... am I sharing my snipe targets with the entire world by using FoE Helper? and if so why? and where can I see this data?
> Of course not. How do you come up with something like that?
em maybe because there is no description of what its actual purpose is?

> I also noticed you started recording attacks and looting, why?
> Wtf?! What makes you think that??!
em, your latest update announcement genius, or maybe your English translations are so bad that you don't even realize what your writing, are you using google translate in your update announcements cuz it sure looks like it?

> Plunder Helper is a heavy cheat,
> Why? This data is available in your browser all the time. We only represent them.
Em, the plunder data even thou it is there for everyone to "see" it is not accessible to an ordinary player, the fact that you can inspect an HTML5 game with developer tools doesn't mean that anyone will actually bother to do it when attacking and plundering players, why is it a heavy cheat? because you can actually open a players city before even attacking him and see if his collection is ready and if there is anything to plunder at all, it gives a huge advantage to PC players with the extension over PC players without the extension and especially a huge advantage over a mobile player, hence it's a cheat, the fact that you are using "the data is available there in your browser for all to see" as an excuse doesn't change the fact that no one reads that data or bothers to read the data manually and doesn't change the fact that it's a cheat  

> ... and the rest is so and so okay and not bankable, but those 2 functions Inno can easily decide to start banning people over it..
> No way. No idea how players like you come up with ideas like this? Have you ever spoken to Inno or have you read the Inno rules?
Yes, I have actually spoken to Inno many times as a matter of fact, but wtf would you know about it?
and yes I have read the rules of Inno detailed as I have actually been many times banned for violation of rules, and even had a permanent ban that I managed to lift as the reason for my permaban wasn't even in the game rules. How do we get ideas like this? maybe because on the Inno forums across various communities, 1 community manager says its an allowed extension, and another community manager says its a forbidden extension and that all users using it will get banned :)

> Summary: Please uninstall the helper immediately or ask guild friends who will be happy to explain the functions to you.
wow, from a founder & leader of an extension to have such rudeness it's unbelievable honestly, when a player approaches you with concerns or a user of your projects that your developing, do you treat them like this as well? I suggest you tone down your ego, cuz you just won the lottery in being the asshole of the year

**Comment by dsiekiera** [comment]
Your appearance is the last.

You come to the Github and denounce a free extension that is programmed by players who love this game in their free time. And blame it as a bot, sniffing program and cheat tool.

How incredibly ungrateful you are.

Instead of writing an email to find out how the extension works, you try to pull the extension straight into the dirt. You have no decency and zero respect for the work of others.

Uninstall this extension and go far away !!

If you have learned to ask politely and do not immediately accuse even though you have no idea about everything, write me an email.
