### ISSUE TITLE
falsche Grafik für "Aufklapp-Pfeil" links oben bei Eigenanteilsrechner

### ISSUE THREAD

**Issue by gneiss15** [dsiekiera/foe-helfer-extension#682]
Gerade wurde bei mir Version 2.4.3 installiert.
Jetzt wird da (siehe Betreff) offensichtlich eine falsche Grafik verwandt.
In der vorherigen Version war das noch OK (wenn auch ungeöhnlich den Ausklapp-Pfeil ausserhalb des eigentlichen Fenster zu platzieren)
![image](https://user-images.githubusercontent.com/36615981/77513086-97302d00-6e74-11ea-8795-3521b146d48d.png)

**Comment by dsiekiera** [comment]
Verdammt. Ich hatte in der Tat gesehen das Inno Grafiken ausgewechselt hat, aber den hab ich glatt vergessen.
Das hole ich schnellst möglich nach.

**Comment by gneiss15** [comment]
Super schnelle Reaktion (Daumen hoch)

**Comment by dsiekiera** [comment]
Ist gefixt:

![Bildschirmfoto 2020-03-25 um 09-35-44](https://user-images.githubusercontent.com/834814/77517217-08bfa980-6e7c-11ea-8666-d908a4c5481d.png)

Kommt im nächsten Update.
