### ISSUE TITLE
Werbenachricht für LG Investition in Zwischenablage

### ISSUE THREAD

**Issue by mrok-gmx-de** [dsiekiera/foe-helfer-extension#684]
Bei den eigenen LGs bzw. dem Eigenanteilrechner wäre eine konfigurierbare Erstellfunktion für die Werbenachricht hilfreich.
Ein Beispiel findet sich hier: https://foe.tools/de/gb-investment/Observatory/

**Comment by dsiekiera** [comment]
Was genau fehlt den noch? Wir sind nämlich der Meinung das die wichtigsten Daten enthalten sind.

![Bildschirmfoto 2020-03-26 um 16-49-21](https://user-images.githubusercontent.com/834814/77666870-c84a5380-6f81-11ea-8957-4ee3f1e71625.png)

**Comment by mrok-gmx-de** [comment]
Vielen Dank für die schnelle Antwort. Das stimmt natürlich, so
      habe ich mir das vorgestellt. 
    
    Voraussetzung ist jedoch, dass man den Punkt überhaupt findet.
      Nach eurer Antwort habe ich das geschafft, 
      was allerdings nicht ganz einfach war.
    
    Ich nehme an, dass das zerbröselte Icon ein Bug ist, oder?
    
    
    Am 26.03.2020 um 16:49 schrieb Daniel Siekiera:
    
      
      Was genau fehlt den noch? Wir sind nämlich der Meinung das die
        wichtigsten Daten enthalten sind.
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/dsiekiera/foe-helfer-extension/issues/684#issuecomment-604508742",

"url": "https://github.com/dsiekiera/foe-helfer-extension/issues/684#issuecomment-604508742",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by dsiekiera** [comment]
Jap und ist auch schon behoben ==> #682 

Ich würde dir jetzt einen Link zu einer Doc Seite senden, aber leider ist derzeit unser Server down für einen größeren Umzug. Dort stteht das noch mal drin.

**Comment by mrok-gmx-de** [comment]
Super, danke. Hab gerade den gestrigen Bug gesehen. Muss ich eben übersehen haben, sorry.
