### ISSUE TITLE
Neighbour steal database

### ISSUE THREAD

**Issue by Franciko** [dsiekiera/foe-helfer-extension#686]
I would like to suggest you a new menu, where we can find reggisted what time we individually steal something to a neighbor and what building.

**Comment by scibuff** [comment]
So basically, the last plunder date&time, building, and what was taken. Ideally, also the battle result = what units I used, how many I lost (if any), what units the opponent used for defense etc.

**Comment by Franciko** [comment]
That would be perfect.

**Comment by belikoviv** [comment]
Neigbour name, last attack date/time, successfull or not, my army (and my losts, if any), opponent army (and losts, if any), date/time of plunder, building, and what was taken (or mark that nothing was taken). And history database for armies and plundered buildings for all neigbours.

I'm writing most of this in google docs right now :)

**Comment by osv** [comment]
plus attack/defend bonuses of armies :)

I'm also interesting in it, and start working for myself, I want to use indexdb as storage because history maybe huge after some time

**Comment by osv** [comment]
Work in progress... will create PR after some cleaning tomorrow

![plunder](https://user-images.githubusercontent.com/213405/78512530-00396e00-77ae-11ea-9155-e4780b6eaa53.png)

**Comment by scibuff** [comment]
Sweet

**Comment by dsiekiera** [comment]
We added this nice modul and publish an update as soon as possible.
