### ISSUE TITLE
Beta-Server: Neues Zeitalter SA:AB ist da; von der Extension nicht erkannt

### ISSUE THREAD

**Issue by Andi47** [dsiekiera/foe-helfer-extension#688]
am Betaserver wurde gestern das neue Zeitalter Space Age: Asteroid Belt freigeschaltet.
Ich habe nun am Betaserver die erste Tech des neuen Zeitalters erforscht und dann in der Extension den Button “Technologien” zum Berechnen der Kosten geklickt. Im Fenster, das sich nun öffnet, wird das Zeitalter nicht erkannt (“Eras.NaN” bzw “Eras.Unknown”), und somit keine Kosten für das neue Zeitalter berechnet.

Link zum Thread im Forum: https://forum.foe-rechner.de/d/225-beta-server-neues-zeitalter-saab-ist-da-von-der-extension-nicht-erkannt/2

**Comment by andrgin** [comment]
Wird mit der nächsten Version gefixed.
