### ISSUE TITLE
Tool selection are is higher in z order than the popup showing additional bonuses enabled by Arc

### ISSUE THREAD

**Issue by coderwolf2015** [dsiekiera/foe-helfer-extension#689]
the tool selection window appears over(or on top of) the Arc bonuses shows by hovering over the rewards area on a Great Building screen.

**Comment by andrgin** [comment]
Can you please use the bug report template and include a screenshot.

**Comment by coderwolf2015** [comment]
Betriebssystem / Operating System:  Windows 10 64 Bit
Verwendeter Browser inkl. Versionsnummer / Used Browser including version:  Chrome Version 80.0.3987.163 (Official Build) (64-bit)
Forge of Empires Server :  us18/sinernia
Extension Version und Sprache der Extension. Falls ihr Betatester seid unbedingt dazuschreiben!!! / : FoeHelper 2.4.4 /at least Previous 2 released versions also
Extension version and language of the extension. If you are beta tester include that as well!!!
Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole" wechseln) / Errors in the console (press F12 and switch to console tab) : I dont think there is any console errors showing in relation to this issue. 


![2020-04-23 13_50_41-Window](https://user-images.githubusercontent.com/13156002/80133753-b43b4700-856b-11ea-9a4a-2a1cc03f05f3.png)

**Comment by andrgin** [comment]
All extension content is drawn above ingame content. There is no way of changing that.

Unfortunately we have no control over where Inno opens their tooltips. This seems this depends on resolution and zoom factor. If you change zoom factor one step further in our out you should be able to avoid the problem.
