### ISSUE TITLE
Seitenleiste verschwindet

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#69]
Guten Abend,

ein Spieler berichtete mir vor ein paar Tagen das die Seitenleiste immer wieder verschwindet.
Nach einigen Versuchen und rumprobieren sind wir nun zu folgendem Ergebnis gekommen:

Werden in den Einstellungen alle Haken gesetzt, verschwindet die Seitenleiste nach reload.
Nimmt man den ersten Haken (Datenübertragung an die Webseite) raus und lässt alle anderen drin - dann bleibt die Seitenleiste. 

Können wir was von unserer Seite aus machen?

**Comment by dsiekiera** [comment]
Hab ich von anderer Seite auch gehört, schaue ich mir asap an.

**Comment by MrMattn** [comment]
verschwindet nur die Seitenleiste oder geht das tool nicht mehr?
Ich nutze ja OSX (also Macbook) und muss täglich mehrfach den cache löschen damit die Leiste wieder kommt.
ich habe alle Haken gesetzt

**Comment by Selene443Foe** [comment]
Wenn die Seitenleiste verschwindet, dann kannst du das Tool ja nicht benutzen. Es fehlen ja dann die Button um irgendetwas einzuschalten.

**Comment by MrMattn** [comment]
das ist so nicht ganz richtig.
ich lade das spiel und es kommt keine Leiste.
das tool geht aber in sofern, dass beim Besuch der Nachbarn ein Fenster erscheint, allerdings mit "undefinied"
siehe screenshot
https://www.bilder-upload.eu/bild-e13820-1564259720.png.html

**Comment by dsiekiera** [comment]
Ich kann diesen Fehler in keinster Weise nachvollziehen oder nachstellen. 
Besteht das Problem immer noch?

**Comment by Selene443Foe** [comment]
Bisher gibt es von meinen Leuten hierzu keine weiteren Meldungen...

**Comment by dsiekiera** [comment]
Fehler sollte verschwunden sein.
