### ISSUE TITLE
Anzeige der Investitionen (Webseite)

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#7]
Auf der Webseite wir die tolle Anzeige der getätigten Investitionen so angezeigt:

![image](https://user-images.githubusercontent.com/50969949/58291631-64358c80-7dbe-11e9-8b22-c0b0a790f3ca.png)

**Comment by dsiekiera** [comment]
Hast Du schon mal die Investitionen vom Game aus übertragen lassen?

**Comment by Lashandan** [comment]
Nach dem "Klick" aufs Rathaus, wechsel ich in den Reiter "Neuigkeiten" danach auf "Legendäre Bauwerke" - danach sendet die Extension die Investitionen an das Profil auf foe-rechner.de
![image](https://user-images.githubusercontent.com/20851108/58324228-924eb700-7e26-11e9-9ff1-e7476946e471.png)

Danach habe ich auf der Webseite folgende Übersicht:
![image](https://user-images.githubusercontent.com/20851108/58324249-a2ff2d00-7e26-11e9-83c9-86e0f1e62e5f.png)

**Comment by Selene443Foe** [comment]
ohjeee... jaja na klar. jetzt passt es. *anstirnklatsch
Vielen Dank Euch :)
