### ISSUE TITLE
Kostenrechner lässt sich nicht verschieben

### ISSUE THREAD

**Issue by PXWaldy** [dsiekiera/foe-helfer-extension#70]
Der Kostenrechner lässt sich bei mir nicht mehr verschieben. Er hängt im Oberen Bildschirmrand fest. 

Der obere Teil des Rechners, den man anfassen kann um ihn zu verschieben ist unter die URL Eingabe gerutscht und lässt sich nicht mehr verschieben.

Bildschirmauflösung, Zoom im Browser, Browser auf und zu gemacht, Erweiterung gelöscht und neu Installiert, alles versucht, leider ohne Erfolg.

Hat jemand eine Idee??

**Comment by PXWaldy** [comment]
Problem Gelöst!

**Comment by dsiekiera** [comment]
Hm, ok. Hier wäre auch eine Lösung gewesen:
[Position Fixen](https://forum.foe-rechner.de/chrome-extension/fenster-laesst-sich-nicht-mehr-verschieben)
