### ISSUE TITLE
Menueleiste leer nach Update

### ISSUE THREAD

**Issue by Barbar65** [dsiekiera/foe-helfer-extension#709]
Nach dem heutigen update ist meine Menueleiste bzw. ohne Funktion und im Protokoll erscheint eine Fehlermeldung über eine Datei, die nicht geöffnet werden kann

**Comment by dsiekiera** [comment]
Es kam ein neues Modul dazu. Warscheinlich musste den Browser neu starten oder die Extension in der  Extenstion-Übersicht "Reloaden"

![Bildschirmfoto 2020-04-01 um 13-14-49](https://user-images.githubusercontent.com/834814/78131119-d03f4300-741a-11ea-806a-a170fa5530fd.png)

**Comment by MasterYinan** [comment]
Bei mir ist das Menü an der rechten Seite ebenfalls leer und auch teilweise kaputt (der "nach unten" button ist nicht mit der restlichen Menü-Box verbunden).
Ein "Reload"-Button existiert bei mir nicht bei der Extension-Ansicht in Chrome.

**Comment by TobiHH** [comment]
Ich habe ebenfalls keinen Reload Button. Die Chrome Console gibt folgendes aus:
`_main.js?v=2.4.3.1:427 TypeError: Cannot read property 'status' of undefined
    at Object.GetSetting (settings.js?v=2.4.3.1:224)
    at Object.api_Btn (_menu.js?v=2.4.3.1:818)
    at Object.ListLinks (_menu.js?v=2.4.3.1:200)
    at HTMLDocument.<anonymous> (_menu.js?v=2.4.3.1:71)
    at i (merged-3rd-party-a32c16de.js:2)
    at Object.add [as done] (merged-3rd-party-a32c16de.js:2)
    at n.fn.init.n.fn.ready (merged-3rd-party-a32c16de.js:2)
    at Object.BuildOverlayMenu (_menu.js?v=2.4.3.1:68)
    at _main.js?v=2.4.3.1:1014
    at _proxyAction (_main.js?v=2.4.3.1:425)`

Das ist der Quelltext dazu;
`	/**
	 * Gibt den Status aus dem localStorage oder den Settings zurück
	 *
	 * @param name
	 * @returns {any}
	 */
	GetSetting: (name)=> {
		let s = localStorage.getItem(name);

		if(s !== null){
			return JSON.parse(s);
		} else {
			return Settings.Preferences[name]['status'];
		}
	},`

**Comment by dsiekiera** [comment]
Fehler gefunden. Ich hab eine Variable im Storage die euch fehlt. Daher sehe ich den Fehler nicht.

Bugfix ist unterwegs,

**Comment by Julian2424** [comment]
Wann kommt das Update, das der Fehler behoben ist? Die rechte Seite ist so leer und einsam, ^^

**Comment by Barbar65** [comment]
Habe alles versucht, Neustart, Reload etc. Kein positives Ergebnis...

Am Mi., 1. Apr. 2020 um 13:15 Uhr schrieb Daniel Siekiera <
notifications@github.com>:

**Comment by dsiekiera** [comment]
Firefox schaltet Updates immer sofort frei. Dort geht auch alles wieder.
Chrome bummelt immer

**Comment by Barbar65** [comment]
Danke, Löschen und Neuinstallation hat geholfen

Am Mi., 1. Apr. 2020 um 13:44 Uhr schrieb Daniel Siekiera <
notifications@github.com>:
