### ISSUE TITLE
Wunsch: FP-Investitions - Anzeige

### ISSUE THREAD

**Issue by xLasa** [dsiekiera/foe-helfer-extension#71]
Mein Vorschlag wäre es neben dem FP-Inventar auch anzuzeigen, wie viel FP man gerade im Umlauf hat. Entweder mit dem evtl. Gewinn bzw. Verlust, den man bei aktueller Platzbelegung machen würde mitberechnet oder starr alle FP die momentan unterwegs sind zusammen gerechnet, ohne evtl. Gewinn oder Verlust zu beachten. Ersteres wäre natürlich schöner. Ich vermute, dass man dafür zumindest in die Legendäre Bauwerke Liste klicken muss im Rathaus. Fände ich persönlich aber sehr nett. 

Falls ihr Interesse, Zeit und Lust habt, würd ich mich und vielleicht auch andere drüber freuen.
LG,
Lasa

**Comment by DasAtom** [comment]
Wenn du die Daten auf die Website übertragen lässt kannst du den Haken bei Fp-Investitionen rein machen. Wenn du dann im Rathhaus auf die LGs klickst kannst du hinterher auf der Website genau das sehen.

**Comment by xLasa** [comment]
Das mag gut sein, ich würds aber sehr gerne ingame sehen können. So wie ich das FP-Inventar sehen kann oben in der Leiste zum Beispiel. Aber wie gesagt nur, wenn sie Interesse, Zeit und Lust dran haben.

**Comment by dsiekiera** [comment]
Das muss ich mir anschauen. Prios liegen aber derzeit noch ein bissel wo anders 😉

**Comment by xLasa** [comment]
Keinen Stress. Wie gesagt nur eine Idee/Wunsch. Nichts dringendes.

**Comment by SkateScout** [comment]
Noch einen Vorschlag es gibt oft alte Leichen mit 1FP
Wie wäre es wenn man Anzeigt "Aktueller Gewinn (SAFE)" d.h. Summe der Plätze wo man > 1/2 Offen belegt hat mal Aktuellen Arche Faktor.

**Comment by andrgin** [comment]
Mittlerweile implementiert
