### ISSUE TITLE
Zugriff auf undefinierte Preferences "CustomerAPI"

### ISSUE THREAD

**Issue by mdittrich-ela-soft** [dsiekiera/foe-helfer-extension#713]
Der Zugriff auf die undefinierten Einstellungen "CustomerAPI" in der aktuellen Version 2.4.3.1 führen zu einen Fehler (Console) der vermutlich den Aufbau der Sidebar verhindert.

https://github.com/dsiekiera/foe-helfer-extension/blob/b6eb90fe27e425c046a2c106cc6c192e9f46513b/js/web/_menu/js/_menu.js#L818

**Comment by dsiekiera** [comment]
Ist bereits behoben #710
