### ISSUE TITLE
FOE Helfer ist das Menü leer

### ISSUE THREAD

**Issue by dirk-der-ripper** [dsiekiera/foe-helfer-extension#714]
Es gab ein neues Update,
jetzt erscheint das Menü vom FOE Helfer aber es ist leer, keine Icons.
( Windows 10/Google Chrome Browser)

**Comment by dsiekiera** [comment]
Welche Version hast du?

**Comment by dirk-der-ripper** [comment]
Version
2.4.3.1

**Comment by dsiekiera** [comment]
Das ist die alte. Aktuell haben wir die 2.4.3.2

**Comment by dsiekiera** [comment]
@dirk-der-ripper die ist auch veröffentlicht.

**Comment by dirk-der-ripper** [comment]
ok diese version hat sich automatisch bei mir installiert vor ein paar minuten... 
Ich deinstalliere mal und lade die aktuelle von chrome herunter
