### ISSUE TITLE
Chrome browser -Menu is blank

### ISSUE THREAD

**Issue by PaulH111** [dsiekiera/foe-helfer-extension#715]
Appeared after latest download and is NOT fixed.   Worls fine in Firefox, but not Chrome
[screenshot.pdf](https://github.com/dsiekiera/foe-helfer-extension/files/4414935/screenshot.pdf)

**Comment by Callisto649** [comment]
after install new version of this day

**Comment by Callisto649** [comment]
> 
> 
> after install new version of this day

OK with 2.4.3.2 :)) TY

**Comment by courseofra** [comment]
Same in Firefox 74.0 (64-Bit) as in Chrome Version 80.0.3987.162 (Offizieller Build) (64-Bit)
![image](https://user-images.githubusercontent.com/38578716/78154882-10172200-743d-11ea-95f5-60ecdbe6b681.png)

By the way: Thanks for your great work in the last months!

**Comment by PaulH111** [comment]
Looking forward to update....though is a strange fault as works fine on my Firefox (asame version as above)

**Comment by courseofra** [comment]
Thx for fast bugfixing!
