### ISSUE TITLE
Negotiation bug

### ISSUE THREAD

**Issue by jjgomera** [dsiekiera/foe-helfer-extension#717]
![bug foehelper](https://user-images.githubusercontent.com/1710547/78153841-caa62500-743b-11ea-9b26-68a931064a7b.png)

The image is clear, the extension dismiss the brea finding in first turn and forget in other turns

**Comment by andrgin** [comment]
That is intended behaviour. There are 2 rounds left and still 2 goods per person so chance of solving is at 100% so the tools decides to use the cheaper goods first.

**Comment by jjgomera** [comment]
thanks, solved
