### ISSUE TITLE
Betaserver: Neues Zeitalter SA:AB - Forschungskostenrechner erkennt Asteroid Ice nicht

### ISSUE THREAD

**Issue by Andi47** [dsiekiera/foe-helfer-extension#718]
Zuerst ein Lob - es ging überraschend schnell, dass das neue Zeitalter SA:AB jetzt von der Extension erkannt wird - danke!!

Aber es gibt einen kleinen Schönheitsfehler: Die Extension zeigt nicht an, wie viel Asteroideneis für die Erforschung des Asteroidenzeitalters benötigt wird.

**Comment by andrgin** [comment]
Stimmt das habe ich noch nicht hinzugefügt

**Comment by andrgin** [comment]
Wird gefixed
