### ISSUE TITLE
Eigenanteilsrechner mit unterschiedlichen Angaben?

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#72]
Guten Morgen :)

Ich hab eine Spielermeldung über eine seltsame Berechnung beim Relikttempel bekommen.
Schau dir doch bitte mal die Angaben zu den Eigenanteilen der drei Rechner an:

![8](https://user-images.githubusercontent.com/50969949/61993525-3d6d2e00-b06d-11e9-9b54-bfa1759376bd.gif)

**Comment by Selene443Foe** [comment]
ich hab noch so einen:

![11](https://user-images.githubusercontent.com/50969949/62081273-90540a80-b252-11e9-8f5f-c153c74b766f.png)

Mäzen und Eigenanteil zusammen ergibt 1273
Als Gesamt FP werden 200 weniger angegeben..
:D

**Comment by dsiekiera** [comment]
Ich habe im Crawler der Webseite ein paar anpassungen gemacht, damit die "Grundwerte" korrekt gezogen werden. Das sollte nun bei vielen LGs besser laufen.
