### ISSUE TITLE
Ability to re-order the icons

### ISSUE THREAD

**Issue by RealTracat** [dsiekiera/foe-helfer-extension#722]
The new building-kits feature is nice, but not one i will use very often. However it is now at the top of the toolbar.
It would be nice if we could re-order the icons so we can have all our most used ones together.
Not sure if this is possible but can't hurt to ask!

**Comment by andrgin** [comment]
You can order the icon by drag and drop.

New icons that have not been availbale in the previous version are always inserted on top so they are noticed by the players.
