### ISSUE TITLE
Anzeige Außenposten

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#73]
Guten Abend :)
Ich habe wieder Spielermeldungen zum Außenposten.
Version 2.3.2
Die Anzeige ist unterschiedlich nio.

Hier fehlt die komplette Bezeichnung:
![1](https://user-images.githubusercontent.com/50969949/61997703-0bc48900-b0a6-11e9-85d7-81f2cc2ccb4d.png)

Hier fehlt die Anzeige für Wolle:
![2](https://user-images.githubusercontent.com/50969949/61997705-1ed75900-b0a6-11e9-8ab1-97a6431f64e3.png)

**Comment by dsiekiera** [comment]
Wenn die Namen Fehlen reicht normalerweise ein einfaches F5. Das passierte am Anfang sogar mal bei mir.

Wenn eines fehlt hab ich schon einen Verdacht. Das ist ein kleiner Bug.

**Comment by Selene443Foe** [comment]
Was tun wenn F5, wie in diesem Fall, nicht hilft?
Die Anzeige klappt garnicht auf:

![9](https://user-images.githubusercontent.com/50969949/62006578-a2468800-b142-11e9-8809-43c4e19e0302.png)

**Comment by Selene443Foe** [comment]
Guten Morgen :)

Die Außenpostenanzeige klappt nach dem Update noch nicht ganz korrekt.

So sollte es aussehen:
![16 1](https://user-images.githubusercontent.com/50969949/63081155-31291200-bf43-11e9-9a56-21f25e6abec1.png)

so sieht es (auf Korch) aus:
![16](https://user-images.githubusercontent.com/50969949/63081157-31291200-bf43-11e9-86c3-8a88cc9f508c.png)

**Comment by dsiekiera** [comment]
Hey Selene,

gib bitte mal in die Konsole des Browser `Outposts.Order` ein. Dort müssten die jeweiligen 5 Güter dargestellt werden:

![Bildschirmfoto 2019-08-15 um 20-01-17](https://user-images.githubusercontent.com/834814/63115520-a0c8ec80-bf97-11e9-8adb-3a5dc5148845.png)

**Comment by Selene443Foe** [comment]
Ok. das sieht so aus:
in der einen Welt lässt sich nichts aufklappen :(

![19 1](https://user-images.githubusercontent.com/50969949/63127547-f068e180-bfb2-11e9-8fdf-433b886166be.png)
![19](https://user-images.githubusercontent.com/50969949/63127548-f068e180-bfb2-11e9-9bbe-eb1a8dd9bb27.png)

**Comment by Selene443Foe** [comment]
Guten Abend :)
Vor und nach neuem Update (2.3.6.1) fehlt bei einem Spieler in 3 von 3 Welten die Anzeige des Außenposten. 
Betätigt man den kleinen Pfeil bewegt der sich nur hin und her - es geht aber nichts auf.

![26](https://user-images.githubusercontent.com/50969949/64738369-4caa1d00-d4ef-11e9-9ab1-4b23b728a162.png)

**Comment by dsiekiera** [comment]
Gefixt in 2.3.7
