### ISSUE TITLE
Registrieren nicht möglich

### ISSUE THREAD

**Issue by biber123** [dsiekiera/foe-helfer-extension#734]
Hallo. habe die ID , meine Email und ein Passwort erstellt. Leider kommt immer die Fehlermeldung: 

Ooops...
Zu diesem Namen konnte ich nichts finden.

Hast Du ihn richtig geschrieben?
Beachte bitte Groß-/Kleinschreibung.
Bist du schon mit der Extension im Spiel unterwegs gewesen?

habe meine ID 10 mal kontrolliert.

**Comment by ljettinger** [comment]
i know of 2 others having this same problem...

**Comment by Maverick2805** [comment]
same here

**Comment by dsiekiera** [comment]
I fixed it some minutes ago. Pls try again to register.

Thanks for waiting, but unfortunately I only have the opportunity to program something for the site in my free time ;-)

**Comment by Maverick2805** [comment]
Working now to register, but to log in somehow doesn't work.

And don't worry at all about the speed of fixing!! This is your free time and everybody should be grateful!

**Comment by ljettinger** [comment]
i'm able to login ok...

**Comment by dsiekiera** [comment]
@Maverick2805, pls try to reset the pw via mail. Please also look into a spam folder. The mail only takes a few seconds to you.

**Comment by biber123** [comment]
Login geht nicht. angeblich falche Daten. schon mehrmals neues Passwort angefordert. keine Änderung.

**Comment by dsiekiera** [comment]
Ich rate mal. Du spielst auf mehr als einer Welt? GIb mir mal deinen InGame Namen

**Comment by biber123** [comment]
Zeno 285 der Grausame. 3 Welten

**Comment by ljettinger** [comment]
I'm still able to log out and back in without issues, I was already registered before the registration issue happened...

**Comment by ljettinger** [comment]
are the people not able to log in selecting the correct server from the dropdown list??

**Comment by Maverick2805** [comment]
> are the people not able to log in selecting the correct server from the dropdown list??

yeah, I select the correct world and only have 1 account.

**Comment by dsiekiera** [comment]
I submitted an update for login now.

**Comment by Maverick2805** [comment]
Perfect, working now!
