### ISSUE TITLE
Idea: History of neighbours LG

### ISSUE THREAD

**Issue by Maverick2805** [dsiekiera/foe-helfer-extension#737]
As a smaller player, I often face the decision to think about which neighbour to snipe and which not. It would be great to have a history to see if a LG is active or not. Because if a player is not active anymore but sticks in the neighbourhood, then one can loos many FPs if he's betting on the wrong LGs of an inactive player.

I thought about when the players LG overview is opened, the number of FP in each LG is stored and the next time the list is shown, the progress is compared and shown.

If the LG is opened in detail view, one could even see if the user has added points to the LG or not. This would give an indication about if and how active a player actually is?

Maybe there is already something like that and I just didn't see it?

**Comment by andrgin** [comment]
Snipe afeature has been removed: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
