### ISSUE TITLE
Anteilsrechner geht nicht auf

### ISSUE THREAD

**Issue by reiner22** [dsiekiera/foe-helfer-extension#74]
Der Anteilsrechner geht nicht komplett auf, und lässt sich auch nicht weg klicken.
Auch STRG+F5 bringen keine Besserung

**Comment by Selene443Foe** [comment]
Ist in dem LG ein gelöschter Spieler?
(siehe #68)

**Comment by reiner22** [comment]
Good morning,
all it’s good.
I am nly not understand the thread and i am not a programmer.
After new load the error is gon
Greetings Reiner

Von: Daniel Siekiera <notifications@github.com>
Gesendet: Montag, 12. August 2019 21:54
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: reiner22 <RSEITZ@OUTLOOK.COM>; Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Anteilsrechner geht nicht auf (#74)


Closed #74<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsiekiera%2Ffoe-helfer-extension%2Fissues%2F74&data=02%7C01%7C%7C5d50d465d6ab4740737f08d71f5edae0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637012364560339130&sdata=UFvAfXpAwODjUDRwE3Vyi0Rl8p0F0J7wqpLHH1HcfoY%3D&reserved=0>.
