### ISSUE TITLE
Infobox zeigt falsche Anzahl an FP beim Leveln von LGs

### ISSUE THREAD

**Issue by McLeise** [dsiekiera/foe-helfer-extension#742]
Die Infobox zeigt beim Level eines LG die falsche Anzahl an FP. Es werden immer nur 0 FP angezeigt.
![FP-falsch](https://user-images.githubusercontent.com/59753459/78479952-adc46700-7745-11ea-9d4c-e35b864227b7.png)

![FP-falsch2](https://user-images.githubusercontent.com/59753459/78485574-3e4f7700-7747-11ea-8805-2f53b8d9b8c1.png)

**Zusätzliche Angaben:**
_Betriebssystem:_ Windows 10 64 Bit
_Browser:_ Chrome Version 80.0.3987.149
_FOE Server:_ de3 (Cirgard)
_Fehler in der Console:_ 
[de3.forgeofempires.com-Cosole.log](https://github.com/dsiekiera/foe-helfer-extension/files/4433578/de3.forgeofempires.com-Cosole.log)

**Comment by Th3C0D3R** [comment]
Dieses Problem ist bekannt. leider Übermittelt Inno nicht wieviel FP man + gemacht hat und die IDs für die FP Pakete die man bekommt ändern sich irgendwie auch ständig wodurch man nichts errechnen kann.
Es ist aktuell so implementiert das das alte Inventar mit dem neuen Inventar vergleicht wird und der unterschied der FP Pakete berechnet wird. Aber wie oben gesagt ist das warum auch immer kaum möglich

**Comment by scibuff** [comment]
This is now fixed on Beta (#1107) and will be in the next release
