### ISSUE TITLE
Idea: Sound notification of a message in the mail

### ISSUE THREAD

**Issue by Kaveori** [dsiekiera/foe-helfer-extension#743]
My game is almost always open. I often wait for messages from friends to give them access to my buildings. It would be nice if I had the opportunity to hear a sound notification when they write to me. Then I could calmly go and wash the dishes or watch the video on YouTube, instead of sitting and looking at the screen while waiting.

**Comment by andrgin** [comment]
You can open the infobox, select "Message" in the filter and enable the sound icon ;-)

**Comment by Kaveori** [comment]
Big THANKS!

**Comment by Kaveori** [comment]
> You can open the infobox, select "Message" in the filter and enable the sound icon ;-)

Don't work((
