### ISSUE TITLE
Rate Calculation can be wrong

### ISSUE THREAD

**Issue by israel-romero-fijo** [dsiekiera/foe-helfer-extension#744]
In the image, i think Rate column (Cotizacion) is wrong calculated 

I think calculus is inverted. 

Rate should be 

netto reward
-------------   *100 = ??? %
costs

 ![imagen](https://user-images.githubusercontent.com/25433339/78527856-4c9ca200-77de-11ea-8d03-3d9200e505b6.png)

![imagen](https://user-images.githubusercontent.com/25433339/78533687-a191e580-77e9-11ea-84e5-e93f443880ab.png)
In this case (155/281)*100 = 55.2%

![imagen](https://user-images.githubusercontent.com/25433339/78534703-28938d80-77eb-11ea-925f-00919033b9e8.png)
In this case (90/35)*100= 257.1%

**Comment by andrgin** [comment]
The rate is calculated costs / netto reward.
So if you get a rate of 185% this equals a 1.85 group.

**Comment by israel-romero-fijo** [comment]
I know how calculation is made, but if i want to know which my return of investment is (ROI), should be used the inversed formula. Or maybe add a new column for this...

**Comment by andrgin** [comment]
ROI is hard to calculate because we dont know when the GB will be leveled, so it will just be a random number.

Also I dont want to make an additional column because it will get too confusing having 2 percent values.

Also the rate column is supposed to do exactly what you want. For example I have +90% arc bonus equals a rate of 190%. Considering the risk of players getting inactive or not leveling their GB fast I invest only in GBs with a rate lower than 180% which would equals around 5% ROI.

**Comment by israel-romero-fijo** [comment]
ROI data is merely orientative, nobody knows when GB will be leveled but if u secure your position whenever GB be leveled i'll receive my invested points plus arc bonus. If you see third image, Rate is lower than in the second one, even gaining many more fps. I'm afraid i don´t understand your rate calculation

**Comment by scibuff** [comment]
FPs earned / Investement cost would make more sense to me too, i.e. how many FPs do I have to invest to earn one FP

**Comment by andrgin** [comment]
Many players are used to 1.85 or 1.9 threads and have a good feeling of how much they earn with 1.85 or 1.80. I dont think it makes much sense creating another scale.

Also there are multiple ways to display it. Profit/reward would also make sense.

We cant make 3 different columns for everybody and I dont want to make a setting so it is displayed differently for everybody as it is hard to test so I think it is best leaving it the way it is.

**Comment by ketjow09** [comment]
Can anyone please explain to me what this rate mean? If it is lower then better?

**Comment by andrgin** [comment]
Rate is how many FP of the netto reward you need to pay.
So in other words 190% is what you pay in a 1.9 group. 185% is what you pay in a 1.85 group.
So yes if it is lower it is better.

So for example when sniping I take everything below 180%.

**Comment by outoftheline** [comment]
As Sniping is no more, so I'm closing the issue.
