### ISSUE TITLE
Moppel-Auswertung

### ISSUE THREAD

**Issue by marcomo09** [dsiekiera/foe-helfer-extension#745]
Die Moppel-Auswertung zeigt keine Spielernamen mehr an sondern nur Platznummern.
https://foe-rechner.de/stats/events/motivations

![Unbenannt](https://user-images.githubusercontent.com/58432539/78577097-dd4e9e80-782d-11ea-9f42-c804d1713095.PNG)

**Comment by marcomo09** [comment]
Namen werden wieder angezeigt. Allerdings werden auch Spieler angezeigt die ich schon länger nicht mehr in der Freundesliste habe.

**Comment by thhartung** [comment]
Bei mir fehlen die Namen teilweise auch.
Es wäre schön, wenn man Spieler, die man bereits als Freund entfernt hat hier auch entfernen könnte

**Comment by dsiekiera** [comment]
Duplicate of #529
