### ISSUE TITLE
Anzeige Zähler

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#75]
Guten Abend :)

diese verschiebbare Anzeige des Tavernenzählers bzw Trunkzählers funktioniert unterschiedlich.
Bei manchen Spielern funktioniert es so, dass wenn einmal die Taverne aktiviert wird und gleichzeitig ein Trunk, die Anzeige des Zählers hin und her springt zwischen den beiden.
Ich vermute mal so ist dies auch angedacht.

Dann gibt es Fälle wo die Anzeige auf die Taverne gar nicht reagiert.
Da wird dann nur der Trunk angezeigt. Ein Wechsel der Anzeige findet nicht statt.

![8](https://user-images.githubusercontent.com/50969949/61998619-edb15580-b0b2-11e9-8699-7eb781daa3fe.png)
![7](https://user-images.githubusercontent.com/50969949/61998620-edb15580-b0b2-11e9-8355-938e1b0cac6f.png)

**Comment by dsiekiera** [comment]
Der Sinn war den "extra Zug" darzustellen. Wenn es mehrere Boosts gibt, weiß ich gar nicht wie man das alles darstellen könnte.
Ich würde das erst mal darauf begrenzen oder müsste das noch mal Umbauen...

**Comment by Selene443Foe** [comment]
ja ich würde da auch keinen Focus drauf legen. Ich denke dieser Zähler hat für alle nicht so die Wichtigkeit wie der Rest.

Seltsam finde ich nur, dass er bei manchen geht und bei manchen, wie mir, nicht...

**Comment by dsiekiera** [comment]
Ist jetzt wirklich nur auf den "Extra Zug" begrenzt
