### ISSUE TITLE
FP Produktion falsch

### ISSUE THREAD

**Issue by Boennsche** [dsiekiera/foe-helfer-extension#76]
Hi,
bei mir werden keine motivierten SdW´s und HHW´s mit einberechent.
Heute angemeldet, aktiviert etc,.... leider nicht korrekt.

**Comment by dsiekiera** [comment]
Es werden nur motivierte SDWs einberechnet, da sie sonst keine FPs produzieren. Und das auch nur beim Spielstart. 
Für ein aktuelles Ergebnis muss das Spiel neu geladen werden. Das lässt sich technisch derzeit nicht anders lösen.
