### ISSUE TITLE
Infobox null error

### ISSUE THREAD

**Issue by scibuff** [dsiekiera/foe-helfer-extension#762]
The Infobox gives these error (in the console) for Guild Battlegrounds data (I believe), for example, when a building is built in a sector.

![image](https://user-images.githubusercontent.com/722049/78797780-7a3d4300-79b8-11ea-9fd0-3022e65311d9.png)

Window 10
Chrome/80.0.3987.163
en9 (Jaims)
2.4.3.2 - English

**Comment by flyingbetty** [comment]
My Infobox is empty everytime. There is nothing in it.
