### ISSUE TITLE
PvP Overview Unknowns und 404 Exception

### ISSUE THREAD

**Issue by FalkoVPart** [dsiekiera/foe-helfer-extension#763]
**Voraussetzung:**
- bislang KEINE Kämpfe gegen Nachbarn abgeschlossen

**Durchführung:**
- PvP-Übersicht das erste Mal öffnen

**Ergebnis:**
- Avatare alle mit Standard-Platzhalter und "Unknown" belegt
- Namen als "Unknown []" belegt
- Zeitalter mit "Eras.undefined" belegt
- Stadtschilder mit scheinbar zufälligen Zeitintervallen belegt (40 Minuten, 1 Tag und 2 Tage)
- Angehängter 404 Error in der Console, "undefined.jpg nicht gefunden"
- weißer Pixel am unteren rechten Fensterrand der Übersicht

Windows 10 64 Bit
Chrome 80.0.3987.149
de11 (Langendorn)
2.4.4 - Deutsch

![PvP Window Nulls](https://user-images.githubusercontent.com/40738463/78805528-ce005a00-79c1-11ea-828f-7c0ac9eaef1c.jpg)
![Error](https://user-images.githubusercontent.com/40738463/78805559-d6f12b80-79c1-11ea-86cd-b3e46cc464ad.jpg)

**Comment by osv** [comment]
Hi, looks like no player information, my guild teammate also report some issue, I'm looking on it

**Comment by osv** [comment]
Should be fixed in next release, @FalkoVPart on your screenshot you can see players that have city protect shield, but you not jet visited player so cannot show details. However it should be fixed soon
