### ISSUE TITLE
PVP Activity

### ISSUE THREAD

**Issue by syjytg** [dsiekiera/foe-helfer-extension#766]
I see a new PVP Activity icon. How do I use it to see if my neighbour is active?

**Comment by andrgin** [comment]
This new tools does not show if your neighbour is active. It shows when you have attacked and plundered this neighbour and the army he had

**Comment by syjytg** [comment]
Can you tell me how you add label please? Also the changelog says "shows all active city signs in your neighborhood" at the end.

**Comment by ecthelioni** [comment]
Hello
Thank you for new function, it is very nice.

I have new idea:
I think, that will be won't see when I attack many neighbour .

My idea is display first PvP windows in one row:
player name, defensive bonus, time from last attack and white text  when I win last battle, red text when i lost last battle.
When I click to the player name, will be opening details about last battle (What I see now)

**Comment by osv** [comment]
I'm playing game on pc using wide monitor so for me this is not a problem to have 2 big windows. 
But I think good to have some compact version of this window with latest information only.

**Comment by Grazvas** [comment]
Hey,
I am daily plunderer and when i saw this feature i got overjoyed.
But it doesn't seem to work properly. I attacked 73 neighbours but only 11 attacks got recorded :(

**Comment by osv** [comment]
@Grazvas there were bug when you attack newer player than you - not recorded. Should be fixed

**Comment by andrgin** [comment]
It is already fixed in Beta, but we are still testing a few other features before we can release the update.

**Comment by outoftheline** [comment]
This feature has been removed.
