### ISSUE TITLE
FoE helper Fp's needed incorrect

### ISSUE THREAD

**Issue by Randrm** [dsiekiera/foe-helfer-extension#767]
foe helper star gazer 23->24 P(1) 694 fp's not matching https://foe.tools/gb-investment/Star_Gazer P(1) 713 fp

**Comment by andrgin** [comment]
Did you select 85% or 90%?

**Comment by lnplnp** [comment]
Be careful, sometime FOETOOLS give wrong number of fps too.

**Comment by Randrm** [comment]
I have pulled fp's and other items from sources to use in my own
spreadsheets. I try to validate them against the wiki. Is there a foe
source of basic info that I could use?

**Comment by andrgin** [comment]
Unfortunately nothing official, but copying from foe.tools seems the fasterst way as they have sources on github.
