### ISSUE TITLE
Ereignisse: Interaktion nach Spieler keine Anzeige

### ISSUE THREAD

**Issue by Boennsche** [dsiekiera/foe-helfer-extension#77]
Leider bekomme ich nicht alle Ereignisse angezeigt.
Kein Inhalt oder das:

![Ereignisse](https://user-images.githubusercontent.com/53441233/62061242-0fcbe480-b227-11e9-8411-d781a30eea73.jpg)

**Comment by dsiekiera** [comment]
Das erscheint nur wenn zu wenig Daten vorhanden sind.
