### ISSUE TITLE
Reihenfolge der Icons in der Menüleiste

### ISSUE THREAD

**Issue by Tsching-Foe** [dsiekiera/foe-helfer-extension#779]
Ich habe im Chrome verschiedene Tabs offen und in jedem eine andere Welt. Die Reihenfolge der Punkte in der Leiste sind auf jeder Welt unterschiedlich. Lässt sich das irgendwie vereinheitlichen?

**Comment by andrgin** [comment]
Die Icon Reihenfolge kannst du selbst bestimmen indem du sie nach oben oder unten ziehst je nachdem was du öfter brauchst.
Da jede Welt seine eigenen Einstellungen hat, musst du deine Icons auf jeder Welt anordnen.
Gemeinsame weltübergreifende Einstellungen sind technisch nicht möglich.

**Comment by Tsching-Foe** [comment]
Danke Dir. Habs auch gerade bemerkt und einfach mal verschoben. Sorry!
