### ISSUE TITLE
Nun alles ins Forum schreiben?

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#78]
Guten Abend,

wie ist das eigentlich mit dem Button "Forum" gemeint?
Bisher wurde ja alles was einem auffällt hier rein geschrieben.
Jetzt gibt es ein Forum was, wie mir scheint, nun dazu gedacht ist.
Wir ziehen also mit unseren Fragen / Wünschen / Ideen nun dorthin um?
Und wenn ja - kommen die Texte von hier mit da rüber? Ich vermute sonst wird alles mehrfach geschrieben?!

**Comment by JHCD** [comment]
Nein, alles was das Plug-in betrifft gehört hierher... 

Das ist nur ein Link zum Forum.
