### ISSUE TITLE
Kein Ton beim Kostenrechner

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#783]
Kann kann zwar oben auf den Lautsprecher klicken... aber es passiert nichts.
Ton bleibt immer deaktiviert :-(

**Comment by andrgin** [comment]
Ich vermute das ist dieser Bug: https://github.com/dsiekiera/foe-helfer-extension/issues/764

**Comment by andrgin** [comment]
Sollte mit dem aktuellen heutigen Update gefixed sein
