### ISSUE TITLE
Feature: Sort resources by quantity

### ISSUE THREAD

**Issue by lnplnp** [dsiekiera/foe-helfer-extension#786]
Hi,
It would be great to automatically order resources by quantity in the preferred order of the window that allows negotiation in the guild expedition.

**Comment by andrgin** [comment]
What do you mean with "preferred order of the window".
Goods are ordered so that coins/supplies, cheaper goods of previous eras or goods with a higher stock are used first.

**Comment by lnplnp** [comment]
In the negotiation assistant, I would like resources to be ordered according to the quantity I have in my stock, regardless of their value.
Like : coins, supplies, goods with higher stock.

**Comment by c01mic** [comment]
A good option would be to permanently block the goods from the era. That is, we set that the previous epoch (according to the quantity in the warehouse) will be charged first, then the current epoch.
To sum up: 
1.Gold/supplies
 2 The era we chose first (according to stock levels)

**Comment by lnplnp** [comment]
> A good option would be to permanently block the goods from the era
I don't understand why it would be a good option.

**Comment by c01mic** [comment]
> > A good option would be to permanently block the goods from the era
> 
> I don't understand why it would be a good option.

Nowadays, I have more production from the era I am in. Changing the order of goods before almost every negotiation can be tiring.
Goods from certain epochs are less available on the market, so I prefer to give them a second order. And first of all, I set it once, not change it before each negotiation.

**Comment by lnplnp** [comment]
In the negotiation assistant in the guild expedition, only the resources that can be invested are displayed and proposed. So it's not a problem that you have a lot of other resources from different eras.

Furthermore, I do not believe that it is possible to "block" the personalized order because the resources necessary for negotiation vary from one negotiation to another.

If you produce more resources of the current era then your stock should be more supplied, so automatically establishing the order of preference by the number of resources in your inventory should not be a problem.

**Comment by c01mic** [comment]
> In the negotiation assistant for the guild expedition, only the resources that can be invested are displayed and proposed. So it's not a problem that you have a lot of other resources from different eras.
> 
> Furthermore, I do not believe that it is possible to "block" the personalized order because the resources necessary for negotiation vary from one negotiation to another.
> 
> If you produce more resources of the current era then your stock should be more supplied, so automatically establishing the order of preference by the number of resources in your inventory should not be a problem.

You don't understand what I mean. 
Two epochs are important in negotiations. The present and the previous one. It is known that the present era provides us with much more goods (production, Château Frontenac). The goods from the previous era can be obtained mainly on the market. And if there are goods from two epochs in the negotiations, the goods from the present should be set first or it is possible to set them first just after gold and supplies.

**Comment by andrgin** [comment]
Goods of the same era are sorted by stock.

Goods of the previous era are always counted as cheaper goods (with the exception of Mars).

The reason for this is that you can always trade down goods. As long as you are not doing strange things like staying in iron age forever there are more than enough neighbors accepting your trades. Just dont do it at 1:2. Put them in at 1:1.5 and you will be fine.

**Comment by c01mic** [comment]
I don't know what worlds you're playing in, but there's a terrible problem with the goods from the previous era on mine, so I came up with this idea.

**Comment by scibuff** [comment]
> Goods of the same era are sorted by stock.
> 
> Goods of the previous era are always counted as cheaper goods (with the exception of Mars).
> 
> The reason for this is that you can always trade down goods. As long as you are not doing strange things like staying in iron age forever there are more than enough neighbors accepting your trades. Just dont do it at 1:2. Put them in at 1:1.5 and you will be fine.

Yeah, this is not necessarily true. Downtrading can be problematic. For players with high level Chateau it is much easier to get the current era goods.

**Comment by andrgin** [comment]
How many goods you make per day with your CF?

**Comment by c01mic** [comment]
> How many goods you make per day with your CF?

10-15k is not a problem:)

**Comment by andrgin** [comment]
Hhm OK that explains a lot...

**Comment by andrgin** [comment]
In the next update we will have 2 settings available in the negotiation helper window that are stored permanently:
.) Save current era goods: If you deactivate this option goods are only chosen based on current stock instead of era.
.) Save medals: If you deactivate this options medals will be used before goods.

Gold and supplies are always are always used first and special resources like promethium are always used last.

**Comment by lnplnp** [comment]
Thanks. I will try it.

**Comment by lnplnp** [comment]
Thanks for this new feature ! It works good for me !
