### ISSUE TITLE
Friend removal from Guild list bugged

### ISSUE THREAD

**Issue by Beta-Wolf** [dsiekiera/foe-helfer-extension#789]
When the extension is enabled, I'm not able to remove friends via the guild member-list.

![ (27)](https://user-images.githubusercontent.com/31244425/79057163-834f3e00-7c5e-11ea-98e9-61ca2b8f8e76.png)

**Comment by andrgin** [comment]
Did you add that brown bar above their names?
What happens if you click on your guild members name? Do you get the context menu for removing friends?

**Comment by Beta-Wolf** [comment]
> Did you add that brown bar above their names?
> What happens if you click on your guild members name? Do you get the context menu for removing friends?

I blurred out the names.
How to reproduce:

-> Click on the name of a friend in your guild list.
-> Click "Remove friend".
-> The windows closes and there won't be a pop-up to confirm the friend removal.
-> The friend isn't removed.

**Comment by andrgin** [comment]
This is an Inno games bug and has nothing to do with the extension.

No matter if the extension is loaded or not this bug occurs only if you have not opened the friends tab since game start. So if your game starts with guild members selected and you try to remove your friend it does not work. If the game starts with friends selected and you switch back to guild members you can remove them.

**Comment by Beta-Wolf** [comment]
> This is an Inno games bug and has nothing to do with the extension.
> 
> No matter if the extension is loaded or not this bug occurs only if you have not opened the friends tab since game start. So if your game starts with guild members selected and you try to remove your friend it does not work. If the game starts with friends selected and you switch back to guild members you can remove them.

When I disable the extension, it works perfectly fine. Only when the extension is enabled, the problem occurs. 

So I highly doubt the issue is with Innogames.

**Comment by andrgin** [comment]
I checked without the extension and can reproduce it as well.
Try foolowing steps:
1.) Start the game and change to the guild members tab
2.) Reload the game
3.) Try removing your friend

**Comment by Beta-Wolf** [comment]
This thread can be removed.
