### ISSUE TITLE
Welt auswählen

### ISSUE THREAD

**Issue by ruqu911** [dsiekiera/foe-helfer-extension#79]
Hauptwelt brisgard + tuulech +uceria. angezeigt wird brisgard + uceria +eldenborough (hatte ich mal)
wie krieg ich das wieder in ordnung?

**Comment by JHCD** [comment]
Welt löschen geht aktuell nicht...
Lädst Du für Tuulech was hoch? Sieht so aus, als wenn Du das für die Welt nicht aktiviert hättest.

**Comment by ruqu911** [comment]
eingestellt ist es jetzt....

**Comment by dsiekiera** [comment]
Dann sollte das normalerweise in Kürze auftauchen.

**Comment by ruqu911** [comment]
alles ok danke
