### ISSUE TITLE
New idea - power levelling + improving FP display of event buildings

### ISSUE THREAD

**Issue by Monkeys012** [dsiekiera/foe-helfer-extension#790]
Dear team,
often players want to push one of their legendary buildings by several levels at once, so called "power levelling". The problem is that the player who wants to do this needs to keep enough forge points in his stock in order to complete the planned amount of levels.
Surely one can calculate the necessary sum of forge points manually, but wouldn't it be nice to have a tool for to do it? Basically such a tool is almost available in the foe-extension, namely the calculator...
I suggest to extend it by another function that allows to calculate the required forge points from a start level to the desired end level. Say i. e. you want to push your Cape Canaveral from level 35 to 60, it tells you immediately that you'll need 4,703 fp in your stock. 

My second idea contains a little improvement in the daily report of the production of your city.
This report is very useful to me as it tells me how many fp a day I make and so I can schedule my investments pecisely. But this could be still improved a little bit, or lets say optimized.
In my particular city there is the following situation:
I have got 6 lighthouses in my city. The report window tells me exactly how many fp each of them will produce the current day. It can be either 8 or 20 fp - depending on the random generator.
But it does NOT tell me which particular lighthouse spends 8 and which 20 forge points.
You may ask now: why does it matter? Well, the point is that I possess also the blue galaxy, which doubles the given ressources randomly. Since the hits of the blue galaxy are limited, it would be better if one could determine the lighthouses (or other event buildings that are multiple times available) more specifically. 
To accomplish this, I suggest to add in the report simply the current age of the event buildings in brackets. For example: Lighthouse level 8 **(Industrial age)**
Sure, if they are all in the same age, the result is like before, but now the player can decide if he wants to upgrade his buildings and receive the better benefits or if he prefers to determine the buildings with the best chance getting most of the forge points.

I'll be waiting for your thoughts and would be glad to hear from you, even if my idea will be declined.

Kind regards
Olaf

**Comment by andrgin** [comment]
1.) We already have a calculator for that: https://foe-rechner.de/invest/level
It is just not translated to English yet.

2.) You can click on the eye symbol on the right side of the row. This will open a map showing you the position of this building.

**Comment by Monkeys012** [comment]
Hallo,
da der Rechner auf Deutsch ist, vermute ich mal, dass ich dann auch auf
Deutsch schreiben kann. Ich hatte mich nur von den vielen englischen
Beiträgen im Forum verwirren lassen. :-)

Zunächst einmal danke für die Antwort.
Ich möchte dann meinen Vorschlag dahingehend konkretisieren, ob man den
Powerlevel-Rechner nicht in das AddOn integrieren könnte, analog zum
Eigenanteilsrechner?!
Es könnte ja sogar eine Registerkarte in selbigem sein, ähnlich wie bei der
Tagesproduktion (FP, Medaillen, Münzen, Güter etc.)
Das Start-Register wäre dann halt der Eigenanteilsrechner (weil öfter
benötigt) und als weiterer Rechner der Powerlevel-Rechner.
Diesen könnte man noch ergänzen um eine 1,85 er bzw. wahlweise 1,9 er
Förderung.
Zum Einstellen der Start- und Zielstufe genügt ja jeweils ein Eingabefeld.
Die Verwendung eines Schiebereglers ist meines Erachtens zu filigran,
insbesondere wenn die Stufen dicht bei einander liegen.

Danke.



Am So., 12. Apr. 2020 um 20:32 Uhr schrieb Gindi4711 <
notifications@github.com>:

**Comment by andrgin** [comment]
Powerlevel Rechner ist seit dem letzten Update auch in der Extension verfügbar (Button im EARechner)
