### ISSUE TITLE
Feature: number of taverns can be visited

### ISSUE THREAD

**Issue by lnplnp** [dsiekiera/foe-helfer-extension#795]
Hi,
Is it possible to have somewhere the current number of taverns that can be visited?

**Comment by Th3C0D3R** [comment]
I think it is possible to get the number of taverns which can be visited.

**Comment by lnplnp** [comment]
Maybe you can add this information in the "hidden rewards", where there is the list if incidents.

**Comment by scibuff** [comment]
The data is available but I'm not sure how reliable it is. I always see the tavern icon (indicating whether or not it is possible to visit) changing when I scroll through my friends list. It seems that the data received at the start is cached, and it refreshes for the set of 5 friends as you go through the list. If that's the case, it may not be possible to get accurate number of available taverns until you scroll through all your friends, which would kinda defeat the purposes of showing this information in the first place.
