### ISSUE TITLE
Kostenrechner - Wunsch

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#80]
Guten Abend,
ich hätte einen Wunsch zum Kostenrechner.
Zur Zeit wird im rechten Feld angezeigt wieviel Gewinn man machen kann.
Könntest du noch sichtbar machen, ob bzw welcher Platz save ist? Also ohne Gewinn, aber auch ohne Verlust belegbar ist?

Ich könnte mir das optisch so vorstellen, dass man das anhand einer Farbe kenntlich macht.
Zur Zeit sind alle Zahlen links Grün. Bzw die ganze Zeile ist Blau wenn man schon drin ist.
Wie wäre es, wenn die linken Zahlen weiß, wie alle anderen färbt und wenn ein Platz save ist wird die Reihe Grün?

Das wäre sehr praktisch um feststellen zu können, ob die LB welche in den Förderungen ausgeschrieben sind auch wirklich save sind.

**Comment by dsiekiera** [comment]
Die Anzeige mit einem möglichen Gewinn ist schon immer die "save"-Version. Ansonsten würde nichts angezeigt werden. Also es bleibt bei den "-" Anzeigen.
Was fehlt ist eigentlich nur die "+-0" Darstellung

**Comment by dsiekiera** [comment]
Hab das ergänzt. 
Es wird ab sofort eine grüne "0" (Null) in der letzten Spalte dargestellt, wenn es genau aufgeht.
