### ISSUE TITLE
Bug: PvP-Aktivitäten ignoriert teilweise Kämpfe / Attacks not recorded

### ISSUE THREAD

**Issue by jiim92** [dsiekiera/foe-helfer-extension#805]
Beim neuen PvP-Aktivitäten Modul werden die getätigten Kämpfe oft ignoriert und nicht mitgeloggt. Das Plündern aber wird jedesmal richtig mitgeloggt. Es ist mir aufgefallen, dass dies auch immer bei denselben Namen passiert. Zu sehen am Screenshot, dass die Kämpfe fehlen.
![image](https://user-images.githubusercontent.com/56258181/79119322-60bd4200-7d90-11ea-828e-106b40764fa8.png)

Windows 10 64 Bit
Chrome  80.0.3987.163
de18 (Sinerania)
2.4.4 - Deutsch

**Comment by scibuff** [comment]
I believe this is #773 and should be fixed in the next update
