### ISSUE TITLE
Idea: Customize Buttons in Cost Calculator

### ISSUE THREAD

**Issue by anudureio** [dsiekiera/foe-helfer-extension#806]
Hello, I would like to know if there is a way I could do that or if you can add a feature for that. I'd like to replace the 85% button in Cost Calculator with another value... I'd like to have 90, 91 and 92 buttons if there is a way. Thank you for your answer.

**Comment by scibuff** [comment]
The default is 85%, 90% and your current arc bonus. You can put any number you'd like in the "friendly invest" field (just beneath the buttons)
