### ISSUE TITLE
Plünderanzeige

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#81]
Guten Abend,

ich hab lange überlegt wie man das eigentlich nennt, ein älteres Posting hat einen wie ich finde passenden Namen enthalten :)

ich habe wieder ein paar Bilder. Augenscheinlich handelt es sich um ein und denselben Fehler?!

![13](https://user-images.githubusercontent.com/50969949/62553656-09191f00-b870-11e9-966d-9bfb0e6e3368.png)
![14](https://user-images.githubusercontent.com/50969949/62553658-09191f00-b870-11e9-9739-c7b835417464.png)
![12](https://user-images.githubusercontent.com/50969949/62553659-09191f00-b870-11e9-906f-2deeca5f3bd7.png)

wobei ich diese Zeile hier am seltsamsten finde:
![15](https://user-images.githubusercontent.com/50969949/62553848-60b78a80-b870-11e9-9d53-96b3c865ae57.png)

**Comment by dsiekiera** [comment]
Wenn das alle mit "undefined" übersetzt wurde, sind dieÜbersetzungen von Inno nicht korrekt verarbeitet worden. 
Hier sollte ein einfaches STRG + R (Reload) helfen.

**Comment by Selene443Foe** [comment]
Sorry. Ein einfaches STRG + R hilft leider nicht. Die Anzeige sieht genauso aus wie vorher...
