### ISSUE TITLE
Guild Goods Income

### ISSUE THREAD

**Issue by HarmMollen** [dsiekiera/foe-helfer-extension#812]
With the new Guild battles it's important to know how much and which goods your guild generates as income because of the battle costs. Every player in the guild generates income (Arc, etc..) depending on the age they are in. Guild goods (and mutations) can be grabbed from the guild info page and calculated against the GS battle costs for encampments. Is this possible to implement in any way?

**Comment by osv** [comment]
Hi, currently I'm working on treasure statistics. However this is just log of your guild's goods. 

In next screenshot below you can see how much Guil's good lost during GvG battles in Future era -60k goods. Support export to CSV too. I need do final test when battleground starts tomorrow and will create pull request soon.

![guild](https://user-images.githubusercontent.com/213405/79386726-38416d80-7f73-11ea-8d51-3d2f715394f5.jpg)

**Comment by scibuff** [comment]
Sweet. Excellent work!

**Comment by HarmMollen** [comment]
Looks very promising!

**Comment by osv** [comment]
My experiments, show battle info: GvG lost goods per Age
![guild](https://user-images.githubusercontent.com/213405/79622754-37e6d500-8121-11ea-8dff-ee8cea4ba06e.png)

**Comment by fxmozart** [comment]
Looks great
