### ISSUE TITLE
Auswertung der "Moppler"

### ISSUE THREAD

**Issue by markbat** [dsiekiera/foe-helfer-extension#814]
Ist es möglich, eine Statistik der Motivierer und Polierer anzeigen zu lassen?
Eine Sortierfunktion Name / Tag / Gilde oder Freunde wäre hervorragend.

**Comment by marcomo09** [comment]
Gibt es doch bereits
https://foe-rechner.de/stats/events/social-player

**Comment by markbat** [comment]
Ja, allerdings nicht funktionstüchtig: 

Fatal error: Uncaught ADODB_Exception: mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY ops.other_name, Spalte ORDER BY ops.other_name ASC, Spalte ' at line 17] in EXECUTE("SELECT ops.other_name, WEEK(opse.date_visit,1) AS Spalte, count(opse.visitor_action) AS Anzahl FROM other_players_service_de15 as ops LEFT JOIN other_players_service_entries_de15 as opse ON ops.ops_id = opse.ops_id WHERE ops.player_id = 5327121 AND ops.is_guild_member = 1 AND opse.visitor_action IN ('motivate','polish','polivate_failed') AND WEEK(opse.date_visit,1) in () GROUP BY ops.other_name, Spalte ORDER BY ops.other_name ASC, Spalte DESC ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1064, 'You have in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79
