### ISSUE TITLE
Idea : keeping tracks of snipes made to optimize friends

### ISSUE THREAD

**Issue by tartetatin18** [dsiekiera/foe-helfer-extension#815]
Would be nice to be able to keep tracks of snipes made and snipes efficiency, with our friends.
Then we can change friends if some are not good candidates enough for snipes.
Hope you'll find this interesting too :)
tatin

**Comment by scibuff** [comment]
Indeed! This has been on my own todo list for ages ;) --- so many good ideas so little time

**Comment by tartetatin18** [comment]
can i help ?

**Comment by andrgin** [comment]
How do you decide between bad friends you are sniping and good friends that are paying in your 1.9 threads?
Also there is no way to check how much profit you made in your friends without opening each GB and scrolling one level back. We could only tell which place you got in a GB. This could be a snipe or a simple 1.9 friendly investment.

**Comment by tartetatin18** [comment]
hi andrgin, each time i snipe, i suppose it's a good friend :)
but : unless i write down on a paper every snipe i made, i don't have track of which friends i've been sniping or not (regardless the cost, 1.9 or less), and how much i invested and earned.
some friends have very few opportunity of snipes or "small' snipes. These friends i want to get rid of.
it's "just" a question of increasing 2 counters for each friend : first counter would be invested fp, and the second one, fp earned. Then we coud have a ratio between these 2 counters to evaluate the "snipe efficiency" of this friend

**Comment by andrgin** [comment]
Are you trying to snipe all of your friends? I think most players dont snipe their friends at all. I had a few of them who are very chaotic and dont use any 1.9 threads or chains and dont mind if I snipe a GB, butmost of them would kick me out of their list if I snipe a GB below 1.9

**Comment by tartetatin18** [comment]
oh ok ! well, yes I'm sniping all my friends, and since they are all "small" players, they're happy to have my fp on their gb. It's a win/win situation actually.
I invest 1.9 with the players of my guild. That would be the difference for me between a friend and a "guild-er".
I find it a bit difficult to plunder neighbours and also snipe them ! So usually I plunder neighbours, snipe friends, and I keep 1.9xpf to guild-ers

**Comment by scibuff** [comment]
Same here, I regularly refresh my friends list with players with open Arcs level 30-70 :)

**Comment by andrgin** [comment]
Snipe feature has been removed: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
