### ISSUE TITLE
Plundering

### ISSUE THREAD

**Issue by Digglefritz** [dsiekiera/foe-helfer-extension#816]
Doesn't show what's available to plunder anymore.

**Comment by andrgin** [comment]
1.) Did you activate the neighbourhood harvest feature in settings?
2.) Is there a box showing "nothing to plunder"?
3.) Is the player also a friend or guild member?
4.) Are there exceptions shown in the console (press F12 and go to the console tab)

**Comment by Digglefritz** [comment]
Yes there is one exception shown in the console. 

DevTools failed to load SourceMap: Could not load content for chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/vendor/dexie/dexie.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by andrgin** [comment]
That is just a warning from Chrome. You can ignore that.

**Comment by scibuff** [comment]
Are there any error in the extensions management under chrome://extensions/ (see FoE - Helper). There would be "details", "remove" and "errors" buttons (if there are errors)

**Comment by Digglefritz** [comment]
No, there are no errors.

**Comment by scibuff** [comment]
Just to double check, are you saying that the list is empty, e.g. it shows "Nothing to plunder" or that the entire Box (which shows the info) does not appear?

**Comment by Digglefritz** [comment]
The entire box does not appear, there are things to plunder.

**Comment by scibuff** [comment]
Ok, it could be that it just got moved out of the view. Try going to one of the cities to plunder, then open the console (F12) and copy paste this `$('#ResultBox').prop('style','top:50px;left:50px;');` and hit enter. If the box was moved out of the view this would set the coordinates to (50,50)

**Comment by Digglefritz** [comment]
That fixed it. Thank you so much.
