### ISSUE TITLE
Eingaben lösen Tastaturbefehle aus

### ISSUE THREAD

**Issue by krkkrk** [dsiekiera/foe-helfer-extension#819]
Tastatureingaben in Eingabefeldern des FoE-Helfer wie z.B. in der Gebäudesuche der Produktionsübersicht lösen die globalen Tastaturbefehle (z.B. M für die Karte der Kontinente) aus.

Das Bubbling der Events müsste per stopPropagation() gestoppt werden damit es nicht bei den globalen Eventhandlern landet. Ich habe das zum Test in HTML.Box() (_helper.js) unterbunden.

`
args['disablehotkeys'] = true;
if(args['disablehotkeys'] !== undefined) {
    $('#' + args['id']).on('keydown keyup keypress','input', function (evt) {
        evt.stopPropagation();
    });
}
`

Windows 10 64 Bit
Chrome 80.0.3987.163
de14
2.4.4 - Deutsch

**Comment by scibuff** [comment]
Yes, I noticed this too. It needs to be done for `input` and `textarea`
