### ISSUE TITLE
Plundering List Incomplete

### ISSUE THREAD

**Issue by jennweinberg** [dsiekiera/foe-helfer-extension#820]
When I pull up my list of folks I have plundered it does not have all the information. For example, one player only shows one plunder and doesn't show the battle info. It was 4 days ago and the list goes back at least 7 days so the battle info should definitely be there.

Also, it would be amazing if you also list losses so you could plan an appropriate army for your next attempt.

Thank you for this amazing tool!

**Comment by scibuff** [comment]
I think the battle info is because of the known bug which is already fixed on beta (it doesn't record battles if your player id is < than the id of the player with whom you battled)
