### ISSUE TITLE
Add an MMR calculator, and +/- MMR for current standings in league

### ISSUE THREAD

**Issue by cjlear** [dsiekiera/foe-helfer-extension#821]
See MMR calculator at
github.com/foe-mmr/foe-mmr.github.io/blob/master/README.md

**Comment by osv** [comment]
The MMR number will be visible for your Guild soon in game. and +- MMR you can find here https://forgeofempires.fandom.com/wiki/Guild_Battlegrounds

**Comment by dsiekiera** [comment]
Excuse me, but what is MMR calculator?

**Comment by andrgin** [comment]
MMR is the points that determin if you rise of fall in the league, but this will be implemented by Inno soon, so I dont think there is a need for us to show it.

**Comment by outoftheline** [comment]
As this is now an ingame feature, I'll close this.
