### ISSUE TITLE
Is it possible to have army helper ?

### ISSUE THREAD

**Issue by lnplnp** [dsiekiera/foe-helfer-extension#824]
Hi,

is it possible to get an army helper that suggest the soldiers to use ? Something like negociation ?

**Comment by scibuff** [comment]
Please see #683

**Comment by lnplnp** [comment]
https://github.com/dsiekiera/foe-helfer-extension/issues/683
Yes I have seen it after !
I'll post a comment on the offer issue/feature/idea.

Thanks !
