### ISSUE TITLE
Idea: FP Calculator improvement.

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#825]
FP Calculator is great and reduces "usual" calculator usage significant.
But sometimes (not often) we need additional calculations during FP deposition.
There are (rare) cases when we need to deposit not exact FP corresponding Arc coeff, but on several FP more or less (f.e. if I have some debt before GB owner - I need to deposit more FP than Calculator shows). So it will be helpfull if Calculator has small window (with default 0), where we can enter +NN FP (to deposit more FP than usually) or -NN (to deposit less FP).

**Comment by scibuff** [comment]
I"m not sure I understand the point. Can't you just take what the calculator shows and add/subtract what you need to/from that number?

**Comment by andrgin** [comment]
You can use the ext column to simulate other payments

Example:
P1 is 190FP
P2 is 95 FP

Your guild mate owns you 50 FP. So you add the 50 FP to the 190 FP (total 240) and you can check if you are happy with the plan.

**Comment by scibuff** [comment]
You can already do this, just enter the 190+50 (please see below, in this case it is 162 + 50) 
![image](https://user-images.githubusercontent.com/722049/79686357-04e73300-8240-11ea-8e42-b38b549ca749.png)

**Comment by belikoviv** [comment]
> You can use the ext column to simulate other payments

Yes, I can use "ext" column.
But "ext" column is absent in "Cost calculator". It exists only in "Co-payment calculator".

**Comment by belikoviv** [comment]
> I"m not sure I understand the point. Can't you just take what the calculator shows and add/subtract what you need to/from that number?

I'll try. English is not my first language :(

![2004201050](https://user-images.githubusercontent.com/35531243/79727287-d9725000-82f4-11ea-9694-368371a7ded4.png)

As you can see on screen - I need to deposit 456 FP.
But several hours before I made mistake and deposit in another GB of this player extra 20 FP. And reach an agreement with him to deposit next time 20 less FP.
So I wish to have "ext" field (as "ext" column in Co-payment calculator) to enter there "-20" and Cost calculator show me right sum of FP I need to deposit.

**Comment by Th3C0D3R** [comment]
Lol, spending FP to not get plundered? That's funny.

What you are wanting is something special and has no real use for others.

**Comment by belikoviv** [comment]
> Lol, spending FP to not get plundered? That's funny.
It was for example.
I may give you another example - some amount of FP in exchange of goods.
