### ISSUE TITLE
PvP Übersicht zeigt keine Kämpfe an

### ISSUE THREAD

**Issue by Capo94** [dsiekiera/foe-helfer-extension#826]
Hallo,
ich weiß nicht was ich falsch mache. Ich habe bereits Auto- und manuellen Kampf versucht aber in der PvP Übersicht werden mir bei 99% aller Spieler nur die Plünderungen und Stadtschilde angezeigt. Keine Kämpfe oder deren Boostwerte!
Bei einem einzigen Spieler aus der Nachbarschaft scheint es immer zu klappen, beim Rest nicht.

Wie behebe ich das ?

Mit freundlichen Grüßen
Capo

**Comment by scibuff** [comment]
This is already fixed (please see #820, #805, #773) and will be in the next release
