### ISSUE TITLE
Datentransfer

### ISSUE THREAD

**Issue by FritzSpitz** [dsiekiera/foe-helfer-extension#83]
Seit dem 01.08.19 werden bei mir keine Daten  an FoE Rechner übertragen. Alle Versuche die Datenübertragung wieder in Gang zu bringen sind gescheitert. Was soll ich jetzt noch tun?

**Comment by dsiekiera** [comment]
Das sollte ab heute mit den Updates von Extension und Webseite wieder funktionieren.
