### ISSUE TITLE
Investment Calculation

### ISSUE THREAD

**Issue by ChaosTheoryRules** [dsiekiera/foe-helfer-extension#836]
I am aware you need to open your inventory to update packs however sometimes you go check packs, go open investment window, and find it is around 2k fp reduced from last check. Wait awhile for another GB flip, repeat process, the missing 2000 are back.

I havent done a manual check to confirm yet, but it is not the first time I have seen this and near as I can recall it has always been 2k difference which is why i notice it.

**Comment by andrgin** [comment]
Inventory is updated every time it is shown on screen like if you open a GB, open inventory and so on so it should not be off so much. The most likely explanation is that a GB is leveled and removed from the list, but you did not receive the reward yet, but this is hard to reproduce.

**Comment by scibuff** [comment]
This should be fixed now on Beta with #1107 and will be in the next release
