### ISSUE TITLE
Wrong total GB (Zeus level 20) cost value

### ISSUE THREAD

**Issue by Minotorious** [dsiekiera/foe-helfer-extension#839]
![Screenshot (11)](https://user-images.githubusercontent.com/40427380/79754923-8b6f4380-8318-11ea-921d-7ea907451aca.png)

As seen in the screenshot the total amount for the level is wrong. FoeHelper says 653 FPs while the game value is 637 FPs

**Comment by scibuff** [comment]
The game's view is incorrect (which is a known bug when you go through the levels). The correct total for level 19->20 is 653
