### ISSUE TITLE
Ernte 2038?

### ISSUE THREAD

**Issue by MrMattn** [dsiekiera/foe-helfer-extension#84]
https://www.bilder-upload.eu/bild-bb1593-1565201610.png.html

**Comment by Elschen** [comment]
Hab ich auch seit dem letzten Update :-(

**Comment by JHCD** [comment]
Inno hat die Möglichkeit die Ernte auszulesen ausgebaut...

**Comment by MrMattn** [comment]
ernsthaft?
komisch, dass es dann noch bei ein paar geht!?

**Comment by JHCD** [comment]
Ich kann Dir nur sagen, was Inno veröffentlicht...

Das Inno Möglichkeiten für Funktionen des Plugins ausbaut, war absehbar/angekündigt...

https://forum.de.forgeofempires.com/index.php?posts/302527

Ich rechne auch damit, dass die Ernte-Anzeige mittelfristig nicht mehr gehen wird...

**Comment by MrMattn** [comment]
hm das wäre schade aber verständlich.

aber ganz ehrlich...solange der Kostenrechner bleibt und man sehen kann wo man Gewinn machen kann...
kann ihn mir gar nicht mehr wegdenken. Allein was das an Zeit spart...

**Comment by dsiekiera** [comment]
Inno hat die Zeiten für die letzte Einzahlung + Ernte komplett entfernt. Daher habe ich diese Darstellung entfernt.

**Comment by dsiekiera** [comment]
**Nachtrag**

Hier isses schriftlich: [https://forum.de.forgeofempires.com/index.php?threads/tool-erlaubt.33170/page-3#post-314803](https://forum.de.forgeofempires.com/index.php?threads/tool-erlaubt.33170/page-3#post-314803)
