### ISSUE TITLE
Boost Report missing from Production Overvies

### ISSUE THREAD

**Issue by noaquie** [dsiekiera/foe-helfer-extension#846]
Under the Production Overview, building tab (on far right).  Selecting the drop-down menu, selecting boost.  No boost are showing.  There are several buildings in my city that have a percentage of attacking and or defending the city or when doing battle. These do not show up under this menu selection.  Example: Appleton Cottage has +8,160 coin, 6% Att. for Attacking, 11% Def. for Defense, +4 Forge Points and +1290 supplies.  The attacking and defenses boost are not showing.

![Boost Report](https://user-images.githubusercontent.com/63854576/79908830-f0df3500-83e9-11ea-956c-288c1d3da4c0.jpg)

**Comment by andrgin** [comment]
This overview does not show you attack/defense boosts.

What it shows you are FP, gold, supplies, medals, population, happiness and goods.

The category "boost" shows benefits of these resource that can not be traced back to a single building for example the boost on happiness you get from arranging set buildings in a certain way.

**Comment by noaquie** [comment]
Thank you.  I thought that all boosts were shown.
