### ISSUE TITLE
Kostenrechner - Name des Spielers nicht korrekt

### ISSUE THREAD

**Issue by JQuango** [dsiekiera/foe-helfer-extension#85]
Liebe Devs, 
mir ist aufgefallen, das wenn ich ein LB über einen "Link/als Anhang" im Chat betrete, der Name des Besitzers nicht korrekt angezeigt wird, der Name des LBs und die Plätze werden manchmal aktualisiert und manchmal auch nicht, konnte da noch keine Regelmäßigkeit feststellen. Betrete ich es über die Liste Legendäre Bauwerke des Spielers, hab ich dieses Problem nicht.
Möglicherweise ist es nicht möglich diese Information auf diesem Weg bereit zu stellen, oder der Kostenrechner ist nicht dafür gemacht sie auf diesem Weg abzurufen, was auch komplett ok wäre. Dann kann das Issue einfach geschlossen werden.
Falls das allerdings vorgesehen oder leicht anzupassen ist, wollte ich kurz darüber informieren.
Steps to reproduce: Lasst dir von einem Gildenmitglied/Freund ein LG als Anhang schicken. Öffne den Kostenrechner. Besuch ein LB eines anderen Spielers, z.B. Nachbars (Kostenrechner aktualisiert sich). Schließe das LB. Öffne das LB deines Freundes aus dem Chat.
LG Q

**Comment by dsiekiera** [comment]
Hallo JQuango,

alles korrekt erkannt. 
Das sieht man auch daran das beim öffnen eines LGs der eigentliche Spielername überhaupt nicht dargestellt wird. Das kann ich in der Extension nur wenn man über die LG-Liste (Übersicht) rein kommt. Dort steht auch der Namen drüber.

Wie du bereits erkannt hast, lässt sich das leider nicht anders lösen...
