### ISSUE TITLE
Typo(says tavernas when it should say Tavern)

### ISSUE THREAD

**Issue by DreadfulCadillac** [dsiekiera/foe-helfer-extension#851]
![download (2)](https://user-images.githubusercontent.com/64133047/79963758-ca57e300-8457-11ea-8a5a-e0e79d98678b.png)
Says Tavernas when it should say Tavern.
Also what is going on with everything saying Legendary building, when they are all called Great Buildings?
(I am a native english speaker by the way)

**Comment by scibuff** [comment]
Yeah, the LG is a direct translation from German (I was a bit confused about that myself at first)

**Comment by andrgin** [comment]
In German it is called "legendäre Gebäude" (legendary buildings). The mistake was simply translating from German to English instead of looking on the English wiki what the official English name is.

**Comment by DreadfulCadillac** [comment]
> In German it is called "legendäre Gebäude" (legendary buildings). The mistake was simply translating from German to English instead of looking on the English wiki what the official English name is.

Alright, thanks for adressing both of these translating issues!
