### ISSUE TITLE
falsche anzeige snipetool

### ISSUE THREAD

**Issue by ruqu911** [dsiekiera/foe-helfer-extension#86]
![image](https://user-images.githubusercontent.com/53529817/63082672-21133180-bf47-11e9-894e-18cdaabbbba0.png)

![image](https://user-images.githubusercontent.com/53529817/63082717-4011c380-bf47-11e9-9875-58796913cc09.png)

![image](https://user-images.githubusercontent.com/53529817/63082748-53bd2a00-bf47-11e9-9bd2-05b40eabc51d.png)

ist glaub ich problem mit 0-Anzeige...

**Comment by Selene443Foe** [comment]
Nabend :)

ich glaube mit der +- Null Anzeige haben wir uns irgendwie missverstanden mainline.

es sieht jetzt so aus, als ob man die Plätze sicher, aber ohne Gewinn belegen könnte.
In beiden Fällen würde das LB aber gelevelt bzw passten die Punkte nicht mehr rein.

![20 1](https://user-images.githubusercontent.com/50969949/63129233-50618700-bfb7-11e9-9875-b587eed1ee43.png)
![20](https://user-images.githubusercontent.com/50969949/63129234-50fa1d80-bfb7-11e9-8133-1eea858a4bbb.png)

**Comment by SamBrePy** [comment]
Ähnliche/vergleichbare Falschanzeigen habe ich in der letzten Zeit bei mir ebenfalls festgestellt!!

**Comment by dsiekiera** [comment]
Eine neue Formel berechnet das nun genauer und besser.
Sollte es genau auf `+-0 == Level` hinauslaufen erscheint der Gewinn nun orange.
