### ISSUE TITLE
Cost calculator wrong / falsch - amount of FP for a full Building / Total FP cost die GB ist falsch

### ISSUE THREAD

**Issue by Taunies** [dsiekiera/foe-helfer-extension#865]
First english - then German:
GB:
Hia - in the Costcalculator it shows an Ark from 37-38 to be with a total cost of 1937 FP but in fact the total cost is 1890 - thereby showing me to "snipe" with more FP than needed (969 instead of 945)
I don't know where to report it, but here it is.
Both languages are not "my own" and i have the english version installed

DE:
Servus - im "costcalculator" die Ark beim 37-38 zeigen ein preis falsch - 1937 und nicht 1890, damit das ich mit mehrere FP "sneipen" (schnepfe?) muss als nötig ( zeigt mir 969 und nicht nur 945)
Who dass zu schreiben weiss ich nicht, aber hier ist es =)
Beide sprache ist nicht mein muttersprache und ich habe den englischer version installiert

Hope this can be helpful / hoffe dass dieses nützlich werden kann.
 - Taunies

**Comment by Taunies** [comment]
i was looking in the Ark at a lvl before the last and then turned back to the latest level - somehow the ingame price then does not change from the level before showing the earlier levels price and not the resent levels actual price - sorry this was not a FoE helper issue - and i don't know how to delete this ticket again =) (ich habs in einem Ark die niveau frühere angeguckt und als ich zurück gegangen war zum aktuellen level den war de "total preize" vom letzten niveau angeshaut als die menge die aktuellen niveau auch brauchte - dass ist ja ein fehler ingame und nicht bei FoE helper, entschuldigung und wie ich dieses "ticket" wieder runterholen weiss ich aber nicht

Gretings - Viele Grüße
 - Taunies

**Comment by scibuff** [comment]
Yes, this is a known game issue

**Comment by dsiekiera** [comment]
All data to be expected comes directly from the game. We have no influence on it from a few formulas.
