### ISSUE TITLE
New feature: Attack buttons blocked on Rogue only army

### ISSUE THREAD

**Issue by mtgtnt** [dsiekiera/foe-helfer-extension#866]
This would add or remove a window to cover the "Auto Battle", "Attack" and "Start Next Battle" buttons in the case you only have Rogues in either the starting army and if a second wave, only Rogues left.

Far too many times I and the wife get into a rhythm and dont notice the non Rogue have died and sent the remaining, Rogue only, army onto their eminent deaths.

**Comment by osv** [comment]
hey, client have no information about selected army, only AFTER you click attack foe helper have info about attack army but it is too late! We can block attack button automatically for SECOND WAVE. For example you may need to close manually window and continue second battler (you can recover unit using premium goods...).

**Comment by mtgtnt** [comment]
Ok. So what you are saying is that on Second Wave you can know if there is only rogues alive and cover the 2 attack buttons?

**Comment by osv** [comment]
Yes, possible for second wave only

**Comment by mtgtnt** [comment]
That is good enough for me. That is probably where we mess up 99% of the time.

**Comment by andrgin** [comment]
If it is a 2 wave battle you need to put 2 real units in your army especially when using auto battle.

**Comment by mtgtnt** [comment]
Sometimes both of them die on the first wave. We can thank that lovely "Keen Eye" for that. It doesnt happen always, but when it does.... click... rogue slaughter :(

**Comment by osv** [comment]
@mtgtnt Comming soon... https://github.com/dsiekiera/foe-helfer-extension/pull/871

![attack](https://user-images.githubusercontent.com/213405/80279299-57739400-8705-11ea-887d-d7f6f9a15da5.jpg)

**Comment by mtgtnt** [comment]
@osv Thank you from both of us and anyone else that has killed defenseless rogues!
