### ISSUE TITLE
Suggestion: Display Opponent Information from PvP Activity log in separate window when attacking neighbors a second time

### ISSUE THREAD

**Issue by Niorian** [dsiekiera/foe-helfer-extension#867]
Considering your browser extension already saves all neighborhood combat details in the PvP activity log (opponent units and opponent combat bonuses), would it perhaps be possible to have these details displayed in a new, separate window when you are about to attack opponents a second time in the same neighborhood? This would make attacking the entire neighborhood for ranking points and plundering a lot more comfortable

I usually use the same army composition to attack my neighbors. For most neighbors, this composition works perfectly. However, there are a few opponents where my setup is hard-countered by the enemy. If I could see again the army composition of the time I last attacked the same neighbor again, I could tweak the army composition accordingly. As of now, I am using paper to write down difficult opponents that I faced. 

People usually don't change their defending army composition a lot, so this would help knowing which opponents are difficult, and which are not. 

Again, your PvP activity log is already displaying this information, so I suppose it shouldn't be super complicated to to this. Made a super awesome mockup of this quickly in Paint: 

![Mockup](https://user-images.githubusercontent.com/58807000/80256164-93174b00-867e-11ea-967d-ccb8ea41c7a0.jpg)

**Comment by scibuff** [comment]
This is already available, if you visit the player's city first --- the PvP data will load and show up. But I do agree, it would be nice not having to go through the city (that would save an extra click and a good amount of time)

**Comment by osv** [comment]
You need open plunder window, than if you enter to the opponent city you will see pvp player log
