### ISSUE TITLE
probleme mit kampfeinheiten

### ISSUE THREAD

**Issue by BlueAngel1975** [dsiekiera/foe-helfer-extension#870]
Hallo zusammen,

die letzte Zeit kommen nicht mehr die Anzahl an Einheiten zurück für die ich Kampfgebäude habe.
Hier haben noch mehrere Personen das Problem.

Gruß
Blue Angel

**Comment by andrgin** [comment]
Meinst du die Alcatraz Anzeige in der Armeeübersicht des Helfers? Daran arbeiten wir gerade.

**Comment by BlueAngel1975** [comment]
Ja. Ich habe die Anzahl an Einheiten vor dem nehmen der Einheiten aus dem
alca und danach verglichen. Waren identisch. Im foe Helfer.
Gruss
Blueangel



Gindi4711 <notifications@github.com> schrieb am Sa., 25. Apr. 2020, 21:09:

**Comment by andrgin** [comment]
Sollte gefixed sein
