### ISSUE TITLE
Infobox im FoE-Helfer, Add-on unter Google Chrome ist immer leer

### ISSUE THREAD

**Issue by flyingbetty** [dsiekiera/foe-helfer-extension#873]
Im Add-on des Helfers ist die Infobox immer leer.

**Comment by andrgin** [comment]
Die Infobox füllt sich nur bei bestimmten Ereignissen z.B. wenn man eine Nachricht erhält oder jemand in der Gex kämpft.

**Comment by flyingbetty** [comment]
Danke
