### ISSUE TITLE
Infobox im Add-on des FoE-Helfers immer leer

### ISSUE THREAD

**Issue by flyingbetty** [dsiekiera/foe-helfer-extension#874]
Im Add-on des Helfers ist die Infobox immer leer.

**Comment by Th3C0D3R** [comment]
Die füllt sich erst nach einiger zeit. Dazu muss sie offen sein. Sie zeigt dir an, wenn der Filter dafür aktiv ist, ob dich jemand zb beim Händler überboten hat, oder ob jemand, wenn aktiv, dein Handel angenommen hat

**Comment by flyingbetty** [comment]
Danke für die Info.
