### ISSUE TITLE
Kostenrechner Parser Fehler

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#88]
Moin,

in der aktuellen (und auch in der vorigen Version) ist ein kleiner, unwichtiger, aber doch zu beachtender Bug drinne.

Wenn man den Kostenrechner auf hat und ein LG z.B. über das Spielermenü öffnet, wird dieser sauber und vollständig ausgefüllt. Öffnet man ein LG allerdings über den geposteten Anhang in einer RM, wird der Spielername nicht erfasst, sprich es bleibt der Name des vorherigen LGs stehen.

**Comment by dsiekiera** [comment]
Das ist korrekt. Das ist auch technisch nicht anders möglich da die Zusatzdaten wie Spielernamen usw. aus der LG Übersicht "mitgenommen" werden.

Wenn mir mal echt langweilig ist, mach ich darüber noch mal einen Kopf 😉
