### ISSUE TITLE
New function suggestion - Forge Point Building Efficiency

### ISSUE THREAD

**Issue by 666shutter** [dsiekiera/foe-helfer-extension#881]
This could be a very useful function if you could quickly find which of the buildings in the city produce the smallest number of points per tile, something like this:
https://forgeofempires.fandom.com/wiki/Forge_Point_Building_Efficiency

This would allow you to quickly assess which buildings to remove first. It would also be a good idea to check if there are more efficient buildings in your inventory.

**Comment by osv** [comment]
Many prefer to know attack efficiency too

**Comment by dsiekiera** [comment]
I think we can easely create a new tab in the production module with both stats.

**Comment by andrgin** [comment]
I think production/tile could make sense for the other tabs as well.

For attack: This would be 4 new tabs. I think we should do 1 tab with a selction fiped with "all/attack_attack/attack_defense/defense_attack/defense_defense".

**Comment by whocares1111** [comment]
sorting the list by efficiency would also help. Note that some items have an efficiency when collecting per day (ie OPUS) as opposed to strictly tiles.

**Comment by andrgin** [comment]
Hhm yes this is a problem when comparing FP/tile

**Comment by osv** [comment]
I would like to have such info for neighborhoods too :)

**Comment by R3d-N4x3l4** [comment]
take a look at my feature wish too, runs in the same direction ;)
[https://github.com/dsiekiera/foe-helfer-extension/issues/862](url)
