### ISSUE TITLE
Eigenanteilsrechner merkt sich Schema nicht

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#89]
Im Eigenanteilsrechner kann man unter "Schema" auswählen, in welcher Form die in einer Mäzen-RM zu postenden Plätze formatiert werden sollen (z.B. "frank42 Alcatraz P1(314) P2(162)".
Problem ist nur, egal welches Schema aus dem dropdown ausgewählt wird, beim nächsten Aufruf des Rechners ist das vorletzte Schema "Name LG P5() P4() P3() P2() P1()" wieder vorausgewählt.

**Comment by dsiekiera** [comment]
Diese Option gab es nicht. Habe ich hinzugefügt.

**Comment by frank42hh** [comment]
Oh, cool, dankeschön :-)
