### ISSUE TITLE
foe-helfer: Probelme bei Statistik

### ISSUE THREAD

**Issue by thelmaLouis** [dsiekiera/foe-helfer-extension#892]
In der Moppel-Auswertung sind keine Daten seit dem 17.03.2020 vorhanden.

**Comment by andrgin** [comment]
Hast du alle Seite in Rathaus durchgeblättert?

**Comment by thelmaLouis** [comment]
Ja habe alle Seiten im Rathaus

**Comment by thelmaLouis** [comment]
Ja, habe alle Seiten im Rathaus durchgeblättert

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Gindi4711 <notifications@github.com>
Gesendet: Tuesday, April 28, 2020 9:45:39 PM
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: thelmaLouis <as-lahntal@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] foe-helfer: Probelme bei Statistik (#892)


Hast du alle Seite in Rathaus durchgeblättert?

**Comment by thelmaLouis** [comment]
Geht wieder. Danke für eure Mühe
