### ISSUE TITLE
Investitionen ausblenden. 

### ISSUE THREAD

**Issue by MasterMind179** [dsiekiera/foe-helfer-extension#9]
Auf der Seite

https://foe-rechner.de/invest/list

Wäre es toll, wenn Einträge ausblendbar wären. (Speicherbar!) Ich habe 2-3 Leute auf der Liste, da hab ich 1 FP drin und die sind seit Monaten inaktiv...P1 mit einem FP, dann wird mir ein Gewinn von mehreren hundert FP angezeigt, der verfälscht dann das total :-)

**Comment by dsiekiera** [comment]
Ok. Das macht Sinn. Ich werde jedoch das Ticket für die Entwicklung hier schliessen und im Repo der Webseite anlegen.
