### ISSUE TITLE
Produktions Übersicht

### ISSUE THREAD

**Issue by kneipenjaeger** [dsiekiera/foe-helfer-extension#90]
Guten Morgen, als erstes mal Danke ich Dir für dieses super Tool.
Bei der Produktions Übersicht fehlt das königliche Schiff. Sorry, es fehlt nicht, wird aber falsch angezeigt...
Die Münzangabe ist falsch...
LG 
Kneipenjaeger

**Comment by dsiekiera** [comment]
Falsch? Fehlt ein Bonus?

**Comment by kneipenjaeger** [comment]
Hallo, habe dieser Mail ein Screenshot beigefügt, guck mal.

 

Ansonsten Top Tool, wass Du da gemacht hast

 

Gesendet: Montag, 16. September 2019 um 13:10 Uhr
Von: "Daniel Siekiera" <notifications@github.com>
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: kneipenjaeger <r_spielmann@web.de>, Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Produktions Übersicht (#90)


Falsch? Fehlt ein Bonus?

**Comment by dsiekiera** [comment]
Von einer Mail aus kannst du leider kein Foto anhängen. Das geht nur direkt auf github.com.
Würdest das noch mal hochladen?

**Comment by kneipenjaeger** [comment]
![das schiff](https://user-images.githubusercontent.com/53101001/65017048-0c4f0280-d926-11e9-8c31-9ad0fd073e08.png)

**Comment by dsiekiera** [comment]
Alles klar. Gefunden und gefixt:

![Bildschirmfoto 2019-09-17 um 19-17-16](https://user-images.githubusercontent.com/834814/65064069-e5251f00-d97f-11e9-83eb-2e1b2e67fbd0.png)
