### ISSUE TITLE
New stats window too large

### ISSUE THREAD

**Issue by Rasnus** [dsiekiera/foe-helfer-extension#902]
Hello, the new stats windows opens up too large, no close button is visible. I can only refrsh my brower page to go back to game.

**Comment by dsiekiera** [comment]
How is U resolution?

**Comment by osv** [comment]
you even cannot move window? screenshot?

**Comment by Rasnus** [comment]
it's 1920x1080, but it's magnified at 125%. If I remove magnification and rstore 100% all it's fine but not at 125%.
Here is a screenshot:

![Capture](https://user-images.githubusercontent.com/64479706/80494017-74f36880-8966-11ea-90d4-78fcf2a6b5de.JPG)

**Comment by Rasnus** [comment]
no, I can't move the window as the top bar is not accessible

**Comment by osv** [comment]
Ah, right, height is too hight.. I will add fix soon - reduce height is height is <= 1080, in next update will be fixed
cc @dsiekiera

**Comment by dsiekiera** [comment]
I think overflow:auto would by the right way. Or?

**Comment by Rasnus** [comment]
thank you ;)
