### ISSUE TITLE
QUESTION - public api

### ISSUE THREAD

**Issue by patrikliska** [dsiekiera/foe-helfer-extension#907]
Hey guys, 
I wanna ask you if is here any Public API - for example endpoint with GB of guild members.

Thanks for your response

**Comment by andrgin** [comment]
There is no official API. What the extension is doing is reading the traffic that the Inno server sends to the browser.

**Comment by patrikliska** [comment]
Yes, i mean. If your web application is providing any info about

**Comment by andrgin** [comment]
We had some discussions, but decided to not do it. Main reason was potential legal issue (GDPR).

**Comment by patrikliska** [comment]
Oh, okay. thanks guys! closing this issue
