### ISSUE TITLE
Einstellungen SPEICHERN?

### ISSUE THREAD

**Issue by Andi47** [dsiekiera/foe-helfer-extension#909]
Bin gerade auf Beta - Sprache der Extension ist englisch (ich hatte die doch auf deutsch eingestellt??)

- Menüpunkt Settings gewählt, Sprache Deutsch ausgewählt, Menü geschlossen

--> und die extension ist wieder englisch

--> Menüpunkt Settings ausgewählt, Sprache Deutsch. suchen..... nein, da ist nirgends ein "Einstellungen speichern" Button?? Menü geschlossen

---> und die Extension ist NOCH IMMER englisch

gibt es eine Möglichkeit, nach dem Ändern der Einstellungen, diese auch zu SPEICHERN?

**Comment by Blackfir5** [comment]
Bei mir läßt sich Moment auch gar nichts speichern. Die Menülänge ändert sich ja auch nicht (das habe ich schon extra gemeldet).
Üblich wurde alles sofort übernommen. Wurde bei der Menülänge rauf, oder runter gedrückt, wurde sofort die länge geändert. Das Speichern vermutlich auch sofort. Einfach zu machen und es war gespeichert. Aktuell wird keine Änderung umgesetzt/gespeichert...

**Comment by Blackfir5** [comment]
Auch die Vorwarnung, dass ein update da ist und ob neu gestartet werden darf kam nicht :(

**Comment by scibuff** [comment]
Confirmed, please see #927
