### ISSUE TITLE
Tavernen Badge

### ISSUE THREAD

**Issue by Selene443Foe** [dsiekiera/foe-helfer-extension#91]
Guten Abend :)

Ein Spieler meldet mir, dass die Tavernen Anzeige (obwohl auf Null) in einer von drei Welten nicht mehr zu geht.
![27](https://user-images.githubusercontent.com/50969949/64738656-14570e80-d4f0-11e9-809b-37d1b28516c1.png)

**Comment by dsiekiera** [comment]
Kann es sein das dieser Spieler einen Fehler in der Konsole hat?

F12 und ist rechts außen an der Ecke eine rote Zahl? Wenn ja, bitte mal draufklicken und Meldung schicken.

**Comment by Galaxy72** [comment]
element.style {
}
body {
    position: absolute !important;
    height: 100% !important;
    width: 100% !important;
    overflow: hidden;
}
body {
    margin: 0;
    padding: 0;
    text-align: center;
    color: #ffffff;
    background: #0E1E2D;
}
user agent stylesheet
body {
    display: block;
    margin: 8px;
}
user agent stylesheet
html {
    color: -internal-root-color;
}
::-webkit-scrollbar {
    width: 5px;
    height: 5px;
}
::-webkit-scrollbar-thumb {
    background: #281207;
    border-radius: 10px;
}
background-attachment:scroll;
background-clip:border-box;
background-color:rgb(14, 30, 45);
background-image:none;
background-origin:padding-box;
background-position-x:0%;
background-position-y:0%;
background-repeat-x:;
background-repeat-y:;
background-size:auto;
color:rgb(255, 255, 255);
display:block;
height:657px;
margin-bottom:0px;
margin-left:0px;
margin-right:0px;
margin-top:0px;
overflow-x:hidden;
overflow-y:hidden;
padding-bottom:0px;
padding-left:0px;
padding-right:0px;
padding-top:0px;
position:absolute;
text-align:center;
width:469px;
﻿
chrome-extension://b…ern.js?v=2.3.7.1:67 Uncaught ReferenceError: moment is not defined
    at Object.CheckTavernBoost (chrome-extension://b…ern.js?v=2.3.7.1:67)
    at chrome-extension://b…rn.js?v=2.3.7.1:190
﻿
​

**Comment by dsiekiera** [comment]
Ich hab eine Zwischenprüfung eingebaut um diesen Fehler nicht zu erzeugen. 
Kommt im nächsten Update.

**Comment by Selene443Foe** [comment]
Schau mal, dass hier sind die Meldungen:
![28](https://user-images.githubusercontent.com/50969949/65346580-4b5aad80-dbdd-11e9-9c07-9047068bc649.png)
