### ISSUE TITLE
Militär Einheiten Überischt Statistik Fehler

### ISSUE THREAD

**Issue by TachTach** [dsiekiera/foe-helfer-extension#911]
Tabellen Fehler in der Stündlichen Einheitenübersicht in der Verbindung mit der Ägypten Siedlung. Da man in dieser keine anderen Einheiten besitzt, denkt die Statistik das man alle in dieser Stunde verloren hat bzw alle danach wieder Produziert hat.
![TdgNjQ3](https://user-images.githubusercontent.com/12811212/80528835-dcc1a780-8996-11ea-923c-9701498fa99c.png)

**Comment by TachTach** [comment]
![3ujVZi9](https://user-images.githubusercontent.com/12811212/80529543-e992cb00-8997-11ea-873b-0ac30cb5a50f.png)

**Comment by osv** [comment]
I will fix it later, because I need to finish my "japan"

**Comment by SkateScout** [comment]
Hi, is there any update?  Filter exclude extra units from cultural cities ?
