### ISSUE TITLE
Plunder window missing

### ISSUE THREAD

**Issue by AmanoJaku77** [dsiekiera/foe-helfer-extension#915]
Since the latest update, when I visit a neighbor, the window with buildings ready to plunder does not show.

**Comment by andrgin** [comment]
1.) Do you have the neighbourhood harvest enabled in settings?
2.) Did you try resetting box coordinates?
3.) Can you look if there are exceptions in the developer console (press F12 and go to tab "Console")?

**Comment by AmanoJaku77** [comment]
I discovered the problem, it was at my end. I have been busy the last few days, but realized the plunder window was only missing when I visited friends or Guild who happened to be in my neighborhood. I apologize for any trouble or confusion I caused.
