### ISSUE TITLE
Statistik: GEX Belohnungen "seit Dienstag" ohne Dienstag

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#917]
Moin,
Erst mal eins vorweg: Ich habe mich unheimlich gefreut über das Statistik Modul, ich finde es klasse.
Leider scheint es noch ein paar Kinderkrankheiten zu haben. Was mir heute aufgefallen ist:
"Belohnungen -> GEX -> Seit Dienstag" beinhaltet "Dienstag" nicht.

Ich habe gestern Mittag, nach der Installation des Updates, die GEX gestartet. Ich habe gestern belohnungen erhalten, und die wurden gestern auch angezeigt.
Heute bin ich auf der Karte weitergegangen und habe weitere Belohnungen erhalten. Allerdings werden nur die heutigen angezeigt, nicht die von Gestern. Wenn ich auf "Belohnungen -> GEX -> letzten 7 Tage" gehe, werden die von gestern mit angezeigt.

![GEX-Stats-2](https://user-images.githubusercontent.com/17932878/80584035-6746ed00-8a11-11ea-88c5-4862ceb87ffd.jpg)
![GEX-Stats-1](https://user-images.githubusercontent.com/17932878/80584037-67df8380-8a11-11ea-9fed-6f2c18912abe.jpg)

**Comment by andrgin** [comment]
Fixed in 2.5.0.1

**Comment by frank42hh** [comment]
Moin, 2.5.0.1 ist nun installiert, aber irgendwie scheint da immer noch irgendwas falsch zu sein.
Es ist Dienstag, 10:20 Uhr. Ich habe die GEx noch nicht betreten, trotzdem liefert mir das Modul ein Ergebnis:

![Anmerkung 2020-06-30 102223](https://user-images.githubusercontent.com/17932878/86102299-9e8e5480-babb-11ea-83a8-29855bbc7d39.png)

Das spannende daran: Das kann unmöglich das Ergebnis von "seit Dienstag" sein, weil "seit heutigem Dienstag" müsste null sein, und "seit letzte Woche Dienstag" müsste deutlich mehr sein als ein Einlagerung-Kit. Und dann kommt noch dazu, dass ich in der vergangenen GEx gar kein Einlagerungs-Kit eingesammelt habe.

**Comment by frank42hh** [comment]
Noch zwei Screenshots vom heutigen Dienstag, nach 9 Begegnungen in der GEX, einmal "heute":
![Anmerkung 2020-06-30 164629](https://user-images.githubusercontent.com/17932878/86140560-45411800-baf1-11ea-850e-6e7fbba78f17.png)

und einmal "seit Dienstag"
![Anmerkung 2020-06-30 164703](https://user-images.githubusercontent.com/17932878/86140631-57bb5180-baf1-11ea-8583-b0598d55d0ec.png)

Morgen schiebe ich hinterher, wie es sich an einem Mittwoch darstellt mit diesen Einstellungen

**Comment by GeniusTimo** [comment]
Das Problem sind Lokalzeit, Serverzeit, ... Auf welchem Server spielst du und in welcher Zeitzone lebst du?

**Comment by frank42hh** [comment]
Moin Timo,

on 2020-06-30 at 17:01:47 CEST, you wrote:
> Das Problem sind Lokalzeit, Serverzeit, ... Auf welchem Server spielst du und in welcher Zeitzone lebst du?
> 

de16, dementsprechend Europe/Berlin, also UTC+2.

Aber wie kann die Uhrzeit da relevant sein, wenn das Teil "x Tage zurück"
rechnet?



Mit freundlichen Grüßen

	Frank Altpeter

-- 
FA-RIPE || http://about.me/frank.altpeter/
| Two clowns are eating a cannibal. One turns to the other and says "I think we got this joke wrong"

**Comment by GeniusTimo** [comment]
Danke @dsiekiera 🙂 Wegen den Statistiken muss man mal schauen...

**Comment by frank42hh** [comment]
de16, dementsprechend Europe/Berlin, also UTC+2.

Aber wie kann die Uhrzeit da relevant sein, wenn das Teil "x Tage zurück"
rechnet?

**Comment by GeniusTimo** [comment]
Muss man sich anschauen, braucht ohnehin eine Überarbeitung (GG startet Donnerstags)

**Comment by frank42hh** [comment]
So, wie versprochen, heute nochmal ein paar Runden GEx gemacht, mit diesem Ergebnis:

Anzeige für "heute" ist korrekt:
![Anmerkung 2020-07-01 133203](https://user-images.githubusercontent.com/17932878/86239266-46c91980-bb9f-11ea-9441-462568724354.png)

Die Anzeige "seit Dienstag" zeigt nur die heute gesammelten Belohnungen ein und ignoriert die von gestern.
![Anmerkung 2020-07-01 133240](https://user-images.githubusercontent.com/17932878/86239324-5d6f7080-bb9f-11ea-982d-74ec92e38d5f.png)

**Comment by andrgin** [comment]
So habe mir das noch einmal angesehen:

moment().startOf('week') liefert je nach Regionaleinstellung entweder Sonntag 0 Uhr (amerikanischer Kontinent) oder Montag 0 Uhr (Europa/Asien)
moment().startOf('isoWeek') liefert immer Montag 0 Uhr

Ursprünglicher Code:
moment().startOf('week').add(2, 'days').toDate() liefert entweder Dienstag 0 Uhr (amerikanischer Kontinent) oder Mittwoch 0 Uhr (Europa/Asien)

Code in Version 2.5.0.1:
moment().startOf('isoWeek').add(2, 'days').toDate() liefert immer Mittwoch 0 Uhr (Montag 0 Uhr + 2 Tage weiter)

Neuer Fix:
moment().startOf('isoWeek').add(1, 'days').toDate() liefert immer Dienstag 0 Uhr (Montag 0 Uhr + 1 Tag weiter)

**Comment by GeniusTimo** [comment]
Ah, dann hatte ich das vertauscht - aber gut.. fast 😅

**Comment by frank42hh** [comment]
Trotzdem Danke! :-)
Dann bin ich mal gespannt auf die nächste Version :)

**Comment by dsiekiera** [comment]
Das darfst du sein. Dort kommt nämlich auch direkt ein Datepicker mit und die Ansicht wurde überarbeitet.

**Comment by frank42hh** [comment]
Datepicker? Wie genial! Ein Punkt, den ich eigentlich noch ansprechen wollte, war die Auswahl der vorgegebenen Zeiträume... weil gerade wenn man monatliche Statistiken erfassen will, wäre neben "Dieser Monat" nämlich ein "Voriger Monat" praktisch (damit man nicht immer am Monatsletzten alles notieren muss und einen Tag später die Statistik nicht mehr notierbar ist).
Aber ein Datepicker macht das natürlich deutlich angenehmer :)

**Comment by dsiekiera** [comment]
Der Datepicker kommt erst in der nächsten Version.
