### ISSUE TITLE
Produktions Übersicht Sortier Fehler

### ISSUE THREAD

**Issue by Vloxxity** [dsiekiera/foe-helfer-extension#92]
In der Produktions Übersicht ist die Sortierung fehlerhaft!
Ich glaube das Problem liegt daran dass du die Werte in deutscher Formatierung mit Tausender-Punkt anzeigst der aber beim Sortieren als US-Dezimaltrennzeichen erkannt wird!
![image](https://user-images.githubusercontent.com/7673506/64860684-2a6ae900-d62e-11e9-9874-262385e88e06.png)

**Comment by dsiekiera** [comment]
![Bildschirmfoto_2019-09-16_14-35-34](https://user-images.githubusercontent.com/834814/64958382-4a4d1780-d88f-11e9-9dc2-f834f736b80b.png)

Ist angepasst.

**Comment by Vloxxity** [comment]
Tritt bei mir immer noch so auf.
Ich hab jetzt 2 von denen stehen da tritt der Fehler in der gruppierten Ansicht nicht mehr auf da es somit über 1.500 (was wegen Konversionfehler glaub ich als 1,5 jetzt sortiert wird statt vorher 700)
In der Einzelansicht stehen die beiden aber immer noch oben!
Hast du irg nen Gebäude mit unter 1.000 Vorratsproduktion?
Falls nicht tritt der Fehler halt nicht auf wenn das was ich Denke der Grund für den Fehler ist!
![image](https://user-images.githubusercontent.com/7673506/64999215-3503d780-d8e7-11e9-8f51-fee5513d78ab.png)
![image](https://user-images.githubusercontent.com/7673506/64999233-45b44d80-d8e7-11e9-90bf-76db70aacb45.png)

**Comment by dsiekiera** [comment]
Nu aber. Hab das noch mal umgestellt. Die Punkte werden ab sofort beim filtern ignoriert.
Hab extra noch mal ein paar Schmieden angeworfen ;-)

![Bildschirmfoto_2019-09-17_17-09-08](https://user-images.githubusercontent.com/834814/65054648-33312700-d96e-11e9-86c2-ae3bf9c17947.png)
