### ISSUE TITLE
google chrome crash

### ISSUE THREAD

**Issue by ddeudon** [dsiekiera/foe-helfer-extension#921]
Hi
Since the foe-helper tool has been installed, why google chrome nagivator crashes around 1 time every 10 minutes and not only where playing FOE.
When the tool is deactivated, no more crash.
My OS: opensuse (linux).
How can I help ?

**Comment by osv** [comment]
browser version? chromium? 
Does it crash even if only one page is opened - FOE?

**Comment by osv** [comment]
Ah not, you wrote "chrome navigator"

**Comment by ddeudon** [comment]
Google chrome - Version 72.0.3626.119 (Build officiel) (64 bits).
Crash at any moment, when starting (no pages opened)

**Comment by ddeudon** [comment]
*even when starting...

**Comment by kwhelan1** [comment]
Version 72 of chrome is 14 months old.    Unless there is a compelling reason not to upgrade(another app that requires the older version) I would upgrade that immediately.  Not only is it old but running any software especially a browser is a severe security risk when it is not kept updated.

Disclaimer: I am just another user,  not a developer here.

**Comment by ddeudon** [comment]
I upgrade as soon as asked... I will check but that means that this version is the one distributed by my OS...
thks

**Comment by osv** [comment]
You still can try install latest google chrome from https://www.google.com/intl/en/chrome/
just select RPM. Pls write here if newer version does not work for you too...

**Comment by andrgin** [comment]
This seems more like a Chrome bug to me because the Extension is not active on other pages except for the icon in the menu bar, but I am not sure because we only test the current browser versions when doing changes.

Btw. my Windows 7 PC was shipped with Internet Explorer 8, so I guess the argument "was shipped with the OS" should not be an excuse.

**Comment by ddeudon** [comment]
You are right, my repository was "corrupted".
Google chrome is now updated... Version 81.0.4044.129 (Build officiel) (64 bits)
Let check if crashs are still there.
Thks

**Comment by ddeudon** [comment]
No crash since google chrome has been updated.
Many thks

**Comment by ddeudon** [comment]
thks

**Comment by ddeudon** [comment]
thks
