### ISSUE TITLE
some strings in json files are not parsed correctly

### ISSUE THREAD

**Issue by enkidu** [dsiekiera/foe-helfer-extension#924]
In the statistics window strings with escaped double quotes are trimmed to the position of double quote. However, in the tooltip of "Messages" button double quotes are displayed correctly.

**Comment by osv** [comment]
pls screenshot?

**Comment by enkidu** [comment]
So, there are two floating messages, created with following lines:
`"Boxes.Stats.BtnAllTittle": "Epoki + \"bez epoki\" + specjalne"
"Menu.Info.Desc": "Informacja o wszystkich zdarzeniach \"w tle\"<br><em>Aktualizuje się na bieżąco ...</em>"`
![Screenshot 2020-05-01 22:10:19](https://user-images.githubusercontent.com/66652/80838219-d29ee380-8bf8-11ea-823b-27c3e439c185.png)
![Screenshot 2020-05-01 22:09:04](https://user-images.githubusercontent.com/66652/80838220-d468a700-8bf8-11ea-9366-df35cdcd2758.png)

**Comment by andrgin** [comment]
Fixed in next update
