### ISSUE TITLE
Statistics Tab: Guild Cash

### ISSUE THREAD

**Issue by Buzz30** [dsiekiera/foe-helfer-extension#926]
Hello
Thank you for adding the statistics tab.
Regarding the guild treasury, would it be possible to integrate the monitoring of:
- The contribution of the Great Guild Monuments (Arch, Observatory, Atonium)
- The contribution of donations from members of the guild.
- The contribution of the Statues of Honor.
This would allow better tracking of cash in the Guild Battlefield.
Thank you for your work.

**Comment by scibuff** [comment]
This is not really possible

- this would require getting the list of each guild player GBs on regular basis, but even that doesn't really tell you if they collect the production (so we could only estimate)
- there's no game data about this
- this would require visiting each guild player's city on regular basis, and that would only give you the number and level of SoH. Again, there's no way to track the collection so the contribution from SoH can be only estimated

**Comment by Buzz30** [comment]
Thank you for these responses

**Comment by andrgin** [comment]
There is an ingame log of guild treasury, but you would have to scroll through all pages which would be a real pain and data would be incomplete if you miss a few pages, so it does not make much sense.

**Comment by PompDaddy** [comment]
Is it possible then, to collect the data that is present in the guild treasury log (all current pages), and display it in the new Statistics tab, and allow an export to Excel, CSV etc.?  This would help immensely in record keeping of treasury donations and expenditures.

**Comment by PompDaddy** [comment]
@scibuff 
I do not agree that this is not possible.
I am not familiar with JSON, but after looking around with Dev Tools, I was able to locate the XHR file (JSON response), and it includes all the data of the Guild Treasury Contributions (player donations, GB donations, other building's donations, and GE costs, and GbG costs etc..).  if you are not familiar with these logs (Global>Your Guild>top left menu>Guild contributions).

Under the "Dev Tools" Network tab, whenever i open the above page, i get a response similar to:  
https://us7.forgeofempires.com/game/json?h=UU8yrlXYbSjUIZaFm0YBDFEz

Getting all pages of this log to be included in your statistics, and allowing to export to CSV would save our treasurer, countless hours per week of manually inputting all 400+ pages of all our guild members' donations, their GB donations, and other costs.  Thank you for any reconsideration

**Comment by WannaKissU** [comment]
This is the best idea I've heard. This would be amazing if we could sum up the contribution log file.
I am not aware what is involved but I would love to have this information coming from foe rechner.

@scibuff : Do you think this could be done from the contribution log file ?

**Comment by andrgin** [comment]
We have an export to csv feature planned for next update.
