### ISSUE TITLE
Produktions Übersicht Tabellen doppelt/mehrfach!

### ISSUE THREAD

**Issue by Vloxxity** [dsiekiera/foe-helfer-extension#93]
Die Tabellen in der Produktionsübersicht werden beim Schliessen der Übersicht und neu Öffnen neu hinzugefügt statt zu aktualisieren und dabei die alten aber auch nicht gelöscht,
sodass sie doppelt oder mehrfach da sind!
Sieht man nur im Sourcode im Inspektor da die sich gegenseitig überlagern ;)
![image](https://user-images.githubusercontent.com/7673506/64865647-13ca8f00-d63a-11e9-90b1-ee978ba2f643.png)
![image](https://user-images.githubusercontent.com/7673506/64865681-23e26e80-d63a-11e9-9062-dd91ecb96f28.png)

**Comment by dsiekiera** [comment]
Gefunden und behoben.
