### ISSUE TITLE
Active Friends

### ISSUE THREAD

**Issue by stevecook428** [dsiekiera/foe-helfer-extension#930]
Is there a clever method within the tool to determine which friends are active?  Always trying to have active friends is challenging and time-consuming.

**Comment by andrgin** [comment]
You can activate Upload to foe-rechner.de and create an account there. Then go to Statistics - Motivieren/Polieren (sorry not translated yet) and Motivation report.

**Comment by stevecook428** [comment]
Nice, I have enabled this feature, it looks very exciting.  It throws a fatal error immediately when attempting to pull a report, is this due to there being no collected data?



Fatal error: Uncaught ADODB_Exception: mysqli error: [-9999: Input array has 3 params, does not match query: 'SELECT DISTINCT YEAR(opse.date_visit) AS Jahr, WEEK(opse.date_visit,1) AS Spalte FROM other_players_service_us14 as ops LEFT JOIN other_players_service_entries_us14 as opse ON ops.ops_id = opse.ops_id WHERE ops.player_id = ? AND ops.is_friend = 1 AND opse.visitor_action = 'friend_tavern_sat_down' ORDER BY opse.date_visit DESC LIMIT ? '] in Execute(, ) in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(786): adodb_throw('mysqli', 'Execute', -9999, 'Input array has...', '', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1168): ADOConnection->outp_throw('Input array has...', 'Execute') #2 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1807): ADOConnection->Execute('SEL in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by belikoviv** [comment]
> You can activate Upload to foe-rechner.de and create an account there. Then go to your town hall and open the event tab and scroll through all pages. On the foe-rechner.de Homapageo go to Statistics - Motivieren/Polieren (sorry not translated yet) and Motivation report.

foe-rechner.de is useless without translation.
