### ISSUE TITLE
Option to disable estimated bonus attack / defense

### ISSUE THREAD

**Issue by szurabura** [dsiekiera/foe-helfer-extension#931]
At some point (+617% / +338% here) defense stats are irrelevant since I'm autoattacking and not paying any attention to their defense, so it's only taking space that I'd rather have for longer list of lootable objects.

**Comment by andrgin** [comment]
This features was removed completely: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
