### ISSUE TITLE
(Bug) Info Box 

### ISSUE THREAD

**Issue by szurabura** [dsiekiera/foe-helfer-extension#939]
There's bug with Info Box stating wrong number of FP gained. I've gained 10FP as per my investment (5pr * 1,9), not 30 as stated in Info Box.

![bug](https://user-images.githubusercontent.com/64558520/80725671-abb2b580-8b03-11ea-8c88-e3bf807324dd.JPG)

**Comment by andrgin** [comment]
Yes this is a known bug.

**Comment by whocares1111** [comment]
Not sure if this is part of the same issue, but when displaying events in the Info box window, Auction events are displayed as "Auktion" and GE events as "GEX" although the filter drop down list is pulling the correct header from the json

**Comment by whocares1111** [comment]
Also, my events do not appear in the InfoBox, specifically noted was GE events

**Comment by MrMattn** [comment]
weiterer Fehler...warum bleiben die Häkchen nicht draussen die man raus nimmt?
Nach jedem neuen Öffnen der Box sind sie wieder da

**Comment by scibuff** [comment]
This is now fixed on Beta (#1107) and will be in the next release
