### ISSUE TITLE
Außenposten geht nicht und vielleicht Fehler im Kostenrechner

### ISSUE THREAD

**Issue by Kooony** [dsiekiera/foe-helfer-extension#94]
Ich habe einen neuen Rechner und hab alles neu installiert. Leider geht der Außenpostenrechner nicht. Egal was ich mache.
Und beim Kostenrechner hab ich heute festgestellt, das mir Plätze zu belegen angezeigt werden, die schon längst mit mehr FPs von anderen belegt worden sind.
Schade, ich nutze das Tool echt gerne

**Comment by dsiekiera** [comment]
Schau ich mir an. Nicht verzweifeln 😉

Kooony <notifications@github.com> schrieb am Fr., 13. Sep. 2019, 21:45:

**Comment by dsiekiera** [comment]
Außenposten sollte mit der Version 2.3.7, die bei Google gerade zur Prüfung liegt, sauber funktionieren.
