### ISSUE TITLE
Info box 

### ISSUE THREAD

**Issue by ketjow09** [dsiekiera/foe-helfer-extension#948]
Windows 10 64 Bit
Chrome 
pl3 
2.4.5 - English

My info box is always empty, doesn't show any messages
![image](https://user-images.githubusercontent.com/64632635/80801248-04d62400-8bac-11ea-8485-115d5d79249e.png)

**Comment by scibuff** [comment]
Please use the [template](https://github.com/dsiekiera/foe-helfer-extension/issues/620)

**Comment by scibuff** [comment]
Are there any errors in the console (press F12 and click on the "Console" tab)

**Comment by ketjow09** [comment]
Somethink like that: ![image](https://user-images.githubusercontent.com/64632635/80828423-8ac29100-8be5-11ea-9b9e-ddf65820886e.png)
How to fix it?

**Comment by scibuff** [comment]
The Facebook one looks like an adblocker but that has no effect on the plugin. Just to confirm, you don't get any message or other info even after you leave the InfoBox open for a long time (it is empty by default when you open it)?

**Comment by ketjow09** [comment]
Yes, it's empty since I had install foe helper. I am opening it and leaving it minimalized like that : 
![image](https://user-images.githubusercontent.com/64632635/80838514-7e483380-8bf9-11ea-8bcf-7ef207d14294.png)

**Comment by andrgin** [comment]
1.) Can you please use the bug report template as it seems to be a compatibility issue with your system/browser/language settings etc.. Do you have an updated browser?

2.) Did you try reloading the extension in browser settings?

**Comment by ketjow09** [comment]
Windows 10 Education 64 Bit
Chrome Wersja 81.0.4044.129  (64-bitowa)
pl3 (Cirgard)
Foe-helper 2.4.5 English (because I can't change to polish)  '
Do you need any other information?

**Comment by andrgin** [comment]
1.) In More tools => Extensions you see a list of all Chrome Extensions. Click on the refresh icon so it gets reloaded.

But you can try uninstalling and installing the Extension again as well.

2.) Did you open the console (F12) before or after you opened the infobox?

**Comment by ketjow09** [comment]
Ok, I uninstaled it and instal again and it works now. Thank you
