### ISSUE TITLE
Gbg attrition.

### ISSUE THREAD

**Issue by c01mic** [dsiekiera/foe-helfer-extension#949]
I have a suggestion for gbg. Is it possible to show what attrition  members of my guild have currently?

**Comment by scibuff** [comment]
This data is not available so the plugin cannot display it.

The only possibility would be to show the attrition of those guild members who are using the FoE-Helper plugin (and it would have to be done through sharing the data on the server)

**Comment by c01mic** [comment]
Exactly. I mean, using the plug.
So, at this point in time, unattainable, I conclude from your earlier comments.
