### ISSUE TITLE
Kann die Werte aus dem LG Rechner nicht mehr kopieren

### ISSUE THREAD

**Issue by Elschen** [dsiekiera/foe-helfer-extension#95]
Die Werte aus dem Eigenanteilsrechner lassen sich nicht mehr kopieren :-( (seit heute auf mehreren Rechnern und Welten).

**Comment by gerrybass** [comment]
ja, leider gehts auch wieder mit dem kostenrechner los.... alle cache gelöscht... nix funzt ...

**Comment by dsiekiera** [comment]
Werte kopieren? Warum sollte man das können?

Der Kostenrechner wurde nicht angetastet. Vermutlich liegt das an etwas anderem. Wenn Du das Spiel mit offener Konsole (F12) startest. Haste dann rechts außen eine rote Meldung?

**Comment by Elschen** [comment]
Im Eigentanteilsrechner gibt es doch extra eine Funktion "Werte kopieren", damit ich die Plätze und geforderten FP in der Förderrundmail posten kann - und das funktioniert nicht.

**Comment by dsiekiera** [comment]
Oh-ja. Hab das gefixt. Da war ein Selector verrutscht. Fix kommt in der 2.3.7.1

**Comment by Hummelchen74** [comment]
Hab auch seit heute das gleiche Problem. 
:(

**Comment by dsiekiera** [comment]
Ich mach das Update fertig. Bei mir geht schon wieder alles.
