### ISSUE TITLE
Possible deposits in Firefox not opening

### ISSUE THREAD

**Issue by redsky5867** [dsiekiera/foe-helfer-extension#951]
In the Possible deposits of the cost calculator on the Firefox platform the screen is not extending to show any possible GBs to research.  

![image](https://user-images.githubusercontent.com/64625326/80830535-1f61ca80-8bb7-11ea-90af-2823ded61de6.png)

**Comment by andrgin** [comment]
Can you please use the bug report template. Maybe you are using an outdated browser?

**Comment by andrgin** [comment]
Closing this one because you already have an issue created here: https://github.com/dsiekiera/foe-helfer-extension/issues/943
