### ISSUE TITLE
Attack/Defense stats for everyone

### ISSUE THREAD

**Issue by DJKC123** [dsiekiera/foe-helfer-extension#952]
I like the att/def stats for people in the neighborhood but I want it for everyone...guildmates, friends, anyone searched globally.  That would be a great addition.

Great product.  Played 7 years without it.  Wish I would have known about it sooner!

**Comment by osv** [comment]
@DJKC123 it possible even now. Not official way but you can open dev console (press F12) then enter in console `UseReaderOnAllPlayers=1`, now if you can visit guildmate, etc and see his att/def stts
