### ISSUE TITLE
Mauvaise traduction

### ISSUE THREAD

**Issue by SdQY78** [dsiekiera/foe-helfer-extension#955]
Dans l'écran "Vue des ressources - Egypte antique", mauvaise traduction de "Butins" (dernière colonne du tableau)

Operating System: Windows 10 Famille 64-bit (10.0, Build 18362) (18362.19h1 release.190318-1202)
Language: French (Regional Setting: French)

Google Chrome est à jour
Version 81.0.4044.129 (Build officiel) (64 bits)
![Colonie égyptienne](https://user-images.githubusercontent.com/61630674/80862631-c8232f00-8c76-11ea-8ed7-09f073c128bc.png)

**Comment by andrgin** [comment]
We get the text "Mais en" directly from the Inno server, so it is a translation error on their side.

**Comment by SdQY78** [comment]
Ok ! merci de votre réponses.
