### ISSUE TITLE
GB Overview - Wish list

### ISSUE THREAD

**Issue by nryan2wc** [dsiekiera/foe-helfer-extension#957]
One thing I love is to see the "great buildings progress" bar for my investments, but would love to also see something similar for my own great buildings, a quick glance at which are the closest to leveling / where neighbors are throwing FP onto.

**Comment by andrgin** [comment]
We do not have the ranking information (which player paid how many FP) available until each individual GB is opened, so I dont see any useful information we could show that the ingame overview does not already have.

**Comment by nryan2wc** [comment]
I'm not sure that it needs to be "which player paid how many FP", but more of a "which GB is closest to leveling". A progress bar for my GB's like what Inno does for GB's that i've invested FP on. So what i envision is a list of my GB's, with bars that then look like this:

![image](https://user-images.githubusercontent.com/26188475/80909026-d3b43b80-8cf2-11ea-8da7-f9784dab4ec9.png)

So a display would be
GB - Level - Progress
GB - Level - Progress

**Comment by andrgin** [comment]
Go to the neighbors/friends/guild tab and search for your own name. Then click on the GB overview button and you have exactly this list.

**Comment by nryan2wc** [comment]
Wow, I've been playing a while, and have never actually clicked on my name. Thank you for dealing with my nonsense. I'm sorry to have bothered you :)
