### ISSUE TITLE
Stadtübersicht / Town schematic view

### ISSUE THREAD

**Issue by Leuselator** [dsiekiera/foe-helfer-extension#959]
Chrome on OSX:
Dropdowns für Perspetive / Zomm wirkungslos...
Dropdowns for view/perspective w/o function...

**Comment by andrgin** [comment]
Welche Chrome Version hast du genau?

**Comment by Leuselator** [comment]
Version 81.0.4044.129 (Offizieller Build) (64-Bit)


Von: Gindi4711 <notifications@github.com>
Antworten an: dsiekiera/foe-helfer-extension <reply@reply.github.com>
Datum: Sonntag, 3. Mai 2020 um 03:05
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: Tim Leuschner <mail@leuselsoft.de>, Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Stadtübersicht / Town schematic view (#959)


Welche Chrome Version hast du genau?

**Comment by torben-w** [comment]
Habe das gleiche Problem. Version ist ebenfalls Version 81.0.4044.129 (Offizieller Build) (64-Bit). Aber auf Windows 10.

**Comment by andrgin** [comment]
Ist mit dem letzten Update gefixed worden
