### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by jetwitaussi** [dsiekiera/foe-helfer-extension#96]
Hello,
Thanks for your extension, this is very great!
Problem, my german is not very good :)
Can you imagine an english version? Then people may translate it to others languages easily

Thanks

**Comment by dsiekiera** [comment]
Hey jetwitaussi,

I have just submitted an English version in the Chrome Webstore. The new Version would be 2.3.8.
If you find unsightly translations, please contact me immediately so that I can fix it.

Regards, Daniel

**Comment by jetwitaussi** [comment]
I will look at it.
When really ready, it would be great to have english as default fallback. Currently my browser has french language on top, then i still got german ;)

Thanks

**Comment by jetwitaussi** [comment]
Found german labels:
Mäzen Anteil, Platz : https://www.dropbox.com/s/v1ig66vcra33033/Capture%20d%27%C3%A9cran%202019-09-19%2013.11.43.png?dl=0

Lager: https://www.dropbox.com/s/wlsynq62tot0e4r/Capture%20d%27%C3%A9cran%202019-09-19%2013.18.54.png?dl=0

Gesamt, Uhr, Stunden: https://www.dropbox.com/s/9o13tjzw1hg6tr1/Capture%20d%27%C3%A9cran%202019-09-19%2013.30.17.png?dl=0

**Comment by dsiekiera** [comment]
If u want u can download the [english](https://github.com/dsiekiera/foe-helfer-extension/raw/master/js/web/i18n/en.js) file version and translate it o french.

Send it back and i install it immediately. That would be wonderful!

**Comment by jetwitaussi** [comment]
You have a PR https://github.com/dsiekiera/foe-helfer-extension/pull/98 :)

**Comment by dsiekiera** [comment]
Hi jetwitaussi

Yesterday I entered a few missing translations in the source code and completely internationalized the app this morning. It will now also be displayed in French in the Extension overview, as well as in the Chrome Webstore.

Thank you for your help. And as soon as you find a mistake, please write to me immediately.

Your new version is 2.3.9

Regards, Daniel

**Comment by jetwitaussi** [comment]
Great, i will update the file and send a new PR
