### ISSUE TITLE
Idea: grafischer Förderrechner /graphical investment calculator

### ISSUE THREAD

**Issue by Leuselator** [dsiekiera/foe-helfer-extension#960]
Ich habe einen graphischen Förderrechner in js programmiert. Gern gebe ich Zugang zur Website, um ihn zu begutachten. Mit ein wenig Starthilfe (wie kann ich meinen Fork dieses RePo's in meinem Chrome zum Testen installieren) würde ich ihn in den FoE-Helfer integrieren (was ein wenig dauern würde...)

I've coded a graphical investment-calculator in js. I'd love to grant you access to the sit it resides on so you may get an idea of it. With a lill' help from you (how may I install the fork of this repo into my browser for testing) I'd integrate it into FoE-helper (what might take a while...)

**Comment by andrgin** [comment]
Wäre gut, wenn du einmal einen Link zu der Seite posten könntest, damit wir uns das einmal ansehen können.

**Comment by Leuselator** [comment]
Hi Daniel – hatte Dich vor ein paar Tagen versucht über Facebook zu kontaktieren – sorry dafür...

Zum Anschauen:

https://www.cookiecrew.de/forums/topic/rechner/

User: Daniel
PW: cookiecrew



Von: Gindi4711 <notifications@github.com>
Antworten an: dsiekiera/foe-helfer-extension <reply@reply.github.com>
Datum: Sonntag, 3. Mai 2020 um 02:54
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: Tim Leuschner <mail@leuselsoft.de>, Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Idea: grafischer Förderrechner /graphical investment calculator (#960)


Wäre gut, wenn du einmal einen Link zu der Seite posten könntest, damit wir uns das einmal ansehen können.

**Comment by Leuselator** [comment]
Schau bloß nicht in den code – hab das nur schnell zusammengestöpselt...
😉
LG Tim

Von: Gindi4711 <notifications@github.com>
Antworten an: dsiekiera/foe-helfer-extension <reply@reply.github.com>
Datum: Sonntag, 3. Mai 2020 um 02:54
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: Tim Leuschner <mail@leuselsoft.de>, Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Idea: grafischer Förderrechner /graphical investment calculator (#960)


Wäre gut, wenn du einmal einen Link zu der Seite posten könntest, damit wir uns das einmal ansehen können.

**Comment by Leuselator** [comment]
Ich mußte feststellen, dass viele Leute die Sache mit den Prozenten einfach nicht raffen – der Artikel im Erklärbär-Forum zu safe/unsafe/185% und der Rechner sind mein Versuch, das ganze etwas intuitiver verständlich darzustellen...

Ausserdem habe ich ein Förderprogramm für Archen in meiner Gilde am laufen, wo ich mit Hilfe von LevelRuns (10-xx Level hintereinander weg) versuche Externe rauszuhalten. Dafür gibt es eine Exceltabelle mit a bissel VBA-Code dahinter – die findest Du hier:

https://www.cookiecrew.de/?topic=levelruntabelle

Wenn man das in den FoE-Helfer integrieren könnte – wäre Spitze...



Von: Gindi4711 <notifications@github.com>
Antworten an: dsiekiera/foe-helfer-extension <reply@reply.github.com>
Datum: Sonntag, 3. Mai 2020 um 02:54
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: Tim Leuschner <mail@leuselsoft.de>, Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Idea: grafischer Förderrechner /graphical investment calculator (#960)


Wäre gut, wenn du einmal einen Link zu der Seite posten könntest, damit wir uns das einmal ansehen können.

**Comment by Leuselator** [comment]
OK - habe begonnen, das in meinem Fork umzusetzen...

**Comment by dsiekiera** [comment]
Wenn du Fragen dazu hast, komm zu uns auf den Discord. Wir helfen dir weiter.

**Comment by Leuselator** [comment]
Channelname?

**Comment by dsiekiera** [comment]
https://discord.gg/z97KZq4
