### ISSUE TITLE
BUG - soma de custos das tecnologias

### ISSUE THREAD

**Issue by Dtarg-FoE** [dsiekiera/foe-helfer-extension#961]
A tecnologia "comunicação quântica", (era futuro) não esta incluída na soma dos custos. 
Esta tecnologia esta ausente da soma.

![BUG](https://user-images.githubusercontent.com/64720616/80899021-3270b980-8ce1-11ea-89e1-43146137a387.png)

**Comment by andrgin** [comment]
This technology is excluded because it is an optional technology that you do not need to research to finish this age.

**Comment by outoftheline** [comment]
we have checkboxes now to include dead ends aswell
