### ISSUE TITLE
Idea: download battleground stats for guild admins

### ISSUE THREAD

**Issue by Rasnus** [dsiekiera/foe-helfer-extension#966]
Hello, it would be very helpful for guild admins to be able to download a csv with the stats of the guild at the end of each battleground.
By stat I mean the number of battles/negotiations for each guild member, just as in the player overview that pops up in the battlegroud window.
The list is already available, it would be nice to be able to download the list to do some stats

**Comment by osv** [comment]
Hi, for your information, currently you can download any chart's data:
![download csv](https://user-images.githubusercontent.com/213405/80944921-4d335300-8df3-11ea-9eba-c231956290ad.jpg)

however, battleground stats have combined value (2*negotiations + battles).
Maybe this is what you need?

**Comment by Rasnus** [comment]
Hi, thank you for your reply, yes the stats are a great addition but they are only about me.
I wold like to create graphs on my guild members evolution through battlegrounds.
A downloadable txt or csv file with name,negotiations, battles would be great.

**Comment by osv** [comment]
"GBG players scoreboard" is about all players in your guild, @Rasnus

**Comment by Rasnus** [comment]
ok you're right.. I downloaded the excel, I can see a timestamp and the total number of batts/negs.. is there a way to see the number of negs and batts?

**Comment by Rasnus** [comment]
also, are the timestamps automatically generated or are they the times I opened the chart?

**Comment by osv** [comment]
each time you open in battleground detail window
![w](https://user-images.githubusercontent.com/213405/80949049-ed8d7580-8dfb-11ea-85e8-86a34e83c98c.jpg 

There are data in db for negs and batts but currently you can see only sum value. Want to know your use case, why you might need to know count of battles or negs, not score?

**Comment by Rasnus** [comment]
I just like to keep stats on my guild... Ideally I would like to be able to see when players are more active (time of day or night) to be able to better coordinate mass attacks.
It would also be useful to know what kind of action (batt/neg) players prefer in order to push to the guild the right help.
For instance, if we find that a low level player uses more negotiations, we can suggetst (and help) to develop more goods buildings.... the same for battles.
We area very collaborative guild and we're trying to get the most out of the players ;)

**Comment by scibuff** [comment]
The date/times are recorded only when you open the battleground leader-board. Yes, differentiating the fights, negotiations (and score) would be helpful.

**Comment by Rasnus** [comment]
ok so basically the stats are only providing a summary of the total score and no real timestamps of the fights/negotiations are available.
Anyway, even though we can't have timestamps, getting to know batts/negs would e fine

**Comment by scibuff** [comment]
Unfortunately, there's no way to record the stats unless you open the leaderboard window. I see no reason not to collect the number of fights and negotiations separately

**Comment by Rasnus** [comment]
ok no problem, I can open the leaderboard twice a day and get teh stats. It ouwld however be nice to get both negs and batts stats ;)

**Comment by outoftheline** [comment]
there is now a csv download option and you can also mark and copy the whole table
