### ISSUE TITLE
Improvement: Drag distance threshold

### ISSUE THREAD

**Issue by mtgtnt** [dsiekiera/foe-helfer-extension#968]
With no drag distance on the buttons in the menu, clicking in a hurry is a real pita. There is no allowed distance before drag is initiated. So if you click down, move even one pixel, click up, you do not open the window.

`// If difference is less than "n" - don't move`
`if (Math.abs(moveX) < o.moveDistance && Math.abs(moveY) < o.moveDistance) {`
`  return;`
`}`

This should get you on the track to adding this. I may be wrong with the code, I have not looked at the menu to see how its built.

**Comment by mtgtnt** [comment]
Had time today to view code and see you are using SortableJS/Sortable. Need to set the option fallbackTolerance.

----------------------
fallbackTolerance option
Emulates the native drag threshold. Specify in pixels how far the mouse should move before it's considered as a drag. Useful if the items are also clickable like in a list of links.

When the user clicks inside a sortable element, it's not uncommon for your hand to move a little between the time you press and the time you release. Dragging only starts if you move the pointer past a certain tolerance, so that you don't accidentally start dragging every time you click.

3 to 5 are probably good values.
----------------------

5 is the best to start with and probably wont need to be changed.

Line 251 of \js\web\_menu\js\_menu.js

**Comment by osv** [comment]
thanks, will try tomorrow

**Comment by mtgtnt** [comment]
How has the test gone?

**Comment by osv** [comment]
Hi, sadly this option only increase distance when drag is applied. It does not help click in hurry :(

**Comment by mtgtnt** [comment]
Strange. I have used this in a project I did a while ago. This was the option for how far the mouse cursor could move after down click and before up click and it would still trigger the click. When set to 5, user could begin the motion of dragging and if under 5 pixel movement it would act as a click. Once it moved 5 pixels it would now be in drag mode.

**Comment by osv** [comment]
I have used next:
```js
$('#ant-hud-slider').sortable({
            fallbackTolerance: 10,
```
I still cannot open window, but dragging icon

**Comment by mtgtnt** [comment]
When I find some time, I will see if I can find out why. It may be another option needs to be set along with it, but I dont remember there being one.

**Comment by osv** [comment]
You can test it. Just clone this repo or download. Goto chrome://extensions/
and remove foe-helper. Than load from directory by clicking **load unpacked**:

![ext](https://user-images.githubusercontent.com/213405/82123296-461c2580-97a1-11ea-949b-09af3187125b.jpg)

**Comment by outoftheline** [comment]
I think this has been resolved by now. If it hasn't, please feel free to create a new issue.
