### ISSUE TITLE
Kostenrechner Berechnungsfehler bei "Gleichstand"

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#97]
Moin,
gerade die neue Version ausgetestet, dabei durch Zufall dies entdeckt:
![Screenshot_2019-09-19_12-29-14](https://user-images.githubusercontent.com/17932878/65236593-3b59a580-dad9-11e9-945a-4870ee1be933.png)
In diesem LG wurde P3 mit 390 FP belegt und es sind noch genau 390 FP frei bis zum Leveln, trotzdem wird P3 aber vom Kostenrechner noch als verfügbar angezeigt.

**Comment by dsiekiera** [comment]
Schau ich mir an.

**Comment by dsiekiera** [comment]
Vorgemerkt für die nächste Version.
