### ISSUE TITLE
Wunsch: Eigenanteilsrechner für fremde LG / Powerleveln

### ISSUE THREAD

**Issue by Tsching-Foe** [dsiekiera/foe-helfer-extension#972]
Da ich viel mit Tauschpartnern spiele, wäre es klasse, wenn ich nicht nur den Kostenrechner für fremde LGs hätte, sondern wenn der Eigenanteilrechner auch für fremde LGs funktionieren würde. Mit einem Schalter vielleicht? Dann könnte ich überprüfen, wie viel ich noch einzahlen muss und wann das LG in die 1.9 kann. So schaue ich halt immer extra unter foe-rechner.de
Und vielleicht könntest Du du https://foe-rechner.de/invest/level auch irgendwie integrieren? Dann könnte ich für meine LG schon mal schauen, wie die nächsten Stufen aussehen.

Herzlichen Dank!

**Comment by Leuselator** [comment]
Da ist was in der Pipeline...

**Comment by andrgin** [comment]
1.) Der EA Rechner funitioniert grundsätzlich auch bei fremden LGs, ist aber nicht dafür freigeschaltet. Wer das trotzdem testen will kann folgenden Befehl in der Konsole eingeben (F12 -> Console):
UsePartCalcOnAllLGs = true

Es aber ein paar potientielle Fallen drin z.B. sieht man im EA Rechner nicht ob man selbst schon einen Platz belegt hat bzw. welches. Man wird also dazu verleitet z.B. P4 zu nehmen obwohl man schon auf P1 sitzt.

2.) Zum Thema Powerleveln ist etwas in Entwicklung.

**Comment by Tsching-Foe** [comment]
Sehr sehr cool!
