### ISSUE TITLE
City Map Lost

### ISSUE THREAD

**Issue by biljef** [dsiekiera/foe-helfer-extension#973]
accidentally dragged city map off the left side of screen and can't recover city map

**Comment by scibuff** [comment]
You have two options:

1) Open the browser console (F12) and type `$('#city-map-overlay').prop('style','top:0;left:0');` and hit enter (this will reset the city box to the top left corner)
2) Or in the settings scroll down and click `Delete!` under `Box Coordinates` (this will reset the coordinates for all your boxes)
