### ISSUE TITLE
Fußballevent: Anzahl der Schritte im Auswahlassistenten nicht korrekt

### ISSUE THREAD

**Issue by Andi47** [dsiekiera/foe-helfer-extension#979]
beim heute gestarteten Fußballevent ist anscheinend die Anzahl der Schritte, die der jeweilige Spieler macht, nicht korrekt: Im Assistenten sind die Schritte IMMER mit 1, 2 oder 3 angegeben; tatsächlich machen die Spieler aber bis zu 4 oder sogar 5 Schritte.

Link zum Screenshot: https://www.dropbox.com/s/hf05yhxt22sbb8i/Fu%C3%9Fball_Anzahl_Schritte.png?dl=0

Edit: Windows 10 home
Google Chrome Version 81.0.4044.138 (Offizieller Build) (64-Bit)
zz1 (Betaserver)
Extension Version 2.4.5

**Comment by andrgin** [comment]
Die Distanz in Schritten wird von Inno so übertragen und war auch bei allen vorherigen Soccer Events bisher immer 1,2 und 3 Schritte. Meiner Ansicht nach ist dies also ein Darstellungsfehler im Spiel selbst. Kannst du den Ball um 2. Spieler spielen (dem 93er) und einen Screenshot vom nächsten Abstoß posten. Meiner Meinung nach ist dieser ca. einen halben Grünstreifen zu weit weg eingezeichnet.

Was ewas verwirren ist:
Ein hell/grüner Streifen entspricht nicht einem Schritt, sondern etwas weniger. Wahrscheinlich wurde das gemacht, dass es nicht so offensichtlich ist, dass die Zahlen so simpel sind.

**Comment by Andi47** [comment]
leider nicht möglich, da ich seit dem Screenshot bereits mehrere Spielzüge gespielt habe.
