### ISSUE TITLE
City View STuck

### ISSUE THREAD

**Issue by PaulH111** [dsiekiera/foe-helfer-extension#981]
City Overview seems stuck on cavalier aspect and 100% ratio.  Both firefox and Chrome

**Comment by osv** [comment]
stuck? what do you mean?

**Comment by PaulH111** [comment]
The view des not change from cavalier and 100% - standard view and any other sizing does not work

________________________________

**Comment by osv** [comment]
Btw, "language" cannot be changed from settings, yes? it will be fixed in next release

**Comment by PaulH111** [comment]
On the webpage?  Correct

________________________________

**Comment by osv** [comment]
fix should be in next release

**Comment by PaulH111** [comment]
Thank you.  It used to work, so an update somewhere has screwed a line or two of coding!

________________________________
