### ISSUE TITLE
Player Profile

### ISSUE THREAD

**Issue by Caellum249** [dsiekiera/foe-helfer-extension#984]
Could we have a Player Profile page where it details the other worlds a player plays in and their activity level I know this happens in other InnoGames, games such as Grepopolis. It would be really useful for guild leaders when reviewing how active someone is.

**Comment by andrgin** [comment]
If the other player does not have the extension installed it is impossible for us to get this information.

I suggest using https://foestats.com/
They have been whitelisted by Inno so they are allowed to make requests to the Inno servers directly.
