### ISSUE TITLE
Bug: Kostenrechner ausblenden

### ISSUE THREAD

**Issue by b-tomasz** [dsiekiera/foe-helfer-extension#986]
Ich kann ein fenster ausblenden, wenn ich nochmal auf den entsprechenden Button klicke. Nur beim Kostenrechner funktioniert dies nicht. Evtl. weil es 2 Fenster sind.
Ich fände es super wenn man das beheben könnte.

Beispiel / Example:
Windows 10 64 Bit
Firefox 75.0
de16 (Tuulech)
2.4.5 - Deutsch

**Comment by andrgin** [comment]
Der Kostenrechner hat seine eigene Logik für den Öffnen/Schließen Button je nachdem welche der 2 Fenster geöffnet sind, ob Übersicht und Details zum selben Spieler gehören bzw. wenn nein welche Daten davon neuer sind.
