### ISSUE TITLE
Verbesserungsvorschlag: PvP Aktivitäten Anzeige-Filter

### ISSUE THREAD

**Issue by frank42hh** [dsiekiera/foe-helfer-extension#988]
Moin,

für effizientes Nachbarn-Ärgern ist die Liste der PvP Aktivitäten schon sehr hilfreich. Richtig spannend wäre es meines Erachtens, wenn man - ähnlich wie in der Infobox - eine Liste von Filtern hätte, in der man die Anzeige der PvP Aktivitäten auf "Nur Plünderungen", "Nur Kämpfe", "Nur gewonnene Kämpfe" und "Nur verlorene Kämpfe" beschränken könnte. Gerade letzteres würde helfen, dass man nicht mehrmals den gleichen Fehler macht :)

**Comment by andrgin** [comment]
Die PvP Aktivitäten wurden entfernt: https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/115
