### ISSUE TITLE
Wish: GB charges left

### ISSUE THREAD

**Issue by mibowyer** [dsiekiera/foe-helfer-extension#989]
It would be awesome to have a way to see how many charges a GB has when in GbG or GE window. For example, the Space Carrier has x number of charges (depending on level) for diplomatic gifts. This icon disappears when going into the GbG/GE screens. Therefore, I never know how many charges I have left without having to go back to main city view.

**Comment by scibuff** [comment]
Nice idea. In a way, this would be similar to the extra negotiation step countdown that shows up in GE (when the extra step has been activated in the tavern)

**Comment by andrgin** [comment]
Released in 2.5.0
