### ISSUE TITLE
Supply Production is Incorrect for Non-Boostable Buildings (i.e. all buildings that can be motivated)

### ISSUE THREAD

**Issue by Minotorious** [dsiekiera/foe-helfer-extension#994]
The supply production menu in the Production Overview calculates boosted production for buildings for which the boosts don't apply.

e.g. as in the screenshot below, the Production Overview shows my Winter Spire will produce 18865 Supplies when it actually produces 4110 instead.

![Screenshot (18)](https://user-images.githubusercontent.com/40427380/81474040-46e21400-9203-11ea-9065-95099eeb83a6.png)

**Comment by andrgin** [comment]
This is because the ingame tooltip is wrong. Coin and supply boosts apply to residential and production buildings.
