### ISSUE TITLE
Identifikation Straßentyp

### ISSUE THREAD

**Issue by fuxi2000** [dsiekiera/foe-helfer-extension#995]
Wenn angezeigt wird auf welcher Art Straße ein Ereignis erscheint, kann es schnell gefunden werden.

**Comment by andrgin** [comment]
Wir zeigen schon an, ob es sich um eine schmale (1 Feld) oder eine breite Straße (2 Felder) handelt. Mehr Information wie die Stelle an der sich die Straße befindet bekommen wir auch nicht.
