### ISSUE TITLE
Hidden rewards not showing correctly

### ISSUE THREAD

**Issue by matrmatr** [dsiekiera/foe-helfer-extension#996]
here is screenshot of 3 rewards on large road and FoE Helper only lists 2 of them
http://prntscr.com/sdpz6z

**Comment by andrgin** [comment]
What we are doing is displaying the list the Inno server sends to the browser. We have no influence if this list is correct or not, but in most cases it is.

**Comment by Th3C0D3R** [comment]
Did you try to scroll down and see if an upcoming hidden reward is this tree?

**Comment by matrmatr** [comment]
Thank you, sorry did not scroll down to see if there was an upcoming reward that matched, I believed I was at the end of the list, will try again in the future. Overall, FoE Helper is outstanding
